### ISSUE TITLE
Cold/Flu: "Don't see my worksite"

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1002]
User Story
If the user does not see their Ministry and City pair, the user will click on "Don't see my worksite" button. On button click, the new worksite registration form will show

Tasks
- [x] Create button on form
- [x]  Create logic for button to show/hide "Register New Worksite Form" component
- [x] Test to ensure that the new worksite component show/hides on click

Acceptance Criteria
The form details for new worksite shall show/hide on button click

**Comment by bhumin-fw** [comment]
Ready to review on DEV environment.

**Comment by ayushdamani** [comment]
Tested and verified!
- 'Don't see your worksite?' button works.
- Once clicked, "Register New Worksite Form" component appears.
- The component can be shown/hidden as clicked.

**Comment by chriscaldwell-psa** [comment]
I tested the button as well. Works great!

**Comment by Stella-Archer** [comment]
sweet can we move this to test?

**Comment by chriscaldwell-psa** [comment]
PO approved closed. Chris
