### ISSUE TITLE
Cold/Flu: Open or Closed Clinic Justification Box & Tooltip

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1004]
User Story
If a user selects "Closed" for the clinic type "Is this an open or closed Clinic?" a textbox (long free text) should appear asking the user to provide justification.

A tooltip to explain what Open and Closed mean.

Tasks
- [x] Confirm open and closed definition with Heather
- [x]  Conditional logic to show textbox if openClosed is true
- [x] Create tooltip in json form
- [x] Add tooltip to front end 

Acceptance Criteria
Tooltip appears on button click and closes when user clicks away
Justification for closed clinic appears when user selects "Yes" for the input "Is this an open or closed Clinic?"

Details: 
Tooltip popup should display:

"Open Clinic is open to all GOV employees. Most clinics should be Open unless, due to safety and/or security reasons, it is not feasible for other GOV employees to access. If you select Closed Clinic, please provide an explanation to help us process your request."

**Comment by bhumin-fw** [comment]
@chriscaldwell-psa I have deployed backend and fronted to support tooltip in select component.
Please review it on your end let me know if anything is missing. If looks good feel free to move ticket forward.

**Comment by chriscaldwell-psa** [comment]
Below are screen shot confirming all criteria has been met: 
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/322a9be9-5678-4bce-a342-9544cb5bb5bb)

![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/53f502a5-00b0-48da-be6a-d3d753053d42)

**Comment by ca-liu** [comment]
Hi @chriscaldwell-psa 
Thanks for the QA! Apologies, I forgot to specify that the Reason box is Mandatory if Closed clinic is selected. Could we please add logic to ensure that the box is not empty?
Thank you!

**Comment by Stella-Archer** [comment]
@chriscaldwell-psa I'm not sure how to test this one please let me know

**Comment by chriscaldwell-psa** [comment]
@Stella-Archer , @ca-liu;  I updated the field validation to required -   Thx Chris , In summary: Bhumin added automation to have the Reason box appear if field value is 'Closed', the field that appears is now mandatory, prompting a user for a value.

**Comment by ca-liu** [comment]
Thanks @chriscaldwell-psa! 
I don't have the source code to test in localhost; perhaps Stella can confirm / test?

**Comment by ayushdamani** [comment]
Tested and verified. 
- The justification box appears when 'Closed' is selected as the field value for 'Is this an open or closed Clinic?'.
- The justification box is mandatory and requires an input from the user before submission.

**Comment by Stella-Archer** [comment]
Looks great thanks all I think we can close this
