### ISSUE TITLE
Cold/Flu: Tooltip for "Will the team be relocating?"

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1005]
User Story
A tooltip to explain what relocating means and the reason behind asking this question.

Default value is no
Popup box

Tasks
- [x] Confirm relocating definition with Heather
- [x] Create tooltip in json form
- [x] Add tooltip to front end (onClick)

Acceptance Criteria
Tooltip appears on button click and closes when user clicks away

Details:
Tooltip popup should say:
"If there are plans for your worksite location to change between the time you register and the end of the flu clinic period (December), please select Yes."
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/2925a8b4-9cb8-4d51-954e-d225317e67f7)

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/7f59523b-dccc-4d6f-8599-c965dc6bdb8e)

**Comment by bhumin-fw** [comment]
@chriscaldwell-psa I have deployed backend and fronted to support tooltip in select component.
Please review it on your end let me know if anything is missing. If looks good feel free to move ticket forward.

**Comment by chriscaldwell-psa** [comment]
The tool tip looks great!  No changes required. 
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/f8a25b36-04d8-40a7-91a6-856c2f49617e)

**Comment by ayushdamani** [comment]
Tested and verified.
The tool tip appears when clicked on '?' button, and closes when clicked outside.

**Comment by Stella-Archer** [comment]
Looks terrific - closing ticket!
