### ISSUE TITLE
ODS APIs: Request for new endpoints for cold-flu

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1010]
In the cold/Flu form we required new data from the warehouse. 

For the same required below endpoints from ODS system,

**GET**: List all the **clinic**s with detail data (filter and sorting is required, we will use filter to fetch single click data too)
**POST**: Add new **clinic** data
**PUT/PATCH**: Update details to existing **clinic**.

**Optional**:
GET: Audit list (Need this details to show what data has been added by whom and who made changes to it)

**Comment by T854236** [comment]
@bhumin-fw 

Can you share what fields you need?  I see a Clinic table in the database.

**Comment by T854236** [comment]
@bhumin-fw 

My email is patrick.senaphanh@telus.com.

**Comment by bhumin-fw** [comment]
@T854236 I'm not sure who will grant access.
Could you please share what access Mike needs to start work on this? I can share the same detail with Alison and we can try to provide required access to Mike in a day or two.

**Comment by T854236** [comment]
@bhumin-fw 

If you can allow him to get access to the project github similar to me so that he can contribute as needed.  I believe you only need his github ID.  If you need anything else, let me know.

**Comment by mikeshitelus** [comment]
@bhumin-fw 

My email is:  mike.shi@telus.com

Please share the required fields with me as well, thx

**Comment by mikeshitelus** [comment]
@T854236 
Received, thx

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
Hie Mike please do let me know if you have any update on this for me. I would love to see if anything ready so I can kick start on my end.

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 

Hi Bhumin, Don did let us know in yesterday's BI meeting that they will do some re-model work (normalization vs denormalization ), for better serve API, we are waiting for their update.

**Comment by T854236** [comment]
@bhumin-fw @mikeshi-bcgov 

I believe we are waiting for the revised schema of the DB from Don.  Mike can you confirm?

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 

May I have your email address? thx

**Comment by bhumin-fw** [comment]
sure @mikeshi-bcgov 
bhumin.patel1@ca.ey.com

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov Please see below Image, we need GET endpoints for ministry, city and worksite to kick start form. (other endpoints we can chat in tomorrow's call or book some additional time)
![influenza.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/bd0e9517-3c57-41a3-875c-3d9dfe1869c1)

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 

3 endpoints are ready for your testing

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
I did share an email about some remain endpoints.
Please do let me know if you have any query for the same.

For changes that required in form data key in the POST and PUT clinics/registrations, we will add new ticket or discuss those in other tickets.

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 
You may have noticed from Don's email, that Karla is reviewing the new schema, will provision endpoint once she is ok with the schema design

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov Just saw that email. No worries, Let me know once you get go ahead on this.
Thank you so much for quick update and detail on call today.

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 

Based on the current version of ERD, API endpoints for all tables have been created as below, "telework" has GET/POST/PUT/DELETE permissions, please let me know what else you need.

https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_contacts/

https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_ministries/

https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_registrations/

https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_worksites/

https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_worksite_ministries/

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 

FYI: The old API endpoints based on the legacy schema have been removed:

ODS_Datamart_influenza_ministry
ODS_Datamart_influenza_city
ODS_Datamart_influenza_worksite

**Comment by bhumin-fw** [comment]
We can close this ticket, We have one ticket #1000 in place to work on API endpoints. We did receive required endpoints here now we have to align with form and data only.
