### ISSUE TITLE
Cold/Flu: Privacy Impact Assessment (PIA)

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1011]
A PIA is required to be signed off before go-live

Tasks
- [ ] Receive updated PIA for Digital Journeys specifically for Cold/Flu
- [ ] Submit PIA to Privacy team
- [ ] Get PIA sign off

Acceptance Criteria
PIA is signed off by privacy team to move forward with go-live.

**Comment by NassNK** [comment]
PIA has been updated to remove sect. 12 and has been sent back to Jennifer for final review and signatures.

**Comment by ca-liu** [comment]
PIA Follow up meeting scheduled for Thursday April 27 to review:
- PIA document (what is required)
- How we can add Google Maps to the program PIA
- Approvals workflow

Attendees: Heather, Jonathan (Privacy), Nass, and Caleb

**Comment by MeghanStothers** [comment]
@NassNK  @ca-liu hello there- can you give an update on this one? We will be meeting with Heather tomorrow to go over all the pieces needed for launch.  Do you expect any issues? The Google map work is not in scope for launch. Thanks

**Comment by ca-liu** [comment]
Hi @MeghanStothers ,

We are meeting with the Privacy team tomorrow afternoon to go over the PIA. Will update the ticket after the meeting.

Thanks,
Caleb

**Comment by MeghanStothers** [comment]
@Caleb - thank you! I know it's with the pros and on your radars for launch.

**Comment by Stella-Archer** [comment]
Heather is just confirming last details with health serve contractor already with Privacy Office

**Comment by MeghanStothers** [comment]
Closing this ticket as Heather indicated to Stella and Meghan via email the PIA is complete. With thanks for working on this key piece.

**Comment by MeghanStothers** [comment]
[Thursday 2:50 p.m.] Bishop, Heather PSA:EX

Hi! If I haven't already provided it - the PIA # for C&F is PSA23017

it is with the PO for sign off still.
