### ISSUE TITLE
Add an additional BMP workflow to remind mangers/employees  that a form submission will be soon be deleted.  

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1014]
Current state - forms are deleted after 60 days in the formsflow portal with no reminder email is sent  informing employees/managers of this action. 

New Feature Request: For managers that are not able to approve a form within the 60 day window due holidays or busy workload, we will send a courtesy follow-up email informing them that the 'said' form is about to expiry  by certain date, or within 1 week. Exact wording and timing can be discussed at scrum.

Objective Key  Result:
1) to minimize emails received in the Digital Journeys emails of expired telework links or possibly other form links.
2) to send a friendly reminder or courtesy email  that a form is about to purged from our system that will require it to be resubmitted by the employee.

**Comment by iman-jamali-fw** [comment]
Good idea to split this ticket for each form.

**Comment by fazil-ey** [comment]
We are going to increase 60 days to 365 days for telework #1695
We are also planning to send reminder emails for approvals #1485

These two will address the issue that forms are deleted before the supervisor is able to approve it.
