### ISSUE TITLE
Cold/Flu: Roles & Roles Controller

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1015]
**User Story**
The form requires roles-based functions (admin). The management of admin list will be on Digital Journey (manual edit / change of admin personnel ) via Keycloak

The Admin would have the access to:
- Read submissions (all submitted forms for the year)
- Create submissions (blank contact)
- Edit submissions
- Delete submissions

**Tasks**
- [x]  Add isAdmin row to Contacts table
- [ ] Add Admin permissions logic to form

**Acceptance Criteria**
- Admin will have access to form when intake period is closed
- Admin can view and edit all form submissions in the Submitted Forms tab

**Comment by EduardoRamirezBC** [comment]
Is this MVP?
Keycloak?

**Comment by ca-liu** [comment]
While Roles is Mandatory for launch, Roles controller (adding, removing, editing of roles) can come post go-live.

**Comment by Stella-Archer** [comment]
to open close forms and send notification are tasks that can be handled by KeyCloak by a forms designer #1023
