### ISSUE TITLE
Issue: Telework Agreement - Employees who haven't yet logged into PeopleSoft receive Null GUID Values

### ISSUE THREAD

**Issue by Abuchana** [bcgov/digital-journeys#1018]
A CRM ticket came in today (230316-000705) asking about several employees with approved telework agreements who were not appearing in the reporting.

This appears to be a separate issue to the known NULL IDIR/Schedule issues that are already being tracked.

This issue is so far only affecting ~180 records. No data has been lost, but the fields that are normally calculated within the BI using GUID are currently blank. Employee ID is one of the affected fields, which is why these employees are not appearing in the reports.

Justin has investigated and, in brief, it looks like the issue is occurring when an employee creates a telework form prior to logging into PeopleSoft for the first time. Under the current architecture, the BI will not have a record of an employee’s GUID until after they have logged into Peoplesoft at least once. 

TES can do a one-time fix, but the problem will reoccur unless changes are made moving forward. There are several approaches that could be taken within the BI to address this moving forward – some higher effort than others. However, I wonder if there might also be a solution that could be applied at the front-end, form level (e.g., could employees who have not yet logged into PeopleSoft receive an error message instructing to them to try again after they have logged into PeopleSoft).

**Comment by MeghanStothers** [comment]
Warren proposed error message and link to ESS - sees this could affect other forms. 
- if employee ID is missing could we check for that on the DJ side? Or could we query ODS? Or give People a link to login to PeopleSoft.
Can we allow these submission to go-through and get notified. 
 Iman - noted one issue it's hard to detect on the DJ side. Long term solution is likely with the ODS side - several approaches we could pursue. 

Next steps: Meeting with ODS team to review solution also find out what is missing on front-end (employee ID or other field?)

**Comment by MeghanStothers** [comment]
@T854236 welcome back, Patrick. Can you email a few times when you'll be available to discuss? We'll also need a few other folks to map out a quick solution and map out longer-term work needed for all forms.

**Comment by MeghanStothers** [comment]
This is mostly a reporting issue that affects people who have not signed into Peoplesoft yet. The short-term fix has been deployed to prod by Justin. We should watch reporting as this should reconcile.
This issue will affect new employees who have not signed in, and also those people from other organizations that are not connected to PeopleSoft.  (Such as some agencies, boards who want to use the Telework form or others). board. This issue will also affect other forms besides Telework. We don't have a source of truth or organizational list.
A few ideas tabled:  Do we have any policies that address these types of users/use cases?  
(Next steps: connect with Sarah/Steven Jones to give an update and talk about this unresolved issue. and map out possible fixes/technical work for tool/form).

**Comment by MeghanStothers** [comment]
This is mostly a reporting issue that affects people who have not signed into Peoplesoft yet. The short-term fix has been deployed to prod by Justin. We should watch reporting as this should reconcile.
This issue will affect new employees who have not signed in, and also those people from other organizations that are not connected to PeopleSoft.  (Such as some agencies, boards who want to use the Telework form or others). board. This issue will also affect other forms besides Telework. We don't have a source of truth or organizational list.
A few ideas tabled:  Do we have any policies that address these types of users/use cases?  
(Next steps: connect with Sarah/Steven Jones to give an update and talk about this unresolved issue. and map out possible fixes/technical work for tool/form).

**Comment by MeghanStothers** [comment]
See #1038 for next steps to connect with Steven Jones/Sarah/BP.
The initial fix has been deployed. This ticket can be closed

**Comment by MeghanStothers** [comment]
Adding some earlier notes from Iman as we look for a longer-term solution on this one: Ideas to fix the missing ODS info for IDIR users:
•	Warning message: Display a warning message to the form users who do not have a PeopleSoft account. The message can inform them about the need for a PeopleSoft account to complete certain actions.
•	Prompt to login: Prompt users to log in to PeopleSoft if they do not have an account and come back after data is updated (may take days).
•	Flag field: Add a flag field in the form submission to indicate users without a PeopleSoft account. This can help with tracking and sorting users based on their account status.
•	IDIR data fallback: Use IDIR data as a fallback to populate user data. This can provide basic data (e.g., first/last name, email ) to help with completing forms and other actions.
•	Stop form submission: Prevent users without a PeopleSoft account from submitting forms. This can help ensure that only users with valid accounts can complete the required actions.
•	Require Employee ID field in the forms : Ask for the employee ID if the forms. This can help the reporting team to link the user to their PeopleSoft record when they create an account.
•	Repopulate form with PeopleSoft data: If there is a conflict between the data entered by the user and what is in PeopleSoft in draft or in a new submission, provide a notification and link the user to PeopleSoft to fix the information.
I will also add these notes to ticket #1038 - thanks Iman!

**Comment by Stella-Archer** [comment]
closed with new ticket #1038
