### ISSUE TITLE
Cold/Flu: Workflow setup (Edit in submission state)

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1024]
When the form submit, It should have workflow that attach some actions.

On Form submit:
- Send data on data warehouse API (create request).
- Send an Email to admin or provided user about new registration. (need to setup email template as well recipient email)
- Keep Form status "Resubmit/Submitted" so it stay editable.

On Form resubmit:
- Send data on data warehouse API (update request).
- Send Form data + old form data to webAPI, It will identify change and prepare mail for admin.

Note: This ticket only build to setup workflow. Add/update data is part of other ticket [#1007](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1007) and [#1000](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1000)

Acceptance Criteria:
- Form submit and trigger data warehouse clinic api (POST) with form data.
- In Edit Form it should submit form data to data warehouse with PUT/PATCH request.
- Keep the Form in Edit mode.

**Comment by EduardoRamirezBC** [comment]
Needs estimate

**Comment by EduardoRamirezBC** [comment]
Stella / Caleb will provide feedback to Bhumin.

**Comment by ca-liu** [comment]
Hi @bhumin-fw ,

Thank you for summarizing the workflow. Please see comments below in red bullet;:

**On Form submit (NEW form):**
- Send form data to data warehouse API (create request).
- Send an Email to admin or provided user about new registration. (need to setup email template as well recipient email) - this will only trigger when the form is closed (please see ticket #1023
- Keep Form status "Resubmit/Submitted" so it stay editable. 
![#f03c15](https://placehold.co/15x15/f03c15/f03c15.png) `Clarification` The Registrations table will contain submittedDateTIme and lastModifiedDateTime

**On Form resubmit (EDIT form):**
- Send data on data warehouse API (update request).
- Send Form data + old form data to webAPI, It will identify change and prepare mail for admin.
![#f03c15](https://placehold.co/15x15/f03c15/f03c15.png) `Clarification` This is only required when the form is closed. Please capture the changes and send via email. Please see comments on ticket #1007 for submission change email notification template.
- Note: This ticket only build to setup workflow. Add/update data is part of other ticket #1007 and #1000

**Acceptance Criteria:**
- Form submit and trigger data warehouse clinic api (POST) with form data.
- In Edit Form it should submit form data to data warehouse with PUT/PATCH request.
- Keep the Form in Edit mode.
![#f03c15](https://placehold.co/15x15/f03c15/f03c15.png) `Clarification`  In edit mode, please still follow input restrictions (e.g. cannot manually change contact name - as seen in mockup)

**Comment by ca-liu** [comment]
Hi @bhumin-fw ,

Thank you for summarizing the workflow. Please see comments below in red bullet;:

**On Form submit (NEW form):**
- Send form data to data warehouse API (create request).
- Send an Email to admin or provided user about new registration. (need to setup email template as well recipient email) - this will only trigger when the form is closed (please see ticket #1023
- Keep Form status "Resubmit/Submitted" so it stay editable. 
![#f03c15](https://placehold.co/15x15/f03c15/f03c15.png) `Clarification` The Registrations table will contain submittedDateTIme and lastModifiedDateTime

**On Form resubmit (EDIT form):**
- Send data on data warehouse API (update request).
- Send Form data + old form data to webAPI, It will identify change and prepare mail for admin.
![#f03c15](https://placehold.co/15x15/f03c15/f03c15.png) `Clarification` This is only required when the form is closed. Please capture the changes and send via email. Please see comments on ticket #1007 for submission change email notification template.
- Note: This ticket only build to setup workflow. Add/update data is part of other ticket #1007 and #1000

**Acceptance Criteria:**
- Form submit and trigger data warehouse clinic api (POST) with form data.
- In Edit Form it should submit form data to data warehouse with PUT/PATCH request.
- Keep the Form in Edit mode.
![#f03c15](https://placehold.co/15x15/f03c15/f03c15.png) `Clarification`  In edit mode, please still follow input restrictions (e.g. cannot manually change contact name - as seen in mockup)

**Comment by MeghanStothers** [comment]
@bhumin-fw Hi Bhumin - can you give an update on this ticket?

**Comment by bhumin-fw** [comment]
Workflow with name "Influenza Worksite Registration" has been setup on DEV.
Right now ODS APIs attached to this workflow fails with 500 error, Due to that it's not been attached it with "2023 influenza worksite registration" form.

**Comment by bhumin-fw** [comment]
@chriscaldwell-psa Please do let me know if you have any query on workflow. You can test data with Mike Shi on PSA side to review data inserted successfully or not.

**Comment by chriscaldwell-psa** [comment]
@bhumin-fw Thanks Bhumin, I was away on holidays all last week (catching up now)  and will connect with you tomorrow when you return re this. Chris

**Comment by EduardoRamirezBC** [comment]
Iman / Bhumin will review this ticket . (In progress?)

**Comment by bhumin-fw** [comment]
@MeghanStothers Workflow has been setup. I'll work on this today afternoon. Let me move it back to in-progress for better visibility. I'll work on change workflow based on new update on #1000.

**Comment by Stella-Archer** [comment]
@chriscaldwell-psa How would I test this is it just noting that my test submissions end up on Dons reports?

**Comment by Stella-Archer** [comment]
Yes that worked great thanks @bhumin-fw !
PO approved and Closing ticket
