### ISSUE TITLE
Cold/Flu: Delete form submission - Logic

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1025]
As a user I want to delete a submitted form request.

Delete form submission required to handle separately, as Delete needs to enable for selected Forms only. 
In Cold/Flu form, data needs to soft delete from data warehouse.
To do so, Delete submission needs to handle separately, it will remove form entry and send DELETE request to data warehouse APIs.

Acceptance Criteria:
- Delete submitted form
- Soft delete data on data ware house by triggering DELETE api endpoint.

**Comment by iman-jamali-fw** [comment]
@ca-liu @fazil-ey @bhumin-fw 

We currently don't have to delete the submitted form functionality. However, there is similar functionality for drafts.![Screenshot 2023-04-25 at 11.54.00 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/1a09bd60-d68a-41a6-a69b-b2eed06ba180)![Screenshot 2023-04-25 at 11.54.05 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/354768c8-bef9-45fa-9530-20136bd993cb)


This ticket only covers the logic side of the work that includes
- Deletion from DGJ DBs
- Delete from the warehouse

There is another piece of work, **the UI side** that should clear how the delete submitted form functionality is added, and also clarify the compatibility of deleted submitted forms with other forms (SL Review, Mat/Pat). Do we want the delete only to be enabled for Cold/Flu submissions or for all? 

I'd suggest another ticket for UI and use this ticket to track the logic.

**Comment by iman-jamali-fw** [comment]
related Mike's comments from #1000 are to be continued in this ticket:

> Endpoint for registration soft deletion is now available:
> HTTP POST (https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_delete_registration/)
> 
> var postdata = { "application_id": 1};
> 

> Yes, the "deleted" registrations will be ignored from endpoint /ods_datamart_influenza_vw_registrations_worksites_joined. As for endpoint /ods_datamart_influenza_registrations/, because it is directly with table, you need to apply filter "deleted_ind Eq null"

**Comment by ca-liu** [comment]
> @ca-liu @fazil-ey @bhumin-fw 
> 
> We currently don't have to delete the submitted form functionality. However, there is similar functionality for drafts.![Screenshot 2023-04-25 at 11.54.00 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/1a09bd60-d68a-41a6-a69b-b2eed06ba180)![Screenshot 2023-04-25 at 11.54.05 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/354768c8-bef9-45fa-9530-20136bd993cb)
> 
> 
> This ticket only covers the logic side of the work that includes
> - Deletion from DGJ DBs
> - Delete from the warehouse
> 
> There is another piece of work, **the UI side** that should clear how the delete submitted form functionality is added, and also clarify the compatibility of deleted submitted forms with other forms (SL Review, Mat/Pat). Do we want the delete only to be enabled for Cold/Flu submissions or for all? 
> 
> I'd suggest creating another ticket for UI and using this ticket to track the logic.

Hi @iman-jamali-fw ,

Thanks for the note. My understanding is that for the FE side of things, we just need to add a button element to the submitted forms table so it will dynamically load for each table row. It will function exactly the same as the button on the draft forms table.

Then add an onClick event handler to POST method to the backend that Mike created to delete the record from both the digital journey and cold/flu database.

Happy to create a FE ticket for a delete button / link creation if required.

Also, I cannot speak to other forms. The delete function we are requesting is strictly for cold/flu form.

**Comment by iman-jamali-fw** [comment]
@ca-liu 
Thank you for creating the UI ticket, I think that helps to move this ticket forward and avoid blockers.

@mikeshi-bcgov
The delete endpoint works great! I'm able to delete a registration by application_id. The deleted entry is also removed from `ods_datamart_influenza_vw_worksites_ministries_joined` by default and removed by filter `deleted_ind Eq null` at `ods_datamart_influenza_registrations` endpoint. Thank you

**Comment by iman-jamali-fw** [comment]
@ca-liu 

Is this delete request only limited to the regular users deleting their own requests or there is a requirement for the admin to be able to delete other users' requests?

**Comment by ca-liu** [comment]
Hey @iman-jamali-fw , thanks for seeking the clarification.

You are correct - registrants should be able to delete their own submissions AND admins should be able to delete ALL submissions.

My understanding is that currently, the submitted forms does filter to only show the user's submitted forms. This just leave the admin piece that required some roles validation.

**Comment by ca-liu** [comment]
Hey @iman-jamali-fw , thanks for seeking the clarification.

You are correct - registrants should be able to delete their own submissions AND admins should be able to delete ALL submissions.

My understanding is that currently, the submitted forms does filter to only show the user's submitted forms. This just leave the admin piece that required some roles validation.

**Comment by iman-jamali-fw** [comment]
@ca-liu 

Thank you for the clarification. I suggest keeping the scope of this ticket to a user who can delete their own submissions and create a separate ticket for the admin piece if that makes sense.

**Comment by iman-jamali-fw** [comment]
Progress:
- **Delete submission from the warehouse: Done**
- Delete submission from webApi PostgresDB: in-progress
- Delete submission from Formio MongoDB: in-progress

**Comment by iman-jamali-fw** [comment]
Please wait for #1067 Delete UI ticket and test them both together.

**Comment by ayushdamani** [comment]
Tested along with #1067 - can confirm this is working.

**Comment by Stella-Archer** [comment]
#1067 has been tested PO reviewed and closed - @Iman how do I confirm this worked here?
here's a screen shot of the successfully deleted form ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/a7804c07-5b3c-4b48-bbc0-04a498898c36)

**Comment by Stella-Archer** [comment]
all delete file are gone PO approved & closing tix
![F4B35002-4530-489A-AF3F-03299404B136.GIF](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/b5498ede-88f2-4584-89d4-c38731b42c1d)
