### ISSUE TITLE
Mat/Pat - Explore pdf generation for wizard forms on server side

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1046]
For mat/pat, we need to generate pdf of the form to attach to emails. 

- Explore how pdf generation works for wizard forms
- We _do not_ want all the pages of the wizard form to be in the email. For mat/pat we only want the Review page & the Certification page to be in the attachment.

**Comment by Stella-Archer** [comment]
email ticket is #874

**Comment by bhumin-fw** [comment]
@fazil-ey 
I'm attaching PDF that we will be generating from Mat-Pat form and send over email.
Could you please review that and give your thought on it?
[https://app.zenhub.com/files/439477060/ac831539-2ca9-4fcb-90be-63644d3ced87/download](https://app.zenhub.com/files/439477060/ac831539-2ca9-4fcb-90be-63644d3ced87/download)

Note: In the same PDF you will see one error, ministry select is not a component. We can fix that as separate ticket.

**Comment by MeghanStothers** [comment]
Fazil will reply to confirm any issues. 

relates to #874

**Comment by fazil-ey** [comment]
@bhumin-fw 
Can we add the BC gov logo and form name, like we have for telework?

**Comment by bhumin-fw** [comment]
@fazil-ey 
It's not there in form itself.
In telework or sl review we have added header (logo + title). Same in not exist in mat-pat.

Now we have 2 ways to do this.
1. Add header log + title
2. Add script that hide logo+title in form and make it visible in PDF only.

Let me know your thought on this.

**Comment by bhumin-fw** [comment]
@fazil-ey It seems we need to explore wizard to put general header in it.
Although I have added logo+title in PDF. please review below PDF
[https://app.zenhub.com/files/439477060/4cd6dbe0-fc31-4256-980a-13da38e85bbb/download](https://app.zenhub.com/files/439477060/4cd6dbe0-fc31-4256-980a-13da38e85bbb/download)


Note: We need to add additional ticket to explore 
- Add Header for wizard forms (No placement for header is available in wizard, we can add all the data in first page of wizard form)
- RemoteSelect component is not display in PDF.

**Comment by MeghanStothers** [comment]
Bhumin to add a note and then Fazil could close this ticket

**Comment by bhumin-fw** [comment]
@fazil-ey Able to make code stable that works fine on DEV. Please consider above comment and PDF in review.
PDF contain header(logo+text), Wizard form does not display header(logo+form) so that needs to be handle separately if we want that(It must be handle with tab redesign ticket).


If it looks good, We can close this ticket.

**Comment by bhumin-fw** [comment]
@fazil-ey 

Please find attached PDF with updated details.
[https://app.zenhub.com/files/439477060/8e1b564b-01df-43a4-93d9-a78f7864cfc2/download](https://app.zenhub.com/files/439477060/8e1b564b-01df-43a4-93d9-a78f7864cfc2/download)
