### ISSUE TITLE
The submitter does not receive an email upon form submission if the email field is updated 

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#105]
**Background:** The submitter does not receive an email upon form submission if the email field is updated 

**Environment:** Dev

**Steps to Reproduce:**

1. Log in to the PSA-Digital-Journey portal with valid credentials.
2. Fill out the telework form.
3. Change the submitter email to a different valid email than the one you are logged in with. 
4. Submit the form.

**Actual Behavior:**  The user does not receive an email upon form submission if the email field is updated 

**Expected Behavior:** The user should receive an email upon form submission.

**Comment by HasanSifat** [comment]
Update- Carried one round of testing. 

- The employee email was changed from what was prepopulated for my work email to my personal email.

- filled out the rest of the form and made a submission.

- Received confirmation email of submission in personal email address

- Also received an attachment alongside a confirmation email of the filled-out form after manager approval was granted. 
![SS3.JPG](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/8ea7af3c-163f-4c84-b19b-673712a768c8)

*scheduled to carry out one more test to close out the issue if the test goes without any errors.

**Comment by Stella-Archer** [comment]
Changing the email address of either the Employee(Submitter) or the Supervisor worked in DEV the updated email was received by the new recipient

**Comment by Stella-Archer** [comment]
This works in test as well sending to the address of whom ever it's addressed and using the 'name' in the email as it it left (or not)
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/f63dab95-6e0f-4689-a263-fb7ca3b11e4e)
