### ISSUE TITLE
Mat/Pat - Icon for info & alert boxes should be in the top left corner

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1059]
- The icon for all warning/info boxes must be in the top left corner. Currently it is in the left centre. 

<img src="https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/eeca3714-946e-409e-910f-35842e662c49" width="20%" height="20%">
<img src="https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/17e324e5-a41b-4e96-8692-4310aa8e6227" width="10%" height="10%">

- Sometimes the spacing in the info boxes is also inconsistent. There is excess space between the icon and content
<img src="https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/85f71d84-990b-447e-af30-bf51d4c68cbc" width="50%">

**Comment by Stella-Archer** [comment]
@iman-jamali-fw could you give us and estimate for this?

**Comment by fazil-ey** [comment]
This is already done
