### ISSUE TITLE
Forms-flow-ai Roadmap explained

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1066]
This ticket review the forms-flow-ai roadmap, discuss the new feature, and provide some insights into how these features can impact DGJ![Screenshot 2023-04-25 at 11.22.25 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/963f03ba-b96c-418a-a60c-a2b1d47d10ee)

- Form versioning
    - Allow forms to be versions. Currently, we only version the workflow through the Camunda, this would enable us to teach the changes on the form and decide if the updated form should be effective for all the in-progress submissions or only new ones
- Form embedding
    - This will allow embedded DGJ in another website. Can be useful if a client want to include a DGJ (which has their form) in their own website
- Form Bundle

- Mobile app template
    - Will allow the web app converted to a mobile app that can be installed on mobile devices. As far as I know this is at early stages is mostly to view the forms.

- User administration
- Designer authorization

- Formsflow cloud
    - I think it should be a wrapper for deployment of the app on a the cloud, probably they have some cloud 
- Container monitoring
    - The whole system consists of multiple containers each representing portion of the app, for example website, api, DBs, PDF generator service and etc. This should allow for monitoring, possibly alerting the these containers in case something go off.

- Custom reporting template
- Predictive modelling
- Chatbot

- Opentelemetry

- Document management
- Document generator

- Micro frontend Phase 1
- Micro front-end Phase 2
    - These should split the front-end of the app into several more customizable, manageable pieces. Should allow for easier customization the client facing of the system

- BPM Abstraction layer
- Plug-n-play BPM engine
    - BPM is universal format for designing workflows and Camunda is one of the engines that can run these types of workflows. I think these new feature would enable to replace Camunda with another BPM management engine.

**Comment by Stella-Archer** [comment]
@iman-jamali-fw  Would 'Forms Versioning' allow us to see when, what and by who the last changes where made?

**Comment by iman-jamali-fw** [comment]
> @iman-jamali-fw Would 'Forms Versioning' allow us to see when, what and by who the last changes where made?

@Stella-Archer 
Sorry for my late reply. Yes, that will allow us that.
