### ISSUE TITLE
Mat/Pat - Add name of applicant in form name

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1070]
**Acceptance Criteria**
- [x] Mat/Pat forms should be named as "Maternity and parental leave form for *applicant name*" in draft forms and submitted forms

**Comment by fazil-ey** [comment]
@bhumin-fw the name should be "**Maternity and parental leave form** for applicant name" NOT "**Maternity, parental and **_pre-placement adoption_**** for applicant name"

cc: @ayushdamani

**Comment by bhumin-fw** [comment]
@fazil-ey form name was already set.
If "Maternity and parental leave form" is the updated on I can apply that. Or need to inform Chris or Andrew to make sure that existing name is not used anywhere so far.

**Comment by ayushdamani** [comment]
This has been updated ✅

![Screenshot 2023-06-21 090609.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/3e477b20-feca-4612-b3d1-a526a5f24cb4)

**Comment by fazil-ey** [comment]
name of form is correct in draft & submitted. Includes applicant name.  
![Screen Shot 2023-06-28 at 4.17.20 PM.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/c996aaa7-26da-4154-8172-8f8594f0f750)
![Screen Shot 2023-06-28 at 4.17.25 PM.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/f0e27a8d-b4ca-4390-aa5a-1ecca620e287).
