### ISSUE TITLE
Cold/Flu: Content Edits

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1073]
Tweaks to wording, and instructions missing from form.

For example, the contacts table after selecting the worksite only showed the contacts, there were no instructions/ wording explaining to the users what this means.

Action:
* [x] Heather is currently reviewing and creating edits
* [x] Heather/Stella/Caleb will add contents and screen shots of edits and where they need to be placed to this ticket

Text Changes/Inclusions:

* [x] **1.	Event:** User goes to register/search their worksite and another previously registered contact pops up for that worksite
**What happens:** Include visible text (not a tooltip)

“The contact(s) below have also registered at your worksite! We will work with all contacts registered at your location to schedule a clinic that works best for everyone, so please go ahead, and register your group.”

* [x] **2.	Event:** User searches their worksite and NO existing registrations come up.
**What happens:** include visible text

“There are currently no registered contacts at this worksite. We appreciate you registering as a worksite contact for this location.”

* [x] **3.	Event:** User reaches the Worksite Secondary Contact field
**Add:** Please include visible text 

“To help ensure your team gets the information they need, please include secondary contact information as back up for your work area."

**Comment by bhumin-fw** [comment]
@Stella-Archer @chriscaldwell-psa 
Changes are up on DEV and TEST

![Screenshot 2023-05-03 at 10.37.49 AM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/04165b66-59ec-4e03-9ea5-9a5049f7d271)

![Screenshot 2023-05-03 at 10.38.01 AM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/ef9aa253-ab58-46ca-bb1f-f3c57d3e8348)

![Screenshot 2023-05-03 at 10.42.35 AM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/cb725510-048c-4bef-911a-38704fb74d8c)

**Comment by ayushdamani** [comment]
Tested and verified in Dev and Test - working perfectly.
After testing each event, the visible text appears accordingly.

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/c9e36b55-2fb6-426b-aa1f-0f3153c9df9f)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/37ca4168-87de-4456-acf9-64709177dc3c)
