### ISSUE TITLE
Cold/Flu: Notification for Cold/flu admin users on every new registration

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1076]
AC:
As an admin Cold/flu user, I should expect to receive an email notification on every new registration after the registration period is closed.

Technical details:
- On new Cold/flu registration after registration is closed, emails need to be sent to all the admin users.
- fetch the "cold-flu-admin" user's email in form or workflow.

**Comment by Abuchana** [comment]
Related to #1023?

**Comment by Abuchana** [comment]
Duplicate ticket #1023
