### ISSUE TITLE
Cold/Flu: Admin can DELETE submitted forms

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1077]
AC:
As an admin Cold/flu user, I should be able to delete all the cold/flu users' submissions under the `Submitted Form` tab.

Technical details:
- submission data should be removed from all sources including webApi's PostgresDB, formio MongoDB and from the warehouse.

**Comment by Abuchana** [comment]
With the end-user edit function being available, this function is less critical and not MVP at this time.

**Comment by iman-jamali-fw** [comment]
@ayushdamani 

This is ready to be tested on TEST. For testing, please add yourself, `formsflow-client` and `cold-flu-admin` groups in Keycloak, and then you'll be to delete cold/flu submissions of other users.

**Comment by ayushdamani** [comment]
Tested and verified working ✔️
As an Admin, I was able to delete all the cold/flu users' submissions under the Submitted Form tab.

**Comment by MeghanStothers** [comment]
Tested and approved by PO
Closing ticket
