### ISSUE TITLE
Mat/Pat - Content Change - Employee Information Page 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1080]
**Context**

Need to make it clear that if information is missing an AskMyHR ticket still needs to be created. Also, need to make it clear that the applicant can proceed to the next step and fill out the form as they wait for the supervisor to create the ticket. 

-----------

Employee Information page 
>**Review you information** 
>
> Please review your information. If your information is incorrect or missing, ask your supervisor to update your information  by creating an AskMyHR Request under "My Team or Organization > Leave & Time Off > Maternity, Parental, Adoption" Incorrect or missing information can cause delays in the processing of your leave application.
> 
> **You can proceed to the next step before confirming**. However before submitting you must confirm your information is correct or that an AskMyHR service request has been created by your supervisor to correct the information. 

> (Radio button 1) I confirm that the information is correct
> (Radio button 2) The information is incorrect or missing. I confirm that my supervisor has submitted a service request with AskMyHR under "My Team or Organization > Leave & Time Off > Maternity, Parental, Adoption" to correct this information

[Design v3](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184517&cot=14)

**Comment by chriscaldwell-psa** [comment]
Dev Env, Mat/Pat -  Tab: Employee information page. Text has been updated. This ticket can be closed.

**Comment by MeghanStothers** [comment]
[DJ_content_edit.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3RUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3fb5ced3b8d5c3c730591f4957e199118ec6a523/DJ_content_edit.docx)

I have made suggestions in the attached based on keeping with webstyle/content guidelines followed by the writing team on the Careers & MyHR website, which is the bc gov site standard for accessibilities, consisitenct etc. 

As discussed this morning, we think it's ideal to make all content changes after UX testing sessions; Ideally all changes would be made at once. After the SME signs off on the content, Any further changes in content should be guided by this priority 
1) accuracy - content that is incorrect or misleading 
2) plain language/clarity 
3) consistency for usability/readability/plain (as possible)

**Comment by chriscaldwell-psa** [comment]
Thank you Meghan for beautiful editing! This ticket can be closed. Chris.
