### ISSUE TITLE
Cold/Flu - Registrant confirmation page and email upon submission

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1081]
**User Story**
As a registrant, I should see confirmation page and receive an email on submission, so that I know my submission was successful or not and any next steps if necessary. 

**Content**
TBD

**Acceptance criteria**
- [x] On form submission, the registrant sees a confirmation page with the mentioned content
- [x] If submission is not successful, the registrant should see a relevant error

**Comment by Abuchana** [comment]
Bhumin has the script from Heather and will use that as a base

**Comment by bhumin-fw** [comment]
Success page is a part of this story.
From Heather's email we found that we need to send confirmation email to user about their submission with same content.

It will be 3 story point. @Abuchana can we change its estimation to 3 from 2.

**Comment by Abuchana** [comment]
@bhumin-fw Changed to a 3!

**Comment by bhumin-fw** [comment]
for testing.
1. On submission there is success message and few details will be display instead of blank page.
2. On the primary email that you have provided in form one mail will be send. Content of that email will be same as success page.

**Comment by ayushdamani** [comment]
Thank you for the instructions @bhumin-fw !

Verified working ✔️

Success message after submission - 
![Screenshot 2023-05-03 112416.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/c8d95e1a-af78-43aa-90d2-e27d7b7f9052)

Email - 
![Screenshot 2023-05-03 112437.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/6a3478e5-8a3a-45ea-b649-e978b4eae766)

**Comment by Stella-Archer** [comment]
Yes, worked absolutely perfectly! got the message and email
PO approved and closing this tix

**Comment by Stella-Archer** [comment]
I've checked in with Heather, we have some small edit to the messaging

**Comment by Stella-Archer** [comment]
Thank you <registrant Name> for registering your worksite for the 2023 Cold and Flu Program. Our nurse teams will reach out to you closer to the fall to begin organizing your clinic. You may check the Cold & Flu page on [Careers & MyHR](https://www2.gov.bc.ca/gov/content?id=F984C626E4814C69B14DA210716F170F) regularly for the most current information on the program. 

If you need to edit your submission during the registration period (June 12-30, 2023), please click the Submitted Forms tab on the main registration page and select edit to make changes to your submission. After June 30, 2023, you will need to request any changes via email to Cold.Flu@gov.bc.ca.

If you have any questions, or need help registering, please email the [Cold and Flu team ](Cold.Flu@gov.bc.ca).

**Comment by bhumin-fw** [comment]
@Stella-Archer @ayushdamani 
I have updated success page content and user's email content as per above comments.
Changes deployed to DEV and TEST.

**Comment by Stella-Archer** [comment]
Sweet confirmation message looks good.
Heather had a tweak to the email
second paragraph needs to read::
“If you need to edit your submission during the registration period (June 12-30, 2023), please click the Submitted Forms tab on the main registration page and select edit. To edit your submission after June 30, 2023, you will need to request any changes by emailing the[ Cold and Flu team](Cold.Flu@gov.bc.ca).”
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/f9d10f8a-833d-4ac7-ac55-df274e8ab5c6)

**Comment by ayushdamani** [comment]
Tested and verified working as well ✔️

The confirmation message has the new paragraph added!

![Screenshot 2023-05-09 121633.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/141000b3-242e-4127-b063-8e23f399a6e2)

**Comment by Stella-Archer** [comment]
Heather had a met with the clinic contractor they had some updates to the messaging update the messaging for both the confirmation page and email
Confirmation page:
1st bullet > Our nurse teams will reach out to you July-August to begin organizing your clinic
3rd bullet > If you have any questions, please email the Cold and Flu team.
with 'Cold and Flu team' linked to 'cold.flu@gov.bc.ca'
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/d0d589cf-784a-4ed6-92c9-50eca46e4b6c)
Email:
1st line should now say:
“Thank you for registering your worksite for the 2023 Cold and Flu Program. Our nurse teams will reach out to you July-August to begin organizing your clinic.”
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/641c2be5-e59d-49f4-9c54-e9640415732e)

**Comment by bhumin-fw** [comment]
@Stella-Archer @ayushdamani 
Updated content for success page and email. Changes available on DEV and TEST.

**Comment by ayushdamani** [comment]
Thank you, @bhumin-fw 

Tested on DEV & Test. Verified working ✔️

Success page - 
![Screenshot 2023-05-10 111722.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/014cabc4-69e3-44af-91c7-5dcae844b51c)

Email confirmation - 
![Screenshot 2023-05-10 111811.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/34429c0c-339f-46ad-a8fa-559b14cf5b52)

**Comment by Stella-Archer** [comment]
Done! PO Approved & Closing this baby
