### ISSUE TITLE
Cold/Flu - Admin can CREATE a cold/flu submission on behalf of another user

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1083]
**User Story**
As a Cold/Flu admin, i should be able to create a submission on behalf of another registrant, as some registrants may not have IDIR to access DJ 

**AC**
- [x] Admin should be able to create multiple cold/flu submissions

Notes 
- We do not need to clear the worksite contact field that are pre-populated with admin details fornow

**Comment by bhumin-fw** [comment]
Work has been updated on DEV and TEST.

**Comment by MeghanStothers** [comment]
Ready to test

**Comment by ayushdamani** [comment]
Tested and verified working. As an Admin, I was able to create multiple cold/flu submissions.

Acceptance criteria met ✔️

![Screenshot 2023-05-11 115051.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/b214d5f0-8608-4177-ae43-e51d455309a4)

**Comment by MeghanStothers** [comment]
Tested with Stella and Heather - PO approved.
