### ISSUE TITLE
Mat/Pat - Content Change - Deferred Allowance 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1085]
**Context**
Content needs to be updated to make it clear that the end date calculated is an estimate. The language has also been improved for additional clarity. 

Existing logic for this page as defined in #877 will stay the same

---------

1. Deferred allowance page (non Crown Counsel )  
>**When do you want to receive your leave allowance?** 
>
> Since you chose to defer your leave allowance, you must return to work for a minimum of 6 months or the length of your leave, whichever is longer, in order to claim the allowance after your leave ends.
> 
>_(information box)_
> You may choose any day to claim your allowance after your maternity and/or parental leave ends on December 17, 2023, until the repayment period ends on April 17, 2024. However, please note that April 17, 2024, is just an estimate, assuming that you do not take any further vacations or leaves after you return to work. The repayment period can extend if you take further leaves
>
>Note that to receive the full allowance amount, you must work until the end of the repayment period on April 17, 2024. Otherwise your allowance will be pro-rated.

2. Deferred allowance page (Crown Counsel = CC)  
>**When do you want to receive your leave allowance?** 
>
> Since you chose to defer your leave allowance, you must return to work for a minimum of 6 months in order to claim the allowance after your leave ends.
> 
>_(information box)_
> You may choose any day to claim your allowance after your maternity and/or parental leave ends on December 17, 2023, until the repayment period ends on April 17, 2024. However, please note that April 17, 2024, is just an estimate, assuming that you do not take any further vacations or leaves after you return to work. The repayment period can extend if you take further leaves
>
>Note that to receive the full allowance amount, you must work until the end of the repayment period on April 17, 2024. Otherwise your allowance will be pro-rated.

[**Design v3**](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184505&cot=14)

**Comment by chriscaldwell-psa** [comment]
@fazil-ey Hi Fazil, can we review the edits I made re this ticket. I just need some clarification on the non Crown Counsel vs Crown Counsel logic/form layout. Thanks Chris

**Comment by chriscaldwell-psa** [comment]
@Andrew-Vargas-bcgov This edits have been made. The code changes can be done next sprint. No rush on this.  Please see ticket 877 for the logic.

**Comment by fazil-ey** [comment]
FYI this needs to be fixed as well
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb21DIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f18c81d20df5f51cc0027f86d55024ef16dbff00/image.png)

**Comment by Andrew-Vargas-bcgov** [comment]
@ayushdamani ready to test.

**Comment by fazil-ey** [comment]
Hey @Andrew-Vargas-bcgov the page works good. Can you do a small design change to make it consistent with the rest of the pages? the design is here - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184505&cot=14

Adding a new heading for the info and moving the question down to right above the field

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey Made the changes this morning. Let me know if these look good to you.

**Comment by fazil-ey** [comment]
Looks good!
