### ISSUE TITLE
Cold/Flu: Validation message adjustments for "email" field 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1087]
As a business owner, I want to ensure all bc gov employees and ABCs have access to the worksite registration worksite via gov.bc.ca email address or via their "work email"

A/C
If possible for launch, we will 

1) change (red) validation message FROM
"Email address must be a bc gov email address"

TO 

"Email address must be a work address" 

2) Change blue box heading from "Email" to "Work Email"  

![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/d014e6a6-e647-49e5-a391-976111498180)

**Comment by MeghanStothers** [comment]
See #1071 which is related (but separate) work for MVP.  This ticket and work are noted and to be prioritized and determined if possible for launch.

**Comment by Abuchana** [comment]
@MeghanStothers is ticket #1071 the correct ticket to reference? It has to do with "retention of forms in tool". #1088 instead...?

**Comment by MeghanStothers** [comment]
@Abuchana  oops! this ticket is a new one I created from #1017 - #1017 is MVP for launch and this one can be completed as possible."

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/832d2c59-ed93-4a50-8525-763d39c92d83)
Label: Work email
Validation message: 
must be a work email address
must be a valid email

**Comment by chriscaldwell-psa** [comment]
Component label renamed - done, validation message added - done, email validation logic added - done. All 3 done like dinner.

**Comment by ayushdamani** [comment]
Tested and verified working in DEV ✔️

![Screenshot 2023-05-12 084556.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/50c93b55-d784-4631-9a18-d6f741fb312d)

**Comment by MeghanStothers** [comment]
@bhumin to deploy to test

**Comment by bhumin-fw** [comment]
@ayushdamani 
here you go. Changes updated on both env DEV and TEST.
Also changes applied to both email primary and secondary email contact. let me know if this changes only need to apply for secondary contact only.

Please re-check that default value for primary key is auto filled or for primary contact.

**Comment by ayushdamani** [comment]
Working in both DEV & Test ✔️
Also re-checked that the default value for primary contact is auto filled.

![Screenshot 2023-05-12 100609.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/7cb6bf57-3668-46b6-b98f-56c1950128a3)

Thank you, Bhumin!

**Comment by MeghanStothers** [comment]
Tested with Heather - success! PO approved. Can be closed
