### ISSUE TITLE
Cold & Flu: Updated ministry and worksite lists

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1088]
As a business area, I would like to have an accurate and updated ministry lists from the ODS to populate  the drop-down menu ("Your ministry or organization") for users to access when registering their worksite.  

AC:

**Comment by MeghanStothers** [comment]
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/c4d06240-e782-401e-a8b5-80e526e9ae29)

**Comment by MeghanStothers** [comment]
Missing: EMBC?

**Comment by MeghanStothers** [comment]
Alison connected with Steven Jones to get an updated list

**Comment by Abuchana** [comment]
MyHR CRM ticket: Org hierarchy + Worksite data [Incident: 230502-001162] - Data Insights Office (DIO)

**Comment by Abuchana** [comment]
Passing over to Don, Caleb, and Mike to complete, with Sarah and Heather if necessary. Thank you!

From Mike: 
Good morning,
Sure we can import records for ministry and worksite when needed, Don and Caleb have prepared sample data a few weeks ago.
1.	Only Ministry list, no hierarchy needed.
2.	For worksites, for your reference, this (  initial load seeder.xlsx) is what Caleb has provided.
Tables are also accessible on GBCBIDSQL4:
 
from Sarah: 
I'll be helping with this request, but I need to clarify a few things.
1) Do you just need an updated Ministry list, or do you need organizational hierarchy information within that? (I see that things like the telework form have a field for 'Division' but it's a free text field, not a drop down).
2) For worksite information, what exactly is needed and how 'clean' does it need to be? I can export a list of addresses that currently have an employee associated with them in PeopleSoft, but it won't be very clean. Would that meet your needs?

Also, when I mentioned this to Don, he seemed to think that Mike would be loading the data and so it should go directly to him. Any thoughts?
Thanks,
Sarah

**Comment by Abuchana** [comment]
Sarah to provide the list she is referencing and Mike to send the list we are currently using, DJ team to compare and confirm with Heather which list she wants to use.

**Comment by Abuchana** [comment]
Link to data dictionary
 DD_Influenza_db.xlsx

Seeder data (ministries and ministry_worksites) 
  initial load seeder.xlsx

**Comment by Stella-Archer** [comment]
Caleb confirmed the 'seeder' data is information extracted from last year's submissions. Sarah M is sending both the Ministry locations with numbers of people at each, plus the ministry list (less than 45 people once you filter for active ministry names)
I will manually audit the ministry list against the 'seeder' data and  send the list of gaps or changes to Mike.

**Comment by MeghanStothers** [comment]
Stella nd Ayush to manually update

**Comment by Stella-Archer** [comment]
Hi @mikeshi-bcgov  I rerviewed and compared the seed data from Caleb to the data from the DWH Sarah sent us
the following organization are new and should be added to the Ministry/org  list:

- Community Living BC 
- Housing
- Royal BC Museum
- BC Investment Corp

The was a few organizations the have had name changes they should be updated but still mapped to their old work sites:
Advanced Education, Skills and Training > is now > Post-Secondary Education and Future Skills
Agriculture, Food and Fisheries  > is now > Agriculture and Food
Emergency Management BC >  is now > Emergency Management and Climate Readiness
Land, Water and Resource Stewardship > is now > Water, Land and Resource Stewardship
the DWH report that we should now longer have BC Infrastructure Benefits or Infrastructure BC but I can still find website for them so I don't think we should delete them but do monitor if they are used at all for this years clinics

**Comment by MeghanStothers** [comment]
@Mike - can you please load from test?

**Comment by mikeshi-bcgov** [comment]
WorkSites data has been transferred to Prod.

**Comment by MeghanStothers** [comment]
Stella tested  and okayed to close ticket
