### ISSUE TITLE
SL Review: User is able to edit a form after submission

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#109]
**User Story**
As a senior leader, I want to edit my information to the SL Review form after I have submitted it so that I can go back to the submission and make changes to it alongside the conversations I am having with my supervisor. 

**Acceptance Criteria**
- [x] I can can come into the SL Review after submission and edit the form for resubmission to my manager
- [x] I can see my submission in the application tab
- [x] I can see the applications tab in my navigation
- [x] I can click edit in the applications tab to make changes
- [x] I can edit any fields in my application

**Technical Details**
- A minimal new SL Review Camunda workflow will need to be added with a user task that is assigned to the manager
- On submission, the application status is set to "Resubmit". Currently, you get the ability to edit a submission through the "Application" tab if the application status is either "Resubmit" or "Awaiting Acknowledgement" (reference: `isClientEdit` method of `List.js`). We can for now set the submission status to "Resubmit", and in future tickets refine this to allow more statuses.

**Background**
- There's already a page in the application (https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/application) where you can see all your submissions. We removed this from navigation as it was not necessary for the Telework form.

**Comment by simensma-fresh** [comment]
@schuyt This will have to built into the workflow of the given form, so we'll have to dig into exactly what cases we need to account for here, for each form figure out when you should be able to edit the form, and who should have the ability.

**Comment by warrenchristian1telus** [comment]
I think we need to further discuss exactly how this will work at the next convenient scrum or review session.

**Comment by MeghanStothers** [comment]
I reviewed this ticket and believe it relates to the Mat/Pat form (see use case above). Not a priority while we work on wrapping Telework in  next few sprints

**Comment by HasanSifat** [comment]
@bhumin-fw please put in an estimate

**Comment by MeghanStothers** [comment]
Separate ticket is required to handle sign-off and when the workflow should be editable (see Simen)

**Comment by MeghanStothers** [comment]
Bhumin to move to test, after reviewing a/c especially the application tab. Bhumin to review and update ticket.

**Comment by MeghanStothers** [comment]
This is a material global change that will involve looking at implications for:
-  the Telework PIA
- the Telework content (in  he tool and Careers & MyHR
- testing for Telework tool
- change management - messaging to the Policy team as well as to users who wrote earlier to say the form must be completed in one session, and there is "no ability to save" go back and edit later

**Comment by bhumin-fw** [comment]
I have added a new workflow for the SL review.
It allows a user to edit the form after submission. Use can see the submitted form with the edit button under the application page.

Note: I did not enable the application link in the navigation bar(535 will allow it to once we start work on that). 
Please test this ticket by redirecting to the application page manually. type <domain>/application in the URL to redirect.
@HasanSifat @Stella-Archer @MeghanStothers Please review it and assign one who can test and move it to done.

**Comment by HasanSifat** [comment]
SL Review 2.0 version is the new form given the updated process map. 

Link to new form in DEV- https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form/62f6a0e509da98bcd4d3d73c

**Comment by bhumin-fw** [comment]
@HasanSifat 
Added new workflow for SL review 2.0 and that link with form in a TEST environment.

**Comment by Stella-Archer** [comment]
waiting for search function 572

**Comment by HasanSifat** [comment]
Tested successfully in DEV. Ready to be transferred to TEST.

@EduardoRamirezBC @JodiLittle please review

**Comment by HasanSifat** [comment]
Tested successfully for the SL review form. Working successfully in DEV. Ready to be transferred to TEST/PROD

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/47507d0e-b8f5-44c7-94a1-c1dcceefad02)

**Comment by JodiLittle** [comment]
Approved

**Comment by HasanSifat** [comment]
tested successfully in TEST
