### ISSUE TITLE
Cold/Flu - Form Access during registration period & grace period 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1093]
**_AC_** 
- Everyone with IDIR should have access to submit forms during the OPEN period
- Everyone with IDIR should have access to submit forms during the GRACE PERIOD i.e. 2 weeks after end of OPEN period
- Only admin should have access to submit forms after GRACE period ends. Regular users should not be able to submit new forms. Regular users can still view their submitted forms, but they cannot edit them. 
    - Implementation - regular users can still see the form in the list but when they go in they see a message
    - Copy for message TBD by Heather , "Registration of the 2023 program was ...If you still want to register Contact .... "
    - Effort  ~3
    - [Form title - closed]

**TBD - dates open period & grace period **

**Comment by iman-jamali-fw** [comment]
Can you clarify "submit forms"? We have three actions on cold/flu forms for users:

- Submit new forms
- View submitted forms
- Edit submitted forms

**Comment by Stella-Archer** [comment]
who should have what access when:
Open period June 12th - June 30 : Any one can come in and submit/edit/delete
Grace period: June 30- July 14 time for stragglers, link is removed from Career & MyHR website on June 30th, but available for users inside Digital Journey
1st report due week of July 15 
Closed July 14 - only ADMIN can access or edit/add/delete

**Comment by Stella-Archer** [comment]
Heather has prepared copy for the message AFTER grace period when the form is CLOSED:
**Worksite registration for the 2023 Cold & Flu Program was June 12-30. This form is now closed. For questions about the program, or if you are interested in registering your worksite for the current, or future programs, please email the <a href="mailto:Cold.Flu@gov.bc.ca">Cold and Flu team</a>**

**Comment by fazil-ey** [comment]
duplicate
