### ISSUE TITLE
SL: Launch Plan June 1

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1095]
As a program area, I want to ensure users have easy and clear to a functional form and meets all requirements for launch.

Acceptance criteria:

**Technical**
functional
tested
ready for launch

testing*
Test with program area before launch

Communications
Link to be added to the Teams channel
Log in Page
 Digital Journeys mailbox triage plan
comms plan

**Security**
 STRA (if needed) 
 SOAR )if needed) 

**Privacy**
 PIA

low/Standards changes - Tuesday and Thursdays are change windows (morning) 
Wednesday and Sunday - - more complex
Emergency changes

**Comment by MeghanStothers** [comment]
Dev decision: Deployment on Monday May 29 after-hours with PSA team to support.
Jodi and team to test on Tuesday.

**Comment by iman-jamali-fw** [comment]
@mikeshi-bcgov
Could you check if the SL Review endpoint has been deployed to ODS PROD? If not, can we have it on PROD by Monday?

Endpoint is `Datamart_Telework_app_slreview_info` and supports POST and PUT methods.

**Comment by MeghanStothers** [comment]
Deployment will happen on Monday as deployment will happen in change windows on Tuesday and Thursday.
Mike confirmed the endpoint is already in prod.

**Comment by iman-jamali-fw** [comment]
@MeghanStothers @Stella-Archer 
cc @bhumin-fw @Andrew-Vargas-bcgov 

Here's the plan for today's deployment:

- Iman will start the deployment at 5 pm.
- Bhumin will be on standby from 5:30 pm to 7 pm in case of any emergencies.
- The testing team can begin testing at 6:30 pm. 
- Iman checks the testing group on Teams and responds from 7 pm to 7:30 pm.

Please let me know if this works for you.

**Comment by MeghanStothers** [comment]
I like it - I will be online around 6:30 and can support testing or anything else.

@iman-jamali-fw Go ahead when  you're ready

**Comment by MeghanStothers** [comment]
Thanks to @bhumin-fw and @iman-jamali-fw and @Andrew-Vargas-bcgov and @Stella-Archer for supersonic testing, testing and fixes.
