### ISSUE TITLE
SL: Content updates for "final submission" confirmation message 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1097]
As a form submitter, I need a message to confirm my submission was sent, as well as any information about next steps and contact information. 

A/C
( ) Business area updating the message below with current dates and approved information
( ) Adding this information into the formsflow.ai tool
( ) testing the message
( ) Approval by PO

Message from 2022: 

> Thank you for your commitment to supporting senior leadership and executive succession.
> 
> The information you’ve provided will be shared with Executive Talent Management and Corporate Workforce Strategies in the Public Service Agency. Ministry-specific results will be shared with the identified ministry key contacts (DMO and/or ministry Human Resources) to inform ministry leadership development.
> 
> Data will be provided for DMC/ DMCPSR to inform executive succession and development strategies, programs and activities.
> 
> The file will remain available in the system until the end of the day on March 17th, 2023.
> 
> Now that the SLR process is complete, please encourage the senior leader to target their learning and development plan, goals, and actions to support their career aspirations and readiness to compete for an executive role.
> 
> You will receive a PDF copy of this form via email. A PDF copy can also be downloaded using the “Print as PDF” button on the top right of the form. We encourage you to share the completed PDF form with the senior leader.
> 
> If you have any questions, please contact PSA.SeniorLeadershipReview@gov.bc.ca

**Comment by MeghanStothers** [comment]
Stella and Meghan to ask Jodi for updated messaging.

@JodiLittle - please send updated messaging

**Comment by Stella-Archer** [comment]
**Please update final confirmation message:**

Thank you for your commitment to supporting senior leadership and executive succession.
The information you’ve provided will be shared with Executive Talent Management and Corporate Workforce Strategies in the Public Service Agency, ministry SLR key contact (ministry-specific data), and DMC/DMCPSR to inform executive succession and senior leadership development strategies, programs and activities at both the ministry and corporate levels.
Shortly, you will receive an email with a PDF copy of the form for your records. 
You will also receive an email with a survey about your experience with this SLR process. Your feedback will help us improve the next review process.
Thank you. If you have any questions, please contact the SLR Team.

**Link the word SLR team to:**
mailto:PSA.SeniorLeadershipReview@gov.bc.ca

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 

This is ready to be tested on TEST.

**Comment by ayushdamani** [comment]
Tested and verified working ✔️
- Updated final confirmation message can be seen
- Link the word SLR to PSA.SeniorLeadershipReview@gov.bc.ca

![Screenshot 2023-05-25 203815.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/40361353-c2ca-40e2-961c-53af9fb9160f)

![Screenshot 2023-05-25 203920.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/8542517c-455f-44bb-983c-42395bb83e18)

**Comment by Stella-Archer** [comment]
this looks perfect PO Approved and Closing tix

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/b0cc1936-aea5-4c53-9cb4-9c823bbe7986)
