### ISSUE TITLE
SL Review: Status of forms on Submitted tab

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1099]
We want to change the status of the form in submitted tab to reflect the actual status and make it clearer for ADMs on what the next action item is.

1. After form is submitted for validation the status of the form should be "Submitted - Validation"
2. After final submission the status of the form should be "Submitted - Final"

This is a nice to have

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey the standard seems to be pascal/title case eg: "Submitted - Validation". Do you want it all caps instead?

**Comment by fazil-ey** [comment]
^ Sorry for the late response. We should not have all caps for readability. Not sure why i used all caps in the first place! my apologies. Updated the ticket!

**Comment by Stella-Archer** [comment]
looks great thanks - PO Approved & Closing tix
