### ISSUE TITLE
Branded look-and-feel for forms

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#11]
As a digital journey user I would like to see a branded consistent look-and-feel for forms

**Acceptance Criteria**
- Styles from the BC Gov Design System:  https://developer.gov.bc.ca/Design-System/Navigation-Bar-Basic are applied to the listed components
- Import and apply government approved BC Sans font as per the BC Gov Design System
- Consider Colours match style guide
- Consider font-size & colours for accessibility
- Page header is updated to match the styling provided by the BC Gov Design System [navigation-bar-basic](https://developer.gov.bc.ca/Design-System/Navigation-Bar-Basic)
- Page footer is updated to match the one provided by the BC Gov Design System [Footer-Basic](https://developer.gov.bc.ca/Design-System/Navigation-Bar-Basic)
- The header of the Telework Agreement is updated to match the given form [Logo](https://drive.google.com/file/d/1E6FxH_t8BcXM5f_6aVity5NpJnAhWFla/view?usp=sharing). [https://www.figma.com/file/gQDAaN0lnJJj1xg6NXFEsI/Wireframes?node-id=11%3A194](https://www.figma.com/file/gQDAaN0lnJJj1xg6NXFEsI/Wireframes?node-id=11%3A194)

**References**:
- Button inc has a react library with alot of prebuilt BCGov branded components: https://button-inc.github.io/service-development-toolkit/@button-inc/bcgov-theme/index.html?path=/docs/components-navigation--html  https://github.com/button-inc/service-development-toolkit

- [Visual Identity Guidelines](https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity)
- [Design System](https://developer.gov.bc.ca/Design-System/About-the-Design-System)
- [Example](https://www2.gov.bc.ca/assets/gov/careers/forms-tools/managers-supervisors/c19_vax_exempt_medical.pdf) of branded form
- [Colour Pallet](https://developer.gov.bc.ca/Colour-Palette)
- [Contrast Accessibility Checker Tool](https://webaim.org/resources/contrastchecker/)
- 

**Notes**:
- Will use Corporate identity "Where We Work" for these forms - see mock-up
- Review styles that we have afterwards and capture any required changes
- Spin out any stories for adjustments

**Comment by schuyt** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Digital-Journeys-61c10fe84c8bcb001491c5f5/issues/bcgov/digital-journeys/11?planning-poker) with ZenHub @simensma-fresh @qudsia-khan-fw @iman-jamali-fw

**Comment by schuyt** [comment]
@iman-jamali-fw Mock-up of form styles using BC GOV branding is here: https://www.figma.com/file/gQDAaN0lnJJj1xg6NXFEsI/Wireframes?node-id=11%3A194

Ping Jordan if you need access.

**Comment by qudsia-khan-fw** [comment]
@iman-jamali-fw Please find the test results as discussed here:
https://docs.google.com/document/d/1Hjbg-NDL3WRvXPXw8PqDPV9eEvSLO_EEasi0-r6mfrQ/edit?usp=sharing
