### ISSUE TITLE
Mat/Pat - CRM ticket on approval

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1100]
**User Story**
As a supervisor, I want a CRM ticket to be created automatically when I approve a mat/pat leave application so that I do not have to do it manually

**Acceptance Criteria**
- [ ] Supervisor should receive an email to confirm the CRM ticket has been created with the ticket number 
    - [ ] Email copy should be the default CRM copy when a ticket is created 
- [ ] The ticket should be created 
    - [ ] for Supervisor as the primary contact, not the applicant 
    ~- [ ] with the option "My Team or Organization"~ (no need as this field is hidden in CRM ticket field)
    - [ ] under "Leave & Time Off > Maternity, Parental, Adoption" 

*Note* - Some AC have been moved to 1190 (thread) and 1192(pdf). The estimated efforted was reduced from 8 to 5 as some of the ACs were moved to separate tickets.

**Technical notes**

**Comment by fazil-ey** [comment]
Hey @T854236, will you be able to provide the API documentation for creating CRM tickets

**Comment by T854236** [comment]
@fazil-ey 

Please request engagement for a CRM resource with a JIRA service request.  You'll also need a user license account provisioned to be used by DJ to access the APIs.

**Comment by MeghanStothers** [comment]
Caleb has submitted a JIRA service request

**Comment by iman-jamali-fw** [comment]
@ca-liu 

Hi Caleb. I have a question for you. 

Does CRM have the capability to send an email? We need to send an email once a ticket (incident) is created/updated, wondering if we can leverage CRM REST API to handle that.

**Comment by MeghanStothers** [comment]
Involves the Camunda workflow and CRM integration. 
Estimate based on initial understanding of work. 
Changes required will be put into a separate ticket.

**Comment by iman-jamali-fw** [comment]
Progress report:
- Created a CRM ticket leveraging API
- Added text to that ticket as a thread
- Have a contact assigned to that ticket
- Updating a ticket is not working yet, it seems like an issue from CRM not allowing me to update (Patch) an existing CRM ticket.

Next:
- Learning how to attach a file (PDF) to an incident (ticket). 
- Will meet with @fazil-ey to find out about the required fields and how to map them to the incident object in the API. After that meeting, I'll have a number of questions for the CRM team to ask.

**Comment by Stella-Archer** [comment]
Iman digging into figuring out updating the API
questions for CRM ready for tomorrow (Friday 9 June)

**Comment by iman-jamali-fw** [comment]
Progress report:

- Had a meeting with Fazil and clarified the field mapping
- Learned about Contact in CRM RestAPI that can help find and assign a ticket to the supervisor.

Next:

- Continue working on ROQL to find the supervisor on CRM in order to assign them to the ticket
- Will ask a few questions for the CRM team about email notifications on ticket creation and field mapping
- Attaching PDF to the ticket (incident).

**Comment by iman-jamali-fw** [comment]
@mikeshi-bcgov @T854236 
I'm trying to use CRM REST API to find the supervisor (in order to assign the ticket to them). So far have found that I can use managers' `IDIR` or `employee-id` to get their contact resources from CRM REST API. Do you know which one is more consistent to be used or if you know a better way please let me know.
Do you know which fields is

**Comment by MeghanStothers** [comment]
Thanks for letting us know Iman - Please keep @Stella-Archer and @Abuchana  updated on any clockers you encountered in the CRM integration work. Thanks

**Comment by iman-jamali-fw** [comment]
Progress Report:
- Finding the primary contact (supervisor) by IDIR/employee-id in the ticket/incident creation worked great.
- Adding file attachments to an incident (ticket) worked fine at the REST API level.
- Forwarded a list of queries to be asked from the CRM team. This would help us understand how to map the current fields in the CRM ticket UI for Mat/Pat to the REST API resources.

Next:
- integrating the CRM ticket creation with the Mat/Pat workflow. 🤞

**Comment by iman-jamali-fw** [comment]
Mat/Pat CRM ticket-REST API mappings Questions

CRM Ticket Notification Process
I spoke with Caleb about enabling CRM to send notifications to relevant parties when a ticket is created or updated. Caleb mentioned that the current setup already sends receipt messages for incidents/tickets created via inbound email or AskMyHR. Could you please provide more information on how this works, including the email format and testing procedures? Specifically, I would like to know:
What actions or events initiate the process, and how are notifications delivered?
Recipient List: Who will receive notifications?
Email Format: Can you provide an example or description of the email notification's content and any included details or links?
Testing Procedure: How can we test the ticket notification process?
 
 
Maternity/Parental/Adoption Leave specific CRM ticket questions.
Please find attached a screenshot of the CRM ticket. I have a couple of inquiries about mapping the ticket information to the REST API incident's properties:
When "My Team or Organization" is selected on behalf of the employee, which incident property should this be mapped to (in the REST API)?
When "Maternity, Parental, Adoption" is selected under "Leave & Time Off," which incident property does this correspond to (in the REST API)?
In the ticket screenshot, there is a field called "Assigned". I found "assignedTo" in the incident properties (in REST API). Is this the same field? If so, it accepts staff account and staff group. Can you explain how it works for Mat/Pat CRM tickets?
In the ticket screenshot, there is a field called "Status". I found the same name in the incident properties (in REST API). Can you explain how can I set status of an incident using the REST API? Can I send any status during incident creation or update? or I should reference an already created status?

**Comment by MeghanStothers** [comment]
Questions submitted to Nancy on June 13 for response. 

@iman-jamali-fw  Does the "screenshot: mentioned above refer to the documentation that Caleb sent as I don't see a screenshot attached to this ticket?

**Comment by iman-jamali-fw** [comment]
@mikeshi-bcgov @T854236 
Hi Mike and Patrick. When you have the chance, could you look at my comment below? Thank you

> I'm trying to use CRM REST API to find the supervisor (in order to assign the ticket to them). So far have found that I can use managers' `IDIR` or `employee-id` to get their contact resources from CRM REST API. Do you know which one is more consistent to be used or if you know a better way please let me know.

**Comment by T854236** [comment]
@iman-jamali-fw 

I would recommend using the IDIR as that is the unique identifier with constraints.

**Comment by iman-jamali-fw** [comment]
Progress Report:

* CRM service - create incident was added
* CRM service - add a thread of texts to an incident was added
* 
Next:
* CRM service adding an attachment to an incident

**Comment by Stella-Archer** [comment]
I've put the recording of our Q&A session with TES on the wiki https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.wiki/tab::3647145d-d141-41cc-9bd4-b8f309d2d983?context=%7B%22subEntityId%22%3A%22%7B%5C%22pageId%5C%22%3A2%2C%5C%22sectionId%5C%22%3A43%2C%5C%22origin%5C%22%3A2%7D%22%2C%22channelId%22%3A%2219%3AQd6bsax8Kq1McTFWXMWQIqWNheO-3gJ7Q_k8v09zgc01%40thread.tacv2%22%7D&tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc

**Comment by iman-jamali-fw** [comment]
Progress Report:
- CRM service can now generate a pdf for submission and attachment it to the incident (CRM ticket).

Next steps:
- Refactoring the service code
- Add error handling

**Comment by Stella-Archer** [comment]
Hope to have the PR over tomorrow

**Comment by iman-jamali-fw** [comment]
I'll deploy to this DEV and TEST later next week (the week of July 17)

**Comment by iman-jamali-fw** [comment]
@fazil-ey 

This is ready to be tested on the TEST environment. Please ping me for the testing, you'll need me to fetch the CRM ticket details from their REST API to ensure it works.

**Comment by ayushdamani** [comment]
Tested with @iman-jamali-fw 

What worked out great:
- CRM ticket was successfully created.
- CRM ticket had a sample PDF attachment
- CRM ticket had a sample thread of text.
- The manager was successfully assigned as the primary contact.

Things we need to verify:
- We had sample text as a subject ticket. Please inform what we should use as sample text.
- The email notification has not been setup. We need to talk to CRM team to enable this.
- "Leave & Time Off > Maternity, Parental, Adoption" is missing.

**Comment by MeghanStothers** [comment]
Thanks, Ayush! 

Iman: will you reach out directly to the TES team about setting up email notification? Let me know if I can help in any way.

**Comment by iman-jamali-fw** [comment]
@fazil-ey 
I want to ask Nancy (from Telus) to enable email notifications for CRM. Have a couple of questions for you:
- Do you want the email to be sent only on ticket creation? Or on creation and update?
- Who should receive the email? At this point the primary contact is the manager who validates the submission, is this person the only one who receives the email?
- Any specific text you want to be added to the email body or we can start with CRM default message?

**Comment by fazil-ey** [comment]
Hey @iman-jamali-fw 
- I think we should follow whatever the default behaviour is in CRM right now when tickets are created in AskMyHR, if emails are sent on creation & update we should follow the same
-  The primary contact must receive the emails. 
-  We can start with CRM default email, we dont need any custom message for CRM emails.

**Comment by iman-jamali-fw** [comment]
@fazil-ey 
Do you want the CRM ticket created/updated **only** when a supervisor **validates** a submission? With implementation, it is also created when employees **resubmit** the submission, I guess this is not what we want, right? If so let me know to fix that.

**Comment by fazil-ey** [comment]
@iman-jamali-fw  It should be only when supervisor validates it. Even if it is resubmited by employees, the CRM ticket should be updated only when supervisor validates it

**Comment by MeghanStothers** [comment]
Ready for testing - piece missing is the the email notification. TES/Nancy is waiting for password.

**Comment by MeghanStothers** [comment]
Iman and Andrew to test today

**Comment by Andrew-Vargas-bcgov** [comment]
![image.png](https://images.zenhubusercontent.com/63bf02395e70d816edf8df36/ef97d2b5-d6a6-45ae-855e-8eeb432163dd)

**Comment by iman-jamali-fw** [comment]
@fazil-ey 
Could you check the screenshot Andrew uploaded in the previous comment (from the CRM test environment) and verify if everything looks good for this ticket?

**Comment by MeghanStothers** [comment]
@fazil-ey - can you check on this ticket and advise if this one (or part) can be deployed tonight?

**Comment by fazil-ey** [comment]
If Iman was the supervisor in the form, the CRM screenshot looks good for this ticket.  
I was not able to test CRM email on approval, as there seems to be a bug when supervisor approves the form. It is not getting validated for me.

**Comment by iman-jamali-fw** [comment]
@fazil-ey 
Yes, I was the supervisor, and Andrew was the employee. Thanks for checking.

Unfortunately, you won't be able to test it out since you don't have a CRM account associated with your IDIR. If you needed one, let the Nancy know and she can create a one for you on CRM TEST environment,

**Comment by MeghanStothers** [comment]
With TES/Nancy email notification fix needed. Ayush needs access to test environment - needs a client account.

**Comment by iman-jamali-fw** [comment]
@Andrew-Vargas-bcgov 
Will you be able to test out the CRM creation for email notifications? I'm able to get email on creation. Let us know if that works for you and if possible share the email text in a comment so @fazil-ey can verify the email content. thank you

**Comment by iman-jamali-fw** [comment]
@fazil-ey 

This is the email I get when creating a CRM ticket with myself as the manager. Please let me know if this looks good to you.

![Screenshot 2023-08-11 at 8.03.54 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/c36d3af5-3ec1-4ccc-8ca9-2470192c0605)

**Comment by Andrew-Vargas-bcgov** [comment]
Tickets are created, but I am not getting e-mails. It looks like my e-mail still has the .invalid which stops e-mails if I recall correctly.

**Comment by iman-jamali-fw** [comment]
Chris also didn't receive an email notification on CRM ticket creation.

I contacted Nancy to investigate the issue. Update the ticket once hear back.

**Comment by fazil-ey** [comment]
Some emails have invalid tags and those need to be removed in test env.

**Comment by iman-jamali-fw** [comment]
Emails are fixed, Stella, Andrew, and Chris will receive email notifications when a CRM ticket is created.

**Comment by fazil-ey** [comment]
Receiving emails. 
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWdpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--397f3aafd455cd9fadcf42444bb2c3a7097db739/image.png)
