### ISSUE TITLE
Cold/Flu: Txt edit to Open Clinic Pop up

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1102]
There is a few text edits needed to the 'Open clinic' info pop up
1/ second sentence the open should not be capitalized
2/ there 2 spot where "GOV" needs to be replace by "BC Public Service employees"
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/3737e307-3150-46c9-b23f-00ab2a5f201f)

**Comment by chriscaldwell-psa** [comment]
The pop-up text has been changed and can be tested again. 

![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/919d3332-d126-477a-8f58-afe2fa33b073)

**Comment by ayushdamani** [comment]
Tested this in DEV, verified working ✔️
The text changes can be seen in the screenshot below.

![Screenshot 2023-05-11 115550.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/6b683f27-4fba-4903-833f-e436a7a5eec9)

**Comment by Stella-Archer** [comment]
@chriscaldwell-psa Looks good in DEV but doesn't appear to have been moved to TEST yet
