### ISSUE TITLE
Mat/Pat - CRM ticket on reapproval 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1107]
**User Story**
As a supervisor, I want a CRM ticket to be created automatically when I reapprove a mat/pat leave application so that I do not have to do it manually and it can be connected to the original CRM ticket

**Acceptance Criteria**
- [x] New information must be sent to the same CRM ticket created when the form was submitted the first time.  
- [x] Supervisor should receive an email to confirm the CRM ticket has been updated with the new information
    - [x] Email copy should be the default CRM copy when a ticket is created 
- [x] The ticket should contain all form fields in the ticket details section
    - [x] The text in the thread should be in a format that is easy to read (Sample below)
- [x] The new form should be an additional pdf attachment. The old attachments should not be replaced
         - The pdf should contain only the review & certification pages in the form 

**Sample**
Click to enlarge
<img src="https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/173132cc-529b-4ff7-8eb9-4dad8821861d" width=50% length=50%/>

**Technical notes**

**Comment by MeghanStothers** [comment]
to start work after #1100

**Comment by Abuchana** [comment]
Bhumin has inquired with Nancy about CRM threads - want to have the system delete old threads and only keeping the most recent thread.

**Comment by fazil-ey** [comment]
I would recommend a second copy of the document is attached to the service request.  It would be time stamped in the audit log to show it’s the newest.  Then we have a complete record of the employees submissions in the event that they/we need it.

**Comment by MeghanStothers** [comment]
Bhumin to make changes and send to testing by end of day.

**Comment by fazil-ey** [comment]
I did not receive a CRM email for every resubmission, but when i did it reflected the changes, except a weird bug with the start date. - documented in #1334
