### ISSUE TITLE
Mat/Pat - Content Changes/Form Design Change for Maternity Allowance

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1108]
**Context**

1. The allowance calculator felt like it was part of the form when it was not actually. To address this the calculator is now in a accordion style box
2. The info/alert boxes were not drawing attention as intended. To address this "check you eligibility" is now not inside a info box
3. Some content has also been moved from the "mat leave -length of leave" page to "allowance" page 
4. A note has been added that AskMyHR will not be able to answer your EI related questions

**New Design & Content**
[Maternity leave - top up allowance v3](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184496&cot=14)

[Maternity leave - length of leave v3](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184493&cot=14)

**AC**
- [ ] The content on both the pages above should match the new designs. Note that the text has also been refined a little bit.

**Comment by MeghanStothers** [comment]
Chris to review version 3 and talk to Andrew before starting this work.
@chriscaldwell-psa - please update the ticket with any info

**Comment by chriscaldwell-psa** [comment]
Made 98% of the changes to the tab on Friday. I need to get some feedback next week to make sure the 'accordion style' calculator reveal is correct. When I moved the components, the calculate button does not work. I will need to connect with Andrew. The test env was downloaded as a backup. It's easy for me to revert any changes if necessary. I will update the hyperlinks on Monday.

**Comment by fazil-ey** [comment]
FYI @chriscaldwell-psa notices these Maternity leave allowance screen - 

1. Change the wording top-up allowance to leave allowance throughout the page. 
2. Add missing links [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXR1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3d2cd3d8f9d7faf2462ba961b7954e9fe24431e0/image.png)
3. Typos in this text 
"To avoid **_unforeseen,_** it's important to check your **_legibility fo_**r EI before commencing maternity leave, especially if yo**_u 've re_**cently completed parental or maternity leave or claimed EI due to any reason like unemployment, family caregiver leave or compassionate care leave. If you have any queries about your eligibility, you can contact EI. **_AskMyHr_** will not be able to help you with your questions about EI. 

Also, note that your eligibility for EI will be officially confirmed only after you apply for EI when your maternity leave begins and your application is approved. "

**Comment by chriscaldwell-psa** [comment]
Changes have been made to review. Chris

**Comment by ayushdamani** [comment]
1. Tested in TEST environment.
2. Started a new Mat/Pat form.
3. Checked the form against the ticket's acceptance criteria
4. Also, reviewed Fazil's comments for updated changes in the form.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaG1HIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--af4f0de74c32cd9131942e28918f323551cd690b/Screenshot%202023-09-11%20050326.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGlHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--43f30b53e7cc472c87da0bff390702464812c9c4/image.png)

**Comment by fazil-ey** [comment]
Looks good, changes match designs. Links not opening in new tabs, but that is a form wide issue that will be tackled in #1274
