### ISSUE TITLE
Mat/Pat - Content Changes - Parental Allowance

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1109]
**Context**

1. The allowance calculator felt like it was part of the form when it was not actually. To address this the calculator is now in an accordion style box

2. Some content has also been changed in parental leave - general information page 
    3. Added a note that for eligibility questions contact EI not AskMyHR

**New Design & Content**
[Parental leave - general information page v3](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184512&cot=14)

[Parental leave - top-up allowance information of leave v3](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184514&cot=14)

**AC**
- [x] The content on both the pages above should match the new designs. Note that the text has also been refined a little bit.

**Comment by chriscaldwell-psa** [comment]
@Andrew-Vargas-bcgov  - thanks for adding the logic!  I will look at the Parental tab now . Thx. C.

**Comment by Andrew-Vargas-bcgov** [comment]
Added all the logic and moved to test. Ready to be tested :).

**Comment by ayushdamani** [comment]
Thank you, Chris and Andrew! Looks great.

Just one question: Is there too much space between point number 1 & 2, under "How will you be paid during your leave?". Maybe @fazil-ey can help answer this.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0JnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7fa48bb87ea12f30e6badc414e31cfbbe2350bd3/image.png)

Looking great, The button works as required -
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2xnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ad126f9481e1a4baaf9ccd7cd9c9c73ed97cefc1/image.png)

**Comment by fazil-ey** [comment]
There is a spacing issue all throughout the form. We have a nice to have ticket #1060 to address it.

**Comment by fazil-ey** [comment]
@chriscaldwell-psa 

Text does not match the [designs](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184514&cot=14). 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalp1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--08354d08b04215e0a80f2a7eccbbfe20e4c2b88b/image.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamR1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0be00bc0a4ecc04c155e5a96938c85d3623c76b2/image.png)

**Comment by chriscaldwell-psa** [comment]
@fazil-ey Edits made as per Miro board.

**Comment by chriscaldwell-psa** [comment]
Edit have been made to review.

**Comment by ayushdamani** [comment]
Confirmed updated:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBam1JIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9189dbfad7873d159f46448d77f0a65649e1bd80/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanVJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--98dbfee57de5df595b51c0cb0e3ff4bbc6d7d30f/image.png)

**Comment by chriscaldwell-psa** [comment]
Changes have been made to:  Parental leave - general information page v3. Ready to approve.

**Comment by ayushdamani** [comment]
Thank you for making the changes, Chris! 

Content in Parental Leave - general information is now updated to match Miro ✅
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXVXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--065bc50432d94d6bfcb7b001a6cd3bc774311c55/image.png)

**Comment by fazil-ey** [comment]
Both pages have been updated.
