### ISSUE TITLE
Telework: CSS style tweaks

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#111]
Please change the following on the Telework form:

1. For each panel heading, make it bigger like the title "Telework Agreement" and bold.
2. Make the checkboxes and radio buttons more prominent. 
3. Signature (Sign Above) colour contrast should be better.

**Comment by MeghanStothers** [comment]
This ticket falls into Ji's court

**Comment by MeghanStothers** [comment]
To look at these earlier findings from Freshworks and prioritize after user testing

**Comment by fazil-ey** [comment]
Closing as this is a minor issue, not be relevant anymore after 1+ years of release
