### ISSUE TITLE
Cold/Flu: Text edits

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1113]
**2/ ALREADY REGISTERED Pop-up:**
replace text in 'already registered' pop up with:

“You have already registered your worksite for the 2023 Cold and Flu Program. 
If you need to edit or delete your submission during the registration period (June 12-30, 2023) please go to the Submitted Forms tab to make any changes. 
After June 30, 2023, you will need to request any changes by emailing the <a href="mailto::cold.flu@gov.bc.ca">Cold and Flu team</a>
Please contact the <a href="mailto::cold.flu@gov.bc.ca">Cold and Flu team</a> if you have any questions. Thank you.” 

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/45de8ab9-3988-4179-bf17-656bf66f847b)

3/ Orientation Text
First line should now read: 
Please register your worksite below. 
Second line: 
If you have any questions or need assistance, please contact the **Cold and Flu team** by email, or call 236-478-2046
"Cold and Flu team" should link to email address Cold.Flu@gov.bc.ca

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/83598f4b-56bb-4105-93b8-7fd434d0cc51)

**Comment by bhumin-fw** [comment]
@ayushdamani @Stella-Archer 
Text changes are up and running on DEV and TEST environment.

**Comment by Stella-Archer** [comment]
Perfect. PO Approved. Tix Closed
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/04a2db73-e4b0-47d4-a292-accd4ae96c0b)
