### ISSUE TITLE
Cold/Flu: Unnecessary text above worksite Information

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1114]
When registering a worksite contact a confusing alert box is seen
could we please have it removed?
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/b2e8f0ec-d4a9-4c24-bcf3-7f03b758919e)

**Comment by bhumin-fw** [comment]
ready to teats.
Change updated on DEV and TEST both environment.

**Comment by ayushdamani** [comment]
Tested and verified in DEV and TEST ✔️
- The confusing alert box does not appear anymore.

![Screenshot 2023-05-11 114637.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/7d9fdc98-2d3c-4384-984a-067a77fb4f38)

**Comment by Stella-Archer** [comment]
Yes - Looks great - PO Approved & Closing tix
