### ISSUE TITLE
Cold/Flu: editing/ resubmit validation and date stamp update

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1117]
**User Story**
“As a user I need to see a validation and/or a time stamp update, so I can be sure my edited information is submitted.” 
![D1E5EDE4-3EB6-45AF-A81D-63C1B7B675A6.GIF](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/7ae295e5-6938-4cb2-a05b-57bc0d2c2144)
**Tasks**
update time in 'last modified' column of submitted forms tab when form has been modified
include a validation message after form has been resubmitted - 

**Acceptance Criteria**
* [ ] the time stamp in the 'Last modified' column is updated when I resubmit my Cold and Flu registration form
* [ ]  a validation message appears when the form is updated by the user, could be a s simple as 'thanks your form has be resubmitted'

**Comment by MeghanStothers** [comment]
Iman is hoping to deploy this one to prod with other tickets - May 15

**Comment by Stella-Archer** [comment]
@iman-jamali-fw  We did a test with Heather  in TEST environment around 3:20pm today.
Heather opened a submissions from me with a 3:15pm date stamp and changed clinic requester to Meghan and a few other details. All the changes worked, but date stamp stayed at 3:15

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 

The changes were just deployed to the DEV and TEST environments. Sorry if it didn't work earlier. Could you test it again?

**Comment by Stella-Archer** [comment]
YAS! the time stamp changed!
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/94d5ead2-8699-401f-ae53-09ab52c8c310)
PO approved & closing this tix!
