### ISSUE TITLE
Cold/Flu: Grace period June 30- July 14

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1118]
**User Story**
“As a cold and flu worksite clinic registrant, I want a grace period so I can register for a clinic after the deadline if I happen to miss the deadline

**Tasks**
Grace period: June 30- July 14 time for stragglers
* [x] link is removed from Career & MyHR website on June 30th
* [x] Cold and flu form is available inside Digital Journey for all users

ticket #1093 describes the complete process of when what access to the form is available to which users groups

**Comment by Abuchana** [comment]
Bhumin automated this function
