### ISSUE TITLE
Cold/Flu - Popup after grace period ends

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1127]
Create a popup & display the message for non-admin users when they click on the form in the Forms tab. 

> Worksite registration for the 2023 Cold & Flu Program was June 12-30. This form is now closed. For questions about the program, or if you are interested in registering your worksite for the current, or future programs, please email the Cold and Flu team at cold.flu@gov.bc.ca

The grace period is June 30 - July 14

@Stella-Archer

**Comment by bhumin-fw** [comment]
Added popup.
To test, I have added one hidden field in form. Form designer can access it.

- Open form in edit mode
- Find field "EndDate YYYY-MM-DDThh:mm:ss", (bottom of the form).
- Open this component by clicking on "setting" icon.
- go to data tab and set your date.
- To test set some past date and save, now when any non-admin user try to add new submission it will show this popup.
note: to view this popup you need to click on "don't see your worksite?" or "register your worksite" button. As select ministry and worksite will stay open to show basic detail about registered clinics.

Make sure you update back that value to "July 14" as soon as possible so it won't affect any other user who are testing or submitting new submission.

**Comment by Stella-Archer** [comment]
@Ayush do you you have form Designer access to test this?

**Comment by chriscaldwell-psa** [comment]
As a forms designer, I edited the hidden date component to an older date (closing the form). The message pop-up appeared and the form closed. The test was successful.  One thing I did notice is, I was wondering if the date in the hidden component will update automatically in the pop-up? For example, if we change the closing date to May 30th, would the pop-up message reflect this date change, or does the pop-up needed to be edited as well.

**Comment by bhumin-fw** [comment]
@chriscaldwell-psa popup text needs to be edit as well.
If you notice there is nothing which indicate that grace period is ending. It says form open period 12th to 30th june.
This popup message is goes live after July 14th when grace period end. hence no dynamic date was et so far.

**Comment by MeghanStothers** [comment]
@Stella-Archer let's look at this one today and see if any changes are required

**Comment by MeghanStothers** [comment]
Keep ticket open and look at this one to test next sprint

**Comment by bhumin-fw** [comment]
@Abuchana @Stella-Archer we can close this ticket now.

**Comment by Abuchana** [comment]
@bhumin-fw  @Stella-Archer I think so.
