### ISSUE TITLE
ODS API does not accept single quote on request data (JSON object)

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1131]
In cold and flu form we found that ODS endpoint fails if we pass single quote in any text value. 
e.g. "That's my office address"
Here it will fail to store above text and hence API request fail.

Digital Journey application uses same JSON object in all services and send the same to ODS Endpoints. 
Services like formio, camunda, python webapi and frontend reactjs.

How to handle?
We can select one path mentioned below,
1. ODS API will handle and accept it. (recommended)
2. Handle it in Digital journey system. It requires to update all touch points where we are moving "Form submission" object.

Edit:
Patrick raised ticket to CDATA (vendor). We are waiting on their update to take final decision.

**Comment by mikeshi-bcgov** [comment]
Vendor CDATA tech support has escalated the issue to their developers

**Comment by MeghanStothers** [comment]
Not a blocker for cold and flu launch, although this is an ODS issue under investigation

**Comment by iman-jamali-fw** [comment]
Based on the discussion with devs, we could do this ticket in other sprints.

**Comment by bhumin-fw** [comment]
Please review below screenshot showing how single quote replaced with double single quote at the time of sending form data to ODS.
![Screenshot 2023-07-19 at 12.09.16 PM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/7cd66ed6-b71d-411b-bc11-49da938a8457)

**Comment by Stella-Archer** [comment]
config & documentation set up
Closing - if another form need verification will check with mike then
