### ISSUE TITLE
Cold/Flu: ODS and data ware house available on ODS production URL

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1134]
As a user, I want that digital journey production From of Cold/Flu sends data on the ODS production URL and the same store on the production data warehouse instance.

Task:
- [x] Enable Cold/Flu related endpoints on ODS production URL
- [x] Load ministry list in the production database of data warehouse.
- [x] Review data received on this URL saves successfully on the production instance of the data warehouse.

**Comment by MeghanStothers** [comment]
@bhumin-fw - Thanks for writing up this ticket after deployment (plus the estimate :).  I have added the MVP label as these endpoints are needed for testing by the program area. Please bring this one up at tomorrow scrum  - thanks

**Comment by bhumin-fw** [comment]
Sure @MeghanStothers, I'll bring this one in tomorrows standup. - Thanks.

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 
1. Database deployed to ODS prod, endpoints created
2. Ministry list data transferred to pod

Please have test for Endpoints on Production https://analytics-api.psa.gov.bc.ca/apiserver/api.rsc/

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
I'm able to see ministry list and submit worksite and registration.
Added one worksite and 2 registration under that worksite. successfully able to edit worksite and registration.

Please confirm on your end, if every thing looks good or not. Let me know if you notice any bug or error in ODS side log for any requests.

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 
Confirm received in ODS.

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
In that case I can checked all the task as completed and move it to test column.
is it fine?

**Comment by bhumin-fw** [comment]
@Stella-Archer @MeghanStothers @ayushdamani 
ODS endpoints updated to production and ministry list has been load by Mike.

Cold/Flu form is now ready to test on Production environment on Digital Journey.
I have tested add & edit submission.

FYI: I have added one worksite location under ministry "Attorney General". And if you select worksite location "9887 Whalley blvd" then it will populate 2 registrations/clinics detail under that location.

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw 
Yes, you can test all scenarios.

**Comment by MeghanStothers** [comment]
@Stella - let us know if/when you're okay to send this link to Heather to test with her team.
As a first step, we'll want to test with on our team on Thursday May 17.

**Comment by MeghanStothers** [comment]
@Stella feel free to send link to Heather for her team to test

**Comment by Stella-Archer** [comment]
I met with Heather this afternoon walk through status and passed on production link. Heather will begin PROD testing and checking access now

**Comment by Stella-Archer** [comment]
Works fantastic Thx All. PO Approved. Closing tix.
