### ISSUE TITLE
Update timestamp on Form Edit

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1135]
Forms involving updates would require a script to be added to their update buttons to ensure the update timestamp is recorded. The script already exists on the Cold/Flu **Resubmit** button

For more information refer to #1117

AC:
Add the update timestamp script to the following forms and ensure their Last Modified timestamp is updated in the Submitted Form tab.

- Telework form when the supervisor approves/deny a submission
- SL: When the form is updated under the Submitted Form tab.
- Mat/Pat: when submission is updated by either submitter or manger

**Comment by MeghanStothers** [comment]
Iman noted that a small script was added to cold and flu - must be done for each form.  It is a bug we need to  fix for all forms

**Comment by MeghanStothers** [comment]
Iman working on this one this morning - in scope for SL

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 

This is ready to be tested on TEST.

**Comment by MeghanStothers** [comment]
Stella and Meghan tested - can be closed. PO approved Thanks Iman!
