### ISSUE TITLE
Cold/Flu: Change form title

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1137]
As a user I want to change form title to "2023 Influenza Clinic Worksite Registration" instead of "2023 Influenza Worksite Registration".

Task:
- [x] Change form title to "2023 Influenza Clinic Worksite Registration"
- [x] Update code base to recognise "2023 Influenza Clinic Worksite Registration" as a Cold/flu title and display correct primary contact information on draft list page and submitted form list page. ![Screenshot 2023-05-17 at 11.06.26 AM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/cb1a50db-975d-44ea-97ea-518234a7eedb)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/1970b9c0-bed9-4721-b54f-7dfbae48c7cf)

**Comment by bhumin-fw** [comment]
@Stella-Archer 
New title will be "2023 Influenza Clinic Worksite Registration".
Please correct me It if it's not. In the morning I got confirmation from the Heather over an email, I have forwarded it to you.
If we are changing it to "2023 Influenza Worksite Clinic Registration" please do let me know so I can fix that in codebase.

Note: we are moving word "clinic" before or after "worksite" in title.

**Comment by MeghanStothers** [comment]
Heather to confirm name today

**Comment by MeghanStothers** [comment]
confirmed name: 2023 Influenza Worksite Clinic Registration

**Comment by bhumin-fw** [comment]
updated cold/flu form title to "2023 Influenza Worksite Clinic Registration".
It is deployed to DEV and TEST.

**Comment by Stella-Archer** [comment]
This looks great Thx @bhumin-fw PO Approved - good to move to PROD

**Comment by Stella-Archer** [comment]
closing tix

**Comment by Stella-Archer** [comment]
Looking good in PROD still need to update name in PROD

**Comment by bhumin-fw** [comment]
We need to deploy code on production to support name change of form title. We can keep it open until we run next deployment on PROD.

**Comment by bhumin-fw** [comment]
@Stella-Archer 
Changes deployed to PROD. Updated form title as well.
It supports both old and new title, so you will be able to see "<title> for <name>" for your all old and new submission in cold/flu form.
