### ISSUE TITLE
SL: Front-end form content changes

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1139]
As a business owner, I want to have the content updated to reflect required changes need to make the for accurate and clear. 

A/C
Complete/approve the following 7 changes as described in the comments below

**Comment by MeghanStothers** [comment]
two change required for the "Intro" section
1) First bullet: remove the work "recent "
2) 4th bullet: replace "will" occur every two years with "SLR process "is expected" to occur every two years
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/3d4f82df-0fa2-47c6-a603-98c8d233f423)

**Comment by MeghanStothers** [comment]
One change required in the "Current Role section
- Expand this sentence to read: "Briefly describe the key accountabilities of the senior leader in their current role. You can add a maximum of three accountabilities: 
- ![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/5739c2dd-415f-4cd0-a5cb-bde7c037a956)

**Comment by MeghanStothers** [comment]
One change required in the "Accomplishments" section
Expand this sentence to read as follows: 
"Briefly describe the senior leader’s key most recent accomplishments over the last year or two. You can add a maximum of three accomplishments.”
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/8e7b86da-8630-4b1b-902e-29252f0b6e57)

**Comment by MeghanStothers** [comment]
In the "Expertise and Skills section
1) Remove "Executive Presence" check box in the "leading category"
2) Replace "Communication" with "Communicating effectively"
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/323f518b-ebc9-4569-8cb7-56e60af1e967)

**Comment by MeghanStothers** [comment]
IN the "Learning and Development" category:
-	Remove "Executive presence" in the "Leading" category  
-	Replace “Communication” with “Communicating effectively”
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/7b8a6298-2542-4ce7-81b0-6a93dced5c32)

**Comment by MeghanStothers** [comment]
In the readiness section:
1) add a small amount of text as follows:
“Based on your assessment of the senior leader’s responsibilities, achievements, expertise, skills, areas for learning and development, and any other inputs you deem relevant, select the most suitable description to indicate their readiness to compete for an executive role:”
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/01f2379c-a910-4546-b61a-4d5b72937300)

**Comment by MeghanStothers** [comment]
In the "Readiness validation and completed form submission" section 
- remove the words "on the system" 
- ![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/ff5d9d98-f8e1-4ad8-b2ad-4b29421c8a20)
-

**Comment by chriscaldwell-psa** [comment]
All edits have been updated in the SL Form - Dev Environment.

**Comment by MeghanStothers** [comment]
Thanks, Chris. We will test these with Jodi tomorrow

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/ca4fca57-27cd-4df9-ac28-994868d8ae85)

**Comment by Stella-Archer** [comment]
Add this link to ministry SLR Contact > 
https://teams.microsoft.com/l/entity/2a527703-1f6f-4559-a332-d8a7d288cd88/_djb2_msteams_prefix_3511159541?context=%7B%22subEntityId%22%3Anull%2C%22channelId%22%3A%2219%3Aoq2N-dqcy0Eb3NwXOKLaWUCSWJo16MSDl5jE9yg1P5c1%40thread.tacv2%22%7D&groupId=b79854d2-f88d-464e-bd31-c6cc2a3612fc&tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&allowXTenantAccess=false

**Comment by Stella-Archer** [comment]
Expertise and Skill section Updates looks great
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/febf0ae5-b36b-47d7-a996-2cbaf2850ec7)

**Comment by Stella-Archer** [comment]
learning & Development section Updates are also perfect!
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/b70cada3-1b4b-4098-b88b-49f9e843324f)

**Comment by Stella-Archer** [comment]
Readiness Section Updates complete :) 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/795ee486-464f-4078-b8c3-c0a967954d90)

**Comment by Stella-Archer** [comment]
and Finally the "Readiness validation and completed form submission" edit is perfect 
this tix is PO Approved & I'm closing it !
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/495bc31f-5e74-48f2-b6ec-eb232c606dfd)
