### ISSUE TITLE
SL: validation message wording changes in "Final Submission" section

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1140]
As a program area, we required accurate and updated language on the form

A/C

In the "Final submission" section, please make the following three changes:

1) Change the validation (checkbox) message 
From  “I have validated this senior leader’s readiness to compete for an executive role” 
To:  "This senior leader’s readiness has been validated”

2) Change the smaller (red) font validation message 
From:  "I have validated this senior leader’s readiness to compete for an executive role is required
To:  "Validation is required prior to final submission"

![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/03cf605b-a1b3-4ff9-a4b6-9d069d481e6a)

3) Update the current wording in the blue info bubble
From: Ensure ministry-specific validation protocols are followed prior to the September 29, 2023 closing date. Contact Strategic HR or DMO for further instruction"
To: “Ensure ministry-specific validation protocols are followed prior to final submission on or before the September 29, 2023 closing date. The ministry SLR contact can provide further instruction” 

(hyperlink "ministry SLR contact" to the MS Teams site with the list of ministry contacts - to be provided shortly)
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/9910e295-064d-4c28-9331-d46bc6aca638)

**Comment by MeghanStothers** [comment]
@JodiLittle Please send the general link to the Team channel - thanks!

**Comment by chriscaldwell-psa** [comment]
All changes have been made. Waiting for hyperlink as mentioned above.

**Comment by MeghanStothers** [comment]
@JodiLittle Please add the Teams link to this ticket so we can complete this work. Thanks

**Comment by Stella-Archer** [comment]
Issue 1 & 2 are fixed in TEST
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/029d6acc-a4eb-432f-b8e2-b92a717a3c18)

**Comment by Stella-Archer** [comment]
Issue 3 is also looking really great
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/11391e5a-a1d8-4c9e-92b7-39581c16972f)

**Comment by chriscaldwell-psa** [comment]
The hyperlink has been added to the pop-up.  Please test. Thx Chris

**Comment by Stella-Archer** [comment]
looks good in TEST
![1C5DFEAC-740D-43F6-B289-FE44F3C5970D.GIF](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/0d7ddfa9-a5a5-42ab-acf4-8dd11bfe5006)

**Comment by Stella-Archer** [comment]
looks fabulous in PROD - closing tix
