### ISSUE TITLE
SL: Edit to validation message and blue bubble info in the "Final Submission" section

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1142]
As a form submitter, I want to have a thorough and accurate alert box message when I make the final submission 

A/C _UPDATE THE TWO ISSUES NOTED BELOW

1) update the alert box message 

FROM:  "It is highly recommended that you have a conversation with the senior leader.  

TO: “It is highly recommended that you have a conversation with the senior leader about the SLR process and contents of this form prior to final submission”

![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/6b35bd0b-28b5-4518-a32d-066309093fef)

2) Blue bubble (question mark) language update/edit  
From: “Ensure ministry-specific validation protocols are followed prior to the September 29, 2023 closing date. Contact Strategic HR or DMO for further instruction”. 

TO: Ensure ministry-specific validation protocols are followed prior to final submission on or before the September 29, 2023 closing date. The ministry SLR contact can provide further instruction” 
(add hyperlink to the MS Teams site )

**Comment by chriscaldwell-psa** [comment]
Edits have been updated, waiting for hyperlink as mentioned above in the ticket.

**Comment by MeghanStothers** [comment]
@JodiLittle Hi there, please send us the Team link so we can close thicket and test. Thanks

**Comment by Stella-Archer** [comment]
1/ Message edit is good.
2. Blue 'Info'/'tool tip' bubble is also correct. The link that needs to be added is in tix #1140
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/96a22dd1-f07a-45c0-a5ea-e05ad29bf12a)

**Comment by Stella-Archer** [comment]
PO Approved and closing this tix
