### ISSUE TITLE
Cold/Flu: Post UAT/UX testing updates email & label

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1143]
1/ add the link back to the digital journey’s platform in this success message where we instruct users how to edit during the registration period. 
link highlighted text to: https://digital-journeys.apps.silver.devops.gov.bc.ca/application
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/0906adca-db7d-458b-b5e7-0a26ca9ed223)

2/ Add "Street name" in brackets after "Address" as some people might get mixed up and think they should put the whole address (incl. #) in that box
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/3c2cc6d7-1c19-4cea-8d53-b11cab9218a9)

**Comment by MeghanStothers** [comment]
Stella and Meghan to connect with Heather to request Friday June 2 as the final date to deliver all findings from testing

**Comment by MeghanStothers** [comment]
Heather and team will be testing with team her the week of May 23 and sending Stella any findings/bugs for priority order.

**Comment by ayushdamani** [comment]
Tested and confirmed working ✅

![Screenshot 2023-06-06 084204.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/557d2c66-6732-46d2-909c-32f315dc6512)

![Screenshot 2023-06-06 084456.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/337509ca-5389-4092-8ebe-f2933a552490)

**Comment by Stella-Archer** [comment]
looks great on TEST links worked perfectly as well, ready to Deploy to PROD
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/0b2271a8-8c63-479a-bcf3-f6d83e6276fd)
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/6360fffc-f587-4d45-b9a3-6daac13b7903)

**Comment by Stella-Archer** [comment]
all perfect in PROD - closing
