### ISSUE TITLE
Cold/Flu: Field validation UX/UAT Testing feedback

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1145]
Please add validation to ensure the following field are mandatory:
1/ “**Phone Number**” field required under “**Worksite Contact**” section
– noticing that users can submit the form successfully without it.
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/ea8ac6b7-4486-4c5d-a0ac-54bfcabb20b6)

2/ “**Will the team be relocating**” field required under “**Registration Information**” section

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/5aec7655-fd19-491d-85ac-2d9b9ecc4a5d)

**Comment by bhumin-fw** [comment]
@Stella-Archer 
Is phone number for secondary contact is required?
As per my understanding secondary contact detail is optional.

**Comment by Stella-Archer** [comment]
@bhumin-fw Correct thanks for the flag -  only primary contact is mandatory

**Comment by bhumin-fw** [comment]
@Stella-Archer @chriscaldwell-psa 
Is there anything that needs to verify and review on this ticket? if not can we move this ticket to TEST?

**Comment by Stella-Archer** [comment]
@bhumin-fw  no good to move to TEST

**Comment by Stella-Archer** [comment]
this works perfect in test please move to  PROD. PO approved
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/0860768c-62f0-45df-8e5d-d5021024e406)

**Comment by Stella-Archer** [comment]
this is working just fine in PPORD as well
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/4167082c-d250-41e1-a29c-39c3e40fed2e)

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/4dfdf4cf-7ad4-43b3-838f-15cc70e37d06)
Approved & Closing TIX
