### ISSUE TITLE
SL review: Updates to options in "Check box" sections

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1149]
please update the following options:
1/ Expertise and Skills Section - Leading
Change “Valuing Diversity and Inclusion” to “**Championing Diversity and Inclusion**”
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/eda559eb-50c8-496f-8fe1-bc3d68f1a27c)

2/ Learning and Development Section – Leading
Change “Valuing Diversity and Inclusion” to “Championing Diversity and Inclusion”
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/2309da13-ea54-4eba-9137-3d68cecb3ff8)

**Comment by chriscaldwell-psa** [comment]
Both check-boxes have been updated.

**Comment by Stella-Archer** [comment]
Thanks @chriscaldwell-psa This Looks great PO Approved and closing this tix
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/9ae57650-613e-48bb-b56a-18695577defe)
