### ISSUE TITLE
Apply Styles to Admin/Designer tables & experience

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#115]
As a formsflow.ai Designer I would like a clear, easy to understand administrative experience so that the tasks of creating and managing forms is clearer and easier.

**A/C**

See [Figma design (Option #2)](https://www.figma.com/file/gQDAaN0lnJJj1xg6NXFEsI/Wireframes?node-id=462%3A9796)

- Table styling
- Update Applications tab to match design
- Clean up task tab (mostly just the header)

**Comment by jchow11** [comment]
**Forms**
[https://app.zenhub.com/files/439477060/1380dd56-14e4-4c79-ac0c-196fdf40e9f6/download](https://app.zenhub.com/files/439477060/1380dd56-14e4-4c79-ac0c-196fdf40e9f6/download)

**Applications**
[https://app.zenhub.com/files/439477060/12adb608-d8c9-44c5-956a-110b1eefd794/download](https://app.zenhub.com/files/439477060/12adb608-d8c9-44c5-956a-110b1eefd794/download)

**Tasks**
[https://app.zenhub.com/files/439477060/2c772233-46cc-42d4-b7b9-fd7e852c01f3/download](https://app.zenhub.com/files/439477060/2c772233-46cc-42d4-b7b9-fd7e852c01f3/download)[https://app.zenhub.com/files/439477060/f1606e58-43aa-443c-bd57-ab6d1977012f/download](https://app.zenhub.com/files/439477060/f1606e58-43aa-443c-bd57-ab6d1977012f/download)

**Admin Dashboards**
[https://app.zenhub.com/files/439477060/c3122217-e299-45c2-a5a9-1a5941526e49/download](https://app.zenhub.com/files/439477060/c3122217-e299-45c2-a5a9-1a5941526e49/download)

**Admin Tasks**
[https://app.zenhub.com/files/439477060/fb76f535-ad30-4faa-9133-16188c633b29/download](https://app.zenhub.com/files/439477060/fb76f535-ad30-4faa-9133-16188c633b29/download)[https://app.zenhub.com/files/439477060/f13d57b2-a316-4e92-b57e-6a60f577e272/download](https://app.zenhub.com/files/439477060/f13d57b2-a316-4e92-b57e-6a60f577e272/download)[https://app.zenhub.com/files/439477060/712185ba-d22c-44b5-97d4-0864517ba1a4/download](https://app.zenhub.com/files/439477060/712185ba-d22c-44b5-97d4-0864517ba1a4/download)

**Admin Forms Directory**
[https://app.zenhub.com/files/439477060/3dc3fa8d-0cc7-40d0-a5f9-5779e66293db/download](https://app.zenhub.com/files/439477060/3dc3fa8d-0cc7-40d0-a5f9-5779e66293db/download)[https://app.zenhub.com/files/439477060/2d247fb3-ec85-41c8-939e-6142ed22e0eb/download](https://app.zenhub.com/files/439477060/2d247fb3-ec85-41c8-939e-6142ed22e0eb/download)

**Comment by jchow11** [comment]
**Forms**
![Forms.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/2abe26d5-4568-4efe-b830-31eb89db96ff)

**Applications**
![Applications.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/4f40b2d6-745f-4594-a892-bdc6bcea4985)

**Tasks**
![Tasks-Applications tab.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/92851725-bf4a-4af5-8f09-3cc739933208)![Tasks-History Tab.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/034d6fb2-9ebe-4117-805f-3546c99a507a)

**Admin Dashboards**
![Admin Dashboards.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/8b69dbff-aa0d-4756-b41b-55bcae128867)

**Admin Tasks**
![Admin Tasks- unclaimed submission.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/3d2d8e2e-0aa9-4a84-b636-de84cce5050e)
![Admin Tasks - change assignee hover.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/278cd7bf-ceb4-4423-b6d9-836bd59a9aa9)
![Admin Tasks-dropdown menu.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/41be8db3-61db-4aee-ac21-0d02daaf1d22)
![Admin Tasks-reset assignee hover.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/76ea59f6-5737-4f96-99fd-7d399390b74f)

**Admin Forms Directory**
![Admin Forms Directory.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/ce4735d2-a4ee-4e95-aca3-188f21d98bde)
![Admin Forms Directory-delete modal.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/6aef905f-201a-4ba9-8aff-efa226597ce2)

**Comment by warrenchristian1telus** [comment]
Converting this to an epic, so we can break out tasks into their related buckets for styles, workflow, or UI changes.
