### ISSUE TITLE
Cold/Flu Personal phone number are prepopulating primary contact field

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1152]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
“As a user registering a clinic I want to have my WORK/UC telephone number prepopulate so I can get have the contractor call me at WORK to book my worksite clinic. I do NOT want to share my personals information/phone number with an outside contractor.” 

**Tasks**
Currently the primary contact phone number is pulling users personal phone number
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/2b02d79b-bb68-476d-a700-a7072303034c)
please check and confirm the source we are getting this number from and change to 'office Number'

**Acceptance Criteria**
Users personal numbers do not appear on the cold and flu form

- Update ODS endpoint
- Make the field editable
- Add a validation message to make sure people add their work numbers. 
- Change field name to "work email" - NOT MVP

**Comment by Stella-Archer** [comment]
@mikeshi-bcgov @T854236 when I look at the response that we are getting from the ODS API.I see the Office Phone has no value or"" why is that? Why would the office number not be available? could we change this? we can't expose employees personal phone numbers to a contractor that would be a privacy breach.
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/783a0685-17be-4dce-8cd2-d42c5186b58c)

**Comment by Stella-Archer** [comment]
Could we point at "office_phone": "" so we're not exposing peoples personal information?

Currently the  Primary phone number is not editable for regular user.
It is editable for admin user only.

I'll check in with Heather to see if we can change that 
 to make phone number editable for primary contact. 

The field is mandatory so we can label it "work phone number" and then they'd be forced to enter it manually

**Comment by T854236** [comment]
@Stella-Archer office_phone is pulling from a table in PS where it is manually populated by the employee.

**Comment by bhumin-fw** [comment]
@Stella-Archer 
I have changed the below points. and changes are up and running on DEV and TEST.
- Map primary phone to office_phone field from the [ODS](https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_employee_demo) response.
- Enable field to edit (this field was already editable based one of the previous ticket works)
- Change label/title to "Work phone number". Apply the same on both primary and secondary contact.
- Added the same label/title in the validation message.
- Added required field and format match validation.

**Comment by MeghanStothers** [comment]
Tested in test and report: 
1) "work phone number field has been enabled to edit 
2) label/title changed to to "Work phone number".  Apply the same on both primary and secondary contact.
3) validation is working for this field as expected

**Comment by MeghanStothers** [comment]
Will need Patrick or Mike to see if the field is properly mapping to ODS

**Comment by T854236** [comment]
@MeghanStothers in ODS it is just called phone and we do see a series of tests with last one at 2023-05-25 16:10:13.

**Comment by bhumin-fw** [comment]
@T854236 
right, we are calling an [API](https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_employee_demo) to pull employee's data. In Stella's first comment you can see that "phone" field contain Stella's private number and not work number.
We need to fetch work phone some how. What are the option here to fetch it?

**Comment by T854236** [comment]
@bhumin-fw 

Sorry for clarity, employee demographic endpoint has both the personal and office phone number as per the screenshot provided by Stella.  

The phone number and test confirmation I was referring to is with the submission and was confirming that a record was created which is exposed with the influenza_contacts endpoint.

**Comment by bhumin-fw** [comment]
@T854236 thank you for detail :)

**Comment by Stella-Archer** [comment]
The phone number field is blank and forces user to enter their work Number 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/925e847c-085c-4566-b437-02a9fb0d4f80)

**Comment by Stella-Archer** [comment]
we will continue to explore long term solutions to WORK phone number this is captured in tix  #1157
PO Approved and closing this
