### ISSUE TITLE
SL Review: Delay in final validation 

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1158]
**Background:** 
In TEST when you submit the form for final validation there is a very long delay before the action is processed and the validation message is displayed
 
Steps to Reproduce:

 
Actual Behavior:
![C8FB8B42-FEB6-4D19-B27E-0204262670FE.GIF](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/0e8bcede-7f1c-42f3-bcc0-5fc53527f2fa)
 
**Expected Behaviour:**
 the "Final submission" confirmation message would display in a reasonable time similar to the "submit for validation" process

**Environment:**
TEST

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 
This is ready for testing on TEST.

A new loading indicator was added when forms are updating. For testing check the followings:
- Senior Leadership form
  - Open a submitted Senior Leadership form under `Submitted Forms` and check the loading when clicking on `Resubmit for validation` and `Final submission`
- Cold/Flu
  - Open a submitted Cold/Flu form and check out loading when clicking on `Resubmit`
- Mat/Pat
  - Same thing for a submitted Mat/Pat when clicking on `Resubmit` under `submitted forms` and `Validated ` under `Review and Process Form`
- Telework
  - Same thing with Telework under `Review and Process Form` when clicking `Submit decision`

**Comment by ayushdamani** [comment]
The loader works great, thank you!

Just a snapshot of the new loader - 
![Screenshot 2023-05-30 090528.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/35b93fd9-8cb4-49c1-bd58-96ea224839ff)

**Comment by MeghanStothers** [comment]
PO approved - tested
