### ISSUE TITLE
Consistent SL Review Keycloak group-role-mapping

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1159]
Keycloak has groups and roles, which are used to manage permissions in an application. Normally, the mapping between a group and a role is based on their names being the same. However, there is one particular group called "sl-review-adm" that is not mapped to a role with the same name. Currently, this group is mapped to the "employee-search" role.

Different parts of the application, such as the API, Camunda, and the website, depend on these group and role names. If we consistently use the same name for both the group and the role, it would make the features based on roles more reliable and easier to implement. For example, we could easily enforce a universal form-lockout feature or allow role-specific access to certain forms.
![Screenshot 2023-05-29 at 9.02.12 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/70b46026-ec9f-4a3f-aa92-ccef8ab97845)

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 

Ready for your test on TEST. For testing, you just need to search for an employee on the SL form to make sure the changes in role name mapping did not break anything.

**Comment by ayushdamani** [comment]
Thank you for the instructions, Iman!

I tested this, searched my name and everything seems good ✔️

![Screenshot 2023-05-30 085656.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/1075df44-6631-46a9-8879-776f2b3ab86b)

**Comment by MeghanStothers** [comment]
@iman-jamali-fw @bhumin-fw This ticket has been tested by our team on the front-end - is there any way for us to test the make sure the changes in role name mapping have been completed or are we okay to close this ticket as per Ayush's test/notes above in this ticket?

**Comment by bhumin-fw** [comment]
In keycloak Iman change that role name to align with group name. It was updated by default for all existing sl-review-adm group user.
So if you are sl-review-adm then you will be able to see SL review form in form list page and search employee by their name. 
If this looks good, We are ok to close this ticket.
