### ISSUE TITLE
Tool: Reporting dashboard for program area/dev team

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1165]
as a program area, I would like to start mapping out a digital journeys internal  dashboard that might be of value to our team as well as the clients

For example - what ministry they belong to?

**Comment by Stella-Archer** [comment]
1/ workshop out needs/Requirements

2/ What do we need to know about our program/tool.
- How many submitted
-  How many stuck?
- Do we just need data

**Comment by Stella-Archer** [comment]
Also reference ##1212

**Comment by Stella-Archer** [comment]
Chris prepared a workshop to explore this https://miro.com/app/board/uXjVNhtZh_4=/. 
Action: Andrew to explore Redash capabilities to see if they can meet our reporting goals with the product
