### ISSUE TITLE
SL: Form pulling in personal/home city, rather than city associated with workplace

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1166]
As a form filler, I expect the field "city" to be populated with my city workplace location, rather than my personal/home location.

**Comment by Stella-Archer** [comment]
In PROD after deployment we noticed the city field was pulling from users personal addresses not work addresses
as below could we check the end points and fix?
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/d7d6d94d-2ab0-46fc-8d70-7b2135fb10c0)

**Comment by Stella-Archer** [comment]
TECH Note form @Andrew-Vargas-bcgov:  office_city, in the search name component  needs to change that from input.city to input.office_city.

**Comment by Stella-Archer** [comment]
and FIXED!!! wooohoo! PO & closed

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/af1cb3ec-2bf8-4dd1-a9f2-3171e71bc69c)
