### ISSUE TITLE
Cold and Flu: Form populates with home postal code, not my workplace one

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1167]
As a form filler, I want the form to populate with y workplace postal code, rather than my home/personal one when I register a new worksite

**Comment by Stella-Archer** [comment]
when I as a user don't see my work site and go to create a new one it default to my HOME postal code
it should either pull my office postal code from the ODS or no default postal code at all
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/95473917-0647-451c-8502-16c5acf47245)

**Comment by bhumin-fw** [comment]
Thanks Megan for the ticket. It accidentally match with the API name with employee field name.
I'll work on it and fix this by tomorrow.

**Comment by bhumin-fw** [comment]
@ayushdamani @Stella-Archer 
It will not populate city and postalcode of user's home  location. It will keep the field blank.
These changes are up and running in DEV and TEST.

**Comment by MeghanStothers** [comment]
@Stella-Archer can someone test this one to close? Ayush are you able to test this one, please?
