### ISSUE TITLE
Telework - Supervisor submit decision button not checking for required fields

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1168]
When a supervisor clicks on `Submit Decision`, the form doesn't check for the required fields in manager/supervisor sign-off section.

![Screenshot 2023-05-30 at 8.53.11 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/c6020e5a-a2a9-4333-b573-0b75e156b2b3)

**Comment by iman-jamali-fw** [comment]
@MeghanStothers 
Turned out this is not a bug, but simply fields in the manager/supervisor sign-off section no longer required. I wonder if this was intended to change or slipped through our hands. Do you remember which fields used to be required?

**Comment by iman-jamali-fw** [comment]
Technically `Decision` must be required otherwise submission will fail, so I made that required to avoid any failed submission (on all environments) waiting for the team to confirm which other fields in the supervisor sign-off section should be required.

**Comment by MeghanStothers** [comment]
@Stella to confirm which fields are required.

**Comment by Stella-Archer** [comment]
If less than 3 days is requested  mandatory fields are:
1/ Agree to box must be checked
2/ Managers name
3/ Decision
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/ca22471d-2891-4102-b48a-6344fe81a154)

**Comment by Stella-Archer** [comment]
If 3 days or more are requested, mandatory fields are:
1/ Agree to box must be checked
2/ ADM (or delegate)name
3/ Upload 'proof'
4/ Manager name
5/ Decision

**Comment by Stella-Archer** [comment]
less than 3 days is looking great in TEST Now!!! YAY @bhumin-fw 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/f11c54a7-2cf7-4317-b0f7-00fbb036c262)

**Comment by Stella-Archer** [comment]
more than 3 days is also working perfectly in TEST ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/1839d0fe-6f1e-4738-b54d-3725b1e00ecf)

**Comment by Stella-Archer** [comment]
3+Day validation functioning correctly in PROD ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/61d57fb2-cca2-468e-9a0a-2ffa4701b89d)
