### ISSUE TITLE
Cold and Flu: Submit button (on re-submit) doesn't let user know the form has been updated since the initial submission

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1169]
When a form-filler submitter goes back into the "edit" function to update their initial submission, there isn't a message to indicate their information has been updated.

A/C
- Add a confirmation message (from the initial submission) or something else

**Comment by MeghanStothers** [comment]
@bhumin or @iman-jamali-fw new cold and flu bug on the board - happy to chat if more info is needed.

**Comment by iman-jamali-fw** [comment]
@MeghanStothers 

Do you mean adding something to the confirmation page which is shown after a successful resubmit to indicate the submission has been updated? Are you looking into the confirmation page content change?
Below is the current confirmation page:
![Screenshot 2023-05-30 at 11.41.17 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/9d4241fd-6572-4eff-91a2-ca96de78a477)

**Comment by Stella-Archer** [comment]
Thanks @iman-jamali-fw showing the confirmation page one re-subimit would do it

**Comment by bhumin-fw** [comment]
@Stella-Archer when someone edit form below page will display. We have changed title of it.

![Screenshot 2023-05-30 at 5.37.25 PM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/0015ce3e-ce83-487d-9729-1a77ff15a707)

**Comment by bhumin-fw** [comment]
@Stella-Archer I have changed EDIT form success page. Title was confirmed by heather. Still you can double check  on your end.
Deploy new success page in DEV and TEST and ready to test.

**Comment by Stella-Archer** [comment]
yay looks good approved & Closed
