### ISSUE TITLE
SL Review: Text edit - Remove 4th Intro bullet 

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1170]
Please remove the 4th bullet 
“SLR process is expected to occur every two years – there will be opportunities for other senior leaders to come forward through a future process”
 ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/09d8fa15-af87-4ea4-af63-2253250e41ea)

**Comment by Andrew-Vargas-bcgov** [comment]
removed in all environments
