### ISSUE TITLE
SL Review test forms and submissions cleanup

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1174]
**SL Review test forms and submissions cleanup**

- [x] Clean up SL Review practice forms and their submission from DEV and TEST Environments
- [x] Clean up SL Review submissions to have clean reporting from PROD

**Comment by iman-jamali-fw** [comment]
@MeghanStothers 
Currently, there are 9 SL submissions in PROD. Please let me know if you want them removed from the DGJ platform (they will still exist on ODS). I suspect only one of them is not a test submission. List of those 9 submissions is attached below:

![Screenshot 2023-06-01 at 1.36.08 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/e59d1ef7-faf4-4c24-91ce-73fb91f5bc7a)

**Comment by MeghanStothers** [comment]
@Jodi - can we go ahead and remove all test submissions except for "Turton" one - is that one our first real submission?

**Comment by JodiLittle** [comment]
Yes - even the turton one is a test

**Comment by iman-jamali-fw** [comment]
All SL test submissions were deleted from PROD.

**Comment by Stella-Archer** [comment]
confirmed - PO Approved and closing
