### ISSUE TITLE
TOOL: Permissions managed from multiple places, explore universal

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1175]
**User Story**
“As a Developer I want have a universal way to manage roles and permissions in one space so I can get have a simpler more efficient process.” 

**Tasks**
Steps needed to achieve this feature. 

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.

**Comment by fazil-ey** [comment]
Role Management is potentially going to be in future forms flow versions. This is not a very pressing issue in DJ for us right now. Cold and Flu is the only form where we have an "admin" role, and we have that process figured and works well. 

So not a priority and we do not want to invest in custom developing this when it might be in future forms flow versions. Closing.
