### ISSUE TITLE
SL Review: Update language on introduction section

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1177]
**User Story**
Update language to align with direction from Comms team (Reviews is plural, remove 'process')

**Tasks**
Form introduction:
•	First bullet, change to “Senior Leadership Reviews (SLR) are a commitment that will support the DMCPSR talent and executive priorities. They address input received from deputy minister talent conversations and respond to an increase in movement at the executive level”
•	Second bullet “The SLR supports…”
•	Third bullet “The SLR provides…”
•	Last bullet change to “Visit the MS Teams Senior Leadership Reviews site…”

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/bcaf030c-73f4-4ece-8d37-7f8a9b8e4ea8)

**Comment by ayushdamani** [comment]
Thank you, Andrew!

![Screenshot 2023-06-06 092533.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/806f0d72-1168-4423-af8d-f52246fa6391)

**Comment by Stella-Archer** [comment]
Looks perfect in TEST ready to deploy to PROD
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/7791e764-7aa1-4f68-8ff5-31551a264dc4)

**Comment by Stella-Archer** [comment]
perfect in PROD = closing
