### ISSUE TITLE
SL Review: Update to final confirmation message

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1178]
**User Story**
Update language to align with Comms team directions

**Tasks**
Pop up message after “Submit Final” button has been selected:
•	Third bullet – Remove
•	Last bullet – remove “Thank you.”

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/28d0f05d-3043-46d7-93ee-0324f0daf4db)
**Acceptance Criteria**

**Comment by Andrew-Vargas-bcgov** [comment]
created pr for this change, waiting on approval to test.

**Comment by Stella-Archer** [comment]
this looks great
• Third bullet – Remove
DONE
• Last bullet – remove “Thank you.”
DONE
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/083487fa-bd6e-468a-9dcd-49a52a3a2f53)
@Andrew-Vargas-bcgov  please move to TEST thanks

**Comment by MeghanStothers** [comment]
ready to move to test

**Comment by ayushdamani** [comment]
Acceptance criteria met - closing ticket

![Screenshot 2023-06-12 092739.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/b778dc7e-0f31-4ec4-b792-7f595c867d9e)
