### ISSUE TITLE
Cold and Flu: Making form live in prod to all users Jun 12

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1184]
As a program area, I would like to ensure all users (acorss the public service) have access to the form on the launch date of June 12.

A/C

< > Stella/Meghan to connect with Heather and confirm the date the form will go live (suggest Monday June 12 to align with COMPASS artcile)
<> give users access to the prod environment in the DJ dashboard 
< > test access with non-admin user groups

**Comment by MeghanStothers** [comment]
Recommended by Bhumin and IMan:  releasing the form to the public on Friday to give us enough time to test and verify the changes. We could start the deployment to PROD Friday afternoon if the team feels comfortable with that, or after hours.

**Comment by MeghanStothers** [comment]
New plan die to team testing availability  
Deploy changes on Friday as planned
Bhumin and Iman to do preliminary testing 
Stella's test to start testing earlier on Monday

**Comment by MeghanStothers** [comment]
@iman-jamali-fw aand @bhumin-fw form owner/Heather gave approval to push everything to prod tomorrow afternoon (Friday June 9) and we will let her know asap of there are any issues before the link is shared with all users on Monday morning. Three cheers - we're almost there.

**Comment by bhumin-fw** [comment]
@Abuchana Yes
