### ISSUE TITLE
SL Review: Post launch UX text Update

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1185]
**User Story**

“As a user wanting to nominate a leader, I want to note their skills in 'issues management' so I can  accurately describe an important leadership competency.” 
 Add it to both sections right above “Risk Management”

**Tasks**
add “issues management” to the SLR form under the two sections
* [x] “Expertise and Skills” and 
* [x] “Learning and Development”

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/672b8a21-3a8f-4699-8f63-c23450e1cd8d)

**Acceptance Criteria**

**Comment by chriscaldwell-psa** [comment]
Issues management has been added to both sections (dev env).

**Comment by Stella-Archer** [comment]
Thanks @chriscaldwell-psa  this looks great could you push in to TEST? Thx!
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/4a0ce87f-7da6-447c-b8e0-6ff2926a9352)

**Comment by ayushdamani** [comment]
Confirmed updated ✅
- Issue management appears “Expertise and Skills” and “Learning and Development”

Closing ticket.
