### ISSUE TITLE
Cold/Flu: Add @pensionsbc.ca to email domain list

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1186]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
“As a cold and flu clinic register from the BC Pensions, I want to be sure  @pensionsbc.ca is on the email domain list  so I am able to register a clinic and get confirmation emails .

**Tasks**
Add @pensionsbc.ca to email domain list

**Acceptance Criteria**
@pensionsbc.ca is included in the allowable email domain list

**Comment by chriscaldwell-psa** [comment]
Added  domain custom validation to both the Worksite contact and secondary contact Work email "pensions.bc.ca".
Dev Env.

**Comment by Stella-Archer** [comment]
Sweet @chriscaldwell-psa  works fantastic  - Could you move it to TEST? Thanks for the quick work on this!
![E5DEC6B9-6E2F-4E72-8AC1-7041CFBF4914.GIF](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/6bae0aa4-fae5-4912-ad19-b374c366f1bf)

**Comment by chriscaldwell-psa** [comment]
@Stella-Archer  Your welcome,  update has now been moved to test.

**Comment by Stella-Archer** [comment]
Sweet works fab in both primary and secondary contact in TEST
PO Approved Ready to deploy to PROD
Thanks @chriscaldwell-psa 
![4D2E957C-7CEA-49A7-90E1-8BFF662210C7.GIF](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/d987f68e-2879-47d5-a2e6-5e42717479ec)
