### ISSUE TITLE
Add validation on required fields to the Telework form

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#119]
**Description:** As a user, I want to know which fields are required and which are optional.

**Acceptance Criteria:**
- Proper error messages should populate if the user tries to submit the form without filling in the required fields.
- User should not be able to submit the form without filling in the following required fields: 
 ![Screen Shot 2022-03-02 at 3.06.29 PM.png](https://images.zenhubusercontent.com/61c1108df318d4181d4d764d/88c56f34-8d66-4b93-8429-7e3b7c27ba59)

**Comment by qudsia-khan-fw** [comment]
@schuyt On the sheet in the ticket, we have fields "personal phone" and "business phone"; however, those fields are not currently on the telework form. What is the requirement?

**Comment by schuyt** [comment]
This sheet was based on the Orbeon form they trialed last year.

Let's ask Don in standup today. I'm thinking we either ignore those fields, or add them to the Tele-work form if they're required.

**Comment by qudsia-khan-fw** [comment]
New requirement for clients: Only comments are optional and from section 5, both fields are required but only the one that is selected by the user should be displayed
