### ISSUE TITLE
Mat/Pat - CRM - PDF (server side)

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1192]
Split from #1100
The CRM ticket must contain a pdf of the form attached as well

- [x] The ticket should contain the form attached as a pdf 
         - The pdf should contain only the review & certification pages in the form 
         - the pdf should contain the form name & logo

**Comment by Stella-Archer** [comment]
@iman could you give us an estimate for this? Thx :)

**Comment by fazil-ey** [comment]
Pulling it in because it is being work on right now. @bhumin-fw  can you estimate this?

**Comment by bhumin-fw** [comment]
Ticket is ready to test on TEST environment.
If you don't see header (Logo + form name) in attached PDF. Please do let me know and I'll update it as soon as possible (due to some form edit and update that part gone missed so).

**Comment by ayushdamani** [comment]
Could not test this:
1. Submitted a Mat/Pat form.
2. Could not validate my submission to generate the CRM ticket.
Error faced: The form loops back to the 'Before you begin' page.

Next steps:
- I have submitted a form with Stella as my supervisor - would request her to try to validate my submission.
- If the above does not work, I would request Meghan/Stella to submit a form.

**Comment by fazil-ey** [comment]
I can confirm we are receiving PDF in the emails, but we need to check in CRM itself is the pdf attached. That has to be tested by someone who has access to CRM.

**Comment by fazil-ey** [comment]
Tested in checkin, CRM ticket has pdf attached, and pdf is rendered properly. Pdf name could be changed to form name from just "attachment.pdf", but captured that in #1308
