### ISSUE TITLE
Cold and Flu: Ministry drop downs

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1194]
As a person wanting to register my workplace clinic, I will need access to a ministry drop-down to register my worksite and to ensure this data/information is being captured in the reporting.

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
do you have any update on ministry list API endpoint?

**Comment by bhumin-fw** [comment]
API Request audit, It seems requests are stable for the rest of the week.
![image.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/a5f8a444-3328-4468-be89-da2a302b0d5f)
