### ISSUE TITLE
Mat/Pat - Change fields to required before submit

### ISSUE THREAD

**Issue by Andrew-Vargas-bcgov** [bcgov/digital-journeys#1197]
Two fields need to be changed to required before submitting the initial form:
1. confirmInfo - this should be set to required for all submissions.
2. confirmPartnerInfo - this should be set to required when the field doesYourPartnerWorkForBcPublicService == yes 
    -  "Get Info" on "Parental Leave - Partner's Information" must be entered and information must be fetched if it hasnt been done, before going to next page

**Comment by Andrew-Vargas-bcgov** [comment]
you can check this by submitting an application without selecting that your information is correct in any tab.

**Comment by ayushdamani** [comment]
Confirmed updated - logic is working great!
Thanks, Andrew!

**Comment by fazil-ey** [comment]
Works well, the validation happens only on the review page
