### ISSUE TITLE
Unexpected error when authenticating with identity provider - User unable to access Telework agreement page.

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1206]
Background: A new employee - Ilaine M.  is unable to access the Telework Agreement Page. When she tries to access the page she receives the following error message: "Unexpected error when authenticating with identity provider"
 
Steps to Reproduce: 
 
Actual Behavior: Receives error message
 
Expected Behaviour: Can access the telework form 
 
Environment: Prod

I will send the email to Iman (June 15th) for troubleshooting and will include their IDIR in the email as well.

**Comment by iman-jamali-fw** [comment]
I escalated the issue to the SSO team. Will update the ticket once hear back.

**Comment by chriscaldwell-psa** [comment]
We have another employee with the exact same issue of not able to login to the telework form. Employee name: Julia C from ministry of Env. I will send the email (with IDIR) to Iman. Thanks

**Comment by MeghanStothers** [comment]
Meeting set up for Friday Sept 8 with a contact to help us develop a better understanding of the issues: IDIR/OCIO/Siteminder/BCeID 

Decision needed about how to troubleshoot, how much effort our dev team should be and look at other solutions: such as addressing this in the DJ mailbox team and or/form owner communications when the Telework form is expected to be upgraded in Fall 2023

**Comment by chriscaldwell-psa** [comment]
this ticket can be closed as we have info being tracked in ticket 1237.
