### ISSUE TITLE
Telework Update:  "Official Office Location" field to support New Policy for the BC Public Service Employees 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1207]
As form owner, I will need updated information on the current form to include:

support the updated policy: “Central to this policy adjustment is clarity around an employee’s “official office location”.

get data of official office location to record and report on how how any work-related travel costs will be paid consistent with applicable financial policy.”

A/C

* [x] 1. add a field (or fields) "Official Office location" to to the front-end of the form 
* [x] 2. realign numbering sequence
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/9b484089-c308-4ad5-8407-25c9178b39e0)
* [x] 3. add an info bubble to give users the following definition:
_The government office where you work (or would work) when not teleworking and your headquarters location for business travel. Please confirm your headquarters location for travel with your supervisor._
* [x]  4. Add new bullet  point to section 10:
Supervisors and employees should also confirm an understanding of how any work-related travel costs will be paid consistent with applicable financial policy
 ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/8eacc4d6-4901-4d80-8493-fc971e23ee38)

**Comment by Stella-Archer** [comment]
@iman-jamali-fw  Required: city and address Not required: business phone 
Proposed launch date: Monday, July 17 so we need to come p with a plan to ensure we can get this live then no matter where we are in the upgrade @MeghanStothers @warrenchristian1telus  did you hear anything about the namespace ask?

**Comment by chriscaldwell-psa** [comment]
The following updates have been added:
Location: Under the The employer and the employee agree to the following' panel: Official office work location header added with 3 fields: street address, city and business phone. Note: you cannot put a tool tip on a header, therefore the tooltip was added to the Street address field. Please test to make sure this looks OK when hovering over the tool tip. 
2) The form has been renumbered due to the insertion of the Official office work location.
3) Under Costs - the last sentence is new and has been added bases on the added context listed above in the ticket. The  telework will be moved to test.

**Comment by Stella-Archer** [comment]
Nice work @chriscaldwell-psa - so quick!
Could you use the pop up style info box here? The text area is to big to read on top of the background :(
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/1925eb6b-9116-4a57-b7fb-abc6f1cae20b)

**Comment by Stella-Archer** [comment]
this looks good 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/a6ab4282-447b-4991-9def-6582e326d20d)

**Comment by Stella-Archer** [comment]
Remove bullet in the Before teleworking section ‘The employee is regular full-time or regular part-time.’ 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/3ef6b4e6-bc74-444d-a493-3cf85abe92ce)

**Comment by chriscaldwell-psa** [comment]
Updates are complete and ready for test.

**Comment by Stella-Archer** [comment]
Almost there
* [ ] 1/ Delete the "Business Phone" & box so HQ info looks just like 'Telework location' ask
* [ ] 2/ The small text is to difficult to read. Put an asterisk on the Headquarter location*
and the definition, start with an asterisk
* [ ]  3/make the text for the definition and the "Your Supervisor must approve..." line same size as the 'I acknowledge' text above 
* [ ]  4/ line break between definition and supervisor line
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/6b236611-9b35-4894-92fd-65ff763ed101)

**Comment by chriscaldwell-psa** [comment]
Updates made. Text size was increased. It cannot be matched exactly to that check box text since they are entirely two different components. I think it looks close as possible. API names where changed with the duplicate address  etc fields so info is not pulled from the ODS.

**Comment by Stella-Archer** [comment]
Nice work here @chriscaldwell-psa 
I downloaded the PDF and will send that to the client for approval
PO Approved and closing

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/b0933efb-f234-47af-98ce-5be39d7bff89)
