### ISSUE TITLE
Process Improvement: Onboarding Package - Program area collateral

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1209]
User Story
As a program area lead/team, I would like to have a suite of onboarding materials to help clients onboard into the team as a form owner or delegate so that everyone is clear on roles, responsibilities, and process when building a form. 

Exit interview with teams working in Digital Journeys space have indicated they'd need to have a package of materials

Possibilities include:
1) definition of Digital Journeys - program are or tool?
a) Getting started checklist (permissions to GitHib, access to ZenHub)
b) Agile resources/training/understanding of scrum
writing tickets
c) How we work together - terms of reference
d) Platform specs:
- architectural diagram of the forms.flow.ai tool
- Openshift environment
- Check list .01 Digital Journeys - [Business Area Orientation Checklist.docx] need links to resources and who has the role to do what
- building out from this what/who when something is done
- TOR?
- (https://bcgov.sharepoint.com/:w:/t/03991/Eft1pJl07v1KlLkHG56Oo2gBavJl2gT1zlWwHimY4q-4Ow?e=eeSbo8)
- Tour of platform
- Look at diagram and pieces of the telework PIA > https://bcgov.sharepoint.com/:b:/t/03991/Ea_tIM3wrBBFk5xUbShzFYEBApf2WYitTCO7m9TctQD1lA?e=7KbtmM
- what the roles are outside of scrum team ie BI stats/reports/ data gathering

Existing resources:
Triage Survey > https://forms.gov.bc.ca/careers-myhr/new-forms-request-intake-survey/
resources informing Triage tool > https://bcgov.sharepoint.com/:f:/t/03608/Em1x2ct9Mi1PgOU34WkIlLgBO1UMMlJCJaViph7uwT6tWw?e=VQqz8v

DJ Onboarding SharePoint site > https://teams.microsoft.com/l/entity/0ae35b36-0fd7-422e-805b-d53af1579093/_djb2_msteams_prefix_142310733?context=%7B%22subEntityId%22%3Anull%2C%22channelId%22%3A%2219%3A81baaa7de0c84cf5abfcc9adf16ecaa9%40thread.tacv2%22%7D&groupId=1b1e011a-9926-44b6-8638-92bc3f9e5435&tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&allowXTenantAccess=false

2) Intranet space with program are description
involved: Stella + one/two on the team

Tasks

- [x] explore - need to look into options
- [x] Steps needed to achieve this feature.
- [x] break this down into smaller tasks project for each piece of collateral

Acceptance Criteria
* [x] 'One pager" with on boarding overview
* [x] Roadmap onboarding steps and document/diagram process

**Comment by Stella-Archer** [comment]
1/ brain storm do things better
2/ prioritizes out comes of brain storm
3/ tackle manageable bits that can be completed in sprint
4/ build out specific tickets

**Comment by Stella-Archer** [comment]
5-8 points

**Comment by Stella-Archer** [comment]
After meeting the MVP 'Acceptance Criteria" this can be closed details are captured in the Onboarding /epic to continue work

**Comment by Stella-Archer** [comment]
@Ayush prep to demo this at Special Sprint Retro "serving up info for the client employee being onboarded when they need it" just like the Service Journey in Mat/Pat

**Comment by Stella-Archer** [comment]
started Documentation
moving to Epic
