### ISSUE TITLE
SL Review: Nominated Senior Leader Name is cut off in the PDF generated online

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1216]
Background:  
when a user saves a PDF version of the SLR form online the SL’s name disappears from the 'select senior leader'  section.
Jodi entered her name as an example. See snips below for PDF vs Online form. 
Please make sure  SLs name remain on the PDF version

ONLINE FORM: Name is visible
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/1f19b61d-181e-4fc6-b316-d8ac6c7ba95e)

DOWNLOADED PDF: Nominees Name has been cut off
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/a1e76575-cb72-48f0-97a8-e92e6c6b5a64)
<HR>

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/15a22e1c-02e3-4bfb-af34-712983a9f264)
 
Steps to Reproduce: 
1. open a SL Review form 
2. select anybody rom the employee list
3. hit the 'print PDF button 
4. check for name of nominee on PDF
 
Actual Behavior: Name is cut off
 
Expected Behaviour: Nominees name appears on PD
 
Environment:
all environments including PROD

**Comment by Stella-Archer** [comment]
Thanks @bhumin-fw this looks great PO approved & ready to move to PROD

**Comment by iman-jamali-fw** [comment]
@Stella-Archer  Deployed to PROD, ready to be tested out.

**Comment by ayushdamani** [comment]
Tested and confirmed working!

![Screenshot 2023-07-13 112144.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/1c638430-f1d8-4856-a086-f4dcd8b4701d)
