### ISSUE TITLE
Telework: Update tweaks

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1223]
**User Story**
“As a user I want to connect the title 'headquarters location' to the starred definition below as per linguistic conventions .” 

**Tasks**
* [ ] Add star next to Headquarter location title
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/7542fdc7-326f-4752-828c-d2c36e9b1b83)

**Acceptance Criteria**
star is inserted after "Headquarters location*" to relate it to the definition

**Comment by ayushdamani** [comment]
Verified that the star is inserted after "Headquarters location*"

![Screenshot 2023-07-07 085320.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/47b2fbb5-603c-44cd-9fa4-b72f83d93e4d)

**Comment by ayushdamani** [comment]
Tested and confirmed working - moving to close.
