### ISSUE TITLE
Mat/Pat - UX - Content update on Supervisor Information page 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1226]
Change the content in the warning info box to
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/e402a87e-867c-4b28-a2aa-7be970100fc1)

> If the information is incorrect or outdated, let your supervisor know that they need to raise a ticket in AskMyHR to get the reporting information corrected to ensure data in our HR systems is consistent. **You can continue to submit the form** after entering the correct information here."

**Comment by jerry-ey** [comment]
Please test, thanks

**Comment by Stella-Archer** [comment]
Looks Fantastic @jerry-ey closing this ticket :)
<img width="1412" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bc6f4bd2b5571a7c7b5e80a78ffdaa6c7b12cd6/image.png" alt="image.png" />
