### ISSUE TITLE
Mat/Pat - Content - Email add ROE info

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1229]
We need to add a note about ROE in the emails that have an instruction about applying for EI. 

> One of the supporting documents needed for EI is the Record of Employment (ROE). **You do not need to do anything as the ROE will be submitted directly to the Government of Canada by BC Public Service**. You will not receive a hard copy. The earliest a Record of Employment (ROE) is issued is 5 days after the end of the pay period in which your leave starts. 

**AC**
- [x] The above copy should be added as a point in the instructions for applying for EI in all emails to the applicant having those instructions.

**Comment by fazil-ey** [comment]
changes done, to be tested

**Comment by MeghanStothers** [comment]
ready to test

**Comment by MeghanStothers** [comment]
Ready to test

**Comment by ayushdamani** [comment]
Text is now updated, thanks! Moving to PO

**Comment by fazil-ey** [comment]
Looks good
