### ISSUE TITLE
Mat/Pat - Minor copy edit on "Maternity leave - General information"

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1230]
"of" is missing in the following sentence on the "Maternity leave - General information" page

> "You can start your leave 13 weeks ahead **_of_** your expected due date, but no later than your due date or the birth of the child"

![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/098cabf8-6458-4712-bea6-e0a7cd263068)

**Comment by chriscaldwell-psa** [comment]
Edit change has been updated.  This ticket can be closed.
