### ISSUE TITLE
SL Review: Update to email

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1233]
The statement in the email that ADMs receive once they submit the finalized SLR form that invites them to respond to the survey currently reads:

“Please take a few minutes to respond to the SLR Survey on your experience with the process, form and related materials. Your feedback will help us improve the next review process.”

Please change it to:
“Please take a few minutes to respond to the SLR Survey on your experience with the process, form and related materials. **If you have already completed the survey, thank you.** Your feedback will help us improve the next review process.”

<hr>

The words **SLR Survey** continue to be linked to  https://survey.alchemer-ca.com/s3/50193895/2023-Senior-Leadership-Review

**Comment by Andrew-Vargas-bcgov** [comment]
Changed in all environments.
