### ISSUE TITLE
Authentication Error Tracking

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1237]
The following user errors are based on client's having difficulties logging in or accessing the telework form. 
Possible issues could be with: their IDIR (newly onboarded), their browser Cache not cleared, duplicate browser logins open, and possible other factors not yet determined. 

3 Authentication Errors are being tracked:

1) login7  (viewed in URL)  Error - results in a blank  login screen.

Impacted Users:
a. David W. (June 29th reported) {Email chain includes: Andrew G - June 29th}
Dev Comments: The issue is on the WAM side, the SSO (Single-Sign-On) website. 
Actions taken: user cleared cache. DJ forms designer followed up on July 5th to ensure user  could access the forms portal.
Current State: User is still unable to be authenticated resulting in a blank screen (URL: login7@...)

2) "Unexpected error when authenticating with identity provider. "

Impacted Users:
a. Ilaine M (June 7th reported) 
Dev Comments:  Iman to look into it and follow up with SSO team. 
Actions taken: Chris C. asks the admin assistant to loop in with OCIO (around July 7) to see if they can find the issue. Waiting for Admin Assistant to provide feedback next week (July 10-14)
Current State: User filled out a Word Document, but would like a follow by DJ team confirming a digital form can be submitted at a later date. 

3) "The username or password you entered is incorrect" - visible under the login user name, password fields. 
Impacted Users:
a. Julia C. (July 20th reported) 
Dev comments: Iman - seems the user has never logged into our platform. Suggest they call 77,000. Indicated he would connect with the SSO team. 
Current State: User still receiving username/password error.

**Comment by chriscaldwell-psa** [comment]
We received a manager reporting "Unexpected Error when authenticating Message".  I am working with the client to remedy the situation, waiting for a response from them.

**Comment by Stella-Archer** [comment]
IDIR issues when logging in which is related to user changing IDIR 
delete in key cloak is the temporary fix

**Comment by Stella-Archer** [comment]
related to #1323 using GUID and employee ID instead of IDIR
closing this
