### ISSUE TITLE
Deploying the app with the new helm-chart deployment to the new namespace

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1246]
The goal of this ticket is to migrate the deployment files and pipeline to the new AOT helm chart-based.

A list of the components that should be deployed are:

- [x] Databases
- [x]  Postgres DB (patroni) + backup
- [x]  MongoDB + backup
- [x]  Redis
- [x] forms-flow-forms
- [x] forms-flow-api
- [x] forms-flow-documents
- [x] forms-flow-bpm
- [x] forms-flow-web
- [x] forms-flow-files
- [x] forms-flow-idm (keycloak)
- [ ] forms-flow-analytics (nice to have)

In addition, we want the GitHub workflow (GitHub Actions) files to work as before and trigger the deployment to different environments when a file changes in a component. These workflow files include:

- forms-flow-bpm-cd.yml
- forms-flow-documents-cd.yml
- forms-flow-forms-cd.yml
- forms-flow-web-cd.yml
- forms-flow-api-cd.yml

**Comment by MeghanStothers** [comment]
@iman-jamali-fw Could you add details to this ticket before grooming tomorrow? Thanks

**Comment by Stella-Archer** [comment]
effort to merge what we have to new environment
custom image in place but needs to merge into new space 
2+ weeks, a month (guestimate.) 
Warren & Kanal most of the lift Iman consults

**Comment by fazil-ey** [comment]
@warrenchristian1telus  @kkapoor-fresh  do you have an update on the progress of this work?

**Comment by kkapoor-fresh** [comment]
Currently,  I am testing Github Actions in the new namespace and running docker builds using base images from the BC gov artifactory.

**Comment by fazil-ey** [comment]
@warrenchristian1telus @kkapoor-fresh please add an update on the progress here

**Comment by kkapoor-fresh** [comment]
I am in the process of setting up the databases in the new name space using forms flow helm charts.

**Comment by fazil-ey** [comment]
@kkapoor-fresh  @warrenchristian1telus is there an update? Is there a date we can expect this work to be done?

**Comment by kkapoor-fresh** [comment]
The web, api, camunda, forms and documents builds have been created in the new namespace.
The following files are being being modified to trigger builds and deployments appropriately. 


forms-flow-bpm-cd.yml
forms-flow-documents-cd.yml
forms-flow-forms-cd.yml
forms-flow-web-cd.yml
forms-flow-api-cd.yml 

The corresponding helm charts deployments are being created and tested.
There is a lot of configuration and other resources that need to be migrated with he deployments to the new namespace which need to be there to make the helm deployments and dbs work which is what is currently in progress. Each component/application needs to be analyzed for configuration and other related resources in the new namespace and has dependency on one another, so trying to work that out.

Our hope is to fix these errors/issues at the earliest and hope to see some good progress on these in the next week.


@warrenchristian1telus @fazil-ey

**Comment by MeghanStothers** [comment]
Thanks for work carried out to date and can you comment on next steps to resolve errors/issues? 

On the DJ roadmap, we'll be launching mat/pat, followed by stabilization period and then we'll turn the focus to the application upgrade with this work expected to begin in November/December and into early 2024. I'm wondering about this namespace work and the team's readiness to begin the application upgrade in the weeks ahead. Looping @Stella-Archer into this conversation.

**Comment by kkapoor-fresh** [comment]
Able to deploy the following components on the new namespace:
patroni
mongo
redis
keycloak
forms-flow-files



Thanks,
Kunal

**Comment by MeghanStothers** [comment]
Next step: minimum viable test - look for example or two and test  out versioning. Decide how we want to test the change - make sure new functionalities work.

**Comment by MeghanStothers** [comment]
Thanks to @warrenchristian1telus for connecting about this one and tabling next steps to move this forward (resolve error message):

1) reach out to Simon
2) reach out to AOT 
3) Dev Exchange
4) Chef's contact
5) M. Hall

**Comment by MeghanStothers** [comment]
Meeting set up Monday, November 27 at 10 a.m. with AOT dev ops to connect/brainstorm possible technical approaches. Ideally @kkapoor-fresh and @simensma-fresh will join this session.

**Comment by MeghanStothers** [comment]
The issues has been shared with the AOT team for reviewing and reporting back to the DJ team.

**Comment by fazil-ey** [comment]
@warrenchristian1telus can you please update the ticket

**Comment by kkapoor-fresh** [comment]
Gladly, we were able to get past the error this week. The following apps have been deployed post the fix.
-forms-flow-web
-foms-flow-documents

-forms-flow-webapi and camunda that were deployed prior to the fix will be redeployed postt this fix

-forms-flow-forms has been deployed as well but it is crashing due to some nodejs specific error. currently looking into it.

Thanks,
kunal

**Comment by MeghanStothers** [comment]
This is a true breakthrough!  Thanks to you and Warren for persevering through this initial hurdle.

**Comment by MeghanStothers** [comment]
Ongoing node JS error. Getting close to a working error.

**Comment by kkapoor-fresh** [comment]
Looks like the issue related to the missing javascript module in forms-flow-forms is related to a change that wasn't merged from a source branch. Working with Iman to get that resolved.

**Comment by kkapoor-fresh** [comment]
The formio issue has been fixed and the formio app is up and running now. 

This now means that all the applications that are being maintained via github actions pipelines have been deployed as helm charts on the new namespace. If team can run a test creating a form or 2, it will be good.

**Comment by MeghanStothers** [comment]
@warrenchristian1telus and @kkapoor-fresh Hi there - can you please add the latest information to this ticket, please?

**Comment by kkapoor-fresh** [comment]
@MeghanStothers The new namespace has been already delivered to the team for testing the helm upgrades. I believe @bhumin-fw  has been testing the new namespace for any issues.

**Comment by bhumin-fw** [comment]
@MeghanStothers 
We have added new ticket to test details on new namespace. We will track testing progress in ticket [#1548](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1548).

**Comment by fazil-ey** [comment]
the remaining the work is being done in #1548
