### ISSUE TITLE
1.10: Submissions stuck in Camunda 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1247]

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov  to add details

**Comment by fazil-ey** [comment]
@Stella-Archer to confirm if this is a priority. Maybe its a violation of the PIA

**Comment by Stella-Archer** [comment]
Hasn't been an issue recently. Closing ticket.

**Comment by fazil-ey** [comment]
Chris and Ayush are checking Camunda to ensure there are no forms stuck in Camunda. We have a process and this can be closed
