### ISSUE TITLE
Test out the upgraded app v5.1.1 

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1249]
Test out different components of the newly upgraded app. If you see an issue/bug please create a bug ticket for it.

- Login/Logout
  - Ensure the login token contains all the necessary information (e.g., role, group, etc.)
- Form Operations (`/form` page)
  - Upload a new form
  - Download a form 
  - Delete a form
  - Create a new form
  - Edit an existing form
  - Test the new **Form History** (form versioning) feature
  - Test the new **Duplicate Form** feature
  - Add/Remove workflows to/from a form
  - Publish/Unpublish a form
  - Ensure the list of forms shown in /form is filtered based on your IDP
  - Test out search, sort, and [form/resource] drop-down functions on the /form page
- Processes/Workflows (`/processes` page)
  - Upload a new process/workflow
    - BPMN
    - DMN
  - Edit a process
  - Export a workflow (BPMN/DMN)
- New Form Submission
  - Access form based on your IDP
  - Test the "Save Changes" button
  - Test the "Print PDF" button
  - Ensure validations and generic UI fields are functional
  - Ensure "Submit a Form" function works (check the network tab of your browser for any thrown errors)
- Draft Operations (`/draft` page)
  - Draft list
    - Ensure it displays the forms saved as drafts
    - Test out draft name search and filter by date
    - Check the draft deletion function
  - Draft details - open a draft item and ...
    - Verify data entered in the new form are saved here
    - Add more data to your draft, close it, and revisit to check if the data are saved in your draft
    - Navigate between drafts to ensure each draft retains its unique data. In previous versions, drafts displayed data from the last opened draft, which should be resolved in this update.
    - Test out the new "Discard Draft" button
    - Submit the draft and ensure it's properly submitted. Check the network tab in your browser for any thrown errors.
    - Test the "Save Changes" button
    - Test the "Print PDF" button  
- Submitted Form Operations (`/application` page)
  - Submitted forms list
    - Test out the list filters (name, date)
    - Verify form statuses are correct
    - Ensure submitted forms have the appropriate View/Edit actions
  - Submitted form detail - open items in the list
    - If the item is in View, test the "Print PDF" button
    - If the item is in Edit mode, test all related editing operations
- Review and Process Form Operations (`/task` page)
  - Depending on your role/group, you should see all tasks or only tasks assigned to you in the task list.
  - Certain forms (cold/flu and SL) should not appear in the task list
  - Test out the task filters - visible by clicking on the "+" icon next to "Created"
  - Open tasks to ensure you can review and submit decisions, and verify the success message appears.

**Comment by Stella-Archer** [comment]
PDF generation issue issue being test w/Iman & Bhumin

**Comment by MeghanStothers** [comment]
Iman to continue testing and expects to wrap this one by end of the week.

**Comment by MeghanStothers** [comment]
Iman hope to wrap this one today - working on draft operations today.

**Comment by fazil-ey** [comment]
Testing is complete, fixes are done  in dev. Testing needs to be done after we stage the app. Handled in a separate tickets #1258, #1246
