### ISSUE TITLE
1.10: add Date Stamp to 1.10 form

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1251]
**User Story**
“As the Arbitrator of the Article 1.10 complaint process I want the form to record the date it was submitted so I can have that important information for arbitration hearings.” 

**Tasks**
Add 'submission date' to 1.10 form, It could work like the telework submission date below but other solutions/suggestions are welcome 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/8822d601-c98b-4402-af7a-3559318cfcae)

**Acceptance Criteria**
When a 1.10 form is submitted, the date of submission is recorded in the pdf (and the email?)

**Comment by fazil-ey** [comment]
Goal is to have date of submission in the pdf,  it does not necessarily have to be a form field

**Comment by Andrew-Vargas-bcgov** [comment]
ready to test new date field. @ayushdamani . the field is at the bottom of the form, above the submit button. It should not be editable and display today's date.

**Comment by ayushdamani** [comment]
Confirmed working ✅

Thanks Andrew!

![image.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/2e3914bc-675b-4910-8987-78cedb3208f6)

**Comment by Andrew-Vargas-bcgov** [comment]
@Stella-Archer please review the change and let me know when to move it to prod :).

**Comment by Stella-Archer** [comment]
One small edit - Could we clarify the label above the date from “Date” to “Date Submitted

**Comment by MeghanStothers** [comment]
Team to test tonight and report back if problem was fixed

**Comment by Stella-Archer** [comment]
Aug 17 Deployment was tested on 1.10, telework and SL review all worked as expected closing tix
