### ISSUE TITLE
SL Review: issue with the ministry names in reporting

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1253]
**Issue:** The current ministry names sent to ODS in SL Review submissions lack spaces, which creates compatibility issues with the reporting team's ministry name table structure. They require ministry names with spaces (e.g., my ministry).

**Comment by iman-jamali-fw** [comment]
The problem occurs when a user searches for a senior leader and then changes their ministry from the drop-down menu. In such cases, the system saves the key of the selected ministry, which does not contain spaces, into the database and later sends it to the ODS. This issue does not arise if the user does not modify the auto-populated ministry name that appears when the senior leader is searched.

To address the problem, I changed the value property under the ministry name field to label. This ensures that the displayed ministry name with spaces is used, resolving the discrepancy between the displayed name and the stored key in the database.

![Screenshot 2023-07-26 at 4.01.30 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/b1e3f972-7e9f-4c7f-8357-f5dc7e49ab43)

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 
The issue was fixed in all environments. It's ready to be tested.

@mikeshi-bcgov 
Do you mind, manually fixing the existing records in ODS that have the space issue in their ministry names? thank you

**Comment by Stella-Archer** [comment]
Thanks  @iman-jamali-fw @ayushdamani could you start testing the in the TEST environment when you get in? Thx!

**Comment by ayushdamani** [comment]
Tested and confirmed working ✅

Selected Meghan and manually changed the ministry.

**Comment by Stella-Archer** [comment]
thx will move it to PO

**Comment by iman-jamali-fw** [comment]
@mikeshi-bcgov 
Did you have a chance to fix the records with ministry name issues?

Also, could you let us know if we need to coordinate with the ODS team if we plan to make a change/add a ministry name to the SL form? Is there a table on your end that maps the ministry names?

**Comment by MeghanStothers** [comment]
org hierarchy is maintained by DI team (Steven Jones' team) - submit a ticket to this area as needed

**Comment by T854236** [comment]
One option for consideration for manage ministry names or department name changes is to pass the ID to ODS.  If you are leveraging the Datamart_Telework_meta_dept_org_levels, there is a departmentID that can be used.  

Doing this however will impact how reporting is done today and it will change automatically as name changes.

**Comment by MeghanStothers** [comment]
Iman noted we could test with a submission and see if the data is correct on ODS side - fix is on dev and on test.  Can be tested on Test and then tested with the ODS to see that the data is confirmed.

**Comment by iman-jamali-fw** [comment]
@mikeshi-bcgov @T854236 

I sent two submissions on the TEST environment with application Ids of `2710` and `2711`. Could you confirm the ministry name/branch/division is correctly mapped to the ODS table (for reporting)? thank you

If it looks good, @Andrew-Vargas-bcgov can move the fix to PROD.

**Comment by T854236** [comment]
@iman-jamali-fw

Looks good.

**Comment by MeghanStothers** [comment]
yes- ready to go

**Comment by MeghanStothers** [comment]
tested and approved
