### ISSUE TITLE
Explore: How to stage upgrade - January

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1258]
Objective: Prepare the "upgraded app" for testing by the entire team, moving it towards a state of production readiness.

Option 1: We can wait for Kunal to integrate the upgraded app with the new deployment pipeline in the new namespace. This approach involves minimal effort and low risk, although it may require additional time before the app is ready for staging.

Option 2: Following Kunal's advice, we could establish the "upgraded app" in a separate environment within the new namespace. While this will lead to some duplication of work, it presents a low-risk strategy and could expedite the staging process.

Option 3: Mirroring the procedure from the last upgrade, we could roll out the "upgraded app" in our current namespace - specifically, on the DEV environment - and let it coexist with the prior version on TEST and PROD. This strategy entails minimal effort and promises the fastest staging time. However, it may temporarily disrupt team activities, as the DEV environment will be engaged with the "upgraded app" for some duration.

cc @bhumin-fw @warrenchristian1telus @kkapoor-fresh @MeghanStothers @Stella-Archer

**Comment by MeghanStothers** [comment]
Decision is needed. We will want to keep this on a radars as we have this on our roadmap for October Implementation and will depend on progress, resources etc.

**Comment by fazil-ey** [comment]
Deadline for decision - December 22? before the holidays?
