### ISSUE TITLE
Set up a local Keycloak instance for local development

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1270]
Currently, for local development, we rely on an EY-hosted Keycloak instance. To safeguard local development from potential outages, we can set up a locally-hosted Keycloak instance (as a backup to the EY-hosted instance).

Technical details:
- In the `docker-compose` file, add the necessary configuration to set up a local Keycloak. Use the docker files from the `forms-flow-idm` directory.
- During the build process, make sure the setup automatically includes the required roles, groups, and configurations.
- As a starting point, Google can be set up as the identity provider.
- Additionally, we can explore the possibility of setting up IDIR locally, though it's considered optional.

By following these steps, local development can continue smoothly and independently, even if the EY-hosted instance encounters any issues.

**Comment by fazil-ey** [comment]
we have already made this switch, we can close this
