### ISSUE TITLE
Mat/Pat - Bug - Mailing address no city & postal code

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1273]
The mailing address in Employee Information does not include city, province and postal code. 

**AC**
- [ ] Mailing address in Employee Information should include city, province and postal code. i.e it should be the complete address
- [ ] The address should involve some separation between pieces of information. Example: In the screenshot below, the address show in a legible way (with spaces and punctuation as follows: 1426 Walnut Street, Victoria, V8R 1Y8

**Comment by MeghanStothers** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDU2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--98f1a2ad57d07493c8267f6e8aadc04774cc1686/image.png)

**Comment by ayushdamani** [comment]
Working great!
- Tested in the TEST environment
- The complete address is shown, in the format mentioned in the acceptance criteria.

**Comment by fazil-ey** [comment]
Relying on  Ayush's testing as there is no data for me in peoplesoft.
