### ISSUE TITLE
Mat/Pat  - Links do not open in new tab the first time you click them in some of the form tabs

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1274]
Some links do not open in a new tab the first time we open the form. All links in the form should open in new tabs
We noticed this on Maternity leave - Length of leave information and Maternity leave - Leave allowance information page. 

When we hit back the saved draft does not open. 

Screen recording - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-08-10%20at%2010.54.34%20AM.mov?csf=1&web=1&e=oV8NfG

---- 
Explore ticket #1349 after which this can be fixed

**Comment by iman-jamali-fw** [comment]
@AayushAnand007 
This is ready for testing on TEST. All the links in all forms are now open new tabs. Please test out all existing forms and check all their links while starting a new form, edit a draft, view/edit a submitted form and finally when review a form as supervisor. All these pages, should now support links that one in new tabs. Good luck with your testing!

**Comment by ayushdamani** [comment]
Working great - I can see all links open in a new tab.
Thank you so much, Iman!

**Comment by fazil-ey** [comment]
all links opening in new tabs. looks good!
