### ISSUE TITLE
Mat/Pat - Change "standard' to "extended" in Parental leave - Start Date tab for extended leave

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1276]
We have logic for the number of weeks 52/78 within which parental leave must start on Parental leave - Start date tab based on the type of leave selected. However in the text it says standard instead of extended when extended leave is selected. 

Change "standard' to "extended" in Parental leave - Start Date tab when extended leave is selected. 

![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/79ec08d1-cd7a-4dca-b904-9c7218b1206e)

**Comment by MeghanStothers** [comment]
It's possible the PSA dev team could do this one (with some training needed). We could also ask AOT to help us with this training piece.

**Comment by Andrew-Vargas-bcgov** [comment]
Added the dynamic text for this field to change to extended leave. @ayushdamani

**Comment by fazil-ey** [comment]
works well
