### ISSUE TITLE
Explore: CRM Ticket Creation for Mat/Pat Users: Addressing Missing Contact Records

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1277]
According to the CRM team, not all IDIR users have contact records in CRM, limiting CRM ticket creation for Mat/Pat users.

To address this:
1. Assess the user impact.
2. Figure out a fallback strategy for Mat/Pat users lacking CRM records.

**Comment by MeghanStothers** [comment]
Meeting set up with PSA contact/CRM team to better understand CRM ID and which groups across the public service (and other ABCs) would ideally have access. This information will inform technical work needed and comms/change management planning

**Comment by iman-jamali-fw** [comment]
Based on Bhakti's investigation:

- IDIR users should expect to have contact records in CRM since these records are auto-generated via the nightly PeopleSoft feed.
- The only case when an IDIR user doesn't have CRM records is when an employee hasn't validated their IDIR.
- Without IDIR validation these users can not access DGJ platform.

Therefore, we can expect that all the IDIR users who can log into DGJ, have CRM records.

**Comment by iman-jamali-fw** [comment]
Investigation completed. This ticket can be closed.
