### ISSUE TITLE
Date Discrepancy in PDF Generated from Form (on server-side): Timezone Misalignment

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1278]
The date shown on the form is appearing one day later in the PDF generated from the server. This could be happening because of the time difference between where the form is filled out (usually in PST) and the server's timezone (which is in UTC).

**Comment by iman-jamali-fw** [comment]
The issue exists in all the similar sing-date fields in Telework, SL, and other forms. I am working on a fix. Once fixed, it needs to be tested across all forms that have the sign-date fields.

I increased the estimate to 3 for the extra effort needed for fixing and testing across all forms.

**Comment by iman-jamali-fw** [comment]
The issue stemmed from the conversion of the submission date to UTC time before saving. This led to discrepancies when the client's local date was different from the UTC date at the time of submission. For instance, a submission made at 5 PM PST is dated as the next day in UTC due to the 7-hour time difference. Consequently, all submissions after 5 PM PST appear as being made on the following day. A similar problem arose for time zones ahead of UTC, where the saved date would be one day behind.

To fix this, I adjusted our method to guarantee the correct UTC date of submission. The solution involves saving the timestamp of the start of the client's day, adjusted for their timezone offset. For example, a client in PST on August 14 would register a submission datetime of `2023-08-14T07:00:00.000Z`. On that same day, a client in Berlin time, which is 2 hours ahead of UTC, would have a datetime of `2023-08-13T22:00:00.000Z`. Both these datetimes translate to `2023-08-14T00:00:00.000Z` in UTC, ensuring that the date is consistently represented and retrieved accurately.

**Comment by iman-jamali-fw** [comment]
The date fields for submission in the forms listed below are now fixed in the DEV and TEST environments and are ready for testing on TEST environment:

1. Telework Form:
   - "Employee Agreement" Date Field
   - "Manager/Supervisor Sign-off" Date Field
2. 1.10 Submission Form:
   - "Date Submitted" Field
3. SL Form:
   - "Final Submission" Date Field
4. Maternity/Paternity Form:
   - Submission Date Field on the "Certify and Submit" Page

When testing, kindly submit the mentioned forms after 5 pm if you're in the PST timezone. Please make sure that the date displayed in the submitted form on the website and in the PDF attached to emails accurately reflects the correct date.

**Comment by ayushdamani** [comment]
Tested and confirmed working ✔️

The date in the PDFs match the date of specified for each form. Thanks @iman-jamali-fw

**Comment by iman-jamali-fw** [comment]
@ayushdamani 
Thanks for the quick testing. Can I ask what timezone you were during the testing and what was the local time?

**Comment by iman-jamali-fw** [comment]
@ayushdamani 
In that case, to replicate the issue, you better submit it after midnight, so your date will be one day ahead of UTC. If that doesn't work, there is another way to change your browser's timezone to a timezone that is one day after or before UTC. Let me know which one works better for you.

**Comment by iman-jamali-fw** [comment]
Hey @ayushdamani 

Did you have a chance to test it again with the timezone that is one day off UTC? [Here](https://www.browserstack.com/guide/change-time-zone-in-chrome-for-testing) you can find a guide on how to change the timezone on Chrome if you decided to go that way.

**Comment by ayushdamani** [comment]
Tested again with changed timezone on Chrome - one day ahead of UTC ✔️

Thank you for the instructions, @iman-jamali-fw
