### ISSUE TITLE
SL Review: Admin group for those covered by PIA to print out PDF report for ministry contacts

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1279]
**User Story**
“As an administrator of the SL Review from and process, I want the ability to access all SL Review forms in PROD so I can print out PDF for ministry validation reviews and meetings.” 

**Tasks**
Create a group with access to SL Review nominations in PROD. 
Jodi/Martha will supply list of admins for this group

**Acceptance Criteria**
small group of admin can access and print nomination PDF for ministries prior to validation process (nominations tha have been submitted for validation)

**Comment by Stella-Archer** [comment]
walk Jodi, Emma and robin through the process when admin group is built & live

**Comment by iman-jamali-fw** [comment]
Tested successfully on TEST. 
A user with [`client` and `sl-review-admin`] roles is able to view all SL submissions and edit/delete their own SL submissions and print out PDFs.
A user with [`client` and `sl-review-adm`] roles is able to edit/delete their own SL submissions.

Ready to move to PROD.

**Comment by Stella-Archer** [comment]
hey @Iman is Jodi Little in the test group now can she test?

**Comment by bhumin-fw** [comment]
@Stella-Archer 
make Jodi Little as sl-review-admin. Now she can test on TEST environment.

**Comment by MeghanStothers** [comment]
Dj team tested this morning with success - over to Jodi for her team to test (as admin) to make sure this feature works for them. And the we can close this ticket.

**Comment by bhumin-fw** [comment]
@JodiLittle I have added Emma, Robin and you in admin group. You will be able to see all SL submissions on production and able to print the PDF.
