### ISSUE TITLE
Telework: New (DMN-based) workflow

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1289]
Background: A new Telework workflow was designed by Andrew that simplifies how things work in that form. The new workflow is based on DMN. 

Goal: We need to test out this workflow and make sure it's production-ready.

In our last attempt to deploy that to PROD, Meghan discovered there were some long delays in submission.

**Comment by fazil-ey** [comment]
Development is done, but might need to change to DMN workflow in test and devs need to test. Then we can move to  Review/QA & then move to prod

**Comment by Stella-Archer** [comment]
yay this worked great - gonna close this baby
