### ISSUE TITLE
Mat/Pat - Extended allowance validation

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1294]
Extended allowance for parental leave should only be allowed if the applicant is taking extended leave.

AC
- [ ] For parental leave, If standard leave is selected disable extended allowance option. Show a message saying "Extended allowance cannot be selected for Standard leave" under the radio button for extended allowance 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEErIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--02dee64878fb01d7e767f2f00cdb56fac54affc5/image.png)

**Comment by Andrew-Vargas-bcgov** [comment]
Ready to test on TEST :) @ayushdamani

**Comment by ayushdamani** [comment]
Tested with Andrew. Works flawlessly:
- Tested in TEST environment
- Only 'standard' option is allowed to be selected under top-up allowance options, when 'standard leave' is selected.
- 'Extended' option is available only when 'extended leave' is selected.
- Logic works great on the review page too.

Thank you, Andrew :)

**Comment by fazil-ey** [comment]
works well functionally. @Andrew-Vargas-bcgov is it easy to fix the spacing within the box and between the boxes? 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnF6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4c4930011eb9a31eed7125f4ed5d261634a19208/image.png)

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey not too difficult, just need to make sure i understand what you want.
Do you mean like 
1: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclcwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fb784b859dfc4aaff1b696b72c3b20def1516817/image.png)

2: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1MwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4c4a10613f696a8fa81e685b8d0fa949de6a6611/image.png)

**Comment by fazil-ey** [comment]
# 1 looks great!

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey the changes are up on test. You might need to clear your cache before seeing the changes.

**Comment by fazil-ey** [comment]
Looks good! Closing ticket
