### ISSUE TITLE
Mat/Pat - Content - Email based on benefit codes

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1296]
Email to applicant after approval - we send the flexible benefits form or the bargaining unit form based on BCGEU and PEA currently but it does not include all groups. So we want to use the benefit program field in peoplesoft to identify which form should go to which group. if there are in multiple codes for an employee use the latest one based on date

Updated AC
- [ ] in all emails sent to applicant on approval with the benefit context, replace the 1st point to this and remove the employee class logic.  
For Excluded Employees -  [Flexible Benefits Enrolment/Change form](https://www2.gov.bc.ca/assets/gov/careers/all-employees/pay-and-benefits/benefits-for-excluded-employees/flexible_benefits_enrolment_change.pdf) or for Bargaining Unit employees - [Bargaining Unit Benefits Program Enrolment/Change form](https://www2.gov.bc.ca/assets/gov/careers/all-employees/pay-and-benefits/benefits-for-bargaining-unit-employees/bargaining_unit_benefits_enrolment_change.pdf)

- [ ] remove logic for careers & MyHR and link and use this link for all emails "https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/pay-benefits/benefits"

**Comment by fazil-ey** [comment]
says &ndash instead of - 

<img width="1646" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3BuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46c10cf1637f65d9002582913c1e6e750cda7316/image.png" alt="image.png" />

**Comment by MeghanStothers** [comment]
Unsuccessful test: Meghan and Mike tested Dec 22 without success. After Meghan Approved Mike's submission, the screen message appeared "Submitting...this can take a few minutes' which appeared for multiple minutes (5+) and the request was not processed  
Stella sent email to Nancy to ask about CRM fix for access in test for Ayush, Mike and Chris.

**Comment by bhumin-fw** [comment]
@ayushdamani you can test it now, It should works for you.

**Comment by ayushdamani** [comment]
Tested with Bhumin, this morning - I was able to move past the 'submitting' screen.
Approval email is updated with the acceptance criteria!
Moving to PO

**Comment by fazil-ey** [comment]
the - issue was fixed, closing ticket
