### ISSUE TITLE
TOOL: Non-IDIR (unauthenticated) users

### ISSUE THREAD

**Issue by Abuchana** [bcgov/digital-journeys#130]
_As a BC Gov Employee without an IDIR account, I would like to be able to fill out and submit forms so that I can submit forms when I am on leave or waiting for an IDIR account.

**Business requirements for this still feature needs discovery**

**Tasks** 

- [ ] TBD

**A/C**
- All forms should accessible for non-IDIR users as well as authenticated ones
- If user is not logged in: support for **viewing** and **submitting** forms only 
- Accessed via a single link from BC Gov site:
	- If not signed in with IDIR already -> show page (login / I don't have an IDIR)
	- Make clear that by not using IDIR you need to fill out the full form
- Same workflows for authenticated or unauthenticated users
- Unauthenticated users can only submit forms, no other functions on the system
- Unauthenticated users have to fill out a ReCaptcha

- Formsflow has a public form option
- embedding form into a  webpage is another option

**Comment by jchow11** [comment]
![Log in Portal.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/7e17e222-84f7-4aca-ba3d-759e6a20bece)

**Comment by MeghanStothers** [comment]
ERIP form set up in Orbeon following a discussion from Ian/FW about:
-	Security concerns for access by non-IDIR uses 
-	A higher technical estimate than anticipated (complete overhaul of the formsflow page
-	A few ideas proposed 1) creating a blanket user name and password sent to all clients – has security concerns sent to lultiple users, and not able to track who is filling out forms. 
-	Hasan reached out to the client about having a PIA in place – client was checking with Jennifer O’Neil/privacy people about updating the PIA
-	June 1 for clients sending invites to new batch of candidates
- Waiting to hear back from client
