### ISSUE TITLE
SL: Blank Branch Name field - unable to submit form

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1300]
As a form user, I want to be able to submit my form.

"...another issue that has popped up with the tombstone information in the SLR form.

This is what she described:

, an ADM was working on a form for XXXX  One field is locked is blank and he can’t fix it as it’s locked: it says the branch name in the division cell, and the branch field is blank.  When he tries to submit the form for validation, it says he can’t because there is a blank field (which is one of the locked fields).

This may be a DJ issue or this may be a PeopleSoft issue so I have included Sarah and Andrew in this email. 

This is an urgent request in addition to the other two from ECC, because they need the submissions for a meeting for tomorrow."

**Comment by MeghanStothers** [comment]
Possible workaround suggested from Andrew that was sent to Jodi by email
: 
This is most likely the result of older information before we changed the division/branch fields to be accurate for reporting.

If the submitter clears out the name of the senior leader, changes it to a different senior leader, then changes it back to (xxx - name), the form should update to the correct information and allow submission.

**Comment by MeghanStothers** [comment]
Some key findings shared by Sarah 

I agree with Andrew: it sounds to me like the form was begun prior to the deployment that corrected the ministry/division/branch information (originally, the forms had Level 2 data for Division rather than Level 1, and level 3 data for Branch rather than level 2). 

(name) works in a department ID that their ministry has not assigned any level 3 org hierarchy information for, so that field is blank. There is level 1 and level 2 hierarchy information, however, so I think Andrew’s suggestion should solve the issue. Thanks Andrew!

Important: If the Division and Branch fields are locked but mandatory, that does bring up another potential issue though. Hopefully it won’t come up for this project, but I think it’s important to flag. Usage of the deeper organization hierarchy levels is discretionary, and not all ministries make use of them for all departments. It can also take Ministries a while to provide the hierarchy information for newly-created departments.

I don’t see any employees in departments without Level 1 (division) information, but there are currently about 1,400 employees across government in departments without level 2 (branch) information (and even more in departments without level 3 or 4 information, but that is not relevant to this particular form). If these fields are locked but mandatory on this or other digital journey forms, this may cause ongoing issues with people being unable to submit forms. 

For future forms, I would recommend not making the organizational hierarchy fields mandatory. I know changes to this form aren’t feasible, but fortunately I only see one department without level 2 / Branch information that is both in-scope for the Senior Leadership Review process and has Band 4 – 6 employees working in it. I am going to see if we can get level 2 / branch information added for that department, to eliminate the possibility of this causing submission issues. 

Until/unless we can get that changed, I don’t think nominating ADMs will be able to submit forms for the following four individuals. Jodi, FYI if you get reports of submission issues for any of these individuals......(Meghan edit: names removed)
	
I’ll look into the org hierarchy side of things, and will let you know whether we are able to address it that way.

**Comment by MeghanStothers** [comment]
We'll wait to hear from Jodi if the ADM was successful with Andrew's suggestion to add-remove-re-add name. Then we'll close this ticket

**Comment by MeghanStothers** [comment]
@Andrew-Vargas-bcgov great work and I think this issue has been resolved. Can you estimate the effort and I'll close the ticket?

**Comment by fazil-ey** [comment]
This was fix by the data team, nothing pushed to prod from DJ
