### ISSUE TITLE
Mat/Pat: Server-side pdf generation timeout issue

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1302]
Random Mat/Pat submissions fail with a timeout error(504). The issue is thrown at the PDF-generation level. Adding PDF generation resources seemed to reduce the likelihood of the error thrown but hasn't fixed the root cause of the issue.

AC: Fixing the PDF generation timeout issue on Mat/Pat submissions.

Technical details: There are multiple timeout variables defined in Camunda that might have something to do with this issue. Finding and increasing those timeout variables might help fix this problem.

Workaround - Usuaully happens when supervisor approves. workaround is to refresh the page and validate again

**Comment by iman-jamali-fw** [comment]
Progress Report:

**Learning So Far:**
I've learned that the Camunda workflows for Mat/Pat always complete successfully, but there's an issue with occasional delays in starting, leading to a 504 timeout error when the website (Review page) communicates with Camunda.

**What I've Tried:**
I've attempted the following:
1. Modified the Mat/Pat BPMN workflow, but it didn't solve the problem.
2. Increased Camunda's memory and CPU resources, which also didn't work.
3. Scaled the number of Camunda pods on OpenShift without success.
4. Tried extending the website's HTTP call timeout using NGINX, which didn't resolve the issue.

**What I'll Do Next:**
My next steps:
1. Explore and adjust various Camunda timeout settings, as there are multiple configurations.
2. Increase the React app (website) HTTP client timeout to accommodate potential delays in network calls.

I'm working to better understand and resolve the intermittent 504 timeout error.

**Comment by iman-jamali-fw** [comment]
## Cause of the timeout issue
The problem stemmed from the short connection timeout of the Camunda DNS server (Route). The default timeout in Openshift Route is set at 30 seconds, which proved insufficient for processing Mat/Pat workflows. These workflows on the DEV environment could take up to 2 or 3 minutes.

## Resolution
To address the timeout issue, all timeout-related configurations in various components at different layers were extended to accommodate longer Camunda operations. Ensuring longer timeouts required adjusting the limits at all layers of connection for each engagement component in the workflow. This involved modifying timeout settings for:

- DNS server timeout (Routes in Openshift)
- Gateway servers, such as NGINX for the Website, GUNICORN for API and PDF generation, and the embedded Spring Boot server for Camunda.

After setting all timeout limits to a reasonable duration, typically 5 minutes or 300 seconds, this ensured that connections between different components would remain stable. This prevents issues like 504 gateway timeout errors during lengthy request/response calls.

**Comment by iman-jamali-fw** [comment]
FYI, this ticket was originally estimated for exploration only. The estimated effort increased to 5 to cover the troubleshooting time and implementation of the fix.

**Comment by ayushdamani** [comment]
I was able to approve my submission and did not get that specified error. Thanks, Iman!

**Comment by ayushdamani** [comment]
I was able to approve my submission and did not get that specified error. Thanks, Iman!

**Comment by Stella-Archer** [comment]
@warrenchristian1telus  doing tests, still in progress

**Comment by fazil-ey** [comment]
submission taking  about 30 seconds but no errors observed
