### ISSUE TITLE
Tool: Deployment of Document service fails for PDF generation

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1305]
With existing version on google repository. We are getting version 114 for WebDriver and version 116 for Chrome browser. Due to this conflict PDF generation on document services fails.

Potential Solution: Find required version from archive(version 114 for chrome browser) and store on git repo and pull it until we receive version 116 for webDriver.

**Comment by fazil-ey** [comment]
@bhumin-fw Is this related to #1302?

**Comment by bhumin-fw** [comment]
@fazil-ey No, timeout issue is relate with specific form when we have more detail on form.

**Comment by iman-jamali-fw** [comment]
All the PDF generation-related dependencies were locked to the latest working stable version.

**Comment by iman-jamali-fw** [comment]
@Stella-Archer @ayushdamani 

Ready to be tested on DEV and TEST. For testing, you should be able to send different forms and expect to get a PDF attached to the email. That should indicate the server-side PDF generation service is working fine.

**Comment by fazil-ey** [comment]
Received the PDF for mat/apt
