### ISSUE TITLE
Mat/Pat: Simplify workflow using DMN tables

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1306]
Simplifies Mat/Pat workflow using DMN tables.

The non-DMN Mat/Pat workflow (on Sep 7, 2023) looks like the screenshot below

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2Q3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--59660b58582d20a4d0cbd5dc4f1574892b625cde/Screenshot%202023-09-07%20at%2012.20.07%20PM.png)

**Comment by fazil-ey** [comment]
The workflow is super flow, and submissions on the supervisor side that a few minutes someimes. Will this help improve that?

**Comment by Andrew-Vargas-bcgov** [comment]
created bpmn and dmn. going to test in dev this morning and move to test if everything works.

**Comment by MeghanStothers** [comment]
Next step is end-to-end testing all scenarios.

**Comment by iman-jamali-fw** [comment]
test comment

**Comment by fazil-ey** [comment]
No major issues found with any workflows since deployment. Closing this
