### ISSUE TITLE
SSL Certificate Install for docs

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/digital-journeys#1307]
SSL certificate has been ordered for digital-journeys-docs.apps.silver.devops.gov.bc.ca, and will need to be installed once it has been provided.

Order was placed on Thu 8/24/2023.

**Comment by warrenchristian1telus** [comment]
Finally received the SSL cert for this domain, and have implemented in prod. This doesn't impact anything yet, as it's the "docs" domain, rather than "documents" which is currently in-use.

@bhumin-fw Can you please schedule a time to make the switch in the application to use the newly secured docs domain: https://digital-journeys-forms-flow-docs.apps.silver.devops.gov.bc.ca/

**Comment by bhumin-fw** [comment]
@warrenchristian1telus Can we update the same on the development and test environments as well? Since code (deployment script) changes are required for Camunda, I need to review and test them. For document services, we are not using them straightforwardly; we only trigger them in the background.

**Comment by warrenchristian1telus** [comment]
@bhumin-fw The SSL certificate is only for prod, and won't match dev or test, so would fail. We can add a "docs" route to dev and test ... in fact, I see that has already been done. It was changed in April, 2023:

![image](https://github.com/user-attachments/assets/28c8683f-c9c1-440d-8752-9bdca8c431f6)

Same for test. So prod is the last environment left to get the update.

**Comment by bhumin-fw** [comment]
Right, the Development and Test environments have "docs" route set. Let me check with Stella and plan to update the same in Production. Since PDFs are generated in the approval state for almost all forms, we need someone who can quickly approve them and then inform the BA team that these are test submissions.

**Comment by warrenchristian1telus** [comment]
@bhumin-fw Would we need to create test form submissions for this? Maybe we could just access existing documents/approvals to verify the changes? Anything that reaches out to the [new] docs URL should suffice.

**Comment by bhumin-fw** [comment]
@fazil-ey provide banner message today for 5pm to 5pm.

**Comment by fazil-ey** [comment]
this has been deployed
