### ISSUE TITLE
Mat/Pat - Handle CRM closed ticket scenario

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1310]
We need to handle the scenario when mat/pat form is resubmitted and re approved, but the original ticket created has been closed. 

1. How do we know if a ticket has been closed and when was it closed?
2. Does the behaviour described by Ronda happen automatically?
3. Can we reopen a ticket and add it back to the main queue for the case when ticket is less than 7 days of closing? 

**Comments by Ronda -** 

> If the request has been closed longer then 7 days a new request will be created which references the original.  Given the taxonomy, it would be directed to our team.  If the request is updated within that 7 day window it will open the existing request and note it as updated.  The TES HR Data technician would receive that update.  I would say we risk that the tech may be away, may not action it in a timely manner, perhaps another step needs to be taken… if there is a way to reopen a request to add the updated information and have the SR return to our main queue that would likely be best option – just unsure if that’s possible.

**Comment by Stella-Archer** [comment]
Bhumin reaching out to Mandu to find out what's involved before he can estimate

**Comment by fazil-ey** [comment]
@bhumin-fw  to add details

**Comment by bhumin-fw** [comment]
1. How do we know if a ticket has been closed and when was it closed?
There are no way we will be able to know that ticket is closed. Only one way we have to connately checking ticket status(not recommended to implement on DJ. It will add an overload on workflow plus mass request on CRM). 
2. Does the behaviour described by Ronda happen automatically?
No, Ticket will close when someone closed it. This case only come into picture when we know at what time CRM ticket will be closed by any user.
3. Can we reopen a ticket and add it back to the main queue for the case when ticket is less than 7 days of closing?
Ticket will be active again if we update in this 7 days period, after that we are not able to fetch ticket information.

**Comment by fazil-ey** [comment]
Action item - reach out to contact centre to figure out when they close the tickets. And what would we need to do if the ticket is closed and its more than 7 days. How do we know a ticket is closed.

**Comment by fazil-ey** [comment]
Added all comments & questions in #1324. Closing this
