### ISSUE TITLE
Mat/Pat - Form Name

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1312]
Change the mat/pat form name to - "Maternity, Parental Leave and Allowance form" to reflect that the we also apply for allowance in the form. 

**AC**
- [x] Name change should reflect in 
    - [x] pdf 
    - [x] All emails
    - [x] DJ tabs

**Comment by fazil-ey** [comment]
Form name updated in pdf, DJ tabs and emails, except the task names in Review and process tab
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW1iQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--617df0247f8af851c72f0755b1d46bd0b4277e40/image.png)


And if its a small change, can you also remove "maternity-parental-and-pre-placement-adoption" from the task list

**Comment by bhumin-fw** [comment]
@fazil-ey 
I did hide the "maternity-parental-and-pre-placement-adoption", a process name from the tasklist.
It is ready to test on DEV and TEST environment.

**Comment by ayushdamani** [comment]
Task names in Review tab updated! Also, the process name from the task list is now hidden as well!
Thank you, Bhumin 7& Fazil!

**Comment by fazil-ey** [comment]
looks good!
