### ISSUE TITLE
Onboarding of new developer

### ISSUE THREAD

**Issue by Abuchana** [bcgov/digital-journeys#1314]
A list of things that need to be done to onboard a new dev. Estimate the time/effort required for the tasks. 

Technical 
Business  - What is DJ, what do we do, goals, people - 1 hour meeting  - what would talk about in that 

Potentially use AOT consulting hours to train new developer, record the session

--- 
**_AC_**
- [x] Onboarding process documented in OneNote & link to documentation should be added to this ticket

**Note:** 
Technical onboarding documentation in #1346

**Comment by MeghanStothers** [comment]
Stella set up meeting for next week for devs to download their thoughts.

**Comment by ayushdamani** [comment]
Update: Stella and I prepared a miro board for onboarding.
I will be preparing some questions for our developers and putting them into the board.

**Comment by ayushdamani** [comment]
Update: I have prepared some questions to ask our devs tomorrow at the meeting, which could help facilitate the conversation. The questions are now on the board.

**Comment by iman-jamali-fw** [comment]
Developer onboarding 

- DGJ
    - A short high-level technical overview
- Formflow.ai
    - https://formsflow.ai/
- formio
    - https://help.form.io/
- Camunda
    - https://docs.camunda.org/get-started/quick-start/
- DGJ
    - A more detailed technical walk though to DGJ

**Comment by Stella-Archer** [comment]
technical onboarding #1346

**Comment by ayushdamani** [comment]
Stella and I have created a notebook in OneNote to summarize the conversation we had with the devs, Chris and Fazil.

**Comment by fazil-ey** [comment]
@MeghanStothers  @Stella-Archer  to review the OneNote. @ayushdamani to add a link to the one note.

**Comment by MeghanStothers** [comment]
Last week: Initial technical meeting last week with devs (Fazil/devs)
This week: Business meeting set up for this week (Meghan)
This week: Dev meeting to get Jerry set up on local (Iman/Bhumin)
@iman-jamali-fw @fazil-ey

**Comment by MeghanStothers** [comment]
Business meeting set up for Thursday, October 26

**Comment by MeghanStothers** [comment]
I added the links above to ticket #1346
Closing this ticket as this is an explore

**Comment by MeghanStothers** [comment]
@ayushdamani Thanks for getting us started - can you please add all links to the OneNote = Miro board to ticket
