### ISSUE TITLE
Mat/Pat - Parental allowance EI info popup

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1316]
Split from #932
Content for info popup needs to be updated for calculator on [Parental Leave allowance information page](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184514&cot=14)

**AC**

- [x] Add info popup that shows instructions for EI estimation to help people find how to calculate the estimate for Parental leave allowance calculator.
    - [x] Instructions for Parental leave are in this document. (https://bcgov.sharepoint.com/:w:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/MatPat%20EI%20Estimate.docx?d=wdbc274396c5c43c9abbb204dd8ebca1c&csf=1&web=1&e=pu1etp)

- [x] Add info popup for additional earnings in maternity leave allowance calculator with the following content
> If you are working for another employer and receiving wages, they must be reported as additional earnings.  If you are receiving top up allowance from a separate employer (outside of government), this is not considered additional earnings.

**Comment by ayushdamani** [comment]
Tested in TEST environment.
Working great:
- Updated pop-up for EI estimation
- Updated pop-up for additional earnings
 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL29FQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f59565e4d9ebb4f4debed19a02ba7de9163bb112/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3dFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--738861783d57447a812e92c551b96f58ae46b7c6/image.png)

**Comment by fazil-ey** [comment]
tested and works well
