### ISSUE TITLE
Mat/Pat - CRM ticket field "Secondary Reference"

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1318]
The following CRM ticket field needs to be mapped as follows

- [ ] Secondary reference should be the applicant. Use the applicant's employee number

**Comment by iman-jamali-fw** [comment]
I will meet with Madhu from Telus CRM team today to learn how add the field the ticket

**Comment by iman-jamali-fw** [comment]
Had a meeting with Madhu and he helped me learn how to add a `Secondary Reference` to a ticket through API. I'll work on implementing this feature today.

**Comment by MeghanStothers** [comment]
Bhumin will download and test the ticket for Iman to deploy on Monday

**Comment by iman-jamali-fw** [comment]
@Stella-Archer @ayushdamani 
This is ready for testing on TEST.

Testing instruction:
1. Start a Mat/Pat submission. @ayushdamani Since your CRM contact record lacks employeeId, it's better to ask someone on the team to start the submission.
2. As a manager, validate the submission.
3. Open that submission under the `Submitted Forms` tab and look for its crmId.
4. On the CRM UI, look for that ticket. Check the **Secondary Reference** tab and verify that the employee that submitted the form, is listed under that tab.
5. To ensure **Secondary Reference** doesn't change on CRM update/reapproval, ask the manager to revalidate the submission and then recheck the CRM ticket (step 4).
 
Please let me know if you need more details. Good luck testing :)

**Comment by ayushdamani** [comment]
Thank you for the instructions, Iman!
I have requested Meghan for a submission.

**Comment by ayushdamani** [comment]
1. Requested Meghan to submit a form.
2. Validated the submission.
3. Followed Iman's instruction

I can confirm that the Secondary Reference tab has Meghan listed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanV1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f2569aa3707e2e98014472fe0352732c4259fedb/Screenshot%202023-09-18%20114108.png)

Thank you so much for the instructions, Iman! :)

**Comment by fazil-ey** [comment]
Based on Ayush's screenshot, approving this. We will show the CRM screen to contact centre to verify if everything is as expected for them.
