### ISSUE TITLE
Mat/Pat : Bug with Submission

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1322]
Extra submission for supervisors in the review and process tab of a form that was never submitted and is not in Submitted forms tab.

Video - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-09-14%20at%2010.17.56%20AM.mov?csf=1&web=1&e=kfjbEi

Another double submission, form for "ere", i validated multiple times as a supervisor because it was looping - 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDYwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7311dbb9f35791a9fc3f42639c2fc26c700b318c/image.png)

**Comment by bhumin-fw** [comment]
@fazil-ey fix one issue of task not update correctly in workflow. That fix double task in review tab. 
Could you please review this now? 
Let me know your finding if any on this ticket so we can add proper bug task. I need full form data(You can share basic details and I can collect from camunda) so I can review it's all fields that are present in workflow at right place.

**Comment by fazil-ey** [comment]
Submitted multiple forms and was not able to replicate this issue even after changing the name in draft. We can close this ticket, but keep an eye out to see if this happens again

**Comment by MeghanStothers** [comment]
Okay to close
