### ISSUE TITLE
Tool: Transitioning IDIR Usernames from Email-Based to GUID-Based

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1323]
**Keycloak Username Issue with IDIR Users**

**Problem:**

*Context:* Current IDIR user accounts have usernames that are based on their email addresses. As noted by Marco and confirmed by the IDIM team, email addresses and IDIR IDs associated with users' IDIR accounts are recycled, leading to cases where a different user could have a recycled email or IDIR ID.

Forms/submissions ownership in DGJ for IDIR users is currently based on the email-based username. Therefore, in the event that an email is reused, this causes two issues:
- **Privacy Issue:** Users with a recycled email will have access to all the forms/submissions of the previous IDIR user with that email.
- If the previous email holder has an existing IDIR account in DGJ Keycloak, Keycloak will have difficulty separating these two IDIRs with the same email. Keycloak will see both IDIRs as the same and try to merge them, leading to issues. This has caused some login issues for users and would require manual resolution.

**Solution:**

*Context:* The SSO team suggests moving to a GUID-based username as the GUID is the only unique identifier.

Potential solutions:
- Migrating IDIR users' usernames from email-based to GUID-based.
- Extending Keycloak with extra logic to handle the case when two IDIRs with the same email emerge in the system.

**Why Was Email-Based Username Chosen and What Was the Reason?**

At the time of employee submission of forms that require a manager's review (e.g., Telework and Mat/Pat), the only identifier for the manager is the email that the employee adds or that is auto-populated at the time of form submission. We need to add a manager role to that manager. If the manager has already logged into DGJ, we look for their user account and add the manager role. If the manager has never logged into DGJ, we need to create a temporary Keycloak user account and assign the manager role to it. Having the email as the only identifier, we decided to architect the IDIR users to have their email as their username so that we can create a temporary user account for the manager, constructing a username based on their email and adding the necessary roles to it. Later, when that manager logs in to DGJ for the first time, their actual information will be merged with the temporary account.

To switch to GUID-based usernames for IDIR users, we need to find a way to add the manager role to managers who are added to forms but haven't logged into the DGJ platform at that time. One possible solution is to obtain the manager's GUID based on their email from PeopleSoft at the time of employee submission. This needs to be confirmed by the ODS team for feasibility. Another option, as suggested by Marco, is to trigger the logic for adding the manager role when the manager clicks on the link sent to them in the email.

**Other System-Wide Implications if We Decide to Switch to GUID-Based Username for IDIR Users:**

- **Keycloak:**
    - Changing all the current IDIR users' usernames to GUID-based usernames.
    - Changing all the temporary IDIR user accounts for managers who haven't accessed the system.
- **Formio:**
    - Changing the ownership identifier for submissions and forms from email-based to GUID-based for all IDIR users.
- **Camunda:**
    - Changing all task assignments for IDIR users from email-based to GUID-based. Several tables would require this change.
- **API:**
    - Changing the ownership of drafts/applications/new-version-feature-notification/form-process-mappers from email-based to GUID-based for all IDIR users.
    - Changing the related logic that allows/disallows IDIR users to access forms.
- **Website:**
    - Changing the related logic that allows/disallows IDIR users to access forms.

Please note that the above migration needs to be done for each environment. This means there will be a temporary outage for a few hours in the PROD environment to carry out the migration.

Most of the code needed for the system-level username migration is already available [here](https://github.com/bcgov/digital-journeys/blob/main/scripts/idir-username-migration.js). It's from the time we migrated users to email-based usernames.

**Status of Other IDPs (BCeID, BCSC, and LDB):**

We have configured other IDPs to rely on the most unique identifier as the username, and they won't have the issue of email-based usernames as IDIR users:
- **BCeID** is configured to rely on BCeID username, which is a unique ID as the username `${CLAIM.bceid_username}_bceid`.
- **BCSC** is configured to rely on BCSC GUID ID as the username. Technically, it is recognized as the token sub-ID `${CLAIM.sub}_bcsc`.
- **LDB** is configured to rely on LDB UID as the username. It is set internally at the LDB level and passed under `ldbuid` to DGJ Keycloak.

**Comment by iman-jamali-fw** [comment]
@T854236 
**Context**: The goal is when an employee fills a form, getting their manager's GUID. The employee might put any employee's email in the manager's field (not necessarily the one prepopulated from ODS)

**Question**: Is it possible to get the manager's GUID of an employee? Other words, can we have an endpoint to search for an employee by email and get their GUID?

**Comment by T854236** [comment]
Hi @iman-jamali-fw,  the employee_demo endpoint does contain email and will allow you to filter by email to get the GUID.  I believe this dataset is now part of your caching and might be easy for you to search locally vs. hitting the endpoint.

**Comment by iman-jamali-fw** [comment]
@simensma-fresh  Please feel free to edit/correct the details in the findings above.

**Comment by Abuchana** [comment]
I have reached out to Dennis (TES dev on the PDP team) to inquire what solution was put in place for the PDP application. Hoping we can connect him with our dev team soon.

**Comment by Abuchana** [comment]
@dennis.cinco@gov.bc.ca this is the ticket in question for the DJ team

**Comment by iman-jamali-fw** [comment]
@MeghanStothers @Abuchana @Stella-Archer cc @T854236 
Seems like `EMPID` (employeeId) is the most unique identifier and won't be recycled. However, not all employees have `EMPID`. Are there cases in which DGJ gives service to an IDIR user that doesn't have `EMPID`?

**Comment by iman-jamali-fw** [comment]
Potential issues that have been learned so far for IDIR user's identifiers.

- `email`: 
  - Can be recycled. Can cause privacy issues. A Different user with a recycled email can access the previous user's data in DGJ.
  - User can request to change it. Same IDIR when email is changed, no longer see their data in DGJ.
- `GUID`:
  - Can change (i.e., when an employee moves to another ministry). Even if email stays the same, that user will lose access to data in DGJ.
- `EMPID`:
  - Protected data. Should be checked to see if it can be stored in the Keylcoak and the DGJ system.
  - No all employees have `EMPID`. Accessibility issue

**Comment by Stella-Archer** [comment]
@iman-jamali-fw and @warrenchristian1telus please confirm following update is accurate and complete, edit & update if necessary.

**UPDATE:** 
Team met with Dennis Cinco from the PDP to see what we could learn from how they are approaching the issue

**High level findings:**
-  PDP was designed to use GUID but ran into issues and so now use EMPID to check against GUID
-  DGJ has a broader audience that does not necessarily have EMPID
-  PDP has access to EMPID because of the unique need for tightly tied employee/supervisor relationships
-  DGJ also has many forms needing tight employee/supervisor pairings

**Action/Next Steps:**
* [ ] Warren to investigate getting access for the team to the GUID look up table from Mohan 
* [ ] Iman to work towards plan to migrate off email authentication
* [ ] DGJ Team will use employee GUID and check against EMPID to confirm user
* [ ] DGJ Team develop plan for cases when GUID fails and there is no EMPID to check against

**Comment by warrenchristian1telus** [comment]
Sounds good to me @Stella-Archer .

A couple of updates.

We now have access to the GUID lookup endpoint for dev / test, and prod is scheduled for implementation next week (26th).

@iman-jamali-fw FYI, it’s pretty big. Big enough to possibly crash your browser if you test it that way (80+ MB), and pretty slow. Much more reasonable to just get the relevant fields by appending the select param to reduce some overhead (2.6MB):

?$select=EMPLID,GUID

 - [https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rst#Datamart_Telework_peoplesoft_guid_mapping](https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rst#Datamart_Telework_peoplesoft_guid_mapping)
 - [https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_peoplesoft_guid_mapping](https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_peoplesoft_guid_mapping)

Due to workflow from PeopleSoft > BI > ODS / CDATA production data updates (such as a new GUID) will take up to 48 hours to propagate to (CDATA).

I’ve raised the issue with the team, and am awaiting feedback / discussions on a more timely solution.

**Comment by iman-jamali-fw** [comment]
Following discussions with the PDP team and internal technical experts, we've outlined the next steps:

## Step 1: Transition from Email-Based to GUID-Based Usernames for IDIR Users

Background: Currently, DGJ uses two types of usernames - Keycloak-level usernames, which are based on IDIR information, and system-level usernames, which grant access to their DGJ contents and services (e.g., formio, API, Camunda). Both of these usernames are currently tied to the user's email address associated with their IDIR.

Why the change? Using email-based usernames can lead to privacy concerns due to email recycling. GUIDs associated with IDIR users have proven to be unique identifiers.

Our solution: We'll migrate system-level usernames to a custom GUID generated by Keycloak, known as the Keycloak user ID. This ensures that even if a user's attributes change in the future, their internal DGJ ID remains unique. For example, if an existing IDIR user's IDIR and GUID change (e.g., due to a ministry change), we can update their Keycloak user account while preserving their unique ID, ensuring continued access to DGJ content.

In summary, we'll migrate IDIR users from email-based usernames to IDIR GUIDs at the Keycloak level, while system-level usernames will transition to Keycloak's user account ID.

The required details for implementation will be added to [ticket #1357](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1357).

## Step 2: Automate Handling Exception Cases When an Existing IDIR User's Information Changes

**Improving Step 1**:
Step 1 addressed privacy concerns and IDIR changes, but it lacked automation. When an IDIR user's GUID changes, verifying their connection to an existing DGJ account requires manual intervention. Consider this scenario: UserA submits a form in DGJ, then switches ministries, gets a new IDIR, and logs in again, appearing as a new user. To regain access, the user must contact DGJ for verification, often involving cross-checking employee IDs.

**Related findings:**
- Keycloak's default login flow offers limited control. Extending it with custom Java classes provides full control over various login flows, not just for IDIR but also for future use cases, like linking IDIR and BCSC accounts.
- `EMPID` serves as a unique and unchanging identifier, retrievable through PeopleSoft API calls and storable in Keycloak user attributes.
- Email addresses associated with IDIR accounts can be recycled, potentially requiring additional information from external teams.

By storing `EMPID` and utilizing API calls and external data, we can design a custom Keycloak login flow to automate exception handling, eliminating manual steps in Step 1.

To design this flow, we'll identify and propose solutions for possible cases. Here are some examples:
- When a new IDIR user with a new GUID logs in:
  - If they have an 'EMPID,' check for matches with existing IDIR users' `EMPID`:
    - If matched, update the existing user's account with new IDIR information.
    - If not, create a new Keycloak user account.
  - If a new IDIR user lacks an 'EMPID,' check for matches based on email:
    - If no match, create a new Keycloak user account.
    - If a match, further validation may be needed through external team data.
  - What to do between the time an employee's IDIR information changes (such as GUID) but their information hasn't been updated on PeopleSoft 

The complete list along with the required details for implementation will be added to [ticket #1358](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1358).

**Comment by iman-jamali-fw** [comment]
@bhumin-fw @simensma-fresh @warrenchristian1telus 
This ticket is ready for your peer review. Please let me know if anything else needs to be added to the result of the exploration and next steps. Details for implementation and a complete list of cases can later be added to the implementation tickets (#1357 and #1358).

**Comment by warrenchristian1telus** [comment]
Thanks @iman-jamali-fw - after an email with Marco, it seems we may be able to get current EMPLID, GUID and email / IDIR from BCeID SOAP service (this would need to be a secondary request upon login, or batch sync job). We're in the process of setting up a meeting to discuss our options.

I also discussed this with Phil, and we may be able to get EMPLID set in AD and limited to unique values to keep things stable. Again, pending further discussions.

If we can get EMPLID into AD / KeyCloak, that should solve all our exception cases at once. If EMPLID needs to be unique in AD, it should eliminate (re)creation of users when they switch ministries, etc.. It would also ensure there is never a 24-48 hour delay for things to [re]sync from PeopleSoft to ODS/CDATA.

**Comment by MeghanStothers** [comment]
Excellent summary and research on this one, everyone! We agreed next step is a conversation with TES and other stakeholders to share and take steps.

@warrenchristian1telus Is your last comment the most recent one? You'd mentioned a a "synchronization" solution and I want to make sure we have all possibilities to share with everyone. If not, pop a few notes down. Thanks

**Comment by warrenchristian1telus** [comment]
Updated information has come in from OCIO regarding SSO.

"If the attribute exists in IDIR AD then we can pass it as an identifier through SAML from SiteMinder.  Keycloak’s integration with us as a defined set of generic attributes.  Since most applications will not require the EMPLID attribute it is not included in the Keycloak payload from SiteMinder."

This suggests that they can enable EMPLID for us, which should solve most of our immediate authentication issues arising from a GUID change.

Our alternate plan is to implement a pipeline from PeopleSoft to CDATA. We would need to hook into the GUID update process, and have it send any updates to CDATA, where it could then be consumed by each application. 

My preference is to go with the first option. As long as it can solve our issues within an acceptable time. This should resolve the issues without as much effort, although it would likely still require us to do some sort of batch job to synchronize existing accounts with new data (GUID to EMPLID).

**Comment by MeghanStothers** [comment]
I reopened this one to keep it on our radars for something we'll need to action after mat/par deployment and (before?) Telework deployment and new application upgrade

**Comment by iman-jamali-fw** [comment]
The team will discuss this work this morning.

**Comment by Stella-Archer** [comment]
@warrenchristian1telus would this be a good thing to tackle when we are doing the cData migration? I'd like to get some sense of when would be the ideal time to look at this
@MeghanStothers  is this also some thing that needs to be confirmed at other teams  'all products' level

**Comment by warrenchristian1telus** [comment]
@Stella-Archer I think this will depend a bit on what changes will be required. Will we need to change the structure of data in CDATA, or are all the changes on the application side?

Either way, I doubt it would be a big impact to the CDATA migration. We just need to ensure that any changes are identified and verified in the appropriate environments.
