### ISSUE TITLE
Mat/Pat - Resubmission & closed ticket scenario

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1324]
To handle the cases of resubmission we must update the ticket status to updated every time there is a reapproval. 

**_AC_**
- [x] For every reapproval, the original CRM ticket status should be set to the [updated](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2cxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0e601959a193fab0b2e724caa11373cead7680e/Screenshot%202023-10-13%20at%209.39.11%20AM.png) status, even if the ticket is closed more than 7 days

- [ ] We should verify with the contact centre that the status update after approval is visible and is enough to ensure changes are not missed 

-----------------------
**_Past Notes_**

**Questions**

_**What happens on resubmission (open ticket)?**_ 
On resubmission, Digital journeys will create a new thread in the same ticket that was created when the submission was done initially. 
1. How will the contact centre know there is a change? Lets say the ticket is with payroll, how would they know there is a change in data?  - 
**_The ticket status changes to "UPDATED" and it remains assigned to the same person it was before. They are expected to notice that the status changed and act on the ticket"_**

2. Does the ticket need to be reassigned/sent back to the original HR Admin queue?
**_No, it will be the responsibility of the last person, team it is assigned to check and see what has changed and send it back manually_**

 _**What happens on resubmission (closed ticket)?**_ 
1. When will mat/pat ticket be closed? 
    - What should we do if the ticket is closed? How will it be different before and after 7 days of closure? 
       **_If a ticket has been closed and it is less than 7 days, if the ticket is updated the status will change to "UPDATED" and remain assigned to the last person it was assigned to_** 
**_If a ticket has been closed and it is more than 7 days, how can we update it? Can we replicate the behaviour where a new ticket is opened that reference the old ticket_**

    - Should we open a new ticket? Can we reopen the closed ticket?
    

    - Can we reference the old ticket in the ticket in any way in the new ticket if we open a brand new ticket?

**_The following systems automatically create CRM tickets - how have things been implemented there -_** 

- time and leave schedule forms
- position management change forms 

We need to connect with the contact centre and make sure they are okay with it. - @Stella-Archer 
We need to let Jen O' Leary know as well - @MeghanStothers

**Comment by fazil-ey** [comment]
**Ronda's Comments**
If the request has been closed longer then 7 days a new request will be created which references the original. Given the taxonomy, it would be directed to our team. If the request is updated within that 7 day window it will open the existing request and note it as updated. The TES HR Data technician would receive that update. I would say we risk that the tech may be away, may not action it in a timely manner, perhaps another step needs to be taken… if there is a way to reopen a request to add the updated information and have the SR return to our main queue that would likely be best option – just unsure if that’s possible.

**Comment by fazil-ey** [comment]
**Bhumin's Comments**
How do we know if a ticket has been closed and when was it closed?
There are no way we will be able to know that ticket is closed. Only one way we have to connately checking ticket status(not recommended to implement on DJ. It will add an overload on workflow plus mass request on CRM).
Does the behaviour described by Ronda happen automatically?
No, Ticket will close when someone closed it. This case only come into picture when we know at what time CRM ticket will be closed by any user.
Can we reopen a ticket and add it back to the main queue for the case when ticket is less than 7 days of closing?
Ticket will be active again if we update in this 7 days period, after that we are not able to fetch ticket information.

**Comment by fazil-ey** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2cxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0e601959a193fab0b2e724caa11373cead7680e/Screenshot%202023-10-13%20at%209.39.11%20AM.png)

**Comment by MeghanStothers** [comment]
Bhumin to deploy on dev

**Comment by ayushdamani** [comment]
Tested in the TEST environment, confirmed working!

**Comment by fazil-ey** [comment]
We see that the CRM status is updated everytime there is an update. We will try to close a tickets and wait 7 days, update and see if the status is changed to updated

**Comment by fazil-ey** [comment]
tested with 231115-000006 CRM ticket. It was solved and after 9 days we updated it and it went through ok with the ticket status updated to "updated"
