### ISSUE TITLE
Mat/Pat - UX - Maternity leave allowance

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1332]
**Maternity leave - Leave allowance information**
1. Ensure we use "maternity leave allowance", not "top-up allowance"

_**Maternity leave allowance**_
1. Put the returning to work warning in yellow alert box for emphasis. Changed wording to make it easier to understand
2. Changed the 2nd example in what did you colleagues do to make it clearer that the person chose to defer. 
3. Split the information and question into 2 sections with separate heading to make the actual form field distinct
4. Changed radio button text for clarity

**_Design_** - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184497&cot=14

**AC**
-  [x] Content & layout matches design for maternity leave allowance **_(the yellow warning box is missing)_**
-  [x] Maternity Leave allowance information page uses only maternity leave allowance to refer to allowance
-  [x] Ensure Union code cc logic works for both maternity & parental leave allowance pages

**Comment by fazil-ey** [comment]
Additional Earnings tooltip - to be added by developers, everything else is done

**Comment by fazil-ey** [comment]
Spacing needs to be fixed

**Comment by fazil-ey** [comment]
Asked Andrew to confirm if th eunion code logic has been implemnted

**Comment by Andrew-Vargas-bcgov** [comment]
completed CC logic. @ccoldwell Do we need to add anything else for this ticket before moving to test?

**Comment by ayushdamani** [comment]
Looking great!
- Tested in the TEST environment.
- The page matches the design in the Miro board

Acceptance criteria met ✅

**Comment by fazil-ey** [comment]
Looks good!
