### ISSUE TITLE
Mat/Pat - Edits disabled after changing start date to current date on resubmission

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1335]
Edits disabled after changing start date to today on editing a form after its been validated by supervisor

**_Steps to recreate -_** 
1. Submit a mat leave application with a start date in the future and approve it
2. Edit the mat leave start date to todays date
3. Observe that all edits get disabled (except mat allowance choice)

**_AC_**
- [ ] Applicant should be able to submit an application with the current date as start date for maternity or parental leave

**_Video -_**  
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-09-19%20at%208.10.33%20AM.mov?csf=1&web=1&e=N20dMZ

**Comment by iman-jamali-fw** [comment]
@ayushdamani 
Ready for your test on TEST. The bug should no longer happen :) 

To replicate it you should submit a mat/pat then approve it as supervisor and finally open it as an employee for edit. In that case, the described bug used to happen. Also, watch the video Fazil shared to learn more about that bug. Good luck testing

**Comment by ayushdamani** [comment]
Since I am not able to approve my own submission, I would request the team at check-in to test this with me.

**Comment by fazil-ey** [comment]
Cannot reproduce bug. Works well!
