### ISSUE TITLE
STRA: Security Review for Mat/Pat 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1336]
Security/review/risk assessment of the maternity/parental leave Digital Journey is required for launch. 

A/C
( )Meeting with PSA Security team to review the Digital Journey
( ) Sign-off/Approval my PSA Security team for inclusion in the PIA

**Comment by MeghanStothers** [comment]
@warrenchristian1telus Hello, I'll be setting up a session with the security team for their review of the maternity parental leave Digital Journey. It's likely they will ask about security vulnerabilities that may affect our ability/approval to launch. Let's connect about any high-level issues on the dashboard we can/could/should resolve before the review.

**Comment by warrenchristian1telus** [comment]
Hi @MeghanStothers - There is currently an update to the hamongo instance (forms-flow-db) that we should look into patching in all namespaces.

**Comment by MeghanStothers** [comment]
Thanks - I've set up a meeting with our security specialist to start the conversation about what we would need to address before launch (so we we can estimate and action, of course :)

**Comment by fazil-ey** [comment]
Meeting with Igor, he said we are "golden" i.e no major issues found. 

Next Action items - 

Warren to see the "security dashboard" in openshift to see if there are any high priority security issues identified.  

We need to meet with Igor again when were are closer to release and do a final review. We need the email sign off as approval to launch.

**Comment by warrenchristian1telus** [comment]
Security dashboard still looks good. Will verify again with Igor closer to release date.

**Comment by fazil-ey** [comment]
@MeghanStothers  to meet Igor to review and look at it in relation with the PIA

**Comment by MeghanStothers** [comment]
@warrenchristian1telus Hi Warren, any security concerns on our dashboard that are blockers for our Dec 4 release to PSA (internal teams) as well as the TES payroll team?
