### ISSUE TITLE
Mat/Pat - Employee Information info popups

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1341]
In the Employee information page, we need to add explanations for Appointment Status and Employee Class as most applicants dont know what these terms mean

**_AC_**
-  [x] Add info popup for Employee Class with the following content

> Union code or Excluded

-  [x] Add info popup for Appointment status with the following content

> R - Regular
> M - Auxiliary with health benefits including leave
> K - Auxiliary with health benefits
> L - Auxiliary without benefits

Design v4 - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564125309764&cot=14

**Comment by ayushdamani** [comment]
Bhumin is reviewing the ticket.

**Comment by ayushdamani** [comment]
Thank you so much @bhumin-fw 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1hTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7acb7395da99cb43b5ab54be228c244e646458b7/image.png)

**Comment by fazil-ey** [comment]
looks good, the pop ups are present and have the correct text.
