### ISSUE TITLE
Mat/Pat - Improve UX if there is error on the review page

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1342]
If there is a validation error on the review page, when we hit next it doesn't scroll up to the error. It can be confusing for users as they might think the button is not working. 

**_AC_**
- [ ] Scroll up to the top of the page where all errors are shown 

Video - 
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-09-20%20at%203.49.26%20PM.mov?csf=1&web=1&e=Xmgboy

------
Explore ticket #1349 after which this can be fixed

**Comment by ayushdamani** [comment]
Working great, Iman! Thank you for the instructions!

**Comment by fazil-ey** [comment]
Works well, thanks!
