### ISSUE TITLE
Mat/Pat - Change in allowance validation

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1345]
Currently we validate that the option for both parental and maternity leave allowance is the same. However, the validation should be as follows

1. If deferring maternity leave allowance, must defer parental leave allowance
2. If claiming maternity leave allowance, can choose to not claim parental leave allowance
3. If not claiming maternity leave allowance, can choose to claim parental leave allowance

**_AC_**
- [x] Applicants are able to select the options as per the above logic

**Comment by MeghanStothers** [comment]
scrum note: Point 2 and 3 not able to defer in parental leave

**Comment by ayushdamani** [comment]
Tested in TEST environment.
Tested the validation logic which Bhumin has posted above.
Working great!

**Comment by fazil-ey** [comment]
hey @bhumin-fw, can we change the validation message from
 "You can only select claim or not claim claim any leave allowance"

to 

"You must defer both maternity and parental leave allowance. You cannot defer only one type of leave allowance."

**Comment by bhumin-fw** [comment]
Update validation in both selection mat & pat.
Also updated message as per above comment. This change is ready to review on DEV and TEST.

**Comment by fazil-ey** [comment]
Error message is not updated for parental leave allowance in the review page and the Parental leave - leave allowance tab. It should be "You must defer both maternity and parental leave allowance. You cannot defer only one type of leave allowance."
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU11QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94620c4ca4eafd743ed6d74577c7be9c1579384d/image.png)

**Comment by bhumin-fw** [comment]
@fazil-ey 
Here you have selected "defer" but on maternity it is not defer. Which means that (defer one) error message will be display on maternity leave allowance.
we can correct this message, but if you want to put only "defer" msg on both side, I can take a look into that.

**Comment by bhumin-fw** [comment]
@fazil-ey Fix message in review page.

**Comment by fazil-ey** [comment]
Works well
