### ISSUE TITLE
Technical onboarding documentation of new developer

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1346]
Based on the dev onboarding session, we can have this ticket capture the technical steps and add it to the repo.

**AC**
- [ ] Document only Week 1 steps/action required (providing links, high level how to, highlighting imp/relevant parts for DJ, how to make account in keycloak, links to relevant AOT recordings & more!)

**Comment by fazil-ey** [comment]
From @iman-jamali-fw 

Developer onboarding

DGJ
A short high-level technical overview
Formflow.ai
https://formsflow.ai/
formio
https://help.form.io/
Camunda
https://docs.camunda.org/get-started/quick-start/
DGJ
A more detailed technical walk though to DGJ

**Comment by fazil-ey** [comment]
Documented day 1, 2 3, and using AOT consulting hours on [onenote](https://bcgov.sharepoint.com/teams/03991/_layouts/15/Doc.aspx?sourcedoc={6f028f9f-6cf7-4828-98b6-9f8a532f3b29}&action=edit&wd=target%28Onboarding.one%7Cf150e25d-8b12-442c-96fd-1d9be1a4480c%2FProcess%20Roles%20and%20Activities%7C3c0d55e4-97f4-4e48-95ed-3354e4214a1f%2F%29&wdorigin=Navigation)

**Comment by MeghanStothers** [comment]
I have closed #1314 and this one this one so we have one resource and links on #1403
