### ISSUE TITLE
Tool - Explore wizard Form issues that dont work, but work for regular forms

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1349]
There are some bugs in the wizard forms that work for normal forms. e.g. links opening in the same tab, screen not scrolling up to the error on the page. We need to explore how this works in wizard forms

 
Related to #1342,  #1274

- [x] Explore why links are not opening in a new tab
- [x] Explore why page does not scroll to the top when there is an error on the page

**Comment by iman-jamali-fw** [comment]
Progress report:
Added a PR for fixing openning links in separate tabs. Will continue working on fixing scroll to validation errors today.

**Comment by iman-jamali-fw** [comment]
First AC: Explore why links are not opening in a new tab was done and ready for testing in #1274 ticket.

**Comment by iman-jamali-fw** [comment]
Second AC: **_Explore why page does not scroll to the top when there is an error on the page_** was done and ready for testing in #1342 ticket,
