### ISSUE TITLE
1.10: Text update

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1350]
The wording of the last question on our Article 1.10 form is creating operational issues and we would like to change it:

From: “Are you open to participating in an alternate dispute resolution process, rather than an investigation?”

To: “If the employer decides that an investigation or review will occur, are you open to participating in an alternative dispute resolution process?”

**Comment by ayushdamani** [comment]
Changes have been made.
Just wondering, since I made the changes, can I go ahead and test as well or would this be tested better by someone else?

**Comment by MeghanStothers** [comment]
Tested with Ayush - approved. Can be pushed to prod. @ccoldwell can you do that? Hooray Ayush on your first official edit - nice!

**Comment by chriscaldwell-psa** [comment]
Changes have been made in Dev and Test, devs can push to prod when ready.

**Comment by MeghanStothers** [comment]
Stella sent note to Don -waiting for his okay

**Comment by MeghanStothers** [comment]
Ayush has permissions and can make the change in prod so the changes are live @ayushdamani let Stella know when this is done.

**Comment by MeghanStothers** [comment]
@ayushdamani can you please share if this has been done?

**Comment by ayushdamani** [comment]
Yes, the changes have been pushed to Prod :)

**Comment by MeghanStothers** [comment]
closed
