### ISSUE TITLE
Mat/Pat - Parental leave UX + Other minor changes

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1351]
**Parental Leave** 

**Parental leave allowance dates** 
Design v4 - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564975455481&cot=14
- [x] Content and layout should match the design
- [x] Add the start and end dates of parental leave in the alert box  (#1193)

**Comment by chriscaldwell-psa** [comment]
Parental leave - Leave allowance dates tab content edits have been updated. @Andrew-Vargas-bcgov  - over to you.

**Comment by ayushdamani** [comment]
Checked for the updated changes in the TEST Environment!

Thank you, Andrew and Chris!

**Comment by fazil-ey** [comment]
copying here reference and keeping the ticket clean - 

- [x] Change description
> If you are the **birthing parent** you can take parental leave **after your maternity leave ends.**
If you are the **non-birthing or adoptive parent** you can take parental leave **after your child is born or placed after adoption.**

- [x] remove the extra space
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDNOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--57a22e32abe0bfa3a4fd4f2869ddb0a1809b7807/image.png)

- [x] changed "does your partner.." to h3 heading
**Verify partner info**
- [x]  Change content to 
>Please verify your partners information. You cannot edit this information in the form. If your information is incorrect or 
> missing:
> 1. For Ministry, Department - Ask your partner's supervisor to submit an _AskMyHR Request under PSA > Supervising and Leading People > Employee Status Change_ to correct the information.
> 2. For Name - Ask your partner an AskMyHR request under _PSA > Supervising and Leading People > Employee Status Change_
> 
> Radio button 1 - I confirm that my partner's information is correct.
> Radio Button 2 - My partner's information is incorrect or missing. I have completed the steps to correct the information.

**Parental leave - General information**

- [x] content & layout must match new design v4 -  https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184512&cot=14

**Parental leave - Leave type and length of leave**
- [x] Fix the spacing [Private Zenhub Image] for type of leave(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcm5WIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a8a7a77b45da5f3c152eb0c66392ac29170844a8/image.png)
- [x] Fix the spacing [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlhhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--77096fbba2b42726fa1c5c9d3bcf2c43cda02b13/image.png)
 
- [x] Update the example

> Since the daycare in my locality had a long waitlist, I wanted to take the maximum leave possible. So as the birthing parent, I took 61 weeks of extended parental leave. My partner also works for BC public service, so his leave type had to be same as mine. Thats why he chose extended parental leave, even though he wanted to only take 4 weeks off. My extended parental leave started after my 17 weeks of maternity leave and his parental leave started on the day the baby was born. 

> **Parental Leave Start Date** Moved to #1376
> Design (With DOB)- https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564970662480&cot=14
> Design (Without DOB) - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564971175906&cot=14
> - [x] Content and layout should match
> - [x] Standard leave/Extended leave logic for the start date limit must work
> - [x] The right layout should display based on taking leave with mat leave or without
> - [x] Colleagues say content should also be updated

> **_Parental leave allowance selection_**  #1377
> Design - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564972369674&cot=14
> - [X] Content and layout should match
> - [x] Crown Counsel logic should also work

> **_Parental leave allowance type selection_**  #1378
> Split into 2 screen - one information, one selection
> New screen - Parental leave - Allowance type information - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564973098203&cot=14 (@Chris)
> - [x] Content/layout should match new screen
> 
> Parental leave - Leave allowance type v4 - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564974489838&cot=14
> - [x] Content/layout should match new screen
> - [x] Show warning about standard leave only if taking extended leave


**Maternity leave start date**
- [x] Fix the spacing
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXJOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1a65cfc4999d6f9291c7cf9227584f6ae1567e22/image.png)

**Employee Information**
- [x] Make "Change" italicized
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTNWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6cd5d01030dd5e5ac742a36e9fe63967576a90be/image.png)

** Maternity leave - length of leave* 
- [x] fix the spacing [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmZWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b185eca8912df7275cc3eaa5fb68ac1482f2d583/image.png)

**Maternity leave allowance information**
- [x] Check "Your" - [Private Zenhub Image] (https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1hWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--81bbe55b7e97faef20cebc14537a90a4a31560b4/image.png) and add space above line

**Comment by fazil-ey** [comment]
Hey @chriscaldwell-psa, can you remove the what did your colleagues do from this page as per the [design](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564975455481&cot=14). Removed it since there are already too many warnings/info ont his page.

**Comment by chriscaldwell-psa** [comment]
@fazil-ey  - Dev and Test env's are now updated with the changes.

**Comment by fazil-ey** [comment]
looks good
