### ISSUE TITLE
Internal Server Error - Incognito Mode did not work. 

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1353]
Background: A manager reported an "Internal Server Error" on Sept 18. She needed to submit a  telework agreement as an employee and approve her staff's telework agreements. She cleared her browser cache, and with her sharing her screen [with me] went into incognito/private mode for both Edge and Chrome. The Error message still persisted.
 
Recent changes from her: IDIR changed within the last 3 months,  last name changed, Email looks suspicious: (email & Idir removed from ticket)
Note: having a past employee the day before select Incognito mode did work, however this new manager was not able to bypass the error message with me watching. User had contacted the OCIO and said her IDIR was fine. 
We need to find out how to troubleshoot this issue and its cause. SSO had recommended to contact the WAM team (web access management - not sure if this is the recommended step going forward).

 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3pOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe412b4f9753b36e9f68c0f1a82a8785ea257bd5/NFanks_InternalServerError.png)

 
Steps to Reproduce:
 
Actual Behavior: 
 
E[Uploading... NFanks_InternalServerError.png]
xpected Behaviour: Employee should be able to login to the forms portal without an internal server message. 
 
Environment: Prod

**Comment by chriscaldwell-psa** [comment]
We have another user that reported an Internal Server Error on September 25th. Director needs to approve her employee's telework agreements and receives the error after she logins her IDIR credentials.  Please note: Last name has changed within the last month, OCIO indicated there are no duplicate conflicting IDIRS. However, employee has two active emails still open (that she uses).  IDIR: BGILLILA.  Keycloak record indicates she has no attributes listed.  I did not delete any attributes in the past.

**Comment by chriscaldwell-psa** [comment]
[Uploading... B_GillilandError.png]

**Comment by iman-jamali-fw** [comment]
Thank you @chriscaldwell-psa  for the detailed description. I'll look into it and will get back to you.

**Comment by iman-jamali-fw** [comment]
For both users, I found error logs in the Keycloak pods indicating a problem:

```
ERROR: Duplicate key value violates unique constraint "uk_ru8tt6t700s9v50bu18ws5ha6"
  Detail: Key (realm_id, username)=(psa-digital-journey, user_email) already exists.
```

This means that when these two users logged into our Keycloak Instance, Keycloak identified them as existing users. They had temporary Keycloak user accounts, likely created when they were assigned as managers. The issue was that Keycloak couldn't merge their IDIR information with the existing temporary user account, as both were mapped based on the user's email.

I couldn't pinpoint the exact failure in the Keycloak login flow, as I couldn't find a useful log. However, I believe that if we delete their temporary user accounts and have them log in again, this should resolve the problem. We just need to add their manager group/role after a successful login.

**Comment by chriscaldwell-psa** [comment]
I deleted their profile in Keycloak this morning and indicated to Nicola that she should be able to login and to let me know if she encounters any issues. 
I'll update this ticket if she responds with any issues.

**Comment by chriscaldwell-psa** [comment]
I deleted their profile in Keycloak this morning and indicated to Nicola that she should be able to login and to let me know if she encounters any issues. 
I'll update this ticket if she responds with any issues.

**Comment by chriscaldwell-psa** [comment]
Just received an update  that the first employee who had the issue no longer is receiving the error message - Removing their profile seems to be consistently working! thanks Iman :)

**Comment by fazil-ey** [comment]
If we see this error again, we should tell a developer to look at the logs, as this is our server we have all the logs we need to diagnose the issue and recommend a solution. 

Try not to put any private info - IDIR, emails as all this is public . Best to connect with developers directly
