### ISSUE TITLE
Mat/Pat - Supervisor form edit logic

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1356]
**AC**

- [x] Direct supervisor to Review page when they open the form. Supervisor should be able to edit on the review page
- [x] Only tabs that necessary for the edits to be successful should be visible. Hide all other tabs from the forms. 

- [x] Maternity leave before leave start 
       - Supervisor can change maternity leave start date to any date 1 month in the past 
       - Supervisor can change to a future date - 2 months in the future
       -  Supervisor can change length of leave
-------     
- [x] Maternity leave after leave start 
       - Supervisor - change the start date 1 month in the past, 2 months in the future
       -  Supervisor can change length of maternity leave
-------- 
- [x] Parental leave (with maternity leave) + before leave starts 
      -  Supervisor can change maternity leave start date to any date 1 month in the past 
       - Supervisor can change maternity leave start date to a future date - 2 months in the future
       - Supervisor can change parental leave start date - to a date after maternity leave ends 
       - Supervisor can change allowance dates between start and end date of the parental leave
       - Supervisor can change length of maternity & parental leave 
-------- 
- [x] Parental leave (with maternity leave) + after leave starts 
      -  Supervisor can change maternity leave start date to any date 1 month in the past 
       - Supervisor can change maternity leave start date to a future date - 2 months in the future
       - Supervisor can change parental leave start date - to a date after maternity leave ends 
       - Supervisor can change allowance dates between start and end date of the parental leave
       - Supervisor can change length of maternity & parental leave 
---------
- [x] Only Parental leave before leave start
       - Supervisor can change date of birth - current date or any past date 
       - Supervisor can change parental leave start date -  52 weeks/78 weeks after date of birth but no more than 2 months in the future
       - Supervisor can change allowance dates between start and end date of the parental leave
       - Supervisor can change length of parental leave 
----------
- [x] Only Parental leave after leave start 
      -   Supervisor can change date of birth - current or past date 
      - Supervisor can change parental leave start date -  52 weeks/78 weeks after date of birth but no more than 2 months in the future
      - Supervisor can change allowance dates between start and end date of the parental leave
      - Supervisor can change length of parental leave 
  

- [x] Add popup warning  - "Please ensure the employee has not already started their maternity or parental leave" for cases, if the maternnity leave start date or parental leave start date is in the past .

**Comment by Andrew-Vargas-bcgov** [comment]
Added permissions for supervisor to edit length of leave (all types) and leave allowance start/end dates.
Added 52/78 weeks check validation.
Added validation for 1 month in past or 2 months in future for parental leave (excluding Mat + parental per requirements)
left to do: add additional validation for maternity start dates.

**Comment by Andrew-Vargas-bcgov** [comment]
Just clarifying with Fazil one final popup condition and then moving to test.

**Comment by Andrew-Vargas-bcgov** [comment]
@ayushdamani ready to test.

You will need to test the different validation cases from the supervisor's perspective.

The pop up condition works as so:

- If leave has started (start date from the last time the form was submitted), and the supervisor changes the leave start date to a date in the future, upon submit a popup will appear indicating that the supervisor should make sure that the employee's leave has not already started.

**Comment by ayushdamani** [comment]
Tested in the TEST environment - I was able to test individual case scenarios from a supervisor's perspective ✅

Thank you, Andrew!

**Comment by fazil-ey** [comment]
I am able to make the changes, but unable to actually submit - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-10-23%20at%204.18.55%20PM.mov?csf=1&web=1&e=l2E7bA

**Comment by fazil-ey** [comment]
Unable to submit a parental only leave, error saying child's date of birth is in future when it is todays date 

video - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-10-30%20at%204.35.13%20PM.mov?csf=1&web=1&e=7qS91G

**Comment by fazil-ey** [comment]
This AC failed
- Supervisor can change parental leave start date -  52 weeks/78 weeks after date of birth but no more than 2 months in the future based on standard/extended leave

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnYvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7057ff2aa1a50d9969370f4ca40415c202a91fbf/image.png)
