### ISSUE TITLE
TOOL: Enhance User Account Management - Username Migration - Step 1/2

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1357]
User Story:
As an IDIR user logging into DGJ, I want a unique user account to prevent sharing when my email is reused by another IDIR user. I also need access restoration when my IDP changes (e.g., changes to a user's IDIR after their ministry changes).

Acceptance Criteria:
- Migrate existing IDIR usernames to their respective IDIR's GUID at the Keycloak level.
- Migrate existing usernames from all IDPs (IDIR, BCeID, BCSC and LDB) to their respective Keycloak ID at the system level.
- Set GUIDs as the usernames for all the new users from all IDPs at the Keycloak level.
- Set Keycloak ID as the username for all new IDIR users at the system level.
- Migrate existing temporary IDIR user accounts to IDIR GUIDs at the Keycloak level.
- Migrate existing temporary IDIR user accounts to Keycloak IDs at the system level.
- Assign new managers, without existing Keycloak accounts, with manager IDIR GUIDs in Keycloak and Keycloak IDs at the system level.
- Ensure IDP-specific form access functions correctly with the new system-level Keycloak ID usernames (e.g., IDIR-specific forms only accessible to IDIR users).
- Prevent release note prompts from appearing for existing users who have already viewed those release notes.

 

Technical notes:
- IDIR Keycloak-level usernames are configured under `Identity Providers > IDIR > Mappers > username`.
- DGJ system-level usernames are configured under `Clients > forms-flow-web > Mappers > preferred_username`.
- Refer to [these scripts](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/here) automated migration steps.
- Ensure that both existing and new temporary Keycloak accounts for managers have an Identity Provider Link based on GUIDs ([Link](https://www.keycloak.org/docs-api/22.0.3/rest-api/index.html)) to minimize login issues reported by some managers.

**Comment by fazil-ey** [comment]
This is higher priority than #1358, if IDIR email is recycled, the other user who is using it might have access they should not have. 

Ballpark estimate - 8 points

**Comment by fazil-ey** [comment]
@bhumin-fw  to investigate further

**Comment by fazil-ey** [comment]
Only risk is if someone with the same name is reassigned an email of a former email with the same email. They will see old employees submission. 

Action item - 
1. Check with the team that assigns emails, do they recycle emails i.e. reassign an old email to a new person with the same email. Ask Igor or someone from OCIO
2. Ris

2. Risk is mitigated by retention policy, if we delete forms in 6 months to 1 year.

**Comment by fazil-ey** [comment]
Comments from Igor about recycling 

[11:26 AM] Buchanan, Alison L PSA:EX
[11:25 AM] Krasnov, Igor PSA:EX
Hi Alison, yes, I would agree with your assessment, the "recycled IDIR" incidents are now very rare as the IDIM team now uses IDIR Table tool when they want to reassign an IDIR.
[11:27 AM] Buchanan, Alison L PSA:EX
I do not think we have had a single incident of this nature this year
