### ISSUE TITLE
Mat/Pat - Supervisor Confirmation 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1359]
Supervisors should see the a confirmation screen when they approve or deny a form. 

**_Design -_** 
Approval - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764567822490602&cot=14
Denial - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764567825651345&cot=14

**_AC_**
- [x] Supervisor sees the correct confirmation page on approval and denial

**Comment by jerry-ey** [comment]
@ayushdamani @fazil-ey this change is ready to test on TEST env. let me know if you face any other issue while testing this one.

**Comment by ayushdamani** [comment]
Since I am not able to validate my own submissions, I will request the team at check-in to test this together.

**Comment by ayushdamani** [comment]
For a submission APPROVED:

"Employees must inform their supervisor if there are any changes to the start date of **the** their maternity.."

Could you please remove "the" from the sentence? Apologies, since there was an error on the Miro board.

**Comment by jerry-ey** [comment]
@ayushdamani Please review again, I removed "the".

**Comment by ayushdamani** [comment]
Thank you so much for the update, Jerry! Moving to PO

**Comment by fazil-ey** [comment]
looks good
