### ISSUE TITLE
Mat/pat: Content change for forms designer

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1363]
When testing the mat/pat journey, the section was intended for X and the screen showed X

**Comment by MeghanStothers** [comment]
[Uploading... image.png]

**Comment by MeghanStothers** [comment]
Should show "parental leave: not " maternity"[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEx5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f9f1484a0472ec3eb246d5832b9e5dc55d96e355/image.png)

**Comment by Stella-Archer** [comment]
This doesn't seem to be an issue any more, Headline and Navigation both correctly say 'Parental Leave'
<img width="1543" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2o0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45cb9ca4460352b82ca07ba3b5279abe0acf7fd6/image.png" alt="image.png" />
