### ISSUE TITLE
Mat/Pat - Bugs in Submission

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1369]
While testing #895 & #1334, i noticed some bugs. I submitted a form for only maternity leave

- [x] On submission i saw this error, but did not see any validation error.  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFlBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--771443580507c5990f2a6da2b47f5ce5555ff083/Screen%20Shot%202023-10-03%20at%204.31.20%20PM.png)

- [x] I also noticed duplicate drafts for the form that I saw an error on submission. However, the form is not in Review & Process tab. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGNBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22f28a2606e7bb7bef40ba8e9c3ad5baf7e1a19a/image.png)

**Comment by MeghanStothers** [comment]
Ayush to perform 4 to 5 more tests and close the ticket.

**Comment by ayushdamani** [comment]
Submitted a couple more forms, and did not face this error.
Closing this ticket.

**Comment by ayushdamani** [comment]
Submitted a couple more forms, and did not face this error.
Closing this ticket.
