### ISSUE TITLE
Mat/Pat - Content -  Add info about tax to emails

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1371]
This was raised by Igor during the security review. Connie said they get a lot of questions about the tax. We should add this info in all the approved emails.

> 
> Income tax is deducted from maternity/parental leave allowance and EI payments — you may want to discuss your personal tax situation with an independent financial adviser.
> - You can choose to have additional taxes deducted to cover the income earned from both sources. Submit a federal TD1 form through an AskMyHR service request using the categories _Myself (or) My Team or Organization > Submit a Form or Document > Direct Deposit/Tax Forms (TD1)_ or by fax to 250-652-2155.
>

**Comment by fazil-ey** [comment]
changes done, to be tested

**Comment by MeghanStothers** [comment]
Ready to test

**Comment by fazil-ey** [comment]
There is a ? instead of a hyphen - 

"Income tax is deducted from maternity/parental leave allowance and EI payments **_?_** you may want to discuss your personal tax situation with an independent financial adviser.
You can choose to have additional taxes deducted to cover the income earned from both sources. Submit a federal TD1 form through an AskMyHR service request using the categories Myself (or) My Team or Organization > Submit a Form or Document > Direct Deposit/Tax Forms (TD1) or by fax to 250-652-2155."

**Comment by fazil-ey** [comment]
looks good
