### ISSUE TITLE
Mat/Pat - UX: Content addition - Tax 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1374]
As an employee going on leave, I want to be aware of the financial implications of my choices so I can take action before I go on leave.

**Comment by MeghanStothers** [comment]
Connie advised that users often have this question or find out afterwards they had an unwanted tax bill after collecting leave allowance. Giving them this info upfront id ideal.

Connie provided this information:

Income tax implications: Income tax is deducted from maternity/parental leave allowance and EI payments—you may want to discuss your personal tax situation with an independent financial adviser.
You can choose to have additional taxes deducted to cover the income earned from both sources.
Submit a federal TD1 form through an AskMyHR  service request using the categories Myself (or) My Team or Organization > Submit a Form or Document > Direct Deposit/Tax Forms (TD1) or by fax to 250-652-2155.
Remember to complete a TD1 when you return to work if you wish to discontinue having additional taxes deducted.

**Comment by MeghanStothers** [comment]
Recommend shortening and adding a link to this page for info about how to take this action: 
Yes…that’s where it’s from…it’s in both the maternity and parental leave sections.

Connie

Connie Der, Manager, Benefit Design and Programs
Employee Relations Division | BC Public Service Agency 
1st Floor, 810 Blanshard Street | Victoria BC | V8W 9V1 | Office 778 698-7879
AskMyHR: www.gov.bc.ca/myhr/contact




From: Stothers, Meghan PSA:EX <Meghan.Stothers@gov.bc.ca> 
Sent: Thursday, October 5, 2023 1:37 PM
To: Der, Connie J PSA:EX <Connie.Der@gov.bc.ca>
Cc: Fazil Hussain <Fazil.Hussain@ca.ey.com>
Subject: FW: Mat/Parental leave: Tax 
We will look into weaving this info somewhere into the DJ, ideally shortening it a bit and possibly linking to this page: 

https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/leave-time-off/maternity-parental-pre-placement-adoption/maternity?keyword=maternity

**Comment by fazil-ey** [comment]
this has been added to email
