### ISSUE TITLE
Mat/Pat - Parental Leave Start Date UX changes

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1376]
**Parental Leave Start Date**
Design (With DOB)- https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564970662480&cot=14
Design (Without DOB) - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564971175906&cot=14
- [x] Content and layout should match (the questions for the text fields are missing currently)
- [x] Standard leave/Extended leave logic for the start date limit must work 
- [x] The right layout should display based on taking leave with mat leave or without
- [x] ~Colleagues say content should also be updated~

**Comment by Andrew-Vargas-bcgov** [comment]
ready to test

**Comment by ayushdamani** [comment]
Tested this in TEST. Need to discuss some errors with Fazil.
For design with DOB:
1. Period at the end of the pointers are missing.
2. "When was our baby born or placed after adoption?" and "When do you want to start your leave?" are bolded.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGt0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6c5483ed305c4ef07a773535ac021b1347ee76c/Screenshot%202023-10-12%20064141.png)

For design without DOB:
1. "When do you want to start your leave?" is bolded

**Comment by Andrew-Vargas-bcgov** [comment]
@ayushdamani added the periods. Not sure what you mean by bolded, are they different from other fields?

**Comment by ayushdamani** [comment]
Thank you for the fix, Andrew!
My apologies for the 'bold error', I was mistaken.
Moving it PO.

**Comment by Andrew-Vargas-bcgov** [comment]
removed periods. 
added spacing between the two warning alert boxes.
added back in the standard and extended leave validation for parental only start date.
@ayushdamani ready to test

**Comment by ayushdamani** [comment]
Thank you for the update, Andrew! Confirmed the following are updated:
1. The period from the sentences have been removed.
2. The spacing between the two warning boxes have been fixed.
3. The validation for start date has also been fixed with updated error message, as advised by Fazil.

**Comment by fazil-ey** [comment]
tested and works well
