### ISSUE TITLE
Mat/Pat - Parental leave allowance selection UX changes

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1377]
**_Parental leave allowance_** 
Design - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564972369674&cot=14
- [X] Content and layout should match
- [x] Crown Counsel logic should also work (i.e remove "or the length of the leave you take, whichever is longer,")

**Comment by Andrew-Vargas-bcgov** [comment]
moved to test

**Comment by ayushdamani** [comment]
Tested this in TEST environment. I see a couple of errors, which I could be incorrect about. 
Would discuss them with Fazil at check-in

[Uploading... Screenshot 2023-10-12 063518.png]

**Comment by Andrew-Vargas-bcgov** [comment]
@ayushdamani oh i see that. Just fixed it. what other errors do you see?

**Comment by fazil-ey** [comment]
Content & layout matches
