### ISSUE TITLE
Mat/Pat - Parental Leave Allowance type - UX changes

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1378]
**_Parental leave allowance type selection_**  
Split into 2 screens - one information, one selection
New screen - Parental leave - Allowance type information - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564973098203&cot=14 (@Chris to add new screen)
- [x] Content/layout should match new screen

Parental leave - Leave allowance type v4 - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764564974489838&cot=14
- [x] Content/layout should match new screen
- [x] Show warning about standard allowance only if taking extended leave
- [x] Show warning about only standard is allowed for standard leave only if taking standard leave

- [x] Both allowance pages should only be seen if the applicant selects that they want to receive allowance during the leave

**Comment by chriscaldwell-psa** [comment]
@fazil-ey  I would like to review these two pages with you when you have 10 minutes. Changes are done in DEV, will move to test once I confirm a few things with you. Thank you, Chris.

**Comment by fazil-ey** [comment]
extra space after ( and missing 61 weeks 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUV3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69ee75999b838ee16233ab99c55ef1b9420d600f/Screenshot%202023-10-12%20at%204.40.03%20PM%20copy.png)

**Comment by Andrew-Vargas-bcgov** [comment]
added conditional show on these two pages.
@ayushdamani moved to test.

**Comment by ayushdamani** [comment]
Tested with Andrew at check-in:
1. Tested in the TEST environment.
2. The conditional logic added by Andrew is working great.
3. The UX errors which were posted by Fazil has been fixed.

Just one small recommendation - on the new page created by Chris, the blue box titled "Taking Standard Allowance with Extended leave?" does not have space after the box. So there is no space between the box and the form buttons. What do you think @fazil-ey ? 

Sorry I am not able to post screenshots for some reason.

**Comment by fazil-ey** [comment]
@ayushdamani, thanks for pointing it out. Me & Chris went through the form at fixed the spacing issues but due to the environment issues they haven't been moved to test yet

**Comment by fazil-ey** [comment]
- The tab needs have to be changed
- Remove the ? at the end of "Taking Standard Allowance with Extended leave?"
- Small change in the bullets for extended leave.> Rename the bullets from "Apply for..." to 
     - "Taking standard EI and standard allowance with extended leave"
     - "Taking extended EI and extended allowance with extended leave"
     - "Taking extended EI and standard allowance with extended leave"

**Comment by fazil-ey** [comment]
changes are done and verified in test
