### ISSUE TITLE
Mat/Pat - Check list before going live (from dev perspective)

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1380]
Learned from the previous live forms, I suggest a list of work to be done before Mat/Pat goes live.

- Review and refactoring the front-end form by devs
- Review and refactoring the workflow (we have a ticket for refactoring and simplifying the workflow)
- Requirements for reporting (BI team) pinpointed. Ensure only DGJ-specific data is sent for reporting along with the reference (like employeeId) that they can use to pull related data from other data sources
- QA: Make sure all the edge cases are identified.
- Improving Error handling on submission.
- Compatibility with the upgraded app

**Comment by fazil-ey** [comment]
Potentially add this to formal documentation on OneNote/Github/Ticket template on Zenhub
