### ISSUE TITLE
Mat/Pat - Spacing issues

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1385]
Fix the following spacing issues in the form - 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzQrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ff3ec8f9627a3c06d7d5cb4ea5e18ce6d8fe50e/Screenshot%202023-10-16%20at%2012.49.48%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlErQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a11441bc1218733b7d4843ccaa9c2b9527c25b4/Screenshot%202023-10-16%20at%2012.51.52%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUkrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39e3d9c3d46d4d40eee7f92022488f89dad65ff1/image.png)

**Comment by Stella-Archer** [comment]
need to book collaborative UX/Tech workshop to crunch through this

**Comment by jerry-ey** [comment]
@Andrew,  assigned this to you. Thanks.

**Comment by Stella-Archer** [comment]
TAB = Parent leave - leave type and Length TAB<img width="1454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2taQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c4cd7224b92dd6d3caf4b998c166d3327243acb/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
<img width="1369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEVaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb2f8aa1d881fa39bb5a33032657764e5f11315e/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
TAB = Parent Leave Start Date
<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHNaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f968b4bb018405c3b629c932558cef1b294ecec/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
<img width="976" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDhaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05d4918cf8aab96ec5e8fd8ca76459746ea304c2/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Nice this looks beautiful Andrew = ready to deploy

**Comment by MeghanStothers** [comment]
White spaces removed in this one: <img width="1765" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1FoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f8d61c1d044549f8d39e1ab77cce4549faedd66/image.png" alt="image.png" />

**Comment by MeghanStothers** [comment]
this one looks good to me - my eyes say this is a pass
<img width="1791" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2NoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0935fb7729490bf680436e1861a56672aa6ab356/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
@Andrew-Vargas-bcgov I'm still seeing no space here - but I swear it was fixed in TEST
<img width="1539" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGdoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b684bb9a6f36bcfffa714e67b8066822fc694877/image.png" alt="image.png" />

**Comment by MikePSA** [comment]
Tested in PROD, but looks to still need a space between the info and warning bubbles at the bottom <img width="995" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDhoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6dde1b203db1bbc8818be12a10f9a41ea964c4d6/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
FYI, I also checked the TEST, there is space.

<img width="1158" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUFoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a12a95e7e8494be1a0da01cc5332e3c3fa4ec5ea/CleanShot%202024-02-01%20at%2018.09.16%402x.png" alt="CleanShot 2024-02-01 at 18.09.16@2x.png" />

**Comment by jerry-ey** [comment]
FYI Andrew, I can see the space in "Edit Mode", but when in user mode, the space disappeared.

### Edit Mode
<img width="1334" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a7b9631b7dbb173869207a5c461cdc171256070/CleanShot%202024-02-01%20at%2018.19.44%402x.png" alt="CleanShot 2024-02-01 at 18.19.44@2x.png" />

### User Mode
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWdoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19afc548944e007cfa23d8dc99d5888c510a22a5/CleanShot%202024-02-01%20at%2018.21.24%402x.png" alt="CleanShot 2024-02-01 at 18.21.24@2x.png" />

**Comment by Andrew-Vargas-bcgov** [comment]
This is what it looks like for me:
<img width="1370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9oQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--668dfdf79cf50591e0158bb7deabd9eec79ce439/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Sweet Looks absolutely beautiful!! - closing tix
<img width="1390" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUloQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44e55680419ea3a5f010109e8199b2fde1d502bf/image.png" alt="image.png" />
