### ISSUE TITLE
Mat/Pat: Standardizing Date-related operations for Mat/Pat Forms

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1394]
As an employee or supervisor using Mat/Pat forms, I expect all date pickers for event dates to capture only **dates** (not date and time) to avoid timezone concerns.

Technical Details:
To achieve this, follow these steps for each date field in the form:
1. On Date Selection: Ensure date pickers store only the date (not date and time) in a date-only hidden field. You can achieve this by extracting the date part from the date UI field output, e.g., `data.matLeaveStartDate = value && value.split("T")[0]`.
2. On Date Loading: Load the date in the date field component using `value = moment(data.matLeaveStartDate)`.
3. On Date Validation: When validating date-only values, compare them by day to eliminate timezone issues. For example:
```js
const daysDifference = moment(data.matLeaveStartDate).diff(moment(), "days");
if (daysDifference > 1) {
  // matLeaveStartDate is after today
} else {
  // matLeaveStartDate is before today (in the past)
}
```

Also check #1448 if its fixed

**Comment by Stella-Archer** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXFMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c5e275ad5ae2b11ce8675d21ef977766dcc6ecc/image.png)

**Comment by Stella-Archer** [comment]
Error saying birthdate is future date when it is todays date https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-10-30%20at%204.35.13%20PM.mov?csf=1&web=1&e=7qS91G
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXlMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8442c8bbe527e46b946f7b8491c15c77479bf532/image.png)

**Comment by Andrew-Vargas-bcgov** [comment]
reviewing at dev standup and then moving to test if it's approved.

**Comment by ayushdamani** [comment]
Tested and confirmed updated! 
Moving to PO

**Comment by MeghanStothers** [comment]
We need to do a full end-to-end testing to confirm and then look at data to make sure everything is correct. For example, if someone starts the leave at 8 p.m.

**Comment by fazil-ey** [comment]
Tested post 5pm, could not replicate the start date error and was able to approve form with child birthdate as today
