### ISSUE TITLE
Mat/Pat - Explore - Submission order is completely wrong for supervisor in review and process tab

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1398]
Converting this Explore - We need to figure out how we can fix this for DJ. For Mat/Pat we can fix this by not have the emails sent out 4 weeks before leave ends & the review order will be based on created. If the fix is not easy, then do #1415 
____
 
Submission order in  the review and process tab shows past submissions a few minutes ago even though they are from days ago. 

In the screenshot the submission that is 19 minutes ago is the 2nd last submission.  

Photo - https://bcgov.sharepoint.com/:i:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screenshot%202023-10-23%20at%204.34.32%20PM.png?csf=1&web=1&e=TP3yjy

**AC**
- [x] Forms should be in the descending order of submission and should have the correct time of submission

**Comment by bhumin-fw** [comment]
@ayushdamani @fazil-ey 

To test out this ticket. Please add at least 2 forms on TEST environment on 2 consecutive dates and review on 3rd day to see their order.
I have added name as "Seq A" and "Seq B" on 14th Nov. You can use this same sequence or add any other name that can be easily identify as order.
on below action it will mark as new entry on review page
- On submission create
- On resubmit form
- When supervisor approve/Denise form
- When it hit 6 week before enddate (That's the place where it send an email about prior four weeks) 

Note: Old submitted form will have old workflow so they will continue refresh their form's created date on daily basis.

Let me know if you have any query on this ticket or to test this ticket.

**Comment by MeghanStothers** [comment]
Bhumin commented further about how to test this form: after submitting two forms on two different days, the first one should show "submitted a day ago" and the second one, should show "two days ago."

**Comment by ayushdamani** [comment]
Update: Submitted two forms

**Comment by ayushdamani** [comment]
Tested and confirmed working; thanks a ton again, Bhumin!

**Comment by fazil-ey** [comment]
2 forms submitted and were in order on the third day as well with the time correctly as 2 days ago. Looks good
