### ISSUE TITLE
Mat/Pat - Improve the Date Gap UX 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1414]
Currently the popup we get if there is a gap between maternity & parental leave there is only an OK button. It can be confusing to know that you have to submit the form. 

Instead of the popup we can add another section to the certify tab that needs to be checked off. This way there is an action for the applicant, the contact centre would also know the gap is intended.

> **Confirm Leave Dates** 
> We noticed there is a gap of [X] days between the end of your maternity leave [date] and the start of your parental leave [date]. Please review the dates to ensure they are correct. If incorrect, please edit the dates before submission.
> 
> - Maternity Leave starts on [date] and ends on [date]
> - Parental leave starts on [date] and ends on [date]
> - Parental leave allowance starts on [date] and ends on [date]
>
>  - [ ] The above dates are correct

**AC**
- [x] If applicant has a gap between maternity & parental leave start date - add a section "Confirm Leave Dates" in the Review page
- [x] If supervisor does not make any edits, they should be able to see the same section as applicant and should not be able to change the selection
- [x] If supervisor makes any edits, and there is still a gap, they should see a new "Confirm Leave Dates" section in the Review tab. The old values and confirmation by the applicant does not need to be shown.

**Comment by jerry-ey** [comment]
@fazil-ey 
If employee went to "Submitted Form" to edit the Mat/Pat form again, what behaviour should we follow?
AC 2 and 3 are for the supervisor, and I am wondering do we follow this flow for employee?

**Comment by MeghanStothers** [comment]
Jerry to deploy this later today

**Comment by jerry-ey** [comment]
please test :) Thanks!

**Comment by Andrew-Vargas-bcgov** [comment]
days/dates in the confirm box are not updating as you change the leave dates.
when selecting that you want to receive allowance during leave for both maternity and parental, the confirm dates box does not appear for the applicant.
Saw the box as a supervisor before changing dates and it was already checked.
@jerry-ey

**Comment by Stella-Archer** [comment]
Could we put the message in a yellow alert box?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOThUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af94aab0c1ec4ed31ad1312dbcfe409c3fe7d604/image.png)

**Comment by Stella-Archer** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0VUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af6931d0dcbb3174c611e64e893f3e54aca6c0f5/image.png)

**Comment by jerry-ey** [comment]
@Stella-Archer 
For sure, I will make the change. and it would be something like this:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--732076f43a11e2a4e5ac25a117931ac6a6abd7cf/CleanShot%202023-11-28%20at%2009.52.17%402x.png)

**Comment by Stella-Archer** [comment]
@jerry-ey brilliant that looks great jerry

**Comment by jerry-ey** [comment]
- add alert view
- fixed bugs
Please verify again, thanks!

**Comment by ayushdamani** [comment]
Confirmed updated; looking really good!

**Comment by MeghanStothers** [comment]
DJ team to test and add any comments about this one. Andrew to share screen with Jerry and have another look

**Comment by MeghanStothers** [comment]
To test this morning

**Comment by fazil-ey** [comment]
@jerry-ey  unable to check "The above dates are correct". the checkbox is frozen. Also when there is a validation error the background becomes white

<img width="1083" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjh0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4fbf1b1a672f7c78eebeedee81bc6f7880f35ab4/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
I  just fixed the frozen one on TEST. Will check the background color later.

**Comment by jerry-ey** [comment]
Please review again.
- Fixed the background color
- Fixed frozen select box

**Comment by Stella-Archer** [comment]
As a supervisor when I go back to an approved form and change the leave start date it does not Update it in the message
example I change leave date from 13th to 10th alert still say 13th
<img width="494" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnc2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1a7e779b8a94963aa4a50a9d99de308329adc42/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
Please check again.
- Fixed the data not being updated when date changed.

**Comment by Andrew-Vargas-bcgov** [comment]
works well. @fazil-ey do we want the checkbox to be cleared when the supervisor edits the dates?

**Comment by jerry-ey** [comment]
Fixed above comment. Please verify again.

> checkbox to be cleared when the supervisor edits the dates

**Comment by ayushdamani** [comment]
Looking great!

**Comment by fazil-ey** [comment]
closing this as main functionality works as expected, created 1519 for the UX improvement
