### ISSUE TITLE
Mat/Pat - Undo the 4 week email feature that is causing Review task list order to be messed up

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1415]
We need to Stop sending the email Sent to applicant's alternate email 6 weeks before end of leave (last date of maternity and/or parental leave). This is causing the application task to be updated everyday, messing the order of tasks on the Review and Process tab. 

**AC**
- [ ] Stop sending the email Sent to applicant's alternate email sent 6 weeks before end of leave (last date of maternity and/or parental leave). 
- [ ] The list of tasks in the review and process tab is in the right oder - Last created to first created

**Comment by bhumin-fw** [comment]
Added solution to keep this workflow in #1398 ticket, It is in QA.

**Comment by fazil-ey** [comment]
the submission order issue has been fixed, so no need to do this
