### ISSUE TITLE
Mat/Pat - Bug - Validation message UI for "Does your partner work for BC Public Service"

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1416]
"Does your partner work for BC Public Service" should not be a heading  in the erroe

Screenshot - https://bcgov.sharepoint.com/:i:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screenshot%202023-10-26%20at%202.23.06%20PM.png?csf=1&web=1&e=kEL5ib

**Comment by ayushdamani** [comment]
Error is now fixed. Moving to PO!

**Comment by fazil-ey** [comment]
looks good!
