### ISSUE TITLE
Mat/Pat - Ineligible workflow simplification

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1419]
For K & L, only show a message that this is not the form for them and point them to careers & MyHR website. 

**Design**
https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764568541168269&cot=14

**AC**
- [ ] If the appointment status is K or L, the above page should be shown.
- [ ] Applicant should not be able to submit the form 
- [ ] All existing tabs for ineligible workflow should be removed
- [ ] All existing emails for ineligible workflow should also not be sent 
- [ ] 

Note - need to have a close button - only if there is an easy way to do it

**Comment by iman-jamali-fw** [comment]
@fazil-ey @ayushdamani 
This is ready for your testing on TEST.

Please note that adding the "close" button was not straightforward to implement so didn't add that button (from design). There is a way to disable global navigational buttons ("Next" and "Previous") and replace them with custom buttons on each page, which will allow us to have greater control over the wizard navigational buttons but making that change at this point is a little disruptive 🙃.
