### ISSUE TITLE
Mat/Pat - Submission bugs

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1424]
(Individual tickets have been created) 

1. Submission could not be completed - applicant - we see a submission cannot be done ("S is not a a function") bug. This has happened before. 
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Submisison%20could%20not%20be%20completed%202023-10-30%20at%204.46.38%20PM.mov?csf=1&web=1&e=6giRkb

(Workaround - go back to draft and try to resubmit) 

3. Supervisor approval takes too much time - no confirmation message but status does change. Here is 4 mins of loading after approval, did not receive any confirmation message or CRM email, however the form was approved  -  (1425) https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Too%20long.mov?csf=1&web=1&e=iHPcWe
4. Refreshes back to before you begin page on approval/denial - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Refreshes%20back%202023-10-30%20at%204.59.15%20PM.mov?csf=1&web=1&e=ObJ7Wm
 Caching issue, will not happen if the superior is on a diff system. For testing, hard refresh/remove the URL and try again 
OR IT CAN HAPPPEN IF YOU TRY TO SUBMIT THE SAME FORM MULTIPLE TIES WITHOUT REFRESHING THE PAGE. WORKAROUND IS JUST REFRESH 

5. Error saying birthdate is future date when it is todays date (1394) - Screen Recording 2023-10-30 at 4.35.13 PM.mov
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-10-30%20at%204.35.13%20PM.mov?csf=1&web=1&e=7qS91G

6. Duplicate approval confirmation emails - https://bcgov.sharepoint.com/:i:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screenshot%202023-10-31%20at%209.47.08%20AM.png?csf=1&web=1&e=A7vKx8

7. Partner info not populating in the supervisor approval review page #1432
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXFNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f7e2c201cf833f5b03bdf81723351c9cd4b8bc3/image.png)

8. Partner info screen is not going away when selecting just I will be taking parental leave, after selecting both partner and i will be taking parental leave (#1430)
9. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnVMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49a3e5eda7e85683f238a53c42c1e5af5a8615be/image.png)
10. Review page is not syncing correctly (recordingn available)

**Comment by Stella-Archer** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmVMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e4c5ae9525a7e8263fbfb4f8c72d220dd4fedfc/image.png)

**Comment by fazil-ey** [comment]
Ticket was split into individual tickets for the bugs. Can be closed
