### ISSUE TITLE
Mat/Pat - Review page syncing errors 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1426]
We noticed that the parental leave start date and parental leave length does not match in the video below. This also caused validation errors because the allowance dates were not within parental leave dates in the review page. 

Video - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Review%20Syncing%20issues.mov?csf=1&web=1&e=MaBT65

**AC**
- [x] All fields in the the review page should sync with the fields in the actual form

**Comment by bhumin-fw** [comment]
@ayushdamani @fazil-ey this change is ready to test on TEST env. let me know if you face any other issue while testing this one.

**Comment by ayushdamani** [comment]
Not able to replicate the error anymore, thanks Bhumin!

**Comment by fazil-ey** [comment]
Tested a bunch of scenarios changing data in both the review page and the tabs. Did not see any syncing errors
