### ISSUE TITLE
Mat/Pat - Make the loader load as soon as you hit the approve button for supervisor

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1427]
Make the loader load as soon as you hit the validate submission button for supervisor. This has been implemented for telework and should be a very easy change

**AC**
- [ ] Loader should load as soon as supervisor hits the validate submission button
- [ ] Add a message to loader saying "Submitting...this can take a few minutes"

**Comment by jerry-ey** [comment]
Discussed with DEV team, assigned this one to myself.

**Comment by jerry-ey** [comment]
Discussed with DEV team, assigned this one to myself.

**Comment by jerry-ey** [comment]
Please test, thanks!

**Comment by ayushdamani** [comment]
I will request the team at check-in to test this, since I am not able to approve my own submission!

**Comment by ayushdamani** [comment]
The team while Bug bash tried testing this out, but the message did not appear right away; only the dancing balls appeared.
Can you please look into this Jerry?

**Comment by Stella-Archer** [comment]
the message did come on 1st which is great BUT the dance balls replaced in for a pretty long time before the validation message came up.
Could we keep the message up UNTIL the validati0on page appears, as we would not want user to close the page before the process is complete
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGNQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08bc61d242643ba111b2e7592108ff86a54a3d13/image.png)

**Comment by jerry-ey** [comment]
Ready to test, thanks.

**Comment by ayushdamani** [comment]
The loading message appeared as soon as I hit 'validate submission'. Thanks Jerry!

**Comment by fazil-ey** [comment]
I see the loader "Submitting...this can take a few minutes" throughout, did not see dancing balls. Looks good
