### ISSUE TITLE
Mat/Pat - Bug - length of leave should not be 0 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1429]
We should not allow maternity & parental leave length to be 0. 
Decimal values i.e 16.5 should not be allowed
negative values should not be allowed 

**AC**
- [x] Maternity leave length should be a whole number from 1 to 17
- [x] Parental standard leave should be a whole number from 1 to 35 if taking full 17 week mat leave or 37
- [x] Parental extended leave should be a whole number from 1 to 63 if taking full 61 week mat leave or 63

**Comment by ayushdamani** [comment]
Tested all three points; confirmed working!
Moving to PO!
