### ISSUE TITLE
Mat/Pat - Partner info tab does not go away 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1430]
Partner info screen is not going away when selecting just "Only I will be taking parental leave", after selecting "both partner and i will be taking parental leave"

**_Steps to reproduce -_** 
1. Apply for parental leave, select "both my partner and I will be taking parental leave" and select Yes to "Does your partner work for BC Public Service?"
2. Go back and Select "Yes, however, only I will be taking parental leave"
3. Notice "Parental leave - Partner's information" does not go away 

**_AC_**
- [x] Partner info tab should go away if "Yes, however, only I will be taking parental leave" is selected or No is selected for "Does your partner work for BC Public Service is selected"

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnVMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49a3e5eda7e85683f238a53c42c1e5af5a8615be/image.png

**Comment by ayushdamani** [comment]
Tested in TEST; could not replicate the error.
Thank you so much, Bhumin!

**Comment by fazil-ey** [comment]
So I filled the partner info and then went went back and changed it to only I will be taking leave. The tab goes away, but in the review page the partner info section remains.

Steps to reproduce -
1. fill the partner info and select Get Info
2. go back to "Are you taking parental leave" and select "Yes, however, only I will be taking parental leave"
3. Notice in Review page, the part info section remains

video - https://digital-journeys-test.apps.silver.devops.gov.bc.ca/form/642da678c960c54ed1c7015f

**Comment by bhumin-fw** [comment]
@fazil-ey 
I did add script to test one detail on test this morning that cause validation error, I have to reverted it now.
It should word as expected now to hide "partner information tab and section review page".
check from my end and it is working fine, able to hide tab + section from review page.

**Comment by fazil-ey** [comment]
looks good!
