### ISSUE TITLE
Tool optimization: Document service fail due to error and resource limit reach

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1431]
For issue in document service can be rise due to memory limit.

From the service log we have note dow few issue that we can take a look

**Error 1:** (service restart and work as it is when memory surge reduce)
[31;21m2023-10-30 16:56:05,812 - app - ERROR - Exception on /form/62c8796e532635532114a70b/submission/653fdfad597f1b02cdbf76a4/export/pdf [GET] (app.py:1449)
...
raise exception_class(message, screen, stack-trace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

**Error 2:** Fix when restart pod
[31;21m2023-10-30 16:12:53,004 - app - ERROR - Exception on /form/62c8796e532635532114a70b/submission/653fd5f2597f1b02cdbf34a8/export/pdf [GET] (app.py:1449)
...
raise exception_class(message, screen, stack trace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=110.0.5481.100)

About the resources
We are able to capture live crash on Monday morning, but if we have detail matrix we can review that and see how memory and CPU usage look like throughout all days. In below image we can see it reach the memory limit of 3GB and hovering around 2 core cpu usage.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a835ece72fcd8ca30f11ceafac948e6c2ebaaac/PROD-DOCUMENT-POD-MATRICS.png)

**Comment by fazil-ey** [comment]
this is also resolved! we can close this. Resolved as a part of the upgrade
