### ISSUE TITLE
Mat/Pat - Partner info in supervisor approval is  not populating

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1432]
Partner info not populating in the supervisor approval review page even though the fields were filled in the applicant form. And it was showing a validation error that the fields are not filled when the supervisor tried to submit the form. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXFNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f7e2c201cf833f5b03bdf81723351c9cd4b8bc3/image.png)

**AC**
- [ ] Partner info should populate for supervisor and supervisor should be able to approve the form without the validation error that the field is mandatory

**Comment by Stella-Archer** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHlhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5868b55285f4d1104c8c3d0ce46a4fc6bb431418/image.png)

**Comment by ayushdamani** [comment]
Can confirm that the error is now fixed! I was not able to reproduce the error.

**Comment by fazil-ey** [comment]
looks good
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2506fe3c91c6d5a374e26cb3fadfa577ed88146a/image.png)
