### ISSUE TITLE
Mat/Pat - Deferred leave tab is not going away 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1435]
Deferred allowance dates tab  is not going away when selecting will claim allowance/not claim allowance, after selecting will defer allowance. Also the leave allowance dates tab is not showing
Steps to reproduce -

1. Apply for parental leave, select deferred my allowance and then select will claim allowance
2. Deferred allowance dates tab does not go away

AC
- [ ] Deferred allowance dates tab and deferred allowance section in review page review section should go away  when selecting will claim allowance/not claim allowance, after selecting will defer allowance

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWVvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e41c3cc289b35d19340cf171c1f9051693770601/image.png)

**Comment by fazil-ey** [comment]
FYI i wasn't able to replicate this issue.

**Comment by jerry-ey** [comment]
i wasn't able to replicate this issue either.

**Comment by ayushdamani** [comment]
Not able to replicate the error as well; moving to PO :)

**Comment by fazil-ey** [comment]
works well, no bug
