### ISSUE TITLE
Mat/Pat - Alert about partner does not go away when selecting only I will be taking parental leave

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1437]
Alert about partner does not go away for "What parental leave option are you taking?",  when selecting only I will be taking parental leave after selecting yes for "Does your partner work for BC Public Service?"

Steps to reproduce
1. Go to mat/pat and go to parental leave tabs. For  "Are you taking parental leave?", first select "Yes, both my partner and I will be taking parental leave" and then "Yes" for "Does your partner work for BC Public Service?"
2. Then select "Yes, however, only I will be taking parental leave"
3. Notice in  "Parental leave - Leave type and length of leave" the partner alert "If your partner works for BC Public Service, they must also choose the same leave type if they are taking parental leave." is still there even though only "Yes, however, only I will be taking parental leave" is selected
4. Go back to " "Are you taking parental leave?" Reselect  " "Yes, both my partner and I will be taking parental leave" " and notice "Yes" is pre-selected on ""Does your partner work for BC Public Service?"

video
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-11-08%20at%202.28.24%20PM%20(1).mov?csf=1&web=1&e=pHWMIZ

**AC**
- [ ] The alert ""If your partner works for BC Public Service, they must also choose the same leave type if they are taking parental leave." should be on  "Parental leave - Leave type and length of leave" only if taking parental leave with a partner and the partner works in BC government too

**Comment by Stella-Archer** [comment]
@bhumin-fw  could you review to see if this is still and issue?

**Comment by jerry-ey** [comment]
Bhumin checked this and the issue still remains. Working on this.

**Comment by jerry-ey** [comment]
Please test, thanks

**Comment by Stella-Archer** [comment]
This works perfect Thanks @jerry-ey
