### ISSUE TITLE
Mat/Pat - Change Instruction in Before you begin

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1442]
In Before you begin tab change 

"After submission of this form, you will receive an email with instructions on what you need to do after you start your leave"

to

"After you submit, your supervisor will receive your form from approval. After approval, you will receive a confirmation email with instructions on what you need to do after you start your leave"

"We recommend you review the latest information in your collective agreement and on the Maternity and Parental employment insurance benefits page and Careers & MyHR"

**Comment by chriscaldwell-psa** [comment]
Changes have been made in the bulleted section on the Before you begin tab.  <img width="1754" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXhCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a092d0b75629d8f0af5f49a9ea73eb2b3c03c6eb/image.png" alt="image.png" />

**Comment by chriscaldwell-psa** [comment]
Note: Changes were made in prod env.

**Comment by ayushdamani** [comment]
Confirmed updated!

**Comment by fazil-ey** [comment]
Hey @chriscaldwell-psa sorry the ticket wasnt clear.

Can you add this "We recommend you review the latest information in your collective agreement and on the Maternity and Parental employment insurance benefits page and Careers & MyHR"

 to the last bullet - 

"Everyone's circumstances are unique. In the event that there is a discrepancy between this form and the Government of Canada Employment Insurance Act, BC Employment Standards Act, or any applicable collective agreement or term and condition of employment, the relevant Acts or terms of employment or agreement shall prevail."



 should be a separate point

**Comment by chriscaldwell-psa** [comment]
@fazil-ey  - changes made. Back to you boss. C.

**Comment by chriscaldwell-psa** [comment]
In Dev env.

**Comment by fazil-ey** [comment]
looks good
