### ISSUE TITLE
Mat/Pat: Content edits to email confirmation message to form submitter

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1452]
As a person requesting leave, I would like an accurate and clear confirmation message that my submission has been approved.

**Comment by MeghanStothers** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkxhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0bc3b77e4e1b43007c912d3d7287c74dce4a0c99/image.png)

**Comment by fazil-ey** [comment]
looks good. the periods at the end of sentences were missed. will create a new ticket
