### ISSUE TITLE
Mat/Pat - Fix the position and rename Submit buttons

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1453]
**AC**

- [ ] Fix the position of the submit button when applicant submits/resubmits 
- [ ] Fix the position of the "Validate Submission" button when supervisor approves
- [ ] Rename "Validate Submission" to "Submit"

Note - Reduce the gap between the Submit and Previous button, and make submit the same size as previous button. Goal is to make it look good

Current positions that need to be fixed - 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3JoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39b8c5b2037c979e66872b24c6a40b40222e5a1c/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL25oQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26fcb775cc6814f6d88831ad9012938dc1b3cf10/image.png)

**Comment by fazil-ey** [comment]
Dont see any changes in test 

"<img width="918" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2lwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab9fc47a4eff2827c82e0346db6d81708f919e73/image.png" alt="image.png" />
"

**Comment by ayushdamani** [comment]
My apologies. Got confused with another button.
Moving back to in-progress

**Comment by jerry-ey** [comment]
@fazil-ey not sure what you mean no change?
I aligned the Previous button to Submit button. 
<img width="1270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee69a960e306c628630082fddc14d8517aa3752a/CleanShot%202024-01-08%20at%2011.08.49%402x.png" alt="CleanShot 2024-01-08 at 11.08.49@2x.png" />

**Comment by jerry-ey** [comment]
Fixed the following, plz check again.
- Reduce the gap between Submit and Previous
- Make Submit button size same as "Previous" button.

**Comment by ayushdamani** [comment]
The sizes of both the buttons is the same now!
The gap has been reduced as well

Over to you, Fazil!

**Comment by fazil-ey** [comment]
Buttons aligned, resized, and gap reduced for both applicant & supervisor. Supervisor submit name changed. looks good

<img width="750" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzY1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f44bfd45c6f88617048289d364ad1c7a92bd3fde/image.png" alt="image.png" />
<img width="556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0c1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a1875f3f1a888d4ea53eba05a4198da2e22ad04/Screenshot%202024-01-11%20at%202.51.08%20AM.png" alt="Screenshot 2024-01-11 at 2.51.08 AM.png" />
