### ISSUE TITLE
Mat/Pat - Leave length - Add days

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1454]
We need to allow applicants to be able to take partial weeks off - i.e 16 weeks and 5 days. For this we need to add days field in the length of leave tab for both parental and maternity leave. 

**_AC_**
- [x] Add days field to maternity leave - length of leave under weeks field
      -  Should be a whole number between 0-6
      -  Should be optional, and if not filled should be defaulted to 0
      -  Maternity leave cannot be more than less than 1 day and less than 17 weeks. 
      -  There should a "Weeks" label for weeks field and "Days" label for days field
      
- [x] Add days field to Parental leave - Leave type and length of leave under weeks field
      -  Should be a whole number between 0-6
      -  Should be optional, and if not filled should be defaulted to 0
      -  Standard parental leave cannot be less than 1 day and more than 37 weeks or 35 weeks if taking the full 17 maternity leave (including the other logic around length described in #876)
      -  Extended parental leave cannot be less than 1 day and more than 63 weeks or 61 weeks if taking the full 17 maternity leave (including the other logic around length described in #876)
      -  There should a "Weeks" label for weeks field and "Days" label for days field
 
- [x] Add the days field in Review page in both Maternity and Parental leave sections, that follows the same validation logic
- [x] Supervisor should be able to see the days field as well and edit it following the logic in  #1356 as part of changing the 
- [x] CRM thread should include the days field as well after the form is approved

**Comment by ayushdamani** [comment]
Tested all criteria and logic; confirmed working!

**Comment by fazil-ey** [comment]
if I take 16 week 6 days of mat leave, i should be able to take 61 weeks 1 day of extended parental leave for 78 weeks. However the validation is shows 62 weeks


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkFtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b94419ca95798bec87abc94c4b93d26194be856/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkltQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f61d2dd5de6cdcb84f4e7cd439cac2a6a907f8db/image.png)

**Comment by fazil-ey** [comment]
BUG - We noticed in the testing that the CRM thread did not have the days for the length of leave in it 
@Andrew-Vargas-bcgov

**Comment by fazil-ey** [comment]
BUG @Andrew-Vargas-bcgov  
Even though we cleared the days field, we still see the old value in the submitted form and also the supervisor tab

https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-12-04%20at%209.50.37%20AM.mov?csf=1&web=1&e=b5x1Oj

**Comment by fazil-ey** [comment]
BUG - @Andrew-Vargas-bcgov we noticed in prod when the supervisor was approving when we noticed that when we put 63 as length of leave for parental leave it still asked us to enter something in days even though days is an optional field
<img width="1366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0k2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d7a6c60422b62d71a8197449fec484f7cfca945/MicrosoftTeams-image%20%288%29.png" alt="MicrosoftTeams-image (8).png" />

**Comment by ayushdamani** [comment]
No errors while testing this, thank you Andrew!

**Comment by fazil-ey** [comment]
BUGS - 
@Andrew-Vargas-bcgov Days still not populating in CRM ticket

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov 

New BUG - noticed when i remove the days in review page and submit the form it does save the change. When you see the form again the old value is still there
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-12-13%20at%2012.04.08%20PM.mov?csf=1&web=1&e=rAGyob

**Comment by fazil-ey** [comment]
New BUG - Review and original tab are off sync <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--682eb9b38e5647ec5dc7edb462db0a9f84fddd3a/Screenshot%202023-12-13%20at%203.27.22%20PM.png" alt="Screenshot 2023-12-13 at 3.27.22 PM.png" />
<img width="864" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXhjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1242d0b86eb793ee94ba5834d49c7b000a6faffd/Screenshot%202023-12-13%20at%203.27.14%20PM.png" alt="Screenshot 2023-12-13 at 3.27.14 PM.png" />

**Comment by Andrew-Vargas-bcgov** [comment]
changed Days from number to text field. Problems seem to have vanished. It is possible that somewhere else in the form might be impacted by this change, but I couldn't find anything immediately.

**Comment by fazil-ey** [comment]
looks good
