### ISSUE TITLE
Mat/Pat - Email - Add instructions for supervisors about updating the form

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1455]
Add instructions for supervisor on how they can go in and update the form on behalf of the applicant  to the email that is sent to inform that there is a form waiting for approval. Also add to the email sent to applicants on approval. 

In supevisor email
"As the supervisor you can make limited changes to the form on behalf of the employee after approval. You can update the leave start date, length of leave and parental leave allowance dates. You can access the form on Review and Process tab in [Digital Journeys](production DJ link)"

In applicant approval emails
"Your supervisor can make limited changes to your form on your behalf. They can update your leave start date, length of leave and parental leave allowance dates. They can access your form in the Review and Process tab in [Digital Journeys](production DJ link)"

**Comment by fazil-ey** [comment]
Changes done, to be tested

**Comment by MeghanStothers** [comment]
Ready to test

**Comment by ayushdamani** [comment]
Emails are updated! Moving to PO

**Comment by fazil-ey** [comment]
Small grammatical error needs to be fixed
"They can access your form **_on_** in the Review and Process tab in Digital Journeys"
