### ISSUE TITLE
Mat/Pat - Remove text on Review and Process page

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1457]
**_AC_**
- [ ] The text "maternity-parental-and-pre-placement-adoption" is removed

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUxoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa3caf7188ad2d25d2f29488d0723365f5ea60fa/MicrosoftTeams-image%20%281%29.png)

**Comment by jerry-ey** [comment]
Got final confirmation from the team, we will remove workflow name from all forms.

**Comment by MeghanStothers** [comment]
Jerry to push to test

**Comment by jerry-ey** [comment]
@ayushdamani @fazil-ey Please verify this ticket. (Workflow name is completely removed from all forms) Thanks.

**Comment by MeghanStothers** [comment]
@jerry-ey Thank you! @chriscaldwell-psa Can you test this one today?

**Comment by chriscaldwell-psa** [comment]
This test is a pass. Looks good. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkVOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0b0b475adf4e29171ea6c274d0f275e0aa17cd9/image.png)

**Comment by MeghanStothers** [comment]
Awesome! Thank you we're looking now

**Comment by Stella-Archer** [comment]
Sweet looks great [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2tPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d85028704df9d370e7f5135d17dfb363ab345caa/image.png)

PO Approved & Closed :)
