### ISSUE TITLE
TELEWORK: Text updates to TEST version

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1458]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
“As a form owner I want to tweak some text on the telework form we have been working on in TEST so I can release it before new changes to policy are finalized.” 

**Tasks**
Remove the crossed out sentence from the wording in Section 2.
 
**2. Headquarters Location**
The official office location where you work (or would work) when not teleworking and your headquarters location for business travel.
 
Your supervisor must approve your headquarters location. All travel costs will be calculated from this location. ~~If your headquarters location is outside of your home ministry, approval is required by the hosting ministry’s Facilities Management Unit.~~
 

**Acceptance Criteria**
**_"If your headquarters location is outside of your home ministry, approval is required by the hosting ministry’s Facilities Management Unit."_** is no longer in the content of Section 2

**Comment by Abuchana** [comment]
Need to sync up with the ODS team
Test the new DMN workflow in PROD

**Comment by Stella-Archer** [comment]
@chriscaldwell-psa could you do this text update so we can look at push this out next Monday?

**Comment by chriscaldwell-psa** [comment]
@Stella-Archer  - All changes finished in dev, just waiting for devs to inform me if its Ok that I upload to  test.

**Comment by chriscaldwell-psa** [comment]
Looks good. Done. [Uploading... image.png]

**Comment by Stella-Archer** [comment]
Opps client had more text changes > nix the line re “all travel costs will be calculated from this location”

**Comment by chriscaldwell-psa** [comment]
@Stella-Archer  - Changes have been made. :)

**Comment by Stella-Archer** [comment]
Thanks @chriscaldwell-psa Looks great - I've run the by Sean G and have an a-ok form them as well

**Comment by Stella-Archer** [comment]
Done & LIVE - closing tix
<img width="1379" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFFoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5e563103bc068b161dba6d16c376b7c89a01b65/image.png" alt="image.png" />
