### ISSUE TITLE
Telework: Text boxes do NOT expand to accommodate all text

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1465]
**User Story**

“As a Telework requestor, I want add more than a single line of text to the address text box in the new 'headquarters' section so I can get can see, and have a record of the complete address in the the PDF.” 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzMrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cd626d8fce987aadfa90ebf995676cc40fbd33a/image.png)

**Tasks**
Currently the address field can hold 250 character but only about 120 characters are can be seen.
- [ ] fix text box so it expands to display all characters entered

**Acceptance Criteria**
255 characters can bee seen in text field when entered

**Comment by Stella-Archer** [comment]
Use text AREA instead of TEXT BOX

**Comment by chriscaldwell-psa** [comment]
Character limit has been increased to 950 characters from 250.  Ready to test @ayushdamani

**Comment by ayushdamani** [comment]
Tested in TEST environment; confirmed updated with the new component!

**Comment by Stella-Archer** [comment]
expands away and looks great in both generated and downloaded PDF however I'm a bit concerned the employer character limit is super small (compared to employee)
<img width="1232" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3JKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59d75078fd7de50e679ae022772c5b409c800102/image.png" alt="image.png" />

<img width="1441" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f767d59994ec90afb34e8b1ba13735d9a531b0b2/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
@chriscaldwell-psa  could you take the character limit off the employee comment box?

**Comment by chriscaldwell-psa** [comment]
Changes were made in dev env, will save to test env at noon today. C.

**Comment by ayushdamani** [comment]
Confirmed updated! Moving to PO

**Comment by Stella-Archer** [comment]
Thanks every one this looks terrific Closing ticket 
I will check with Sean/Jenn and Meghan to confirm Telework can be join Mondays Deployment

**Comment by Stella-Archer** [comment]
Sweet many many comment printing in PDF and sending as well - closing
<img width="1216" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2toQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--632a32fbe44dac63d9e6249cc0cf00a88acbb4ad/image.png" alt="image.png" />
