### ISSUE TITLE
Security Review: Selenium

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1472]
Exploring automated testing for Telework

**Comment by Stella-Archer** [comment]
waiting for selenium security review & approval

**Comment by Stella-Archer** [comment]
@MikePSA is reviewing and fabbing up and estimate

**Comment by Andrew-Vargas-bcgov** [comment]
This is with Igor for review.

**Comment by MeghanStothers** [comment]
I have re-requested a security review of this tool
