### ISSUE TITLE
MAT/PAR: Employee Email Message: Wording Change

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1477]
As an employee submitting my mat/par application, I need clear instructions about confirmation of my application and any actions I need to take.

A/C: 

1) After your supervisor reviews your submission, you will receive an email with a pdf of your submission

**Comment by MeghanStothers** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUFIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73ee253ce7edd614684ef295202c26a70efedc65/MicrosoftTeams-image%20%286%29.png)

**Comment by fazil-ey** [comment]
has been fixed
