### ISSUE TITLE
Mat/Pat: Pre-Production Check and confirm end points in the CRM production environment

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1479]
**User Story**
“As a developer I want to make sure I have the correct endpoints for the CRM production environment so I can be sure the transition to the PROD is smooth as pssible.” 

**Tasks**
Check in with Nancy or TELUS technical people to confirm

**Acceptance Criteria**
production deployment ready

**Comment by iman-jamali-fw** [comment]
This was tested during depoyment and already exist on PROD. @bhumin-fw Can you confirm if this is ready to close?

**Comment by MeghanStothers** [comment]
Our team confirmed this is done
