### ISSUE TITLE
Mat/Pat: Loading message needs to run until success message is complete

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1481]
**User Story**
“As a user I want to be sure my Mat/Pat form has been completely processed so I can be confident it complete and can close out of the window.” 

**Tasks**
currently the loader works great but ends long before the success message pops up
could we program the loader to continue until the processing is done and the success message is loaded
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6ab90dfe95e030d5000033035faebc4508c97d3/image.png)

**Acceptance Criteria**
user sees loader until success message loads

**Comment by fazil-ey** [comment]
this was implemented already
