### ISSUE TITLE
Tool: Error handling on initial submission

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1484]
**Issue**
Upon initial form submission in the tool, certain error cases are not adequately addressed, affecting all forms. Two scenarios arise:
1. If Camunda is offline and a user submits a new form:
   - User receives an error: "Submission Failed" (screenshot 1)
   - A new submission appears under "Submitted Forms" with a default status of "New" (screenshot 2)
2. If Camunda is online but an issue occurs in the workflow:
   - User sees a success message on the website (screenshot 3)
   - A new submission is created under "Submitted Forms" with a status of "null" (screenshot 4)
   - API and Camunda logs are also included in screenshots 5 and 6.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzBXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90ccf85795f10aa00fc4cd65a9db73e231707e9d/Screenshot%202023-11-28%20at%207.00.30%E2%80%AFPM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1e885f7d69c9dae8e810d00c5b2e66daccef8d3/Screenshot%202023-11-28%20at%207.00.40%E2%80%AFPM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGtXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b447409697e572909456bc99950ed5ffb74e099/Screenshot%202023-11-28%20at%207.15.18%E2%80%AFPM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG9XQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1d58eb083de9fcd07c74b7973c041a4ca4ccd02/Screenshot%202023-11-28%20at%207.15.36%E2%80%AFPM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDBXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9115eea73f3e06b41fe71728d2d73328655c0e10/Screenshot%202023-11-28%20at%207.15.43%E2%80%AFPM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDhXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5aa0b257a9b1347cb43f23c6c6658e1e775b52b/Screenshot%202023-11-28%20at%207.15.58%E2%80%AFPM.png)

**Comment by iman-jamali-fw** [comment]
Progress report:
Exploration for error 2 is complete. Code responsible for capturing the error was identified.

Next:
- Throw error when Camunda workflow is broken. This will cover error 2.
- Recover from error. This means submission in Formio and application in API should be deleted and the draft (resubmitted) should be undelete and kept for user so they don't lose data.
- Do the same thing for error 1. When Camunda is down

**Comment by iman-jamali-fw** [comment]
Progress report:
Throw error and show erro message on the website when Camunda workflow is broken. This will cover error 2.

Next:
Recover from error, other words, making the initial submission transactional (either all go or nothing). This means submission in Formio and application in API should be deleted (when workflow is broken) and the draft (resubmitted draft) should be undelete and kept for user so they don't lose data.
Do the same thing for error 1. When Camunda is down

**Comment by iman-jamali-fw** [comment]
@ayushdamani 
This is ready for testing on TEST. I think it's easiest to set a time and test it together. It would need someone to inentilally break the workflow to test out handing the error cases. Please ping me when you're ready for the test.

**Comment by MeghanStothers** [comment]
Iman and Ayush to test today

**Comment by ayushdamani** [comment]
Tested with Iman in TEST.
Number 2 worked perfectly. Number 1 needs some more work.
Bringing this back to in-progress.

**Comment by ayushdamani** [comment]
Tested with Iman in TEST environment.
The second acceptance criteria is working as accepted.
Moving to PO :)
