### ISSUE TITLE
Mat/Pat: PROD deployment initial testing category and Assignment

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1487]
**User Story**
“As a QA tester of the initial deployment to the CRM PROD environment I want tickets to go into the testing catgory and assigned to a BA so I can get be sure our tests are not counted in the CRM data and tickets don't get lost in a large group assignment category like HRSS which gets hundreds of tickets a day.” 

**Tasks**
- [x] Send DGJ ticket to the "Training Test Tickets" Category
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEFoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0b027e8f55990d42a25c292938a97c1c347f194/image.png)
- [x] Assign Tickets to "Augusteen Myeong"
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFFoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c50b1cc83bbd3e3135248ef940a20965d938fba/image.png)

**Acceptance Criteria**
test tickets in the PROD environment go to test category and team is able to find them an test they are working correctly

**Comment by MeghanStothers** [comment]
PO approved - tested with Mike
