### ISSUE TITLE
SL review: Stop forms from getting deleted

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1488]
In SL review submission workflow there is a fix date **6th December 2023** set to delete application and submission.
Based on final update from the form owner Jodi. We should keep all forms in DJ. To do that new changes needs to deploy that sto SL forms getting delete via workflow.

Task
- [x] Add condition that skip SL submission getting deleted.

**Comment by MeghanStothers** [comment]
Will be included with mat/par deployment

**Comment by bhumin-fw** [comment]
Tested code and it is working fine. Delete function skip all SL submissions. If form name is "Senior Leadership Review Form" then it will not delete application/submission from the digital journey database.

**Comment by MeghanStothers** [comment]
Bhumin noted this ticket can be closed
