### ISSUE TITLE
SL Review: JANUARY 12 2024 - Delete all remaining forms from Digital Journeys

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1490]
**User Story**
“As a form owner I want to delete all submitted and validated forms from the Digital Journeys system so I can be compliant with records/reention schedules>.” 

**Tasks**
on January 12, 2024
- [ ] Delete ALL SLR submitted for validation forms (But not validated forms) YES
- [ ] Delete all validated forms form Digital Journeys System

**Acceptance Criteria**
There is no longer and SL Review submissions of any sort in the Digital Journeys System

**Comment by Stella-Archer** [comment]
This looks good to me I can "see' the form in the 'forms' tab but when I search for submissions nothing shows up :)
I will double check with Jodie
<img width="1012" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHJKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1156c2225d5ed170fc360cfe3b80d19f1c593357/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
@Stella-Archer  Please let me know if I need to also delete the form in the "form" tab?

**Comment by Stella-Archer** [comment]
@jerry-ey Jodi tested and looked good to her too - we do NOT need to delete the form itself as only admins/DEVs can see it and they will probably do it again next year
Closing the Tix :)
PO Approved
