### ISSUE TITLE
Bug: Mat/Par: Values do not disappear when changing leave types

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1492]
As an employee, I would like to change my leave type from standard to extended (on the summary page) and I would like to have all values erased (in the "dates" and "days" fields) when I resubmit with new dates and days.

video - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-12-18%20at%2012.44.06%20PM.mov?csf=1&web=1&e=d7XjaD

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e0e0d0636017bc8be5b3f919fb23760701581e6/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
this is still a bug, video attached. The days field should also clear like the weeks field

**Comment by fazil-ey** [comment]
Works, but it shows a validation error when switching. It is fine except the first time it only shows it for days field, not both days and weeks which can be confusing. 
video - 
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202024-01-08%20at%2011.26.32%20AM.mov?csf=1&web=1&e=WAmN1N

**Comment by fazil-ey** [comment]
created #1547 nice to have ticket for the validation error. Cloisng this
