### ISSUE TITLE
Mat/Par - Post deployment testing for Dec 4 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1493]
**Testing Scenarios Mat/Pat -**  (Mike, Andrew, Stella, Meghan, Fazil) 
 1. Submit a form with maternity & standard parental leave. Approve and check if the CRM ticket is create and has correct values. Check Emails
 2. Submit just a extended parental leave with a partner. Approve and check CRM. Check Emails
 3. Edit the form in 1 and resubmit. Supervisor reapproves. Check CRM. Check Emails
 4. Supervisor edits the form in 2 and re approves. Check CRM. Check Emails
 5. Test if Ayush is able to do what he is not able to do in test 

**Testing Scenarios Telework -**  (Stella & Meghan)
1. Test 2 days and 3 days scenario. Submit form as applicant and approve as supervisor. 
    - Ensure employees dont get pdf. Supervisors should get pdf

**Testing Scenarios Bullying -**  (Stella) 
1. Make sure its there, input values  but dont submit the form
2. just a note to be sent to Don, no testing required

**Testing Scenarios SL -**  (Stella)
1. Ensure the right date is in production in the delete script 
2. Confirming Stella can see the form in producition

**Comment by Stella-Archer** [comment]
Given Dev's can NOT point the to the end points to 

Category = Training Test tickets
and Assign = Augusteen Myeong

We should NOT test Mat/Pat tonight as all our submission will end up assigned to HRSS, (and Ronda will be super upset) they would also count and skewer the data/measurements if our testing in PROD goes to anything other that the Training TEST ticket category

**Comment by Stella-Archer** [comment]
yay thanks everyone this worked great!!
<img width="959" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGd2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2039db1d7f1c11c08a40d9daad925068ee5dc3f/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Scenario 1 & 3 came through correctly had correct emails

**Comment by Stella-Archer** [comment]
extended leave ask had a lot of issues with leave dates and I could not Process # 2 scenario
<img width="841" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUl2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ff5aa76b612ca9d54e7006a99f90293f49f7ffe/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
1. Full Time/ Part time is not populating in employee info
<img width="1150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0l2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea834624c286b71d45a84f3e205fdaed8aedbc04/MicrosoftTeams-image%20%284%29.png" alt="MicrosoftTeams-image (4).png" />

**Comment by Stella-Archer** [comment]
telework testing looks good new HQ piece has NOT been made public YET :)

**Comment by Stella-Archer** [comment]
I can still see all the Senior leader submissions in the PROD environment

**Comment by Stella-Archer** [comment]
1.0 also looks good the boxes expanded PDF printed fine, pre populated with correct info
will drop Don Smallwood a heads up note

**Comment by MeghanStothers** [comment]
Basic testing done and we will continue drafting comprehensive testing scripts over the coming weeks. Team to open new tickets with the bugs found and noted in the thread above.

**Comment by MikePSA** [comment]
test

**Comment by Stella-Archer** [comment]
On Dec 06 I opened ticket ID 231206-000197
DGJ Ayush Damani
Application ID# 74841
and closed it
check again in 7 days to see if we can retrieve
