### ISSUE TITLE
Mat/Pat -UX - add optional with days

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1495]
**AC**
- [x] Add "optional" for number of days in both maternity and parental leaves

**Comment by MikePSA** [comment]
<img width="1387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFV2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48f9f0e7c33cbb0658d6c4195d4430b02f42bc00/image.png" alt="image.png" />
Showing a validation error for number of days, number of days should be an optional field

**Comment by ayushdamani** [comment]
"Optional" button now appearing!
