### ISSUE TITLE
Mat/Pat - Employee Info Full time/ Part time not being pre-populated

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1498]
As a user, when I navigate to the Employee information tab, the field: Full-time/Part-time (status) should pre-populate with: Full-time or Part-time, based on the user's PeopleSoft data. 

AC:
- [ ] Full-time/Part-time should be populated in production
- [ ] Devs will need to connect to this field on the backend

<img width="1318" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFUwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3467f575ddb9d551ba521d3086a8523712cf1f5c/image.png" alt="image.png" />

**Comment by chriscaldwell-psa** [comment]
@bhumin-fw  That's a good question. Can we investigate the object Key: EMPL_Status more. I'm not sure what that references. Are there other values besides A? My first guess would be this object.

**Comment by fazil-ey** [comment]
So connie said this is what it looks like in People soft frontend, look slike there is a Full/Part field 

<img width="1068" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmc3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16a5dcd5eaccae0ec6097b06fe7aeaf050294e33/MicrosoftTeams-image%20%289%29.png" alt="MicrosoftTeams-image (9).png" />

**Comment by iman-jamali-fw** [comment]
@T854236 
Hi patrick, 
We're looking for a information about employee full/part time status. Can you help us find out which (or any) is available to us? I found one with the name of `full_part_time` in [this endpoint](https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rst#Datamart_Telework_employee_demo), not sure if this is one.

**Comment by T854236** [comment]
@iman-jamali-fw 

Hi Iman, sorry on my late reply.  I think you meant to past this endpoint: https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rst#Datamart_Telework_employee_demographic instead.  Employee status is available on there.

**Comment by iman-jamali-fw** [comment]
@T854236 

Hi Patrick,

You're correct! The `full_part_time` field is accessible only in `Datamart_Telework_employee_demographic`.

I have a couple of questions:

1. Is `full_part_time` the field we should rely on to determine if an employee is full-time or part-time? If yes, could you share the possible values for this field?

2. Could you consider adding `full_part_time` under `Datamart_Telework_employee_demo`?

Also, on a broader note, we have two endpoints for getting employee information: `Datamart_Telework_employee_demo` and `Datamart_Telework_employee_demographic`.

It seems that the `demographic` endpoint has all the information available in the `demo` endpoint and includes additional fields. If this is the case, would it make sense to retire the `demo` endpoint and exclusively use the `demographic` endpoint? Currently, we use the `demo` endpoint for initial form filling, while the `demographic` endpoint is dynamically accessed by form fields when additional information not covered by `demo` is required.

**Comment by T854236** [comment]
@iman-jamali-fw @notjustinchoy 

For question 1, possible values are F (full-time), P (part-time) and D.  I will defer to Justin on what D means.
For question 2, Datamart_Telework_employee_demo breaks down to the job level.  Since an employee can have multiple active jobs, 2 or more jobs can be part-time which can equate to full-time.

The demographic one has some logic built and incorporates information at the position level vs. job level.  Let us know what you need and we can review if it can be merged.

**Comment by iman-jamali-fw** [comment]
@T854236
Oh OK, I guess we need to have a boarder discussion with team to find out if we can merge the two endpints. Thanks for the info.

In the meantime, is it possible to have the `full_part_time` field added to the `demo` endpoint?

**Comment by notjustinchoy** [comment]
@iman-jamali-fw 
Yes, we can add full_part_time to the demo endpoint.  It will require some work on my side.
The 'D' is for "On Demand".
The job_indicator field will also tell you whether the position is P = Primary, S = Secondary, or N = Not Applicable.

Note, the TES BI team's last Production deployment window ended at 11 AM Pacific today (December 14, 2023).  The next one will be January 2, 2024.

**Comment by iman-jamali-fw** [comment]
@notjustinchoy 
Hi Justin,
That would be great if you can add `full_part_time` to the `demo` endpoint. Thank you

**Comment by fazil-ey** [comment]
From Connie - if there are 2 part time jobs, they will be eligible for allowance from only one. It will be 2 records in peoplesoft. We can redirect them to fill the manual form.

**Comment by notjustinchoy** [comment]
@fazil-ey @iman-jamali-fw 
Sorry, next production deployment window for the TES BI team will be January 4, 2024.

In the meantime, I have added two fields to the employee_demo API endpoint in Dev/Test:
1. full_part_time, and
2. job_indicator

As I mentioned above, the job_indicator field will indicate whether the job is P = Primary, or S = Secondary.

**Comment by iman-jamali-fw** [comment]
@notjustinchoy
Thank you Justin. 

One question. How can we know if an employee has more than one job?

**Comment by notjustinchoy** [comment]
@iman-jamali-fw 
A "concurrent hire" employee may have two or more records in employee_demo.  Their EMPLID will be the same for each row, but EMPL_RCD, EFF_SEQ, job_indicator, full_part_time, or position_number should be different.

**Comment by notjustinchoy** [comment]
@iman-jamali-fw 
The two columns full_part_time, and job_indicator have been added to the Production employee demo endpoint.

**Comment by iman-jamali-fw** [comment]
@ayushdamani @fazil-ey 
This is ready for your testing on TEST. You will see the employee full time or part time status (specified as "F" or "P") on the Mat/Par form. Please let me know if anything not working as expected.

**Comment by iman-jamali-fw** [comment]
The case when an employee have more than one job will be tracked under the ticket below:
https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1521

**Comment by fazil-ey** [comment]
looks good 
<img width="1293" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2VwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57786eba5f1b8e3cf684adf8cac74a85adc6a2bb/MicrosoftTeams-image%20%2815%29.png" alt="MicrosoftTeams-image (15).png" />
