### ISSUE TITLE
Mat/Par: Audit and Streamline the Workflow Steps

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1499]
Some of the Mat/Par steps in the workflow appear to be remnants of the initial design. Please review the workflow with Fazil to optimize and eliminate unnecessary steps. During the pre-production devs' check, two specific steps stood out:

1. **Assessment of the "Send email to supervisor about change (with PDF)" Step:**
Question the necessity of this step in the workflow. Determine whether it adds value or can be streamlined for efficiency.
2. **Clarification on Email Content Based on Supervisor Validation Type:**
Collaborate with Fazil to establish if distinct emails are required for the first-time supervisor validation compared to subsequent validations. This consideration arises from the evolution of the supervisor validation process—from an initial "Validate" button to a later version with two options, Approval and Denial.

Let's ensure that our workflow aligns with the current system dynamics and is optimized for a seamless user experience.

**Comment by Stella-Archer** [comment]
when making updates in status would be best time to do this

**Comment by ayushdamani** [comment]
Andrew - can you please take a look at this and comment?
