### ISSUE TITLE
Mat/Par: Optimizing form Validation Logic - Centralizing Field Instances for Consistency and Efficiency

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1500]
Enhance the validation logic in cases where multiple instances of data field (like `Are you the birthing parent?`) are present, and these instances are referenced in validations throughout the form. For example in one place it checks `data.birthingParent === 'yes'` and another place `data.birthingParent1 === 'yes'`

- All validations should rely on a single instance of a field.
- When applicable, transfer the validation logic to a globally hidden field and establish connections between all validations in the form and that global field. This approach facilitates centralized maintenance of the validation logic, streamlining updates across the various forms.

**Technical details:**
For instance, consider two instances where it asks `Are you the birthing parent?`. Numerous sections in the form may require verification of the chosen option. In such cases:

1. Ensure that all validations are anchored to a singular instance for example `data.birthingParent`.
2. Relocate the logic determining whether it is Maternity leave or not (e.g., `data.birthingParent === 'yes'`) to a centralized global field.

This strategy promotes consistency and efficiency by consolidating the validation rules in a single location, minimizing the need for updates across different sections of the forms.

Also, please review the `isEmployeeEligible` global hidden filed as a best practice.

**Comment by Stella-Archer** [comment]
If there is changes to employee class/status would be the best time to update validation logic

**Comment by ayushdamani** [comment]
@Andrew-Vargas-bcgov

**Comment by Stella-Archer** [comment]
Note for best practice but no action necessary on Mat Par now
Developers have internalized this as best practice closing tix
