### ISSUE TITLE
Mat/Par: Form Data Reading Issue in 'Review and Process Forms' for Mat/Par Submission

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1501]
When accessing a submitted Mat/Par form within the 'Review and Process Forms' section, several warnings are generated in the page's developer console. These warnings indicate an issue with reading data from a specific field in the form. The common error pattern is as follows, with `<page-number>` and `<field-name>` placeholders varying based on the field's name and its corresponding page:

```
Error occurred within a custom function for <page-number>: TypeError: Cannot read properties of undefined (reading '<field-name>')
```

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzAxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f272141231a9ef795f78e50429a51f964e428529/Screenshot%202023-12-05%20at%202.16.20%E2%80%AFPM.png" alt="Screenshot 2023-12-05 at 2.16.20 PM.png" />

**Comment by fazil-ey** [comment]
This is needed as diagnosing issues in case of bugs will be easier if we do not have all these unnecessary error messages

**Comment by jerry-ey** [comment]
Discussing with Bhumin, taking back to in progress and do more testing locally to confirm all behaviours.

**Comment by jerry-ey** [comment]
To test this one, see the following steps and screenshot
1.  go to review page
2.  open developer console by right click and inspect
3.  go to console tab
4.  if you don't see lots warning, then means it works.
<img width="1551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTAwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5525e23f9f5879bad0aca125f4fdc56bf03206c1/CleanShot%202024-02-06%20at%2013.23.22%402x.png" alt="CleanShot 2024-02-06 at 13.23.22@2x.png" />

**Comment by ayushdamani** [comment]
Tested in TEST environment. I am still seeing the errors:
<img width="1897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEE2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf82ac450d3cb0c0adc79aa5f10646fe8c01964f/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
@ayushdamani The ticket is asking removing the "Warning" part which is yellow background color.
Error part is expected.
If you don't see too much yellow message, then this one works well.

<img width="463" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3c4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1516130cc0887dd11d7b0ba856f398653ac05c4c/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
<img width="815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFU4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc3694fda6e6bd2c559379e85ea7600377e63551/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Not seeing yellow portions, thanks Jerry!
Moving to PO

**Comment by Stella-Archer** [comment]
Yup lots of red no  yellow :)

**Comment by Stella-Archer** [comment]
<img width="1223" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de7c9e614c5df4f1bcb52d3b6c13ce90255a67ee/image.png" alt="image.png" />
