### ISSUE TITLE
Mat/Pat - Dates within valid range showing error

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1503]
During post-launch testing we observed that 
1. We could not select the start date as the childs birth date
2. Allowance dates were within valid range but  still showed validation error

This was observed in both test and prod

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUl2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ff5aa76b612ca9d54e7006a99f90293f49f7ffe/image.png

**AC**
- [ ] Dates that are valid selections should not show any error

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov this seems like the timezone bug as we were doing our testing late in the evening?

**Comment by Andrew-Vargas-bcgov** [comment]
i'll test this one tonight and fix the issue @fazil-ey

**Comment by ayushdamani** [comment]
Working great, thanks Andrew!

**Comment by fazil-ey** [comment]
could not reproduce, looks good
