### ISSUE TITLE
Mat/Pat - add waiting period instruction for EI screenshot

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1504]
Add instruction in approval email to applicant that when they take the EI screenshot, they must ensure there is waiting period dates. Sometimes it takes 2-3 days, so they should wait till that info is populated. 

**_AC_**
- [ ] Add this as point 3 -  
Ensure the waiting period dates are **in the** "My Latest Claims" page before you take the screenshot. Sometimes it takes 2-3 days for the waiting period dates to appear. Please wait till it appears before taking the screenshot as those dates are needed to calculate your leave allowance.

**Comment by fazil-ey** [comment]
It says 2&ndash3

<img width="1506" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2RuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34eb9caee0ef8ceb82e310af2aa7d6553dfb3b23/image.png" alt="image.png" />

**Comment by MeghanStothers** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeStEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0987124ba92b385bfef37879cc670746aa266f5d/image.png" alt="image.png" />

**Comment by MeghanStothers** [comment]
Meghan and Mike tested:  Test failed - the wording added has two instances of "in the".

Incorrect in the A/C  - I adjusted the AC language so it is now correct.

**Comment by bhumin-fw** [comment]
Corrected based on new AC. remove duplicate **in the** from the sentence. Changes are deployed on TEST environment.

**Comment by MeghanStothers** [comment]
Tested again and see the change has been made - thaks Bhumin. 
Small treak need to close thic ticket  
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUdEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90fe911725d595f0d00c88ae9e2ca9e5ba2b6940/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Hi everyone,
Not able to validate the submission - stuck on the loading screen.
I will request the team at check-in to test this :)

**Comment by ayushdamani** [comment]
Sure, Bhumin!
That'd be great, thank you so much!

**Comment by bhumin-fw** [comment]
Ayush contact is still not there in CRM test.
Let me check what I can do in this case to unblock Ayush to test in TEST environment.

**Comment by bhumin-fw** [comment]
@ayushdamani you can test this now.

**Comment by ayushdamani** [comment]
Tested with Bhumin in TEST environment!
I was able to approve my submission! 

The only things which needs to be fixed is that period, which Meghan mentioned in her comment above. Moving to In-progress

**Comment by bhumin-fw** [comment]
Added fullstop at the end of sentence as per Meghan's instruction in standup.

**Comment by fazil-ey** [comment]
looks good
