### ISSUE TITLE
Mat/Pat - CRM ticket should be assigned to Service centre first

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1509]
**_AC_**
- [ ] New CRM tickets should be assigned to "HRSC - Service Representative" group NOT TES HR Admin Tech. (Do it in TEST ONLY) 
- [ ] If its an update don't reassign to anyone else

<img width="260" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--feef4fff3a485fc34e25242ff38c9b72b5b9c0fb/MicrosoftTeams-image%20%2811%29.png" alt="MicrosoftTeams-image (11).png" />

**Comment by Stella-Archer** [comment]
do in test but not \production until JUST befor public launch

**Comment by fazil-ey** [comment]
@bhumin-fw  tickets should be assigned to "HRSC - Service Representative"

**Comment by Stella-Archer** [comment]
<img width="983" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24f668a829bb5d58e0aa7198459d976259c3a5c5/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
<img width="955" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e3cefeaff814c377e7dc84daf74600d187e0010/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Test tickets grouting correctly to service rep
<img width="862" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWExQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a57f53ceafc8cf57d6d827d95932b07410e35901/image.png" alt="image.png" />
