### ISSUE TITLE
Mat/Pat - Blocking Access to Mat/Pat

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1514]
We need to block access to the mat/pat form for groups who have IDIR but should not submit their mat/pat forms to the PSA HR service centre. 

_Two options_ - block access to the form itself or show a message in the form that this is not the form for them. Dev effort is lower for showing a message so the decision is to implement showing a message within the form

_Decision_ - show a message in the form

**_Groups that we need to block access_**
- [ ] Office of the Auditor General @bcauditor.com
- [ ] Office of the Ombudsperson @bcombudsperson.ca
- [ ] Office of the Info and Privacy Commissioner @oipc.bc.ca
- [ ] Elections BC @elections.bc.ca
- [ ] Office of the Police Complaint Commissioner @opcc.bc.ca
- [ ] Office of the Merit Commissioner @meritcomm.bc.ca
- [ ] BC Rep for Children and Youth @rcybc.ca
- [ ] Human Rights Commissioner @bchumanrights.ca
- [ ] Pension Corporation @pensionsbc.ca
~- [ ] Community Living BC can be identified through organization "Community Living BC" in in the employee data~ #1558
- [ ] Liquor Distribution Board @bcliqourstores.com @bcldb.com 

**AC**
- [ ] When employees from the above groups access Mat/Pat form in digital journeys they should be shown the following  message similar to the ineligible (K&L) appointment status workflow
"This Maternity and Parental Leave form is not the correct form for your ministry or organization. Please contact your ministry or organization's HR team to access the correct form"

**Comment by MeghanStothers** [comment]
From a tech perspective, it's harder to block access. We will plan

**Comment by fazil-ey** [comment]
@Stella-Archer to ask Patrick how to identify Community Living BC folks

**Comment by Stella-Archer** [comment]
the Organization “Community Living BC” filter in org

**Comment by Stella-Archer** [comment]
Hey @bhumin-fw how should/can I test this one?

**Comment by bhumin-fw** [comment]
It is still in progress and can be deploy later this week. We are not adding it to this week's deployment.

**Comment by bhumin-fw** [comment]
@ayushdamani 
To test this ticket. When you fill employee information please add email with blocked domain and you will see 3rd page with blocked access.

**Comment by ayushdamani** [comment]
Seeing the blocked access page for the above stated emails! Thanks, Bhumin! :)

**Comment by Stella-Archer** [comment]
Sweet this looks great - Closing ticket!
<img width="1429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDREQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e299237317211b6d42a10c9cce73ab58c16579d/image.png" alt="image.png" />
