### ISSUE TITLE
ZenHub Board back-up information 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1515]
As a product team, we want to back-up our data to ensure business operations after the ZenHub board is decommissioned at January 15 (extension granted on Dec 22).

No estimates
No pipelines 
No epics
No images
We would lose context of tickets - what is the order/status 

We do see comments

A/C
We have business continuity to carry basic operations until our team's board access has been restored 

Resources/links from Iman
I looked into ZenHub backup and seems like the only way is to use their API to fetch all the data.
 
API is only way to backup/download a board: https://help.zenhub.com/support/solutions/articles/43000480389-exporting-zenhub-data#:~:text=To%20generate%20a%20report%20export,Customize%20your%20data!

Here is the API documentation and guide: https://github.com/ZenHubIO/API
 
The link Meghan shared (added below) is also a third party utility which I believe is build on top of the official ZenHub API.
https://github.com/stolostron/zenhub-backup

**Comment by MeghanStothers** [comment]
@iman-jamali-fw to start the backup today (as possible) and update Bhumin about any next steps.

**Comment by iman-jamali-fw** [comment]
I wrote a file that can call ZenHub API and backup most of the data. Passed that file along with instructions to Bhumin to improve and run those calls on the last day of work to capture the lastest data.

**Comment by MeghanStothers** [comment]
Need to know: where we store the information

**Comment by MeghanStothers** [comment]
Bhumin working on script to export files on Thursday Dec 21. 
Plan
1) Export as JSON files (as multiple zip files)
2) Will store to his local + DJ Teams folder (@Stella to advise location in program area files)  
3) Stella to make plan for smooth team resume to work on January 2

Re-importing datat/restoration work to be put into a separate ticket

**Comment by MeghanStothers** [comment]
Sharing feedback from another product team: Given the comments will remain after exporting tickets to GitHub, we could (before exporting):
1) Add notes to the comments e.g. Product backlog, estimate = 2
2) Link screenshots from ticket to Teams channel/files

**Comment by bhumin-fw** [comment]
I have prepared and export data using below API guideline
https://developers.zenhub.com/
https://github.com/ZenHubIO/API

Note: above API does not contain **Sprint** related details 

It contain:
1. Workspace details
2. Board pipelines (except closed) with issue ids.
3. Each Issue details about pipeline and estimation
4. Events for each issue. (like moved from X to Y, added estimation, etc)
5. List all epics (basic details like repo and issue id)
6. List all issues related to epics
7. List all dependancies from the board, which issue is blocked and which issue is blocking it.
8. List all releases.
9. List all releases with issues list.

Please find attached zip with export file(index.py) and exported data in .json format.

file: [zenhubDataFile.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzU0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4bc602fd2d0733d07c5a7643e3a42224b4da486/zenhubDataFile.zip)

**Comment by MeghanStothers** [comment]
Decision made: Bhumin will back-up board again on **Friday at noon**** and confirm on this thread @MeghanStothers that the board download was successful. 
Meghan to 
1) Save zip file to external DJ Teams channel 
2) Take a screenshot of the board and 
3)  Send a note to team about where they can access the board on GitHub in January if needed:
 https://github.com/bcgov/digital-journeys

   NOTE: Meghan is still hoping for a Christmas Miracle in which all ZenHub broads are functional in Janaury!

**Comment by Abuchana** [comment]
@bhumin-fw will the images be included in the back up?

**Comment by jizhaogit** [comment]
@bhumin-fw, could you please send me the file you used to export Zenhub? Alternatively, please let me know where I can access it. thank you!

**Comment by bhumin-fw** [comment]
@jizhaogit 
Please find attached zip in above comment that fetch meta data of zenhub. (Index.py)

alternate, we are discussing everything in https://github.com/bcgov/digital-journeys/issues/1515 this issue.
In file you can see link to generate token.
 
You need to find your `workspaceId` and `board id` from zenhub.
`workspaceId` can be collect from zenhub board URL.
For `boardId`, open issue and go to network tab in browser and see issue URL, it contain `boardId`.

**Comment by bhumin-fw** [comment]
@Abuchana no Images are part of GitHub issue only. You can see them on GitHub issues for each issues detail and in comment.

**Comment by jizhaogit** [comment]
@bhumin-fw Thank you, Bhumin. I've received the py file and successfully exported my first set of data. Below is a snippet from the `zen_allissues.json` file:

{
    "1139": {
      "issue": {
        "plus_ones": [],
        "estimate": {
          "value": 2
        },
        "is_epic": false,
        "pipelines": [
          {
            "name": "To Be Estimated",
            "pipeline_id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzIzMDI0NTU",
            "workspace_id": "60020b0a13a09c0014af2469"
          },
          {
            "name": "New Issues",
            "pipeline_id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzI0MzIyMDM",
            "workspace_id": "60f098ab875719001bce05fb"
          }
        ],
        "pipeline": {
          "name": "To Be Estimated",
          "pipeline_id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzIzMDI0NTU",
          "workspace_id": "60020b0a13a09c0014af2469"
        }
      },
      "events": [
        {
          "user_id": 75701575,
          "type": "estimateIssue",
          "created_at": "2023-12-04T17:59:50.850Z",
          "to_estimate": {
            "value": 2
          }
        }
      ]
    }
  }
},
I just wanted to confirm if this is correct. I noticed that I didn't get the issues' contents such as subjects, bodies, etc. Could you please advise? Thanks!

**Comment by bhumin-fw** [comment]
@jizhaogit correct, zenhub only store meta data for board. Issue related all information like subject, body, assignTo, label are stored on GitHub issue(in github repo).

**Comment by MeghanStothers** [comment]
Email from ZenHUb about extension to January 15

"After the discussion with the accounting, contracts and leadership teams, we are happy to offer you a grace period for the Zenhub Enterprise Licence contracts. The updated service termination date is January 15th, 2024."

DJ team will still back-up board, take a screenshot and save files to Teams folder as a precaution.

**Comment by MeghanStothers** [comment]
@jizhaogit @bhumin-fw Is there anything further you'll need to to export the zip files?

**Comment by MeghanStothers** [comment]
DJ Teams folder link to save the zip files:https://bcgov.sharepoint.com/:f:/r/teams/03991/Shared%20Documents/General/ZenHub%20Back%20Ups?csf=1&web=1&e=OLgybd

**Comment by bhumin-fw** [comment]
Latest backup uploaded on above mentioned folder.

**Comment by MeghanStothers** [comment]
Update: Connecting you on the latest info I have about the ZenHub issue:
-	We have been given an extension to Jan 15
-	OCIO contact will be advocating for an extension to at least Jan 31 
-	They/OCIO are aiming for an 18-month agreement with the possibility of purchasing orders in a monthly basis.
-	We have the OCIO PIA
-	 OCIO STRA is in progress (last note was December 20)
-	We will still need to complete PSA PIA and STRA 
Decision needed about what term of contract we should request while the DJ team explores other tools such as JIRA

**Comment by MeghanStothers** [comment]
I connected with OCIO contact today and have this update: They are making good progress with the master agreement with ZenHub, but cannot say for sure that ZH will extend the Jan 15 deadline (although the OCIO suggested they might need to give another extension.)  @Stella-Archer  suggest that the board gets backed-up again as a precaution.

**Comment by iman-jamali-fw** [comment]
@bhumin-fw  to have a Backup on Friday

**Comment by MeghanStothers** [comment]
I will get another update tomorrow (Jan 12) about a possible extension beyond Jan 15. In the meantime, be sure to back up the board as planned. @jizhaogit Can you confirm you are also doing a backup tomorrow or on Monday?

**Comment by MeghanStothers** [comment]
The ZenHub PIA is in progress and invoice with exec for signature/routing through e-approvals. I have followed up with ZenHub today to share the latest.
