### ISSUE TITLE
Mat/Par: Add users to KeyCloak Security group for PROD Launch 

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1518]
**User Story**

“As a UX test facilitator I want to add the following users to the Mat/Par KeyCloak group created in ticket #1471 so I can get these HRSC service reps into the 'hidden' Mat/Par PROD form before the workshop on January 4th 2024.” 

**Tasks**
Please add the following people to the security group
developed in ticket #1471
https://bcgov.sharepoint.com/:x:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/HRSC%20Reps%20to%20add%20to%20MatPar%20KC%20group.xlsx?d=w4cdcef96f3b74806b9aac9730f2cee58&csf=1&web=1&e=cSeVCh

**Acceptance Criteria**
the attached 3 users can access the Mat/Par form in PROD before we release to all employees

**Comment by bhumin-fw** [comment]
@Stella-Archer 
I have added all 3 users from the attached excel sheet in mat/pat form group on production.

**Comment by Stella-Archer** [comment]
Ronda has confirmed the new user can access the Mat/Par form in PROD thanks @bhumin-fw 
PO approved and closing this ticket
