### ISSUE TITLE
Mat/Pat - Gap UX - Unselect checkbox everytime there is a change in dates  

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1519]
For both applicant & supervisor, the confirm leave dates checkbox should be unchecked everytime there is a change in the dates and the gap between maternity and parental leave still exists. i.e if the applicant or supervisor checks it, goes back and changes the dates, the checkbox should be unchecked and the applicant & supervisor needs to confirm the new dates.  

<img width="1204" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3R1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--925956ae918a91e647902838ab98a3ad2fc28263/image.png" alt="image.png" />

video - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-12-18%20at%2012.26.07%20PM.mov?csf=1&web=1&e=iMUEl1

**_AC_**
- [ ] The confirm leave dates checkbox is unchecked everytime there are new dates for both applicant and supervisor

**Comment by ayushdamani** [comment]
Tested in TEST environment.
Confirmed working!

**Comment by fazil-ey** [comment]
looks good for both employee and supervisor
