### ISSUE TITLE
Mat/Pat - 2 jobs scenario

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1521]
We have found that some employees have 2 jobs and they are allowed to claim mat/pat benefits only for one of those jobs. We need to find a way to know if an employee has 2 jobs and show them a message saying they need to fill the pdf form. In the future we can find a way to ask them to choose which job they want to claim benefits for. 

@iman-jamali-fw is exploring the technical requirements for this. 

**AC**
- [ ] Show the following message to employees with 2 active jobs after Before you Begin tab, instead of the the Employee Information tab

> We have found that you have two active jobs with BC Public Service. Employees can only claim maternity or parental allowance for one of their active jobs. The digital form is not configured to handle this scenario yet. Instead, please fill out the [PDF form](https://www2.gov.bc.ca/assets/download/342D475867AB49ABA0576D856CD9D2E5) and ask your supervisor to submit it through [AskMyHR](https://psa.frontlinesvc.com/app/account/questions/list) under _My Team or Organization > Leave & 
> Time Off > Maternity, Parental, Adoption._
> 
> If this is incorrect or you have any questions, please contact [AskMyHR](https://psa.frontlinesvc.com/app/account/questions/list

**Comment by fazil-ey** [comment]
Alison to help Iman find people who have 2 jobs in peoplesoft

**Comment by iman-jamali-fw** [comment]
@notjustinchoy 
Thank you for adding full-time/part time status to the demo endpoint. 

Do you know what the data structure would like like when an employee have more than one job on the `demo` endpoint? Or if you can share an anynoumus example with us. Thank you

**Comment by Stella-Archer** [comment]
@T854236 Patrick can you help us with the data structure question?

**Comment by T854236** [comment]
@iman-jamali-fw 

The endpoint where it would list multiple records for the same employee is in the employee_demo endpoint.  The data structure is the same.  Some examples of emplids to filter: 

000310
000506
000869
001345
001371

**Comment by Abuchana** [comment]
@Stella-Archer who will provide the wording for this message, please let Bhumin know.

**Comment by fazil-ey** [comment]
@bhumin-fw i have added the copy to the ticket

**Comment by jerry-ey** [comment]
To test this, you can override the response in Chrome Dev Tool.

- Make sure your chrome is up to date.
- Go to the form and open dev-tool (right click and choose "inspect") 
- Go to Network Tab and find "me" this request.
- Right click on "me" and select "override content". (And it will ask you to create an arbitrary folder)

<img width="1842" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzZmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3ac93051fb9539edcb8be15ce5a3245d15dd46e/image.png" alt="image.png" />

- After select a folder, you can override `noofrecords` to `2`, and then refresh your page.

<img width="830" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd09nQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c52426b9d496359606702ff85b122f4b5ed6aab1/image.png" alt="image.png" />

- after test, you can clean your override by clicking this icon
<img width="809" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e1f5baf5638e49eeadfb2b84fc7056f55e38fa0/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
@ayushdamani Please follow above step to test. And let me know if any issue,  thanks.

**Comment by fazil-ey** [comment]
Hey @jerry-ey  thank you for the help! mostly looks great. Just a few copy edits, 

1. Add a heading as shown below "You have more than one active job with BC Public Service"
2. Change 2 active jobs to "more than one active job"
3. Ensure "My Team or Organization > Leave & Time Off > Maternity, Parental, Adoption" is in one line



<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f42904e0d27e00c6183ece351423e8ca5b8c0469/Screenshot%202024-03-01%20at%2010.23.38%20AM%20copy.png" alt="Screenshot 2024-03-01 at 10.23.38 AM copy.png" />

**Comment by jerry-ey** [comment]
Please verify again.
I have made the above change also adding some vertical padding.

<img width="1088" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUtsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72e602a9621f54e11f8ebb93bfd6d0f85592a206/CleanShot%202024-03-01%20at%2010.44.26%402x.png" alt="CleanShot 2024-03-01 at 10.44.26@2x.png" />

**Comment by fazil-ey** [comment]
Looks good!

**Comment by jerry-ey** [comment]
Tested on PRD, mocking api to 3. Working fine. Close this.

<img width="1830" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3pJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9f155e19abbea7c7ccfbe14a348cbe06ae00a2b/CleanShot%202024-03-08%20at%2016.27.52%402x.png" alt="CleanShot 2024-03-08 at 16.27.52@2x.png" />

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov @T854236 
We receive one query from form owner. If any employee has temporary assignment, will that send over employee_demo endpoint?

**Comment by fazil-ey** [comment]
@mikeshi-bcgov

**Comment by fazil-ey** [comment]
We have removed this for Sprint 34 deployment to resolve issues - 
1. Applicant seeing this when their supervisor is a TA
2. If applicant themselves is a TA will it show up as 2 jobs?
