### ISSUE TITLE
Dev is not working

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1522]
<img width="1610" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWx6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d92f3ec3c746fb748b4f937ebfc8e417ab9f045/image.png" alt="image.png" />

**Comment by MeghanStothers** [comment]
@Stella-Archer can you confirm if this one can be closed?

**Comment by Stella-Archer** [comment]
I can get into the original DEV environment :)
<img width="1003" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFI1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2349750dd69670edc473540826612ad98c79bf33/image.png" alt="image.png" />

**Comment by MeghanStothers** [comment]
Working for Stella
