### ISSUE TITLE
SL Review: Nominee's names have disappeared from the completed nominations

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1523]
Background: Administrator hired staff to back up the submitted nominations. They can not begin backing up because the name of the nominated leader is no longer appearing on the form
<img width="1549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzkwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a120c94639e4cf1fc4ccfeb53a1bb13f900fb276/image.png" alt="image.png" />

all other information is available, but not the name which is key info
the names are available in the submitted form view, appended to the form name
<img width="1525" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEowQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1e2413678993a866dbc8afc4f90ddfdb457d43e/image.png" alt="image.png" />

 The client would lose this info when the back up, they need name in each form 

Steps to Reproduce:
 in production open up a summitted form the nomination name is blank
in the 'submitted forms' tab notice names are associated

Actual Behavior:
 no names in appear in any submitted forms

Expected Behaviour:
 each nomination includes the name of the leader being nominated

Environment:
PROD

**Comment by bhumin-fw** [comment]
@Stella-Archer @JodiLittle 
Seems component issue. I have added one additional field under same field with employee Name.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEo1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--debea5bbad69aed85752e9794ed8fe6e4ebf8c45/slr_name_live.png" alt="slr_name_live.png" />

PDF works fine, That means print PDF button and email attachment should have nominee name in place.

**Comment by MeghanStothers** [comment]
We will want to dig into this issue in our de-brief and understand why this happened and many others: going back to work on band-aid solutions.

**Comment by Stella-Archer** [comment]
Bhumin and I met with Jodi she confirmed the names are now visible on the form and they can proceed with their back up.
PO Approved and closing this thicket
Many thanks for the quick work on this @bhumin-fw

**Comment by Stella-Archer** [comment]
I will make and link a ticket to have this component on a 'Kitchen sink' deployment test form
