### ISSUE TITLE
Mat/Par: Content change to "Denied" Message

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1524]
As a person applying for Mat/par benefits, I would like the email message to reflect clearly my request has been "denied" not "sent back"

**AC**
- [ ] Change subject to "Maternity, Parental and Allowance form denied" 
- [ ] Replace "sent back" to "denied" in email 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODU1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcde345b3310892b6765df7e5969ebaefa33eb7e/image.png" alt="image.png" />

**Comment by MeghanStothers** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODU1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcde345b3310892b6765df7e5969ebaefa33eb7e/image.png" alt="image.png" />

**Comment by MeghanStothers** [comment]
@fazil new usability ticket for prioritization

**Comment by ayushdamani** [comment]
The subject line of the email has been updated ✅
The email matter needs to be updated from "sent back" to "denied" please ❌

**Comment by Andrew-Vargas-bcgov** [comment]
good catch! Totally missed that part of the ticket. Should be fixed now :).

**Comment by Stella-Archer** [comment]
Looks great - Closing this tix
<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE1EQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8bbd53775d09ca9ef57bd3a2c17b6711451cf4e4/image.png" alt="image.png" />
