### ISSUE TITLE
Mat/Par: Front-end field wording change: 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1526]
As a person filling out the form, I would like to have consistent and correct language

Small edit may be needed to live form  (screenshot below taken from TEST environment)

**Comment by MeghanStothers** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXA1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a74b6a175314efb42111f6c6f90038d3e27cbb1/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
no longer an issue
