### ISSUE TITLE
Mat/Pat - Bug - Applicant should not be able to edit parental leave start date if taking maternity leave

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1529]
After leave start date, applicant can edit parental leave start date and length only if they are taking just parental leave, not maternity leave. 
This is because applicants can go on parental leave only if the child is born, so if there is any delay they should be able to change it to a date in the future. 

Refer #906

In the following form the applicant is taking maternity leave, and the leave has started, therefore they should not be able to make any edits to the form. 

<img width="1624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3g3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afca26946f2e9d0e998a3e706a3b521c7640265d/image.png" alt="image.png" />

**AC**
- [ ] After approval and leave start date applicants should be able to edit start date, leave length & parental leave allowance dates only if they are taking "only parental leave"

**Comment by fazil-ey** [comment]
After leave start date - Applicants can edit ONLY parental leave start date, leave length and parental leave allowance dates to a date in the future from current date and no other field.  Currently they are able to change everything. 

After leave start date, if applicant is taking maternity leave or maternity leave + parental leave, applicant should be able to change anything. This works correctly. 

Here this recording was done on 12th Jan, and the leave was starting on 12th Jan and approval was done on 12th jan. Yet when applicant when to submitted forms, they could edit everything.
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202024-01-12%20at%209.43.18%20PM.mov?csf=1&web=1&e=IUL8fD

**Comment by Stella-Archer** [comment]
I can NOT edit my Parent leave after I started the Mat leave so I think this is working as designed now thx - closing ticket
<img width="1366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2ZKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91f3b47c839a39e5dbe69e145437d05f5aef28b3/image.png" alt="image.png" />
