### ISSUE TITLE
Telework: Remove Mandatory upload of ADM approval when request is denied

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1533]
**User Story**
As a ADM/Supervisor denying a 3+ day request for telework I do NOT want upload an "approval' document as I have not approved the request
**Tasks**
Remove the ADM 'proof' document requirement if **Decision = 'Denied'**

<img width="1174" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1dNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85e1d7c9c801c63959b816dfadd798bf77cd56c2/image.png" alt="image.png" />

**Acceptance Criteria**
An ADM or delegate can DENY a 3+ day telework request with out having to upload a document

**Comment by Stella-Archer** [comment]
his may have already been solved in TEST as I can process a DENY without upload pls confirm 
<img width="676" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3lNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61fb7f2b45a609fc023e77612d9ac0b7f909aebe/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
@chriscaldwell-psa and @ayushdamani could you test to see if this is already done in TEST and DEV?
thx

**Comment by Andrew-Vargas-bcgov** [comment]
@ayushdamani Hey Ayush, can you test to make sure upload is required if >=3 days teleworking and approved. If denied, the user should not be required to upload a document.
Also check that there are no errors when <3 days.

**Comment by ayushdamani** [comment]
Tested with Andrew in TEST
Works great - @chriscaldwell-psa can you please do one test as well?

**Comment by chriscaldwell-psa** [comment]
Works like a charm. This ticket can be closed.

**Comment by Stella-Archer** [comment]
this worked did NOT have to upload anything when denying 3+dat request
<img width="890" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUloQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2124260aeaae949815397951d4ee0b7497d70c02/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
I am wondering about the message I saw - Is this what it should be @Andrew-Vargas-bcgov 
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU1oQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3200cc705132979b13243a01e88494baec728716/image.png" alt="image.png" />
