### ISSUE TITLE
Mat/Pat - HRSC/Payroll Content Edits

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1534]
**_AC_**

- [x]  In Employee Information change "Please confirm your information. You cannot edit this information in the form. If your information is incorrect or missing" to 

"Please confirm your information is correct as this is the current information in the employee database - PeopleSoft. If your information is incorrect or missing, please follow the instructions below to correct it as soon as possible as payroll will use the latest information in PeopleSoft when they process your leave to determine your leave allowance. You cannot edit this information in the form. If your information is incorrect or missing, follow the instructions below: "

- [x] Maternity leave - General Information
Change "You must start your leave the day you have your baby, even if it is before the expected due date or the date you intended to start your leave" to "If you have your baby before the expected due date or the date you intended to start your leave, you must start your leave on the day you have your baby" 

- [x] In Parental leave - Start Date, in case of only parental leave,  add the following line under "When was your baby born or placed after adoption?"
"Provide the date your baby was born or placed or the expected due date or placement date"

**Comment by chriscaldwell-psa** [comment]
The three changes have been made in the Dev and push to Test env as well.

**Comment by ayushdamani** [comment]
Thank you, Chris! The changes look great!
Moving to PO

**Comment by fazil-ey** [comment]
@chriscaldwell-psa for #3 can it be a description under the question like in "are you a birthing Parent" <img width="648" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUdqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e771c39e6c93d8e7f7753f27bd30cc4ff72c590e/image.png" alt="image.png" />


<img width="1234" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUNqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--788a90e68a6fada1043bd0617eac1fc6d92bcaaa/image.png" alt="image.png" />

**Comment by chriscaldwell-psa** [comment]
@fazil-ey How does it look now? <img width="827" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNStvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5022b8af25ec88a2c724493b8b977ea030614db3/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
Working with @Andrew-Vargas-bcgov  to fix the font and spacing. While we are fixing it for "What was your baby born...?, also fixing "How many weeks of leave do you want to take?" for Parental leave and "When do you want to start your leave?" for maternity leave

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey moved changes to test. let me know if they look okay.

**Comment by fazil-ey** [comment]
Looks good, confirmed content changes and the font change in the comment above
