### ISSUE TITLE
Mat/Pat - CRM ticket edits

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1535]
**_AC_**
1. Add Employee ID in employee information section
2. Remove the confirmation field for both employee information & partner information

**Comment by fazil-ey** [comment]
<img width="999" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCtZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9029f8e75daaf92c6971f1f4b000b2019fa91dfe/MicrosoftTeams-image%20%2812%29.png" alt="MicrosoftTeams-image (12).png" />

**Comment by fazil-ey** [comment]
<img width="999" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzZkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--998a366cf8b28e8d61e0f6d33782560ec77cd8e6/MicrosoftTeams-image%20%2813%29.png" alt="MicrosoftTeams-image (13).png" />

**Comment by ayushdamani** [comment]
Submitted a form with Stella as my supervisor - would complete the test at check-in!

**Comment by ayushdamani** [comment]
Confirmed updated; employee id has been added

**Comment by fazil-ey** [comment]
@ayushdamani, please upload a screenshot that shows both the AC & close this ticket!
