### ISSUE TITLE
Mat/Pat - Remove fax number in email

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1542]
**_AC_**
- [ ] In all versions of the emails sent to employees after approval, remove "by fax to 250-652-2155." in the income tax bullet as fax is no longer used
"You can choose to have additional taxes deducted to cover the income earned from both sources. Submit a federal TD1 form through an AskMyHR service request using the categories Myself (or) My Team or Organization > Submit a Form or Document > Direct Deposit/Tax Forms (TD1) **_or by fax to 250-652-2155._**"

**Comment by Andrew-Vargas-bcgov** [comment]
Fax number should be removed for all approval emails where allowance is taken.

**Comment by ayushdamani** [comment]
Thank you, Andrew! Fax number has now been removed!

**Comment by fazil-ey** [comment]
Looks good
