### ISSUE TITLE
Mat/Pat - Live Testing

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1544]
List of things we need to do - 

1. Ensure the Subject, Assigned, and Category are correct (Can this be done after releasing all other changes?) 
    - Subject should not have "Test"
    - Should be assigned to Maternity, Parental and Adoption
    - Category should be HRSC - Service Representative
    
2. Adding the live test employees to the Keycloak so that they can see the form. 
    - Their supervisors should also be able to see the the employees submitted forms in productions
    
3. Remove access to the contact centre and other service reps that were given access previously in production.  Keep access for PSA and EY devs. 

4. Make the employee information fields non-editable

Alexander Gleis
AGLEIS
Alexander.Gleis@gov.bc.ca
 
Garima Sood
GSOOD
Garima.Sood@gov.bc.ca
 
Allyssa Fong
AFONG
Allyssa.Fong@gov.bc.ca

**Comment by fazil-ey** [comment]
https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24f668a829bb5d58e0aa7198459d976259c3a5c5/image.png

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e3cefeaff814c377e7dc84daf74600d187e0010/image.png

**Comment by Stella-Archer** [comment]
@fazil-ey we will also need to know the supervisors of these employee names/emails so they can go in and approve the request and trigger the CRM ticket

**Comment by Stella-Archer** [comment]
@bhumin-fw will the end to end LIVE test Applicants also need their Supervisors name & credentials for the security group?  as supervisors  will need to approve the request to trigger the CRM ticket

**Comment by bhumin-fw** [comment]
@Stella-Archer Yes, We need to add their supervisor too in the live testing group. I have fetch their supervisor name too. do you want me to add it in this ticket?

**Comment by Stella-Archer** [comment]
@bhumin-fw will be creating a ticket for Make the employee information fields non-editable
Closing this ticket
