### ISSUE TITLE
Tool - Helm : Webapi is not connecting with patroni database.

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1546]
https://helm-digital-journeys.apps.silver.devops.gov.bc.ca/
On above new server we are not able to test form, It fail with 500 error.

Project: e66ac2-test

On Patroni it has below error message.
_2024-01-08 18:14:54.192 UTC [1700975] FATAL: password authentication failed for user "app"
2024-01-08 18:14:54.192 UTC [1700975] DETAIL: Password does not match for user "app"._

On Webapi pod we can see the same error.
_connection to server at "patroni" (10.98.33.106), port 5432 failed: FATAL: password authentication failed for user "app"_

**Comment by kkapoor-fresh** [comment]
@bhumin-fw  Changed the "app" user password in the web api config map to match up with the password defined in Patroni Statefulset. Api logs look fine so far. Please validate.

**Comment by bhumin-fw** [comment]
Looks good Kunal. We can close this ticket. Thanks for the quick fix on it.
