### ISSUE TITLE
Tool & Env : Test and review new deployment in HELM

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1548]
New server is up and running. We can test forms and workflow on https://helm-digital-journeys.apps.silver.devops.gov.bc.ca/
Note: It is not working for now due to database connection issue. Please check [#1546](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1546) ticket form more updates on it.

Dev Instruction:
Server is up and running under project `e66ac2-test` on openshift cluster.
Branch that set for auto deployment is `DGJ_1236-update-to-the-new-helm-chart-deployment`
Keycloak admin is same as existing DEV environment. Please connect with Warren or Bhumin for forms-client user password. Or create new user and assign required group permissions.

As a designer and user we can create one or more forms and workflow to test existing features, customization and third party data transfer mechanism. Please refer https://formio.github.io/formio.js/app/examples/kitchen.html
 to generate kitchen form.
Idea behind this form is to identify forms behaviour and how component render in new, view, edit, and print form. For that create one kitchen form on existing dev environment https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/ and use same form on new environment https://helm-digital-journeys.apps.silver.devops.gov.bc.ca/ (It will help to identify component behaviours on existing and new environment and also help in troubleshoot and improve bugs on new environment)

Test below task on new environment
- [x] Create form with all existing component
- [x] Create form or add customized component (like ministry dropdown, email, tooltip popup for several components)
- [x] Check onlick popups (review telework, SL, or 1.10 forms)
- [x] Test print PDF on frontend, Make sure all component render properly, same as DEV environment on new HELM TEST environment.
- [x] Add workflow and DMNS, Attach workflow with form
- [x] Checkout Camunda dashboard and review form progress, authentication and permissions for forms and workflows.
- [x] Checkout formio dashboard and make sure any update(assigned new user role, form permissions) made on form does not revert when user update forms.
- [x] On workflow Test assign to user (find user name from keycloak-admin), send email, DMNS based conditions, Email with attachment, timer functions, etc.
- [x] Keep an eye on logs and make sure no error logs for any operations.

**Comment by bhumin-fw** [comment]
reviewed so far
- Added kitchen sink form on DEV environment and copy that form and deploy on new name space. (Works great)
- All formio component and customize to them works fine, like tooltip, select component, popup, DPF generation button and trigger search api dynamically from form. (Works great)
- Added basic workflow with email, DMN and timer to review how submission work. (Works great)
To review Pull data from API in form
-> Pull data works fine (SL + Cold/FLu)
-> **_Display employee name not working (SL): need to update script as new formio version does not support manipulation of data in template of dropdown list._**

Remain Task
- One more DMN and Email workflow along with timer and delete function.

**Comment by bhumin-fw** [comment]
Final update:
All existing component and customization works fine on helm chart deployment.
- Tested DMN based email
- SL, Influenza(cold/flu) and Mat-Pat form tested on new namespace
- Assign submitted for to supervisor also works fine.

to Test,
- There is a kitchensink form that help to test all basic and data grid component that we have used in different form. Print form.
- Other forms are pulled to review all form component, forms are like SL, COld/Flu and Mat-Pat.
- In SL review when you search user you will see comma in between last and first name (for example, It will show name as "Vargas,Andrew Ryan" instead of "Vargas Andrew Ryan")

**Comment by ayushdamani** [comment]
I was able to login with the credentials that Bhumin provided. 
I was also able to look at the Kitchen Sink form - the modules in the form are working as expected.

**Comment by Stella-Archer** [comment]
Looks great, fun to play in side new name space :)  thanks @bhumin-fw
