### ISSUE TITLE
Mat/Pat - Minor Email Edits 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1549]
Minor changes suggested by Connie

<img width="647" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3U1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1ccca37c5eb9f436f6eb940660edea70acfd36b/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
@Andrew-Vargas-bcgov want to make sure this is also on your radar as you are reviewing emails

**Comment by Stella-Archer** [comment]
This looks perfect thanks @Andrew-Vargas-bcgov PO Approved Closing Tickets
<img width="649" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN01LQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d938d56a683f1c44b869b10fe7d13b30378d7e41/image.png" alt="image.png" />
