### ISSUE TITLE
TOOL: CSS style tweaks

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#155]
1. There is a hover effect when you mouse over any of the Section headers, bullets or check boxes. Can we remove this? It indicates they are clickable, when they are not.

2. Info callouts should have a background. 

3. Font sizes are inconsistent– checkbox font size is larger than bullet points. 
Call-outs, bullet points, checkboxes, radio buttons, tool tips, should be:
BC Sans Regular 15pt with 21pt leading.
Spacing (leading) between bullet points is a bit wide right now. Can we tighten this up? Should be leading listed above.
Questions should be:
BC Sans Bold 24pt with 32pt leading.
Field labels (Ex. Legal name, Phone number) should be:
BC Sans Bold 17pt with 24pt leading.

4. Can we make tooltips wider, with a blue “info” background shown in the wireframes?

5. Superscript “1” should be a superscript in for benefits continuation in both sections.

**Comment by warrenchristian1telus** [comment]
@Stella-Archer I think we should discuss at our next opportunity to determine which of these should apply just to the Maternity form, and which should be global. I would think most of these design decisions should apply to all forms.
