### ISSUE TITLE
Mat/Pat - Double submission

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1551]
- There are 2 submissions (most likely after approval). When I approved the form i observed that I saw the "dancing balls" loader instead of the "submitting..this can take a few mins" loader in the review and process tab. 
- Could not replicate, does not happen for all submissions

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2JEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e7dc1f953f602c95519e5345da3c26bf5aabc93/image.png" alt="image.png" />
<img width="1554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2ZEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef40a5a41827eabc140c98a4cad12bcaea1eb007/Screenshot%202024-01-12%20at%209.15.27%20PM.png" alt="Screenshot 2024-01-12 at 9.15.27 PM.png" />
<img width="1354" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2pEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ba778affd94e81a1b1f7f07bb71fd94b7f1b22a/Screenshot%202024-01-12%20at%209.15.34%20PM.png" alt="Screenshot 2024-01-12 at 9.15.34 PM.png" />

**Comment by Stella-Archer** [comment]
neither Bhumin nor Jerry can not replicate this either  - moving to ice box incase it pops up once we are live

**Comment by fazil-ey** [comment]
closing and we can reopen if this is observed again in production
