### ISSUE TITLE
Mat/Pat - Production Bugs Jan 16, 2024 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1554]
Syncing issues in production. Seems to be. happening only in cases when taking a leave with a partner in BC gov. https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202024-01-16%20at%206.22.47%20AM.mov?csf=1&web=1&e=WvCmA3

video - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202024-01-16%20at%206.51.37%20AM.mov?csf=1&web=1&e=Gnw5sp

Also replicated in test - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202024-01-16%20at%206.31.46%20AM.mov?csf=1&web=1&e=kSuzwT

**Comment by jerry-ey** [comment]
I can not reproduce on Test and Prd env.

**Comment by Stella-Archer** [comment]
Fazil will try to replicate the issue to see if it  is still happpening

**Comment by jerry-ey** [comment]
Discuss with Fazil and Iman, would do more testing regards memory issue and document it.

**Comment by jerry-ey** [comment]
@fazil-ey  Please verify again, thanks.

**Comment by fazil-ey** [comment]
Could not replicate in Test, still had a lot of tabs opened. tested in with a partner for both maternity + parental and just parental

**Comment by fazil-ey** [comment]
Can be pushed to prod!
