### ISSUE TITLE
Mat/Pat - Email to applicant on form submission is different for one of the cases

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1555]
The copy email to applicant on form submission when taking maternity and parental leave without partner is not the latest copy. it is the following,  - 

> 
> This is to confirm that we have received your application for maternity/parental leave.
> 
> Your application has been forwarded to your supervisor for review and approval. Once your supervisor approves your leave, we will notify you via email. You can also check the status of your application in the 'Submitted Forms' tab on Digital Journeys
> 

The copy email to applicant on form submission should be 

> "This is to confirm that we have received your application for maternity/parental leave. Your application has been forwarded to your supervisor for review and approval. Once your supervisor approves your leave, we will notify you via email. You can also check the status of your application in the "Submitted Forms" tab on Digital Journeys
> 
> Your supervisor can make limited changes to your form on your behalf. They can update your leave start date, length of leave and parental leave allowance dates. They can access your form on Review and Process tab in Digital Journeys"
> 
>

**Comment by ayushdamani** [comment]
Email is now confirmed updated!
Moving to PO!

**Comment by Stella-Archer** [comment]
Looks great thanks all closing tix
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f3229c9a297ea5b0a7c2ddecec1d86f02d588a9/image.png" alt="image.png" />
