### ISSUE TITLE
Telework: Display only the selected option from the two required options under the "Teleworking Schedule" section

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#156]
**Actual Behavior:**
If the user selects "I am requesting to telework on an occasional basis, with no formal schedule", then the checkboxes for telework schedule days section is not displayed.  If any checkboxes are selected, the user is displayed with the checkbox "I am requesting to telework on an occasional basis, with no formal schedule".

**Expected Behavior:**  If the user selects any Mon-Sun checkboxes, then, the user should not be displayed with the checkbox "I am requesting to telework on an occasional basis, with no formal schedule".

![teleworkSchedue.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/f579c624-b3d7-4db3-be0e-79619710f003)

**Comment by DonMoffatt** [comment]
Hello @jizhaogit : I will work on this one then update you, unless you are close to being done with it. Stella wants you to focus on the #222 (the production environment). Is that ok?

**Comment by DonMoffatt** [comment]
I've got this half done. If the user selects the "no formal schedule" checkbox then the specific day options disappear (and reappear if the box is deselected). Getting the "no formal schedule" tickbox and text to disappear is proving more difficult.  I am wondering if there is an issue with the hide() function or if I need to set show() to false.

**Comment by DonMoffatt** [comment]
@Stella-Archer Can you please test this? It works for me. Go to the Telework form in TEST.

**Comment by Abuchana** [comment]
- [ ] test 

- [ ] test 

- [ ] 3

**Comment by Abuchana** [comment]
- [ ] test 4

- [ ] test 5

- [ ] test 6

**Comment by Stella-Archer** [comment]
**Q/A Actions DEV Env.**
- [ ] when 'No formal schedule' is checked schedule day options is hidden

- [ ] when a 'schedule day' is checked  'No formal schedule'  option is hidden

- [ ] when a 'schedule day' is checked the day is added to the # of days a week field

- [ ] when 3 or more days are checked in 'schedule day' the day(s) are totaled in the # of days a week field and the 'ADM Alert message' is displayed

**Comment by Abuchana** [comment]
I LOVE IT, Stella!!!! 😊

Alison Buchanan
Scrum Master, Project Manager
Corporate Services Division | BC Public Service Agency
810 Blanshard St | Victoria BC | Tel 778.698.2133

**Comment by Stella-Archer** [comment]
### Test test

**Comment by DonMoffatt** [comment]
There is an issue executing javascript in DEV. The solution works in TEST. Let's separate out the checklist issue from this ticket, as that is not related.

**Comment by DonMoffatt** [comment]
There is an issue executing javascript in DEV. The solution works in TEST. Let's separate out the checklist issue from this ticket, as that is not related.
