### ISSUE TITLE
Mat/Pat - Email content 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1561]
Add the following to the email (all versions) sent to applicants after approval 

**AC**
- [x] Add a point stating the employees benefits will continue unless they are explicitly cancelled by the employee. Ensure the link is also added

> Benefits in place before your leave will remain in place during your leave unless you [cancel](https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/pay-benefits/benefits/excluded#open_enrolment) them.  You must maintain Employee Basic Life Insurance and long-term disability coverage, there is no option to waive this coverage.

- [x] Add this in the end of the email

> NOTE: You will lose access to your work email after you start your leave. Please save a copy of this email or forward it to your personal address your reference. 

- [x] Change the last bullet from (Ensure the link to DJ is also added) 

> "Your supervisor can make limited changes to your form on your behalf. They can update your leave start date, length of leave and parental leave allowance dates. They can access your form on Review and Process tab in Digital Journeys"

 to 

>   "You can edit the form before your leave start date by going to "Submitted Forms" on [Digital Journeys](https://digital-journeys.apps.silver.devops.gov.bc.ca/form). If you need to edit the form after your leave start date, please contact your supervisor. Your supervisor can make limited changes to your form on your behalf. They can update your leave start date, length of leave and parental leave allowance dates. They can access your form on Review and Process tab in Digital Journeys

For reference on where to add/change the copy
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHJpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd7bd939c1073dfb8e6717a9cad181d7197fefaa/image.png" alt="image.png" />

**Comment by Andrew-Vargas-bcgov** [comment]
@Stella-Archer I'll add these changes today :)

**Comment by Andrew-Vargas-bcgov** [comment]
@chriscaldwell-psa

**Comment by Stella-Archer** [comment]
@Andrew-Vargas-bcgov I just checked with Connie - she's like the link on cancel removed 
because it is specific to excluded and there is different processes for differed employee classes

**Comment by Stella-Archer** [comment]
<img width="729" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmp3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19c03a3fd69ee77c57ae3cbfd2a5d7cbc2533066/image.png" alt="image.png" />

**Comment by chriscaldwell-psa** [comment]
Reviewed and approved all 3 bullet points reflected in the Mat Part document. This can be closed - great Job.
