### ISSUE TITLE
Tool: Troubleshoot and Fix Patroni Defective Image

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1562]
The latest version of the Patroni image, _patroni-postgres:12.4-latest_, is defective. This issue is causing service interruptions in associated components namely Keycloak, API, and Camunda.

A functioning version of the Patroni image is stored in the BC Gov Artifactory, accessible at `artifacts.developer.gov.bc.ca/bcgov-docker-local/patroni-postgres:2.0.1-12.4-latest`. Warren has successfully reconfigured the Patroni StatefulSet to direct towards this BC Gov working image. However, there is an ongoing risk. 

The Patroni ImageStream in OpenShift is still linked to the defective Patroni image, `patroni-postgres:12.4-latest`. This poses a potential problem during a rebuild/restart of the Patroni StatefulSet (might cause by OpenShfit Cluster updates), as new pods could be created based on the defective image.

Acceptance Criteria:
- The Patroni StatefulSet should be tested for a rebuild/restart in a non-production environment to ascertain whether the defective image influences the creation of the new pods. If this is the case, the Patroni ImageStream should be updated to direct towards the functional image in the BC Gov Artifactory.

**Comment by iman-jamali-fw** [comment]
Restarting Patronin Statefulset on DEV worked well and the new pods were built off the BC Gov hosted image (working image). Will continue troubleshooting on TEST for today.

**Comment by iman-jamali-fw** [comment]
Tested out Patroni in TEST and pods were recrated (on oc rollout restart) by the BC Gov hosted image and working fine.

**Comment by Stella-Archer** [comment]
To test: check Mat/Pat check all service are working 'end to end '
check data in CRM

**Comment by Stella-Archer** [comment]
@bhumin-fw  - End to end mat/pat looks great TEST CRM received string for details and PDF attachments.
However I did notice the **Subject** field in the CRM generated ticket has reverted back to the value we had before our last deploy to PROD - could have nothing to do with the Patroni issue but want to check and get it fixed anyways
OLD ticket with correct info in subject field
<img width="884" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5aac79b5844b9671ddec88d1afebf0017f424e8/image.png" alt="image.png" />

NEW ticket with TEST back in the subject Field
<img width="878" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFlFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe627561f5a8a7512b46a655c10142be2ca70641/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
Seems Change by any recent update on PROD mat-pat. Let me correct it right away.
No this is not related to patroni database issue.
