### ISSUE TITLE
Telework: 3+ day Supervisor notification email URL to approve is not linked

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1568]
Background:
When a supervisor receives a email to approve a 3+ day telework request the URL to approve is not linked
<img width="931" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTM5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b4cdb7fc960c4de1397623611ac264bf67f1614/image.png" alt="image.png" />

Steps to Reproduce:

1. make a telework request for 3+ days 
2. review supervisor email 
3. In the **After obtaining proof of ADM (or delegate) approval** section, check first bullet

_Open the request at this link: https://digital-journeys.apps.silver.devops.gov.bc.ca/task/eaaca67f-a5b9-11ee-98f5-0a580a618238_

Actual Behavior:
URL is displayed, but it is not linked

Expected Behaviour:
 URL should be linked to help supervisor find and get to the form needing approval

Environment:
PROD
TEST

**Comment by Andrew-Vargas-bcgov** [comment]
@Stella-Archer I turned the link into words and made it into a hyperlink so the manager can just click it for occasional, <3 days and >=3 days . Can you test this and let me know if you want me to change the text and the links work.

**Comment by Stella-Archer** [comment]
Sweet this is looking great - goes right to the review and process tab :)
for occasional or 3 days it perfect - 
Unfortunately the 2 days email is wrong - you do NOT need ADM approval/upload for that
<img width="839" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM01FQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d46dc9951f1be86c2226e8cdd05594ff79fd2394/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
this is what the 2 day request should look like replacing the URL with 'review the submission' linked would be super nice it looks way cleaner, scans easier
<img width="879" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1VFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--130eb6393516691cb5d2143cc7066d4ad660569b/image.png" alt="image.png" />

**Comment by Andrew-Vargas-bcgov** [comment]
Updated the less than 3 day request. Weirdly the original one I was working with had the adm requirement, but I removed it :).

**Comment by ayushdamani** [comment]
<img width="1146" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzBQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--116f5e272985e654347df0c8c8f874c934a27d0d/image.png" alt="image.png" />

Less than 3 days, has been updated! Thank you, Andrew :)

**Comment by Stella-Archer** [comment]
Perfect - ready to deploy

**Comment by Stella-Archer** [comment]
It's LIVE and it rocks!
<img width="885" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDBoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5c3040ce2474c3c576742513902f577d0560ba4/image.png" alt="image.png" />
