### ISSUE TITLE
SERVER SIDE PDF: fields are cut-off and manager's section not present in the generated email PDF

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#157]
**Background:** Some fields are cut-off in the EMAIL-generated PDF. In the final email sent to the employee and manager after a decision has been made, the attachment in that email does not have the manager's section visible. 

**Steps to Reproduce:**
1. Log in to the PSA-Digital-Journey portal on dev with valid credentials.
2. Fill out the telework form. 
3. Click "Submit".
4. Approve/Reject the form logged in as a supervisor.
5. View the pdf in the e-mail.

**Actual Behavior:** Some fields such as signature are cut-off in the generated PDF. The manager's section of the pdf that was approved/denied is also not present (Same applies to the maternity, parental form)
Please see the attached pdf:
https://app.zenhub.com/files/439477060/3bca4828-c790-4e25-be8e-e20538e5ce53/download

**Expected Behavior:** The user should be displayed with all the content as was entered by the user on the PDF and the final approval or denial in the manager's section should also be visible.

**Comment by MeghanStothers** [comment]
Ticket #71 to be completed before this one

**Comment by iman-jamali-fw** [comment]
@MeghanStothers Please let me know if including a link to TOOL in the emails for generating a PDF works. Otherwise, I look into options for the server-side pdf generation.

Including a link to download/print pdf in emails for users involves, clicking on that link. The link will navigate a user to the TOOL where they should log in first, then will land on a page where can click a button (or automatically) print/downalad pdf.

**Comment by Abuchana** [comment]
Show after the manager has approved or denied and there after

**Comment by Stella-Archer** [comment]
@iman-jamali-fw  we'd like to try the 1st suggestion:
Rely on API to generate PDF.
This could be Common Document Generation Service by BC Gov as suggested by Karim.
Or a custom API using Node.js technology to reuse the pdf generation library that was used on the client-side

**Comment by alexandralloyd** [comment]
@iman-jamali-fw @MeghanStothers Please review ticket #353 as this relates to this ticket.

**Comment by Stella-Archer** [comment]
common components has a API document generator > https://bcgov.github.io/common-service-showcase/services/cdogs.html

**Comment by iman-jamali-fw** [comment]
@HasanSifat For splitting this ticket I suggest:
1. A ticket that makes sure PDF has the right formatting/styles/font/icons and no cut-off and has manager sign-off visible.
2. An integration ticket that integrates the solution built in 1 into the system. This ticket ACs can include PDF generated in 1, attached to the emails.

As an idea we can keep the ticket in the product backlog for reference along with other linked tickets and when 1 and 2 completed, we can close all pdf related tickets (can that day really comes)

**Comment by alexandralloyd** [comment]
Currently not working in TEST - manager's section is still missing

**Comment by Stella-Archer** [comment]
[Uploading... image.png]

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/0cb33e8e-ca39-4204-a761-1ffdc8f62539)

**Comment by simensma-fresh** [comment]
@alexandralloyd @Stella-Archer This has now been resolved, and is ready for a re-test

**Comment by HasanSifat** [comment]
Tested Successfully in TEST. 

Manager Notification email has an attachment with the manager's section visible and unfilled- 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/d3e12e06-b273-4c5f-bb26-44269237e906)

Employee final confirmation email has an attachment with the manager's section visible and filled out- 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/d7b7e101-f9a3-41d4-8543-bafe5740b9e1)

Manager's final confirmation email has attachment with manager's sign-off section visible and filled out-
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/47452532-7677-49b6-8b8e-95b69ba6f35b)

**Comment by alexandralloyd** [comment]
Working in TEST.

**Comment by HasanSifat** [comment]
Tested successfully in PROD

Ready o be closed
