### ISSUE TITLE
Mat/Pat : Return to work email edits

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1571]
The instructions in the return to work reminder email are unclear and need to be updated
Replace the copy of the reminder email as follows - 

> 
> This is to inform you that you must notify your supervisor about your intent to return to work at least 4 weeks before your intended return date. To notify your supervisor complete this [letter template](https://www2.gov.bc.ca/assets/download/E7ED327147F843678802958B9310F218) and ask your supervisor to submit an [AskMyHR](https://www2.gov.bc.ca/gov/content/careers-myhr/bcpsa/contact-the-bc-public-service-agency) service request for "My Team or Organization" under the following category "Leave & Time Off > Maternity, Parental, Adoption" with the letter attached.
> 
> You must also inform your supervisor if:
> 1.	You’re requesting an extension to your leave, and you have not taken the maximum parental leave and extended childcare leave (combined maximum of 78 weeks total).
> 2.	You’re wanting to return earlier than the date you indicated on your digital application; or
> 3.	You’re resigning and not returning to work.
> 
> Ask your supervisor to submit an AskMyHR service request for "My Team or Organization" under the following category "Leave & Time Off > Maternity, Parental, Adoption" advising that you’re returning early, extending your leave or resigning. AskMyHR will process the request and confirm when the request is completed.
> 
> There are things to consider if you’re extending your leave, returning to work or resigning.
> 
> - If you’re extending your parental leave and not receiving leave allowance, there won’t be any pay to deduct your premiums for any of the optional life insurance plans.  If you would like to pay the premiums to  maintain any optional life insurance, complete an [Option to Continue Benefits While on Employment Standards Act Leave of Absence Without Pay form](https://www2.gov.bc.ca/assets/gov/careers/all-employees/leave-and-time-off/continue_benefits_esa_loa_without_pay.pdf). Submit it to your supervisor to submit to AskMyHR. You will receive a statement of cost.
> - If you’re taking extended childcare leave, your benefits will be cancelled at the end of the month in which you start extended childcare leave.  You can pay the premiums to maintain any of your benefits by completing the [Option to Continue Benefits While on Leave of Absence Without Pay or Layoff](https://www2.gov.bc.ca/assets/gov/careers/all-employees/leave-and-time-off/continue_benefits_loa_without_pay_layoff.pdf). Submit it to your supervisor to submit to AskMyHR.  You will receive a statement of cost.
> -  If you have deferred your allowance and you wish to claim it when you return, submit a copy of “My Latest Claim” (which can be found by logging into your account with EI) and submitting it to [AskMyHR](https://www2.gov.bc.ca/gov/content/careers-myhr/bcpsa/contact-the-bc-public-service-agency) service request for “Myself” under the following category “Leave & Time Off > Maternity, Parental, Adoption”.
> - If you cancelled your benefits while you were on leave and want to reinstate them upon your return to work, you must complete the applicable application form and submit it to AskMyHR under the following category Myself > Benefits > Bargaining Unit or Excluded Employees
>     -  [Bargaining Unit Benefits Program Enrolment/Change Form](https://www2.gov.bc.ca/assets/gov/careers/all-employees/pay-and-benefits/benefits-for-bargaining-unit-employees/bargaining_unit_benefits_enrolment_change.pdf)
>     -  [Flexible Benefits Program Enrolment/Change Form](https://www2.gov.bc.ca/assets/gov/careers/all-employees/pay-and-benefits/benefits-for-excluded-employees/flexible_benefits_enrolment_change.pdf)
> - If you suspended any [deductions](https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/leave-time-off/cancel-deductions) during your leave, such as bus pass, charitable donations, deferred salary leave, etc., contact AskMyHR to reinstate them.  
> - Your pension contributions are based on the leave allowance you received while on leave.  You can purchase the remaining service for your leave within five years of the end of your leave period or before termination of employment, whichever occurs first.  For more information, refer to the:
>   - [Purchase of service page](https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/pay-benefits/benefits/pension/purchase-service)
>   - [Public Service Pension Plan website](https://pspp.pensionsbc.ca/)
> - If you’re resigning to care for your dependent, you may be eligible for [Bridging of Service.](https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/leaving-the-public-service/bridging-service)
>     - You must notify your supervisor and note that you’re Bridging Service in your resignation letter.  
>     - Bridging of service cannot be claimed retroactively.
> 

**AC**
- [ ] The copy for return to work reminder email is updated as described above

-------

**Comment by MeghanStothers** [comment]
Suggested edits and questions: 

This is a reminder to inform your supervisor at least 4 weeks before your intent to return to work date. 

Please include the following information in your communication to your supervisor
•	Type of leave you took (include leave types here?)
•	First day of work (rephrase for clarity "Your return to work date")
•	Phone number(s) for supervisor to reach you, if needed.

You must ask your supervisor to submit an AskMyHR service request for 'My Team or Organization' under the following category 'Leave & Time Off > Maternity, Parental, Adoption' with the letter attached. (Does it have to be a letter or is email okay?) 

Extending your leave 
You can (must?) inform your supervisor about your intent to extend your leave beyond your originally chosen return date. 

To extend your leave, ask your supervisor to update and resubmit your Maternity and Parental leave form with the new length (date?) of maternity or parental leave. 

(Not sure what this info relates to.....After employee submits?)

Log into the Service Canada website <link) and go to 'My Latest Claim'.

Take a picture or screenshot of the contents on 'My Latest Claim' webpage. This information confirms that you have been approved by Service Canada to receive the Maternity/Parental benefits.

**Comment by MeghanStothers** [comment]
@Andrew-Vargas-bcgov Hey there- I recall Stella decided we would not include this email reminder at launch and would check in with Fazil when he's back to review the suggested edits and answer the questions I'd noted above. 
@Stella-Archer I added Fazil to this ticket. Can you confirm that the email updates are not in scope for today's deployment or if you would like Andrew to do some of them?

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey  Can you give some insight on this when you get back?
I am going to remove the reminders for now until we get confirmation.

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey We have 4 different emails currently for the return to work email:
1. defer topup & not extended
2. defer top up & extended
3. not defer top up and not extended
4. not defer top up and extended.

Do you want me to add the additional information you put in those emails at the bottom of this new email copy? Or are we just using this one for all of them?

**Comment by fazil-ey** [comment]
Copy updated

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov  added the deferral bullet and updated the copy

**Comment by Andrew-Vargas-bcgov** [comment]
sent the email to fazil and ayush. If it looks good, I can enable it in the form and workflow.

**Comment by fazil-ey** [comment]
emails looks good, we can release

**Comment by Andrew-Vargas-bcgov** [comment]
this is in prod, but we need to add a check before the email goes out in the workflow to verify the manager has approved.

**Comment by Andrew-Vargas-bcgov** [comment]
You can test this by having your leave end date be less than 6 weeks in the future. The return to work email should only happen if the leave is approved and we are past the leave end date - 6 weeks.

**Comment by ayushdamani** [comment]
Looking good! Thanks Andrew - moving to PO

**Comment by fazil-ey** [comment]
i recieved this email!
