### ISSUE TITLE
Mat/Pat: Denied confirmation page edit

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1572]
The confirmation message for a request that has been "denied" has a list bullet with one item in it could we remove the list and just have the text in a regular paragraph?
<img width="1498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlVLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c48a1010f3e77c434ec9fdd69d9fd2c63b2f428f/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
ready to test, thanks

**Comment by Stella-Archer** [comment]
Thanks Jerry looks great
<img width="1523" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHNMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0dfce37980e94b9fdf4569e8d42ecb7da07b0508/image.png" alt="image.png" />
