### ISSUE TITLE
Mat/Pat: Confirm "TEST" is removed from subject line going to CRM

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1574]
Please make sure the Prefix TEST is removed form the :subject' field before launch
<img width="858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOThLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4959db5be2af896937c6ef56d551db798cd290d/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
Please test, thanks

**Comment by Stella-Archer** [comment]
YAY looks great @jerry-ey thanks for jumping right on that!
<img width="899" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUVMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--760ea33c89f3bc758e969b8d57574c2443e48081/image.png" alt="image.png" />
