### ISSUE TITLE
Mat-Pat: Disable Employee information edit on form

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1576]
As a user I would like to keep data on Digital journey Form and ODS/CDATA same. That's why employee information on employee detail tab must be disabled. So employee can see that information to verify but not edit on digital journey form itself.

**Comment by Stella-Archer** [comment]
Looks good Bhumin!
<img width="1524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0FMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a5b08a2bf9060acba20bfc2160256de2c155fb9/image.png" alt="image.png" />
