### ISSUE TITLE
Mat-Pat: Fix invalid date issue for start date and maternity start date

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1578]
Invalid date appear in couple field field if we apply for only parental leave.
That has no effect on UI/UX but we are using it in workflow. Hence those value needs to be fixed for 'hiddenStartDate' field.

On CRM Thread, We noticed that Maternity Start date shows "Invalid date". If only parental leave is selected in form.

Task:
- [x] Fix "hiddenStartDate" value in case of only Parental Leave.
- [x] Remove "Invalid date" under Maternity leave section from the CRM thread Text in case of only Parental Leave.

**Comment by ayushdamani** [comment]
Tested in TEST - unable to reproduce the issue!

**Comment by Stella-Archer** [comment]
@bhumin-fw How do I test this?

**Comment by Stella-Archer** [comment]
CRM thread looks good I only see Parent leave info no invalid Mat leave
<img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fde2bd5f1e517824629ac4ba7812a529232d116/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Email thread is also good - ready to deploy
