### ISSUE TITLE
Mat-Pat: Union Codes Update

### ISSUE THREAD

**Issue by Andrew-Vargas-bcgov** [bcgov/digital-journeys#1579]
Add CRN as additional condition for Crown Counsel in form.
Add GEU as additional condition for BCGEU in Form.

SalAdminPlan returns 3 character length versions of the union/crown counsel/excluded membership.

Crown Counsel references are only found in the form and need to be updated throughout.

- found in all references to leave length allowance info.
- Maternity leave - Leave allowance
- Parental leave - Leave allowance
- Parental leave - Leave allowance dates - repayment date
- Deferred allowance dates

GEU needs to be added to DMN to send the proper emails to BCGEU members.

**Comment by Andrew-Vargas-bcgov** [comment]
@Stella-Archer @chriscaldwell-psa I have unlocked the employee info section so you can use either GEU or CRN to test these conditions.

**Comment by Stella-Archer** [comment]
GEU email:
<img width="755" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelFmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e238700541855336c553cbd6005abed032e339d2/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Live and Fantastic closing this tix
