### ISSUE TITLE
Mat/Par : Parental leave – leave type and length Content edits

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1581]
Under the Parental leave – leave type and length of leave

Example should be gender neutral language.

Use they and their.

<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2taQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37842bd9e86866da982b9944580c1681d5819a82/image.png" alt="image.png" />

**Comment by chriscaldwell-psa** [comment]
Within the Parental leave - leave type tab, the gender male pronouns have been changed to: they/their:
<img width="1623" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8abc4593d2b97668b038732759f1623f5652dbe4/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Perfect - ready to deploy

**Comment by Stella-Archer** [comment]
<img width="1264" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemtmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8d24f87bd15dd693f11fdeb91a93ab8898a8299/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Sweet thanks - ready to deploy

**Comment by jerry-ey** [comment]
Working on PRD.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd01oQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9dbf67fb529e4c4cd577069972e3874cb826c38f/CleanShot%202024-02-01%20at%2017.46.13%402x.png" alt="CleanShot 2024-02-01 at 17.46.13@2x.png" />
