### ISSUE TITLE
Mat/Par : Parental Leave – Estimator Information box Content edits

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1583]
Under the Information box ( “?”)  in the EI Estimate for Parental Leave

Step 1 – Use the EI maternity and parental benefits calculator to estimate how much you might receive for EI depending on whether you are claiming Standard or Extended EI.

Remove the highlighted:
<img width="354" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70c03ed5b61b337e851ef9731298535ad2ac604e/image.png" alt="image.png" />

Step 2 – The EI estimator provides you both the standard and the extended parental benefits amount.  When completing the amount under EI estimate (weekly), use the standard parental benefits amount even if you are taking extended parental benefits with EI as the calculator calculates what you would receive if you were taking standard parental benefits with EI and standard leave allowance and divides it over 61 weeks.

**Comment by jerry-ey** [comment]
@Stella-Archer  Step1, the highlight part is actually in a `image`, could you provide a new image?
(The part where the  screenshot showing is actually a image file, can not directly fix the text, please provide new image to replace the existing one.)
<img width="598" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3dnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e3561d039f4b6ef757b7f3d2c0a6c1b95bc9642/CleanShot%202024-02-01%20at%2016.11.08%402x.png" alt="CleanShot 2024-02-01 at 16.11.08@2x.png" />

**Comment by jerry-ey** [comment]
Thanks Andrew providing me the link to screenshot.
https://www.canada.ca/en/services/benefits/ei/ei-maternity-parental/benefit-amount.html

**Comment by chriscaldwell-psa** [comment]
@Stella-Archer  Please provide a screenshot for Jerry. Thank you!

**Comment by Stella-Archer** [comment]
Image for Step 1:
<img width="483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2MwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e898f51ae9949158a879e4213a3ff82dfb2584c9/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Image for Step 2: 
<img width="874" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEUwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1aca45828c5ae157515c8017cc6cbc93de883fb0/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
updated the text and 2 above images, please test ,thanks

**Comment by ayushdamani** [comment]
Looking good! Thanks, Jerry!

**Comment by Stella-Archer** [comment]
Yes this looks terrific @jerry-ey  I will send the link to Connie to approve
<img width="246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTQ4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6384994226614083712dea3959ed966b13e1888f/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Update: 

- Please add link to the estimator in the instructions -
'Step 1 – Use the **EI maternity and parental benefits** calculator to estimate how much you might receive for EI depending on whether you are claiming Standard or Extended EI.'

- In Step 2, please add the information in bold -
'Step 2 – The EI estimator provides you both the standard and the extended parental benefits amount.  When completing the amount under EI estimate (weekly), use the standard parental benefits amount even if you are taking extended parental benefits with EI **and extended parental leave allowance** as the calculator calculates what you would receive if you were taking standard parental benefits with EI and standard leave allowance and divides it over 61 weeks.'

**Comment by jerry-ey** [comment]
Ready for test

**Comment by ayushdamani** [comment]
Links updated, thanks Jerry!

**Comment by jerry-ey** [comment]
will work on it

**Comment by jerry-ey** [comment]
updated above bold text, please verify again.

**Comment by ayushdamani** [comment]
Text now bolded, thanks Jerry!

**Comment by fazil-ey** [comment]
I dont see the update <img width="1613" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFo3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebe96398cfc0c2c5160f59b2e11ec0a27e7bd57c/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
@fazil-ey It was some how wiped. I fixed it again and please check again.

**Comment by fazil-ey** [comment]
Can see the changes now, looks good
