### ISSUE TITLE
Update  link for Telework section 8: Occupational Health and Safety - Working Alone call-in procedures

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1584]
Link as was updated when employee reported the issue. The changes were made in both test and dev and are ready for push to prod.

**Comment by chriscaldwell-psa** [comment]
Here is the link that was updated.
https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/work-arrangements/flexible-workplaces/flexible-work-readiness-reflection-and-discussion/safety-inspection#call-in-procedures

**Comment by ayushdamani** [comment]
<img width="1622" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFllQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc603e97f6829eb0dbe2b96eec875ec46315f4ca/image.png" alt="image.png" />

Link successfully updated!

**Comment by Stella-Archer** [comment]
Link works great thanks - ready to deploy

**Comment by Stella-Archer** [comment]
Fabulous work @chriscaldwell-psa Link works great - closing tix
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a23e7412e03210907baac5d5017c9a4f1e369e6b/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
<img width="1449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0VoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03e587747e61b32db624fbc53a281e5d59df6c44/image.png" alt="image.png" />
