### ISSUE TITLE
Mat/Par : Parental Leave – Leave allowance option information content edits

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1585]
Under Parental Leave – Leave allowance option information.

Change to:

If you or you and your partner are NOT taking the full extended parental leave and you choose extended benefits with EI and extended parental allowance, you will not receive the full benefits of EI or the allowance as neither are pro-rated based on the numbers of weeks that you take.  
Here is an example below of how it’s calculated: 
1.	If you take the maximum standard parental EI and standard leave allowance of 35 weeks and assuming that the total allowance you receive in those 35 weeks is $14,351.00 and that your standard parental EI is $668 per week x 35 weeks = $23,380.
2.	If you take extended parental EI and extended leave allowance, your weekly allowance amount would be $14,351.00/61 weeks = $235.26 per week and your extended parental EI is $401 per week.  
3.	If you only take 40 weeks of extended parental EI and extended leave allowance, you will receive $235.26 x 40 weeks = $9,410.40 in allowance and $401 x 40 = $16,040 for extended parental EI. Even though your leave is 40 weeks, the extended parental EI and the extended leave allowance is not prorated over 40 weeks.
4.	In this scenario, you will receive less money overall if you do not take the full extended leave but choose to take extended parental EI and extended leave allowance.  If you took standard parental EI and standard allowance, you would receive the full amount of EI and allowance, but you will be without pay for the last 5 weeks of your parental leave.
5.	
<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a63ef738e1ddbbb2a819b3c9d63b181aa2111290/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
@Stella-Archer  Do we have 5th item for new content? or totally just 4 items.

<img width="1222" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzBlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--315987202c803d89d769c4871053ed56d7a5d251/CleanShot%202024-02-01%20at%2009.02.12%402x.png" alt="CleanShot 2024-02-01 at 09.02.12@2x.png" />

**Comment by chriscaldwell-psa** [comment]
Changes have been made to Blue info box, please confirm if you would like item 5 removed or it it is Ok. 
<img width="1307" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1llQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d30a762dff3e166e994b0729ae6a189135c1c099/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
I will double check with Connie

**Comment by Stella-Archer** [comment]
@chriscaldwell-psa   please remove #5 THX!

**Comment by chriscaldwell-psa** [comment]
@Stella-Archer. Line 5 removed. Dev env has been pushed to test for review. Thanks, C.

**Comment by Stella-Archer** [comment]
Thanks @chriscaldwell-psa looks Deployment ready :)
<img width="1570" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29nQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29b90335e19e2c1db86ef4824c6de5518f9a223e/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
LIVE and perfect closing this
<img width="1488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL29nQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80411cd8b9135f17b853c788898e47e33af0c4f4/image.png" alt="image.png" />
