### ISSUE TITLE
Mat/Par : Parental Leave – Leave allowance dates content edits

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1586]
Under the Parental Leave – Leave allowance dates:

This should be “intend”
<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODRaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3be786827df7a57e40ca2bf9c14c6be989bc50d/image.png" alt="image.png" />

**Comment by chriscaldwell-psa** [comment]
Within the tab: Parental leave - leave allowance dates, the second bullet list has been updated with the word 'intend'
<img width="1711" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFFlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8daf40f681ba7d264d8fb05590bcbc284db9233b/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Perfect - Deploy ready!
<img width="967" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN01nQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aecb915cebc59b343426749ab5f1e56e79dfc0fd/image.png" alt="image.png" />

**Comment by MikePSA** [comment]
tested in PROD, content change is updated correctly. <img width="1359" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzhnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--604185a5320ac311fd7a55165cabe0ce452ec570/image.png" alt="image.png" />
