### ISSUE TITLE
Mat/Par : Supervisor Information content edits

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1587]
Under Supervisor Information tab

This should say “service request”

<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57cf22822616f804f0666507409f9019054de956/image.png" alt="image.png" />

**Comment by chriscaldwell-psa** [comment]
Content change in the yellow alert box has been updated. The word 'ticket' has been replaced by the word 'service request':
<img width="1598" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9lQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cbd9668d4af241ab96d0b4af8638c8542ef8c70d/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Perfect - ready to deploy

**Comment by jerry-ey** [comment]
working in PRD
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3doQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70b12542291d3696c528637cd812f6ba02cc9d58/CleanShot%202024-02-01%20at%2017.52.15%402x.png" alt="CleanShot 2024-02-01 at 17.52.15@2x.png" />
