### ISSUE TITLE
Cold/Flu: Update Cold/Flu Form Title to 2024

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1589]
**User Story**
As an applicant, I want to be sure I am filling out the right form so I can book a clinic for my organization. 

**Tasks**
Change form title from "2023 Influenza Worksite Clinic Registration Closed" to "2024 Influenza Worksite Clinic Registration"
New title should appear in the bread crumbs and in the top bar:
<img width="1321" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVllQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a838be5644de19ccccdd49102effe803761f3b23/image.png" alt="image.png" />

**Acceptance Criteria**
Form title should reflect new year (2024)

**Comment by ayushdamani** [comment]
Please remove "closed" from the title too. Thank you!

<img width="1277" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFFzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--268c4f2ff97202bc7f7b2822ec36df0bfa9317ec/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
Thanks for catching this, updated.

**Comment by ayushdamani** [comment]
<img width="1243" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjRzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94e817fe46f7b81c750dd0a3f92c0814e33e1d84/image.png" alt="image.png" />

Looking good!

**Comment by Stella-Archer** [comment]
Looks Fabulous

**Comment by jerry-ey** [comment]
Looks good, can see the title on PRD

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXdMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03746979a2a3ce7f65e63de11379064d2ae97ae2/CleanShot%202024-03-25%20at%2017.06.00%402x.png" alt="CleanShot 2024-03-25 at 17.06.00@2x.png" />
