### ISSUE TITLE
Cold/Flu: Update data in the ODS with inputs from 2023 campaign.

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1590]
**User Story**
As an applicant, I want to make that I have the most current data about the clinic locations and contacts so I can find my correct address in the form. 

**Tasks**
Get most recently updated data from contractors.
Clean up data.
Update the database in ODS.

**Acceptance Criteria**
2023 Data with additions from the contractor (Healthserv) should be updated in the Data Warehouse

**Comment by DonMoffatt** [comment]
I asked @mikeshitelus to update the worksite table with the information provided to me by Heather Bishop on January 15, 2024.

**Comment by mikeshitelus** [comment]
It is done on ODS TEST Database

**Comment by fazil-ey** [comment]
@Abuchana to tell heather to test the updated data in the test DJ env. If its okay we can ask Mike Shi to push this to prod

**Comment by Abuchana** [comment]
@fazil-ey 
Heather has responded, which dev can help with this?
[1:35 PM] Bishop, Heather PSA:EX
okay hi! 
So I am in test
[1:35 PM] Bishop, Heather PSA:EX
there is nothing (no addresses/worksites) showing in the drop down menu for select your worksite

**Comment by Abuchana** [comment]
Heather has tested and the location information is now in the dropdown menu, however, she has found some errors in the data (unit #s are showing for some locations in the street address). She is updating the spreadsheet and sending it over to Don for him to pass to Mike Shi in order to update the ODS. She will cc Stella to keep her in the loop.

**Comment by Stella-Archer** [comment]
Data cleaning happening with DIO people to take unit # out of street address

**Comment by DonMoffatt** [comment]
> Heather has tested and the location information is now in the dropdown menu, however, she has found some errors in the data (unit #s are showing for some locations in the street address). She is updating the spreadsheet and sending it over to Don for him to pass to Mike Shi in order to update the ODS. She will cc Stella to keep her in the loop.

Heather and I met and we looked at a few examples. I think the Workplace dropdown is not pulling on the unit field when presenting the address choices.  I will contact @mikeshitelus  about that. I will also look at why there are duplicates in the ministry list (which have different worksites associated with them). @Stella-Archer @Abuchana

**Comment by DonMoffatt** [comment]
> @DonMoffatt Wondering, are you going to send us an updated spreadsheet?

Hi Mike - do you need the spreadsheet to make the corrections I just noted, or is it for another purpose?

**Comment by mikeshitelus** [comment]
@DonMoffatt If the corrections only for those Ministry names, it is ok I can make the change now. However, if the corrections also include unit/suite and street number, I guess we need the updated spreadsheet re-loaded.

**Comment by DonMoffatt** [comment]
> @DonMoffatt If the corrections only for those Ministry names, it is ok I can make the change now. However, if the corrections also include unit/suite and street number, I guess we need the updated spreadsheet re-loaded.

I will check the spreadsheet to see if it is complete. Heather identified a couple of missing unit names.

**Comment by DonMoffatt** [comment]
> @DonMoffatt @Stella-Archer @Abuchana
> 
> Ministry names have been updated in ODS, please test.

It looks good. Thanks for your fast action on this, Mike.

**Comment by DonMoffatt** [comment]
@mikeshitelus I am going through the spreadsheet to check on unit name entries with Heather. I will send the updated list when done.

**Comment by mikeshi-bcgov** [comment]
@DonMoffatt 
New excel file received and Worksites table updated on ODS, thanks.

**Comment by Stella-Archer** [comment]
@DonMoffatt could you update this? Thx

**Comment by Stella-Archer** [comment]
Sweet Thanks @DonMoffatt and @mikeshi-bcgov

**Comment by DonMoffatt** [comment]
@mikeshi-bcgov Hi Mike. I'm looking to update a report that is based on Influenzaclinic.[dbo].[vw_registrations] and noticed that the address does not include the unit field. Would you please add it so I can update the subscription report that Heather Bishop needs? [dbo].[worksites] does not contain that field, either (I checked Prod as well).

**Comment by mikeshi-bcgov** [comment]
@DonMoffatt added on DEV, please check.

**Comment by DonMoffatt** [comment]
@mikeshi-bcgov unit_suite - Terrific, looks great.
