### ISSUE TITLE
Cold/Flu: No constraint to the volume of registrations

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1591]
**User Story**
In 2023, we had an influx of registrations on the first day. Many users were then unable to register their worksites. We discovered the form had a capacity limit set. This was increased, and people were able to register again. Want to make sure this doesn't happen again.

**Tasks**
To be decided

**Acceptance Criteria**
Digital Journeys team should confirm the form capacity does not limit the volume of registrations we get in the first few days

**Comment by Stella-Archer** [comment]
we added a load balance and some constraints, will place a loader or time but not prevent access
when load spikes will add new server
no issues with resources anticipated on server but @bhumin-fw will monitor and confirm action on spike

**Comment by Stella-Archer** [comment]
closing
<img width="843" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3417a8809d62199b559b68e2b92a7e5a7cbb2572/image.png" alt="image.png" />
