### ISSUE TITLE
Cold/Flu: A user should be able to register more than one form. 

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1592]
**User Story**
Some worksite contacts oversee more than one worksite. It is best if these contacts are able to register ALL of their worksites, as in 2023 some were missed, and many required manual entry by the Cold & Flu Team. If NOT possible, see below.

**Tasks**
To be decided

**Acceptance Criteria**
A user should be able to register more than one form.

**Comment by ayushdamani** [comment]
*In absence of the above* The form should include text notifying the user that they will need to contact the Cold & Flu Team if they need to register additional worksite(s).

**Comment by ayushdamani** [comment]
"This system only allows for one registration per person. We recommend that each worksite have it's own ON-SITE contact. If you are unable to find a contact to register your other worksites, and you need to register more than one, please email cold.flu@gov.bc.ca for support."

**Comment by Andrew-Vargas-bcgov** [comment]
ready to go on test.
You should be able to submit multiple forms now.

**Comment by ayushdamani** [comment]
Working great!
As a user, I am now able to make multiple submissions!

**Comment by Stella-Archer** [comment]
Yes - I registered 2 sites for AG
I will ask Heather to check as well :)
