### ISSUE TITLE
Cold/Flu: Instructions for adding new worksites and registrations

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1593]
**User Story**
"If you don't see your worksite listed in the drop down menu, or your unit number is not listed as part of the worksite address, then select only your ministry or organization in the drop down, and click the button Don't see your worksite? to create a new entry with your worksite's address"

**Tasks**
To be decided.

**Acceptance Criteria**
Form should include instructions for users who are not able to find their worksite: how they would create a NEW registration and ADD their worksite

**Comment by jerry-ey** [comment]
Stella will put some screenshots if possible. Thanks.

**Comment by jerry-ey** [comment]
Please verify, thanks
<img width="1368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGVJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62916ea47871b4229acdb00f774d8b4f891f0eac/CleanShot%202024-02-23%20at%2012.13.31%402x.png" alt="CleanShot 2024-02-23 at 12.13.31@2x.png" />

**Comment by ayushdamani** [comment]
Looking good, Jerry
Question for @fazil-ey - Does the text 'Don't see your worksite' need to be in inverted commas?

**Comment by ayushdamani** [comment]
Confirmed with Fazil.
@jerry-ey Please add double-inverted commas before and after the text. This is how it should appear please:
"Don't see your worksite?"

**Comment by ayushdamani** [comment]
Can you please include the question mark in the inverted commas?
<img width="275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGVUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa4b7e1225de07141e90497252417dc73453b213/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
please verify again, thanks

**Comment by Stella-Archer** [comment]
Thanks this looks really good to me, @Augusteen-myeong I'm going to approve and close
<img width="1486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHluQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a61822e0cb2118b31055d98310db56190d45dcac/image.png" alt="image.png" />

**Comment by MikePSA** [comment]
Tested in PROD, works fine. Closing.
