### ISSUE TITLE
Cold/Flu: Update text

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1595]
**User Story**
Current text: "If there are plans for your worksite location to change between the time you register and the end of the flu clinic period (December), please select Yes."                                                                                                      
Proposed text: "If there are plans for your worksite location to change between the time you register and the end of the flu clinic period (December), please select Yes, and enter any relevant details in the "Special instructions" box."

**Tasks**
To be decided

**Acceptance Criteria**
Update the text in the (?) pop up for "Will the team be relocating"

**Comment by ayushdamani** [comment]
Text updated. Thanks!

**Comment by Stella-Archer** [comment]
Looks great will get Heather to check as well
<img width="728" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0U4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c5926f216afad6becd8bd5c37ef94958c229efb/image.png" alt="image.png" />
