### ISSUE TITLE
Cold/Flu: Change the default option to "Open"

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1596]
**User Story**
Given the option, many users opted for "Closed" clinics this year when they really should have been open. Would like to make OPEN the default so the user has to select closed if they want that option.

**Tasks**
To be decided.

**Acceptance Criteria**
Make the "Is this an open or closed clinic" box default to "Open"

**Comment by jerry-ey** [comment]
please test, thanks

**Comment by ayushdamani** [comment]
Default option is now "open". Thanks!

**Comment by Stella-Archer** [comment]
Yup - Defaulting to 'Open' will have heather approve as well
<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1E4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b29448fd26f1670ba6f49443984a9922b4e2b71/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
working on PRD
<img width="1031" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b59edda9dfffd6549c47843087571729d05fb25c/CleanShot%202024-03-25%20at%2017.11.46%402x.png" alt="CleanShot 2024-03-25 at 17.11.46@2x.png" />

**Comment by MikePSA** [comment]
Tested in PROD, working great. Closing.
