### ISSUE TITLE
Cold/Flu: Add Functionality to Search Registrations under Submitted Forms Tab.

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1597]
**User Story**
Unfortunately the "Application Name" search bar does not work. Finding an application among over 400 is very difficult. We often used the CTRL+ F feature to try and find them, but again when there are over 400 registrations, this page does not allow us to load ALL submitted forms on one page for viewing.

**Tasks**
To be decided

**Acceptance Criteria**
Admin needs to be able to SEARCH for registrations under the SUBMITTED FORMS tab "Application Name" using the persons first/last name.

**Comment by Stella-Archer** [comment]
@bhumin-fw   is looking for ways to allow search with minimal impact to upgrades

**Comment by bhumin-fw** [comment]
Update it's estimation to 2. It'll require little bit more effort to review migration script and search string update on webapi.

**Comment by jerry-ey** [comment]
ready for review the PR

**Comment by jerry-ey** [comment]
Discussed with @bhumin-fw, 
FYI, this functionality requires to add a hidden field `submissionDisplayName` in the form.
So now it's NOT applying to Telework and SL forms.
Document this info for the future if we want to include Telework and SL.

**Comment by Abuchana** [comment]
As per Stella, not needed in Telework at this time. 
SL may need this but will be revisited in the future if needed.

**Comment by jerry-ey** [comment]
Please test with newly-created form. I will only work for newly-created form.

**Comment by ayushdamani** [comment]
"Application Name" search bar is now working! Thanks :)
Moving to PO

**Comment by Stella-Archer** [comment]
OMG this works GREAT - Thanks for all your hard work on this @jerry-ey 
@Augusteen-myeong I made up a bunch of goofy names you can test on tooo. :)
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0prQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--625f800f302f56a9bd99e53cf9b96c8223608777/image.png" alt="image.png" />
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88c846def16dabad61610cc24580e1451065b284/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Closing PO approved :)

**Comment by Augusteen-myeong** [comment]
@Stella-Archer I don't think I see the submitted forms. How can I access the list? 
![image](https://github.com/bcgov/digital-journeys/assets/159492049/51262b8c-be90-47ff-b48a-cbf1ef864051)

**Comment by Stella-Archer** [comment]
Thanks for testing that @Augusteen-myeong  - I think that means you have general access but not Cold and flu Admin access !!!
 I will ask the dev team to check that tomorrow and try again - will keep you posted!

**Comment by bhumin-fw** [comment]
@Augusteen-myeong I have granted you cold/flu admin access. Now you will be able to see those forms.
cc: @Stella-Archer

**Comment by Augusteen-myeong** [comment]
@bhumin-fw - Thank you. 
@Stella-Archer - I've tested and confirmed search is working as expected. 
![image](https://github.com/bcgov/digital-journeys/assets/159492049/b013bd78-029e-4a24-8488-7811dd6f6ef1)

**Comment by Stella-Archer** [comment]
search Submitted forms works perfect live
<img width="1482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDBMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--415a7d1ac9a99428027878f48905fd4dc37d6ed3/image.png" alt="image.png" />
closing
