### ISSUE TITLE
Cold/Flu: Admin would like to be able to edit a submission once it has been submitted.

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1598]
**User Story**
Unfortunately we were not able to edit submissions (ie. For address changes) when a worksite moved locations. For edits we often had to delete the whole submission and create a new one.

**Tasks**
Please consult Mike Shi.

**Acceptance Criteria**
Admin would like to be able to edit a submission once it has been submitted.

**Comment by mikeshi-bcgov** [comment]
Sorry just see this, will take a look.

**Comment by mikeshi-bcgov** [comment]
@ayushdamani There is a endpoint for editing existing submissions, have you tried?

https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_update_worksite_registration/

https://analytics-api.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_update_worksite_registration/

**Comment by Stella-Archer** [comment]
!/ Assign all forms to Heather allow her to update or submit in review task - ask heather if this is more work that currently - risky bottle neck
2/ Manual code changes - add condition specific group edit form, changes in multiple place If/else not applicable to all users on all forms on list and update submission file

**Comment by ayushdamani** [comment]
We are opting for the second option, out of the two mentioned above!

**Comment by jerry-ey** [comment]
Created the new ticket to track here: https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1652

**Comment by Stella-Archer** [comment]
Yay work great Live :)
<img width="1477" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f15d47923a00a422107dd0320efb10bc3fa24fb3/image.png" alt="image.png" />
<img width="1447" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bb8c9dbab3d5c770535d6446946739e375c27c2/image.png" alt="image.png" />


closing
