### ISSUE TITLE
Cold/Flu: Clean out and delete all old data from 2023

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1599]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
“As the forms owner, I want to remove all data from 2023 so I can get the latest and most updated data.” 

**Tasks**
clean out and delete all old data from 2023

**Acceptance Criteria**
All old data from 2023 should be removed.

**Comment by jerry-ey** [comment]
@Stella-Archer Does this also delete all submitted data?

**Comment by jerry-ey** [comment]
Please check Production directly.

**Comment by ayushdamani** [comment]
All the old data has been deleted - thanks Jerry!
<img width="1638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--553a7b430216087ce11648b4b498f07056af19ff/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Yes Looks good to me too
@Augusteen-myeong I'm Approving and closing
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDJuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf4607a489d65cfd9775101cf5babd2bc4739f51/image.png" alt="image.png" />

**Comment by Augusteen-myeong** [comment]
@Stella-Archer  - I only have access to the testing environment (https://digital-journeys-test.apps.silver.devops.gov.bc.ca/application). Can I have access to PROD for testing?
