### ISSUE TITLE
Mat/Par: Add bullet point

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1606]
**User Story**
Adding this bullet point would bring clarity for all applicants.

**Tasks**
Please add bullet point to "Parental leave - General information" tab - 

> Employees can request to use earned vacation before or after their parental leave to extend their time off work. Request the leave through [Employee Self Service](https://timepay.gov.bc.ca/) (or [if working from home](https://timepayhome.gov.bc.ca/)). If you do not have access to ESS, fill out the [leave management transaction form](https://www2.gov.bc.ca/assets/download/A53FAC45E03348B3BB3A1D90059E4E09) and send it to your supervisor who should submit it through [AskMyHR](https://www2.gov.bc.ca/gov/content/careers-myhr/bcpsa/contact-the-bc-public-service-agency) under _My Team or Organization > Leave & Time Off > Vacation & Holidays_

Please add it here:
<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3NxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea929dfdb21f2b39a433fca69aa77a85c95813fe/image.png" alt="image.png" />

Also, please make sure that this is only visible when someone is taking parental leave.

Next, add a blue alert box on the same page: 

> You may be eligible to take up to two days of leave for the birth of your child, from the period beginning with the onset of labor up to the time when the birthing parent and child return home. Please refer to your [collective agreement](https://www2.gov.bc.ca/gov/content/careers-myhr/managers-supervisors/employee-labour-relations/conditions-agreements/collective-agreements) or the [terms and conditions for excluded employees and appointees.](https://www2.gov.bc.ca/gov/content/careers-myhr/managers-supervisors/employee-labour-relations/conditions-agreements/excluded-employees-appointees)

**Acceptance Criteria**
- [ ] Bullet point added with the correct text and links 
- [ ] Blue alert box added with the correct text and links

**Comment by ayushdamani** [comment]
Fazil will work with Connie for some clarifications!

**Comment by ayushdamani** [comment]
Changes are up in TEST and DEV :)

**Comment by fazil-ey** [comment]
@ayushdamani can you change the AskMyHR path to italics "_My Team or Organization > Leave & Time Off > Vacation & Holidays_"

and i think there is a grammar mistake so lets change the first sentence of the blue box to 

"You may be eligible to take up to two days of leave for the birth of your child, from the period beginning with the onset of labor up to the time when the birthing parent and child return home."

**Comment by ayushdamani** [comment]
Requested changes are up in TEST and DEV :)

<img width="1310" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e672e78af014113cf0ac35c13a2f4c9e03477bfa/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
@ayushdamani the blue box is in the wrong page. it should be Parental leave - General informatio

**Comment by ayushdamani** [comment]
My apologies! I do not know what glitched - fixed it

<img width="1243" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0pDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b00c8e20d03800aaa65a8d5262c583afdc17604/image.png" alt="image.png" />
----------------------------------------------------------------------------------------------------------------------------
<img width="1373" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK05DQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b54b2d94bd31e1558c794800ce5b33d1f4a2dc0/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good

**Comment by fazil-ey** [comment]
@ayushdamani can you cange the note to say this instead 

"You may be eligible to take up to two days of leave for the birth of your child, from the period beginning with the onset of labor up to the time when the birthing parent and child return home. Please refer to your collective agreement or the terms and conditions for excluded employees and appointees. 

Also note that this extra two-day leave is separate and in addition to your parental leave. If eligible, you can apply for it through [Employee Self Service](https://logon7.gov.bc.ca/clp-mp/ntlm.cgi?flags=1000:1,0&partner=fed42&TYPE=33554433&REALMOID=06-73702074-5cf7-471a-b875-b5df824be782&GUID=&SMAUTHREASON=0&METHOD=GET&SMAGENTNAME=$SM$ui%2fRndhXA8ldRn5B9ReEwVkGRBcDALmClZno3VcOtuEOnKpNicqvuSLNYu9aOFRi&TARGET=$SM$https%3a%2f%2ftimepay%2egov%2ebc%2eca%2f) (or if [working from home](https://timepayhome.gov.bc.ca/)) or let your supervisor know."

**Comment by ayushdamani** [comment]
Updated!

<img width="1549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFJEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b53eb482f0352f5ee5b1be82583da27ef84e4c9/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
sweet - let's deploy this baby

**Comment by MikePSA** [comment]
It looks like according to Fazil's message above, "collective agreement" and "terms and conditions for excluded employees and appointees" in the info box should be hyperlinked to the respective website. Needs to be fixed in PROD.

**Comment by Stella-Archer** [comment]
Bullet in 'Before you begin' messaging looks good in PROD
<img width="989" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHhEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ce00e715ca25bf6842c206596938a8af4fbc07f/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Parent leave information looks good too - PO and closing
<img width="830" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDVEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f741f5e8167ce29aef3c0b565ddac18baa6aa514/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
1. Collective agreement Link to > https://www2.gov.bc.ca/gov/content/careers-myhr/managers-supervisors/employee-labour-relations/conditions-agreements/collective-agreements
2. <img width="830" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWxEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad5c19404ec2d1eaefa30db9a0570dc3b9a333e4/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
2.  terms and conditions for excluded employees and appointees Link to >  https://www2.gov.bc.ca/gov/content/careers-myhr/managers-supervisors/employee-labour-relations/conditions-agreements/excluded-employees-appointees

**Comment by Stella-Archer** [comment]
<img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca8ad29b409bad0264b57a2c5ef0fd534eb1b109/image.png" alt="image.png" />
YAYAYAYYAYAYYAY - PO and closing!
