### ISSUE TITLE
Cold and Flu : Update success message to 2024

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1613]
**User Story**

“As a clinic registrant, I want to see '2024' in my success message (NOT 2023) so I can feel confident I've registered for the current cold season clinics .” 
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3M4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b8f57ebc2eebb3caada8b2c3f7a3b005ab48cc0/image.png" alt="image.png" />

**Tasks**
Edit Message title 
from: Thank you for registering your worksite for the **2023** Cold and Flu Program
To:  Thank you for registering your worksite for the **2024** Cold and Flu Program

**Acceptance Criteria**
Success message title reads:
Thank you for registering your worksite for the **2024** Cold and Flu Program

**Comment by ayushdamani** [comment]
Updated wording from 2023 to 2024! Thanks :)
Moving to PO.
<img width="938" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjVVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc8318a32b25563ed19429f6f517cf3e2798a0b4/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Perfect - Closing Tix 
@Augusteen-myeong let me know if you can see the update as well
https://digital-journeys-test.apps.silver.devops.gov.bc.ca/form/641b44c5bddb37f24587dcf3

**Comment by Augusteen-myeong** [comment]
@Stella-Archer , I've confirmed that the text is updated to "2024"
![image](https://github.com/bcgov/digital-journeys/assets/159492049/ecaafe9f-e96f-4f3f-a2f0-233fe5ae8b6d)

**Comment by jerry-ey** [comment]
I can see "2024" in PRD

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da2d4d349246c44e4408634b1d7ad2898e833df3/CleanShot%202024-03-25%20at%2017.56.20%402x.png" alt="CleanShot 2024-03-25 at 17.56.20@2x.png" />

**Comment by MikePSA** [comment]
Tested in PROD, looks good. Closing.
