### ISSUE TITLE
Upgrade to the latest version of forms-flow-ai - Merge Jul 20,23 onword changes

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1616]
Upgrade to latest AOT version 5.1.1 was started in May 2023. Detail about new features are there on ticket [#951](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/951).

Writing up this ticket to continue that work and finalize upgrade with latest branch. We need to fix version upgrade of underhood packages on each services which align with 5.1.1 version on AOT.
Merge latest changes from 20th Jul till today for all below listed services. Including Digital journey requirements and customization + AOT 5.1.1 version related updates (which are commented out for Helm chat deployment Testing)
- WebAPI
- Camunda / BPM
- FormIO
- Document services
- Frontend WEB

**Comment by bhumin-fw** [comment]
Hi team, 
Version upgrade deployed on new name space.
https://helm-digital-journeys.apps.silver.devops.gov.bc.ca/form
Please connect with any Dev to get login credentials. I have shared those on team with Developer group.

Progress: 
I'll continue work on upgrade and fix remain conflict and feature merge with version 5.1.1 from AOT.

Note: Kunal is working on deployment issue with web code. I'll keep posted on his progress here.

**Comment by MeghanStothers** [comment]
@Stella-Archer can you confirm what new features this application upgrade will bring? This information was requested for exec reporting. Thanks

**Comment by Stella-Archer** [comment]
K. @MeghanStothers  do you need it for tomorrows report?

**Comment by MeghanStothers** [comment]
Here's a link to the release notes with a list of features: https://formsflow.ai/category/release-notes/
@Stella - can you confirm which version the team will upgrade? Is it 51.1 as above or will the devs upgrade the application to 5.2?

**Comment by bhumin-fw** [comment]
@Stella-Archer @MeghanStothers 

Some of the new features are:
- Most of the dependencies (packages and libraries used under the hood) will be updated. This will check many security vulnerability boxes and will bring better performance among other things.
- Added form versioning
  - Allow forms to be versioned. This will allow us to track and manage form versions. Also, a form designer can decide if the updated form (the last version of the form) should be effective for all the in-progress submissions or only new ones.
- Draft discard
  - We already have this feature, but opt-in for the form-flow-ai implementation would allow easier future updates and better maintenance. 
- PDF templating
- Document services
  - From the document service, we are using PDF generation and attachment in an email.
- Added form embedding
  - This will allow embedded DGJ in another website. Can be useful if a client wants to include a DGJ (which has their form) in their own website

**Comment by bhumin-fw** [comment]
@MeghanStothers We are upgrading it to 5.1.1

**Comment by MeghanStothers** [comment]
Thanks - I've got my answer: 51.1 - thanks!

**Comment by Stella-Archer** [comment]
All changes are good and have updated to latest version 5.1.1 :)
