### ISSUE TITLE
Mat/Par - Subheadings in Before you begin

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1621]
Add subheading to before you begin to make it easier to read and give a quick overview of the kind of information being provided.

<img width="1944" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3RWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c057fc6fe9f2853e7b76037568a1cfae9786d130/Screenshot%202024-02-13%20at%209.46.59%20AM%20copy.png" alt="Screenshot 2024-02-13 at 9.46.59 AM copy.png" />

**AC**
- [ ] Add subheadings as per the screenshot above. Move the policy points in one section

**Comment by ayushdamani** [comment]
Changes are up in TEST and DEV :)

**Comment by fazil-ey** [comment]
@ayushdamani  while we are at it lets change the point in After submission to 

"After you submit, your supervisor will receive an email informing them about your form submission."

**Comment by fazil-ey** [comment]
looks good

**Comment by MikePSA** [comment]
Tested in PROD, looks good. Closing.
