### ISSUE TITLE
Mat/Par - Add link to link to the TD1 form in email to applicant after approval

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1622]
Add link to link to the TD1 form in email to applicant after approval

**AC**
- [ ] Add the link as shown in the following point in email sent to applicant after supervisor approval

> Income tax is deducted from maternity/parental leave allowance and EI payments — you may want to discuss your personal tax situation with an independent financial adviser.
> You can choose to have additional taxes deducted to cover the income earned from both sources. Submit a [federal TD1 form](https://www.canada.ca/en/revenue-agency/services/forms-publications/td1-personal-tax-credits-returns/td1-forms-pay-received-on-january-1-later/td1.html) through an AskMyHR service request using the categories Myself (or) My Team or Organization > Submit a Form or Document > Direct Deposit/Tax Forms (TD1).

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey do you want the last paragraph in the ticket to be a bullet point too?
Lastly, do you want this to go at the end of the email, above the "NOTE"?
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9BQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58c50761fb8eb0e87de7ce1c7ea07a5c84498154/image.png" alt="image.png" />

**Comment by Andrew-Vargas-bcgov** [comment]
This is complete, just waiting on 1625 feedback to combine into new dmn.

**Comment by Andrew-Vargas-bcgov** [comment]
complete

**Comment by fazil-ey** [comment]
this looks good

**Comment by bhumin-fw** [comment]
@Andrew-Vargas-bcgov It seems we have updated this change on production as well?
Could you please re-verify it and add po-approve tag, assign release and close this ticket.

**Comment by Andrew-Vargas-bcgov** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0RJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--907c8dd004ff5cd652432b9cd04e601ecdf2e006/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Sweet looks great!
