### ISSUE TITLE
Mat/Par - UX Improvement - Coming early or extending leave 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1625]
Add information about coming early or extending maternity/parental leave in the email send to applicants on approval

 - To be sent to all applicants on approval 
 
Copy 

> - Returning early or Extending leave 
>     - You must also inform your supervisor if - 
>         1. You’re requesting an extension to your leave, and you have not taken the maximum parental leave and extended childcare leave (combined maximum of 78 weeks total).
>         2. You’re wanting to return earlier than the date you indicated on your digital application.
>      - Ask your supervisor to submit an [AskMyHR](https://www2.gov.bc.ca/gov/content/careers-myhr/bcpsa/contact-the-bc-public-service-agency) service request for "My Team or Organization" under the following category "Leave & Time Off > Maternity, Parental, Adoption" advising that you are returning early or extending your leave. AskMyHR will process the request and confirm.

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey do you want the last paragraph in the ticket to be a bullet point too?
Lastly, do you want this to go at the end of the email, above the "NOTE"?
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9BQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58c50761fb8eb0e87de7ce1c7ea07a5c84498154/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov  above NOTE 

I have updated how the bullet points should be. It should go as the last bullet point with sub points

**Comment by fazil-ey** [comment]
hey @Andrew-Vargas-bcgov can you change the last bullets to include. main bullet like so - ( for some reason Zenhub is showing this in the preview but not updating the ticket to reflect the change)
<img width="1204" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzdJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3988a9febb6edde3530bfbbdb5aefd54f52773c/image.png" alt="image.png" />

**Comment by Andrew-Vargas-bcgov** [comment]
<img width="1769" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2JJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--545d8505fea41ba4d06829123bd111151266ba1a/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
thx @Andrew looks good!

**Comment by fazil-ey** [comment]
I do not see this in the latest emails. Has this been released?

**Comment by fazil-ey** [comment]
Getting the content in the emails
