### ISSUE TITLE
Mat/Par: Supervisor to be notified for all updates and re-submissions

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1628]
**User Story**
One of our first people to submit the application form has advised that he is trying to submit his application form to his supervisor and it's not working again.  He is not receiving the emails not but he was previously.

Bhumin adds: In case of resubmission, there is email sent out to the employee and supervisor

**Tasks**
TBD

**Acceptance Criteria**
Each time an employee submits an update, the supervisor needs to be notified. Andrew is already working on it.

**Comment by ayushdamani** [comment]
Tested in TEST - as an employee, I changed dates in my form. As an employee, I received an email for the change made to that form.
Moving to PO!

**Comment by fazil-ey** [comment]
both employee and supervisor getting emails on update, looks good!

**Comment by bhumin-fw** [comment]
@Stella-Archer @fazil-ey It looks good on prod, but it does not have "po-approved".
can we add that tag and close it ?
