### ISSUE TITLE
Add a new sub-Ministry as an option for Ministry Housing - Telework

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1630]
As a user I would like to select a ministry called "**Ministry of Housing"** from the drop down ministry component on the telework form.  This would be separate form the current "Attorney General and Minister or Housing" selection that is already available to choose from. 

Original Email received on Feb 14:
I’m inquiring on behalf of my ministry to see if we can have a separate “Ministry of Housing” selection added to the drop down for organization on the 
digital telework agreement page.  We’d like to have the current “Attorney General and Minister for Housing” selection separated into the two distinct ministries.

Please let me know if you require anything additional from us to complete this change.

**Comment by Stella-Archer** [comment]
Please reach out to the BI team before you add new ministry

**Comment by Andrew-Vargas-bcgov** [comment]
sent myHR request to BI team to discuss if this would be okay.

**Comment by Andrew-Vargas-bcgov** [comment]
BI Team confirmed changing ministry info won't impact reporting. 

Confirming with Meghan on ministry scope and then will request updated ministry name list.

**Comment by MeghanStothers** [comment]
Here is the link to the bc gov ministries, which also shows the ministries listed separately: https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries

I also looked on the BI analytics dashboard (Stella also has access) and see those ministries (AG and Housing) are separated in the reporting.

@Stella I'd go ahead and make that change and make sure the team has an updated ministry spreadsheet in its files with a "last updated" date"

**Comment by ayushdamani** [comment]
Small request -
The dropdown menu shows "Housing", can you please change it to "Ministry of Housing"?
Attorney General looks good

<img width="778" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a273f6624d66327175b6305eed7fa9d1178bda9a/image.png" alt="image.png" />

**Comment by Andrew-Vargas-bcgov** [comment]
@ayushdamani none of the other ministries are prefixed with "Ministry of". Are you sure we should make this change?

**Comment by Stella-Archer** [comment]
No please keep consistent

**Comment by ayushdamani** [comment]
Awesome - thank you Stella and Andrew!

**Comment by Stella-Archer** [comment]
Thanks this looks really great.
ticket is ready for next deployment

**Comment by Stella-Archer** [comment]
Sent through and sent a note to Sarah M to check for it in BI on Monday
