### ISSUE TITLE
Mat/Par - Add total amount EI + allowance in calculator

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1631]
In the allowance calculator, we could also include total amount - EI + allowance, as in real life most people will do that anyway as that is the total amount of money they will be earning. Will save people that extra step of adding those 2 numbers up. 

**AC**
- [ ] Add total amount in the calculator for both maternity and parental allowance calculators 
        Field label should be  - Estimated total weekly earnings (gross) i.e. leave allowance + EI 

**_Design_**
<img width="1456" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekdJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--396ce89184bd03aa265ee804bad2cb326b1a265d/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Tested in TEST

Maternity calculator looks good

For Parental - 
<img width="1369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekV4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--884ecff6a64a53aef4d6fc547d04bca84dafd555/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good

**Comment by MikePSA** [comment]
Tested in PROD, looks good. Closing.
<img width="1361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGxEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30dbbe3fd4113a3ec6c9f1c6fa4235cd1d5e3230/image.png" alt="image.png" />
<img width="1349" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHBEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e1b1a8785f3b1b5063ec92a21ead8ddb0974ce9/image.png" alt="image.png" />
