### ISSUE TITLE
1.10 - Recipient changes

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1635]
We need to make a change to the 1.10 form, regarding how the “Recipient” section is handled.  For LDB, we would like it left as-is, as LDB staff generally know who to send their complaint to. In the case of PSA, some Complainants are sending the form to the wrong person, thereby creating more work for PSA staff, as well as possible privacy breaches.  As such, we would like the following changes, for PSA submissions only:

o  Allow the Complainant to specify who they want to send the form to (the Recipient) but **do not automatically email the Recipient** a copy of the complaint when they hit submit.

o  Change the wording in the Recipient section (PSA-only version of the form):

From: (Current PSA Wording on 1.10 Designated Form)

> Recipient of written complaint – contact information
> The person to whom you are submitting this written complaint. This complaint should be directed to your supervisor or first level of excluded manager (unless the complaint is about them), in which case give the contact information for the first level of excluded manager not involved in the complaint.

To: (Proposed PSA Wording on 1.10 Designated Form)

> Recipient of written complaint – contact information 
> The person who you want to help resolve this complaint. This would normally be your supervisor or first level of excluded manager (unless the complaint is about them), in which case give the contact information for the first level of excluded manager not involved in the complaint. The Public Service Agency will confirm this is an appropriate Recipient and will provide them a copy of your complaint, so resolution discussions can begin.

**AC**
- [ ] Automatic emails to recipients after submission are stopped
- [ ] Copy for "Recipient of written complaint – contact information" is updated as described above

**Comment by fazil-ey** [comment]
Hey @Andrew-Vargas-bcgov
For a LDB complaint, the text should remain the same as it is:
“When you submit your complaint, it will be automatically sent to you, to the recipient, and to the Director of Investigations & Intake, Public Service Agency (PSA), who will provide a copy of your complaint to your union within 10 days”

For a PSA complaint, the text should be changed to:
“When you submit your complaint, it will be automatically sent to you and to the Director of Investigations & Intake, Public Service Agency (PSA), who will provide a copy of your complaint to the recipient and to your union within 10 days”

**Comment by ayushdamani** [comment]
Looking good!

<img width="1545" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2FOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15b136ad8ade39aec3f11ad66a005f20039e84ee/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
Works well, will share with Don

**Comment by Stella-Archer** [comment]
this has been resolved and is Live - Closing tix
