### ISSUE TITLE
Mat/par: Add email extension to give access to mat/par application form 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1637]
As a member of Attorney General, I will need to have my supervisor approve my application so I can submit a maternity/parental leave and allowance application for approval. 

A/C
Add email extension "trustee.bc.ca"

**Comment by Andrew-Vargas-bcgov** [comment]
added "trustee.bc.ca" to supervisor accepted domains list.
There is currently no validation on employee email, do we want to add the same restrictions as supervisor email?
Should i also add "trustee.bc.ca" to partner's email domain list?

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov Yes, add trustee.bc.ca to partner's email domain list. 
I don't think employee email needs any validation as i think we have a list of domains we DON'T want to allow already in keycloak

**Comment by fazil-ey** [comment]
trustee.bc.ca added

**Comment by fazil-ey** [comment]
This was hotfixed

**Comment by fazil-ey** [comment]
This was hotfixed
