### ISSUE TITLE
Change formsflow.ai  + logo on browser to "Digital Journeys" instead of formsflow.ai

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#164]
As per the client's requirements, we need to change formsflow.ai  + logo on browser to "Digital Journeys" instead of formsflow.ai.

*Acceptance Criteria*
- The browser tab name when visiting the application in the dev + test environment is "Digital Journeys" instead of Formsflow.ai
![image.png](https://images.zenhubusercontent.com/61df28f84562db4e4d8e63d1/52c67faf-edcd-4d27-9d1b-f5b8f7ce07ae)

**Comment by Stella-Archer** [comment]
Not visible in DEV
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/fe37e41d-68b8-4f19-8661-c9403ecc1c5d)

**Comment by Stella-Archer** [comment]
or TEST
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/4ec2ee44-54d5-454c-be69-b357d41f0e92)

**Comment by Stella-Archer** [comment]
or PROD
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/ef85b750-c8aa-4bab-9759-ed417093aa51)

**Comment by david-sabadash** [comment]
Does not include the navigation bar logo change - see https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/bcgov/digital-journeys/336

**Comment by MeghanStothers** [comment]
Alex tested in Dev, to test in Prod and Test

**Comment by Stella-Archer** [comment]
The favicon is correct in DEV but not in TEST
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/22597918-8364-4c7c-b138-092235d11174)
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/7e0ce881-edd0-49c9-9c60-86d635861b54)

**Comment by HasanSifat** [comment]
Tested Successfully in PROD

Ready to be closed
