### ISSUE TITLE
Mat/Par - Add Employee id & Department ID in pdf

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1640]
TES employees prefer to use the PDF for their processing. 
The current PDF does not include employee number. They also need department ID which is missing in the form. 

**AC**
- [ ] Add department id in the employee information section, pdf and CRM ticket
- [ ] Add employee id in the pdf in employee information section. It should be hidden in the form itself.
- [ ] Add this to the Confirm your information section 

> 4. For Department ID: Ask your supervisor to submit an _AskMyHR Request under PSA > Supervising and leading people > Employee status change_ 

- [ ] Add tooltip (?) with the following instruction for department ID 
> You can find your Department ID in your pay stub

**Comment by ayushdamani** [comment]
Tested with Andrew in TEST 
Employee id and department id are now available in the PDF ✅

**Comment by fazil-ey** [comment]
Hey Andrew a couple of things
1. make this " _AskMyHR Request under PSA > Supervising and leading people > Employee status change_ " italics in the content
2. As discussed with Connie, add a tooltip for department id field in the form 
> You can find your Department ID in you payslip

**Comment by MeghanStothers** [comment]
Meghan sent note to Connie asking to review and update the PIA if needed.

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey super easy. I'll fix that this morning.

**Comment by ayushdamani** [comment]
Gap in the PDF is now fixed - thanks Andrew!

**Comment by fazil-ey** [comment]
looks good!
