### ISSUE TITLE
The web app deployment in e66ac2-test is not picking up the latest image changes/builld

### ISSUE THREAD

**Issue by kkapoor-fresh** [bcgov/digital-journeys#1641]

**Comment by kkapoor-fresh** [comment]
@bhumin-fw I have fixed the issue with the web app deployment. The deployment seems to be picking up the latest image for the web pod .Please run a test at your end and let me know.

<img width="1072" alt="image" src="https://github.com/bcgov/digital-journeys/assets/77285719/3dfade07-c9f2-464f-92a0-54f8f8b9060c">

@Abuchana

**Comment by bhumin-fw** [comment]
@kkapoor-fresh tested it, works fine.
