### ISSUE TITLE
Cold/Flu: Email subject should read “Registration for the 2024 Worksite Influenza Vaccination Program”

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1645]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
“As a user when I register a new worksite, the confirmation email's subject line should read “Registration for the 2024 Worksite Influenza Vaccination Program”

**Tasks**
TBD

**Acceptance Criteria**
Email subject line after worksite registration should read “Registration for the 2024 Worksite Influenza Vaccination Program”

**Comment by ayushdamani** [comment]
Thanks Jerry!

<img width="735" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGZIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eae6b619e8580b80705fd83c7ca969b6eb15f4ab/image.png" alt="image.png" />

**Comment by Augusteen-myeong** [comment]
@Stella-Archer - Received the confirmation email with the subject line "Registration for the 2024 Worksite Influenza Vaccination Program"
![image](https://github.com/bcgov/digital-journeys/assets/159492049/6b7d22ab-5d6e-46d2-80e9-97820d4b78b6)

**Comment by Stella-Archer** [comment]
Terrific - PO approved and closing tix!

**Comment by Stella-Archer** [comment]
It's live looks great - closing
<img width="1010" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUFMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2101ceb916d855ebd390dcb2a1eecef23436ff9d/image.png" alt="image.png" />
