### ISSUE TITLE
Cold/Flu: Update text in email

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1646]
**User Story**
As a user I want to see the updated name of the form, once I have registered a new worksite.

**Tasks**
TBD

**Acceptance Criteria**
Highlighted text should read “Worksite Influenza Vaccination Program”

<img width="1125" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGlOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de8a39370d49ee5a088fd712db0c9fe5576f67a4/Screenshot%202024-02-26%20104326.png" alt="Screenshot 2024-02-26 104326.png" />

**Comment by ayushdamani** [comment]
Looking good, thanks Jerry!

<img width="1275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN202QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--145c41b92a410cad00b717d4e0d98a77e5a7b3cf/image.png" alt="image.png" />

**Comment by Augusteen-myeong** [comment]
I've confirmed that the subject for email notification after submitting a form is updated to include “Worksite Influenza Vaccination Program” 

[Before updating] 
![image](https://github.com/bcgov/digital-journeys/assets/159492049/ed3df097-0883-4c6e-b7c4-a8e98bb8d322)

[After updating]
![image](https://github.com/bcgov/digital-journeys/assets/159492049/38aa1da1-2d59-4d00-9782-554b066328d0)

**Comment by Stella-Archer** [comment]
Terrific closing ticket

**Comment by Stella-Archer** [comment]
email from live form looks great - reclosing ticket
<img width="1010" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelVMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--daeaaf95209d4e20fb9dffbce3f786bd8d31ce4a/image.png" alt="image.png" />
