### ISSUE TITLE
Cold/Flu: Update text in email

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1647]
**User Story**
As a user, I want to see updated details of my submission, once I have registered my worksite.

**Tasks**
TBD

**Acceptance Criteria**
1. Highlighted text should read “Influenza supports for BC Public Service employees” 
2. Please hyperlink this text as “Influenza supports for BC Public Service employees page”. Here is the permalink: https://www2.gov.bc.ca/gov/content?id=F984C626E4814C69B14DA210716F170F

<img width="1125" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc9cf9077c5827a45ea8bf1defad8a58e7d64ae6/Screenshot%202024-02-26%20104326.png" alt="Screenshot 2024-02-26 104326.png" />

**Comment by ayushdamani** [comment]
Looking good, thanks Jerry!

<img width="1275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3E2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2ce94c120dd58ef3de05b5881625bad7db9f0f4/image.png" alt="image.png" />

**Comment by Augusteen-myeong** [comment]
@Stella-Archer @ayushdamani - Sorry I am not sure what I am supposed to see. After registering a new worksite, I only see this page without “Influenza supports for BC Public Service employees”
![image](https://github.com/bcgov/digital-journeys/assets/159492049/b31029c7-61d7-40b5-bdfe-b75540ca24f6)

**Comment by Augusteen-myeong** [comment]
I've confirmed that the hyperlink in the email is updated to “Influenza supports for BC Public Service employees” and pointed at https://www2.gov.bc.ca/gov/content?id=F984C626E4814C69B14DA210716F170F

[Before updating]
![image](https://github.com/bcgov/digital-journeys/assets/159492049/f7368040-dc1c-46f0-ad94-bb9b87085316)

[After updating] 
![image](https://github.com/bcgov/digital-journeys/assets/159492049/f79f7ffd-9811-410e-94fc-0ad4faf06208)

**Comment by Stella-Archer** [comment]
Sweet PO approved and closing TIX!

**Comment by Stella-Archer** [comment]
Perfect reclosing
<img width="1010" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBellMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28dafa5701f9592accfb1c3a2ac6cd32b2e4a2e5/image.png" alt="image.png" />
