### ISSUE TITLE
Cold/Flu: Update broken hyperlink

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1648]
**User Story**
As a user, I want to be able to go to Careers & MyHR from the hyperlink provided in the email. 

**Tasks**
TBD

**Acceptance Criteria**
Hyperlink on highlighted text is broken (404). Remove hyperlink from “Careers & MyHR”. Add the new hyperlink.

<img width="1125" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e26a396255d8e41c891bf7f312ddaa2cd2cdd6ac/Screenshot%202024-02-26%20104326.png" alt="Screenshot 2024-02-26 104326.png" />

**Comment by Stella-Archer** [comment]
This link is broken as it is not live YET ask @Augusteen-myeong could you check with Heather about plans for link on site during registration period?

**Comment by Augusteen-myeong** [comment]
@Stella-Archer - I cannot open the screenshot. I'm getting "Non-Image content-type returned" error message. 

Do you want me to ask Heather when she would like to start posting and advertising the hyperlink on Careers & MyHR?

**Comment by jerry-ey** [comment]
@Augusteen-myeong 
Could you please ask Heather for the correct link?

The existing Careers & MyHR hyperlink https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/safety-health-well-being/health/cold-flu is broken.

**Comment by Stella-Archer** [comment]
the link from last year is in the QA > https://www2.qa.gov.bc.ca/gov/content/careers-myhr/all-employees/health-safety-and-sick-leave-resources/health/cold-flu
I imagine it will be the same this year (w/o the qa. ) - with content /date updates

**Comment by Augusteen-myeong** [comment]
> This link is broken as it is not live YET ask @Augusteen-myeong could you check with Heather about plans for link on site during registration period?

@Stella-Archer - **June 10th** will be the go-live date. 

Fazil, Mike Don to confirm the testing timeline: 
- Mar 20th - Development complete
- Mar 21st to Mar 29th - End to End test 
  - Is a week for E2E enough? 
  - Could we be more agile and fix issues during the E2E test period? (Stella: I see this being more iterative)
- Apr 2nd to Apr 10th - fixing issues found in E2E test, Heather on vacation (Stella: May take longer depends on scope of issues identified)
  - if not agile approach
- May 20th - Compass article for information ( no link available yet )
- June 3rd - Deploy PROD, Link to the PROD is available for admins
- June 10th - Cold/Flu registration form is available and open for employees

**Comment by Augusteen-myeong** [comment]
@jerry-ey @Stella-Archer  

The Careers & MyHR Page where Heather will be making changes to and adding the link to the form will be this one
- Influenza Supports for BC Public Service Employees
- https://www2.gov.bc.ca/gov/content?id=F984C626E4814C69B14DA210716F170F                                                                                                                                                                                                                                           

The page and program are likely going to go through some changes in the coming months.

**Comment by jerry-ey** [comment]
@Augusteen-myeong We did have "Influenza Supports for BC Public Service Employees". What we really need here is the link to `Careers & MyHR`. Could you please provide it?

<img width="1258" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFhVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7689e2cbbaf86aba5440e89da66c895a60f7284c/CleanShot%202024-03-12%20at%2010.26.28.png" alt="CleanShot 2024-03-12 at 10.26.28.png" />

**Comment by Augusteen-myeong** [comment]
@jerry-ey - I might have misunderstood your question. This is the URL for Careers & MyHR. Let me know if you need anything else. 
- https://www2.gov.bc.ca/gov/content/careers-myhr

**Comment by jerry-ey** [comment]
@Augusteen-myeong The existing link Careers & MyHR is https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/safety-health-well-being/health/cold-flu

Could you please confirm we need to change to the one you provided above https://www2.gov.bc.ca/gov/content/careers-myhr? Or this existing link  https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/safety-health-well-being/health/cold-flu needs to be fixed?

**Comment by Stella-Archer** [comment]
Jerry link to: 
https://www2.gov.bc.ca/gov/content?id=F984C626E4814C69B14DA210716F170F
The link is not live now but will be when we launch
Currently it's in QA, Heather will work with the web people to make changes to the web page before launch but 99% it will be the same GUID/URL when we launch. 
If you are logged in w/IDIR you can see it in the website QA as it is now https://www2.qa.gov.bc.ca/gov/content?id=F984C626E4814C69B14DA210716F170F

**Comment by jerry-ey** [comment]
@Stella-Archer  Sorry, it's a bit confused now. Please see the screenshot.
We did have "Influenza Supports for BC Public Service Employees" pointing to https://www2.gov.bc.ca/gov/content?id=F984C626E4814C69B14DA210716F170F

Currently, it's the Careers & MyHR broken https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/safety-health-well-being/health/cold-flu.

<img width="1253" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHpVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a25349b80b967dec06d84cf7d4283ccff25831d5/CleanShot%202024-03-12%20at%2011.24.41.png" alt="CleanShot 2024-03-12 at 11.24.41.png" />

**Comment by jerry-ey** [comment]
@Stella-Archer  should we point "Careers & My HR" at https://www2.gov.bc.ca/gov/content/careers-myhr ?

**Comment by Stella-Archer** [comment]
Having the second link point to somewhere else make it super confusing for users we should remove the second link and just point to specific page

**Comment by jerry-ey** [comment]
I have removed the second link.

**Comment by fazil-ey** [comment]
The work is done, link is updated, when the page goes live the link will work
