### ISSUE TITLE
Mat/Par Parental Calculator  - Standard, Extended Math  - Misinterpretation of selection

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1649]
CRM Ticket came for this Mat/Par issue, please read below re Mat Par Calculator: 

Hi there, 

I've been running numbers through the digital journeys parental leave calculator to determine whether standard or extended leave is better for me. I think there is an error in the way the extended leave is calculating the allowance though, when calculating for extended leave, the allowance amount is more than when calculating for standard leave.  

When multiplying this across the benefit weeks for each option, the result is that I would receive 9170.17 more in allowance if I took extended leave, which I assume is not the case and the amount paid for standard should just be prorated across the 61 weeks. Is this correct? In that case I'd expect my allowance should be 137.04 weekly for extended.  Please see attachments for my calculations. 

Please let me know if I'm understanding correctly, or if the allowance really is more overall for extended leave. 

Thank you!

Attachments<img width="1088" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHVUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a89c0512751da8d5760080690ff68c600da2fa6/Ticket1649Att1.JPG" alt="Ticket1649Att1.JPG" />
:

<img width="1273" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHlUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c573ce9420921d5ed5ee393034edd7e3eb23791a/Ticket1649Att2.JPG" alt="Ticket1649Att2.JPG" />

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDJUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fd587846de7ccc4503d9cfa25957ff0bf318719/Ticket1648Att3.JPG" alt="Ticket1648Att3.JPG" />

**Comment by Andrew-Vargas-bcgov** [comment]
I think the issue is just that the person input the extended leave EI instead of the standard leave EI as is indicated in the pop-up. Might want to make this more clear?

**Comment by Stella-Archer** [comment]
calculator works correctly as expected there maybe UX fixes we could consider if there are more issues related to calculator consideration
