### ISSUE TITLE
Telework: Hide the Comments/Sign-off section for the client view

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#165]
**Background:** The Comments/Sign-off section should be hidden for the client view.

**Steps to Reproduce:**

1. Log in to the PSA-Digital-Journey portal on dev as a non-admin user with valid credentials.
2. Click on “Submit New” on the telework form.
3. Scroll to the last section of the form. 

**Actual Behavior:** The Comments/Sign-off section is not hidden for the client view.

**Expected Behavior:** For the **Telework form**, the Comments/Sign-off section should be hidden for the client view.

**Comment by iman-jamali-fw** [comment]
***Updated AC for Maternity form***
- When client filling the form:
  - Sign-off section => hidden
  - Update date section => hidden
- When supervisor review form
   - Sign-off section => enabled and visible
   - Update date section => visible but disabled
- When supervisor updates dates if form is parental leave
   - Sign-off section => visible but disabled
   - Update date section => enabled and visible

The above behavior were added to [this maternity form](https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form/6244a6ecb6fef0bf7ed39067) on DEV


 Based on my test, everything works on that form except for the PDF attachments in the emails.
In the emails that have attached PDF and sent to client => Signature is not rendered correctly
In the emails that have attached PDF and sent to supervisor => both `Sign-off` and `Update date` sections are hidden.

**Comment by schuyt** [comment]
@simensma-fresh Is there a value in the form object already that lets us know if the user is an employee or manager?

**Comment by schuyt** [comment]
@jizhaogit `task.assignedToMe` which indicates whether or not you are assigned to the task.

By looking at that and maybe `managerEmail` we should be able to determine if the person viewing the form is a manager or now.

**Comment by DonMoffatt** [comment]
I think @jizhaogit has fixed this but it hasn't been pushed to TEST yet from DEV. I see the correct conditional logic in manager portion and the manager portion does not show when the employee fills out the form now. @Stella-Archer @MeghanStothers

**Comment by jizhaogit** [comment]
yes @DonMoffatt, i just made a fix in dev telework form and we can check it tomorrow.

**Comment by DonMoffatt** [comment]
I tested it and it looks good to me.

Don

**Comment by jizhaogit** [comment]
merged to test site
