### ISSUE TITLE
Implementaion of #1598 Cold/Flu: Admin would like to be able to edit a submission once it has been submitted.

### ISSUE THREAD

**Issue by jerry-ey** [bcgov/digital-journeys#1652]
**User Story**
Unfortunately we were not able to edit submissions (ie. For address changes) when a worksite moved locations. For edits we often had to delete the whole submission and create a new one.

**Tasks**
Please consult Mike Shi.

**Acceptance Criteria**
Admin would like to be able to edit a submission once it has been submitted.

1/ Assign all forms to Heather allow her to update or submit in review task - ask heather if this is more work that currently - risky bottle neck
2/ Manual code changes - add condition specific group edit form, changes in multiple place If/else not applicable to all users on all forms on list and update submission file

**We choose option 2** as option 1 may have bottle neck.

**Comment by mikeshi-bcgov** [comment]
Ok, will check

**Comment by mikeshi-bcgov** [comment]
@jerry-ey 

This is current endpoint for updating a submission with existing worksite:

https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_update_registration_existing_worksite/

And below is the sample post data:
var postdata = { "application_id": 1, "closed_reason": "closed_reason_2", "date_submitted": "2024-03-04T08:40:29-08:00", "is_closed": "is_closed_4", "is_relocating": "is_relocating_5", "ministry_id": 6, "number_of_employees": 7, "primary_email": "primary_email_8", "primary_first_name": "primary_first_name_9", "primary_last_name": "primary_last_name_10", "primary_phone": "primary_phone_11", "secondary_email": "secondary_email_12", "secondary_first_name": "secondary_first_name_13", "secondary_last_name": "secondary_last_name_14", "secondary_phone": "secondary_phone_15", "special_instructions": "special_instructions_16", "worksite_id": 17, "year": 18, "date_updated": "2024-03-04T08:40:29-08:00"};

Below are fields in table WorkSite can be updated:
  unit_or_suite,
  street_number, 
  street_name,
  city, 
  province, 
  postal_code, 
  country

Which fields would you like to include in the post?

**Comment by mikeshi-bcgov** [comment]
@jerry-ey
Anyways, those fields have been introduced to the endpoint for update.
<<
 unit_or_suite  varchar(128),
 street_number varchar(128),
 street_name varchar(128) ,
 city varchar(128),
 province varchar(128),
 postal_code varchar(50),
 country varchar(128)
>>

Please test endpoint: 
https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_update_registration_existing_worksite/

By the way, you can call below the endpoint to edit any worksites you want:

https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_worksites(worksite_id)

**Comment by ayushdamani** [comment]
As an Admin, I was now able to make changes to the submission! Thanks Jerry!

**Comment by Augusteen-myeong** [comment]
@ayushdamani - Were you able to change the worksite or update the address on the form that was submitted by others? 

1. I was able to update the worksite address on the form I've submitted. 
2. I was NOT able to update the worksite address on the form someone else submitted. The address fields are greyed out. 
3. In this scenario, are we looking at **reselecting a worksite** or **updating the selected worksite's address**?

**Comment by jerry-ey** [comment]
@Augusteen-myeong 

I discussed with @bhumin-fw , we are only allowed to edit the worksite created by the user (Click the button "Don't see your worksite?") instead of the one selected from the dropdown.

**Comment by Stella-Archer** [comment]
@Augusteen-myeong to edit a worksite a user has entered you (Admin) need to: 
1/ Go to the "Submitted Forms" tab
2/ Search and find the form/person whos worksite needs editing and hit "edit'
you can not edit from the drop down because that is just a field with data populating from the database in ODS

<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4c973086237c143a020d5ba05cb22e525b8955d/image.png" alt="image.png" />

**Comment by Augusteen-myeong** [comment]
@jerry-ey @Stella-Archer  - Thanks for the clarification. That makes more sense!

**Comment by Stella-Archer** [comment]
Tested again with Jerry's submitted form worked fantastic. Ready for deployment, PO Approved and closing tickets

**Comment by jerry-ey** [comment]
Tested on PRD, working fine. Edit unit#.

<img width="1318" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkFkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ee9664cb33c20bc7ee31311e05af42f295d0470/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Admin edit in PROD is working fine!
<img width="1470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2hEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18aede21846b1376a2f837acb8f2a537191255f8/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
PO approved and closing :)
