### ISSUE TITLE
Mat/Par - Note for PSSG/AG users seeing Justice

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1653]
The ministry for users for PSSG is not Justice. In peoplesoft they see PSSG but Justice in our form. We need to address the data mismatch for Justice users on Mat/Par form to prevent confusion.

**AC**
- [ ] Add alert box above the fields for users with Ministry as "Justice" with the following copy

> Note: There is a known data issue for employees with AG and PSSG defaulting to Justice. We are working on fixing this, please continue to submit as this will not impact your leave

**Comment by Stella-Archer** [comment]
@mikeshi-bcgov @T854236  the Justice m ministry doesn't exist could you help us to point at the right table to make sure we are pulling PSSG, AG and Housing instead of Justice?

**Comment by jerry-ey** [comment]
I also added the alert box above the ministry as well.

**Comment by fazil-ey** [comment]
@jerry-ey can you move the note below the existing alert and ensure the fields are aligned

<img width="1727" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9UQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4dfca2ab14f1baec5117d365235afdb4f3206cd1/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
@fazil-ey  moving to below and aligned.
When you test this, you can mock the api "me" with `organization: "Justice"`
Or the following complete data.
```
{"displayName": "Andrew Vargas", "name": "Andrew Ryan Vargas", "firstName": "Andrew", "lastName": "Vargas", "email": "Andrew.Vargas@gov.bc.ca", "address": "119-3501 Dunlin Street, Victoria, V9C 0P7", "address1": "119-3501 Dunlin Street", "address2": " ", "postal": "V9C 0P7", "city": "Victoria", "officePhone": "", "empId": "179934", "positionTitle": "Application Analyst", "depId": "100-0058", "officeAddress": "810 Blanshard St, Victoria, BC, V8W 3E1", "officeAddress1": "810 Blanshard St", "officeAddress2": " ", "officeCity": "Victoria", "officeCountry": "CAN", "officePostal": "V8W 3E1", "officeStateprovince": "BC", "organization": "Justice", "divisionLevel2": "Information Management & Digital Transformation", "supervisorName": "Stella Archer", "managerEmail": "StellaAnne.Archer@gov.bc.ca", "supervisorPositionTitle": "UED - Information Architect", "empCtg": "R", "appointmentStatus": "Regular", "salAdminPlan": null, "phone": "778/535-4071", "fullPartTime": "F", "jobIndicator": "P", "noofrecords": 1}

```

<img width="1313" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3JVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f2ac9ada0e7cfcb9fd80a9709b91ab6889178d9/CleanShot%202024-03-12%20at%2009.58.36.png" alt="CleanShot 2024-03-12 at 09.58.36.png" />

**Comment by jerry-ey** [comment]
@mikeshi-bcgov @T854236 the Justice ministry doesn't exist could you help us to point at the right table to make sure we are pulling PSSG, AG and Housing instead of Justice? (for the Organization field)

**Comment by jerry-ey** [comment]
@T854236 @mikeshi-bcgov 
We are using the endpoint you mentioned. And I still see `organization: Justice`.

Could you please make sure we are pulling PSSG, AG and Housing instead of Justice? (for the Organization field)
<img width="1339" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTdoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34bd7a977eac2c1bb4d3e154a716399012923785/CleanShot%202024-03-14%20at%2011.54.19.png" alt="CleanShot 2024-03-14 at 11.54.19.png" />

**Comment by T854236** [comment]
@jerry-ey 

Hi Jerry, organization names are maintained by the DIO team.  I have requested their support/review if it needs to be changed.  Will keep you posted.

**Comment by Stella-Archer** [comment]
@DonMoffatt and could you follow up on this issue, we are not sure why we re seeing Justice instead of  PSSG, AG and Housing

**Comment by DonMoffatt** [comment]
> @DonMoffatt and could you follow up on this issue, we are not sure why we re seeing Justice instead of PSSG, AG and Housing

@Stella-Archer I think it is pulling on the Org list for the individual rather than Business Unit. I am off Friday (tomorrow) but perhaps this is something the devs could look at. I will follow up on Monday.

**Comment by jerry-ey** [comment]
Hi @DonMoffatt, is there any update here? Thanks

**Comment by DonMoffatt** [comment]
> Hi @DonMoffatt, is there any update here? Thanks

Hi - My note was intended to say that this is something the devs on your side (either ey or Stella's gorup) should look at. I can't tell which list you are pulling from: is it a business unit list or an org list? From our end it appears you only get Justice if you look at an org list.

**Comment by DonMoffatt** [comment]
@mikeshi-bcgov further to my reply this morning and Thursday, the context for this is that we cannot change the Org list at the moment and it uses Justice rather than the separate ministries for AG and PSSG. Our team is going to bring this up with Allan to see what the impediment is, as Justice has not existed as a ministry since 2015. I've suggested that the developers use the Business Unit instead. As a temporary solution (rather than waiting for a fix to the Org list), is there an endpoint for Business Units that they could use instead? That should provide the correct result.

**Comment by fazil-ey** [comment]
This is a data issue, we have a temp fix for the alert that has been released. If the data issue is fixed no work is expected on our end.
