### ISSUE TITLE
Upgrade - Testing Dev Environment 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1654]
Test the dev environment once upgrade is deployed to it. 
https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form
**_Tasks_**
1. Mat/Par - Fazil
2. Cold/Flu - Jerry/Stella
3. 1.10 - Andrew/Ayush
4. Telework - Chris 
5. SL Review - Andrew/Stella

Work with Mike to discuss test cases before the deployment 

**_Scope_** - Only Dev, namespace is NOT is scope, Namespace will be done in #1616

**Comment by MikePSA** [comment]
After discussing with Bhumin, we concluded to perform End to End testing with common test scenarios for the forms listed above. Below is a general checklist of what to test on each form/page: 

1.	Functionality
2.	Validation errors
3.	Content changes
4.	Form submissions
5.	Emails and PDFs

The Formio version upgrade will also need testing, but will require Forms Designer access to test certain functions:

1.	Filter Form/Resources: To the right of the search bar there is a new option to filter forms and resources. 

2.	Form History: As a forms designer click view/edit a form, on the top right it will show form history and duplicate form. To test - edit a form with any 
        small change, such as a content or title change, save the form, go back to form history and you will see any changes made there. If you want to 
        switch to a previous version, go to history and select a version, edit and save form. It will overwrite the form with a past version.

3.	Form Versioning: is now an option to create a new form version. To test - submit a copy of any form. Edit the original form to add a new field and 
        check the box where it asks, “do you want to save a new version of this form?” There will now be two versions, an old and new version of the form. 
        New form versions will have the updated fields, but old forms will not. This is also the case with submitted forms.

4.	Drafts: Need to retest if drafts work properly because of form versioning. The yellow warning box should show up if you have a draft when you 
        try to create a new form. 

5.	Search: You should be able to search submitted forms by form or candidate name.

6.	Form Name Sorting: Click on up/down arrows to the left of the search bar to check if sorting form names cause any delay or lag.

7.	Closing forms: Open a form, copy the URL, go into forms editor for the selected form and disable it for the end user by unchecking “Publish this 
        form for Client Users”. Paste the copied URL into the browser and it should show that the form is not published.

8.	Form Submissions and Workflow: For all forms, we will need to do End to End testing with common test scenarios. The main concern here is that 
        the emails and PDF triggers are working properly after a submission is made, eg. email is sent to applicants and supervisors, they contain the 
        proper content, PDFs properly summarize the form, etc.

**Comment by jerry-ey** [comment]
> 5. Search: You should be able to search submitted forms by form or candidate name.

For this one, please noted this is only applying to cold/flu and mat/par forms. And the form submitted after this name searching function implemented. So better to create new submission and test.

**Comment by ayushdamani** [comment]
Tested 1.10 with Andrew! He is adding our findings in the comment below!

**Comment by Stella-Archer** [comment]
@fazil-ey  be sure to check the review page in new version as per #1583

**Comment by jerry-ey** [comment]
For cold/flu,

## Positive
- submit the form
- after submission, I can see in submitted page
- as admin, I can edit in submitted page

# Negative
- name searching will show blank page

**Comment by chriscaldwell-psa** [comment]
In the dev env, I cannot upload an attachment. I have tried two times and get the following error: 
<img width="1496" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMS9EQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c80a03920e35455a882771bec88cc81986ceb171/image.png" alt="image.png" />

**Comment by chriscaldwell-psa** [comment]
@bhumin-fw Hi Bhumin, can you look into this error. I have tried 2 times to upload ADM Supporting document for 3+ days and get the error object message as seen above. Thank you. C.

**Comment by chriscaldwell-psa** [comment]
Also, when I try to create a new form, its asks for a path. How do I know what path to choose or write:   <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlBEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9d7d48fa6c42b9a543f9404b113ccc8425b5535/image.png" alt="image.png" />

**Comment by chriscaldwell-psa** [comment]
As a forms designer I tested: 
Filter Form/Resources: DONE/Works great

Form History: DONE/Works great
Form Versioning: DONE/Works great

Drafts: DONE/Works great

Search: DONE/Works great

Form Name Sorting: DONE/Works great

Closing forms: DONE/Works great

Form Submissions and Workflow: Done for telework - issue with attaching/uploading Word doc, read above

**Comment by bhumin-fw** [comment]
@chriscaldwell-psa I have fixed upload document error. Please review it.
I'll check with Kunal and find its permanent solution, It is due to files services that stopped working couple week back on DEV environment.

**Comment by bhumin-fw** [comment]
@jerry-ey regarding your comment for not searching by name. 
It should have required hidden field, that's the only requirements for it.


<img width="1352" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1REQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef69b2d53d6e4864146896ee717d3351c39b5289/Screenshot%202024-03-07%20at%206.41.28%E2%80%AFPM.png" alt="Screenshot 2024-03-07 at 6.41.28 PM.png" />

<img width="1877" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1hEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94f442bb8099e623e8357ccb88692d04b71e3e21/Screenshot%202024-03-07%20at%206.45.07%E2%80%AFPM.png" alt="Screenshot 2024-03-07 at 6.45.07 PM.png" />

Let me know if you have any case in mind which in which it is not working.

**Comment by chriscaldwell-psa** [comment]
@bhumin-fw  re: ADM supporting doc to upload - Thank you for fixing this so quickly. It works now.

**Comment by Andrew-Vargas-bcgov** [comment]
1.10 works well.
Tested workflow for all routes, logic and validation for all fields.

**Comment by jerry-ey** [comment]
Bhumin, refer to #1667 and https://github.com/bcgov/digital-journeys/pull/1668 for name search issue.

**Comment by ayushdamani** [comment]
Tested SL Review.
All components, their logic and validation works well.
But, I am not able to validate and make the 'Final Submission'. The options are greyed out.

<img width="1412" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTNIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6754612bb02eaed7aaabb75f1c46f18c1e2ed87/image.png" alt="image.png" />


@bhumin-fw  is taking a look at this error. I will retest once the error is resolved.

**Comment by ayushdamani** [comment]
Update to the above comment: Stella & Andrew is also not able to 'edit' the form. They are also just able to 'view' the form.

@bhumin-fw is actively working on this.

**Comment by ayushdamani** [comment]
All Devs have resolved the above states error in SL Review.

Working perfectly now :)

**Comment by fazil-ey** [comment]
Update - Mat/Pat 

1. Reviewed validation and field logic, looks good
2. emails and pdf look good

No new issues found due to the upgrade
