### ISSUE TITLE
Upgrade - Deployment on Dev

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1655]
@bhumin-fw to add description

**Comment by ayushdamani** [comment]
Bhumin will be testing the new build in the DEV environment.

**Comment by bhumin-fw** [comment]
Hi Team, 
I have deployed the latest version on DEV.
If you want to work on DEV, please let me know, and I will guide you on how.

If you have time, begin testing each detail individually on DEV (recent ticket-related changes). Review recent updates (changes in code) on the web. Form and workflow for each form from end to end.

**Comment by bhumin-fw** [comment]
Deployment to DEV is done, also testing on DEV is done in ticket [#1654](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1654).

Now we are testing OCI endpoints on DEV, It is in progress.
