### ISSUE TITLE
Mat/Par Extended Start/End Dates Required in Form & piped to CRM

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1658]
**User Story:**
TES Feedback:
When an applicant selects Parental Leave, it is to be coded as Parental Leave for the first 35 weeks, and then **Extended Parental Leave for the remaining weeks with the appropriate effective dates should be displayed.** (CRM Ticket: 240229-000669)

If I as a user should select **Extended Parental Leave**, the form should indicate when **Extended Parental Leave Starts** ( so the Telus Reps do not have manually determine the Extended Parental Leave Start Date using the old Mat/Par leave calculator)

**Tasks:**
-	Connect with devs to determine best way to implement the Extended Parental Leave Start Date and end date. (this data needs to reach the CRM)
-	Test once finished.

**Acceptance Criteria:**
- [ ] For extended parental leave, if the leave is greater than 35 weeks, the form should have "Parental leave start date", "First 35 weeks end date", "Extended leave start date" and "Parental leave end date" in the PDF and CRM thread ONLY, not in the DJ form/review page.
- [ ]  It should be where the existing parental leave dates are in the pdf and CRM

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey what if they take 16 or 17 weeks of maternity leave? Should extended still be beyond 35 week of parental?

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov  we don't need to do anything is standard leave is beyond 35 weeks.
We only need to show first 35 weeks if the extended leave is beyond 35 weeks

(it is likely because one person cannot take allowance for more than 35 weeks for standard leave)

**Comment by ayushdamani** [comment]
<img width="385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFB5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5437b24c007a3ac1fef9a3ac166171b4c73beda2/image.png" alt="image.png" />

Looking good, thanks Andrew!

**Comment by Stella-Archer** [comment]
@fazil-ey could you check this is good for Prod deployment?

**Comment by fazil-ey** [comment]
The calculations of the dates seems to be incorrect. The First 35 weeks and the end date both are wrong

<img width="1962" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFA0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--906afd5415af47371ae4a624b91355ad8836649e/image.png" alt="image.png" />

<img width="1513" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGY0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18a0b41eaaeee0226218612c126a7edee9698dbf/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
Confirmed with Connie, for reference if a leave is starting on 30-March-2024, the excel shows what the actual dates should be. There is also inconsistency between the 61 weeks calculated for leave end date and allowance end date

<img width="340" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkw0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd903b163140cf8176204725bac97cb32a103992/MicrosoftTeams-image%20%2816%29.png" alt="MicrosoftTeams-image (16).png" />

<img width="996" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkg0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d79caf3508b4e1534d50787cebc2459ef7eda2ab/Screenshot%202024-03-20%20at%2010.35.32%20AM.png" alt="Screenshot 2024-03-20 at 10.35.32 AM.png" />

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey hey Fazil, everything looks good now. For some reason dev and test were displaying differently, even though the date on the backend was the same. Fixed the display issue.

**Comment by fazil-ey** [comment]
looks good, see the fields in the pdf and CRM, calculations correct

**Comment by Andrew-Vargas-bcgov** [comment]
<img width="760" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBendMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ddf9ac43696cddbab154a70909616f589e678e7/image.png" alt="image.png" />
