### ISSUE TITLE
Telework: Add anchor to the task list to directly navigate the manager to the Comments/Sign-off section

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#166]
**Description:** Add anchor to the task list to directly navigate the manager to the Comments/Sign-off section.

**Acceptance Criteria:**

Given the supervisor has received the "For Action" e-mail after a client has submitted his application
When he clicks on the link provided in the e-mail
Then he should be navigated to the Comments/Sign-off section

**Comment by jizhaogit** [comment]
Added anchor in middle of telework form <a href="#manager"> and tested with formurl#manager, but does not work as expected.

**Comment by MeghanStothers** [comment]
Stella and team to determine if this make sense from user testing findings

**Comment by MeghanStothers** [comment]
We'll pause on this one until we:
1) carry out user testing and get feedback from "manager" about the long scrolling to get to the bottom of the form
2) get direction from Policy team they'd like us to do this - they might want people to read all information about the policy
3) We explore other usability options to reduce scrolling

**Comment by alexandralloyd** [comment]
Policy said all information had to be visible. 

User testing showed that managers wanted to read through the whole form.
