### ISSUE TITLE
Cold/Flu: Pre-populate 'Province' & 'Country' under Worksite Information

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1662]
**User Story**
As an applicant, while filling my worksite information, it would be great for me to see the 'Province' and 'Country' pre-populated to 'BC' and 'Canada'.

**Tasks**
TBD

**Acceptance Criteria**
Auto-populate the 'Province' and 'Country' fields, as 'BC' and 'Canada' respectively -  We only service the province so there shouldn’t be a need for a further reach than that.

<img width="883" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd216QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c3cfda7778dcb046617901ee3a327ca0f060330/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Working great in TEST

<img width="1138" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnE3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24674ece4afb6ca7cde82a0a7c314a798ae71608/image.png" alt="image.png" />

**Comment by Augusteen-myeong** [comment]
@Stella-Archer - I've confirmed that "BC" and "Canada" are pre-populated in the test environment. 
![image](https://github.com/bcgov/digital-journeys/assets/159492049/e3aa9f90-7a04-40fc-adc5-8bf225154e5a)

**Comment by Stella-Archer** [comment]
sweet - PO approved and Closing this :)

**Comment by Stella-Archer** [comment]
Post  Deployment Test:
Looks good live :)
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW9MQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e69b141fcd4e5119e46cbbf6dfa2ace0d14cf9af/image.png" alt="image.png" />
Closing
