### ISSUE TITLE
Telework - Failed Tasks (Camunda Tasklist) Increase Size of field 

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1665]
Background: @mikeshi-bcgov  - Hi Mike, we created a ticket for you to track the size limit impacting the telework form.  

Re: Telework:  all that failed tasks on telework have more than 1000 characters in field “employeesCommentsOptional”. Let’s ask Mike to increase size of that field to 2048 or for safe side 3000 characters.

 
Steps to Reproduce:
 
Actual Behavior:
 
Expected Behaviour: Be able to released incidents in Camunda 
 
Environment: Prod- Camunda etc

**Comment by mikeshi-bcgov** [comment]
Sure will increase the size limit to 3000 characters

**Comment by mikeshi-bcgov** [comment]
Changes will be deployed on Thursday March 7th 2024.

**Comment by mikeshi-bcgov** [comment]
Changes have been deployed to prod, done.

**Comment by Stella-Archer** [comment]
New error March 7 @mikeshi-bcgov There are still 8 jobs are not successfully completes could you check errors in field Thx

**Comment by mikeshi-bcgov** [comment]
Below are the errors for today's submissions applicationid:

83458 -- "Execution of the INSERT query failed. Error: [HY000] Incorrect string value: '\\xF0\\x9F\\x98\\x8A\\x0A\\x0A...' for column 'employeesCommentsOptional' at row 1 (1366)"

85524, 82511, 83437 -- "message" : "Execution of the INSERT query failed. Error: [22001] Data too long for column 'noteOptional' at row 1 (1406)"

83189, 85842, 82684  -- "message" : "Error parsing Date value [null]."

61923 --"message" : "Execution of the INSERT query failed. Error: [22001] Data too long for column 'employeesCommentsOptional' at row 1 (1406)"

Items to highlight:

1. Column 'noteOptional', allowed maximum characters need to be increased too? eg. 3000
2. Maximum allowed size for column 'employeesCommentsOptional' has been increased to 3000, need even bigger?
3. Seems there are "null" value for date/timestamp field, please check
4.  Seems there are invalid characters for 'employeesCommentsOptional', possibly with something like Happy Face, please check

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
Thank you so much for detail comments here.


Applications that are still not clear.
85842, 85524, 82511, 83189, 61923, 82684, 83437, 83458

Note:
"noteOptional" No such field is there in any of applications.
61923: I don't see field name "employeesCommentsOptional" for this record.

Try to fix data with given comments, still all 8 submissions fails. Could you please again? We might see different error for given application.
Also if possible could you please share one or two full request data over [email](bhumin.patel1@ca.ey.com)? I would like to see what exact data are sending to ODS.

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw all sent over email to you already, thx

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov I did change all give with correct data, it still sending old data. Let me check it on codebase and try again. Thank you for detail mail on all queries.

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov 
85524, 82511, 83437 -- "message" : "Execution of the INSERT query failed. Error: [22001] Data too long for column 'noteOptional' at row 1 (1406)"

**To resolve this we need to increase size to 3000. Longest data are 1465 from these data for noteOptional field.**


@Stella-Archer 
One employee made comment with 6700 characters long. Do you want us to increase that limit to 7000 from 3000? Please confirm SO Mike can update same on database.


Note:
@mikeshi-bcgov 
Other issues seems fixed, data required to sync on digital journey between 2 services to send updated details. Able to fix it. Thank you for detail notes/logs on an email

**Comment by mikeshi-bcgov** [comment]
As the maximum allowed row size reaching limit, we can only increase "noteOptional" to 2000. If have to increase further for these fields, need to change data type to TEXT

**Comment by bhumin-fw** [comment]
@mikeshi-bcgov for "noteOptional" let's make 2000 only. Let me add limit on form. If we receive any request we will review it and let you know to update.

Also do we have any issue increasing size to 7000 for "employeesCommentsOptional"?

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw "employeesCommentsOptional" can't be increased further, maybe make limit on FORM for <=3000?

**Comment by mikeshi-bcgov** [comment]
@bhumin-fw change for "noteOptional" has been deployed to prod.

**Comment by Abuchana** [comment]
Submission Sept 13. 2023.
Amend comments to 3000 characters and send to ODS. 
New forms will not face this issue.
