### ISSUE TITLE
Mat/Pat - add bullet in email to applicants about pension

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1670]
**_AC_**

- [ ] Add this as the 3rd point in the email sent to applicants after approval (before income tax)

> - You have the option to make continuous pension contributions monthly throughout your leave.  You must decide within the first 30 days of your leave and submit a completed Purchase of Service Application through an AskMyHR Service request.  Use the category Myself > Benefits > Pension/Purchase of Service.  

<img width="1188" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEVFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b05499cc747a3fc5cc372617b9d08c16d4f8a0f/Screenshot%202024-03-22%20at%2012.25.06%20PM.png" alt="Screenshot 2024-03-22 at 12.25.06 PM.png" />

**Comment by bhumin-fw** [comment]
@ayushdamani 
Added bullet point as per this ticket. It is ready to test on TEST environment.

**Comment by fazil-ey** [comment]
looks good

**Comment by fazil-ey** [comment]
looks good

**Comment by Stella-Archer** [comment]
Live email came through with bullet yay re-closing
<img width="987" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenNMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b19747193c9dc16e52866a751825b20077dfc711/image.png" alt="image.png" />
