### ISSUE TITLE
Tool: Deploy new version 5.1.1 to TEST environment

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1674]
Release new version 5.1.1 to TEST environment.

Points that needs to be review before and during upgrade deploy to test.
- Make sure webapi database update before service start, It hase 2 new table and re-map form version query for all existing records.
- Review and process form tab needs to check after deployment done. Check console and APi to make sure all required detail (API call and no error on console) works well.
- Review and process has few additional change, As a supervisor make sure you are able to select form and take action on it for all legacy form submissions.
- Form version is enabled in new version/upgrade. We can skip that as a designer until we have such case where we want to implement it.
- Review all services log while performing above operations.
- End to End test all legacy forms, telework, SL, Mat-Pat, Influenza, and 1.10

**Comment by Stella-Archer** [comment]
Bhumin is reviewing approach for deployment to PROD
long time 25 min need a lock down for period,
- [ ] end to end test
- [ ] confirm with BI data is submitted for telework
- [ ] Mat pat end to end - CRM team needs to remove forms 


****this forms check list for PROD deployment

**Comment by bhumin-fw** [comment]
Successfully deployed code with newer version on TEST and PROD.
