### ISSUE TITLE
Cold and Flu: OCI End point testing

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1675]
**User Story**
“As a form owner, I want make sure my data is migrated to OCI so I my application is correctly connected when I Launch to PROD on JUNE 10.” 

**Tasks**
Confirm Influenza DB submission can be summitted and updated

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.

**Comment by bhumin-fw** [comment]
@T854236 
I have sent you an email regarding 500 error on Influenza (cold/flu) endpoint. + SL review endpoints on new OCI server.

Here is brief details regarding that.
**Telework submit with success.**
Could you please confirm that record has been created in telework table on database via OCI API?
applicationId: 11561, 11564


**SL review/ Influenza form relate endpoint fails with 500 error.**
500 from POST https://bi-api.tssi.ca/apiserver/api.rsc/Datamart_Telework_app_slreview_info
500 from POST https://bi-api.tssi.ca/apiserver/api.rsc/ods_datamart_influenza_insert_registration_existing_worksite
500 Internal Server Error from POST https://bi-api.tssi.ca/apiserver/api.rsc/ods_datamart_influenza_insert_registration_existing_worksite

**Could you please send me an error log of it ?** (SL review fails on both OCI and existing ODS might be some update on database field, let me know detail of it from both server so I can review and plan to fix it if any)

cc: @mikeshi-bcgov

**Comment by T854236** [comment]
@bhumin-fw @mikeshi-bcgov 

Mike reviewed and confirmed on the 2 submissions is in OCI ODS.

**Comment by bhumin-fw** [comment]
@T854236 
Thank you Patrick & Mike for confirming it.

@mikeshi-bcgov 
I have sent 2 objects over email, 1 for SL review and 1 for Influenza (cold/flu) form on which we receive 500 error.
I don't see any detail error on response, status is 500 and detail shows internal server error.

If on log it shows any variable/key/value related error from JSON payload, Please share detail with me so I can review and try to fix it.

**Comment by Stella-Archer** [comment]
Mike see warning on ODS side to make sure warning cap 'No' small case 'no' ask to use all values - otherwise convert to lowercase on our end

**Comment by bhumin-fw** [comment]
Ready to review new OCI endpoints for Influenza form on DEV environment.

**Comment by Stella-Archer** [comment]
This was successfully tested in DEV closing now
