### ISSUE TITLE
Mat/Pat - Add info in mail to supervisors and applicants on submission

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1679]
**_AC_**
- [ ] Add the following line to the email sent to supervisors informing a new form submission pending for approval 

> 
> **NOTE**:  If the employee is taking **only parental leave**, a leave can be approved with a future date of birth, however, it is the **responsibility of the supervisor and the employee to ensure parental leave is started only after the child is born**. If there is any change in the date of the birth or leave start date, the employee or supervisor can edit them on [Digital Journeys](https://digital-journeys.apps.silver.devops.gov.bc.ca/form) and resubmit. Not doing so can lead to payroll errors. 

- [ ] Add the following line to the email sent to applicants taking only parental leave confirming submission of a new form (NOT the email sent after approval)
> 
> **NOTE**:  Your supervisor can approve your parental leave with a future date of birth, however, it is both your **and your supervisor's responsibility to ensure parental leave is started only after the child is born**. If there is any change in the date of the birth or leave start date, the employee or supervisor can edit them on [Digital Journeys](https://digital-journeys.apps.silver.devops.gov.bc.ca/form) and resubmit. Not doing so can lead to payroll errors.

**Comment by Stella-Archer** [comment]
There is another very small email fix in #1670 about adding pensions.
Could we do that at the while we have the emails open?

**Comment by bhumin-fw** [comment]
This email content are before approval. #1670 is after approval. I can check it with Andrew and add it along with this ticket.

**Comment by bhumin-fw** [comment]
@ayushdamani @fazil-ey 
It is ready to test on TEST environment.

**Comment by fazil-ey** [comment]
@ayushdamani yes needs to be bolded

**Comment by ayushdamani** [comment]
Thank you, Fazil!
Moving back to in-progress!

**Comment by bhumin-fw** [comment]
@ayushdamani Updated content, selected text are bold now. Moving again for testing.

**Comment by ayushdamani** [comment]
Tested in both TEST and DEV .Looking great - moving to PO

Supervisor email -
<img width="1116" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2dFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4136b96d2281217fed98a4532aad0f9b877aa6cd/image.png" alt="image.png" />
---------------------------------------------------------------------------------------------------------------------------------
Employee email -
<img width="1125" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2tFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cf4800103a6d0b64c731ee1edc3dc6fcb71e6c3/image.png" alt="image.png" />
---------------------------------------------------------------------------------------------------------------------------------

**Comment by fazil-ey** [comment]
Dont see the note in Employee email. Application ID# 5329

Took only parental leave

**Comment by bhumin-fw** [comment]
@fazil-ey 
I did check, I saw an email with notes. Same value selected.
birthing parent: No
Taking Parental leave: yesHoweverOnlyIWillBeTakingParentalLeave

<img width="901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzBKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed017ea7dd0cd0a1f17db9a839adb45dd02ce796/Screenshot%202024-03-25%20at%2012.10.28%E2%80%AFPM.png" alt="Screenshot 2024-03-25 at 12.10.28 PM.png" />

Please hard refresh before launching mat-pat form or try in incognito.

**Comment by fazil-ey** [comment]
It works, i was checking the wrong email!
