### ISSUE TITLE
Cold/Flu: Update success message to say 2024 Worksite Influenza Vaccination Program

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1682]
**User Story**
“As a influenza clinic registrant I want confirmation that I have signed up to host a clinic correctly. The title of the clinic should be consistent in all places it appears

**Tasks**
edit “2024 Cold and Flu Program” to read
“2024 Worksite Influenza Vaccination Program”
<img width="637" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemYrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5e32cdf1f7181b611774ec8a9944eb306086f27/image.png" alt="image.png" />

**Acceptance Criteria**
Headline of the success message reads:
**Thank you for registering your worksite for the 2024 Worksite Influenza Vaccination Program**

**Comment by jerry-ey** [comment]
ready to test

**Comment by ayushdamani** [comment]
Updated - moving to PO ✅
<img width="1063" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGUxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--234eeadf480034e6c29b662b9659de35d916bc27/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good 
<img width="968" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzY1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebaf8e1178030493100308e0a5a1f7c3a5cd564a/image.png" alt="image.png" />
