### ISSUE TITLE
Supervisor/Managers' Review and Process Forms Tab - Tasks/Completed Approvals not removing from the side panel

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1686]
Background: A manager from OCIO completed two submissions, yet they are still showing up. The manager would like them to disappear ( for manageability). Note: the email sent to DJ's inbox was forwarded to Bhumin to reference. 
 
Steps to Reproduce:  Approve a telework form under the Review and Process tab. 
 
Actual Behavior: Manager's approved employee tasks are still displaying (when they should disappear)
 
Expected Behaviour: After a manager approves their employee's telework form, the task or employee name listed disappears.
 
Environment: Prod

Acceptance Criteria:
Test:
- [ ] Approve a test telework submission
- [ ] Look to see if the approved task or submission disappeared from the Review and Process Form tab.
- [ ] End to end UX
- [ ] End to end functionality
- [ ] if data impacting confirm w/BI/DIO team

**Comment by Stella-Archer** [comment]
Resolved - Closing
