### ISSUE TITLE
Mat/Pat - Missing word in Before you Begin

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1688]
**_AC_**
- [ ] Change "HR Centre" to "HR Service Centre" as shown above in the Before you begin tab.

<img width="1255" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMThRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1e0c4f7674b2e986edbca19656aca64941ae442/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
This is the bullet under 'Privacy'

**Comment by ayushdamani** [comment]
Moving to PO

<img width="1189" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDloQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efb330d6ee5df11bec2c010692cb2b02178eafd3/image.png" alt="image.png" />
