### ISSUE TITLE
Mat/Pat - Resubmission emails fix

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1689]
AC
- [x] Applicants should **not be** sent pdfs on resubmission before their application is approved. 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenNTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf2549684e8c0a91e23f54458bb1d3f5309501a4/image.png" alt="image.png" />

- [x] Resubmit email to applicant should include the following note( #1679) as well
    - [x] Add the following line to the email sent to applicants taking only parental leave confirming submission of a new form (NOT the email sent after approval)
> 
> **NOTE**:  Your supervisor can approve your parental leave with a future date of birth, however, it is both your **and your supervisor's responsibility to ensure parental leave is started only after the child is born**. If there is any change in the date of the birth or leave start date, the employee or supervisor can edit them on [Digital Journeys](https://digital-journeys.apps.silver.devops.gov.bc.ca/form) and resubmit. Not doing so can lead to payroll errors.

**Comment by ayushdamani** [comment]
Working great - moving to PO

**Comment by fazil-ey** [comment]
looks good
