### ISSUE TITLE
Mat/Pat - Add link in email

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1691]
**_AC_**
- [ ] Add link to Purchase of Service Application in the mail sent to applicants on approval

https://pspp.pensionsbc.ca/documents/824580/824628/pspp-form-purchase-of-service-application.pdf/cb05328f-fec7-4758-8e4a-faae3e389590

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejhTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5a037ea94fe81395eb93277bf4da3540849d837/image%20%281%29.png" alt="image (1).png" />

**Comment by jerry-ey** [comment]
ready to test

**Comment by ayushdamani** [comment]
The link is working great - moving to PO
<img width="1095" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG5qQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b18681a432c1c20aa8b44b7599e7e9cee31596cc/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good
