### ISSUE TITLE
[UPGRADE]: testing the TEST Environment

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1692]
**User Story**
The Upgrade has been deployed to TEST.
Please do end to end testing on each of the following forms in the TEST environment.
https://digital-journeys-test.apps.silver.devops.gov.bc.ca/form
Tasks

Mat/Par - @fazil-ey 
Cold/Flu - @jerry-ey  /Stella/ @mike
1.10 - @Andrew-Vargas-bcgov / @ayushdamani 
Telework - @chriscaldwell-psa 
SL Review - Andrew/Stella
a general checklist of what to test on each form/page:

- [ ] Functionality
- [ ] Validation errors
- [ ] Content changes
- [ ] Form submissions
- [ ] Emails and PDFs

The Form.io version upgrade will also need testing, but will require Forms Designer access to test certain functions:

- [ ] Filter Form/Resources: To the right of the search bar there is a new option to filter forms and resources. Devs are planning to look into hiding this filter once all major functionality is stable, as it may effect keyword search.

- [ ] Form History: As a forms designer click view/edit a form, on the top right it will show form history and duplicate form. To test - edit a form with any small change, such as a content or title change, save the form, go back to form history and you will see any changes made there. If you want to switch to a previous version, go to history and select a version, edit and save form. It will overwrite the form with a past version.

- [ ] Form Versioning: is now an option to create a new form version. To test - submit a copy of any form. Edit the original form to add a new field and check the box where it asks, “do you want to save a new version of this form?” There will now be two versions, an old and new version of the form. New form versions will have the updated fields, but old forms will not. This is also the case with submitted forms.

- [ ] Drafts: Need to retest if drafts work properly because of form versioning. The yellow warning box should show up if you have a draft when you try to create a new form.

- [ ] Search: You should be able to search submitted cold/flu and mat/par forms by form or candidate name. Create a new submission to test, as this function only works for submissions after the fix was implemented.

- [ ] Form Name Sorting: Click on up/down arrows to the left of the search bar to check if sorting form names cause any delay or lag.

- [ ] Closing forms: Open a form, copy the URL, go into forms editor for the selected form and disable it for the end user by unchecking “Publish this form for Client Users”. Paste the copied URL into the browser and it should show that the form is not published.

- [ ] Form Submissions and Workflow: For all forms, we will need to do End to End testing with common test scenarios. The main concern here is that the emails and PDF triggers are working properly after a submission is made, eg. email is sent to applicants and supervisors, they contain the proper content, PDFs properly summarize the form, etc.

**Comment by chriscaldwell-psa** [comment]
Tested the telework agreement for both 1-2 days and 3 + days requests. Worked smooth as butter. Emails, attachments and form all work great. Chris.

**Comment by ayushdamani** [comment]
Tested the 1.10 - working great

Will perform one more test once Andrew is back next week.

**Comment by Stella-Archer** [comment]
@bhumin-fw is working on one issue #1696 upper/lower case issue in pre-population of fields from ODS

**Comment by fazil-ey** [comment]
Except #1696, no other issue found yet with the form. Discovered some bugs not related to upgrade #1691 and #1689
