### ISSUE TITLE
Add the feature to EDIT the telework form due to high demand from users (managers).

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#1694]
**AC**
- [ ] Telework should be editable before the form is approved by supervisor 
- [ ] Change the instruction in Before you begin
- [ ] After every edit and resubmission, same actions should take place that happen after the first submission

> You can edit the form after submission. It can be accessed in the [Submitted forms ](https://digital-journeys.apps.silver.devops.gov.bc.ca/application) tab. However, no edits will be allowed after your supervisor approves your form

------
Context

I spoke to a manager on Tuesday March 26 via Teams who addressed that she and other managers are frustrated by the inability to edit the telework form. 

Scenario: 
A typical process flow would be for an employee to submit a telework agreement, hoping for 5 days a week at home (for example), when 2 to 3 days is the average allowed, or selecting days to work from home when a mandate is set for employees to be in the office on a specific day(s). This will require an edit, which would be easier to update from the managers point of view rather submitting a new form.

**Comment by Stella-Archer** [comment]
Edit before or After approval?
Edit existing agreement
Is there a record of what approval was previously granted
Recommend: before approval edit after NO, submit a new form

**Comment by Stella-Archer** [comment]
How long can you edit? Until after the supervisor approves?

**Comment by Stella-Archer** [comment]
Spoke with Sean at policy he gave employee draft/edit go ahead. no supervisor edits just approval/deny

**Comment by bhumin-fw** [comment]
Required to change estimation from 3 story points to 5.
In this ticket, 

- We will allow employees to edit the form before it is approved or denied by the supervisor. 
- The supervisor will only be able to approve or deny the form, but will not be able to edit the form data.
- Incomplete submissions will be deleted 60 days after submission.

**Comment by bhumin-fw** [comment]
@fazil-ey @Stella-Archer @ayushdamani 
In the telework, we cannot enable editing for older submissions, nor can we hide the edit button for those submissions. To address this issue, I have added a label to the form for older submissions. This label will display a message, as shown in the screenshot, at both the top and bottom of the form.

<img width="1847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeitMQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9597fcd713b224c75d5476423fbbbcc32656bd51/Screenshot%202024-08-26%20at%207.19.54%E2%80%AFPM.png" alt="Screenshot 2024-08-26 at 7.19.54 PM.png" />

    
<img width="1847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMENMQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75d3ea04f1761fb5a86bf90b93108240aaa0c2e7/Screenshot%202024-08-26%20at%207.20.05%E2%80%AFPM.png" alt="Screenshot 2024-08-26 at 7.20.05 PM.png" />

**Comment by fazil-ey** [comment]
@Bhumin "This telework submission cannot be edited. However, new submissions can be edited before the supervisor submits a decision"

**Comment by bhumin-fw** [comment]
It is ready to test on DEV and TEST environment.
Note: The new message provided above for the old form will not be visible in the DEV or TEST environments. However, it will be implemented in the PROD environment next week.

Please test edit telework form and workflow in detail, and if you try to edit older form old message will be display for now.

**Comment by ayushdamani** [comment]
Tested and confirmed working - thanks so much Bhumin!
