### ISSUE TITLE
COI: Building front-end (Employee Disclosure Statement)

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1699]
Build the Employee Disclosure Statement tab

**Acceptance Criteria**
- [x] The Employee Disclosure Statement tab is built as per the design and content provided below
- [x] Questions 1, 2 and 3 should be text area fields and mandatory. (no technical limit on word count for DJ) 
- [x] Question 4 should be a file attachment field and optional **_(file size and types TBD)_**  
- [x] Question 5 should be radio button (Yes/no) and mandatory
- [x] If Question 5 answer is _Yes_, only then Question 6 should be shown
- [ ]  If Question 5 answer is _Yes_ only then Question 6 is mandatory i.e there must be an attachment **_(file size and types TBD)_**  

**_Design_**

Link to miro - https://miro.com/app/board/uXjVKbE3n_8=/?moveToWidget=3458764585134827511&cot=14

**Comment by jerry-ey** [comment]
Please test

**Comment by fazil-ey** [comment]
1. Question 5 should be mandatory  https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Conflict%20of%20Interest/Test%20recordings%20and%20screenshots/Screen%20Recording%202024-04-22%20at%207.52.15%20PM.mov?csf=1&web=1&e=YW4tNv

2. Seeing this unauthorized message when uploading files 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEdEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f29f0f149fe65527ed700f2dfb0d3b950b63273/image.png" alt="image.png" />

3. Can we remove the file name and size box 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE9EQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9065c198a0048e904eba399e8ed6b2f7ffc25dab/image.png" alt="image.png" />

2.

**Comment by fazil-ey** [comment]
file upload needs to be handled in #1720

**Comment by MikePSA** [comment]
1. "Please provide the following" is missing from the top of the Employee Disclosure Statement tab, according to the design on COI miro. (Ignore if doesn't matter)
<img width="905" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGlQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b520a2958875ca3aa5f8dfcbfcbc4a591b4889ab/image.png" alt="image.png" />
2.  Unauthorized message still shows for both questions 4 & 6 when uploading files
<img width="1371" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e1d0e61be9479611975aacd4760f5337175e142/image.png" alt="image.png" />

3.  If you try to proceed without answering question 5, the validation error just repeats the same question. Should be changed.
<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHlQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96bd91c024053d7e639d7179679203bae167ab19/image.png" alt="image.png" />
4.  If you try to proceed without answering question 6, the validation error just repeats supported file types. In this example I have not attached anything as well. Should be changed.
<img width="841" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeCtQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c0af0047de93eed53ce7cc9429a2f78ae9d138a/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
@MikePSA , For 2. and all attachment related, please refer to other ticket as mentioned above in the comment.
<img width="916" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWlQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da80eeb352d35c154bc26c99acaabf8571b19848/CleanShot%202024-04-24%20at%2014.50.12%402x.png" alt="CleanShot 2024-04-24 at 14.50.12@2x.png" />

**Comment by jerry-ey** [comment]
please test again.

**Comment by jerry-ey** [comment]
Note to me: 
To fix the number 4 item.
Check the mat/par parental leave for example. can do error message based on different condition.

**Comment by jerry-ey** [comment]
@fazil-ey 
Based on source code of Formio, we are not allowed to change the following error message for file upload component.

- file type
- file size

But only can change the "required" error message.

<img width="1448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG1mQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d852b191fe86f31db2e9329a27629d311fbb222/CleanShot%202024-04-29%20at%2010.06.25%402x.png" alt="CleanShot 2024-04-29 at 10.06.25@2x.png" />

**Comment by fazil-ey** [comment]
The error message is correct now when no file is attached
