### ISSUE TITLE
After the submission of a form, the user should be navigated to a proper landing page

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#170]
**Description:** After the submission of a form, the user should be navigated to a proper landing page.

**Acceptance Criteria:**
Given the user is filling out a form such as the Maternity, Parental one
When the user clicks the "Submit" button
Then he should be displayed with the proper toast message and navigated to the proper landing page as below:

![landingPage.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/f7d74d2a-2347-48ab-a406-7f9cc171c97b)

**Comment by DonMoffatt** [comment]
This was likely started with Mat leave in mind but applies to Telework as well.

**Comment by MeghanStothers** [comment]
Duplicate ticket
