### ISSUE TITLE
Mat/Pat - Add description under "Does your partner work for BC Public Service"

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1706]
We have observed that if both partners work for BC public service, they are making mistakes in the number of weeks of allowance, taking more than they each should. 

To resolve this we want to add a description under "Does your partner work for BC Public Service"

**_AC_**
- [ ] Add description under "Does your partner work for BC Public Service

> If both parents are BC Public Service employees, both **can take the full length of standard leave or extended leave**. However, they must **split the number of weeks they claim leave allowance between the two of them**. For standard leave parents can split 35 weeks of allowance and for extended leave parents can split 61 weeks of allowance between them. Both parents are required to **choose the same EI parental benefit option**, either standard or extended. They must also **choose the same leave allowance type** in each of their Maternity and Parental leave allowance forms.**

<img width="1148" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f075762dc2fbc6086bfde2acf0b4e13ee9dcb7d/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Changes are up in TEST & Dev.
Question: Should I make the description yellow or blue?

<img width="1407" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3AwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d56ee9fa4d07a862eb9c8fda952b21d06b6fa50c/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
The initial idea was to have it under the question, but making it a alert box is a better idea. Lets make it a blue information box

**Comment by chriscaldwell-psa** [comment]
@fazil-ey Heading has been added up the text; the component has been changed to a blue info box: <img width="1391" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3FIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c096c34c92a884833ecc0ddf9e9b14e5269b8dbf/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
@chriscaldwell-psa also the heading text has some typos - it should be "Allowance weeks must be split when both parents work for BC Public Service"
