### ISSUE TITLE
Mat/Pat - Add content in "Parental leave - Leave allowance dates" if both parents work for BC Public Service

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1707]
We have observed that if both partners work for BC public service, they are making mistakes in the number of weeks of allowance, taking more than they each should. 

To resolve this we want to add a add alert box under "Choosing dates for receiving parental leave allowance

**_AC_**
- [x] If "Does your partner work for BC Public Service" is yes then add alert box under "Choosing dates for receiving parental leave allowance

> ### Choosing allowance dates when both parents work of BC Public Service

> If both parents are BC Public Service employees, both **can take the full length of standard leave or extended leave**. 
> However, they must **split the number of weeks they claim parental leave allowance between the two of them**. For standard leave parents can split 35 weeks of allowance and for extended leave parents can split 61 weeks of allowance between them. 
> 
> 
> **Example** -  Let's say both parents chose standard leave and standard leave allowance. Here's what they can choose:
>  
>**1. Length of leave** - Both can take leave for up to 35 weeks each. For e.g. one parent can take parental leave for 35 weeks and the other for 20 weeks, or 35 weeks and 35 weeks and so on.
> **2. Number of weeks of allowance** - Both must split 35 weeks. For e.g. one parent can take parental leave allowance for 20 weeks and the other 15 weeks, or 30 weeks and 5 weeks and so on. 
>

**Comment by ayushdamani** [comment]
Changes are up in TEST & DEV :)

**Comment by fazil-ey** [comment]
Change this language 

1. Length of leave - Both can take leave for up to 35 weeks each. For e.g. one parent can take parental leave for 35 weeks and the other can also take 35 weeks of leave. Or one parent can take 35 weeks of leave and the other can take just 20 weeks.

**Comment by chriscaldwell-psa** [comment]
@fazil-ey Text has been updated and spacing has been added between the components: <img width="1135" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem1IQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c068fc22e39c17d94aab49a6474c2b8208a269f3/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEdKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca087354f26598585eefc6a979614beb4bc69ac1/image.png" alt="image.png" />
