### ISSUE TITLE
Mat/Pat - Add note in "Parental leave - Leave allowance dates" if both parents work for BC Public Service

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1708]
We have observed that if both partners work for BC public service, they are making mistakes in the number of weeks of allowance, taking more than they each should. 

To resolve this we want to add a note suggesting the max number of weeks the partner can take allowance for based on the applicants choices. 

**_AC_**
- [ ] If "Does your partner work for BC Public Service" is yes then when calculating allowance end date add a note like described below in yellow alert box that shows the allowance end date. (done in #1709)

> Your allowance end date is [allowance end date]. Please note that based on your selections your partner can claim [standard/extended] parental leave allowance for a maximum of [number] weeks and [number] days. Please verify your selections with your partner to prevent delays in the processing of both of your leave applications. 

**Logic** 
[standard/extended] this should what the applicant has selected
[number] of weeks and [number] of days
- if standard this should be (35 weeks - [applicants number of weeks/days])
- if extended this should be (61 weeks - [applicants number of weeks/days])

**Comment by Andrew-Vargas-bcgov** [comment]
ready for you @fazil-ey
