### ISSUE TITLE
Mat/Pat - Optimizing information and alerts

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1709]
We want to optimize how we give alerts as they are overwhelming in some places in the mat/pat form 

**_AC_**

- [x] In Parental leave - Start date, add the information about date as description "When do you want to start your leave?"

<img width="1846" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWhJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89adda9673065329143f6cb3551e085b6901ad88/image.png" alt="image.png" />

- [x] In Parental leave - Start date, make the blue box with start and end dates a yellow alert box
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0pKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cb786edc6e4e1b35ced1e81290a1753f953788b/image.png" alt="image.png" />

- [x] In Parental leave - Leave allowance dates, add the information about date as description under "When do you want to receive your parental leave allowance?"

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXhJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbf4d3c1d60499bfea4bddf1f97b5a7d099a7e77/image.png" alt="image.png" />

- [x] In Parental leave - Leave allowance dates, instead of end date field add a yellow alert box with the end date

> Your parental leave allowance end date is **[date]**

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0JJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7127a49ce7e4f817d5a8961169455aba89f0413a/image.png" alt="image.png" />

**Comment by chriscaldwell-psa** [comment]
@ayushdamani  Over to you Ayush! This is ready to test. Thanks Chris

**Comment by ayushdamani** [comment]
Tested in the TEST env - looking good

**Comment by fazil-ey** [comment]
1. Remove the question in the description
 <img width="1792" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDU2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--496256ed673cf2904f6eaabafd4fd530183ce196/image.png" alt="image.png" />

2. the yellow box should come only after a start date and number of weeks is filled 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU42QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58072b9bcff0de951c867e135954c99efbece36f/image.png" alt="image.png" />

**Comment by chriscaldwell-psa** [comment]
@fazil-ey Updates should be good now. I had Andrew look at this. Thanks Chris

**Comment by fazil-ey** [comment]
Looks good!
