### ISSUE TITLE
COI: Building front-end (Employee Signoff Statement)

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1710]
Build the Employee Sign off Statement tab

**Acceptance Criteria**
- [x] The Employee Sign off Statement tab is built as per the design and content provided below
- [x] Employee Declaration checkbox should be mandatory 
- [x] For IDIR
    - [ ] Employee Name, Employee Email, Employee Number and Date should be prefilled and not editable 
    - [x] Supervisor Name, Supervisor Email should be prefilled and editable 
    - [x] Supervisor email should be a valid gov email (gov.bc.ca)
    - [x] Supervisor Name should be a valid string
    - [x] Supervisor Name, Supervisor Email should be mandatory
- [ ] For LDB **_TBD_**
    - [ ] Employee Name, Employee Email, Employee Number and Date should be prefilled and not editable 
    - [ ] Supervisor Name, Supervisor Email should be prefilled and editable 
    - [ ] Supervisor email should be a valid ldb email (bcldb.com)
    - [ ] Supervisor Name should be a valid string
    

**_Design_**

Link to miro - https://miro.com/app/board/uXjVKbE3n_8=/?moveToWidget=3458764585135351695&cot=14

**Comment by Stella-Archer** [comment]
@Andrew-Vargas-bcgov Check with LDB to see if there is information we can import from their data

**Comment by ayushdamani** [comment]
The layout has been created in TEST - please test @fazil-ey 
I am not sure of the spacing between the sentences and headers - would appreciate your guidance.

**Comment by fazil-ey** [comment]
@ayushdamani if you could make the spacing like below it would be great. There too much space 
<img width="584" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3VsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--634f6474f94fd9e20c722b403295039a79b7f95f/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
For sure, Fazil - I will do that! Thank you!

**Comment by ayushdamani** [comment]
1. Fazil, does the spacing look okay to you?
<img width="1222" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bbff66f02abeaa716fe9c6409a69cbb70424366/image.png" alt="image.png" />

2. @MikePSA is this good?
<img width="1225" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUNtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1682df0ecc009c9385a169f2da81bcefc0aea656/image.png" alt="image.png" />

3. @Andrew-Vargas-bcgov can you please advise on how to move the submit button, as requested by Mike in the comment above?

**Comment by Abuchana** [comment]
Should this ticket be in the in progress column?

**Comment by ayushdamani** [comment]
Yes. My apologies!

**Comment by Abuchana** [comment]
All good, thank you!

**Comment by MikePSA** [comment]
@ayushdamani looks good for the most part, but just missing the "is" part. If we want it to be consistent with the prior page. And on that note, it looks like there's an extra colon in number 5 for the Employee Disclosure statement tab, if we could remove that as well. Thanks!
<img width="1378" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2ltQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--534ca7a18d56ad1bf8584d3c9acbcc2bbfe5571f/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
@Andrew-Vargas-bcgov can you please help me out with the above request? I do not know how to fix these please.

1. Can you replace the colon with 'is' so it says 'Certification for submission is required'
<img width="1225" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnJBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31cb002ef6c322fdada8eeaa910aa9c185f019cb/image.png" alt="image.png" />
 
2. Please remove the extra colon from this:
<img width="1378" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi9BQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06668a79a6d2d6a84c101f8d10948a3585496a7c/image.png" alt="image.png" />

**Comment by Andrew-Vargas-bcgov** [comment]
see latest comment in #1742.

**Comment by ayushdamani** [comment]
Thanks Andrew!
Since the error messages are being fixed in another ticket, @fazil-ey @MikePSA can you please test this ticket?

**Comment by MikePSA** [comment]
@Andrew-Vargas-bcgov please fix these to fit acceptance criteria, thanks.
1. Employee Name, Employee Email, Employee Number is prefilled, but editable. It should not be editable.
2. Submit and Previous buttons need to be rearranged to fit miro design (see comment above)

**Comment by Andrew-Vargas-bcgov** [comment]
added custom prev/next buttons and aligned with submit button.
We have been keeping the employee required fields editable for testing. Unless you all don't need that anymore. Let me know!

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov 
1. Closer together on the right side would be ideal. 
2. Lets keep the fields them editable but before release we must change.

**Comment by Andrew-Vargas-bcgov** [comment]
bhumin added this to the buttons: "added "float-right" custom class to buttons on all pages "next", "submit" and "resubmit". It looks good so far. Small CSS alignment required for "resubmit". We will handle it later."

**Comment by ayushdamani** [comment]
<img width="1548" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS9xQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a240c956ffae8d3b16d3fa7668ec48e5da6c28d8/image.png" alt="image.png" />
Does this look good? @fazil-ey

**Comment by fazil-ey** [comment]
yes i this is good @ayushdamani

**Comment by fazil-ey** [comment]
will test LDB as part of #1771
will make the fields not editable for release, need it to be editable for testing
