### ISSUE TITLE
COI: Authentication methods

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1711]
_**Acceptance Criteria**_
- [ ] COI form should be accessible using IDIR and LDB authentication methods

_**TBD - pre-filling employee name, number, email and supervisor name and email when logging in with LDB**_ (#1710)

**Comment by jerry-ey** [comment]
unassigned myself, as we are focusing on snowplow for now.

**Comment by fazil-ey** [comment]
Need to connect to LDB team to see if we can get any of this info.

**Comment by Abuchana** [comment]
@Andrew-Vargas-bcgov, should this ticket be in the in progress column?

**Comment by Andrew-Vargas-bcgov** [comment]
We have not heard back from LDB yet after the initial contact last week. I will try to connect with them again after the holiday and see if we can get a test account.
This will most likely be resolved after LDB is integrated with the rest of gov in the next few months.
Either way, the dev work has been completed for LDB integration already and we can just do a test with a member of the LDB once UX testing starts.

**Comment by Andrew-Vargas-bcgov** [comment]
we know where to send emails for ldb now. Emailed ldb asking for verification of form access with ldb credentials.
