### ISSUE TITLE
COI: Supervisor Submission Workflow

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1714]
Workflow on supervisor submission 

_**Acceptance Criteria**_
- [ ] On submission by the supervisor the form status should be "APPROVED" 
- [ ] The form should **_not_** be editable after supervisor submits the form

**Comment by fazil-ey** [comment]
Will test after employee submission is tested successfully #1712

**Comment by fazil-ey** [comment]
Will wait for confirmation on the status name "APPROVED", will confirm tomorrow. Everything else looks good

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey <img width="1446" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNStaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f0f0e48fa5f4234187b05ee72706e0854ae3f7a/image.png" alt="image.png" />
