### ISSUE TITLE
COI: Supervisor submission success page 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1715]
Building the success page on submission by supervisor

_**Acceptance Criteria**_
- [ ] On COI form submission by the supervisor, they should see a success page on successful submission as shown in the designs below

**_Design_**

Link to miro - https://miro.com/app/board/uXjVKbE3n_8=/?moveToWidget=3458764585409072538&cot=14

**Comment by ayushdamani** [comment]
@fazil-ey could you please review this page for me?

**Comment by jerry-ey** [comment]
@ayushdamani  is there a "denied"? I saw the design on miro, it only has "approved"

**Comment by jerry-ey** [comment]
I will go ahead with current design.

**Comment by jerry-ey** [comment]
Ready to test: https://digital-journeys-test.apps.silver.devops.gov.bc.ca/success?type=COI_SUPERVISOR_SUBMISSION_APPROVED

**Comment by ayushdamani** [comment]
Looking good - thanks Jerry! 

<img width="1293" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXQwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8c516d2e84f5b8572a5ea26e12e122f8fe77044/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
Looks good, but will PO approve only after the submission piece is implemented

**Comment by fazil-ey** [comment]
looks good

**Comment by MikePSA** [comment]
tested as well, looks good!
