### ISSUE TITLE
COI: CRM ticket

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1718]
On supervisor submission a CRM ticket should be generated for further processing by the HRSC Records teams 

_**Acceptance Criteria**_
- [x] On submission by supervisor, a CRM ticket must be created with the following parameters
    - [x]  Subject should be  _Conflict of Interest Disclosure RE: [employee first name <space> last name]_
    - [x]  Primary contact should be supervisor
    - [x]  Secondary reference should be the employee. Use employee number 
    - [x]  Category should be - _Supervising and Leading People -> Access to Personnel File -> Conflict of Interest Disclosure_
    - [x]  Assigned should be _HRSC - Records_
- [ ] It should include all the following attachments (this is moved to #1720)
- [x]  The auto CRM email should be sent to supervisor after ticket is generated

**Comment by Stella-Archer** [comment]
Ask CRM or Nancy what cat

**Comment by ayushdamani** [comment]
Tested with Bhumin - moving to PO

**Comment by fazil-ey** [comment]
demoed to Karen for the records team and it looks good
