### ISSUE TITLE
COI: Build front-end (Supervisor Documentation and Decision tab)

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1719]
Build the Supervisor Documentation and Decision for COI

_**Acceptance Criteria**_
- [x] The front end of Supervisor Documentation and Decision is built with the content as defined in design below. 
- [x] The record of decision and attachment component should be as per design
- [x] The two checkboxes needs to be mandatory before submission

**_Design_**
Link to Miro: https://miro.com/app/board/uXjVKbE3n_8=/?moveToWidget=3458764585409071958&cot=14

**Comment by ayushdamani** [comment]
Supervisor Documentation and Decision page ready in Miro

**Comment by ayushdamani** [comment]
@fazil-ey can you please test this for me?

**Comment by fazil-ey** [comment]
Can we remove this table from the form? <img width="1694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMENQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34b5af67ddd1fdad3d7c00df413ad16446dbb3db/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good
