### ISSUE TITLE
COI: Building front-end (Employee Disclosure Statement - file attachments 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1720]
After a form is approved by supervisor, we need to send the attachments to CRM 

**Acceptance Criteria**
- [ ] After form is approved, CRM ticket created has all files attached in the form (both by employee and supervisor)
    - [ ] pdf of the form named as _Document Name <space> Employee # <space> Date (YYYYMMDD)_  For e.g. _Conflict of Interest 019594 20240405.pdf_
    - [ ] If attached, the Optional file in Employee Disclosure Statement for question 4, named as is uploaded
    - [ ] If attached, the Optional file in Employee Disclosure Statement for question 6, named as is uploaded
    - [ ] If attached, the Optional file in Supervisor Documentation and Decision, named as is uploaded
- [x] File size and type restrictions are defined  (8MB for each file) 
- [x] Pdf of form should be attached in email to employee on supervisor approval
- [x] File name should be less than 40 characters. Show error is possible otherwise trim the name to 40 characters and upload
- [x] Max file limit is added to all file attachment fields 
<img width="1702" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--036ada876ed0d9aa2e08eae307b0376d1095edd1/Screenshot%202024-04-26%20at%201.28.48%20PM.png" alt="Screenshot 2024-04-26 at 1.28.48 PM.png" />

**Comment by Stella-Archer** [comment]
file upload needs to be handled before initial submission.
this need more work so we have upped the estimate to work on this

**Comment by ayushdamani** [comment]
Tested with Bhumin - moving to PO.
The Conflict of Interest PDF is missing the logo and the title of the form - creating a new ticket for this.

**Comment by fazil-ey** [comment]
1. Supervisor acknowledgements are missing
<img width="1393" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmE2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33fa23e557d61185bf036b9443d48b5f25157b93/image.png" alt="image.png" />

2. add the max file limit AC#5  <img width="1168" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0M2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09fea999f7dce1f80f7259bbeb86b4dcdf5fcf15/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
@fazil-ey 

1. Field on supervisor tab are hidden using custom script to support form validation. **That point needs to handle separately which field we want to show in PDF and which we want to hide.** Here I have only handle PDF creation and attach the same to CRM.

2. **Added file size instruction along with supported formats**, File size validation is already in place and display error like below
<img width="1356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFc3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adb1d8aaf8e533873affa5a6b98406d39d55bbcf/Screenshot%202024-05-06%20at%205.39.41%E2%80%AFPM.png" alt="Screenshot 2024-05-06 at 5.39.41 PM.png" />




**Filename on CRM,**
We set fileName as it is, and display name will be trimmed to 40 characters and then upload to incident on CRM.
Display name will be name in attachment tab on incident,
FileName, that will be a name of file when someone download it to their local machine.

**Comment by ayushdamani** [comment]
The error message for file validation is looking good!

**Comment by bhumin-fw** [comment]
@ayushdamani @fazil-ey 

Andrew has address issue of supervisor acknowledgement issue and that is ready to test on TEST.
We are good with all points here to test and move if looks good.

**Comment by ayushdamani** [comment]
The error message for file validation is looking good - tested this yesterday.
The supervisor acknowledgements are tested in #1761

**Comment by fazil-ey** [comment]
@bhumin-fw can we make the file name like  "Conflict of Interest 019594 20240405.pdf" with spaces

**Comment by bhumin-fw** [comment]
@fazil-ey Yes I guess it should work. I have updated it and worked for me. Please try again with new submission. I have updated changes on DEV and TEST.

**Comment by fazil-ey** [comment]
No space between the words  Conflict of Interest

<img width="261" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelhZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49d11f09064a6ec5caec260cff8ddce02c6e56c3/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
@fazil-ey 
Updated name as "Conflict Of Interest 192173 20240513.pdf".
It is ready to test on DEV and TEST environment.
cc: @ayushdamani

**Comment by ayushdamani** [comment]
File name has been updated - thanks Bhumin!
<img width="415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXZqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7015f87e1a14cc560d49fa0d10f6ae745ad0adf5/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good (assuming .pd is just a character limit in the name column and it is a proper pdf file in the screenshot)
