### ISSUE TITLE
Application - Test Preferred Name change 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1733]
There is a change in how name works. Employees can now set preferred name and that will be reflected everywhere employee name is pulled. When this change goes live we need to test our forms in DJ and ensure we handle all impacts of this change. 

**_To do -_**

- [ ] Ensure all "employee name" field in all forms uses the preferred name if that has been set by the employee
- [ ] Discuss plan of action for 1.10 where we have a manually entered preferred name
     - [ ] Do we remove this field, keep it with a note that it doesnt update anything o no change

**Comment by bhumin-fw** [comment]
Update:
There have been no updates so far on the results. I have tested both APIs that we are using to pull employee information.
I replied to the email with the details and tagged Patrick to see if any configuration changes are needed.

**Comment by bhumin-fw** [comment]
Patrick: For clarity, changes to preferred name in ESS would be captured in the first_name column, there is no new fields being added in the API endpoints to expose the preferred names.

Which means we do not need to make any changes on Digital Journey. Test data are not loaded under the correct email, so we are unable to pull any information on the form to test it. This can only be tested via the API, which was done earlier on May 28.

**Comment by Abuchana** [comment]
[8:54 a.m.] Bhumin Patel (Guest)
email chain to watch
 
RE: Agile App Test with Preferred Name Change - Digital Journey
