### ISSUE TITLE
COI: Content changes for before you begin tab

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1736]
_**Acceptance Criteria**_
- [ ] Hyperlink this "[Disclosing a Conflict of Interest: Political Staff Guideline & Disclosure Form](https://www2.gov.bc.ca/assets/gov/careers/about-the-bc-public-service/ethics/assessing_addressing_coi_political_staff.pdf)"
<img width="1602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFNWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec873e1c8bbf14b678c610426028471ed30941f8/image.png" alt="image.png" />

- [ ] change content

> You can edit the form after submission. It can be accessed in the Submitted forms tab. However, no edits will be allowed after your supervisor reviews and submits your form for documentation

<img width="1602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTJWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c0e1e5173f5be5acde59bbd68d7cf7e3385182a/image.png" alt="image.png" />

- [ ] change content

> - After you submit your supervisor will receive an email informing them that your disclosure is available for review
>  
> - After your supervisor reviews, your form will be automatically sent to the AskMyHR team for documentation. Your supervisor will receive a confirmation email from AskMyHR with the information of the service request.

<img width="1602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24dad1aa5549c6ee7be825577ed2f59e474a0c17/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
ready to test

**Comment by ayushdamani** [comment]
Looking great - thanks Jerry!

**Comment by fazil-ey** [comment]
looks good! 

"After your supervisor ~reviews~ submits, your form will be automatically sent to the AskMyHR"
has context menu
