### ISSUE TITLE
COI: Supervisor Documentation and Decision changes

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1738]
_**Acceptance Criteria**_
- [ ] Update this content

> 
> **About this section** 
> 
> This section is intended for supervisors within the BC Public Service.
> 
> As outlined in the [Conflict of Interest Guidelines](https://www2.gov.bc.ca/assets/download/91C81FC2530F4FE89A07A18961793F13), you have a responsibility to review the disclosure form in a timely manner and discuss it with the employee.
> 
> This process may include:
> - Further discussion with the employee
> - Consultation with your [ministry ethics advisor](https://www2.gov.bc.ca/gov/content?id=83A2B60ACB024A9EA47C5ABC89F709E6#EthicsAdvisors) or the [BC Public Service Agency](https://www2.gov.bc.ca/gov/content?id=BA01C2B7E36D4AD9A435EF9D36972023)
> 
> If you have any questions about this process, or your role, refer to [Manage a conflict of Interest disclosure in the BC Public Service](https://www2.gov.bc.ca/gov/content?id=1B0F52A878544CD1A28C7F68F6EF669A).
> 
> **Record of Decision**
> 
> Please summarize any discussions and decisions that have taken place regarding this matter. Also indicate how you communicated this decision to the employee. Attach any files supporting this decision below.
> 
> [text area]
> 
> Attachments supporting this decision: 
> 

- [ ] The text area should be mandatory i.e "Please summarize any discussions and decisions taken place regarding this matter. Also indicate how you communicated this decision to the employee. Attach any files supporting this decision below." should be mandatory
- [ ] Attachment should be optional

- [ ] Add hyperlink in the checkbox

> I confirm that the employee has disclosed the involvement of a third party in this conflict, and attached the [Third Party Authorization form ](https://www2.gov.bc.ca/assets/download/70F57B797A4341CE81B5E3DDC78907CE)if a third party is involved.

- [ ] Change "Supported file types: .eml, .msg, .docx, .pdf, common image formats" to "Supported file types: .pdf, .png, .jpg/jpeg, .docx, .eml, .msg" 
<img width="1236" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGlWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--292a2e644da0d86c93a81936c3154a16c024bf0f/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
ready to test

**Comment by ayushdamani** [comment]
Looking good, thanks Jerry!
<img width="1006" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05cd4a74f6b48afbb6a9b90ae5ef495f18fe6f5a/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
@jerry-ey  can you change this error message to "This field is required"

<img width="1768" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzJyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30196edb46ff8ebf81bc1aaae312bf7f2bde3c61/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
<img width="1150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1N3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b396b69ef6e6ae9eea12784f3836b7e959c8e89f/image.png" alt="image.png" />

Moving to PO

**Comment by fazil-ey** [comment]
looks good
