### ISSUE TITLE
COI: Supervisor should not be able to edit employee fields

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1739]
_**Acceptance Criteria**_
- [x] Make all employee fields in all employee tabs not editable for supervisor in the review and process tab. Only the fields in "Supervisor Documentation and Decision" tab should be editable for Supervisor
- [x] Supervisor should be able to see the employee fields but not edit

Note for testing - end to end test, all fields that are added my employee are not removed or hidden due to this. Review pdf as well to see if all fields are there or not

**Comment by jerry-ey** [comment]
ready to test

**Comment by ayushdamani** [comment]
Tested - moving to PO

**Comment by fazil-ey** [comment]
Cant edit fields. Need to check pdf but unable to submit

**Comment by fazil-ey** [comment]
works well and employee fields are not missing inpdf
