### ISSUE TITLE
COI: Emails edits

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1740]
Update the subject and content of the emails 

_**Acceptance Criteria**_
- [ ] Email to Supervisor on employee form submission

> SUB: [Employee name’s] Conflict of Interest Disclosure Form for Review
> Content: This is to inform you that a new Conflict of Interest Disclosure form has been submitted by [employee name] and is ready for your review. The form can be found in the "Review & Process" tab on [Digital Journeys](https://digital-journeys.apps.silver.devops.gov.bc.ca/task). After you review and submit, the disclosure will be automatically sent to the AskMyHR team for documentation. You will receive a confirmation email from AskMyHR with information about the service request created for documentation. 

- [ ] Email to Employee on employee form submission

> SUB: Conflict of Interest Disclosure Form Submitted for Review By Your Supervisor
> Content: This is to confirm that we have received your Conflict of Interest Disclosure. Your form has been forwarded to your supervisor for review. If required, your supervisor may discuss your disclosure with you. Once your supervisor approves your form, we will notify you via email. You can also check the status of your application in the "Submitted Forms" tab on [Digital Journeys](https://digital-journeys.apps.silver.devops.gov.bc.ca/form).  

- [ ] Email to Employee on supervisor form submission

> SUB: Conflict of Interest Disclosure Form is Documented
> Content: This is to confirm that your disclosure for conflict of interest has been reviewed and documented. You can find a pdf of your form attached in the email. Please save the copy for future reference. You can also find your form in the 'Submitted Forms' tab on [Digital Journeys](https://digitaljourneys.apps.silver.devops.gov.bc.ca/form) for up to 1 year from now.

**Comment by fazil-ey** [comment]
Note to self - add 90 days in email after confirming with COI team

**Comment by ayushdamani** [comment]
Email content looking good!

**Comment by fazil-ey** [comment]
unable to submit the form. will validate once thats fixed

**Comment by fazil-ey** [comment]
Additoinal content change 

In - [ ] Email to Employee on employee form submission  change "Once your supervisor approves your form, we will notify you via email." to "Once your supervisor submits your form, we will notify you via email."

**Comment by ayushdamani** [comment]
Updated ✅
<img width="1140" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXJGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f789bf40692534f8a08b30f2cfb1a94c4584250/image.png" alt="image.png" />
