### ISSUE TITLE
COI: Add name of tabs

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1741]
**_AC_**
- [ ] Add the name of the tab in the form for Employee Acknowledgements and Employee Disclosure Statement tabs

Example
<img width="1160" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMytWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d5918b99c3c2b73f308e5ae28f86cfedd04ce77/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
Ready for test

**Comment by ayushdamani** [comment]
Both tabs have been created

**Comment by fazil-ey** [comment]
@ayushdamani Can you add a space here below the heading <img width="968" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2lyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16f5f0ac41b883c7e2ec5717f805342718e78e79/image.png" alt="image.png" />
<img width="826" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd21yQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e35d5d7a988b9832ea481499622ae6ae6a18022/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
space added

**Comment by ayushdamani** [comment]
Space has been added - moving to PO

**Comment by fazil-ey** [comment]
looks good
