### ISSUE TITLE
COI: Error message improvements

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1742]
**AC**
- [ ] Change this 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFdWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a890a49e7c70a79d836961609fee66061696466/image.png" alt="image.png" />

to  

> All Employee Acknowledgements are mandatory - Select all items

- [ ]. Add quotation to the questions like shown below 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHlWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51bb5bbdd13e825853ee21b4a442df43c30596d6/image.png" alt="image.png" />

> Please fix the following errors before submitting.
> 
> "1. Your job duties or activities relevant to the possible conflict" is required
> "2. Your private interests relevant to the possible conflict" is required
> "3. A description of the steps you will take to mitigate this possible conflict" is required
> "5. Are you disclosing personal information related to a third party? If you are disclosing personal information of a third party you must obtain their permission before making your disclosure. You may also attach other relevant documents." is required

**Comment by Andrew-Vargas-bcgov** [comment]
Checkbox Components display the banner message with a colon between the component label and the component error.  While the field level error message only shows the error message AND NOT the field label. This is different from other components.

The other fields in this ticket display the errors correctly now.

**Comment by ayushdamani** [comment]
Error messages are fixed:
<img width="1247" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTNYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4e54c97799d14c1fc17d71467dbbe2b9daf48d7/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good
