### ISSUE TITLE
COI: Content changes for employee and supervisor success page

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1744]
Content Changes for Success Page 

**_AC_**
_Employee Success Page_
- [x] change in "Your form has been sent to your supervisor"

> change 
> You can modify your submission prior to receiving approval from your supervisor. You can find your submitted form in the  Submitted Forms  tab
> 
> to 
> You can modify your form prior to final submission by your supervisor. You can find your submitted form in the  [Submitted Forms](https://digital-journeys.apps.silver.devops.gov.bc.ca/application) tab

- [x] change in next steps

> change 
> After your supervisor approves, you will receive a confirmation and a copy of your form on your email. Your form will be automatically forwarded to AskMyHR for further processing
> 
> to 
> 
> After your supervisor submits, you will receive a confirmation and a copy of your form on your email. Your form will be automatically forwarded to AskMyHR for further processing

_Supervisor Success Page_

- [x] change heading

> change 
> Conflict of Interest Disclosure Form approved
> 
> to 
> Conflict of Interest Disclosure Form Submitted for Documentation

**Comment by jerry-ey** [comment]
ready to test

**Comment by ayushdamani** [comment]
Jerry, could you please check if there is extra space before and after "Submitted Forms"?
<img width="1237" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHkxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1b2dda95b1492fb1529ab161cc047326ae4c3d0/Screenshot%202024-05-03%20124944.png" alt="Screenshot 2024-05-03 124944.png" />

**Comment by jerry-ey** [comment]
space removed, thanks

**Comment by ayushdamani** [comment]
Thanks Jerry - moving to PO!
