### ISSUE TITLE
Application - Publicly available forms on DJ

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1747]
We want to find a way to build a form on DJ that is publicly available i.e can be accessed without any authentication. 

1. Such forms do not need to have drafts/autosave or submitted form history. 
2. They will also not have any prefilled info, supervisor approvals or connection to database. 
3. However, they should have the ability to send an email with the pdf of the form after submission.

**Comment by bhumin-fw** [comment]
**Feature Addition: Guest Login**

On the development ([DEV](https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form)) environment, I've implemented a "Guest Login" feature along with an open form. Simply click on the "Guest Login" button, and you'll be logged in as a guest user. Technically, this means you'll be logged in as a pre-registered user with the username "guest."

**Key Points:**

1. **Draft Creation Requirement:** To submit the form, users need to create a draft first.
2. **Form Activity Duration:** The form will remain active for 1-2 minutes while the workflow prepares a PDF from the submitted data.

**Setup:**

- I've added a condition to minimize unnecessary drafts. Drafts will only be created if the user fills in the First Name and Recipient Email fields (we can choose any 2-3 fields to trigger draft saving).
- Currently, submissions are deleted after 5 minutes. This duration is set for testing purposes, but we can reduce it to 1 minute.

**Concerns:**

1. **Draft Visibility:** If a user fills out the entire form, including all required fields, it will be saved as a draft. This means other guest users will see the same form in their drafts. We'll need to add instructions on the form to address this.
2. **Submission Visibility:** Other guest users can view submitted forms for up to 1 minute in the "Submitted Forms" tab. If necessary, we can reduce this visibility duration to 15-20 seconds.

@fazil-ey Please review on your end, and let me know your thoughts on it. This is solely for testing purposes, and we'll need to allocate 3-5 story points to enable guest login. Additionally, form creation will require additional efforts.

**Comment by fazil-ey** [comment]
@bhumin-fw - can we hide the drafts and submitted form tabs if you are guest. So you can only see the form and fill the form. But no auto-save or see drafts or submitted forms or anything.

**Comment by bhumin-fw** [comment]
I was looking for that option as all detail controlled by roles and permissions. Role and permission we need to keep as regular user only. I'm looking other possibility to add additional permission and use them to determine it is a guest user.
Auto-save is must in submission. We can reduce no of draft by adding conditions to start auto-save form.

**Comment by bhumin-fw** [comment]
@fazil-ey  We are able to hide draft and submitted form from the navigation bar for guest user. It can be manage same as manager/reviewer role to see "review and process" tab. I haven't uploaded that on DEV environment for review.

I guess we are good with explore part, Let's close this ticket and add new ticket in which we'll implement given solution.
