### ISSUE TITLE
ERIP: Introduction Page

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1749]
**User Story**
As an employee, I want to be able to access the form and work through it so I can submit the form successfully.

**Acceptance Criteria**
- [ ] Build the introduction section of the form. Link to Miro board - https://miro.com/app/board/uXjVKMReQvg=/?moveToWidget=3458764587857038152&cot=14
- [ ] Match the content and formatting from this section
- [ ] Please show this in the attached PDF after submission

**Comment by ayushdamani** [comment]
The form is built in DEV and is ready for test.
The form has not been built in TEST yet, since it is down due to maintenance.
I'll move this ticket to the QA column once both TEST and DEV are ready for test.

**Comment by ayushdamani** [comment]
Ready for test in TEST & DEV

**Comment by fazil-ey** [comment]
fix the highlighted changes, right side is whats on DJ 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0FaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--becc4d7ada041c470345ddfcb375e11bb215e095/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Fixed in TEST
<img width="1220" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVEyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f7cae6570475766f29003167d02b2d3a53f6292/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
it should be gov.bc.ca

<img width="820" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTgzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65657952f24926e72db3bec0d7fdf0addd8ef66b/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Fixed. Please test again.

**Comment by fazil-ey** [comment]
looks good
