### ISSUE TITLE
ERIP: Employee Information Section

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1750]
**User Story**
As an employee, I want to be able to access the form and work through it so I can submit the form successfully.

Tasks:
Build the Employee Information section of the form.
Link to Miro - Miro board - https://miro.com/app/board/uXjVKMReQvg=/?moveToWidget=3458764587857361029&cot=14

**Acceptance Criteria**
- [ ] Make all the fields except 'Country' required.
- [ ] The certification checkmark is a required field - please make the date coded and not just the current year.
- [ ] We are not pulling data, thus the fields need not be auto-populated
- [ ] Please show this in the attached PDF after submission

**Comment by ayushdamani** [comment]
The form is built in DEV and is ready for test.
The form has not been built in TEST yet, since it is down due to maintenance.
I'll move this ticket to the QA column once both TEST and DEV are ready for test.

**Comment by ayushdamani** [comment]
Front end has been created.
@Andrew-Vargas-bcgov can you please make the date of the certification coded, so it reflects the current year?

**Comment by fazil-ey** [comment]
i notice postal code is optional. It should be mandatory

<img width="1146" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVpFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a209c51658b44a391fad069faf7b0c99accfd435/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
Postal code is okay, but email address is now optional

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmRUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--362a2bbc914e2f73a479412975c4fb400d598dc3/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Updated --
<img width="1271" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0phQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b875160411827f0dcd5ca1d59ce1656185dab17/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good
