### ISSUE TITLE
ERIP: Payment Section

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1752]
User Story
As an employee, I want to be able to access the form and work through it so I can submit the form successfully.

Tasks:
Build the ERIP Payment section of the form.
Link to Miro - https://miro.com/app/board/uXjVKMReQvg=/?moveToWidget=3458764587860184996&cot=14

**Acceptance Criteria**
- [x] Make the required fields compulsory
- [x] If selected 'Yes', for any of the questions, display the required question underneath - logic required
- [x] Match the content and formatting from this section
- [ ] Please show this in the attached PDF after submission

**Comment by ayushdamani** [comment]
The form is built in DEV and is ready for test.
The form has not been built in TEST yet, since it is down due to maintenance.
I'll move this ticket to the QA column once both TEST and DEV are ready for test.

**Comment by ayushdamani** [comment]
Ready to test on TEST & DEV

**Comment by fazil-ey** [comment]
RRSP should only come if Do you want some or all of your ERIP payment to be transferred directly to your RRSP? is Yes. Added this issue to #1781. 

Otherwise Payment section looks good
