### ISSUE TITLE
COI: PDF of the form in CRM is missing Title & Logo

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1753]
**Acceptance Criteria**
- [ ] Add the BC Gov logo and Title of the form to the Conflict of Interest Form PDF which is attached to the CRM.

<img width="1118" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFcxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4e5779d4b8813cb4b5f48827692a60439a52e2c/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
Added Logo and form title on form PDF that attached with CRM ticket. Ready to review.

**Comment by ayushdamani** [comment]
Title & Logo now appears in the PDF ✅
<img width="1275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a32b9c1afbb499dec37e745d50a8e544734fef36/image.png" alt="image.png" />

@fazil-ey alignment okay?

**Comment by fazil-ey** [comment]
looks good
