### ISSUE TITLE
COI - Make the file names look like hyperlink

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1755]
**_AC_**
- [ ] File names should look like a clickable hyperlink for both supervisor and employee. 
- [ ] if possible, cursor should change to a hand pointer

**Comment by jerry-ey** [comment]
Looks like it's already working. I think Bhumin had added this.

After your supervisor reviews your disclosure, makes a decision on the outcome and submits, your form will be automatically sent to AskMyHR for inclusion on your personnel file. Your supervisor will receive a confirmation from AskMyHR that the service request has been created

**Comment by ayushdamani** [comment]
Yes it is working - the hyperlink and the hand pointer

<img width="1529" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejdxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04ff1db995a2a21fa33c6e04d893d45f9cb4f1f2/image.png" alt="image.png" />
