### ISSUE TITLE
COI - Add employee number validation

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1756]
**_AC_**
- [ ] In Employee Sign Off Statement, employee number must be a 6 digit number. 
- [ ] Error message should be "Employee number invalid, must be a 6 digit number"

**Comment by ayushdamani** [comment]
Tested successfully
@jerry-ey could you please fix the error messages for validation and maybe remove  "\d{6}"
<img width="1234" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1BYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc2209edafcef4347bd39a8600f89c7bb59b590c/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
fixed,
<img width="678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVRkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--840e9d454e667bc72d1f42ad0dfb262c88401f27/CleanShot%202024-05-14%20at%2010.23.29.png" alt="CleanShot 2024-05-14 at 10.23.29.png" />

**Comment by ayushdamani** [comment]
Thanks Jerry!

**Comment by fazil-ey** [comment]
looks good
