### ISSUE TITLE
Cold/Flu - Update content

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1758]
_**AC**_
- [ ] Update "Registration for the 2024 Flu Clinic Program is now open" to "Registration for the 2024 Influenza Worksite Clinic Registration is now open"

<img width="1628" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlc2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2296db09fb44a428c2a68364e6b6be20f90930b7/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
ready to test

**Comment by ayushdamani** [comment]
Updated!
<img width="783" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2pYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d4c1fc4bf5b90a199429475a4ed0d58b64d262c/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good

**Comment by Stella-Archer** [comment]
Live in Prod look perfect - closing tix
<img width="1315" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWM0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb9e43c29987ba166134d61d2c20e702f0b474cf/image.png" alt="image.png" />
