### ISSUE TITLE
Mat/Pat - Test CRM category 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1759]
Test what happens to category when a ticket is created in the CRM through the API from DJ. We observed it was not the lowest level, but the parent category Maternity, parental & Adoption

We found 2 things - 
1. We were not setting it to the lowest category 
2. We were resetting to the parent category Maternity, Parental & Adoption on resubmission

To fix the issue of TES payroll not being able to see the ticket on resubmisson, do the following 

**AC**
- [ ] Set the category to Maternity leave if taking maternity or maternity + parental leave
- [ ] Set the category to Parental leave if takin only parental leave. 
- [ ] Do not reset category when updating the ticket on resubmission

**Comment by MikePSA** [comment]
@fazil-ey to confirm with Connie for category options

**Comment by ayushdamani** [comment]
If require, add additional ticket to update the form data. 
Approx estimation is 1 story point.

**Comment by bhumin-fw** [comment]
It is ready to test on TEST environment.
@fazil-ey @ayushdamani 
Now we are setting the category to a lower level from the form itself. We hope that no category changes are required from the CRM admin team. However, we need to keep the code where the category can be updated if there are any changes in the application, such as a leave type change due to any reason.
Product and AssignTo will not be updated at the time of updating the CRM ticket.

**Comment by ayushdamani** [comment]
Stella tested - on submission, the page keeps loading but does not submits.

**Comment by Stella-Archer** [comment]
YAY worked! PO/Closing tix
<img width="821" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMko5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6522203facd56ec655cbd7b43841ad49488bc912/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
BUG will process to CRM if:
1/ you are selecting only one type of leave (and employee has same email as supervisor)
2/ 2 types of leave if the employees email is different from supervisor

Will NOT process if mat and par leaves are selected an Employee and supervisor have same email address

**Comment by fazil-ey** [comment]
verified by Connie
