### ISSUE TITLE
COI - Add email validation

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1760]
**_AC_**
- [ ] In Employee Sign Off Statement, employee and supervisor emails must be BC gov emails (gov.bc.ca)

**Comment by fazil-ey** [comment]
Decision made with COI team to include only gov.bc.ca and if any other group asks add them after we go on prod

**Comment by jerry-ey** [comment]
ready to test. And you can add further domain in the future when needed. 
simply put in "validation" --> "custom validation" --> the first line of code is an array, add your new domain there.

**Comment by ayushdamani** [comment]
Test successful - moving to PO

**Comment by fazil-ey** [comment]
looks good
