### ISSUE TITLE
COI : PDF of the form missing supervisor confirmation fields 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1761]
Bug from #1720, the supervisor acknowledgements are missing int he pdf. 

**AC**
- [x] Form pdf has the supervisor acknowledgements 

<img width="1393" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMERBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45f1f1bc8b5e899be29dc108bb2a1b6aa9ec7443/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
The PDF now has the supervisor acknowledgements ✅
<img width="1285" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFhMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86d95d391a754a1eb2a4b2f3bf5a4bc04d63780b/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks goos
