### ISSUE TITLE
Fix how we handle workflow failures 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1762]
if there is a workflow failure, The status of the form is updates to APPROVED in submitted forms but it remains in the tasklist of the supervisor as NEW. This can potentially cause confusion where an employee thinks their form is submitted for documentation or leave application is submitted to AskMyHR but in reality it is not. 

Video - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Conflict%20of%20Interest/Test%20recordings%20and%20screenshots/Screen%20Recording%202024-05-06%20at%203.48.41%20PM.mov?csf=1&web=1&e=VOvE1I

Explore potential solutions - 

1. show error message to supervisor if the CRM ticket is not created successfully. 
2. if there is an error do not show "APPROVED" to employee

**Comment by bhumin-fw** [comment]
Once form successfully approved, That will be removed from "review and process" tab. I have requested access to review above video. Mean while you can review this again and share your comment on it.

**Comment by fazil-ey** [comment]
Similar to telework, since after submission by supervisor edits are not allowed, the task will be removed from the Review and Process tab, therefore approved forms will not show there. The forms we were seeing with the new status were forms where the workflow failed.

**Comment by jerry-ey** [comment]
Discussed with Bhumin and got the info I need. will work on the exploration after coming back from vacation.

**Comment by jerry-ey** [comment]
- For frontend, we have idea how to implement "close loader" and "show error message".
- For backend, Bhumin and I still investigate the part how application status is getting updated to "APPROVED"

**Comment by jerry-ey** [comment]
Draft PR for frontend: https://github.com/bcgov/digital-journeys/pull/1836
(Removing the loader and showing error toast message)

**Comment by jerry-ey** [comment]
In order to use the remain time effectively, I have unassigned myself and discussed handing over the task to Bhumin.

**Comment by bhumin-fw** [comment]
A separate ticket has been created to revert the Form.io status and data. [#1874](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1874)

We will display an error message to the user if a timeout error occurs as an initial step.

**Comment by fazil-ey** [comment]
CLosing this because the action for this will be done in #1874
