### ISSUE TITLE
COI: Form does not always open in the Employee Disclosure Statement tab in Review and Process tab

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1763]
Form does not always open in the Employee Disclosure Statement tab in Review and Process tab

Video - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Conflict%20of%20Interest/Test%20recordings%20and%20screenshots/COI%20tab%20bug.mov?csf=1&web=1&e=kQfWmi

**AC**
- [ ] COI forms on the Review and Process tab should open in the Employee Disclosure Statement tab

**Comment by Andrew-Vargas-bcgov** [comment]
Ready to test. Can you try making 2-3 new forms to test it with?

**Comment by ayushdamani** [comment]
Tried with 3 submissions, working great - moving to PO
