### ISSUE TITLE
Telework: Ergonomic Changes

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1764]
Chris Grellmann is currently working on a project rebuilding the Ergonomics E-Tool and he is looking to correct some information regarding ergonomics on the Telework Agreement form.

**Acceptance Criteria**
We were looking at two spots under ‘8. Occupational health and safety’.
- [x] Changing the link in – “Ergonomic considerations” to link to here - https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/health-safety-and-sick-leave-resources/workplace/planning/ergonomics and changing the link text to ‘Ergonomic Resources’
- [x] Changing, “WCB liability for work-related accidents will continue to apply during the telecommuting work schedule as defined in this agreement.” To "Eligibility for WorkSafeBC compensation for a work-related injury during the telecommuting work schedule as defined in this agreement will be determined by WorkSafeBC"

**Comment by ayushdamani** [comment]
Ready for test in TEST & DEV!

**Comment by Stella-Archer** [comment]
Live in PROD looks perfect!
<img width="1513" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVk0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7630cd4dc0b93ab177dc3d9a1b5b6ef8d714ea65/image.png" alt="image.png" />
