### ISSUE TITLE
 COI: Content edits in Supervisor Documentation and Decision

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1768]
_**Acceptance Criteria**_
- [ ] Change the content in Supervisor Documentation and Decision as follows

<img width="1758" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejdOQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06a125413f04772d43355e438ec3c47093dc5d42/image.png" alt="image.png" />

>  As outlined in the [Conflict of Interest Guidelines](https://www2.gov.bc.ca/assets/download/91C81FC2530F4FE89A07A18961793F13), you have a responsibility to review the disclosure form in a timely manner, discuss it with the employee and document your decision.

**Comment by ayushdamani** [comment]
Looking good
<img width="1123" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelRxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed7748172b5ba5f73601cdcb68180dc7d1f65bc0/image.png" alt="image.png" />
