### ISSUE TITLE
COI: Content edits in Supervisor Success Page

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1769]
_**Acceptance Criteria**_
- [ ] Change the content in Supervisor success page as follows

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEROQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c760383034e07668215d199b2dbc8110f219d5b/image.png" alt="image.png" />

>  Conflict of Interest Disclosure Form Submitted Successfully
> - The form will be automatically sent to AskMyHR for inclusion on the employee's personnel file. You will receive a confirmation from AskMyHR that the service request has been created.

**Comment by ayushdamani** [comment]
Updated 
<img width="1242" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e005c4867825bbf7cad2389ff3e506d52a78445a/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good
