### ISSUE TITLE
COI - Multiple File Attachments

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1770]
We expect multiple attachments particularly for the supervisor. So we want to include the ability for employees and supervisors to attach multiple files. We do not expect them to be large files 1.5 MB is sufficient for each file. 

**_AC_**
- [x] Employee and supervisor should be able to upload multiple attachments (atleast 3)
- [x] Each file should be at least 1.5 MB 
- [x] Appropriate error messages should be shown if there is an issue with the upload

**Comment by MeghanStothers** [comment]
Bhumin working error message

**Comment by bhumin-fw** [comment]
@fazil-ey (below changes are enabled on DEV and TEST both)

I've added code that allows for four files (specifically for the supervisor tab), with each file having a maximum size of 2MB. Additionally, we can extend this to accommodate up to six files, each with a 2MB limit.

Validation regarding the file count will only trigger when you click on the submit button

**_How it different._**
**File component error looks like below (alert box with pink background)**
<img width="1356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm5rQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--717360b08c5d1b95a854d1590fad21c274876c8d/image.png" alt="image.png" />

**Form field validation looks same like other error on form for text field/component**
<img width="903" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnprQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2ad546cb9ccbb28a366993971f11a1ee6593595/Screenshot%202024-05-15%20at%201.54.50%E2%80%AFPM.png" alt="Screenshot 2024-05-15 at 1.54.50 PM.png" />



Added for your review. Please let me know your thoughts. Also, inform me if multiple file uploads need to be enabled for the employee-related file upload field.

**Comment by bhumin-fw** [comment]
@fazil-ey @ayushdamani 
It is ready to be tested on the DEV and TEST environments. For employees, I have set a maximum of three files, up to 2 MB each, for both fields (point 4 and point 6). For supervisors, it will allow a maximum of four files, with each file being up to 2 MB.

**Comment by ayushdamani** [comment]
Working great - thanks Bhumin!

Error Messages for employees -
<img width="1219" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHY4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ef245a3e844a1c5179883be5d389746c5c02c26/image.png" alt="image.png" />

Error messages for supervisor -
<img width="903" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWI4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af82642ecb8993e76c79b286b8a4e4ac353110d6/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
tested multiple attachments, noticed if the file is too big, it gave an error but allowed submission. Creating a different bug for it
