### ISSUE TITLE
COI - LDB workflow

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1771]
We do not want a CRM ticket to be created for LDB folks. We want it to be sent directly to LDB an LDB mailbox. LDB mailbox to be confirmed. 

**AC**
- [ ] After supervisor approves, send pdf of the form, and attachments to [email TBD]
- [ ] Email content should be as follows 
 

> SUB: TBD
> TBD

**Comment by Stella-Archer** [comment]
@Stella-Archer tella confer with client about any different actions for LDB

**Comment by Andrew-Vargas-bcgov** [comment]
need to do an explore ticket for attaching multiple files. rest of this is complete and waiting on email contents and ldb mailbox.

**Comment by Stella-Archer** [comment]
Cantact destination and email edits are being gathered in this document > https://bcgov.sharepoint.com/:w:/r/teams/03991/Shared%20Documents/Conflict%20of%20Interest/2024%20Project%20Files/CoI%20UX%20test%20subjects.docx?d=w371abe9d00724210bc61235daebed56c&csf=1&web=1&e=jpAUed

**Comment by Andrew-Vargas-bcgov** [comment]
Test this on dev. I have set it so all users go through the ldb workflow for testing. Just use your normal @gov.bc.ca email. Let me know when you are done and i will change it back.

**Comment by ayushdamani** [comment]
<img width="1283" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUFuQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f1fc2d2004030ee83043f31d5cccd30fd30aa97/image.png" alt="image.png" />

Tested and received the LDB email!

**Comment by Andrew-Vargas-bcgov** [comment]
changed the flow back so idir and ldb receive their respective emails. looks good to go.

**Comment by fazil-ey** [comment]
Tested the employee emails, was not able to test supervisor emails or the email to LDB team. We can test that when we test with LDB employees

**Comment by Stella-Archer** [comment]
Worked great @Andrew-Vargas-bcgov  - can move to PROD for LDB testers, we can't test the supervisor side until then

**Comment by Stella-Archer** [comment]
@Andrew-Vargas-bcgov after we are finished testing with LDB people the final email is sent to > to ethicsadvisor@bcldb.com 
as specified in the edits document >
https://bcgov.sharepoint.com/:w:/r/teams/03991/Shared%20Documents/Conflict%20of%20Interest/2024%20Project%20Files/Conflict%20of%20interest_LDB%20Edits.docx?d=w18353bea5919421698111bcacb9664e1&csf=1&web=1&e=3MBQmk
