### ISSUE TITLE
Mat/Pat - Saturday Checkbox in review page

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1775]
Add the saturday checkbox in the review page as well

Copy for checkbox
> I understand that since I chose to start my leave on [day], [date] I will not be paid for the week of [Sunday], [Date] to [Saturday], [Date]. Since EI pay periods run from Sunday to Saturday, and partial weeks are not paid, choosing a day that is in the middle of the week would mean I would not get EI and leave allowance for that week. 

AC
- [ ] If there is a saturday checkbox in the Maternity leave - Start date or Parental leave - Start date tab then show it in the Review page as well. Any change in review page should reflect in the Maternity leave - Start date or Parental leave - Start date tab and visa versa

If there employee makes a change in the start date in the Review page
- [ ] For employees taking maternity leave and parental leave or only maternity leave,  add the checkbox under the "Start Date" field in Maternity Leave Information section if they choose a date that is not on a Saturday. 
    - [ ] Do not add the checkbox in parental leave information section if taking both maternity and parental leave
- [ ] For employees taking only parental leave,  add the checkbox  under the "Start Date" field in Parental Leave Information if the choose a date that is not on a Saturday.
- [ ] Checkbox should be mandatory if it is shown

Note for testing - Currently, before this ticket is implemented, the checkbox in the start date tab came in when the value was changed in review page, however when submitting, it did not show the error in review page, but submit also did not go through. The error cold only be seen in the start date tab. This ticket should resolve that issue.

**Comment by jerry-ey** [comment]
will work on it once I come back from vacation.

**Comment by jerry-ey** [comment]
ready for test, thanks

**Comment by ayushdamani** [comment]
Taking both Mat and Par:
<img width="763" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVowQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38f7453b8df0d1f0a56dd689ece2dbbb1dc3da6e/image.png" alt="image.png" />

Taking only Mat:
<img width="773" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXgwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ce7ae0db100d0aa73fb866b59c0c8c41bf6586f/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Taking only Par:
The checkbox shows up here:
<img width="1527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelYwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6936b2906235750ed7ad6dec4d6563d70809bf90/image.png" alt="image.png" />

But it does not show on the review page:
<img width="735" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelowQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8c2007ef7ce37e057cfb2335c6845ff9cb317c4/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
@ayushdamani  good catch, please review again, thanks.

**Comment by ayushdamani** [comment]
Thanks Jerry!
<img width="678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnQ5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb8a31cc3c8bb07bab4e5321c535a2078f7ac7e0/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
works well

**Comment by ayushdamani** [comment]
Closing
