### ISSUE TITLE
Mat/Pat - Simplify email logic

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1780]
We have a lot of different emails versions that we send on approval. It is complex and difficult to maintain as new edits might not be implemented in all versions. There is opportunity to simply the email logic. 

**Task**
- [ ] Work with devs to map out the logic implemented right currently and solution ways to improve it

**Comment by Andrew-Vargas-bcgov** [comment]
got it down from 17 variants to 11.

**Comment by Abuchana** [comment]
@fazil-ey Do we want to reduce these further?

**Comment by Andrew-Vargas-bcgov** [comment]
Let me know if we want to try and get the number of email variants down further. I have reduced it to 11 so far. The others differ in either a sentence or a paragraph at most.
If this is fine, the work has been completed. If we want to try to get it down further, we will have to have the discussion @fazil-ey mentioned during backlog grooming.

**Comment by fazil-ey** [comment]
#2 and #5 in the DMn table are not needed

**Comment by Andrew-Vargas-bcgov** [comment]
removed 2 and 5. We are down to 9 now :).

**Comment by fazil-ey** [comment]
Worked with andrew on it. Looks good in the DMN table
