### ISSUE TITLE
ERIP: RRSP Information Section

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1781]
User Story
As an employee, I want to be able to access the form and work through it so I can submit the form successfully.

Tasks:
Build the 'RRSP Information' section of the form.
Link to Miro - https://miro.com/app/board/uXjVKMReQvg=/?moveToWidget=3458764589196444078&cot=14

**Acceptance Criteria**
- [ ] Make the required fields compulsory
- [ ] The 'Country' field needs logic
- [ ] Match the content and formatting from this section
- [ ] Please provide this information in the PDF attached after submission

**Comment by ayushdamani** [comment]
The form is built in DEV and is ready for test.
The form has not been built in TEST yet, since it is down due to maintenance.
I'll move this ticket to the QA column once both TEST and DEV are ready for test.

**Comment by ayushdamani** [comment]
Ready to test on TEST & DEV

**Comment by fazil-ey** [comment]
RRSP should only come if this Do you want some or all of your ERIP payment to be transferred directly to your RRSP? is Yes

**Comment by fazil-ey** [comment]
Country needs to be optional, based on the form in Orbeon QA https://forms2.qa.gov.bc.ca/forms/content?id=AFF58A28D2314CC9B2AFCD85B138038B

**Comment by fazil-ey** [comment]
tooltip text is overlapping 
<img width="908" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTAzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c073d4f91234e2b632e5fb7788bf3fa696bd5c7/image.png" alt="image.png" />


Use this style for the Attention to tooltip that we have in mat/pat, OR fix the overlapping in some other way
<img width="1178" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXczQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e186484ec7ee05a269efc7d96e270b22a83bac0f/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
@ayushdamani  we can also add the tooltip text like it is in telework
<img width="1082" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlU4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e3da76d1955ca9a12a2748bfe79d59c06c2e8ca/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Updated:
1. Country field under RRSP in now optional
2. The tooltip now opens a popup to display the content

**Comment by fazil-ey** [comment]
looks good
