### ISSUE TITLE
ERIP: Signature Section

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1782]
User Story
As an employee, I want to be able to access the form and work through it so I can submit the form successfully.

Tasks:
Build the 'Signature' section of the form.
Link to Miro - https://miro.com/app/board/uXjVKMReQvg=/?moveToWidget=3458764589196670688&cot=14
We do not need the Corporate email inbox section from this page

**Acceptance Criteria**
- [ ] Make all sections compulsory
- [ ] Match the content and formatting from this section
- [ ] Please show this section in the attached PDF after submission

**Comment by ayushdamani** [comment]
Ready to test

**Comment by fazil-ey** [comment]
looks good.

**Comment by ayushdamani** [comment]
Got it working
<img width="677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU04QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bed2fa48e66f1b6708986e7139df2191d4cda46/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks goos
