### ISSUE TITLE
COI - File to big, shows error but still submits

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1784]
When a file greater than max file size limit is uploaded, it shows the error, but it appears like the file uploaded. Also when you submit it allows submission but the file doesn't actually go through. 

<img width="1112" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGorQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c18706dbb623479159488b51f1c588726244563/image.png" alt="image.png" />

Video - 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFQrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cd8aaaee7e8dd81262d874286bfee0c16554ab5/Screen%20Recording%202024-05-21%20at%203.40.16%20PM.mov)

**AC**
- [ ] We should not allow submission if the file uploaded is too big and and the file should not appear to have been uploaded

**Comment by bhumin-fw** [comment]
@fazil-ey 
It's ready for your review on TEST. Since DEV is still down, I've moved it to the test environment for now.

**Comment by fazil-ey** [comment]
Looks good, no file name shown when file to big and for 3rd party it wont allow submisison if file is too big

**Comment by Stella-Archer** [comment]
Yes - yay
1/ Small files uploaded and appeared fine
2/ The 19.6MB .mov file did NOT upload and I got the appropriate message
but :(
3/ the email file which is only 48KB did NOT upload - it should have and I got a 'wrong type'  message about it
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE1xQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9658ecca692608141aec196bd116040da653bdd3/image.png" alt="image.png" />

<img width="696" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGNxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db5522b8f67c4734975f194e9962e14d71e27454/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
@bhumin-fw I've uploaded the message file to our Teams channel> https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/Conflict%20of%20Interest/2024%20Project%20Files/Test%20ADM%20Approval%20email.msg?csf=1&web=1&e=dKQfsE

**Comment by bhumin-fw** [comment]
@Stella-Archer @ayushdamani @fazil-ey 
I've added a fix for selecting and uploading .msg files. I've allowed the application/octet-stream MIME type and limited it to the .msg extension. I've tested it with the file Stella shared, and it seems to be working fine. It's now ready for testing on the DEV and TEST environments.
