### ISSUE TITLE
COI: loading after supervisor submits

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1785]
**AC**
- [ ] Show the following loader for the whole time it takes to submit the form after supervisor submits the COI form. The goal is to prevent double submissions, or clicking away to another form and send a clear message that it will take some time to submit.

<img width="1212" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNElFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e5156ddd85d6e1da1db3ddd717f785d61ab9dd8/image.png" alt="image.png" />

Do NOT show this - 
<img width="990" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFlFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba0a9825fec6996649c74de43b0912e9f31c479e/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
Ready to test.

**Comment by fazil-ey** [comment]
cant see the "dancing balls" submit loader. Looks good
