### ISSUE TITLE
Mat/Pat - Partner allowance checkbox

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1786]
Add an checkbox with the allowance information if partner works for BC public Service instead of just an alert box.  The messages we have may are not a 100% effective. 

**_AC_**
- [x] The alert below that shows when employee is taking parental leave and partner works for BC Public service in "Parental leave - Leave allowance dates" should be changed to a mandatory checkbox

<img width="1042" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b77cb4bc9822bba4c4286d392a1aff169d52e28f/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
ready to test

**Comment by ayushdamani** [comment]
Looking good
<img width="764" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3hQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4dcf081081c036e503d57bf248c32b5ea91a944f/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good

**Comment by jerry-ey** [comment]
@fazil-ey Removed yellow background, please check.

**Comment by MikePSA** [comment]
Tested in PROD, looks good. Closing.
