### ISSUE TITLE
ERIP: Emails (subject and content)

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1788]
**Acceptance Criteria**

- [ ] Email to Employee on employee form submission
SUB: Conflict of Interest Disclosure Form Submitted for Review By Your Supervisor
Content: This is to confirm that we have received your ERIP form submission. 

- [ ] Email to Darren on employee form submission
SUB: [Employee name’s] ERIP Form Submission
Content: This is to inform you that a new ERIP form has been submitted by [employee name].

**Comment by ayushdamani** [comment]
We will be confirming this info with Darren.

**Comment by Andrew-Vargas-bcgov** [comment]
@ayushdamani any emails available yet?

**Comment by ayushdamani** [comment]
I have not received these from Darin yet
@fazil-ey do you by any chance have these? Shall I remind Darin to share these?

**Comment by Abuchana** [comment]
@Stella-Archer please follow up with Darin

**Comment by ayushdamani** [comment]
Confirmation from Darin --

Email to employee on form submission

SUB: [Employee name’s] ERIP Form Submission
Content: 
Hi (employee name),
Thank you for submitting your ERIP application. Attached is a copy of your submission for your records. If you have any queries, feel free to reply back to this email or you can contact us at CorporateHealthPrograms@gov.bc.ca

Thank you,
The Digital Journeys Team
BC Public Service Agency

---------------------------------------------------------------------------------------------------------------------------------
Email to Darin on employee form submission

SUB: [Employee name’s] ERIP Form Submission
Content: This is to inform you that a new ERIP form has been submitted by [employee name].

**Comment by Andrew-Vargas-bcgov** [comment]
Created bpmn for ERIP.
Added emails.
Set deletion for 60 days after submission. @ayushdamani @fazil-ey is this the correct retention duration?

**Comment by ayushdamani** [comment]
Andrew, can you please make the initials of the first and last name capitals?
<img width="1294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2hpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fe69772af828ef59b8390bc11cb6f0f296d55a2/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Moving to PO
<img width="1125" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODluQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c44d55a0685b82abe466b170c51afbb498cfadf/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Small change in content --

Email to employee on form submission

SUB: ERIP Application: Confirmation of Submission from [Employee name’s]
Content:
Hi (employee name),
Thank you for submitting your ERIP application. Attached is a copy of your submission for your records. If you have any queries, feel free to contact us at CorporateHealthPrograms@gov.bc.ca

**Comment by ayushdamani** [comment]
Thanks again!
<img width="1128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME5vQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f87b21144c3b31f5c5c86f38e29c6dd8ee190cf/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good
