### ISSUE TITLE
ERIP: Guest Login

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1789]
**User Story**
As a user I want to be able to submit an ERIP form without using credentials.

**Acceptance Criteria**
- [x] A user should able to submit a form without needing any credentials
- [x] Multiple users should be able to use the Guest login feature at the same time
- [x] A user should not able to view applications submitted or drafts saved by other users

**Comment by bhumin-fw** [comment]
@fazil-ey It is ready to test on TEST environment.
Note: Hard refresh page if you don't see ERIP form or try in incognito to login as guest.

**Comment by fazil-ey** [comment]
works well. A small cosmetic change - make the button left aligned like the other buttons 

<img width="1004" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFV3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61251a7fcb96c4c99ae1ff8b9990444887370536/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
@fazil-ey Alignment set to left and changes are up on DEV and TEST.

**Comment by ayushdamani** [comment]
Updated
<img width="502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTAyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81418caff351b38e31e84aa36d5293abd59289cf/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
Looks good in dev, will approve after theme issue is fixed in test

**Comment by fazil-ey** [comment]
looks good
