### ISSUE TITLE
ERIP: Form submission success page

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1790]
**User Story**
As a user I want to see a success screen which  confirms that my form has been submitted.

Miro link - https://miro.com/app/board/uXjVKMReQvg=/?moveToWidget=3458764590066587696&cot=14
Design yet to be finalized

**Acceptance Criteria**
- [ ] Design the success page

**Comment by ayushdamani** [comment]
We will gather some info related to the success page from Daren next week

**Comment by ayushdamani** [comment]
Looking good, @fazil-ey do we need to remove all periods?
<img width="1319" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEZDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cd1a8c923bd20604c9638c8d4b0468477af7261/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
@ayushdamani yes, no periods for bullets is the standard we follow

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey not a problem. do you want the period in the "thank you for submitting" section?

**Comment by ayushdamani** [comment]
Can you please check @Andrew-Vargas-bcgov ?
<img width="1327" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3hhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4acd967daf86c7611650e58dcb92c14651a27ce9/image.png" alt="image.png" />

Tested in TEST and DEV

**Comment by ayushdamani** [comment]
TEST & DEV - updated

<img width="1409" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelZoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d603ac0786a3002fc319568a3425c7bad27c0d7/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good
