### ISSUE TITLE
COI - content edits 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1799]
**_AC_**
- [ ] Update second point
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2dZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76e373a7801d79b06a5bc8e9077ee890aa98299e/image.png" alt="image.png" />

> After your supervisor reviews your disclosure, documents a decision on the outcome and submits, your form will be automatically sent to AskMyHR for placement on your personnel file. Your supervisor will receive a confirmation from AskMyHR that the service request has been created

- [ ] Update first point
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOElZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99c3ed9b573b931e29c6ed1b2240b69d32770837/image.png" alt="image.png" />

> After your supervisor reviews your disclosure, documents a decision on the outcome and submits, you will receive a confirmation and a copy of your form in your email. Your form will be automatically sent to AskMyHR for placement on your personnel file

- [ ] update 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b831a01529a7d51489919f335c2f06f9e4bbc7ff/image.png" alt="image.png" />

> Your supervisor will reach out to you if they need some additional information

- [ ] Update in the Supervisor Documentation and Decision tab
<img width="1808" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOThZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--edee2a9cabf9fbf582a85d8f067451a3920fb75d/image.png" alt="image.png" />

> 
If a third party is involved, I confirm that the employee has disclosed the involvement of a third party in this conflict, and attached the [Third Party Authorization form](https://www2.gov.bc.ca/assets/download/70F57B797A4341CE81B5E3DDC78907CE)

**Comment by jerry-ey** [comment]
update estimation to 2, as it needs code change for success page.

**Comment by jerry-ey** [comment]
ready to test

**Comment by fazil-ey** [comment]
all okay
