### ISSUE TITLE
Mat/Pat - Bug with allowance date

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1803]
We should not allow allowance to end after the leave end date like in the case below

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUV3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3dfbe9897769666dd033017d6f89e8fd49e2b5a/image.png" alt="image.png" />

**AC**
- [x] The allowance end date should be on or before the leave end date. 

Error message - 
> Allowance must end before the parental leave end date August 10th 2025

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov 

<img width="1152" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVZKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--022ec5add18e71bc6528e84ffbfadb2487c218d7/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
works well

**Comment by ayushdamani** [comment]
Closing
