### ISSUE TITLE
Mat/Pat - Checkbox for standard allowance for extended leave 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1806]
**_AC_**

- [x]  If someone is 
-  taking extended parental leave allowance 
- and partner is not in BC Public Service or "Yes, however, only I will be taking parental leave"
-  and they are not taking 61 weeks of allowance 
-  then show a checkbox in "Parental leave - Leave allowance dates" saying 

> I understand that weekly extended allowance is calculated based on 61 weeks, regardless of the length of leave I take, which can result in lower overall earnings if I do not take extended allowance for the full 61 weeks. If I am not taking the full extended allowance for 61 weeks, it would be more beneficial if I take standard allowance. I understand I can take standard allowance even if I take extended leave.

**Comment by jerry-ey** [comment]
ready to test

**Comment by ayushdamani** [comment]
Looking good, 
@fazil-ey does the checkbox and yellow alert box look okay to you from a UX perspective please?
<img width="1543" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3BQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d72766bf857c5c2e1b1968198c24a3307245e0eb/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
Discussed with Fazil
- remove yellow alert
- move to next to weeks
- only show when user enter weeks

**Comment by fazil-ey** [comment]
Notes 
1. Style checkbox without the alert
2. It should not be always present, only after the weeks is entered
3. Make it appear next to the date and week fields

**Comment by jerry-ey** [comment]
moving back to inprogress

**Comment by jerry-ey** [comment]
@fazil-ey  please review again. Have made above change.

**Comment by jerry-ey** [comment]
Discussed with Fazil.
moving back to in-progress.

Also needs to add if the user select the second choice.
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzlVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81a0f4c8daed7195a5c223c666db8c0b378273ff/CleanShot%202024-06-11%20at%2012.28.27%402x.png" alt="CleanShot 2024-06-11 at 12.28.27@2x.png" />

**Comment by jerry-ey** [comment]
@fazil-ey  Please review again, thanks

**Comment by ayushdamani** [comment]
Updated
<img width="1258" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmRhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84e557600b645743c246b4679243c61a164c9e5a/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
this looks good

**Comment by ayushdamani** [comment]
Closing
