### ISSUE TITLE
No success message when submitting a draft

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1808]
When employee submits any form from draft, there is no success page but form submits successfully

video link - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Conflict%20of%20Interest/Test%20recordings%20and%20screenshots/Screen%20Recording%202024-06-04%20at%203.09.41%20PM.mov?csf=1&web=1&e=Vz1Djg

**AC**
- [ ] Success page should be shown when a new or draft form is submitted for all forms

**Comment by fazil-ey** [comment]
I noticed the draft alert again <img width="794" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVZFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e23e4ff2472455490d0b7882f00f8aa246470c1/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
ready to test, pls note that when go to draft page, refresh the browser might help avoid some unknown issues.

**Comment by fazil-ey** [comment]
tested with COI, Bullying and Mat/Pat

**Comment by ayushdamani** [comment]
Updated, over to you @fazil-ey

**Comment by Stella-Archer** [comment]
Success message worked from draft in PROD - yahoo closing this :)
