### ISSUE TITLE
ERIP - Remove saved to drafts toast notification

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1810]
**AC**
- [ ] Remove this notification 
<img width="806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2MzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d30379d6f6a1e3ebe780a5ca7a9e10ede0da62c/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
@ayushdamani It is ready to review on TEST environment.

**Comment by ayushdamani** [comment]
Tested and can verify that the toast is removed!
Thanks Bhumin!

**Comment by fazil-ey** [comment]
dont see the notification
