### ISSUE TITLE
COI - Rename files in the CRM ticket

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1819]
We want to rename files when we upload to CRM so that its easier for the records team to find out which files are employee and which ones are supervisor so that they can process the files faster.

**_AC_**
- [ ] Add prefix Emp_[originalFileName] for employee files when uploading to CRM
- [ ] Add prefix Sup_[originalFileName] for supervisor files when uploading to CRM

**Comment by bhumin-fw** [comment]
Ready to test on DEV and TEST environment.

**Comment by ayushdamani** [comment]
Thank you, moving to PO
<img width="324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2Q5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc8a1c09f0159da5976cc1d6ed2eedf5ca66efbd/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
@Stella-Archer please PO Review this as I cant access CRM!

**Comment by Stella-Archer** [comment]
Thanks @fazil-ey  this looks good, I'm wondering why the file names have random characters suffixed to them (the files I uploaded where just called "orange.png" "olives.jpg")
<img width="760" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGFLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d732bbd7c4be6a9a2a410f9ec35bca638b98a75/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
@Stella-Archer Each selected file is assigned a unique name by the component to ensure separation from overrides. It also attempts to remove unnecessary special characters.

**Comment by Stella-Archer** [comment]
Ok thanks @bhumin-fw PO approved - closing ticket
