### ISSUE TITLE
Mat/Pat - Update the instructions for allowance dates

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1820]
The instructions for parental leave allowance dates are from when we had start and end dates. We should change it to start date and number of weeks
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHBiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5766fea5a5b2d84d48149eba478444b23fe8cced/image.png" alt="image.png" />

**AC**
- [ ] Change the points highlighted int he screenshot as follows 

> - If you intend to claim parental leave **EI for your entire parental leave**, you can **enter the start date and number of weeks of your parental leave** in the fields below
> - If both **you and your partner intend to claim parental leave EI**, i.e. share parental EI, you can **enter the start and the number of weeks that you intend to claim parental EI**. You can learn more about sharing parental leave EI in the "Parental leave  Leave allowance information" tab

**Comment by jerry-ey** [comment]
ready for QA

**Comment by ayushdamani** [comment]
Looks good
<img width="1554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTZEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccb2f63b0a0b982ab934265ca46eb2d4952e2c77/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good

**Comment by Stella-Archer** [comment]
Live in PROD - looks good!
<img width="1443" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKytiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78206705fd309a2dcdca6d30da66a89d051bc37b/image.png" alt="image.png" />
