### ISSUE TITLE
COI - Error message for third party attachment

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1824]
**AC**
- [x] If no file is attached to the third party field, the error message should be 

> Third Party Authorization for Collection and Use of Personal Information form must be attached

<img width="1410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVJpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6190bb9bb4fbb9ae237d0ba9c897d334d8d02267/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
Please test.

**Comment by ayushdamani** [comment]
Thanks Jerry!
<img width="1537" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU5uQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--584da10cf391b528d3b1cc2a4b1fd3cdecf9cfbe/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good
