### ISSUE TITLE
Telework - restrict optionalNote field to 2000 characters

### ISSUE THREAD

**Issue by Andrew-Vargas-bcgov** [bcgov/digital-journeys#1825]

**Comment by Andrew-Vargas-bcgov** [comment]
optionalNote field in ods is varchar 2000.

**Comment by ayushdamani** [comment]
Updated!
<img width="1088" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFJuQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7346d7bfeddfc51aff2d5984d335711783096794/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good

**Comment by ayushdamani** [comment]
<img width="1004" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0tiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d590cd3213e4642cf821734ea5ab17bf501c0de9/image.png" alt="image.png" />

Closing.
