### ISSUE TITLE
Mat/Pat - Partner allowance checkbox in Review and Process

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1826]
Add an checkbox with the allowance information if partner works for BC public Service when allowance dates are chosen in review page as well. 

**_AC_**
- [ ] When employee is taking parental leave and partner works for BC Public service, the checkbox shown after allowance  start date and weeks are entered in "Parental leave - Leave allowance dates" should also be shown in the Review page. 
- [ ] The checkbox in review and "Parental leave - Leave allowance dates" must also sync with each other

<img width="1176" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUpqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b475431c393d16c40c9e2c20656fb78257859772/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
ready for QA

**Comment by ayushdamani** [comment]
Working great - moving to PO

**Comment by fazil-ey** [comment]
works well

**Comment by MikePSA** [comment]
Tested in PROD, looks good. Closing.

**Comment by Stella-Archer** [comment]
Worked prefect in PROD both allowance and review screens
<img width="1522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzZiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85e600afe1079160571dbbb2473476ad98df654c/image.png" alt="image.png" />

<img width="1174" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzJiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a6d4b226214b37d21246e2d3f9688dfa0590820/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
closing!
