### ISSUE TITLE
Mat/Pat - Checkbox for standard allowance for extended leave in Review tab

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1827]
**_AC_**

- [ ] In the review tab show the same checkbox that is shown in "Parental leave - Leave allowance dates" if someone is 
-  taking extended parental leave allowance 
- and partner is not in BC Public Service or they selected "Yes, however, only I will be taking parental leave"
-  and they are not taking 61 weeks of allowance 

- [ ] The checkbox in review and "Parental leave - Leave allowance dates" must sync with each other

<img width="1168" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVJqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5fd71b0d225073163e5cf1aebdea16a391bf2251/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
ready for QA

**Comment by ayushdamani** [comment]
The checkbox does not sync between the "Parental leave - Leave allowance dates" and "Review" page - can you please check @jerry-ey

**Comment by jerry-ey** [comment]
@ayushdamani  I have tested couple times and no issue. Could you please provide screenshot or video? thanks

**Comment by fazil-ey** [comment]
Hey @jerry-ey i noticed this too, here's the link to the video https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202024-06-27%20at%201.26.59%20PM.mov?csf=1&web=1&e=jfNylq

FYI - @ayushdamani

**Comment by jerry-ey** [comment]
Thanks for the detail, I added more scripts. Please review again, thanks

**Comment by ayushdamani** [comment]
Checked and confirmed working - thanks Jerry!

**Comment by fazil-ey** [comment]
works well
