### ISSUE TITLE
COI - Supervisor redesign

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1828]
Supervisors find it confusion what information is for them and what is for the employee. So we want to hide all the tabs not relevant to supervisor and make the supervisor tab a section in the employee disclosure tab, similar to telewor

<img width="1342" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenQwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4387445dde7a591c882c8c3b075da6db0daa278/Screenshot%202024-06-18%20at%202.49.43%20PM.png" alt="Screenshot 2024-06-18 at 2.49.43 PM.png" />

**AC**

- [ ] Hide Before you begin, Employee Acknowledgements, Employee Sign Off Statement
- [ ] Add Supervisor Documentation and Decision as a section in the Employee Disclosure Statement tab. Section heading  should be "Supervisor Documentation and Decision". 
    - [ ] This section should be hidden from the employee, only supervisor should see it. 
    - [ ] It should be included in the pdf of the form

**Comment by ayushdamani** [comment]
Tested and confirmed updated, thank you Bhumin!

**Comment by fazil-ey** [comment]
Looks good, @Bhumin, can we add the heading Supervisor Documentation and Decision to the Supervisor section? 

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVpJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--222fd1153659717a0ee849b537b6c35aea210e44/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
@fazil-ey I’ve made the changes you mentioned. Adding a box around the employee section looks odd, as the same effect applies to the initial form as well. Let me know if you’d like me to remove the box effect. I’ve already added it to DEV and TEST environments for now.

**Comment by ayushdamani** [comment]
Box has been added to the employee disclosure section ✅
Supervisor section heading has been added ✅

Thanks, Bhumin!
<img width="865" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0JUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83294b4bbb64aedfa7df13ad50f1afa229a78db2/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
looks good
