### ISSUE TITLE
COI - Supervisor content changes

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1829]
**AC**
- [ ] Supervisor section should have the following content

> This section is intended for supervisors within the BC Public Service.
> 
> You have a responsibility to review the employee's disclosure form in a timely manner (approximately 2 weeks), discuss it with the employee and document your decision.
> 
> This process may include:
> 
> - Further discussion with the employee
> - Consultation with your [ministry ethics advisor](https://www2.gov.bc.ca/gov/content?id=83A2B60ACB024A9EA47C5ABC89F709E6#EthicsAdvisors) or the [BC Public Service Agency](https://www2.gov.bc.ca/gov/content?id=BA01C2B7E36D4AD9A435EF9D36972023)
> 
> If you have any questions about this process, or your role, refer to [Manage a conflict of Interest disclosure in the BC Public Service](https://www2.gov.bc.ca/gov/content?id=1B0F52A878544CD1A28C7F68F6EF669A).

**Comment by ayushdamani** [comment]
Ready in TEST & DEV - @fazil-ey
