### ISSUE TITLE
COI - Add additional supervisor text fields

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1830]
**AC**

- [x] Change the existing text field, field is mandatory 

> Please summarize any discussions that have taken place regarding this matter. 

- [x] Add a new text field, field is optional

>  If there is a conflict of interest, please summarize the actions taken to resolve or mitigate the conflict. Also indicate how you communicated this decision to the employee. Attach any files supporting this decision below.

**Comment by ayushdamani** [comment]
Ready in TEST & DEV - @fazil-ey
