### ISSUE TITLE
COI - Content changes

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1831]
TBD after Sean and Raman send the changes

**Comment by ayushdamani** [comment]
Changes made to the form:
Add to 'Before you begin' --
- Submitting a conflict of interest form demonstrates your commitment to transparency and ethical behavior, showcasing your dedication to a fair and trustworthy workplace. This proactive step not only protects you and the Public Service but also highlights your personal integrity and professionalism
- Your disclosure is kept strictly confidential and is only accessible to your supervisor, the Ethics Advisor, the PSA ethics team, and records staff in PSA. It may be shared with the Deputy Minister in exceptional circumstances

Added to point number 5 under 'Employee Disclosure Statement' --
You may also attach other relevant documents. A third party might your spouse, another family member, a friend, or a business associate whose interest are related to the conflict being disclosed

**Comment by ayushdamani** [comment]
Ready to test on TEST & DEV

**Comment by fazil-ey** [comment]
noticed a small error - 

You may also attach other relevant documents. A third party might your spouse, another family member, a friend, or a business associate whose **_interests_** are related to the conflict being disclosed

**Comment by ayushdamani** [comment]
Great catch, Fazil - updated!

**Comment by fazil-ey** [comment]
looks good
