### ISSUE TITLE
Mat/Pat- Info about 2 day leave for non birthing parents in before you begin

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1832]
**_AC_**
- [x] Change the the info box content in before you begin

> 
Non-birthing parents may be eligible to take up to two days of leave for the birth of their child, from the period beginning with the onset of labor up to the time when the birthing parent and child return home. Please refer to your [collective agreement](https://www2.gov.bc.ca/gov/content/careers-myhr/managers-supervisors/employee-labour-relations/conditions-agreements/collective-agreements) or the [terms and conditions for excluded employees and appointees](https://www2.gov.bc.ca/gov/content/careers-myhr/managers-supervisors/employee-labour-relations/conditions-agreements/excluded-employees-appointees) for more information.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVIwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06660a77a4d3cf08585ffd5167ac6424bad82d47/image.png" alt="image.png" />

- [x] Change the content of the info box in Parental leave - General information

> Non-birthing parents may be eligible to take up to two days of leave for the birth of their child, from the period beginning with the onset of labor up to the time when the birthing parent and child return home. Please refer to your [collective agreement](https://www2.gov.bc.ca/gov/content/careers-myhr/managers-supervisors/employee-labour-relations/conditions-agreements/collective-agreements) or the [terms and conditions for excluded employees and appointees](https://www2.gov.bc.ca/gov/content/careers-myhr/managers-supervisors/employee-labour-relations/conditions-agreements/excluded-employees-appointees) for more information.

> You may be eligible to take up to two days of leave for the birth of your child, from the period beginning with the onset of labor up to the time when the birthing parent and child return home. Please refer to your collective agreement or the terms and conditions for excluded employees and appointees. 

> 
Also note that this extra two-day leave is separate and in addition to your parental leave. If eligible, you can apply for it through [Employee Self Service](https://timepayhome.gov.bc.ca/) (or if [working from home](https://logon7.gov.bc.ca/clp-mp/ntlm.cgi?flags=1000:1,0&partner=fed42&TYPE=33554433&REALMOID=06-73702074-5cf7-471a-b875-b5df824be782&GUID=&SMAUTHREASON=0&METHOD=GET&SMAGENTNAME=$SM$ui%2fRndhXA8ldRn5B9ReEwVkGRBcDALmClZno3VcOtuEOnKpNicqvuSLNYu9aOFRi&TARGET=$SM$https%3a%2f%2ftimepay%2egov%2ebc%2eca%2f)) or let your supervisor know.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkIwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c7ad6996789d84622357ccb1113178f2caf4518/image.png" alt="image.png" />

**Comment by jerry-ey** [comment]
ready for QA

**Comment by ayushdamani** [comment]
Looking good - moving to PO

**Comment by fazil-ey** [comment]
looks good

**Comment by MikePSA** [comment]
Tested in PROD, looks good. Closing.
