### ISSUE TITLE
[Tool]: Pathfinder SSO upgrade

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1833]
**User Story**
SSO is moving to the much anticipated Red Hat Build of Keycloak (RHBK 24) which is built upon Keycloak Quarkus 
Quarkus is a Java framework tailored for deployment on Kubernetes. It was designed around the container first philosophy. It allows for running Java code on a very small resource footprint (CPU/Mem), while retaining excellent performance and pod startup times. 

Upgrade timeline
**DEV/TEST September 4 2024 20:00 -2030** 
**PROD September 18 20:00 - 2030**
 **ACTION** by July 31, 2024: Review your redirects and replace * with your app's custom scheme something like custom://test, custom://test/*

In preparation for this:

1. General pattern * no longer covers custom scheme in redirect uris
   Context 5.1.1.2. Changes in validating schemes for valid redirect URIs
If an application client is using non http(s) custom schemes, the validation now requires that a valid redirect pattern explicitly allows that scheme. Example patterns for allowing custom scheme are custom:/test, custom:/test/* or custom:. For security reasons, a general pattern such as * no longer covers them.

   What you might see: You may get the error message 'invalid redirect uri' in your dev and test environment.

   ACTION by July 31, 2024: Review your redirects and replace * with your app's custom scheme something like custom://test, custom://test/*

2. Custom Service/Realm Community

We've got 4 things for you below and a reminder on the Custom Service/Realm Community Ways of Working

a) if you missed our community chat on June 5th, please review the notes below and/or watch the recording note we've updated our wiki help since we met.  

b) Please take note of our planned upgrade timeline --- we will need you to do your part in testing your apps between September 4 -17th  

    DEV/TEST September 4 2024 20:00 - 20:30
    PROD September 18, 2024 20:00 -20:30
c) As a committed community member, please update your contact information with us 

d) Redirect Changes -- be aware of the future horizon
Since many Gov teams make use of the redirect_uri parameter to log out the users in their applications, we applied an available patch to support the backwards compatibility option with redirect_uri; we also want to highlight that this option will be completely deprecated in the future Keycloak releases.

We recommend to include id_token_hint and post_logout_redirect_uri parameters. (recommended)
https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?post_logout_redirect_uri=http://localhost:3000&id_token_hint=xxxxxxxxxxxxxxxxxxxxx

For more information go to : https://www.keycloak.org/docs/latest/securing_apps/index.html#logout

**Comment by Stella-Archer** [comment]
@warrenchristian1telus could you see if there is something we need to action on this issue by July 31 or is is applicable to us at all?

**Comment by warrenchristian1telus** [comment]
@Stella-ArcherIt I think we may want (or need) to replace * in "Valid Redirect URIs" with something like: https://digital-journeys-keycloak.apps.silver.devops.gov.bc.ca/* (with corresponding changes to dev and test).

It looks to me like we will need to test and verify on Sept. 5th, and migrate any changes to prod for Sept. 18th.

Maybe @bhumin-fw or @kkapoor-fresh can confirm?

If there is still a question I can raise it with the SSO team: https://chat.developer.gov.bc.ca/channel/sso

**Comment by warrenchristian1telus** [comment]
@Stella-Archer Actually, after further review and recently updated documents, it seems we should make these changes Before July 31st. As this is recommended prior to the implementation, I suspect we can do this at any time, and therefore should likely schedule this for dev and test over the next week or so. It should be a simple change in the Keycoak admin panel, so unless there is some unexpected issue with the redirect URL format, I figure this will require minimal effort.

**Comment by Stella-Archer** [comment]
Thanks @warrenchristian1telus we can dig into this and any action we need to take at Mondays Scrum - I'll move this to the Sprint backlog so it visible, @bhumin-fw I'm giving it a 3 point estimate for now - we can adjust it when we discuss what's involved on Monday

**Comment by kkapoor-fresh** [comment]
@Stella-Archer I am in conversation with @warrenchristian1telus on this.

**Comment by Stella-Archer** [comment]
Thanks @kkapoor-fresh  I noticed in the last reminder from SSO, active sessions might be lost so we should plan to do this later in the afternoon when there not many users in, here's their note: 

Before July 31st, 2024, you must take action. To facilitate this service upgrade you must review your redirects, and replace wildcard (*) with your app’s custom scheme, such as:
custom://test
or
custom://test/*
•	Note: when you make these changes, active sessions may be lost, so users may need to log in again afterwards.
More information on these required changes is at:
https://bcgov.github.io/sso-docs/integrating-your-application/redirects#valid-redirect-format

**Comment by warrenchristian1telus** [comment]
Valid Redirect URIs have been updated in dev. Testing was successful on my end.

Please verify and let me know when we're ready to migrate to test.

**Comment by warrenchristian1telus** [comment]
According to Keycloak.org, we should also change any occurrences of localhost to the IP literal 127.0.0.1.

[Securing Applications and Services Guide : 2.10.2. Redirect URIs](https://www.keycloak.org/docs/latest/securing_apps/index.html#redirect-uris)

So I've done that as well. I'm sure it's fine, but not quite sure how to validate that one.  Maybe @bhumin-fw knows a way to test a local connection / redirect?

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh has also assisted with testing on dev, and everything looks good so far.

**Comment by bhumin-fw** [comment]
@warrenchristian1telus local connection not working with DEV keycloak, 

Below request fails with 400 code.
request auth on dev keycloak, redirect url is http://localhost:3000

https://digital-journeys-keycloak-dev.apps.silver.devops.gov.bc.ca/auth/realms/psa-digital-journey-dev/protocol/openid-connect/auth?client_id=forms-flow-web&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fsilent-check-sso.html&state=04fab499-8cb5-44f0-8113-c9c4a2037b81&response_mode=fragment&response_type=code&scope=openid&nonce=428582dd-969a-443f-949a-a3ee2c924c77&prompt=none&code_challenge=44asWJLw1DU9OzEntjhQiKA-ayMvLxddGiCQuPgqsSk&code_challenge_method=S256

**Comment by warrenchristian1telus** [comment]
Thanks @bhumin-fw 

How do you get to localhost in keycloak? Maybe 'localhost' should be replaced with '127.0.0.1' somewhere else as well?

I'm just not getting why / how a user would get a localhost redirect. It wouldn't be valid browser-side. It will only work for internal communications. Of course, it could be done that way between apps/pods. 

Either way, I think we should try to change all occurrences of localhost to 127.0.0.1 for security best practices (at least for KeyCloak interactions).

I'm wondering if we need to make changes for every URL / app? I see quite a few occurrences of localhost in the repo:

[Repo search: localhost](https://github.com/search?q=repo%3Abcgov%2Fdigital-journeys%20localhost&type=code)

And redirects:

[Repo search: Redrects](https://github.com/search?q=repo%3Abcgov%2Fdigital-journeys%20redirectUri&type=code)

Upon inspection of Camunda logout, I see that redirect_uri is set to Camunda's:

redirect_uri=https://digital-journeys-**camunda**-dev.apps.silver.devops.gov.bc.ca/camunda/login/oauth2/code/keycloak

I think we also need to update the Keycloak Valid Redirect URIs for:

1. forms-flow-bpm
2. forms-flow-analytics (although it's not currently being used)

These are the only apps with Keycloak profiles, so I would suspect they are the only ones we need to worry about in configs (or ENV vars or wherever "localhost" is being set).

I've made the changes for each app url and set 127.0.0.1.

If you need to change them while I'm away (say, if something is broken and can't get fixed another way), the keycloak page to find/edit them is here: /auth/admin/master/console/#/realms/psa-digital-journey-dev/clients

**Comment by bhumin-fw** [comment]
@warrenchristian1telus 
Let me know when you are Applying these configuration to TEST and PROD, So I will stay online during that time and jump to quick test, And If it's already done then I guess we are good as TEST and PROD works fine.

I did review DEV few more time and no issue at all. So we are good with similar configuration apply to TEST and PROD.

**Comment by fazil-ey** [comment]
Team has verified that we are able to login. Bhumin connected with Kunal and make sure change was made on prod.
