### ISSUE TITLE
COI - explore multiple file attachments for LDB

### ISSUE THREAD

**Issue by Andrew-Vargas-bcgov** [bcgov/digital-journeys#1835]
In the new ldb branch of the workflow. The business would like to send all uploaded file attachments to an ldb mailbox.

**from bhumin:**
public ByteArrayDataSource generatePdf(String formId, String submissionId) throws IOException {
        String url = String.format("%s/form/%s/submission/%s/export/pdf", documentApiUrl, formId, submissionId);
        Mono<byte[]> pdfFile = httpServiceInvoker.exchangeForFile(url, HttpMethod.POST, null);
        return new ByteArrayDataSource(pdfFile.block(), "application/pdf");
}
I did check where it pulls data and converts to byte[] to attach as file in Email. It does support only one file per name. And we have multiple file attachment for each field. Requires to convert this function to support multiple file in both format, uploaded file and base64 file.
We have base64 string, we can decode and convert that to byte[]....

**Comment by ayushdamani** [comment]
Bhumin tested this - moving to PO!

**Comment by ayushdamani** [comment]
For testing:
LDB is required for testing and DJ inbox receives all communications for testing purposes.

**Comment by fazil-ey** [comment]
Waiting for resolution of #1855 to PO test this ticket

**Comment by fazil-ey** [comment]
Best approach is to test with LDB folks directly. We will close this ticket after we do that.

**Comment by Stella-Archer** [comment]
Waiting to TEST
