### ISSUE TITLE
ERIP - Employee Information field changes

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1840]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2lPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61b6f00dcf5ad1e11a87ebbb50d0a894cb9a8f77/image.png" alt="image.png" />

**_AC_**

- [ ] Change "Province or State" to just Province
- [ ] Change "Country (if Institution is Outside of Canada)" to just Country
- [ ] Add validation for email format in the email field

**Comment by ayushdamani** [comment]
Ready for test on TEST and DEV :)

**Comment by ayushdamani** [comment]
Updated! Please test again, thanks!

**Comment by fazil-ey** [comment]
looks good
