### ISSUE TITLE
ERIP - Only one of Phone number or Email required

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1841]
**_AC_**

- [ ] Only one of Phone number or Email is required i.e Both Phone number AND email should not be empty
- [ ] If email is not provided, email confirmation need not be sent to applicant

Error message 

> Please provide either a 'Phone number' or an 'Email' to facilitate communication during the processing of the form.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUNPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--725a7b9f136499c132b368af7165997441a0bee7/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
Error message says both are required, we should use "Please provide either a 'Phone number' or an 'Email' to facilitate communication during the processing of the form."

 <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ZzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c28ad4978641de183ba5b4eea94fd76d955b6d1b/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
It is ready to test again.
