### ISSUE TITLE
ERIP - Change Success Message

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1842]
**_AC_**

- [x] Change message in Success page on form submission to, remove the next steps section - 

> 
> ###  Thank you for submitting your ERIP application, it is currently being processed.
>  
> Please allow up to two weeks to receive an ERIP approval confirmation and additional instructions from the date we receive your application.

**Comment by jerry-ey** [comment]
@fazil-ey 

Do you want to keep the section "Next Steps"?

<img width="1498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--405a7743a82a88e958bb015ddbe8b80562709902/CleanShot%202024-06-26%20at%2011.19.27.png" alt="CleanShot 2024-06-26 at 11.19.27.png" />

**Comment by ayushdamani** [comment]
<img width="1042" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWViQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd6be11b94c5c3227c5178c6b71f16ad222722a7/image.png" alt="image.png" />

Can you please fix the alignment Jerry?

**Comment by jerry-ey** [comment]
Thanks, I added dot list, same style as other success message.
(EX: https://digital-journeys-test.apps.silver.devops.gov.bc.ca/success?type=COI_SUPERVISOR_SUBMISSION_APPROVED)

**Comment by ayushdamani** [comment]
My apologies - I meant the alignment of the message with the heading.
"Please allow up to two.." is a bit towards the right. Can you please put it under the "Thank you.." heading?

**Comment by jerry-ey** [comment]
The body/content part always has space there. To be consistent, I would suggest we follow the same style as all other success messages.
(See the example in COI: https://digital-journeys-test.apps.silver.devops.gov.bc.ca/success?type=COI_SUPERVISOR_SUBMISSION_APPROVED)

**Comment by ayushdamani** [comment]
Oh okay - thanks Jerry!

**Comment by fazil-ey** [comment]
looks good
