### ISSUE TITLE
ERIP - RRSP or direct payment validation

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1843]
**_AC_**

- [x] Both "Do you want some or all of your ERIP payment to be paid to you directly?" or "Do you want some or all of your ERIP payment to be transferred directly to your RRSP?" cannot be "No"

Error Message

> "Please select 'Yes' for either 'Do you want some or all of your ERIP payment to be paid to you directly?' or 'Do you want some or all of your ERIP payment to be transferred directly to your RRSP?'"

<img width="1258" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWVPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--227866b2ab8937746d154ac68f10ff07e88b516b/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
<img width="1048" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEhSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ffdd875ed48520624449621d31daaf0ce57733a/image.png" alt="image.png" />

Please add an apostrophe (') towards the end of the sentence

**Comment by ayushdamani** [comment]
Thanks Bhumin - moving to PO

**Comment by fazil-ey** [comment]
works well

**Comment by fazil-ey** [comment]
works well
