### ISSUE TITLE
1.10 Bullying & Harassment: PSA not receiving 1.10 complaints

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1854]
Background:
Article 1.10 complaints get automatically sent to PSA.RegistrarIntake@gov.bc.ca but they do not get automatically sent to the Recipient named in the complaint form anymore.  

Yesterday, for the first time ever, the opposite occurred.  The ministry Recipient was sent the complaint, but we did not receive it in our Intake mailbox. 

Please look into this asap, as it appears there is now an error in the distribution logic of the form, and if the Recipient is not the person who should receive the complaint, we could be creating privacy breaches.  In this case, it was the correct Recipient, so there was no breach.  

I understand that the Recipient received the complaint from the Complainant’s union rep and that the Complainant’s IDIR is suspended while they are on sick leave.  Not sure if the union rep completed it on behalf of the Complainant, but it shouldn’t matter – when you hit submit on the form, it should only go the Complainant and PSA, not the Recipient.  

The union rep may have completed the form on behalf of the employee, without revealing this in the complaint form.  If that was the case, the union rep would have received a copy of the complaint, which she then forwarded to the Recipient. As such, I don’t think the form logic sent the complaint to the Recipient, so likely no problem there. 

That just leaves understanding why PSA did not receive this complaint in its mailbox.  

Communicate with Don.Smallwood@gov.bc.ca about testing
 
Steps to Reproduce:
fill out 1.10 form, check that PSA.RegistrarIntake@gov.bc.ca receives complaint
 
Actual Behavior:
PSA.RegistrarIntake@gov.bc.ca does NOT receive complaint
Expected Behaviour:
 
Environment:
PROD

Acceptance Criteria:
Test:
- [ ] Component functionally test
- [ ] Integration
- [ ] End to end UX
- [ ] End to end functionality
- [ ] if data impacting confirm w/BI/DIO team

**Comment by bhumin-fw** [comment]
We found that the user only took the PDF of the form from the draft and did not submit it.
