### ISSUE TITLE
Mat/Pat - Validation error in parental leave allowance date

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1856]
Found in test: Leave ends 26 July, allowace date ends 26 July, but it still says allowance should be within the dates

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFBZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aad6ff7c7c9fdad1112de5026805b01718419dde/image.png" alt="image.png" />

but it is inconsistent & seems to have fixed itself later i played around with the dates in the review page

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHpZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a26f1d26e6ff8b1085e69cc018239f34a94b0e1/image.png" alt="image.png" />

**AC**
- [ ] Validation should not be triggered if allowance dates are within the leave dates

**Comment by ayushdamani** [comment]
Tested in TEST - not able to replicate the issue

**Comment by fazil-ey** [comment]
Cant replicate either

**Comment by ayushdamani** [comment]
Cannot replicate the issue
