### ISSUE TITLE
Application: Identify Draft PDFs

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1857]
We observed a case in 1.10 form where someone downloaded a draft pdf and did not submit the form, and sent the pdf to Don's team. It wasnt clear the pdf was a draft pdf not a submitted form pdf. 

**_AC_**
    - [ ] If a pdf of the draft is taken then, add a text in the top of the form saying 
    

> "This form is a DRAFT, it has not been submitted"

**Comment by ayushdamani** [comment]
Looks great!
<img width="1883" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0xEQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b71bee6de91cacb47c5d377047c47ad4cfaf96f/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
yup looks really great Bhumin, moving to deploy
<img width="1375" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHZQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--405f65568eaf0a794ed5947a93329775fdcf44a9/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
looks good in PROD Closing Ticket
<img width="1168" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVVVQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--992d23752dcd2c0bb946d1424d3e9a693aee54c9/image.png" alt="image.png" />
