### ISSUE TITLE
COI - Add LDB success page

### ISSUE THREAD

**Issue by Andrew-Vargas-bcgov** [bcgov/digital-journeys#1858]
Add new success page for LDB employees. data.employeeOrganization
Need copy from LDB team before this can be completed.

**Comment by bhumin-fw** [comment]
@AayushAnand007 It is on DEV and TEST, Please go ahead and test it.

**Comment by ayushdamani** [comment]
Changes are updated - thanks Bhumin!

**Comment by Stella-Archer** [comment]
Messaging looks good.
ready to move to PROD for LDB testers
<img width="1146" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmhxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c554758cf1016917ac645ed895752f3fab6a062a/image.png" alt="image.png" />
