### ISSUE TITLE
COI - add LDB specific language/links in form

### ISSUE THREAD

**Issue by Andrew-Vargas-bcgov** [bcgov/digital-journeys#1860]
There are several sections that need to have language and/or links modified for LDB users. 
Also need to move COI to prod and restrict access to LDB test users.

We will get this list from the LDB team.

Edits - [Conflict of interest_LDB Edits.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2xKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8d0b853029684603a84b66e11341778c6819418/Conflict%20of%20interest_LDB%20Edits.docx)

**Comment by ayushdamani** [comment]
Confirmed updated - thanks Andrew!

**Comment by Stella-Archer** [comment]
How can we test this without LDB log in?
@bhumin-fw make @fazil-ey a LDB employee

**Comment by fazil-ey** [comment]
Changes look good, i wasnt able to test the supervisor screens but we can test them when we test with LDB. Otherwise looks good
