### ISSUE TITLE
OCI testing

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1865]
**User Story**
As a platform we want tp makes sure our data migrates to the OCI successfully so we do not have error in any of our forms.

**Acceptance Criteria**
- [ ] If change is data impacting, test to confirm data has been sent with BI/DIO team

RE: #1851

**Comment by fazil-ey** [comment]
Checked with Heather and we are good with Cold/Flu
Telework - we need to verify, To check with Patrick and Mike

**Comment by Stella-Archer** [comment]
heather , Mike and Patrick have all confirmed they are seeing correct data in BI
all correct data is being pulled into Digital Journeys forms
