### ISSUE TITLE
Mat/Pat: Syncing Issue

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1872]
Connie observed an employee input 35 weeks of parental leave, but in review page it was only 3. We have observed this error before in test.

**Comment by Stella-Archer** [comment]
@Andrew-Vargas-bcgov will review and confirm if this is still happening in PROD/TEST

**Comment by Stella-Archer** [comment]
check PDF values

**Comment by fazil-ey** [comment]
Could not replicate in TEST. 
I may have been able to replicate in PROD based on Andrew's instructions but not sure.

@ayushdamani please test as well.
