### ISSUE TITLE
Mat/Pat - Selenium Other Scenario - Deferred leave

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1879]
Flow -  Maternity + Standard parental leave + Deferred Allowance + Supervisor approval
**AC**
- [ ] Test applicant is able to submit successfully
- [ ] Test supervisor receives submission and is able to approve

**Comment by fazil-ey** [comment]
Link to script - https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Maternity%20Parental%20L%26A/DeferredLeave_1879.side?csf=1&web=1&e=OVTWPX

**Comment by fazil-ey** [comment]
@MikePSA Can you peer review this script?

**Comment by MikePSA** [comment]
After testing, some potential improvements to the script are:
•	Clean up disabled commands
•	Use search function for the Maternity/Parental form and relocate “Start new” button 
•	Missing confirm employee information is required checkbox?
•	If/click Saturday checkbox, can we change that to just click?
•	Something going on with the dates after I edit the script? (But I didn’t change date commands) need to discuss
•	At end of script, delete the command "click on success intro" as it should be wait for element before assert
•	Observed 60 seconds not long enough to generate new Mat form in review and process, may need to extend wait time

**Comment by fazil-ey** [comment]
@ayushdamani  to test

**Comment by ayushdamani** [comment]
Script worked great! I just had to increase the duration between clicks, while moving from one action to another!
Moving to PO!

**Comment by ayushdamani** [comment]
Tested again - thanks Fazil!

**Comment by Stella-Archer** [comment]
Sweet! this worked great the very 1st try  - yahoo closing, PO approved
<img width="896" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenJLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--809df703f05e45c6e89527498c95314577e0f5d2/image.png" alt="image.png" />
