### ISSUE TITLE
Mat/Pat - Employee Information Validations

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1886]
Tab -  Employee Information
**AC**
- [x] Name Ministry and Email field values is present (testing only the critical fields)
- [x] "Incorrect or missing information can cause delays in the processing of your leave application" can be left empty and next tab "Alternate contact information" should show up

Note
"Incorrect or missing information can cause delays in the processing of your leave application" is mandatory only on form submission so will test that as part of another ticket

**Comment by fazil-ey** [comment]
script - https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Maternity%20Parental%20L%26A/MaternityEmployeeInfo_1886.side?csf=1&web=1&e=gt56fc

**Comment by ayushdamani** [comment]
Working great - thanks Fazil!

**Comment by Stella-Archer** [comment]
Perfect - Good to go PO A = closed
<img width="1119" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXZLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e04c834ea34f81a43e3f85d7ab0dcb9e7de651c9/image.png" alt="image.png" />
