### ISSUE TITLE
 Mat/Pat - Alternate contact information Validations

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1887]
Tab -  Alternate contact information
**AC**
- [x] Validation message shows when invalid email is entered
- [x] Validation message shows when invalid phone is entered (when invalid characters are types nothing shows up in the field, so may not be possible to test in selenium)
- [x] Email and Phone can be left empty, so should be able to hit next and Maternity leave tab should show up

**Comment by fazil-ey** [comment]
script -https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Maternity%20Parental%20L%26A/MaternityAlternateContact_1887.side?csf=1&web=1&e=DY0f4U

**Comment by ayushdamani** [comment]
Thanks Fazil - moving to PO!

**Comment by Stella-Archer** [comment]
Success - this worked great PO approved and Closing
<img width="1118" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDdLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccc32c19d9aef51a8882a6fd9489860591e93ff6/image.png" alt="image.png" />
