### ISSUE TITLE
Mat/Pat - Maternity leave validations

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1888]
Tab -  Maternity leave
**AC**
- [x] Validation message shows when "Are you the birthing parent?" is not answered and next is hit
- [x] If "Yes" is hit for "Are you the birthing parent?" the following tabs are shown
Maternity leave - General information
Maternity leave - Start date
Maternity leave - Length of leave information
Maternity leave - Length of leave
Maternity leave - Leave allowance information
Maternity leave - Leave allowance
- [x] If "No" is hit for "Are you the birthing parent?" the following tabs are hidden

**Comment by fazil-ey** [comment]
Link https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Maternity%20Parental%20L%26A/MaternityInformationAndValidation_1888_1889.side?csf=1&web=1&e=edvSNd

**Comment by ayushdamani** [comment]
Script working great - acceptance criteria met

**Comment by Stella-Archer** [comment]
Worked perfect PO Approved & Closing ticket
<img width="1119" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGpQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16e7fd1fef41e01707546dea04d6e4fad5dfa793/image.png" alt="image.png" />
