### ISSUE TITLE
Mat/Pat - Maternity leave - General information & Maternity leave - Length of leave information

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1889]
Tab -  Maternity leave - General information & Maternity leave - Length of leave information

**AC**
- [ ] Content is present for Maternity leave - General information
- [ ] Content is present for Maternity leave - Length of leave information

**Comment by fazil-ey** [comment]
Script: https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Maternity%20Parental%20L%26A/MaternityInformation_1889.side?csf=1&web=1&e=WfaWd1

**Comment by ayushdamani** [comment]
Worked flawlessly! Thanks Fazil!

**Comment by Stella-Archer** [comment]
Infotest worked great
<img width="1119" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEhQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4fc2056425df304cc4e12a286ef2f5c010060399/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Length of leave also tested perfectly PO'd  and closing 
<img width="1119" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFRQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9cbcbf91e690b3efd0f3dbd681b7d3145ee5776/image.png" alt="image.png" />
