### ISSUE TITLE
Mat/Pat - Maternity leave - Leave allowance

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1891]
Tab -  Maternity leave - Leave allowance

**AC**
- [x] "Are you applying for maternity leave allowance?"  must be answered before going to next, validation should appear

---
Notes
 validation that both must be same can be checked along with parental leave allowance selection parental

**Comment by fazil-ey** [comment]
script https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Maternity%20Parental%20L%26A/MaternityAllowance_1891_1892.side?csf=1&web=1&e=vdu4d2

**Comment by Stella-Archer** [comment]
Worked great - PO Approved, Closing ticket
<img width="929" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTdQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf4136d30b54a2484d31bc75e81bd0d856573bda/image.png" alt="image.png" />
