### ISSUE TITLE
Mat/Pat - Maternity leave - Leave allowance information

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1892]
Tab -  Leave allowance information
**AC**
- [x] Validate if calculation box appears
- [x] Validate if basic pay is $1000, EI Estimate is $200 and Additional earnings is $50, Estimated leave allowance  should be $175, Estimated total weekly earnings should be $375.00
- [x] Validate if basic pay is $1000, EI Estimate is $200, Estimated leave allowance should be $225, Estimated total weekly earnings should be $425
- [x] All 3 tooltips should be present
- [x] If basic pay or EI estimate is not entered, validation error should be present when Estimate is clicked

---
Notes

**Comment by fazil-ey** [comment]
https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Maternity%20Parental%20L%26A/MaternityAllowance_1891_1892.side?csf=1&web=1&e=vdu4d2

**Comment by ayushdamani** [comment]
Confirmed working! Moving to PO

**Comment by Stella-Archer** [comment]
Allowance info is working perfectly. PO approved & closing this ticket
<img width="929" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0xQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4837c1828b6071fe93843164cae8cd6190412c0e/image.png" alt="image.png" />
