### ISSUE TITLE
Mat/Pat - Maternity leave - Start Date

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1893]
Tab -  Leave allowance information
**AC**
- [x] Should not be a date in the past
- [x] Should not be more than 2 months in the future
- [x] if a day other than Saturday then Saturday checkbox should appear 
- [x] Saturday checkbox is mandatory, validation should appear if not selected
- [x] Saturday yellow alert box should be present 
- [x] Start date is mandatory, validation should appear if not entered
---
Notes

**Comment by fazil-ey** [comment]
@ayushdamani to test 

https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Maternity%20Parental%20L%26A/MaternityStartDate_1893.side?csf=1&web=1&e=EBWQrp

**Comment by ayushdamani** [comment]
Script worked great! I just had to increase the duration between clicks, while moving from one action to another!
Moving to PO!

**Comment by Stella-Archer** [comment]
This failed for me @ the start date >
<img width="1537" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3JyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba06e1af628a73a709a8cd12a9e18bbe54c9aff2/image.png" alt="image.png" />


<img width="1537" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ZyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2d7e0107a3e0c2d98c3cb1419d852972f1c95bf/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
Worked Perfect!!! PO Approved, Closing Ticket
<img width="1159" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGJQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59d298bea273ecc5e2f8d10831cb0bfca20db108/image.png" alt="image.png" />
