### ISSUE TITLE
[Telework]: Supervisor ADM approval is n NOT showing up in the PDF

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1898]
**User Story**
“As a telework requestor I want to see my supervisor/ADM sign off/approval of my request in the PDF soi t is a valid and approved evidence.” 

**Tasks**
In PROD and TEST check PDF after approval for approval of PDF
check when this started in PROD, 
inform people who haven't go the correct PDF to do so when issue is fixed

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [ ] End-to-end functional testing 
- [ ] End-to-end UX testing
- [ ] If change is data impacting, test to confirm data has been sent with BI/DIO team

**Comment by bhumin-fw** [comment]
Changes have been deployed to the TEST environment. Please review the entire form at submission time, edit the form, and review the form for approval and denial.

**Comment by Stella-Archer** [comment]
Thx @bhumin I see the section in the submitted as well as the emails sent to supervisor @ayushdamani could you check you see the approvals in your employee version (both submitted tab and email sent)
<img width="1303" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3JyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--607b972b371dfcda4e98e26815bd798e476ce04d/image.png" alt="image.png" />

<img width="1269" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3pyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a3d6763a642d5ab338fc8fbb57eb052e569fad1/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
I can see the manager approval in test pdf after approval.

**Comment by Stella-Archer** [comment]
@Fazill that is as an employee?

**Comment by Stella-Archer** [comment]
@bhumin this look perfect in test - good to move fix to PROD

**Comment by Stella-Archer** [comment]
In PORD ready for TEST now

**Comment by Stella-Archer** [comment]
this is working in Prod now many thanks @bhumin-fw a new issue was discovered with validation we will write up a new tix for that
closing this
