### ISSUE TITLE
1.10: One submission not pass through, ask user to resubmit.

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1901]

**Comment by Stella-Archer** [comment]
SSl issue must reach out to user to processes again

**Comment by bhumin-fw** [comment]
@Stella-Archer 
Could you please ask Forrest Jacob to re-approve the form? The manager needs to go to the "Review and Process" tab, find the mat-pat form that was not approved correctly, verify or review their decision (it must show "Approved" as the selected option), and then resubmit the decision.

**Comment by bhumin-fw** [comment]
@Stella-Archer @ayushdamani 
We do not need to ask user to re-submit, I was able to find all detail and run in system with administrative code to pass this submission. Let's check with LDB mail box, did they receive mail in their mailbox?

**Comment by Stella-Archer** [comment]
Hear back from LDB they received submission
