### ISSUE TITLE
[Telework] : form is submitted without managers agreement

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1903]
Background:
While testing in PROD we noticed we (as supervisor) were able to submit a telework agreement Approval without selecting the "I have read the above..." agreement box (see screenshot below)

Steps to Reproduce:
- [x]  Have employee file out form in PROD, complete all aspects of approval as manager approval
- [x]  Do NOT select agreement box
- [ ]  submit approval
- [ ]  Note if submission is successful

Actual Behavior:
Form is successfully processed without selecting 'agreement box'
 
Expected Behaviour:
Manager MUST select 'agreed to' box before approval is submitted
if it is not selected validation error and message is displayed and submission can not proceed

Environment:
PROD 
<img width="1204" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGYyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21de004e0508afd9b50b4500b267e936d58f2608/image.png" alt="image.png" />

Acceptance Criteria:
Test:
- [ ] Component functionally test
- [ ] Integration
- [ ] End to end UX
- [ ] End to end functionality
- [ ] if data impacting confirm w/BI/DIO team

**Comment by ayushdamani** [comment]
@Andrew-Vargas-bcgov please discuss this ticket with Stella

**Comment by ayushdamani** [comment]
Cannot produce the error anymore - thanks Andrew!
