### ISSUE TITLE
Telework: Submission failed at the stage of sending data to ODS

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1908]
In production tasks we did notice few submissions fails due to null value in employeesignaturetime stamp. This issue occurred in latest and old submission.

Task:

- [ ] Fix employeesignatureTimeStamp null value in telework workflow

**Comment by fazil-ey** [comment]
To test We should submit telework form multiple times and see if any submissions fail.

**Comment by bhumin-fw** [comment]
It is ready for testing in the DEV or TEST environment. Please submit at least 2-3 telework requests and approve them (they will not be processed if denied). Ensure that at least one telework form is edited by the employee before approval.

**Comment by bhumin-fw** [comment]
@ayushdamani I did review all submissions that approved today. they all went successfully. We are good to close this ticket.

**Comment by Stella-Archer** [comment]
Hi @bhumin-fw I've but a couple of teleworks through
"Andrew 02" and a"Andrew 03" have been edited
could you check to see if it sent data
<img width="1622" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0haQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b1c83288cbb7fc694f8e63f578d3de25b01b01f/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
@Stella-Archer 
On test environment Andrew TEST  01, Andrew TEST 02, Andrew TEST 03 data sent successfully to ODS test endpoints.

**Comment by Stella-Archer** [comment]
Perfect I think this is good to move to PROD the 
PO Approved & sending to deploy
