### ISSUE TITLE
 Mat/Pat - Parental leave - Leave type and length of leave 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1911]
Tab -  Parental leave - Leave type and length of leave 
**AC**
If only parental leave and leave type is standard
- [ ] How many weeks of leave do you want to take? should appear with the following desc
"You can take up to 37 weeks of standard leave (or 35 weeks if taking the full 17 weeks of maternity leave)"
- [ ] Weeks cannot be greater than 37 or less than zero
- [ ] If weeks is 0, days must be present and between 1-6 inclusive
- [ ] if weeks is present, and days is present, days must be between 0-6
- [ ] Weeks must be filled before going to next tab

If only parental leave and leave type is extended
- [ ] How many weeks of leave do you want to take? should appear with the following desc
"You can take up to 63 weeks of standard leave (or 61 weeks if taking the full 17 weeks of maternity leave)"
- [ ] Weeks cannot be greater than 63 or less than zero

If maternity + parental leave and leave type is standard
- [ ] Weeks cannot be greater than 61

If maternity + parental leave and leave type is extended
- [ ] Weeks cannot be greater than 35

**Comment by fazil-ey** [comment]
link -https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Maternity%20Parental%20L%26A/ParentalLeaveTypeandLength_1911.side?csf=1&web=1&e=p2yNY7

**Comment by ayushdamani** [comment]
Thanks Fazil!

**Comment by Stella-Archer** [comment]
Worked perfect! PO Approved and Closed
<img width="894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXpLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3636ad262a4d4b175cdbef5af887114a48f7756c/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
PArtner info checks out too
<img width="894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekRLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--245e1e82b6903e3c8993bd6fb44da79b145a035e/image.png" alt="image.png" />
