### ISSUE TITLE
Mat/Pat - Parental Leave start date

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1914]
Parental leave start date

- [ ] Should not be more than 2 months in the future 

If taking only parental leave
- [ ] Should not be before child's birth date 
- [ ] Should be with 52/78 weeks of child's birth date for standard/external leave

If taking maternal leave + Parental leave
- [ ] Should be after end of paternity leave

**Comment by fazil-ey** [comment]
Script - https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Maternity%20Parental%20L%26A/ParentalLeaveTypeLengthStartDate_1914.side?csf=1&web=1&e=4ncpHR

**Comment by ayushdamani** [comment]
Working perfect!

**Comment by Stella-Archer** [comment]
@ayushdamani  I'm getting an error, It fails at the date picker - I'm not sure if I needed to but the dates in manually or not, Could you look at this again and see if you get an error as well? 
<img width="1131" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0REQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9cdd4038f944b4bf4cfe19b98ca05da14f60d5ee/image.png" alt="image.png" />
<img width="1689" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0hEQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--853b1bfa222ccd3dd19e99d5c2372e89f1a157c5/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Hi Stella,
I tested the script twice and it worked through, can you please try again?
<img width="1484" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZKQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42af34a9e90ce38377db5546215afc23e1856fc1/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
YAY YAY slow and steady wins the race - it worked PO approved & closing

<img width="892" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGZLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdfe74ae88591cbb70b1af5af9d4afd1fe7b9944/image.png" alt="image.png" />
