### ISSUE TITLE
COI: Change the name of the API to "Digital Journeys"

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1915]
Change the name of the API to "Digital Journeys" from "Digital Form: MatPar" which is what it shows in the live CRM now

<img width="814" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVEyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0509f39ef2099a5bfc508e9ecadf2e788e3fd17b/image.png" alt="image.png" />

<img width="852" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1E3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eea6a9583b3fb65eef308cb81b783cfd0a66e523/image.png" alt="image.png" />

<img width="843" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmxQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee2c0b735ff9efc7c966982350ac9723570542fb/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Stella will be talking to Nicholas to request for some Nancy time!

**Comment by Stella-Archer** [comment]
Nancy has confirmed this has been completed.
We can have Karen's team check before release

**Comment by Stella-Archer** [comment]
The new name is now appearing in the live CRM it looks like it works retroactively and all items coming from our API in past are now labeled as 'Digital Journey'
<img width="1022" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--990d9e051b21caec97e4cbbefe3aaaf57933e612/image.png" alt="image.png" />
