### ISSUE TITLE
[CoI]: Add link to the Ethics Advisory Service 

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1918]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
“As a supervisor I want have quick and accurate connection to the Ethics Advisory service at BC Public Service Agency so I can get resolve any questions or issues I have around the process promptly.” 

**Tasks**
Change BC Public service agency link in the Supervisor Documentation and Decision section to:

the **Ethics Advisory service at BC Public Service Agency**

and link it to the email address: ethics@gov.bc.ca
 
<img width="1064" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEEzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--626773056d289568603f490cb511785b14f56561/image.png" alt="image.png" />

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [ ] End-to-end functional testing 
- [ ] End-to-end UX testing

**Comment by ayushdamani** [comment]
Ready for test in TEST & DEV

**Comment by fazil-ey** [comment]
Link is not opening correctly 
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Conflict%20of%20Interest/Test%20recordings%20and%20screenshots/Screen%20Recording%202024-10-18%20at%204.27.06%E2%80%AFPM.mov?csf=1&web=1&e=kaHcAZ

**Comment by ayushdamani** [comment]
Changes are up in TEST & DEV :)

**Comment by Stella-Archer** [comment]
yay works great @ayushdamani one teeny tiny thing: it looks like it needs a 'the' before BCPSA ... "or the Ethics advisory Service at **_the_** BC Public Service agency
could you add this.
<img width="1178" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGx3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--348cd26a1c18a22f08156893d0b840e6c1324492/image.png" alt="image.png" />

**Comment by ayushdamani** [comment]
Changes are up in TEST and DEV

**Comment by Stella-Archer** [comment]
Looks excellent ready to go
<img width="1603" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDU3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--334af3fe5a4517baa3a9708ae7ebfdec796693df/image.png" alt="image.png" />
