### ISSUE TITLE
Mat/Pat - Supervisor Submission Bug

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1920]
Supervisor is not able to edit the form for an applicant after approval. 
There should be no time limit for editing after submission.

**Issue identified:** There a validation that start date cannot be more than a month in the past. This effectively created a time limit where if the number of weeks is being extended after 1 month of the leave start, their will be a validation error for the validation. 

**Solution:** If form is approved, and the start date has not been changed, this validation (start date must not be more than 1 month in the past) will NOT be triggered when supervisor edits

**Comment by ayushdamani** [comment]
We are asking Connie to update this!
