### ISSUE TITLE
telework: Workflow fail

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#1928]
One telework workflow failed due to missing data on the form. Please review and identify which field has the data discrepancy, fix it, and implement the solution in production on priority.

**Comment by Stella-Archer** [comment]
Limit max @ 3000 characters but some are coming in at 6000 which causes work flow failure
@bhumin-fw is verifying

**Comment by bhumin-fw** [comment]
Failed data workflow passed, Send data successfully to ODS.
