### ISSUE TITLE
Telework: update manager's notification email language

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#198]
**Acceptance Criteria**
- Email copy is replaced with new language (see comments).
- Insert managers name into the copy

> Hello (manager's name),
> 
> A new Telework Agreement has been submitted by Meghan Stothers (meghan.stothers@gov.bc.ca).
> 
> Please review this submission in the Manager/Supervisor Sign-Off section of the Agreement at https://digital-journeys-test.apps.silver.devops.gov.bc.ca/task/9d327b61-b203-11ec-b8d0-0a580a61197b to complete and submit this form.
> 
> *If this request is for 3 or more Telework days, you must get approval from your ADM or delegate.
> 
> Thank you.

**Comment by MeghanStothers** [comment]
As a manager receiving the email from my employee with a request to review and approve my Telework agreement, I would like to see the following direction/language in the email: 

PLEASE UPDATE THE CURRENT EMAIL TEXT WITH THE FOLLOWING  
Hello (manager's name), 

A new Telework Agreement has been submitted by Meghan Stothers (meghan.stothers@gov.bc.ca).

Please review this submission in the Manager/Supervisor Sign-Off section of the Agreement at https://digital-journeys-test.apps.silver.devops.gov.bc.ca/task/9d327b61-b203-11ec-b8d0-0a580a61197b to complete and submit this form.

*If this request is for 3 or more Telework days, you must get approval from your ADM or delegate.

Thank you.

This ticket will be considered done when the language has been updated and includes the programmatic work to embed the manager's name and link to the employee's unique submission/Telework form

**Comment by schuyt** [comment]
@simensma-fresh Do you know to add newlines characters into the email body in the Camunda modeller?

**Comment by MeghanStothers** [comment]
To complete this ticket, we will need to 
- Kamunda modeler editor (Don, Hasan)
- also needs Postman API deployment (
- Don to share documentation when he is back from hols April 19

Ji noted we will need to find an easier way to update the interface to use the email content language

**Comment by MeghanStothers** [comment]
See ticket #209 as good way for Don, Stella, Hasan to update the language

**Comment by MeghanStothers** [comment]
Ji - updated language for you to add:

Hello (manager's name),

A new Telework Agreement has been submitted by Meghan Stothers (meghan.stothers@gov.bc.ca).

Please review and submit the submission in the Manager/Supervisor sign-off section of the Agreement (PLEASE EMBED the URL in "Manager/Supervisor sign-off section" 
URL: https://digital-journeys-test.apps.silver.devops.gov.bc.ca/task/9d327b61-b203-11ec-b8d0-0a580a61197b 

Please note: If this request is for 3 or more Telework days, you must get approval from your ADM or delegate.

Thank you.

**Comment by DonMoffatt** [comment]
@jizhaogit Let's discuss this Friday April 22.  I need to change the message in the model. I might need your help downloading a copy of the model that is in use. I will see if I can do it on my own first. If I can it should be an easy modification.

**Comment by DonMoffatt** [comment]
I've made a change in the model and have uploaded it. I will test it to see if the changes work. I may need to collaborate with Ji on this if it doesn't.

**Comment by DonMoffatt** [comment]
Changes completed and ready for testing. I changed the first line from "Hello Stothers,Meghan" to "To: Stothers, Meghan" in keeping with the more formal way the name is presented. The name is drawn from the autofilled field in the form. Beware: on the modeling side some of the variables reference variables defined in Camunda while others reference the form field names. @MeghanStothers  @Stella-Archer

**Comment by Stella-Archer** [comment]
@MeghanStothers  message has been updated there are some limitations due to how fields have been populates see attached email message
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/466766a0-d5df-45ed-8a01-6f972ae16f85)

**Comment by DonMoffatt** [comment]
I will need to look at embedding the url on Monday. Hard coding in html didn't work but there is a workaround, I think.

________________________________

**Comment by DonMoffatt** [comment]
@MeghanStothers This appears to be done. Do you want me to close the issue or do you want a final look?

**Comment by DonMoffatt** [comment]
@MeghanStothers Hi Meghan - after discussing it with Stella I decided to  close it on my own. We think the issues have been addressed.
