### ISSUE TITLE
Bug: Incorrect data pulled from PeopleSoft: Postal Code and City 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#202]
The field is currently pulling the **office** postal code and city, but it should be pulling the applicants **home** postal code and city.

-Two of the "Telework Location" fields on the telework form have the wrong labels (see screenshots). They have _officeCity_ and _officePostal_, so they're pulling the users office location info instead of their home location.

- I don't see the home postal or city in the data being sent by the ODS, so we may need to coodinate with Justin to have those fields added: 

- Will want to update the documentation here, too: https://bcgov.github.io/digital-journeys/forms/#how-to-auto-populate-form-fields-with-the-user-data

![Screen Shot 2022-04-04 at 3.57.41 PM.png](https://images.zenhubusercontent.com/61c1108df318d4181d4d764d/70ea3484-efa7-42ed-8a0c-2b6ddd167e3c)

![Screen Shot 2022-04-04 at 3.57.50 PM.png](https://images.zenhubusercontent.com/61c1108df318d4181d4d764d/c5403acc-7da0-4861-a8d9-eb735c097df4)

**Comment by MeghanStothers** [comment]
As a user/employee filling out a Telework form, I start by login in with my IDIR. I see the PeopleSoft information has been pulled. The postal code pulled into the form from Peoplesoft is incorrect and does not match the one in my personal information in Peoplesoft

**Comment by schuyt** [comment]
Simen created a PR to fix this [here](https://github.com/bcgov/digital-journeys/pull/207).

Here's some additional details on how to perform the mapping of ODS variables on our side. I've made a Pull Request to add mapping for the postal / city fields which were missing: https://github.com/bcgov/digital-journeys/pull/207. Once this is deployed to dev/test, you can go in and change the property names of those fields in the form builder

The mapping itself is performed in `forms-flow-api/src/formsflow_api/models/employee_data.py`
the left side of the statements is what the name you can use to prepopulate the field using the form builder (API tab of a field -> Property Name), the right side is the name of the field from the ODS you want to map. Spec can be found here: https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rst#Datamart_Telework_employee_demo

@Justin Choy  @Patrick Senaphanh With these changes, we will be sending back the postal code / city to the ODS as `postal`/`city`. Would it be possible to update the Datamart_Telework_app_telework_info endpoint to accept those?
