### ISSUE TITLE
Telework: Remove Digital Signature

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#212]
PIE/Policy team decided that the IDIR login would suffice for ID, and the digital signature is not needed

Remove the signature box in the formsflow tool

Acceptance criteria
- test the form as an employee filling out the form - ensure the box is not visible/removed
- ideally the box will be removed not hidden
- confirm with TES Patrick/Justin data saving and reporting are not affected

**Comment by jizhaogit** [comment]
both manager signature and employee signature are removed from telework form in DEV site.
