### ISSUE TITLE
Telework - Add text box to "Costs" section on digital form

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#213]
PIE/Policy team has requested we add an text box to the digital form

Questions to ask Policy/Sean:
1) Is it a text field (more limited) of a text area  

2) Text or numbers wanted in this field?

2) What language do they want?:
Example "Please add the items and costs of the items you have at..." 

3) Please describe what they want here

4)  Business will get all requirements before estimating this ticket

For the dev team, we will consider possible affects to review:
- formatting of form changes
- ODS data pull and push
- pdf changes

Acceptance criteria
- Data field is tested and functional
- data does not disrupt flows
- User can go into to this costs section and add the info easily
- all pdfs have properly formatted information   

Our recommendation is a text field with a character limits we will determine once we know what they want

**Comment by Abuchana** [comment]
Duplicate ticket with #218
