### ISSUE TITLE
Telework: Make a direct link to the IDIR login (not via KeyCloak)

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#214]
As a user, I want to go directly from the Telework link on the Careers & MyHR page to the IDIR login page (rather than having to click "IDIR" on the Keycloak page: "PSA-DIGITAL-JOURNEY-TEST" page. 

Link to test page on Careers & MyHR- https://www2.qa.gov.bc.ca/gov/content/careers-myhr/all-employees/work-arrangements/flexible-workplaces/get-started-with-flexible-work-in-the-bc-public-service-clone-62682

After clicking on "Telework Agreement" users are taken to an authentication page where the user name password is the primary login process with secondary options for "IDIR" and "Google" (as shown in the screenshot below)
![SS1.JPG](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/994c0706-0864-4350-b42a-15c1d20eb5a5)

After clicking on IDIR as the login options users are taken to a page to enter their IDIR credentials. (screenshot given below)
![SS2.JPG](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/7c80e6bc-c525-46b1-a430-25309e0ccda1)

We need this page to be the default method of signing in for users.

**Comment by schuyt** [comment]
Need to get Keycloak admin credentials to Warren and Ji

**Comment by warrenchristian1telus** [comment]
I have updated KeyCloak admin to use IDIR (ocio) as the defaut authentication provider.

![image](https://user-images.githubusercontent.com/70002196/163875491-caeff6ab-328d-4c6f-8b4c-cb2ff13f920e.png)

Changes are in dev: https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/

@schuyt Do we have a procedure in place for tracking and migrating admin / DB config changes? Not sure if/how we can get something like this into the repo. Possibly in the KeyCloak ConfigMap or similar?

https://github.com/bcgov/digital-journeys/blob/29685a840d69208ec73267681a6dbbeb8e69558f/deployment/openshift/web_config.yaml#L51

**Comment by warrenchristian1telus** [comment]
Changes are in test: https://digital-journeys-test.apps.silver.devops.gov.bc.ca/

**Comment by DonMoffatt** [comment]
I tested it and it works for me.

**Comment by Stella-Archer** [comment]
this works correctly in test; https://digital-journeys-test.apps.silver.devops.gov.bc.ca/form goes directly  to ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/cc5607fc-d1be-4833-a74e-db515377ec4a)
in Dev https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form goes to ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/61cc8f5f-f14f-4b40-8cbf-d62c3d512ca4) I don't think it's critical that DEV behaves exactly the same as there will not be end users in here - meet MVP will close ticket

**Comment by warrenchristian1telus** [comment]
Just a note there there is a "part b" to the process (Identity Providers > IDIR) that was initially missed in dev. This has been resolved, and I added the step to my earlier comment: https://github.com/bcgov/digital-journeys/issues/214#issuecomment-1101761097

**Comment by warrenchristian1telus** [comment]
Redirect added to production login as well.
