### ISSUE TITLE
Limit emails allowed to BC Government emails only

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#215]
As PSA I would like the option to only allow the Employee Emails to be used in some forms. This should be a validation option a Forms Designer can apply to specific forms. 

**Acceptance Criteria**

- Only valid BC Government emails can be entered in the "Email" field.
- Forms Designer has the ability to use this feature selectively on certain forms

**Comment by schuyt** [comment]
@MeghanStothers To determine a list of valid BC Gov email domains, or considering making this field read-only.

**Comment by warrenchristian1telus** [comment]
We need to have this associated with specific forms and fields to be actionable.

@Stella-Archer @MeghanStothers can you please let us know which forms / fields this should apply to?

**Comment by DonMoffatt** [comment]
Duplicated in #360

**Comment by MeghanStothers** [comment]
Duplicate ticket closed
