### ISSUE TITLE
TOOL: Dashboard Interface: For Form Reviewers

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#217]
Relooking at what the user interface for form reviewers will look like to incoming submissions for approval/rejection.

**Comment by HasanSifat** [comment]
Current considerations-

Only Forms and Tasks tabs will be visible to form reviewers
1.1- Forms tab to show forms accessible to a certain user
1.2- Tasks tab will only show tasks to be carried out by a user with a status message in the left pane to show "Pending/Approved/Denied"
1.3- Forms tab should have the option to make a new submission and view previous submissions besides each form available to a certain user

Current test and dev environment have all historical submissions available to any/all users coming into the environment. The tasks tab has submissions that have no relation to a new user coming in. Forms tab gives access to all available forms in that particular environment.

The Prod environment has a bug where new users coming into the task tab in the environment as reviewers get an "Unauthorized" error and has no info filled out from the submission of the employee. The manager's section is also not visible. Ticket#292 has been created to address this issue

**Comment by MeghanStothers** [comment]
Stella to QA and compare against a similar ticket

**Comment by alexandralloyd** [comment]
These issues now captured in Ticket #335.
