### ISSUE TITLE
Telework:  Add a text box to cost section

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#218]
As a user, I want to record any costs my Employer has agreed to pay for as part of my Agreement.

Requirements:
1. Add a text box with character limit of approximately 500

2) Please the box at the bottom of the "costs" (section 11)

3) add the following language to the top of the box
Optional: Employees and supervisors have agreed the Employer will pay the for the following:

Include an estimated annual cost related to the item(s)

**Comment by DonMoffatt** [comment]
I've added the text box. Please test it to confirm that it meets the needs.

**Comment by MeghanStothers** [comment]
Great, although I cannot see the box/language, so assume it needs to be pushed to test next by Ji:

TEST LINK: https://www2.qa.gov.bc.ca/gov/content/careers-myhr/all-employees/work-arrangements/flexible-workplaces/get-started-with-flexible-work-in-the-bc-public-service-clone-62682

**Comment by jizhaogit** [comment]
Get a 403 error when i try to touch the page that Meghan included.  Don would you please let me know what is the details?  thanks.

**Comment by DonMoffatt** [comment]
I think the link was incorrect and I forwarded instructions on where to find the form.

**Comment by DonMoffatt** [comment]
Ji asked if the contents of this box need to go to the ODS. I thought the answer was no, but I am not sure. @MeghanStothers do you know?

**Comment by MeghanStothers** [comment]
You are right @DonMoffatt - the info will not go to the ODS

**Comment by DonMoffatt** [comment]
@MeghanStothers Could Ji and I have a list of what goes to the ODS please?

**Comment by DonMoffatt** [comment]
@MeghanStothers and @Stella-Archer Would you please look at the text box I've added to the "Telework Agreement - Copy" version of the form in DEV? If you approve of the change Ji will push it to TEST.

**Comment by Stella-Archer** [comment]
@MeghanStothers the fix is in dev still here's the link https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form/6245258a5302ccaf000035e7
@DonMoffatt ![image.png]
(https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/9ab61955-87d3-4109-b35c-ea00908c4f2a)

**Comment by DonMoffatt** [comment]
@MeghanStothers I made the changes and they look fine in TEST. I am closing the ticket.
