### ISSUE TITLE
Auto-generate PDF on form submission

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#22]
_As a BC Gov Employee I would like to receive a PDF copy of the form I submitted so I can reference the form later if needed._

_As a Supervisor I would like to receive a PDF copy of the form that was submitted so that I can review the submission easily and have a copy for my records._

_As a form designer I would like to specify that a PDF copy be generated when a form is designed so that I can use that PDF in my workflows._

**Acceptance Criteria**

- Ability to enable/disable PDF generation on a given form
- When enabled, on submission of a form a PDF copy is generated
- We don't need/want to store the PDF's permanently on the server
- If form has file attachments, we can list the filename for now (file attachments on the form will be handled in another story)
- Given a submission's status changes, an email with a PDF attached gets sent to the employee (and manager)

**Notes:**
- Will need to add a listener and create functionality for this
- Would be good to have on the Camunda as a workflow

**Comment by qudsia-khan-fw** [comment]
@matbusby-fw

1. According to the Acceptance Criteria, a PDF should be generated on submission. Currently, this is not happening.
2. After the supervisor approves or rejects the application, the PDF in the email is blank. Please see the attached pdf.
[Reference Submission](https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form/61e9f5286dd5b367312d9c2e/submission/62347c88b6fef0bf7ed32ad9)
[https://app.zenhub.com/files/439477060/adc8163b-3e5c-46b3-b316-06c6fd802685/download](https://app.zenhub.com/files/439477060/adc8163b-3e5c-46b3-b316-06c6fd802685/download)

**Comment by qudsia-khan-fw** [comment]
1. According to the Acceptance Criteria, a PDF should be generated on submission. Currently, this is not happening.
2. Long comments up to 255 characters are not fully visible in the PDF
![Screen Shot 2022-03-21 at 10.09.46 AM.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/6bf66334-2171-4c6f-86f7-ad57cffb8928)

**Comment by qudsia-khan-fw** [comment]
Created [bug ticket](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/bcgov/digital-journeys/157) for the content cut-off issue.
