### ISSUE TITLE
Create Production Environment

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#222]
As a forms designer, I need to be able to push the form to an environment where it can be seen by the wider government in order to test and use it by end users.

**Comment by Abuchana** [comment]
Aim for May 20th 
Warren inquiring with Phill

**Comment by warrenchristian1telus** [comment]
The production environment is live. I'm looking into any outstanding transfers / migrations that may be required. There is currently no content, but it otherwise seems to be functioning as expected.

https://digital-journeys.apps.silver.devops.gov.bc.ca

**Comment by DonMoffatt** [comment]
We will only know whether this is functioning when we have tested forms in it.

**Comment by Stella-Archer** [comment]
Monday May 9th - still getting 'No forms found'

**Comment by warrenchristian1telus** [comment]
@Stella-Archer @DonMoffatt - I'm seeing the Telework form in production. Maybe this is due to a permissions issue. I'll see if I can spot a discrepancy in KeyCloak.

![image](https://user-images.githubusercontent.com/70002196/167469198-50050849-6bb1-4ede-b384-388ca7f45f7b.png)

**Comment by warrenchristian1telus** [comment]
@Stella-Archer @DonMoffatt I think I've found and resolved the permissions issue in production. Please test again and let me know if you can now see the Telework Agreement form.

**Comment by warrenchristian1telus** [comment]
Found an issue with forms-flow-bpm-85-z4xpf: CrashLoopBackOff

Investigating the root cause.

Moving this back to in progress until resolved.

**Comment by warrenchristian1telus** [comment]
@iman-jamali-fw Once the deployment is completed with #232, please ensure that the latest Telework Agreement form updates are in production, then we can move this to QA for review.
