### ISSUE TITLE
telework test sends wrong links to manager

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#226]

**Comment by Stella-Archer** [comment]
As a manager I receive a email telework submission from and employee. The link in the email goes to 'my tasks' not the specific form to approve. This makes it impossible to know what to approve.

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/ca3d8e23-8653-4304-aad3-a41d58849b05)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/69c2b109-da8b-4708-8d8f-c9aa7bcf348b)

**Comment by Abuchana** [comment]
- [ ] Stella to check which environment(s) this occurs in

**Comment by jizhaogit** [comment]
Please use the following email body content:

To: ${supervisorName},


A new Telework Agreement has been submitted by ${name}  (${email}).


Please review this submission in the Manager/Supervisor Sign-Off section of the Agreement at $BASE_URL/task/$TASK_ID to complete and submit this form. 


*If this request is for 3 or more Telework days, you must get approval from your ADM or delegate.




Thank you.

**Comment by Abuchana** [comment]
Thanks, Ji! Just checking… were you just updating the ticket to capture what to do or did someone need to action it? You are the only one assigned to the ticket so if you need someone to action it, we need to reassign it to them.

Alison Buchanan
Scrum Master, Project Manager
Corporate Services Division | BC Public Service Agency
810 Blanshard St | Victoria BC | Tel 778.698.2133

**Comment by jizhaogit** [comment]
Hi Alison, it is more like a knowledge sharing.  no more action need to be taken. the content is already be deployed in dev.   Thanks

**Comment by Abuchana** [comment]
Ok, thank you for the clarification! 😊

Alison Buchanan
Scrum Master, Project Manager
Corporate Services Division | BC Public Service Agency
810 Blanshard St | Victoria BC | Tel 778.698.2133

**Comment by Stella-Archer** [comment]
The issue is resolved in DEV & PROD, currently not receiving messages from TEST so can not confirm for that environment
