### ISSUE TITLE
As a form submitter I can receive an email confirmation on submission

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#24]
As a form submitter,  I would like to be able to receive an email confirmation when I submit a form

**Acceptance Criteria**
- On submission of a form an email is successfully sent to the submitter

**Test Notes**
- Will want to setup a mail trap for now

**Tech Notes:**
- [SMTP setup](https://help.form.io/developers/email-integrations#smtp)

**Comment by qudsia-khan-fw** [comment]
- The email will go to the submitter as well as the appropriate manager
- In the future, we will want to include other third parties
