### ISSUE TITLE
Ability to track tests by environment

### ISSUE THREAD

**Issue by T854236** [bcgov/digital-journeys#270]
Have ability to separate test submissions from different environment.

**Comment by T854236** [comment]
There are 2 non-prod environments:  PROD and non-PROD.  The API server tracks source IP of every call made.  Sample below.  

![image.png](https://images.zenhubusercontent.com/626979332cf51c6ab3c77983/2c23ad26-1747-48f7-95f7-34d25f6c16b7)

@warrenchristian1telus I have enabled GET on that endpoint.

**Comment by MeghanStothers** [comment]
Do we need to test this one? Let's ask Patrick at next scrum

**Comment by T854236** [comment]
We should discuss if there is an action needed based on what was shared during SCRUM meeting by Warren.  The concern was that tests from DEV/TES forms are hitting non-PROD ODS and if there is a requirement to separate them.  If there is no need to differentiate them in ODS then we can close/cancel this task.

Submission from PROD would be hitting PROD ODS.

**Comment by MeghanStothers** [comment]
Patrick/TES would like more info about the requirements. TES and PSA business team to look at this one together and make decision about separating test environments

**Comment by MeghanStothers** [comment]
Developers to review this one at tomorrow's scrum so business can make a deci0dion

**Comment by MeghanStothers** [comment]
Decision at meeting today:  Re-open if it becomes an issue if we need to differentiate between dev and test data
