### ISSUE TITLE
Security Vulnerabilities of Application

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#271]

**Comment by MeghanStothers** [comment]
As a program area leads, we need to have an established approach and someone with security/technical skills to maintain and update the OpenShift application.

**Comment by MeghanStothers** [comment]
May 16 - Igor sent email message noting 37 security vulnerabilities 
May 17 - consulted with Warren who noted two possible approaches 1) scheduled updates (weekly or monthly) or 2) Repo/alert system, almost daily updates
In short term, our team will ask Warren/someone to review the vulnerabilities  
In the longer term, we will need to have a resource to address this essential work to keep the application updated (noting the single-sign authentication on reduces the risk). 
Given this work would be a full-time job, we will connect with BP/other PSA product owners about how they are doing this work and if we could have a shared resource who oversees this work, given this person will likely be working on many PSA product teams.

**Comment by Abuchana** [comment]
OCIO resources
• OCIO  Vulnerability Patch Standard: https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-management-technology/information-security/defensible-security/ocio_patch_guidelines_-_2021-02-18.pdf

• OCIO Security Standard for Application and Web Development and Deployment: security_standard_application_web_development_deployment.pdf (gov.bc.ca)

**Comment by fazil-ey** [comment]
all issues completed
