### ISSUE TITLE
Telework: TES consult about load testing

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#279]

**Comment by MeghanStothers** [comment]
For the Telework corporate roll-out, BP/TES/PSA Product teams will need to set up a consult with Patrick TES about ODS and any plans and/or requirements for testing and high-load situations.  We will want to talk about: timing, our understanding of server limits and requirements for concurrent connections.  The PSA product team advised form owners (PIE) to consider a staggered rollout for employees to submit Telework forms, rather than a fixed deadline.

**Comment by alexandralloyd** [comment]
Waiting for a consultation with Karim about load testing.
