### ISSUE TITLE
The user should be displayed with a message after form submission

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#28]
**Background:** The user should be displayed with the toast message upon form submission

**Actual Behavior:** Currently, after submitting the form, the user is displayed with the toast "Submission Saved".

**Expected Behavior:** The user should be displayed with a more user-friendly message:

"Thank you for your submission. Once your submission has been reviewed by your supervisor, you will receive a notification via email. You can view a copy of your submission in your forms dashboard."

**Notes**
- See wireframe

**Comment by qudsia-khan-fw** [comment]
**Background:** The user should be displayed with the toast message "Your form was successfully submitted".

**Actual Behavior:** Currently, after submitting the form, the user is displayed with the toast "Submission Saved".

**Expected Behavior:** The user should be displayed with a more user-friendly message such as "Your form was successfully submitted" or "Thank you for your submission".

**Comment by Stella-Archer** [comment]
this worked perfect in DEV ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/56676f09-e4d7-4e0b-bb3e-7cede82b59a1)

**Comment by Stella-Archer** [comment]
Worked well in test as well and message persisted long enough for me to read and understand the instructions
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/0f4906c3-a2f8-4294-b1a8-ce2315b3c1b6)
