### ISSUE TITLE
Add Tags to Differentiate Environments 

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/digital-journeys#282]
Add build tags to pipeline builds to distinguish dev, test and prod deployment images.

Please use these check-boxes to verify as each step is verified. Once all three environments have been successfully deployed and validated to be using the appropriate image tags, this issue will be considered resolved.

**Dev**
- [x] Deployed with :dev tag
    -  [x] Verified by @kkapoor-fresh 

**Test**
- [x] Deployed with :test tag
    - [x] Verified by @warrenchristian1telus 

**Prod**
- [x] Deployed with :prod tag
    - [x] Verified by @warrenchristian1telus

**Comment by warrenchristian1telus** [comment]
Add build tags to pipeline builds to distinguish dev, test and prod deployment images.

Note: This should be done after the same is implemented in the Performance Development environment.

This is to ensure that deployments to dev or test can't unintentionally be used in production due to cluster upgrades or other events which may trigger pod recycling.

Rather than building to :latest, all images should include a tag for their build target environment. :dev, :test, or :prod.

@kkapoor-fresh I will assign this to you, but we can determine timelines as you progress with / complete the rollout for Performance.

**Comment by MeghanStothers** [comment]
Suggestion: Add a checkbox to show testing results in three environments so the developers are clear about which environment the ticket relates to

**Comment by MeghanStothers** [comment]
We'll try checklists for the next sprint and review how this works for the dev team and our team

**Comment by MeghanStothers** [comment]
warren comments: More to do with the deployment and where things are built in open shift. 
About the pipeline that builds images - we need for it to build specific dev, test, prod images

**Comment by Abuchana** [comment]
@warrenchristian1telus Warren, can this ticket be closed now?

**Comment by Abuchana** [comment]
@warrenchristian1telus Sure, just let me know what you need me to do :-)

**Comment by warrenchristian1telus** [comment]
@Abuchana Apparently task list aren't supported in tables. Unfortunate. https://github.community/t/checkboxes-are-not-being-checked/187797

I'll try another way to display it nicely (and have the checkboxes work), but my basic idea was to include both the development task and a testing task. This way, the developers can sign-off on the task, and tag a reviewer to verify the changes, as I did with you in the Dev task above:

![image](https://user-images.githubusercontent.com/70002196/178554186-f85cd176-34ee-4c49-9078-fda2cd3a1119.png)

**Comment by Abuchana** [comment]
@warrenchristian1telus the check boxes at the top worked for me

**Comment by warrenchristian1telus** [comment]
Thanks for helping me test that @Abuchana 

I think managing the [available/assigned] testers in the ticket will be helpful as we onboard developers, have people jumping between projects, going on vacation, etc.

**Comment by will-freshworks** [comment]
Hey @kushal-arora-fw I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/psa-devops-60f098ab875719001bce05fb/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by warrenchristian1telus** [comment]
Hi @kkapoor-fresh there is a build issue with the (missing) TAG param:

![image](https://user-images.githubusercontent.com/70002196/180044683-c126d849-9ea1-4ac5-917b-5e548c56c2b0.png)

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus I have fixed this and pushed my changes to the main but the build failed as there seem to be some issues from a previous merge by David. Once that is resolved, I will be able to run the Github Actions workflow to test out change

**Comment by kkapoor-fresh** [comment]
@Abuchana @warrenchristian1telus The web, api and camunda have been deployed with "dev" and "tags"

**Comment by kkapoor-fresh** [comment]
The above services have been deployed with "production" tags as well.

**Comment by kkapoor-fresh** [comment]
The following services have been updated with proper image tags in Dev, test and Prod

- camunda
- web
- webapi
- files
- forms
- analytics

An important point to understand here is that some of the applications services( forms, files and analytics ) are not being built from the "tools" namespace at the first place but rather have their builds running in their respective deployment namespaces(dev, test and prod) Hence, any recycling of these deployments will not not have any adverse effect on the image being synced to the wrong environment. 
Same is true for DB services.  
Please validate the above services once and let me know.
@simensma-fresh @warrenchristian1telus
-

**Comment by warrenchristian1telus** [comment]
Thanks @kkapoor-fresh. @will-freshworks @simensma-fresh we should probably discuss the implications of this for future patches, security updates, etc.. I'm concerned that if the images aren't all built in tools that this will cause discrepancies when the others are updated. We are looking at making a version upgrade fairly soon after launch, and hoping to be able to use Snyk and/or Dependabot to maintain versioning going forward.

**Comment by simensma-fresh** [comment]
For sure there's some room for improvement here. I think a ticket to 
a) move all the services into our pipelines
b) build using the tools namespace
would be good. 

Another thing we could work towards would be to only build our images once. Seeing as we're always deploying to dev -> test -> prod, we could benefit from doing image promotion instead of re-building the services for each environment.

**Comment by warrenchristian1telus** [comment]
I agree @simensma-fresh - not sure about the image promotion though. I like the sound of "instant" promotion. Just need to be careful of sharing the images, and doing reversions, etc.. We can certainly discuss. I just think if we want to change the process, we'll need to consider it for all projects. So far it seems that individual build / deployment is the safest bet (although it's also the slowest). If we do s hared build, maybe we could look into more advanced tagging / versioning to handle promotions, version updates, rollbacks, etc.

**Comment by warrenchristian1telus** [comment]
Hi @kkapoor-fresh - it's looking good for the main images. Noticed a few missing tags:

    - forms-flow-analytics (+-adhoc-worker, scheduled-worker, etc.)
    - forms-flow-forms

Also, forms-flow-files is a DC in dev, but also a StatefulSet (everywhere else + dev) - I think the DC can likely be deleted from dev. Please do that if it's appropriate.

**Comment by warrenchristian1telus** [comment]
I'm going to move this back to In Progress, but wanted to note that I think this is far enough along to safely go-live, and continue development.

We should ensure that all images have been tagged before attempting a version upgrade, but there is no immediate requirement for that.

**Comment by warrenchristian1telus** [comment]
I will also remove the MVP tag, for the reason mentioned above.

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus The im ages for forms-flow-forms and forms-flow-anlytics(adhoc workers, scheduled-workers etc. ) seem to be have the the proper  "production" tag attached to their images in the image stream as well as the deployment configs. Could you please point me to the namespace/build/deployment where you are seeing the discrepency. ?

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh here is what I meant by the tags not being used:

![image](https://user-images.githubusercontent.com/70002196/183720145-c94d9e0c-9981-455e-a0d6-1b9f9ed18bc6.png)

**Comment by MeghanStothers** [comment]
@simensma-fresh to check in with Kunal
