### ISSUE TITLE
Add Production CDATA Endpoint to FormsFlow Production Deployment

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/digital-journeys#289]
The production CDATA endpoint is now live. Please integrate this into the production application to prepare for final testing and go-live.

Production API URL:
https://analytics-api.psa.gov.bc.ca/apiserver/api.rst

Please ensure that dev and test environments continue to use the (shared) test API:

https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rst

**Comment by DonMoffatt** [comment]
@iman-jamali-fw Is this critical for the launch of Telework, Iman?

**Comment by T854236** [comment]
@iman-jamali-fw yes correct.  It's with the pull/get and not the push with the POST.

**Comment by iman-jamali-fw** [comment]
@warrenchristian1telus You can find the relevent env variables on Openshift, under `forms-flow-webapi` by these two names:
- `EMPLOYEE_DATA_API_URL`
- `EMPLOYEE_DATA_AUTH_TOKEN` I believe this token need to be updated for the new endpoint url.

**Comment by warrenchristian1telus** [comment]
@iman-jamali-fw The above URL and token have been updated. I've also updated the "ODS" URL for POSTS back to CDATA:

ODS_URL = https://analytics-api.psa.gov.bc.ca/apiserver/api.rsc

**Comment by warrenchristian1telus** [comment]
Hi @iman-jamali-fw I've updated the CDATA API Token, but noticed there's a 500 error from request. Not sure if this could be to do with the token being wrong, but I wouldn't expect that could cause a 500 error. Can you please look into it?

![image](https://user-images.githubusercontent.com/70002196/177214317-95c1862b-9aff-4155-b03b-e73b00096fd4.png)

**Comment by MeghanStothers** [comment]
A similar ticket #405 was closed (ticket was about Telework users not seeing Peoplesoft data in PROD)

**Comment by HasanSifat** [comment]
Tested in PROD- 

1. Employee info pre-populated correctly. Name is also in correct order
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/94598366-a790-42b2-b14e-5024efdcf9b4)

2. Address fields also loaded correctly- 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/3d2b9bf5-84a6-427f-83cf-a6f86e78bed0)

Moving ticket to Review Pipeline

**Comment by HasanSifat** [comment]
Tested successfully. Closing ticket
