### ISSUE TITLE
TELEWORK: manager's approval or Rejection email message for submitter

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#291]
As a BCPS employee, I want to receive a notification that my telework application has been rejected (so that I can get more information from the supervisor/delegate approver about my submission. 

Potential rejection message:

"Hello (employee name),

Your Telework submission was not approved.  Please see the comments in the form or check with your Manager/Supervisor (name) or delegate who reviewed your submission.

Thank you."

ACCEPTANCE CRITERIA:
This ticket can be closed when:
- the Telework pdf to employee contains a record/details 
of the decision
- we have a successful test the (correct) rejection message is sent to the employee
- the test is successful in all three environments

**Comment by DonMoffatt** [comment]
@MeghanStothers Please review in TEST.

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/fcb161d5-5234-4197-a688-56c2731e1e02)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/494e0d81-19ea-49ba-8a05-c01270421420)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/300c9516-4bd6-43f0-964a-2ba2a8fa58a4)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/fbf6400c-980c-4b4d-bfe0-4c20b54be684)

**Comment by MeghanStothers** [comment]
If this technical task is complete, let's close the ticket. Ten we can open a new one "email wording" so the writers can review/ere-write the message and ask form/owners (PIE) to sign off on the wording. Otherwise, this ticket will never be closed :)
