### ISSUE TITLE
New Users not getting Reviewer access in Prod environment 

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#292]
When a new user to Formsflow.ai receives a new submission from his/her employee to review a new telework agreement, the user is not able to access the submitted form and is prompted with an "UnAuthorized" error. 

The form can be seen in the tasks tab for the new user, however, it has no info filled out and the managers' section is not visible, screenshots below 
![ss3.JPG](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/7d3c700b-dc34-45fe-9221-99d2c094883b)
![ss2.JPG](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/dc111de2-558c-4deb-922f-94887c0997b0)
 
The form has the following issues-

1. "unauthorized" error
2. No pre-population
3. None of the fields have any data according to the submission made
4. The manager section is not visible.

**Comment by MeghanStothers** [comment]
Iman suggested this might not be a bug, it might be a tool feature we have not used yet.

**Comment by iman-jamali-fw** [comment]
**Issue**
New users onboarding to the PROD is assigned the "Client" role. At this point, assigning other roles including "Reviewer" would require a manual role assignment through the Keycloak dashboard. 

**Goal**
This ticket goal is to automate this process so that Tool automatically assigns the "Reviewer" role to the supervisor.

**Decide on the solution to fix**
The important question for the team is to define when the "Reviewer" role is assigned to the supervisor? 

Some possibilities come to mind:
- Based on the info of the user's IDIR login (e.g., name, email, idir), decide to assign the "Reviewer" role to that logged-in user?
- Whoever clicked on the supervisor email (e.g., https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/task/3e254d12-e5a1-11ec-8eda-0a580a618dca) that is sent in the workflow, will be a "Reviewer" and can review the assigned tasks?

**Comment by iman-jamali-fw** [comment]
After a discussion with @Stella-Archer, I was to look into the possibility of adding the "Reviewer" role to all new users in the PROD. With that regard, I looked into the permissions associated with the "Reviewer" role and compared that to the "Client" role. 

Clients can only see their own submitted forms under the "Application" and "Task" tabs. They cannot sign off a submission even if it is assigned to them.

Reviewers can see their own and other submitted forms under the "Application" and "Task" tabs. They are only able to sign off the submissions that are assigned to them.

**Comment by iman-jamali-fw** [comment]
Please see comment on [#308](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/bcgov/digital-journeys/308) for details on different roles access level and let me know if want to change access-levels for each role.

**Comment by iman-jamali-fw** [comment]
@HasanSifat @Stella-Archer 
In terms of the next steps for this ticket, should I go ahead with this comment from Hasan from #308?

> Expected behaviour-
> By default, users in the following environment need to get these roles-
> 
> 
> DEV
> client
> reviewer
> designer
> 
> TEST
> client
> reviewer* only able to review forms assigned to them for approval/denial
> 
> PROD
> client
> reviewer* only able to review forms assigned to them for approval/denial

**Comment by HasanSifat** [comment]
@iman-jamali-fw,  I would recommend going ahead with this proposed setting and after that, we can test to see how the use cases are functioning. You mentioned having a conversation with Stella and Meghan this week in a previous comment. If my proposed configuration meets those discussed requirements, we should be good to go.

**Comment by iman-jamali-fw** [comment]
TEST and PROD now assign `client` and `reviewer` roles -- by default to the new users.

![Screen Shot 2022-06-09 at 8.25.02 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/0b0b10b3-5b4a-466c-93e3-9a0601d8f720)

**Comment by HasanSifat** [comment]
Reviewer access to Prod Environment has been solved. New users going into prod only have reviewer/client access confirmed.

**Comment by HasanSifat** [comment]
Accessibility and privacy-related issue that was identified is that clients coming to the "forms" tab have now only two options for each form available to them: "Submit new" or "View Submissions" 
When clicking on "View submissions" the client sees all historical submissions made by anyone/everyone. Screenshot below:
![MicrosoftTeams-image (7).png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/a55ee4c3-3994-4583-9ba8-12a693f94fb2)

Acceptance Criteria:
Clients should only see their own submissions made for each form. So ideally, if a certain client has made 1 submission they should be able to see only 1 submission history when going into "View Submissions"

**Comment by iman-jamali-fw** [comment]
@HasanSifat I logged in as a new user on both PROD and TEST and only see one button under Form for submitting a new form. Can you help me reproduce the situation when a new user can see "View Submissions"?
 
![Screen Shot 2022-06-13 at 7.08.54 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/9d069404-d1e5-495f-bd63-3773031c8548
)

**Comment by iman-jamali-fw** [comment]
I opened a PR to fix this issue.
https://github.com/bcgov/digital-journeys/pull/317

**Comment by HasanSifat** [comment]
@iman-jamali-fw Hi Iman! I tested this out one more time with a new user in test and they are not getting the "review submissions" button anymore. Moving this to QA again as this issue seems to have been solved. We'll do a final round of testing before closing this issue. 

Thanks for all the help! :)
