### ISSUE TITLE
Logging with another IDIR subsequently will prompt you with the error

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#306]
Logging with another IDIR subsequently will prompt you with the error (image attached below) and doesn't let you in.
Steps to reproduce:
1. login with an IDIR (let's call it idir1) => should work fine
2. Login with another IDIR (call it idir2) => show error "invalidFederatedIdentityActionMessage" and stop you from logging

Workaround: The error persists unless page cookies and cache are clear. This can be done through "clear site data" on chrome dev tools under the application tab.

The same thing happens if logging in with idir2 first, idir1 shows an error unless "clear site data" is clicked on chrome.

Affected environments: All

![Screen Shot 2022-05-31 at 2.04.59 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/333157d2-2164-4a2a-ad47-eb96387a2d4f)

**Comment by MeghanStothers** [comment]
@iman-jamali-fw - Is this ticket/bug still an issue or has this been resolved? If so, please close the ticket. Thanks!

**Comment by iman-jamali-fw** [comment]
@MeghanStothers This still exists.

**Comment by MeghanStothers** [comment]
For review after launch - low risk.
Suggest to send users to digital journeys team with instruction to clear cache

**Comment by simensma-fresh** [comment]
@MeghanStothers I believe this is an issue on the OCIO side, think there's not much we can do about this
