### ISSUE TITLE
TELEWORK: Dashboard Increase timer for green popup message box for submitters 

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#309]
When users have submitted a telework agreement, they are led to the Form's dashboard environment followed by a green popup message confirming their submission. There is a timer on the popup message after which the green popup message box disappears. The timer on this message box needs to be increased so that users are given more time to review the message. Screenshot below- 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/ed280f41-9dd7-4479-8746-229115b0dcea)

**Comment by MeghanStothers** [comment]
Not needed for launch

**Comment by alexandralloyd** [comment]
We will now have a confirmation page Ticket #327.
