### ISSUE TITLE
Bad Request After Session Timeout

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/digital-journeys#311]
If my session times-out, then I try to log back in, I get the following 400 Error - Bad Request:

![image.png](https://images.zenhubusercontent.com/5f6b6e00c344a38c20855fad/06d550f2-41a3-4300-9f5b-a4723044bbe0)

**Comment by MeghanStothers** [comment]
Currently we have a one hour timeout - we will re-open if needed
