### ISSUE TITLE
Telework Form: (usability) User instructions before Employee fills form 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#313]
As an employee who want to submit the Telework form for approval, I'd like to have the following information BEFORE I begin the form:
- information needed to complete the "costs" section
- the form will not save
- the status of their submitted form can be found on the dashboard?
- flex days? how to manage those requests
  

This ticket relates to other tickets about the usability of the form

To be estimated by Iman/TES Dev team

**Comment by Stella-Archer** [comment]
Duplicate ticket to documentation #342 and preamble #323
