### ISSUE TITLE
TOOL: Optimized for Mobile devices

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#314]
As an employee and/or supervisor, I would like to see the form is functional and boxes and text fields display properly and clearly.  

Please test for findings and fixes.

For SL review: it is recommended to fill out the form in a coputer. putting in icebox for review later.

**Comment by MeghanStothers** [comment]
For phase 2

**Comment by Abuchana** [comment]
On AOT's roadmap for Q4

**Comment by fazil-ey** [comment]
no plans of doing any mobile optimization right now for any of the forms. WIll likely be a part of AOT upgrade anyway
