### ISSUE TITLE
Show Scrollbar on Forms

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/digital-journeys#316]
There is currently no scrollbar shown on the forms.

To add one, use the following CSS rule:

.scrollable-page { scrollbar-width: thin; }

Or use scrollbar-width: auto; for a thicker (default) size.

**Comment by iman-jamali-fw** [comment]
@warrenchristian1telus I tested this, but it doesn't bring up the scroll bar. I remember we made other changes to have it show up. Do you remember what they were?

**Comment by DonMoffatt** [comment]
This came up in user testing for Telework as well.

**Comment by DonMoffatt** [comment]
I checked this and it appears fixed on the employee side. The supervisor sie was not an issue.

**Comment by DonMoffatt** [comment]
@warrenchristian1telus  I changed this to a 2 - was that ok as an estimate? I'd like to close it but we should have some points assigned first.

**Comment by warrenchristian1telus** [comment]
Thanks @DonMoffatt - I think 2 will easily cover it. Likely only a 1, but I'm not 100% sure about the implementation. @iman-jamali-fw can adjust if it's any more or less.

**Comment by DonMoffatt** [comment]
I will close it with a 2. Iman can change it if that's not right.

**Comment by DonMoffatt** [comment]
I will close it with a 2. Iman can change it if that's not right.

**Comment by MeghanStothers** [comment]
Not required for launch - but be fixed. Please/QA check to see if this is resolved

**Comment by DonMoffatt** [comment]
@alexandralloyd and I have Q/A'd the scroll bar and it meets requirements.
