### ISSUE TITLE
TELEWORK: Remove Menu Tabs for Manager

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#320]
**User Story**
As a manager (reviewer), I want to only see the menu tabs that are relevant to me so I don't confused or enter areas that which would constitute a privacy breach. 

**Tasks**

- [x]  Remove Forms, Applications, and Dashboards tabs from view for reviewers in the production and test environment

**Acceptance Criteria**

- [x] Inability to see  Forms, Applications, and Dashboards tabs from view when logged into the production and test environments as a reviewer

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/c6576c75-dc9d-4ddf-9545-59772467f303)

**Comment by MeghanStothers** [comment]
See #338 which is similar

**Comment by MeghanStothers** [comment]
Check if this a duplicate

**Comment by HasanSifat** [comment]
update to requirement to not remove "Forms tab"
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/272e0aab-3729-4254-8461-cf6cec335c9e)

**Comment by Stella-Archer** [comment]
Not seeing this in any environment
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/e54b84a2-2f2f-4699-9917-26c8df8b6251)
![image.png]
(https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/08973cbf-9b8e-499b-8671-5a599123ccf3
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/9c5d4fa1-4224-40fa-8679-39ae42d6c7a5))

**Comment by HasanSifat** [comment]
Tested successfully in TEST. Waiting on this change to be pushed to PROD and do a final review before closing ticket

**Comment by alexandralloyd** [comment]
Successfully tested in PROD with Lee-Ann and Josh.
