### ISSUE TITLE
TELEWORK: Left Hand Panel in Tasks Tab

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#331]
All tickets relate to the left-hand panel in the Tasks tab that supervisors/reviewers see when signing off on an application.![ManagerReviewSpace.jpg](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/5e231833-7fd4-4a94-9f19-b6e45eb4c066)

**Comment by HasanSifat** [comment]
tested as complete
