### ISSUE TITLE
TELEWORK: Remove "History" and "Diagram" from Tasks Tab

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#332]
**User Story**
As a supervisor/reviewer, I want to only see the tabs relevant to me within Tasks area so I can quickly and easily sign-off on applications without getting distracted or confused.

**Tasks**

- [x] Remove the "History" and "Diagram" tabs from view within the Tasks tab (see picture) for supervisors/reviews for all environments

**Acceptance Criteria**

- [x] Supervisor cannot see the "History" and "Diagram" when a form is selected to review in the Tasks tab in all environments![historydiagram.png](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/e6126828-6d34-43e1-b436-b9007861205b)

**Comment by MeghanStothers** [comment]
This ticket relates to having another requirement to have logic in place to differentiate between the roles (employee and manager)

**Comment by HasanSifat** [comment]
Tested successfully in TEST environment. Ready to be deployed to PROD

**Comment by Stella-Archer** [comment]
@HasanSifat  I notice this schedule thing in TEST -
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/1af0bc5c-8abf-4d1f-b69f-ef8a8879b0e4 Is that just because my designer role)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/bc0bf82b-2847-4e54-a0c7-902a21ec0ca8)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/7fc0de8f-655f-403f-817d-e093d5924f4d)

**Comment by HasanSifat** [comment]
Hi @Stella-Archer, this is the group assignee option that is being removed as part of ticket#333. This is what I pointed out to David in the morning. Once complete with 333, this option will not be available. the form tab is the only one going to be there. Previously we had history and diagram tab, those were removed as part of ticket#332

**Comment by Stella-Archer** [comment]
@HasanSifat  I see you've flagged this in #333, thanks you please disregard the above comments!

**Comment by HasanSifat** [comment]
Tested successfully in PROD. Closing ticket!
