### ISSUE TITLE
TELEWORK: Replace Logo with "Where Ideas Work" Branding

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#336]
**User Story**
As an employee, I want to see consistent branding on the website I'm using so I can be sure that the website is internally facing.

**Tasks**

- [ ] Replace the main British Columbia branding in the upper left side of the banner to be "Where Ideas Work" branding in all environments

**Acceptance Criteria**

- [ ] All users see "Where Ideas Work" branding on the top banner in all environments ![branding.png](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/77513704-0d93-45fb-9567-f45e7530f847)

**Comment by MeghanStothers** [comment]
Stella to connect with PIE/Matt Gardiner for correct logo

**Comment by Stella-Archer** [comment]
![BCPS_IDEAS_rgb_rev.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/90a18917-da1f-441b-b1db-a2bb2958c513)

**Comment by Stella-Archer** [comment]
This hasn't been done in any environments 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/377a8511-dd4a-414b-b2d8-c3c5304defdc)

**Comment by MeghanStothers** [comment]
Warren suggests a test in dev when ready
Iman has tested on local and it didn't break

**Comment by Stella-Archer** [comment]
please note there is some spacing padding info for logo placement in ticket #106

**Comment by HasanSifat** [comment]
Hi @david-sabadash I dont see any change in DEV or TEST with an updated "Where ideas work" branding. 

Test failed!

**Comment by simensma-fresh** [comment]
@HasanSifat This has now been deployed to dev/test

**Comment by HasanSifat** [comment]
Tested successfully in DEV & TEST

Ready to be transferred to PROD

**Comment by HasanSifat** [comment]
Tested successfully in PROD!
