### ISSUE TITLE
TELEWORK: Remove Menu Tabs for Employee

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#338]
**User Story**
As an employee (client), I want to only see the menu tabs that are relevant to me so I don't get confused or enter areas that would constitute a privacy breach. 

**Tasks**

- [x]  Remove Forms, Applications, tasks, and Dashboards tabs from view for clients in the production and test environment

**Acceptance Criteria**

- [x] Inability to see Forms, Applications, Dashboards, and Tasks tabs from view when logged into the production and test environments as a reviewer

**Comment by MeghanStothers** [comment]
Warren estimates that blocking "hiding" something from the interface would be fairly easy as a short-term solution.

**Comment by HasanSifat** [comment]
update to requirement to not remove "Forms" tab- 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/2d07301f-ef6c-4622-8b83-37ab46287c7f)

**Comment by iman-jamali-fw** [comment]
Are we keeping both Forms and Tasks for employee/client? Or only Forms?

**Comment by HasanSifat** [comment]
@iman-jamali-fw we are keeping forms tab and tasks tab for both clients and reviewers. The only difference between the 2 types of users will be that reviewers will have items in the tasks tab for them to review, clients will have no items to review.

**Comment by HasanSifat** [comment]
Hi @iman-jamali-fw. After discussing with the team, we have decided to go ahead and remove the forms tab for both Clients and Reviewers. 

Clients will only be able to come to formsflow using the direct link to the form. No tabs in the formsflow tool will be available to them. After clicking submit, the clients will be taken to a confirmation window/page (this can be in cms lite/myhr as a redirect)

For reviewers, only the tasks tab will be available for them to come into formsflow and approve/deny an application that was specifically assigned to them.

Aplogies for the back and forth on this.

**Comment by Stella-Archer** [comment]
not seeing this in any environment
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/a0b7aff0-9a57-438b-99fc-3f7d33e9aaf0)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/2cf65bb6-dedd-4480-a916-b93d4b73c2a4)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/ad279505-0bf2-4a6c-8e3b-d5a914be0c0c)

**Comment by david-sabadash** [comment]
Currently the base redirect when logging in is to the /form page for Clients. are we wanting to change this in addition to hiding the tab?

**Comment by HasanSifat** [comment]
Hi @david-sabadash 
Our understanding of the business requirements is that users after submitting a form will be redirected to a confirmation page, either within formsflow or a redirect to a page in CMS Lite. 

New users coming into Formsflow to make a submission will not have the link to the forms tab, instead only the direct link to the Telework Agreement form will be available to them to sign in and complete their submission. 

Hope this helps!

**Comment by david-sabadash** [comment]
@HasanSifat Ok! thanks Hasan, that makes sense. To clarify though, what I mean is currently Client roles will be put on the /form page after logging in despite having no Form tab access. This should probably be changed, should it not?

**Comment by HasanSifat** [comment]
@david-sabadash well that depends on which link the users are taking to come into formsflow. The only link that will be available to them will be a direct link to the Telework form through the BC Gov website. So I don't see how users will be directed to the forms tab after signing in if they don't have the link to it in the first place.

**Comment by alexandralloyd** [comment]
Tested in PROD, working.
