### ISSUE TITLE
TELEWORK: Remove Back Button on the Top of Form

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#351]
**User Story**
As an employee, I want the back button at the top of the telework form removed so I don't get confused and go into the wrong page.  

**Tasks**

- [x] Remove the back button on the top of the telework form for employees/clients in all environments (see picture below)

**Acceptance Criteria**

- [x] Back button is hidden from view for employees in all environments

![backbutton.png](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/1079f132-c48e-4d1c-b20d-c4133080d0cf)

**Comment by Stella-Archer** [comment]
Test with Roles

**Comment by Stella-Archer** [comment]
Not happening in PROD
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/fedc19b5-9500-4154-b1bc-18b83c2c005f)

**Comment by Stella-Archer** [comment]
Is working in DEV :)
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/3d1c2066-b24a-4cdf-add2-6c21c1fa28d6)

**Comment by Stella-Archer** [comment]
Could we pish this change to tst?

**Comment by HasanSifat** [comment]
tested successfully in TEST. waiting to push this change to PROD and do a final round of testing before closing this ticket.

**Comment by alexandralloyd** [comment]
Tested in PROD, works.
