### ISSUE TITLE
Add Dependabot Version Updates

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/digital-journeys#366]
To add/enable Dependabot version updates to code, we will need to create the config file:

https://github.com/bcgov/digital-journeys/network/updates

**Comment by warrenchristian1telus** [comment]
This is to remediate the following scanned issues (Alerts): https://github.com/bcgov/digital-journeys/security/dependabot

**Comment by MeghanStothers** [comment]
@warrenchristian1telus - Hello and welcome back - I see we wanted to wait on this one post-launch. Is there an update on this ticket? I'm thinking we'll roll this ticket into our work with Senior Leaders team.

**Comment by warrenchristian1telus** [comment]
@MeghanStothers We have a meeting this afternoon to discuss the upgrade path. Just a note that we seem to have 4 active issues around updates: #271, #366, #487, #488
