### ISSUE TITLE
The user is not displayed with any errors if he does not fill out the required form fields

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#38]
**Background:** The user is not displayed with any errors if he does not fill out the required form fields.

**Steps to Reproduce:**

1. Log in to the PSA-Digital-Journey portal on dev with valid credentials.
2. Fill out a form that has required fields such as "Telework Agreement Qud". Do not fill in the required fields.
3. Click on "Submit".

**Actual Behavior:** The user is not displayed with any errors if he does not fill out the required form fields and can not submit the form.

**Expected Behavior:** The user should be displayed with an error message stating to fill in the required fields before submitting.

**Comment by simensma-fresh** [comment]
@qudsia-khan-fw I had a look at the form, and none of the fields are checked off as "Required" (Validation tab). If you do, you're not able to submit the form until the required fields are filled in

**Comment by schuyt** [comment]
@simensma-fresh When there are required fields present, does a validation message appear?

**Comment by simensma-fresh** [comment]
On that note, I think there's a story here to add validation to the Telework form.
- Making all required fields required
- Validation of email addresses
- Adding max lengths to all fields
... Any other appropriate ones

**Comment by schuyt** [comment]
Awesome. I think we can close this then.
