### ISSUE TITLE
Remove Deployment Trigger Type: ImageChange

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/digital-journeys#390]
Please remove the Type: ImageChange from the DeploymentConfigs, so that changes deployed to one namespace (/tools) do not trigger updates in the others.

This is to temporarily resolve the deployment issues while we work toward the permanent tagged image fix in #282.

Note that the deployed changes will still be susceptible to cluster-wide upgrades and pod cycling, as they will still share base images in tools namespace until #282 is implemented.

**Comment by kkapoor-fresh** [comment]
Pull request https://github.com/bcgov/digital-journeys/pull/391 created for this fix.

**Comment by kkapoor-fresh** [comment]
The fix has been deployed to DEV, TEST and PROD. @warrenchristian1telus I saw a few workflow actions running after this fix, so I am assuming this looks good but please confirm at your end once.  @freshjwarren

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus @Abuchana I guess this ticket is good to close.

**Comment by warrenchristian1telus** [comment]
Hi @kkapoor-fresh I found an ImageChange trigger on the first DC I checked in prod. Can you please review the deployments and make sure they have all been removed?

![image](https://user-images.githubusercontent.com/70002196/180025605-0dcb407c-6537-48c8-b500-b8ad01821a1d.png)

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus The image triggers have been removed from the web, api and camunda services as these are the only services actively build and deployed by the pipeline currently. These automatic deployments are running fine after removing the image triggers as the refresh of environments done via code updates is not refreshing all the environments but only one which is relevant. To tackel deployment refresh issue during cluster upgrades, #282 should be good enough.
