### ISSUE TITLE
Ability for Supervisor to approve forms

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#40]
_As a supervisor/manager, I would like to be able to approve forms after they've been submitted_

**A/C**
- Supervisor section of the form is only editable if you are the supervisor
- Supervisor can see the entire form
- Supervisor can authenticate with IDIR
- Supervisor can load submitted form
- Supervisor can add their info and signature
- Supervisor can add **comments**
- Hide ADM approval section if num days working remote < 3days

**Notes:**
- Can remove "Upload the Telework Agreement sent by your employee" and Employee "First Name / Last Name" from the digital form.

**Comment by qudsia-khan-fw** [comment]
Supervisor will be assigned a task which is created upon form submission
This should also work for supervisors who have not logged in to the system yet. The task should be displayed after first log in.

**Comment by qudsia-khan-fw** [comment]
@matbusby-fw 
Please address the following:
1. After approving or rejecting the application, the diagram highlight does not get updated.
![diagramWorkflow.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/cfdf4dbd-5916-4bc2-82c2-58aa5f3f5ce8)
2. There is no section for the supervisor to add comments

**Comment by simensma-fresh** [comment]
4. This would be expected, seeing as the manager will have the same client role as the form submittor. Or do you mean if you specify the same employee and manager email?
5. Think the search feature might only return results for the users of the group that's assigned to the form and if you're part of that group. So this would expected behaviour for the Telework form where the task is not assigned to a group

**Comment by qudsia-khan-fw** [comment]
4. Yes same employee and manager email, or employee email in the manager email field.
5. Ok thanks.

**Comment by simensma-fresh** [comment]
Re. 1. and 4. Can we add these as requirements for the Validation ticket? Think it would be best done together with the rest of the validation

**Comment by qudsia-khan-fw** [comment]
Added 1 and 4 to validation ticket #85. Thanks
