### ISSUE TITLE
TELEWORK BUG: No Peoplesoft info in the form in PROD 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#405]
Background: As an employee, I am do not have the Telework form auto-populated with Peoplesoft information in the prod environment
 
Steps to Reproduce: Login to the form using the prod link.
 
Actual Behavior: Form fields are blank
 
Expected Behaviour: Form fields should be complete
 
Environment: PROD

**Comment by T854236** [comment]
@warrenchristian1telus  looks like Digital Journey PROD is hitting DEV API URL.

**Comment by T854236** [comment]
@warrenchristian1telus for clarity to my comment.  I don't see any hits to API PROD server from telework this morning.

**Comment by warrenchristian1telus** [comment]
@MeghanStothers I think there is an issue with the TOKEN for prod CDATA in our config. Investigating.

As the original issue for this is still open, I think we can likely close this one and complete the work / validation through that to avoid duplication:

https://github.com/bcgov/digital-journeys/issues/289

**Comment by MeghanStothers** [comment]
Duplicate ticket so will close this one - see  #289
