### ISSUE TITLE
TELEWORK: Deleting Completed Submissions

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#416]
**User Story**
As an employee, I want to make sure my submission is deleted from formsflow upon completion so I know my privacy is protected.

Relates to ticket #339 and ticket #417

**Tasks**

- [ ] Once the submission is actioned by a supervisor (either approved or denied), the submission should be automatically deleted from the formsflow.ai system. This deletion would be the last step in the workflow process

**Acceptance Criteria**

- [ ] Above task is completed in all environments

**Comment by Abuchana** [comment]
Iman working on implementing a listener to manage this function

**Comment by MeghanStothers** [comment]
Iman working to delete from one of three areas. This work needs to have an end point to API

**Comment by iman-jamali-fw** [comment]
Tested again on DEV, both submission and application delete successfully after completion. Ready to close.

**Comment by HasanSifat** [comment]
Confirmed with @iman-jamali-fw that issue has been solved and tested.

Ready to be closed
