### ISSUE TITLE
TELEWORK: Delete Incomplete Submissions After 30 Calendar Days 

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#417]
**User Story**
As an employee, I want my telework submission to be deleted from formsflow.ai after 30 calendars if my supervisor doesn't approve it within that timeframe, so my privacy is protected. 

Relates to ticket #339 and ticket #416.

**Tasks**
- [x] If a submission is not actioned by a supervisor (either approved or denied) within 30 calendar days, the submission should be automatically deleted from the formsflow.ai system

**Acceptance Criteria**

- [x] Above task is completed in all environment

**Comment by iman-jamali-fw** [comment]
I tested this on DEV and incompleted submissions were deleted after one day. 
The two applications below are incomplete and were deleted after two days.
![Screen Shot 2022-07-27 at 2.41.34 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/91928d4a-6374-4148-b9fa-603fbead84b7)

**Comment by iman-jamali-fw** [comment]
Created two incompleted submissions. They should be deleted tomorrow at the same time. Will update the ticket once it hit a one-day duration.

![Screen Shot 2022-07-28 at 10.11.00 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/c7eb68c8-4a80-4051-844b-8093d78181a3)

**Comment by iman-jamali-fw** [comment]
Both in-completed applications were successfully deleted:
https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/application/6134
https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/application/6135

@HasanSifat Ready to be closed :)
