### ISSUE TITLE
TELEWORK/APP DEV: Remove "+" and rename pending tasks sort function

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#424]
**User Story**
As a user, I want the "Sort by" functions in the "Review and Process Applications" tab to be more user-friendly so that I know definitively that this feature is a sorting function. 

**Tasks**

- [x] Remove the "+" sign as it adds more confusion to the interface
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/a73f5768-9c48-4a81-a00f-75dbb15186fa)

- [x] Rename "created" label to "Sort by"
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/6ec54eb4-f3bd-4321-a5d0-fea869b11cdd)

**Acceptance Criteria**
Once the "+" feature is removed and the "Created" label name is changed to "Sort by".

**Comment by david-sabadash** [comment]
@MeghanStothers @HasanSifat 

just a question about the renaming of the 'Created' label- currently this is one of the sorting options, not a label. it changes based on which sorting option is chosen, such as priority, assignee, etc. are you wanting this changed to be a static label of 'Sort By' if that is done, there won't be a way to see what the currently selected sort parameter is

also, is this CSS issue happening for anyone else or just me? it only occurs when I hover over the popup box
![image.png](https://images.zenhubusercontent.com/62b33d00d955ad0dc2151a98/6a0192a0-e06c-456e-889b-2dab605e3896)

**Comment by MeghanStothers** [comment]
I think the goal of this ticket is to hide or remove this feature ofr launch rather than re-name. Is that correct @HasanSifat ?

**Comment by david-sabadash** [comment]
to specify; even if we rename, the default sort will still be 'Created date'

**Comment by HasanSifat** [comment]
Hi @david-sabadash! I just had a discussion with Meghan and Stella, and we have decided to take out the option altogether(both sort function and the + sign). There won't be any need to rename the label/sort function. We want to take out the option altogether and have submissions sorted by creation date as a default. 

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/d3b67515-02f7-491d-8eb3-d3ce5eb39b51)

**Comment by david-sabadash** [comment]
ok perfect, thanks!

**Comment by HasanSifat** [comment]
Tested successfully in TEST! 

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/a2ca176e-eb2b-4c18-923a-6d54ebc469b7)

Ready to be transferred to PROD!

**Comment by HasanSifat** [comment]
Tested successfully in PROD 

Ready to be closed
