### ISSUE TITLE
Automated backup of Postgres (for Keycloak)

### ISSUE THREAD

**Issue by will-freshworks** [bcgov/digital-journeys#430]

**Comment by Abuchana** [comment]
@will-freshworks, Hi Will, can you please confirm this should be a task for the Digital Journeys team as it seems out of context? Thank you!

**Comment by will-freshworks** [comment]
Hi @Abuchana. This is part of the DevOps task list for this project. We needed to get backups of the database for Keycloak automated in case the postgres cluster suffered data loss (very unlikely but better safe than sorry). I actually think @kushal-arora-fw has already finished this task - I will check in with him at our next DevOps stand-up tomorrow morning (PT).

**Comment by kushal-arora-fw** [comment]
That is right, this can be marked done @will-freshworks. Patroni backups are up and running. 

My troubles with Zenhub didn't allow me to change ticket status.

**Comment by Abuchana** [comment]
Thank you! Closed.
