### ISSUE TITLE
[DUPLICATE TICKET] [TELEWORK/SERVER SIDE PDF]: Filled out manager's section integrated as attachment with final confirmation email

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#442]
**User Story**
As an employee and manager, I want to have the manager's section of the telework agreement visible and filled out once a final decision has been made by the manager. This way I will have an artifact to save and refer to later on

**Tasks**

- [ ] Manager's section visible and filled out after decision submitted by Manager

**Acceptance Criteria**
this ticket can be defined complete when the final confirmation email has an attachment with the manager's section visible and filled out.

**Comment by MeghanStothers** [comment]
See #367 as this is a similar ticket
