### ISSUE TITLE
BUG: Telework ADM Attachment

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#448]
As a supervisor wanting to approve an employee's request for 3 or more days, I am unable to attach proof of ADM approval.   

I tested are was not successful in uploading a jpeg file nor a .msg file

Closing this ticket will happen with 
- successful upload of all file format allowed
- having the file format as an attachment to the supervisors confirmation email

**Comment by MeghanStothers** [comment]
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/2fe4e5cb-a377-49b7-827c-710dcf1a6ab4)

**Comment by MeghanStothers** [comment]
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/a57cdf22-bdde-46ed-a74f-ea0af19ba106)

**Comment by simensma-fresh** [comment]
@Stella-Archer A fix for this has now been deployed to test

**Comment by HasanSifat** [comment]
Tested successfully in TEST! attachments are uploading successfully
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/46759d11-29a7-4f95-aa8f-ed6e26beaa6e)

**Comment by Stella-Archer** [comment]
fixed! upload worked just fine in test
