### ISSUE TITLE
The user is not displayed with a warning pop-up when navigating back from the edit and submit form screen

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#46]
**Background:** The user is not displayed with a warning pop-up when navigating back from the edit and submit form screen.

**Steps to Reproduce:**
1. Log in to the PSA-Digital-Journey portal on dev as an admin or designer with valid credentials.
2. Click on "View/Edit" form.
3. Make some changes. Do not click on "Save Form".
4. Click on the blue back arrow on the top left of the edit screen.
5. Log in to the PSA-Digital-Journey portal on dev as a non-admin or designer with valid credentials.
6. Click on "Submit New".
7. Fill in some fields.
8. Click on the blue back arrow on the top left of the form.

**Actual Behavior:** The user is not displayed with a warning pop-up when navigating back from the edit screen.

**Expected Behavior:** The user should be displayed with a warning pop-up when navigating back from the edit screen: "If you go back now, all unsaved information you have entered will be lost. Are you sure you want to exit this page?" with a Cancel and Continue button.

**Comment by jchow11** [comment]
![Exit Page Modal.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/3d3d8dc3-6241-48c4-b8a3-77f76f72b8c7)
