### ISSUE TITLE
Log out flashes task page

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#463]
Background: In TEST when I,  as a user logo out, the task page flashes for a fraction of a second before log out is complete
 
Steps to Reproduce: go to the telework in TEST
hit log out button
 
Actual Behavior:  task page flashes for a fraction of a second before log out is complete
 
Expected Behaviour: logo would be direct and complete form the forms page
 
Environment: TESThttps://images.zenhubusercontent.com/439477060/e853ab23-94d7-4c9c-9649-169a129d8c31/logouttaskflash.mp4

**Comment by Stella-Archer** [comment]
![1EDC0AA5-9470-4DC7-A810-B92DE162DF4A.GIF](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/7774aefe-8ad6-4cd7-9b25-f53aa1c08932)

**Comment by warrenchristian1telus** [comment]
Just a note on this - I think the main issue is that if you immediately log back in, you end up on the tasks page (rather than just a flash of it).

**Comment by Stella-Archer** [comment]
yes ok I've got that to reproduce, wierd yeah, your correct @warrenchristian1telus the UX should be the user returning to where they where last, I will try to document the logging back in immediately experience

**Comment by Stella-Archer** [comment]
[Uploading... 2A33EE12-0D19-4A7D-92F1-26155B78CD8A.GIF]

**Comment by warrenchristian1telus** [comment]
It seems the task page is the default "Home" page. I think this is why it's going there. Not only on log out, but also if you just go to the site root at https://digital-journeys.apps.silver.devops.gov.bc.ca.

**Comment by Stella-Archer** [comment]
when a 'regular user goes to the form in PROD they do not see the admin tab YAY
when the log back in after signing out they are directed to the /task tab - boo 
.....But they don't see any tasks as they have not been assigned any, so not a security issue but it should be cleaned up for improved user experience and when they log back in they should be returned to the place where they logged out form
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/5ccf509d-c8eb-4671-996d-75162c7e990d)

**Comment by MeghanStothers** [comment]
Bug depends on which type of role you have.
Next steps: check with Warren to see if this ticket has some implications

**Comment by warrenchristian1telus** [comment]
@MeghanStothers I don't think the bug depends on the role, but just redirects to "/task" when the Sign Out button is clicked. My assumption is that this is due to "/task" being set as the home / main page. Maybe @simensma-fresh or @iman-jamali-fw can confirm? I'm wondering if we can just remove the URL change on Sign Out...or edit the default home page to make it more appropriate for form submitters?

**Comment by HasanSifat** [comment]
The user to be routed back to the sign in page after clicking on sign out button. 
After logging back in again, where would users be routed back to? One possible location would be the last form the users left from.

**Comment by fazil-ey** [comment]
no longer an issue, did not observe in test
