### ISSUE TITLE
TELEWORK: Confirmation page edits 

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/digital-journeys#470]
Can you please make the following changes to the employee confirmation page? (see attached image for examples)

i)	Remove period after "decision" in second bullet point
ii)	Files not file (second bullet point)
iii)     Second bullet point should be divided into two separate bullets (so one bullet for each sentence)
iiii)	add period to last bullet

![image.png](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/4a4cfe41-3acb-460a-ae53-dfa926c7e3b8)

**Comment by david-sabadash** [comment]
Updated as per the ticket description. also caught issue IV on the 'approval' version of the page
![image.png](https://images.zenhubusercontent.com/62b33d00d955ad0dc2151a98/d078b187-65d8-4b05-920a-662036eb82ee)

**Comment by alexandralloyd** [comment]
@david-sabadash Changes not present in any environment (screenshot from DEV). Moving back to in progress
![TEst.PNG](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/dc8db039-0fe0-45e5-a9a1-b543c2aaf402)

**Comment by david-sabadash** [comment]
Apologies, i forgot about the split deployments update we made at the end of last week. deployed it to DEV but not test. pushing right now and will move the tickets once it's done

**Comment by alexandralloyd** [comment]
@david-sabadash Thanks, let me know when it's ready for test. Also, could you change 'personal' to 'personnel' please?

**Comment by HasanSifat** [comment]
Hi @david-sabadash, Still don't see any of these changes in DEV/TEST

**Comment by simensma-fresh** [comment]
@HasanSifat I've confirmed that the changes are in dev/test. You might have to do a hard refresh of the page to make sure you're not viewing a cached version

**Comment by HasanSifat** [comment]
Tested successfully in TEST & DEV

Ready to be transferred to PROD

**Comment by HasanSifat** [comment]
Tested successfully in PROD
