### ISSUE TITLE
Telework: Devs to confirm production link for users to access Telework form at launch

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#474]
As a user, I will need access (link) to the Telework form.

Simen, can you please confirm this is the correct link we can use and sent to the communications team: 

https://digital-journeys.apps.silver.devops.gov.bc.ca/form/62c8796e532635532114a70b

**Comment by simensma-fresh** [comment]
@MeghanStothers Can confirm it is indeed the correct link

**Comment by MeghanStothers** [comment]
@Simen - thanks - I have shared the link with the communications team and ours
