### ISSUE TITLE
Telework: Post-launch wording changes in emails and confirmation messages

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#479]
**User Story**
“As form owner (Policy), I would like to change all instances of the work "rejected" to "denied" where they appear in the confirmation messages, pdf name, email messages and html content/resources.

This work can be carried out post-launch as it is not a priority and should be bundled with all changes.

Please add any changes here to be carried out as possible

**Tasks**
1) find instances where the wording needed changing
2) make he changes
3) test
4) advise client change has been completed

**Acceptance Criteria**
client gets notified of each change made

**Comment by MeghanStothers** [comment]
Meghan to connect with Lee-Ann

**Comment by MeghanStothers** [comment]
@MeghanStothers please assign to writing team to find instances

**Comment by MissionT** [comment]
This is to confirm 3 instances of the word “Rejected” were found. 
Please change the word “Rejected” to Denied in the following areas:
1.	Drop-Down Form Field: The value stored in the Decision field located at the bottom of the form.
2.	The supervisor’s response notification email: 
Subject Line – is fine – “…. Has been denied..”
However, the name of PDF attachment  has “_Rejected” and the body of this email with the attachment has the word rejected in the first sentence.

Please see the attachment for screen shots. 
Thank you, Chris [https://app.zenhub.com/files/439477060/63c5df21-ff98-4ebc-aa8a-5950245b42db/download](https://app.zenhub.com/files/439477060/63c5df21-ff98-4ebc-aa8a-5950245b42db/download)

**Comment by HasanSifat** [comment]
Tested in Dev- Successful 
test in Test was not successful 
No test in Prod or deployment was carried out/made

**Comment by DonMoffatt** [comment]
@simensma-fresh Would you please look at the issue for the supervisor after submitting the denial in TEST? The screen refreshes and the supervisor stays in the task area. As noted by Hasan, it is working in DEV.

**Comment by iman-jamali-fw** [comment]
@DonMoffatt @HasanSifat 
It is fixed and working on TEST. There was a small issue with the `Denial` value on the form. The value was `Rejected` but the new workflow expected `Denial`, I changed that and it is working.

Please note that if you already have already signoff forms that are stuck in the task because of the issue above, you'll probably see three options in the `Decisoin` dropdown. This won't be the case for the new or old but not yet signed forms, shouldn't be a problem for clients on PROD if we change this in midnight :)

**Comment by DonMoffatt** [comment]
Thanks @iman-jamali-fw Would you please email me a copy of this updated workflow? Thanks.

**Comment by DonMoffatt** [comment]
The table side of this is referred to in ticket #540
