### ISSUE TITLE
Telework: PDF email attachment - date field is blank 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#483]
As a user employee filling and submitting the Telework form, I enter the date in the form, but when I open the emailed pdf attachment, the date isn't showing in the date field.

**Comment by HasanSifat** [comment]
Simen getting this fix into DEV today (8th august)

**Comment by HasanSifat** [comment]
A pre-populated field will need to be NOT DISABLED!

**Comment by simensma-fresh** [comment]
@HasanSifat I think we can close this one, I don't think there's much else to do here
