### ISSUE TITLE
TOOL: List of ministry names in forms as a custom component for forms designer

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#484]
**ticket needs a re-write**
currently the only working end point is for the ministry names 
needs more work on back-end to introduce different end points
ticket #361 is related to a similar kind of feature 

As a form-filler, I want access to a current drop-down list of the correct names of all BC gov't ministries. 

Acceptance Criteria:

- [x] A pre-populated field. 

- [x] An editable filtered drop-down field where users can select from a list of options. Users won't be able to input any new data, not in the list. Only type in their options to select an option from the list. 

- [x] The drop-down field needs to be pre-populated using the endpoints from BI (see Patrick's comment) 

- [x] A customized field option for forms designer to drag and drop this field into different forms.

**Comment by MeghanStothers** [comment]
Hasan and Don were able to manually add new ministry and adjust the name of another one, based on feedback we got from a user as follows: 
"Under the ‘ministry’ drop down menu, it currently gives an option for Forests, Lands, Natural Resource Operations and Rural Development. This ministry was reorganized in April 2022 and is now two separate ministries: the Ministry of Forests, and the Ministry of Land, Water and Resource Stewardship."

**Comment by MeghanStothers** [comment]
Hasan and Don were able to manually add new ministry and adjust the name of another one, based on feedback we got from a user as follows: 
"Under the ‘ministry’ drop down menu, it currently gives an option for Forests, Lands, Natural Resource Operations and Rural Development. This ministry was reorganized in April 2022 and is now two separate ministries: the Ministry of Forests, and the Ministry of Land, Water and Resource Stewardship."

**Comment by HasanSifat** [comment]
Two regularly updated list of ministry names- 
1. https://timepay.gov.bc.ca/ps_help/index.php?title=Ministry_Listing
2. https://timepay.gov.bc.ca/ps_help/index.php?title=Ministry/Business_Unit_List

**Comment by MeghanStothers** [comment]
Let's consult with Simen if we can dynamically update the drop-down menu in the tool/platform using the links above. 

See ticket #432  with Simen's comment:

"It would indeed be possible to pull this from the ODS if such endpoints exist. The Form builder does support fetching dropdown options dynamically, so with and endpoint added to our API to proxy the call through (for auth) this should work fine.

A reusable "ministry selection" dropdown would also be possible to add to the Form Builder in case a similar dropdown will be needed in future forms."

**Comment by HasanSifat** [comment]
Match the domain names with the list of organizations. Possible solution to combine list from multiple sources. BI table of Ministry names are pulled from Peoplesoft. Patrick confirmed that the BI list is regularly updated.

**Comment by T854236** [comment]
Please review endpoint https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_meta_dept_org_levels/

**Comment by HasanSifat** [comment]
Iman consulting with Simen to start work on this one

**Comment by HasanSifat** [comment]
A possible filtered list where users can type in an option from a list of preselected options

**Comment by iman-jamali-fw** [comment]
We have a way forward to implement this feature.

I'll working on the `webapi` to add an endpoint fething ministry names. @MeghanStothers and @T854236 to help me figure out which fields in the ODS endpoints to extract.

On the TOOL (frontend web), we'll extend a new Formio component based on [`Select` component](https://github.com/formio/formio.js/blob/9aab5c421a023e4280de897a01cd92393c62d745/src/components/select/Select.js). @bhumin-fw can work on that extending component which fetches the ministry names from an endpoint in `webapi`.

**Comment by T854236** [comment]
It will depend on what you are looking to show.  The [Datamart_Telework_meta_dept_org_levels/](https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_meta_dept_org_levels/) is a hierarchy.

**Comment by DonMoffatt** [comment]
@iman-jamali-fw I am checking with the BI group at the BCPSA to see if they can limit the incoming list to Public Service Act groups.

**Comment by MeghanStothers** [comment]
Don got a spreadsheet that is missing some groups (and not full names). List is not complete and we would like it to be automatically updated when there are new ministry names. 
Iman got access to endpoint with thousands of names and difference. values.

Iman to work with Don to ask about best way to get a specific list.

**Comment by MeghanStothers** [comment]
At Aleesa's suggestion, I reached out to Nina Moore and Virnia who are working on an ABC project and might have access to a recent source of ministries and ABCs. See Stella for details as I looped her into my request and situation:  "As an interim step, we have been manually adding ministry/ABC names and domains into our Telework form. We are looking for a more sustainable and accurate way to access this type of information (ideally in from an online source rather than from a spreadsheet)."

**Comment by iman-jamali-fw** [comment]
Per discussion with @DonMoffatt , we identified [the closest endpoint](https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_peoplesoft_bus_unit_tbl_hr/) that returns ministry names. However, the endpoint can improve the list's accuracy.

Regarding the implementation, the backend endpoint to the ODS endpoint for extracting the names is complete.
We'll see if @bhumin-fw or I will work on the front-end side (the drop-down).

**Comment by DonMoffatt** [comment]
I received the spreadsheets from Nina via Stella and found there are also issues with their list, such as including the Ministry of Housing, which has been rolled under AG. I updated Steven Jones today (Monday). I am creating a comparison of sources to highlight all issues.

**Comment by iman-jamali-fw** [comment]
@Stella-Archer Ready for test on DEV.

For testing, you can find two new form components `Remote Select` and `Ministry Select`.
- `Ministry Select`: Just drag and drop it in a form and click save. No configuration is needed, it should work out of the box and load all the ministry names from ODS.
- `Remote Select`: This is a more generic component that can fetch items from DGJ backend endpoints. At this point you can test it out with ministry names endpoint. First, drag and drop it on the form. Then under `Data` tab and in the `Data Source URL` enter an endpoint and click save. At this point, you can enter `/ministry-names` to load from our backend.

![Screen Shot 2022-08-19 at 11.56.00 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/7441f410-7f5c-4e3c-bae3-8f9e4af48557)

![Screen Shot 2022-08-19 at 11.57.09 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/36231c0e-90cb-4593-8955-c812dbc5f572)
![Screen Shot 2022-08-19 at 11.56.52 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/8bab4749-fd87-4a68-8159-24441c45d5ff)

**Comment by HasanSifat** [comment]
Tested in Dev as a form component. I placed the "Ministry Select" form component in one of the forms. The data is pre-populated and did not require the form designer to custom put in all the options within the field. 

Ready to be transferred to TEST

**Comment by Stella-Archer** [comment]
Closing and opening up test tix

**Comment by DonMoffatt** [comment]
See ticket #540
