### ISSUE TITLE
Welcome to the team

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#485]
Welcome!

**Comment by MeghanStothers** [comment]
I can see Bhumina, and I cannot find fazil-ey

**Comment by Abuchana** [comment]
I was able to add him, it might have been a timing thing.

**Comment by Abuchana** [comment]
This makes me think... we should have an onboarding Epic and create issues for each new person with a checklist of actions required...

**Comment by MeghanStothers** [comment]
Hey @ccoldwell I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
