### ISSUE TITLE
Update to current version of formsflow.ai

### ISSUE THREAD

**Issue by Abuchana** [bcgov/digital-journeys#487]
this is going to be an ongoing epic to ensure the latest version of formsflow is maintained for the Digi Jrny platform 

This epic is a place to host a checklist for updating to the latest version of formsflow- 

**In progress**
1. run vulnerabilities check (we need to decide which platform/application to use- Red Hat vs Snyk) 
2. carry out end to end test of all live forms 
and rest TBD

**Comment by fazil-ey** [comment]
all issues completed, new upgrade in progress, this epic is not being used
