### ISSUE TITLE
TELEWORK: Access to dashboard for stats on submissions

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#496]
**User Story**
As a business analyst in the program team, I want to see live stats on in progress and complete submissions within the digital journeys platform so I can get create reports and send these stats to executives for various decision making. 

**Tasks**

- [x] Provide access to the program team in PSA to these stats/dashboard

**Acceptance Criteria**
- [x] This ticket will be defined as complete when the program team has access to submission stats which Simen had referred to on 8th August scrum

**Comment by HasanSifat** [comment]
Possible dashboards to explore- Redash and Camunda Admin. Don is an admin on the Camunda side from PSA.

**Comment by MeghanStothers** [comment]
Don is able to pull the those numbers.

Simen Might make a simple dashboard in re-dash

**Comment by DonMoffatt** [comment]
There are still issues in interpreting the Camunda dashboard. I've asked @simensma-fresh about it via email.  There are multiple instances that say "Telework Agreement", each with a total. I do not know if I need to pick on (the largest) or add them all together, or a subset.

![image](https://user-images.githubusercontent.com/97757401/184253167-0ca534e0-4c56-4b27-bdb5-a582dd80c140.png)

**Comment by DonMoffatt** [comment]
Note: @simensma-fresh responded by email to say it is the aggregate of these.
