### ISSUE TITLE
SL Review: Providing access to nominated Band 4 leaders

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#522]
We intend to allow a small set of nominated Band 4 employees to go through the SL review process. 

Questions -
1. If provided a custom list of nominated Band 4 employees, can we ensure that only they are able to access and submit the form. 
    - Can we do this using Key Cloak? 
    - How big can this list be? 
2. Can we make this list dynamic? Can we add or remove employees after the SL review process has started?
    - If so, how will we handle a case if someone has filled the form, or even submitted the form, but their access is removed midway?

**Comment by HasanSifat** [comment]
Waiting on decision from SL Review team to be part of MVP for November launch.

**Comment by T854236** [comment]
There is an exposed API endpoint that lists all employee demographic information.  To get band 4, it is in the job description.  Please filter against the attribute jobcode_desc with "Band 4".

**Comment by iman-jamali-fw** [comment]
@T854236 Can please help me find that API endpoint that lists all employee demographic info?

**Comment by T854236** [comment]
@iman-jamali-fw https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_employee_demo/

**Comment by MeghanStothers** [comment]
Jodi waiting for this decision

**Comment by T854236** [comment]
A few questions as we review some use cases:

- In some cases we see multiple DMs, which one should be returned first?
- Some leader positions may be vacant and there's no ability to get the top tier information when hierarchy is broken.  Is it acceptable that it remains blank?

**Comment by MeghanStothers** [comment]
Not relevant anymore to SL
