### ISSUE TITLE
TOOL: "Metrics" dashboard inside the tool

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#525]
All tickets related to the "Metrics" Dashboard will go in this epic

**Comment by Stella-Archer** [comment]
Dashboard prototype: https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/insights

Metrics: https://digital-journeys.apps.silver.devops.gov.bc.ca/metrics
Digital Journeys
forms-flow-web

**Comment by fazil-ey** [comment]
#1212 covers this. dont need this epic
