### ISSUE TITLE
Maternity form initial submission email workflow

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#53]
As a BC Gov Employee filling out the maternity form I would like the form to be submitted to my supervisor for approval on submission so that I don't have to manually submit a copy

**A/C**
- Maternity form is created/exists
- Form auto-populates if user is authenticated with IDIR
- On any submission of the form a copy is sent to the employee and their supervisor
- Supervisor can come back and update any of the dates (they need to update at least the child's birthdate)
- Supervisor can update the dates after submission, but the employee cannot

### **Process**

**On formsflow:**

- On submission of the form a copy is sent to my supervisor to sign/approve
- Supervisor approves the form initially, then holds the form until the child is born, gets proof of child's birthdate / adoption
- Supervisor can come back and update any of the dates (they need to update at least the child's birthdate)

**Offline:**

- The supervisor gets a copy of proof of birth
- The supervisor gets a copy of the federal EI claim
- Supervisor submits an AskMyHR request manually (can we automate this?)

**Comment by qudsia-khan-fw** [comment]
@iman-jamali-fw 
The manager does not receive an e-mail upon form submission and it does not appear in his task list to approve or reject the application.

**Comment by qudsia-khan-fw** [comment]
1. For maternity option:
Currently, a pdf is generated on form submission. We see the updated dates section. PDF should not be generated and updated dates section should not be displayed. 
 The following message should be displayed: “Please submit their approved application via an AskMyHR service request immediately.”

2.  For maternity + parental option :
Currently, Section 2 parental field dates are editable. A pdf is generated on form submission.  We see the updated dates section. PDF should not be generated and updated dates section should not be displayed. 
The following message should be displayed: “Please submit their approved application via an AskMyHR service request immediately.”

3.  For Parental ONLY  option:
A pdf is generated on form submission.  PDF should not be generated. None of the dates are editable. All date fields should be editable. 
Updated dates sign-off section is disabled for the supervisor. It should be enabled. 
The following message should be displayed: “Please HOLD their application until the baby is born or placed, confirm birth or placement date with the employee. Make any necessary changes as per employee request, and then submit the approved application along with proof of birth via an AskMyHR service request.”

4. Pre-placement/Adoption:  
Currently, a pdf is generated on form submission. We see the updated dates section. PDF should not be generated and updated dates section should not be displayed.
  The following message should be displayed: “Please submit their approved application via an AskMyHR service request immediately.”

5. For Defer option:
Currently, a pdf is generated on form submission. We see the updated dates section. PDF should not be generated and updated dates section should not be displayed. 

6. For Not claiming option:
 Currently, a pdf is generated on form submission. We see the updated dates section. PDF should not be generated and updated dates section should not be displayed.

**Comment by schuyt** [comment]
Sent a message to Meghan and Stella to get confirmation on messaging. We can move that to another story and just focus on getting the PDF behaviour correct in this story.

**Comment by qudsia-khan-fw** [comment]
@iman-jamali-fw 
The supervisor is not receiving any emails after submission and hence no tasks are being created. I am further blocked from testing the end to end workflow. 
Maternity option:
Supervisor did not get email
No task is created
Can not further test
Reference: https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form/620ea51af5f0b5e2b6bdfd34/submission/6244e61d5302ccaf00002f67

Parental ONLY Supervisor did not get email
No task is created
Can not further test
Reference: https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form/620ea51af5f0b5e2b6bdfd34/submission/6244ed5f5302ccaf00002fd0

Maternity + Parental:
Reference:
https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form/620ea51af5f0b5e2b6bdfd34/submission/6244edcb5302ccaf00003001

**Comment by qudsia-khan-fw** [comment]
@iman-jamali-fw retested and for parental option, after supervisor submits initial decision, then, the updated dates link sent in email is not working. The user is navigated to the blank screen. Please address this
https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/task/$TASK_ID

![Screen Shot 2022-03-31 at 8.33.32 AM.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/509f0e86-fb5a-4e9a-828f-944b45fba342)
