### ISSUE TITLE
SL Review: Data | Connect API endpoints to front end form 

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#533]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
“As a user, I want the basic information section and Work Relationships and background section of the form to have all the fields in there prepopulated so that it saves time for me to fill out a long form. 

**Tasks**
- [ ] The given fields (as highlighted in attached screenshot) are auto-filled when I'm creating a new SL Review submission

**Acceptance Criteria**
When the above checklist has been checked off and the fields in the 2 sections have correct pre-populated info from the ODS/PeopleSoft

Link to draft form in DEV- https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form/62f6a0e509da98bcd4d3d73c

**Technical Details**
- Current ODS (operational data store) endpoint is accessible at https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_employee_demo (when connected to the BCGov VPN). 
- Mapping of this data so that a form can access it happens in `employee_data.py`
- Fields are automatically pre-populated with data as long as the "Property Name" of the "API" tab of a component in the forms designer matches a key in the payload.

**Comment by HasanSifat** [comment]
Screenshot to fields![MicrosoftTeams-image (13).png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/9e97660e-0dda-4211-ab16-391343655161)

![MicrosoftTeams-image (12).png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/f81a7d85-10f6-4407-86e7-2009f857edcd)

**Comment by iman-jamali-fw** [comment]
These are the mapping of the fields in the form and the key of data we're getting from `ODS`. For the missing ones, I'll first look into the ODS [table](https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_employee_demo) and if not found it there will talk to @T854236 for the possibility of adding the missing info to the ODS table.
### Employee work relationship and background
Ministry/organization => `organization`
Branch/division
Deputy minister's (DM) name
Assistant to the deputy minister's (ADM) name
Manager/supervisor name => `supervisorName`
Manager/supervisor title => `supervisorPositionTitle`
Manager/supervisor email => `managerEmail`
Number of direct reports
Number of indirect reports

### Personal Information
Employee name => `name`
Employee number => `empId`
Employee email => `email`
Employee position/title => `positionTitle`
City => `city`
Postal code => `postal`
Belong to diversity group? (Yes/No/Prefer not to say)

**Comment by T854236** [comment]
For branch/division, please have a look at level2_division.

Can you confirm at what lowest level leaders this form is form?  Depending on the level, this will dictate approach in getting the DM and ADM information.  It will most likely be in a separate endpoint.

We will need to check with PS BSAs for the indirect reports if/where it is stored.
For direct reports, a count on the existing endpoint where it matches the supervisor id should work?

**Comment by T854236** [comment]
Can you define how indirect reports should be counted?  For example, is it the number of employees that report to an employee that reports to a leader?

**Comment by MeghanStothers** [comment]
Decision needed: Can you confirm at what lowest level leaders this form is for? Depending on the level, this will dictate approach in getting the DM and ADM information. It will most likely be in a separate endpoint.

Decision needed to find out if it is technically possible: We will need to check with PS BSAs for the indirect reports if/where it is stored. For direct reports, a count on the existing endpoint where it matches the supervisor id should work?

**Comment by iman-jamali-fw** [comment]
@HasanSifat The currently available fields are added to the DEV and are ready for testing.

**Comment by MeghanStothers** [comment]
4 fields for Patrick to add to ODS

**Comment by HasanSifat** [comment]
- Personal information Panel pre-populated with correct info for my profile- ![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/68c58700-d66f-45f0-9103-d5c81f8df3b0)

- Employee work relationships panel: 2 fields not pre-populated ![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/51d0d4ba-a5d8-45aa-87c8-dd9b83722bab)

**Comment by T854236** [comment]
With ADM and DM information, can you confirm leaders to be returned when there are multiple ADMs?  For example, an ADM might report to another ADM.  Should ADM return the first one and then the DM (skipping the 2nd ADM).

**Comment by HasanSifat** [comment]
Tested successfully in DEV. Ready to be transferred to TEST
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/91ce91e6-450f-4ca0-8642-252fd09e4b4a
)

**Comment by iman-jamali-fw** [comment]
@HasanSifat  Deployed to TEST and ready for testing

**Comment by HasanSifat** [comment]
Tested successfully in TEST. Ready to be transferred to PROD
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/1d2a7b15-648b-4ddf-8360-1002f8ccf5af)

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/e7740eda-25c7-4745-8a17-ea6db25621da)

**Comment by MeghanStothers** [comment]
Simen will deploy to prod when we have more SL tickets - ready to be tested
