### ISSUE TITLE
SL Review: Being able to save a form before submission and the form autosaves

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#535]
**User Story**
As  a user, I want the ability to save a form through a button before submission and also the form needs to autosave itself anytime any changes have been made. 

**Tasks**

- [ ] TBD 
@simensma-fresh Please look into this for further discussion. This ticket is related to ticket#109. Thank you :) 

**Acceptance Criteria**
This issue can be defined complete when users have a save button and the form auto saves itself after each change.

**Comment by HasanSifat** [comment]
@bhumin-fw please put in an estimate on this ticket

**Comment by simensma-fresh** [comment]
@HasanSifat I noticed in the formsflow repository that the last couple of days they've added some functionality related to saving submissions as draft. If we have a contact at AoT, I would suggest that we reach out and see if this is a feature they expect to release soon, before we start implement our own version

**Comment by Abuchana** [comment]
AOT has a "draft" feature in the next version

**Comment by iman-jamali-fw** [comment]
I did a quick lookup into the AOT repo and seems like they have implemented the draft feature. Below are two PRs that implement that on API and UI:
- [Draft feature API](https://github.com/AOT-Technologies/forms-flow-ai/pull/617)
- [Draft feature - UI](https://github.com/AOT-Technologies/forms-flow-ai/pull/708)

**Comment by MeghanStothers** [comment]
Simen suggestion to hold off on next feature update in formsflow.ai - possibly in Sept/October

**Comment by HasanSifat** [comment]
Ready to be closed
