### ISSUE TITLE
Telework Form - Submission Analytics Dashboard 

### ISSUE THREAD

**Issue by simensma-fresh** [bcgov/digital-journeys#538]
**User Story**
As a Digital Journeys admin, I want to be able to view a number of how many submissions there currently are in the system

Acceptance Criteria
- A dashboard is created where the total number of telework submissions is displayed

**Comment by MeghanStothers** [comment]
Numbers of completed and in progress Telework forms are needed for weekly reporting to exec (every Thursday). 
I have requested access to BP (Stephen Jones) who will grant Stella, Hasan, Meghan access as soon as possible.
In the interim, Alison can provide those numbers, but for efficiency, we'd like the DJ program area team to have direct access.

**Comment by Abuchana** [comment]
@MeghanStothers, I'm wondering if this should maybe be on the Program Board as it's more operational/BI and doesn't really involve the dev - TES team. Thoughts?

**Comment by MeghanStothers** [comment]
Yes- we will create a new tix for the business board
