### ISSUE TITLE
Mat/Pat: Differentiate users with multiple roles

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#539]
**User Story**
“As a user, I want to have different roles at different times/situations, so I can both submit an application AND review, comment, and approve my employee's applications.” 

**Acceptance Criteria**

As an employee, I can see my own in the applications tab
As an employee, I cannot see others' applications
As a supervisor, I am able to see my employee's submissions in the tasks tab
As a supervisor, I cannot see other employee's applications that do not report to me

Ensure the work done to hide the applications tab in Telework is not undone

**Comment by Abuchana** [comment]
Consider the impacts of making the task tab and applications tab visible to users
