### ISSUE TITLE
SL REVIEW: Make the "+" sign on collapsible panels to be more visible

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#541]
**User Story**
As a user and forms designer, I want to be able to clearly see the + sign on the collapsible panels so that it is more visible and accessibility standards are maintained. 

**Tasks**

- [ ] Make the + sign contrast higher (make it white) with the blue background color

- [ ] Or possible make it bigger whichever works

**Acceptance Criteria**
When the above tasks are complete and the plus sign is clearly visible.

**Comment by HasanSifat** [comment]
tested successfully in DEV. Ready to deployed to TEST

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/f83296cb-47bb-4cd2-9e85-3a3c0ca8c718)

**Comment by iman-jamali-fw** [comment]
@HasanSifat Deployed to TEST and ready for the test.

**Comment by HasanSifat** [comment]
Looking good in TEST. Ticket is ready to be closed as this feature is not required in the updated SL review form.
