### ISSUE TITLE
SL Review: Secure authentication/access to the form  

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#549]
As a forms designer, I want to restrict the access to forms database to a specific list of people.

Tasks- 

- [ ] Create list of people 

- [ ] add list to keycloak  for restricting access

- [ ] sync this list of people to the SL Review 2.0  form 

- [ ] COnfirm this list is available in the Microsoft teams channel

**Acceptance Criteria**
When only the listed people have access to the form

**Comment by MeghanStothers** [comment]
Simen: If it is a small number of people, can be managed by keyCloak

Jodi: People who need access 1,300 people (and 5 and 6) plus nominated band 4 SL 

Restrict submissions

**Comment by MeghanStothers** [comment]
merge ticket with #522

**Comment by MeghanStothers** [comment]
We will have to review the (updated) SL authentication requirements to know which groups need access to the form (and which ones should not have access).

**Comment by MeghanStothers** [comment]
@simensma-fresh Can you set up keycloak so only ADMs can access this form?

**Comment by simensma-fresh** [comment]
@MeghanStothers 
Maybe! If there's only a limited number of ADMs, we could set up a KeyCloak group that we manually maintain. Otherwise we could look into and see if there's a data-point in the ODS that would give us this information so we can restrict it that way

**Comment by HasanSifat** [comment]
new group added in keycloak- SL Review ADM. This group will have access to form pre population and also access to the form 

Simen setting up meeting with Eddie to get the list and manage the handling of updating this list by the program team.

**Comment by MeghanStothers** [comment]
@simensma-fresh is this something we could do as a bulk load? For example, as an Excel spreadsheet?

**Comment by simensma-fresh** [comment]
This is ready to be tested in dev. A KeyCloak group has been set up (sl-review-adm) to manage access to the form.
- If you're part of that group (or you're a forms-designer), the form shows up in the forms list
- If you're not part of that group, the form does not show up in the list

**Comment by HasanSifat** [comment]
/SL review ADM group working as required in DEV environment. yet to test in TEST/PROD

**Comment by JodiLittle** [comment]
With the delayed launch how will this affect testing of this in TEST/DEV? PSA will be piloting the process and form - not sure of launch date, but I could provide the names, emails, idirs of those ADMs for testing. Would this help?

**Comment by HasanSifat** [comment]
working successfully in DEV and TEST
