### ISSUE TITLE
Update fromsflow.ai to version 5.0.0

### ISSUE THREAD

**Issue by Abuchana** [bcgov/digital-journeys#553]
The Digital Journeys project is currently running on formsflow.ai v4.0.6. A need for features in the latest formsflow version has been identified, so a version upgrade is needed

**Tasks**
1.  Run Snyk on the local code base for digital journeys to identify vulnerabilities 
2. Push stable version of the update to DEV

**Comment by Abuchana** [comment]
Note: Major version update this time may be trickier than the last version update

**Comment by iman-jamali-fw** [comment]
Link to all the new features in v5:
https://github.com/AOT-Technologies/forms-flow-ai/releases/tag/v5.0.0

**Comment by iman-jamali-fw** [comment]
Deployed to DEV and ready for testing

**Comment by MissionT** [comment]
Stella and I tested the telework agreement for: 2 days, 3+ days, and occasional agreements. Everything looks good; no issues were generated.

**Comment by Abuchana** [comment]
That's great news, thank you for testing it and the update! 
@iman-jamali-fw and @simensma-fresh, what comes next, push to Prod? Timing?

**Comment by iman-jamali-fw** [comment]
Regarding the next steps, one question would be if the team wants the new draft feature enabled in PROD.

**Comment by Abuchana** [comment]
@iman-jamali-fw if pushed to Prod, draft would automatically be applied to TW? If so, not yet I'd say.

**Comment by iman-jamali-fw** [comment]
@Abuchana  We can disable it on PROD if you want everything in v5 except the draft (which would require some prep work).

**Comment by MissionT** [comment]
UPDATE: I tested this in the test environment and realize this should have been tested in DEV. Doing that now.

**Comment by Stella-Archer** [comment]
I'm not seeing the Draft test page
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/a6daef38-d4a5-4f0a-aba0-6ab8226f28b6)

**Comment by MissionT** [comment]
Testing is complete  - please let me know when this can be closed.

**Comment by iman-jamali-fw** [comment]
@Stella-Archer To have draft, you first need to start a new form (Telework), wait for a few seconds, and then a draft version of that form is saved and will be accessible under /draft page.

**Comment by iman-jamali-fw** [comment]
@MeghanStothers @Stella-Archer 
To move v5 to Prod, you need make a decision whether to have draft feature for Telework enabled or not. To help you decide, here are some steps we can take:

1. We can globally disable draft feature with no effort involved.
2. We can toggle draft per form, other words, only disable it for the Telework form. This will require some effort, I estimate it to be **3**. 
3. If you decide to enable draft for Telework, we need to make sure drafts are removed completely after being submitted. Currently drafts are soft deleted, which means user data will persist in database AND delete submissions functionality for incomplete and completed submissions will partially fail. Efforts involved to add hard-delete for drafts is **2**.

**Comment by HasanSifat** [comment]
We have ticket 601 to address 3.2 of the above comment. 3.1 needs to be addressed after 3.1/601 has been solved. The decision from the program team is to enable the draft feature globally and make sure it's working accurately

**Comment by HasanSifat** [comment]
Tested in DEV. Ready to be transferred to TEST and PROD
