### ISSUE TITLE
Create a PeopleSoft certificate upon form submission

### ISSUE THREAD

**Issue by Abuchana** [bcgov/digital-journeys#554]
As a form submitter, I want a certificate to be created in PeopleSoft (My Self-Serve dashboard), so I have proof of completion.

This is a technical request from Ian Hennem. The intention is to not only to create a form but also transactions that equate to a journey.

**Comment by fazil-ey** [comment]
closing as it is an old ticket, has not come up as a feature since. May not be relevant with oracle fusion
