### ISSUE TITLE
Telework: Add two bullets to the  "Before you begin" section 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#555]
As a user, I need key information about the form up front, such as 
1) the form cannot be edited after submission
2) you will need to resubmit if you make an error or if your personal information or telework request changes 

A/C
Add these two new bullets 
- Your agreement cannot be edited after submission  
- to update your your telework request (or agreement information), you must resubmit your agreement using the digital form and your supervisor must again approve 

Please put these bullets above this last one:
"Your telework agreement will be valid for one year"

**Comment by MeghanStothers** [comment]
I propose we go ahead with the wording for the two points based on user feedback - we will need to run them by Sean/Ken first with an invitation for us to edit the bullets if required.

**Comment by MeghanStothers** [comment]
@MissionT Hey, I think this change has been done, right?  If so, we can closet his ticket.

**Comment by HasanSifat** [comment]
I don't see the bullets in PROD. not ready to close yet

**Comment by MeghanStothers** [comment]
@MissionT Hi Chris - are we able to close this ticket?

**Comment by HasanSifat** [comment]
added to DEV and TEST!

**Comment by Stella-Archer** [comment]
prod is live
