### ISSUE TITLE
TELEWORK: make attachment field not mandatory in manager's sign-off section if denied

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#559]
**User Story**
As a manager, I want to be able to deny a submission of the telework form and not have to attach a document if the submission was for more than 3+days. This will allow me to deny applications when an ADM approval was not acquired and the application needs to be denied. However, if the application needs to be approved the attachment field should be mandatory.

**Tasks**
Make the attachment field in manager's sign-off section non-mandatory

**Acceptance Criteria**
When the attachment field is not mandatory for managers anymore if the selection is made for "Deny"

**Comment by MeghanStothers** [comment]
This is a process problem missed during initial development. We need to have application logic. Chris to investigate and think about the logic and the connect with a dev.  We don't want people to upload a doc in order to deny them - this is a usability issue.

**Comment by HasanSifat** [comment]
tested successfully in DEV.

**Comment by HasanSifat** [comment]
Ready to move to TEST

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
