### ISSUE TITLE
TOOL: Re-introduce Applications tab and test

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#574]
**User Story**
As a user filling out any form, I want to be able to see the difference between in-progress applications, rejected ones, approved ones and etc. 

**Tasks**

- [x] Reintroduce the applications tab for users for selection on the top menu bar. 

- [x] Carry out end-to-end test for testing the page and how it affects the platforms/forms

**Acceptance Criteria**
When the applications tab is available for users and is bug free

**Comment by JodiLittle** [comment]
Introduce as is. Look at the applications tab and the feasibility of it. Related to ticket 576.

**Comment by HasanSifat** [comment]
tested successfully in Dev. Ready to be transferred to TEST

**Comment by HasanSifat** [comment]
ready to be transferred to test

**Comment by HasanSifat** [comment]
Tested successfully in TEST

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
