### ISSUE TITLE
Telework PIA; Adjustments needed from Applications tab/Privacy rules in the current PIA

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#577]
As a form owner, I want to make sure my PIA is up-to date.

The SL project requires a global change to the tool that will put the "applications" tab in use and allow users to have forms in draft form and go back and edit.

This is change to the current PIA and we will need to work with the privacy office to update the current PIA/make an amendment

**Comment by MeghanStothers** [comment]
Consider feedback from users (confirmed by Chris) to adjust to 60 or 90 days - will need an update to the PIA

**Comment by MeghanStothers** [comment]
@NassNK Hi Nass - we're ready to review the Telework PIA as a team to make sure we've incorporated SL changes that affect the tool. I'll set up a session for next week.

**Comment by HasanSifat** [comment]
Meghan meeting with Jennifer today(Thursday 20 oct) to review the Telework and SL PIA

**Comment by HasanSifat** [comment]
Jennifer is also working on ER form PIA

**Comment by HasanSifat** [comment]
According to last update from Meghan, PIA has been updated for telework

**Comment by MeghanStothers** [comment]
The updated PIA is with the privacy folks for signature and any next steps. I will close this ticket when it has been delivered and signed. I will coordinate the signature with PIE/Rueben.
