### ISSUE TITLE
KeyCloak Gold Migration

### ISSUE THREAD

**Issue by simensma-fresh** [bcgov/digital-journeys#578]
OCIO Is ending support for their KeyCloak Silver cluster in January 2023, we need to migrate to using their Gold cluster for our IDIR integration before then.

*Acceptance Criteria*
- [ ] As a new user, I'm able to log into the platform using my IDIR
- [ ] As an existing user, I'm able to log into the platform using my IDIR
- [ ] As an existing user, I'm able to see all tasks I previously had access to
- [ ] As an existing user, I'm able to see all applications I previously had access to
- [ ] Pre-population of the Telework form still works as expected if I try to fill out a new one

**Comment by HasanSifat** [comment]
- [ ] As a new user, I'm able to log into the platform using my IDIR
- [ ] As an existing user, I'm able to log into the platform using my IDIR
- [ ] As an existing user, I'm able to see all tasks I previously had access to
- [ ]  As an existing user, I'm able to see all applications I previously had access to
- [ ]  Pre-population of the Telework form still works as expected if I try to fill out a new one

**Comment by Stella-Archer** [comment]
@iman-jamali-fw  to test the first 'New user' criteria we need to have you remove Hasan completely from KeyCloak

**Comment by HasanSifat** [comment]
test submission for telework failed in TEST

**Comment by Abuchana** [comment]
https://bcgov.github.io/sso-requests

**Comment by warrenchristian1telus** [comment]
Just a note about the link above. It is intended to be used to **delete the silver integration #2311** once prod has been upgraded to gold.

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
