### ISSUE TITLE
ODS: Employee record not passed with form submission to ODS/BI

### ISSUE THREAD

**Issue by T854236** [bcgov/digital-journeys#580]
When the Telework form data is sent back to us, the EMPL_RCD is lost. This makes calculating/assigning the EMPL_RCD tricky especially in the cases where employees have multiple records.

**Comment by MeghanStothers** [comment]
@T854236 Hi Patrick - can we connect about this ticket so I can understand timelines and if this can be pulled into the backlog. Thanks. Do we need Steven Jones for this if this involves the dashboard?

**Comment by T854236** [comment]
@MeghanStothers 

Hi, I was away on vacation but will book a meeting with Aki.

**Comment by Abuchana** [comment]
@T854236, can you provide an estimate for this ticket? And this assigned to all the people it needs to be? There are no Devs assigned...

**Comment by T854236** [comment]
@Abuchana we would need input from a forms developer for the effort.  The job record already exists in the API endpoint being consumed.

**Comment by Abuchana** [comment]
@T854236, are you thinking PSA Dev or EY Dev?

**Comment by T854236** [comment]
@Abuchana I suppose that depends on who can add a new field on the form from the API endpoint.  I'm not sure if a PSA dev does that now?

**Comment by Abuchana** [comment]
@HasanSifat, who would be the dev on this ticket? TES Dev or PSA Dev? we need to assign it accordingly...

**Comment by HasanSifat** [comment]
For now, this would be Dev-PSA and that is because we still are looking into solutions to this particular issue. But not a priority for the next sprint or at least till SL review launch.

**Comment by Abuchana** [comment]
@HasanSifat thank you. So pull it into the product backlog and assign it to...?

**Comment by HasanSifat** [comment]
yes product backlog and assigned to Me/Stella. I see Patrick is already tagged.

**Comment by HasanSifat** [comment]
PDP project team is also facing this same issue.

**Comment by HasanSifat** [comment]
@T854236 any news or solutions to this?

**Comment by T854236** [comment]
@HasanSifat the employee record is available in the existing endpoint for employee demographic to be consumed by the application.  The application will need to have logic to determine what is passed back down to ODS and BI.

**Comment by fazil-ey** [comment]
Setup meeting with Patrick to discuss implication of having an employee with 2 diff positions (i.e. 2 different records in the database). 

- Does this mean they have 2 different supervisors, and should be allowed to have 2 different agreements? 
- How do we want to handle this situation for these employees?

**Comment by fazil-ey** [comment]
Closed because it affects only reporting and there are a very small fraction of people with this issue.
