### ISSUE TITLE
TOOL: Drafts Tab | Remove Draft ID column and change Draft name column to give more info

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#598]
As a user, the draft id column does not give me any useful information. The draft name column should also so "Telework Agreement for XXXXX"/ SL Review form for XXXXXXX", depending on a specific field in particular to that form. 

Tasks

- [x] Remove Draft ID column

- [x] Change/add new cloumn to say  "Telework Agreement for XXXXX"/ Senior Leadership Review form for XXXXXXX"

For telework: field name (employee name)
For SL Review: field name (enter employee name) 

Acceptance criteria
When the required info for draft applications are available in the draft tab

**Comment by HasanSifat** [comment]
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/4533fe0d-375d-47a5-8d19-6e88cde16687)

**Comment by HasanSifat** [comment]
Update: Rename SL review form entries to say "Senior Leadership Review Form for XXXXX"

**Comment by HasanSifat** [comment]
Tested successfully in DEV. Ready to be transferred to TEST and PROD

**Comment by HasanSifat** [comment]
@bhumin-fw the SL review 2.0 form name was changed to Senior Leadership Review Form and i can see that the draft name column is not reflecting the name of the senior leader the ADM will approve. Pulling this back into In progress pipeline

**Comment by bhumin-fw** [comment]
@HasanSifat Fix name does not display issue. The fix is available on DEV.

**Comment by HasanSifat** [comment]
looks good thanks. tested successfully in DEV. Ready to be transferred to TEST/PROD

**Comment by MeghanStothers** [comment]
Approved and ready to be moved to test

**Comment by HasanSifat** [comment]
Tested successfully in TEST

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
