### ISSUE TITLE
Tool: Application tab | change "new" status of forms to say "pending"

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#599]
As someone going into the forms tool I want to see the correct status of my forms 

Dev Tasks
Change status of "new" applications to "pending"
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/b8a1b56e-04f1-43ab-8837-f999418f88dc)

**Comment by HasanSifat** [comment]
not needed at this time!
