### ISSUE TITLE
The user is displayed with a "Login Error" after logging out from the app

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#60]
**Background:** The user is displayed with a "Login Error" after logging out from the app.

**Environment:** Test

**Steps to Reproduce:**

1. Log in to the PSA-Digital-Journey portal on test with valid credentials.
2. Click on "Logout".

**Actual Behavior:** The user is displayed with a "Login Error" after logging out from the app. The user can not log back in as a different user unless using an incognito window which must be closed and re-opened after logging out. 
![DJloginError.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/c201dfb0-1cd0-466c-9e01-088403b11e87)

**Expected Behavior:** The user should not be displayed with any errors and should be redirected to the login screen after logging out.

**Comment by schuyt** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Digital-Journeys-61c10fe84c8bcb001491c5f5/issues/bcgov/digital-journeys/60?planning-poker) with ZenHub @simensma-fresh @iman-jamali-fw @qudsia-khan-fw
