### ISSUE TITLE
TOOL: Drafts Tab | Add button in top menu bar for "Draft Forms" tab

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#602]
**User Story**
Asa a user, I want the draft forms tab available in the top menu bar

**Tasks**

- [x] Add button to "Draft Forms" tab in the top menu bar

- [x] Remove drafts tab under applications

**Acceptance Criteria**
When the draft forms tab is available from the top menu bar

**Comment by HasanSifat** [comment]
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/c71e06b9-caf1-4d28-8812-07384232f12e)

**Comment by HasanSifat** [comment]
the icons and the underline can go as well

**Comment by bhumin-fw** [comment]
@HasanSifat 
Added new Draft tab. As "Admin" tab is role-based and not visible to all the users.
The new nav bar and the draft page will look like the below image. Please review and do let me know if you find any corrections or do not match the requirements.
![image.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/e3d51336-ad3b-43e5-8185-a340c34d43f4)

cc: @simensma-fresh

**Comment by bhumin-fw** [comment]
@HasanSifat For sure, Let me change its position and add PR.

**Comment by HasanSifat** [comment]
Tested successfully in DEV. Ready to be transferred to TEST and PROD

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/49135dcd-7b6b-47c4-bd71-03d5261ecef8)

**Comment by HasanSifat** [comment]
ready to be transferred to TEST

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
