### ISSUE TITLE
TOOL: Drafts Tab | Add description to Drafts tab under title 

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#603]
**User Story**
Asa user i need to know the definition and purpose of the drafts tab 

**Tasks**

- [x] Add description "All applications/submissions that have been started by the user but not yet submitted" under title 

**Acceptance Criteria**
When the description has been added under the title

**Comment by HasanSifat** [comment]
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/86492301-aeef-44db-8305-67c5c4c5b68c)

**Comment by HasanSifat** [comment]
@bhumin-fw I can see the description in the draft forms tab. But can you make the description font to be black? It's a grey color now

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/db4dd959-85c2-49fe-82dc-c06d94273e07)

**Comment by bhumin-fw** [comment]
@HasanSifat 
It was default CSS, Changed the description color to black on both pages Application and Draft.

**Comment by HasanSifat** [comment]
@bhumin-fw Update to description: All forms that have been started but not yet submitted

**Comment by bhumin-fw** [comment]
@HasanSifat updated the description on DEV.

**Comment by HasanSifat** [comment]
tested successfully in DEV. Ready to be transferred to TEST/PROD

**Comment by MeghanStothers** [comment]
approved and moved tot test

**Comment by HasanSifat** [comment]
Tested successfully in TEST
