### ISSUE TITLE
TOOL: Applications Tab | Add description to Application tab under title

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#606]
**User Story**
Asa user i need to know the definition and purpose of the applications tab 

**Tasks**

- [ ] Add description "All applications that have been submitted. Includes pending for review, approved/denied, resubmit, etc." under title 

**Acceptance Criteria**
When the description has been added under the title

**Comment by HasanSifat** [comment]
@bhumin-fw update to description: All forms that have been submitted

**Comment by bhumin-fw** [comment]
@HasanSifat updated the description on DEV.

**Comment by HasanSifat** [comment]
looks good. Tested successfully in DEV. Ready to be transferred to TEST/PROD

**Comment by MeghanStothers** [comment]
approved - ready to be moved to test

**Comment by HasanSifat** [comment]
Tested successfully in TEST

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
