### ISSUE TITLE
SL Review: Change "resubmit" status name to "Submitted"

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#610]
**User Story**
As an ADM, the re-submit status is confusing. The term "submitted" makes more sense

**Tasks**

- [x] Change the "resubmit" status fo SL review forms to "Submitted" 

**Acceptance Criteria**
When the resubmit status has been changed to "Submitted". SL review form once submitted needs to be in "Submitted" status and the ADM can edit the form as well.

**Comment by HasanSifat** [comment]
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/bb836219-2837-4693-8c03-ad785d9be606)

**Comment by HasanSifat** [comment]
Tested successfully in DEV. Ready to be transferred to TEST/PROD

**Comment by JodiLittle** [comment]
Approved

**Comment by HasanSifat** [comment]
tested successfully in TEST
