### ISSUE TITLE
Mat/Pat: Show workflow based on eligibility using appointment status from ODS

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#612]
**User Story**
As a mat/pat applicant I want go to the appropriate workflow based on my eligibility that is decided by my appointment status

**Acceptance Criteria**
- [x] In the basic info screen, if appointment status is ~J or K~ K or L, go to the [not eligible screen](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764536517404784&cot=14) 
- [x] For all other appointment statuses go to the [next screen in eligible workflow ](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764543687588205&cot=14)

**Design**
Employee Info - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764544376295648&cot=14

Not eligible screen - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764543687588220&cot=14

Miro board - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764543687588226&cot=14

**Comment by T854236** [comment]
@Stella-Archer 
I believe you are looking for appointment status and category based on the values you shared.  That is available in the existing endpoint used by the Telework forms: https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_employee_demographic/

Column names: appointment_status and empl_ctg

**Comment by HasanSifat** [comment]
@T854236 I can't seem to access this link. I tried with my idir and password. Do i need to put ina request to Aki and the team to get access?

**Comment by T854236** [comment]
@HasanSifat 
If you are looking to make a call to the API endpoint, yes you'll need an account.  Perhaps leverage the one provisioned for Telework?

If you are only looking for information, you can access it here: https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rst#Datamart_Telework_employee_demographic

**Comment by HasanSifat** [comment]
Thanks @T854236 this is much more helpful

**Comment by Andrew-Vargas-bcgov** [comment]
Connie updated us that it is 'K' and 'L' that do not receive benefits.

**Comment by iman-jamali-fw** [comment]
I checked our API and we currently not getting the employee's `appointment status` from ODS. We need to add that to the backend and then will be able to use it on the form.

**Comment by T854236** [comment]
@iman-jamali-fw 

To confirm, you are wanting appointment status and not employment status?

**Comment by iman-jamali-fw** [comment]
@T854236 

Yes, based on the ticket, appointment status. 

By the way, I assumed this is included in the `https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rst#Datamart_Telework_employee_demographic`. I didn't test out that endpoint, having difficulty connecting to BC Gov VPN on my EY laptop. I just confirmed that we currently not recording it in our backend (to be passed to the form).

**Comment by T854236** [comment]
@iman-jamali-fw 

Hi Iman, there is an appointment_status field with possible options: Regular, Auxiliary and ABC.  Is that what you were looking for?

**Comment by iman-jamali-fw** [comment]
@T854236 
Apologies for my late reply!

yes, I believe so. 
@fazil-ey  and @Andrew-Vargas-bcgov can confirm if this is the one.

**Comment by ayushdamani** [comment]
Tested and verified.

 [Not eligible screen](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764543687588220&cot=14) appears if 'k' or 'l' is typed in the appointment status. Although, if the alphabets are capitalized, the not eligible screen does not appear. Not sure if that makes a difference.

**Comment by Andrew-Vargas-bcgov** [comment]
@ayushdamani good catch. The statuses will autopopulate capital K and L. Fixed the conditional.

**Comment by fazil-ey** [comment]
This is not working in test. Seems like the logic has not been implemented in test yet 

[Recording](https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-04-24%20at%2012.58.07%20PM.mov?csf=1&web=1&e=PTbBke)

**Comment by Andrew-Vargas-bcgov** [comment]
Seems like it reverted back for some reason. Fixed it again.

**Comment by fazil-ey** [comment]
- The bug with capitalized K & L still exists not going to "not eligible" screen still exists
- If R, the next screen is confirmation page & not the Alternate contact info screen

Recording -> 
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-04-24%20at%202.06.37%20PM.mov?csf=1&web=1&e=m4tYOX

**Comment by Andrew-Vargas-bcgov** [comment]
capitalized K and L work for me. It leads to the not eligible screen in test. Looks like the confirmation page was added when I was gone, do you know when it is supposed to be shown? Is this the confirmation page for K and L people?

**Comment by ayushdamani** [comment]
- Just checked, capitalized K & L are not working for me in the test environment. 
- Lower case 'k' and 'l' are working perfectly.

**Comment by fazil-ey** [comment]
Capitalized K & L are working. Considering the field will not be editable and the value will be pulled from DB, we should be okay. 

Pending issue - 
1.  R is still going to confirmation screen, instead of alternate contact screen. confirmation screens should only come on submission

**Comment by Andrew-Vargas-bcgov** [comment]
the confirmation page is not part of the form, so I have hidden it.
It will be a success page redirect like the other forms.

**Comment by fazil-ey** [comment]
@chriscaldwell-psa 
The label "Date/Time" should be "Start Date" on the not eligible page

<image src="https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/4b4752b0-5e33-4e81-b43d-c1bc4750f469" width="50%" length="50%"/>

**Comment by fazil-ey** [comment]
[Works as expected](https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-05-01%20at%209.06.40%20AM.mov?csf=1&web=1&e=hhNJxb)
