### ISSUE TITLE
ODS: Possibility to have a copy of the employee demographic information in formsflow

### ISSUE THREAD

**Issue by T854236** [bcgov/digital-journeys#617]
If possible, recommendation to have a copy of the employee demographic data in formsflow to be used by all the forms used.

This should allow better performance if data is within local environments and reduce the amount of API calls to BI API servers

**Notes**
- Will caching work? @iman-jamali-fw 
- What is the advantage? Is it worth it? How many calls can we reduce? 
- Does it affect PIA?

**Comment by fazil-ey** [comment]
Action - Ask Patrick @Abuchana

**Comment by T854236** [comment]
@iman-jamali-fw 
If you can use caching for multiple hours, that will work.  ODS is refreshed once a day.  Depending on how the form is built, it can make multiple calls to the API for information that doesn't change for the day.  It is averaging 150 calls for telework form per day in PROD and was averaging 1500/day during first week of launch.

I can't comment on the PIA but can share that other applications have a copy of the employee demographic information within the application that is loaded once a day.

**Comment by iman-jamali-fw** [comment]
@T854236 
Can you confirm the smallest data change period at ODS for getting requests? For employee demographic.

**Comment by T854236** [comment]
@iman-jamali-fw 
ODS feeds from BI datawarehouse which feeds for CHIPS RP.  Refreshes are run once a day every morning.

**Comment by fazil-ey** [comment]
@iman-jamali-fw  to test this ticket. @bhumin-fw  to add more context

**Comment by iman-jamali-fw** [comment]
It was tested successfully. Amazing work @bhumin-fw

**Comment by MeghanStothers** [comment]
Okay to close - this is the only test we/team can do. We/users should notice better speed.  There will be lower usage of resources.
- reduces unneeded calls to ODS
- could use across other forms

Great work, Bhumin! Can you please add info about this work for succession planning/our team's records?
