### ISSUE TITLE
Manager/supervisor sign-off section not appearing in final PDF. 

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#624]
Background: Manager/supervisor sign-off section missing from final PDF. 
 
Steps to Reproduce: Supervisor selects the approval link sent from the employee's confirmation email. Supervisor approves/rejects the agreement whereby a final PDF is generated.
 
Actual Behavior: Manager/supervisor sign-off section not appearing in final PDF
 
Expected Behaviour:Manager/supervisor sign-off section should appear in final PDF
 
Environment:
Production Env.

**Comment by MeghanStothers** [comment]
This was likely a one-off - we have not seen this one repeated. We will keep it on the board in icebox. Chris reporst it has only happened with one or two.  Connectivity issue?

**Comment by HasanSifat** [comment]
This bug came up one more time with telework users. Bringing back to Product backlog and start investigating.

**Comment by HasanSifat** [comment]
Submissions disappearing right after approval is a big blocker for DEVs to investigate and troubleshoot these kinds of issues. One solution recommended is to have submissions available for 30 or so days in the tasks tab so that they can be investigated

**Comment by HasanSifat** [comment]
If the employee cna share the pdf that has this issue it will help the devs as well

**Comment by HasanSifat** [comment]
once Digital journeys moves into AOT PDF generation feature then this might not be a problem anymore. No other users reported this issue. Moved to ICEBOX

**Comment by MissionT** [comment]
[https://app.zenhub.com/files/439477060/0b92f745-9e9f-483b-a067-00be2fe1651e/download](https://app.zenhub.com/files/439477060/0b92f745-9e9f-483b-a067-00be2fe1651e/download)

Please see the PDF containing the missing manager sign-off section.
