### ISSUE TITLE
Mat/Pat: CRM ticket generated upon form approval

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#625]
Explore how to create a CRM ticket after form submission/form approval. 

**To be decided** 
- Method for creating CRM ticket - API vs mailbox. (API is preferred) 
- Service category the ticket has to be created under
- How should the data be sent? as a pdf attached to ticket? Are any fields required? 
    - How does the CRM team prefer to receive the data? PDF? 
- Confirmation of submission, tracking ticket 
- Can we show the CRM ticket number in digital journeys (so that people can access it even if the cant access their emails)  
    - Will CRM send an email? 

**After Approval** 
- What do we do for edits? If a form is edited and reapproved by supervisor how will we create a ticket? What will happen to the old ticket?

**After leave starts** 
- What will we do if a new document is uploaded in the form like EI acceptance screenshot, birth certificate? 

**Other**
- Can applicants see the CRM ticket as one of the tickets created in their name or supervisor's name? What is preferred?

**Comment by MeghanStothers** [comment]
Decision made: Thread options as a pilot as we get info and estimates about option mapping as longer=term option.

**Comment by Abuchana** [comment]
Caleb: A JIRA has been submitted to TES for quotation. I will advise the digital journey team once this is created and ready for testing.
