### ISSUE TITLE
SL Review: Rename tasks for SL Review in Tasks tab

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#628]
**User Story**
As an ADM, I want to see more information in the tasks tab related to the submissions I made through the SL Review form

**Tasks**

- [ ] Rename entries of SL review from in tasks tab to say "Senior Leadership Review Form for XXXXXX" 

**Acceptance Criteria**
When entries in the task tab for SL review form has the information mentioned above.

**Comment by MeghanStothers** [comment]
As per decision with Jodi SL team: 

1) Preferred name is Senior Leadership Review
2) Second choice is Sr Leadership Review

**Comment by Abuchana** [comment]
Not needed any longer
