### ISSUE TITLE
TOOL: DEV environment not allowing data input 

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#630]
Background: All forms in DEV do not allow for any input on any fields. Specifically or gov.bc.ca users
 
Steps to Reproduce:
1. Go into DEV with a gov.bc.ca user credential
2. Open the telework/sl review form
3. try to input info into the fields 
 
Actual Behavior:
 1. The fields all revert back to default even after inputting data. 

Expected Behaviour:
1. The fields should hold the data being input and allow users to edit pre-populated info as well. 
 
Environment: DEV

**Comment by MeghanStothers** [comment]
@Simen Hi there - is this bug still an ongoing issue?

**Comment by MeghanStothers** [comment]
@simensma-fresh

**Comment by simensma-fresh** [comment]
@MeghanStothers  @HasanSifat @Stella-Archer This has now been fixed in dev, so both auto-population of the telework form and SL Review should now work

**Comment by HasanSifat** [comment]
Just did a test submission in Dev for Telework, Also SL review form's search and pre-population feature is working correctly. All emails for telework came in and SL review looks good too. I think this is ready to be closed
