### ISSUE TITLE
SL Review: Confirmation page after "Final Submit" button

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#632]
**User Story**
A confirmation window after the final submit button is pressed. 

**Tasks**

- [ ] Currently a green popup with telework messaging shows up 

- [ ] Copy:

Thank you for your commitment to supporting career development of your Senior Leadership team and for your contribution to executive succession.

- The information you’ve provided will be shared with Executive Talent Management, Corporate Workforce Strategies in the Public Service Agency, as well as ministry Strategic Human Resources (ministry-specific data). Broad themes will be presented to DMCPSR to further the conversation on executive talent and utilized for executive succession and development strategies, programs and activities.
- Please download a PDF copy for your files and share with the senior leader. Continue conversations with the identified senior leader to refine their learning and development plan, goals, and actions in support of their aspirations. Your Ministry Human Resources representative can connect the senior leader with targeted ministry and corporate learning opportunities to ensure they have access to the essential learning and experiences that will set them up for success. Coaching services are also available to senior leaders.
- Thank you for completing the senior leadership review process. You have made your final submission for the senior leader.
- You can come back and edit the information and resubmit at any point up until 11:59 PM on January 27, 2023.

**Comment by HasanSifat** [comment]
Edit to copy-
**Thank you for your commitment to supporting senior leadership and executive succession**
•	The information you’ve provided will be shared with Executive Talent Management and Corporate Workforce Strategies in the Public Service Agency. Ministry-specific results will be shared with the identified ministry key contacts (DMO and/or ministry Human Resources) to inform ministry leadership development 
•	Data will be provided for DMC/ DMCPSR to inform executive succession and development strategies, programs and activities
•	Now that the SLR process is complete, please encourage the senior leader to target their learning and development plan, goals, and actions to support their career aspirations and readiness to compete for an executive role 
•	You will receive a PDF copy of this form after the SLR process closes on January 27, 2023. If you prefer a copy beforehand, you can download a PDF for your files using the “Print as PDF” button on the top right of the form. We encourage you to share it with the senior leader
•	If you have any questions, please contact [Jodi Little, Leadership Development and Succession Lead](mailto:jodi.little@gov.bc.ca)

**Comment by iman-jamali-fw** [comment]
@HasanSifat Ready for test on DEV

**Comment by HasanSifat** [comment]
tested successfully in DEV 

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/6b11da97-50a9-470e-85ad-c0e87169b1a6)

**Comment by HasanSifat** [comment]
@iman-jamali-fw One more change has been made to the copy. Please refer to my last comment. Pulling this back to in progress

**Comment by iman-jamali-fw** [comment]
@HasanSifat Ready for testing on TEST

**Comment by HasanSifat** [comment]
@iman-jamali-fw update to copy- 

Thank you for your commitment to supporting senior leadership and executive succession.

•	The information you’ve provided will be shared with Executive Talent Management and Corporate Workforce Strategies in the Public Service Agency. Ministry-specific results will be shared with the identified ministry key contacts (DMO and/or ministry Human Resources) to inform ministry leadership development.
•	Data will be provided for DMC/ DMCPSR to inform executive succession and development strategies, programs and activities.
•	Now that the SLR process is complete, please encourage the senior leader to target their learning and development plan, goals, and actions to support their career aspirations and readiness to compete for an executive role.
•	You will receive a PDF copy of this form via email. A PDF copy can also be downloaded using the “Print as PDF” button on the top right of the form. We encourage you to share it with the senior leader.
•	If you have any questions, please contact PSA.SeniorLeadershipReview@gov.bc.ca

**Comment by HasanSifat** [comment]
Tested successfully in TEST. Ready to be deployed to PROD
