### ISSUE TITLE
SL Review: Remove entries of SL review form from task tab

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#636]
**User Story**
As an ADM, I don't need to see any entries of the SL review form in the tasks tab as it adds more confusion.

**Tasks**

- [ ] Remove entries of SL review form in the tasks tab, leave the Telework Agreements

**Acceptance Criteria**
when the task above is complete

**Comment by bhumin-fw** [comment]
SL review submitted from 24th Oct and onwards won't be displayed in the tasklist under the task tab. Changes Pushed to DEV.

**Comment by JodiLittle** [comment]
Approved

**Comment by HasanSifat** [comment]
tested successfully in TEST
