### ISSUE TITLE
TELEWORK: Extend duration from 30 to 60 days for an ADM (or delegate) to complete a request

### ISSUE THREAD

**Issue by Abuchana** [bcgov/digital-journeys#646]
User Story:
As an ADM (or delegate) I want to have 60 days to approve or deny a Telework Agreement submission so that I have enough time before it expires so employees won't have to fill out another one. 

Tasks:
- [ ] Extend duration from 30 days to 60 for ADM response
- [ ] Test to ensure the change is functioning properly
- [ ] Change all corresponding copy that refers to 30 days, to 60 days

Acceptance Criteria:
When the duration for an ADM (or delegate) to respond to a Telework Agreement is 60 days

**Comment by MeghanStothers** [comment]
Duplicate ticket
