### ISSUE TITLE
SL Review: Send email to ADMs after final submission

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#648]
**User Story**
As an ADM i want to get an email after final submission so that I have a record of what was submitted 

**AC**

- [ ]  ADMs to get an email with each submission after final submission 
- [ ] Email should contain the PDF of the form

**Comment by HasanSifat** [comment]
Copy for email- 
The   Senior Leadership Review (SLR) process is now over. Thank you for completing the form(s) for your senior leader(s). Shortly, you will receive an email with a PDF copy of the form(s) you have completed l for your records. we encourage you to share it with the senior leader(s). 
The information you’ve provided will be shared with Executive Talent Management, Corporate Workforce Strategies in the Public Service Agency, ministry strategic human resources (ministry-specific data), and DMC/DMCPSR to inform executive succession and development strategies, programs and activities.
Now that the SLR process is complete, the senior leader can target their learning and development plan, goals, and actions in support of their aspirations and readiness to compete for an executive role.
Since the Senior Leadership Review is a biennial process, there will be opportunities in the future for other senior leaders in your organization who aspire to executive roles to participate in the SLR process.
If you have any questions, please contact [Jodi Little, Leadership Development and Succession Lead.](mailto:jodi.little@gov.bc.ca)

**Comment by iman-jamali-fw** [comment]
@HasanSifat  Some questions:
- When you say "ADM to get 1 email with pdf attachments of **all submissions** made by the ADM." By **"All the submissions"** do you mean each time ADM clicks "Submit for Validation", we should attach a copy of that submission in the email? We currently update the submission each time ADM clicks "Submit for validation" and then clicks "Final submission". So we only have the final version to attache wants to change that.

- For deletion of "all drafts", do you mean SL Review's drafts that were never submitted? Currently, we delete the ones that ADM actually submits.

- "ADMs cannot come back and edit their submissions", do you want the submissions will be kept in the "submitted forms" tab just not editable thereafter?

**Comment by HasanSifat** [comment]
What do we do about forms that were in draft, after Jan 27 deadline?
What do we do about submitted forms after Jan 27 deadline?

**Comment by HasanSifat** [comment]
make custom group for late submitters and make form accessible to that group after Jan 27 deadline

**Comment by MeghanStothers** [comment]
@JodiLittle Jodi to give PSA team a few week's (or more) notice to add names into Key Cloak - two weeks minimum but three weeks is better.

**Comment by MeghanStothers** [comment]
UPdated wording from Jodi:
1.	Follow up email after final submission:



The Senior Leadership Review (SLR) process is now over. Thank you for completing the form(s) for your senior leader(s). Shortly, you will receive an email with a PDF copy of the form(s) you have completed for your records. We encourage you to share it with the senior leader(s).
The information you’ve provided will be shared with Executive Talent Management and Corporate Workforce Strategies in the Public Service Agency, ministry SLR key contact (ministry-specific data), and DMC/DMCPSR to inform executive succession and development strategies, programs and activities.
Now that the SLR process is complete, the senior leader can target their learning and development plan, goals and actions in support of their aspirations and readiness to compete for an executive role.
The Senior Leadership Review is expected to occur every two years and there will be other opportunities for other senior leaders to come forward in future processes.
Expect us to contact you with a survey about your experience with this SLR process. 
If you have any questions, please contact the SLR Team

**Comment by Stella-Archer** [comment]
@Andrew-Vargas-bcgov how do we test the final submission email and message?
In TEST nothing happens, and in DEV I get the "Almost Done" message with last years date and no email
![FinalSubmissionFAIL.gif](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/a3ca9d39-d212-4228-9abc-f543f82618e9)
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/a8ff5956-0e3e-4755-a2a2-7c3e25ddf744)

**Comment by MeghanStothers** [comment]
@Stella-Archer is this one that Iman could pick up? or is this one not needed?

**Comment by Stella-Archer** [comment]
**The final email message has been updated:** 

**[Insert ADMs name]**,

Attached is a PDF copy of the Senior Leadership Review submission for **[insert senior leaders name]**. Please save it for your records and share it with **[insert senior leaders name]**. Note that the file will be deleted from the system on November 10, 2023.
The senior leader can utilize this information to shape their learning and development plan, inform goals, and actions to support their career aspirations, and build readiness to compete for an executive role.
Thank you for participating in the Senior Leadership Review process. If you have any questions, please contact the **SLR Team**.

**Link "SLR Team to** :
mailto:PSA.SeniorLeadershipReview@gov.bc.ca

**Comment by Stella-Archer** [comment]
Late breaking update to the above:
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

[Insert ADMs name],
Attached is a PDF copy of the Senior Leadership Review submission for **[insert senior leaders name]**. Please save it for your records and share it with **[insert senior leaders name]**. Note that the file will be deleted from the system on December 5, 2023.
The senior leader can utilize this information to shape their learning and development plan, inform goals, and actions to support their career aspirations, and build readiness to compete for an executive role. For their development, the senior leader can consider:
•	targeted experiential and exposure opportunities
•	formal ministry learning opportunities (e.g., in-house leadership development programs)
•	formal or experiential corporate learning opportunities such as senior leadership courses, confidential coaching services and career support services. 
Thank you for participating in the Senior Leadership Review process. If you have any questions, please contact the **SLR Team**.


,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
*note new bullets added

**Link "SLR Team to :**
mailto:PSA.SeniorLeadershipReview@gov.bc.ca

**Comment by Andrew-Vargas-bcgov** [comment]
added to dev. will move to test in the morning.

**Comment by Andrew-Vargas-bcgov** [comment]
moved to test

**Comment by ayushdamani** [comment]
Tested and verified working!

![Screenshot 2023-05-26 092932.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/558fecce-3d0d-4139-a96b-d6bd5a1ff385)

**Comment by Stella-Archer** [comment]
@Andrew-Vargas-bcgov 
we need to add some links as highlighted below
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/3fd361eb-ef09-4f44-9069-fa1221256014)
* [ ] senior leadership courses 
Link > https://learningcentre.gww.gov.bc.ca/learninghub/?s=Senior+leader&post_type=courses
* [ ] confidential coaching services 
Link > https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/career-development/coaching-services#services
* [ ] career support services
Link > https://www2.gov.bc.ca/gov/content/careers-myhr/all-employees/safety-health-well-being/health/efas/career-services

**Comment by ayushdamani** [comment]
Tested and verified updated ✔️
- added links works 

![Screenshot 2023-05-29 092505.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/e13ef02b-6bc4-4aac-b591-0ed4a4fecfbf)

**Comment by Stella-Archer** [comment]
Brilliant! I've tested all the 3 new links - love the name differentiation too
PO Approved & Closing this tix
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/4f50803f-af07-4d7d-a35a-85c6c7e14a30)
