### ISSUE TITLE
Telework: Change expiry date from 30 days to 60 days

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#649]
“As an employee/manager or delegate submitting and completing a Telework agreement, I would like the expiry date to be change from 30 days to 60 days to allow enough time for the approvals and to avoid having to re-do my agreements.” 

**Tasks**

1) Note all areas where we’d need to adjust the “30 day expiry” language (in the tool instructions, in the confirmation emails and in the comms/content on Careers & MyHR). We’d also need to look at the PIA to make any adjustments there.
2) Stakeholder outreach: Asses technical work required as a dependency with consultation with stakeholders to making this change (comms, etc.)
3) Timeline: Ensure this work/change doesn't interrupt other work, such as SL launch  

The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.

**Comment by MeghanStothers** [comment]
PIE/Rueben requested the change and Sean Gadsby also reported he has no concerns and will be available to review content updates or others as required. 

As devs and PSA team to consider best timeline of this work - not a priority, but possibly just after/around SL launch

**Comment by MeghanStothers** [comment]
closed related 646 ticket as it is a duplicate

**Comment by MeghanStothers** [comment]
Reviewed PIA with Hasan and Nas - meeting with PSA Privacy next week.

Working with Stella/Chris to identify where we need to adjust language in the tool, content. etc. and plan the timing for when we will make the changes - related to the upgrade of the tool which will bring in new features as well as to SL launch

**Comment by HasanSifat** [comment]
Camunda model for telework updated in DEV. Submissions now expire in 60 days. Emails updated as well

**Comment by Stella-Archer** [comment]
This looks good we've checked all the emails and messages @simensma-fresh how would we test it technically expires?

**Comment by HasanSifat** [comment]
release complete! Deployed to PROD
