### ISSUE TITLE
Set up automated backups of MongoDB instance

### ISSUE THREAD

**Issue by simensma-fresh** [bcgov/digital-journeys#65]
**Description**
As a user of the platform, I want my form submissions to be backed up so I don't lose my submissions to the void if for any reason the DB storing them failed.

**Acceptance Criteria**
- Daily backups for the MongoDB instance are set up using the BC Gov backup container: https://developer.gov.bc.ca/Backup-Container
- Alerting is set up to alert a defined list of people if the backup fails
- Monitoring is set up so a administrator can see whether or not a backup succeeded for the given day
- Backups are stored on an OpenShift volume using the netapp-file-backup storage tier

**Note**
Feel free to suggest any appropriate tools for Alerting/Monitoring. This can be anything from notifications to a RocketChat channel to a Dig dashboard.

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh Is this in place already? If not, do you know if we can leverage the same (or similar) backups as on Moodle, Performance, etc.?

Maybe just try to provide or validate the estimate here if you can. I realize it may be a while before you can get to it.

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus I believe this is not in place yet.  Yes, the solution should be on the lines of what we implemented for Moodle, Performance.  
The estimate would be about 2.5 weeks for DEV, TEST and PROD including setting up the backups and testing the process.

**Comment by Abuchana** [comment]
@kkapoor-fresh and @warrenchristian1telus, can you indicate whether this is something that still needs to be done and if so, who, how, and when? If not, can you close it?

**Comment by kkapoor-fresh** [comment]
@Abuchana The mongo DB backups are up and running in Dev, Test and Prod. So, we should be good to close this ticket.

**Comment by Abuchana** [comment]
@kkapoor-fresh, thanks. Kunal, I'll close it!
