### ISSUE TITLE
Confirmation of Telework Not Working - New mechanism was added for showing confirmation page to SL Review, update Telework Form as well. 

### ISSUE THREAD

**Issue by MissionT** [bcgov/digital-journeys#655]
Background: Ticket 559 - ADM approval document should not be required when a supervisor denies a 3+ telework request. The process should include the supervisor's decision first to deny the request without having to go to the ADM.  Validation code was updated in the telework agreement to check for 'approved' submissions only. Logic works correctly (Confirmed by devs), however the issue is now a redirect issue caused by the recent confirmation page logic that was added to the SL Review Form. 
** Current state now - telework form does not close, no confirmation page loaded. (email is sent in the background)
 
Steps to Reproduce: Select the Submit button to Telework submission, confirm confirmation page loads. 
 
Actual Behavior:1. Employee fills out the telework form, selects Submit, the confirmation page load, sends an email and the form closes. 
 
Expected Behaviour: a new mechanism was added for showing confirmation pages, this was missed in the Telework approval/denial stage. Please updated for confirmation page to load correctly after the employee selects the submit button. 
 
Environment: Dev Env.

**Comment by HasanSifat** [comment]
Ready to move to test

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
