### ISSUE TITLE
Telework in the `Review and Process Form` tab is not loading properly when first open - unless page is refreshed

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#665]
**Issue**
Once a manager tries to open an employee's submission under `Review and Process Form`, the loading overlay not going away and the manager cannot edit the submission. If refresh the page, the submission will be shown properly and the manager can edit that submission.

**Comment by Stella-Archer** [comment]
Noo Issues now seems to be work just fine

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
