### ISSUE TITLE
Telework: v5.0 all changes to emails to employee/manager

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#669]
All changes related to the emails being sent to employee/manager 

Need to investigate camunda workflow to identify all use cases of emails

**Comment by MeghanStothers** [comment]
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/4497f2f6-798f-4762-af3e-33ea18a780c5)

**Comment by HasanSifat** [comment]
All changes required identified in this doc- https://bcgov.sharepoint.com/:w:/t/03991/EU2-drPQs9lCqlx-sHS3yCcBcGTjoMrVTLtkpV59C2lhiQ?e=Yh1ABy

meeting with Iman  on Tuesday to apply changes

**Comment by Stella-Archer** [comment]
All options have been tested. One issue with the employee Confirmation page identified - a new ticket has been created to fix this this can be moved to PROD now

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
