### ISSUE TITLE
Telework: Signature box name change

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#670]
As a user, I want to be clear about what is needed to complete and submit my Telework agreement.

- [ ] Make edits in the tool required related to usability in the "Signature" box in the Telework form

**Comment by MeghanStothers** [comment]
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/e04b188d-bdf1-42fb-baac-f7b1c9e8f65c)

**Comment by HasanSifat** [comment]
updated in DEV and TEST-

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/0eacef2c-f4ac-4833-a4ae-fe4cd11087a0)

**Comment by Stella-Archer** [comment]
This looks great ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/6c717137-777d-440a-8088-09cf6aa240e4) ready for PROD

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
