### ISSUE TITLE
SL Review: Auto Save for Submitted Forms

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#671]
**User Story**
As an ADM I should have a consistent experience with respect to auto-save in drafts & submitted forms, so that I do not mistakenly lose changes when I am editing the submitted forms. 

**Acceptance Criteria**

1. Submitted form autosaves when edits are made. i.e edits are available when the form is re-accessed even if the form isn't submitted.
2. Only the last submitted form should be sent to ODS (?)(TBD)
3. The form should still be in submitted forms tab (?)(TBD)

**Comment by HasanSifat** [comment]
Moving edited "submitted forms" back to Draft forms will be technically complicated. Devs to do a spike test and do some initial exploration. Submitted forms are not to be going back to "draft forms" tab.

**Comment by iman-jamali-fw** [comment]
@MeghanStothers @JodiLittle @Stella-Archer (I didn't find Eddie's username on Zenhub). Could you let me know which option you'd like me to move forward with regarding this ticket? There are two options that Fazil mentioned in the Team, you can find that in the link below:
https://teams.microsoft.com/l/message/19:35af534929d640a2bd94cbd20f650a5c@thread.tacv2/1666978250706?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=b4f3d2e7-7ee8-4f52-a981-039d66932eb3&parentMessageId=1666978250706&teamName=External%3A%20Digital%20Journeys%20Project&channelName=SL%20Review&createdTime=1666978250706&allowXTenantAccess=false

**Comment by HasanSifat** [comment]
@iman-jamali-fw the team has decided to go with option 2- We can also implement a manual save button in submitted forms. For consistency, we can also do the same in draft forms. To prevent accidents in the draft form we can keep the autosave on in the background, but not notify people about the autosaves. The instruction would be to save the form manually.
	
This way the instructions would be consistent in draft & submitted, manual save options in both, but in draft forms we will still continue to autosave to prevent any accidents.

**Comment by iman-jamali-fw** [comment]
@HasanSifat Some questions on this ticket:

**Initial submission page:**
What happens when a user clicks save terms of navigation and messaging?

**Draft page**
Do we need a save button at all?

**Submitted form page**
What happens after a user click save in terms of navigation and messaging?

--------------------

**For Telework**
Do we want the manual save button? If so, only in the initial submission page?

**Comment by HasanSifat** [comment]
Answers- 

**Initial submission/draft submission pages:**
Green popup window with this message- "Submission saved to Draft Forms" 
Navigation- Stays on that particular form 

**Submitted form page**
Green popup window with this message- "Submission saved to Submitted Forms" 
Navigation- Stays on that particular form 


**For Telework**
Do we want the manual save button? If so, only on the initial submission/draft submission pages?
No manual save button is needed for telework (new form or draft). The form auto-saves by itself and there is not edit feature for telework in submitted forms.

**Comment by iman-jamali-fw** [comment]
@HasanSifat Do you mind reviewing this on the `Senior Leadership Review Form` on TEST and letting me know if there is anything else that needs to be changed apart from messaging? Thank you

**Comment by HasanSifat** [comment]
@iman-jamali-fw I tested this feature and the changes are holding/being saved in the submitted forms section for that particular leader's submission. However, the green popup box says "Saved as Draft". For the submitted forms section, we want the popup to say "Saved to Submitted forms". 

Howver, from the draft orms section, if save button is clicekd the messag needs to stay as "Saved to drafts"

**Comment by HasanSifat** [comment]
tested successfully in TEST! ready to be transferred to PROD
