### ISSUE TITLE
TOOL: Release Note for v5.0 release to PROD (GO LIVE NOV 9)

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#673]
A popup window clearly listing out all the changes to the tool and additions made. 

Tentative List of things to cover in the release note- 
1. draft forms tab
2. Forms tab
3. submitted forms tab 

Acceptance Criteria
* When I log in as a forms user, I get a popup displaying the latest release notes
* When I log in as a forms user for the second time, I do not get  a popup with the latest release notes
* A dev can toggle whether or not a release note should be *active* (displayed to the user)
Design requirements: (see example below)

BC sans font
Visually similar to the release note in the PDP tool

**Comment by HasanSifat** [comment]
https://bcgov.sharepoint.com/:w:/t/03991/Efd9ryRGQIdHpybYCdKTwsgBwJpGTeKE15Xil6BkcO4Cwg?e=U25fuY

**Comment by MeghanStothers** [comment]
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/277b86ff-9a3b-425f-a8a8-e07d0dfa04f6)

**Comment by MeghanStothers** [comment]
@iman-jamali-fw Hi Iman can we connect about this rerlease note after you've had a chance to review the ticket details?

**Comment by iman-jamali-fw** [comment]
Hi @MeghanStothers, sure. Wondering if it's helpful to include @bhumin-fw as we (devs) had a sync-up this morning and reviewed the technical side of this ticket. Either @bhumin-fw or I might pick up this ticket depending on our workload.

**Comment by MeghanStothers** [comment]
Bhumin working on it - almost done. Will move to QA tomorrow if possible. 
Top priority to launch

**Comment by bhumin-fw** [comment]
@HasanSifat @MeghanStothers  @Stella-Archer I have deployed code for release note on DEV and testing some details. You will see it once when you login and navigate to forms page. Please review on your end and try to take screenshot for further discussion. I'm attaching screenshot of it to review in-case you missed it. (FYI: We can make changes in it's content and make it re-appear for all users).
![image.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/cf9aacf8-a9eb-484e-a426-3423a535aa64)

**Comment by HasanSifat** [comment]
one minor issue we noticed, the release note is showing up only when users are landing in the forms tab page. Managers, who are directly being taken to the review forms tab is not seeing the release note. 

@bhumin-fw

**Comment by MeghanStothers** [comment]
@HasanSifat - should I add create a new ticket to add the release note to show on all pages and not just the "forms" tab?

**Comment by HasanSifat** [comment]
@MeghanStothers Sure go ahead, a new ticket so that the release note shows up on all pages. 

One more concern before closing this particular ticket. @bhumin-fw made this release note feature a part of the forms designer interface. A walkthrough or step-by-step notes for recreating this for future forms would be a required form of documentation. Which is why i brought this back to the review pipeline

**Comment by bhumin-fw** [comment]
@HasanSifat 
I have enabled the release note popup accessible from all the pages. Deploy change on DEV and TEST. (Hard refresh is required to apply new changes, else if you land on the form page before hard refresh it will pick the old code only).

Regarding Doc,
I have added the document, You can view it here for now https://github.com/bcgov/digital-journeys/blob/Docs-for-release-note-module/docs/ReleaseNote/index.md.
In this document, the Designer and the Developer get to know how to add new a release note. Also added sample files for the designer and the developer for reference.
