### ISSUE TITLE
TOOL: Reintroduce back button from forms to forms tab

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#676]
- [ ] Reintroduce back button from forms to forms tab
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/f0ed4acc-1fe4-4c59-bb03-f099382d9de7)

**Comment by MeghanStothers** [comment]
@HasanSifat @Stella-Archer Do you think this "back button" is essential MVP for launch? If so, can we assign it to a dev in the next sprint?

**Comment by Stella-Archer** [comment]
Could we have the arrow in black and aligned?
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/a75abf7d-a900-469d-bb48-0d7d94a62032)

**Comment by bhumin-fw** [comment]
@Stella-Archer for sure. Right now it's default and the same in the draft and submitted page too. I should change those too, right?

**Comment by Stella-Archer** [comment]
Yes please :) thanks @bhumin-fw

**Comment by Stella-Archer** [comment]
Sweet this looks terrific @bhumin-fw !
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/cf7c491f-57ac-4395-b6bd-9e8af5543ac7)
Good to move to PROD

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
