### ISSUE TITLE
[Question] - Help required to evaluate formsflow ai for NSGov

### ISSUE THREAD

**Issue by dinbtechit** [bcgov/digital-journeys#681]
I'm a manager from NSGov - Emerging platforms team. We are evaluating forms-flow-ai for the Nova Scotia province. I stumbled upon this repository and found that there are some openshift templates in the repository that we could leverage. 

https://github.com/bcgov/digital-journeys/tree/main/deployment/openshift

I am looking for some directions on deploying on openshift. Are you able to provide some steps to deploy the Database (MongoDB, postgres, redis) and  forms-flow (analytics, forms, webapi and web)

I have a project & namespace in openshift. I tried to deploy the MongoDB secrets template getting the following error. (It does not appear to look like a valid openshift template.) 

```
$ oc process -f mongodb-secret.yaml --parameters -f mongo-db_param.yaml

error: failed to read input object (not a Template?): unable to decode "mongo-db_param.yaml": couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

Cheers!

**Comment by fazil-ey** [comment]
Hey, Please go to BC Dev Exchange to get help with this issue. Thank you!
