### ISSUE TITLE
[Telework]: Update: front end "Before you begin" section

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#682]
**User Story**

“As a user I want accurate up to date instructions reflecting the new 5.0 workflow and features so I can get manage my submission properly.” 

**Tasks**
Steps needed to achieve this feature. 
Delete second bullet 'this agreement must be finished in one session"
Edit second Button "You can save your progress, it will be auto saved to the drafts folder"
New Bullet after "your session will time out..." "if you supervisor does not  process this telework agreement in 60, it will expire in this system."

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.

**Comment by fazil-ey** [comment]
This is done through the release notes feature
