### ISSUE TITLE
Telework: Update before you begin section

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#683]
**User Story**
“As a telework user I want accurate and up to date instructions reflecting the new features and flow of the 5.5 release so I can get understand how the new feature impact my work.” 

**Tasks**
-  Delete 2nd bullet "This agreement must be finished in one session
-   Replace 3rd bullet "You can not save your progress' with "Your progress will be automatically saved to the the drafts tab until you submit the agreement
-   New bullet after "your telework agreement is valid for...." "If your manager does not process your telework agreement in 60 days it will expire from this system"
![Before you begin messages.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/190b43df-c04b-454b-a428-a532ae6e7eba)

**Acceptance Criteria**
Edits are are entered as above

**Comment by HasanSifat** [comment]
changes have been added to DEV and TEST- 

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/e21d366a-5b4c-4838-a797-62afaa9cbcdf)

**Comment by Stella-Archer** [comment]
This looks terrific good to move to PROD ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/ca9442fe-917f-4f40-b60d-60bc26c6fbce)

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
