### ISSUE TITLE
TOOL: Draft forms not getting deleted from table after delete button

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#687]
Background: When draft forms are deleted the entry is persisting in the draft forms table. **Potential impact to telework users**
 
Steps to Reproduce: go to the draft forms tab and click on delete. After confirmation, the entry to the deleted draft form needs to disappear 
 
Actual Behavior: The entry is persisting. If clicked on edit on the deleted entry it's taking users to an error 404 page. 
 
Expected Behaviour: the entry on the table needs to get deleted as well.  
 
Environment: DEV/TEST

**Comment by iman-jamali-fw** [comment]
@Stella-Archer This is ready for testing on TEST.

The fix has been applied to both drafts and submitted forms, so for testing please test deleting drafts and the submitted SL Review forms.

There is also an update to the Telework confirmation page after employee submission, changing 30 days to 60 days in one of the bullet points.

**Comment by Stella-Archer** [comment]
@iman-jamali-fw works great for draft forms in test ![4E48302F-1D71-4F69-9E96-F8562B5AACC5.GIF](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/b90f3198-2706-4133-9ed9-48392dcf2e15)

**Comment by Stella-Archer** [comment]
@iman-jamali-fw I don't have access to the SL leaders form in TEST so can't test the summitted form delete ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/a04c87db-8dd1-4405-b8fd-fcbeac3cacb0)

**Comment by iman-jamali-fw** [comment]
@Stella-Archer  No worries. I added you to the ADM group. Could you try again to see have access?

**Comment by Stella-Archer** [comment]
Thanks @iman-jamali-fw I can access and deleting the submission worked fine > ![5274CCE9-0199-4D82-94B3-85F12D7BC2C8.GIF](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/a541aef1-3639-4d0e-a6fb-0b27a656fd68)

**Comment by HasanSifat** [comment]
successfully tested in PROD. Closing ticket
