### ISSUE TITLE
1.10 Form: Orientation for Business Area team

### ISSUE THREAD

**Issue by Abuchana** [bcgov/digital-journeys#690]
User Story:
As a form owner who is beginning to work with the Digital Journeys team, I want to be oriented to all the tools, processes, and people that are involved with creating a form so it goes as smoothly and efficiently as possible. 

Please use the checklist located at this link: 
https://bcgov.sharepoint.com/:w:/t/03991/EU42xBTq16RGgV736tkbA9kBAQm50xnRA1G52NIMM1_Wmg?e=GqGP1d

**Comment by HasanSifat** [comment]
Aiming for 14/15 of November to get ER 1.10 team into scrum and all other agile meetings.
