### ISSUE TITLE
KEYCLOAK ISSUE - AUTHENTICATION ERROR LOGIN

### ISSUE THREAD

**Issue by MissionT** [bcgov/digital-journeys#697]
Background: a supervisor/manager attempts to review/approve an employee's telework agreement via the link generated in the 
 employee's confirmation email. Once the link is selected, the user logins, following this, an error message appears:   "PSA-DIGITAL JOURNEY" We are sorry.... Unexpected error when authenticating with identity provider.  The supervisor is unable to have their IDIR and password authenticated. 
 
Steps to Reproduce:   Supervisor to follow the employee's confirmation email link to login, review and approve or deny the telework agreement. Anomaly - this error message happens occasionally and it not a persistent problem with most users.  
 
Actual Behavior:  Error message is generated after the supervisor tries to access the confirmation email located under the: After obtaining proof of ADM (or delegate) approval section of the email. 
 
Expected Behaviour: Supervisor is taken their task list to review and approve/deny telework agreements vis the confirmation email link. 
 
Environment: Prod env.

**Comment by MissionT** [comment]
[Uploading... Online Telework Agreement - Access Error697.msg][https://app.zenhub.com/files/439477060/a4315147-3f59-4ae9-83a6-f80ae7f760ec/download](https://app.zenhub.com/files/439477060/a4315147-3f59-4ae9-83a6-f80ae7f760ec/download)

**Comment by Abuchana** [comment]
@MissionT it looks like we have duplicate tickets for this issue, #697 and #653

**Comment by MissionT** [comment]
I'll close this. Thanks Chris
