### ISSUE TITLE
The user's name is no longer displayed after logging in to the app after branding is applied

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#70]
**Background:** The user's name/role is no longer displayed on the right side of the header after logging in to the app.

**Environment:** Dev

**Steps to Reproduce:**

1. Log in to the PSA-Digital-Journey portal on test with valid credentials.

**Actual Behavior:**  The user's name/role is no longer displayed on the right side of the header after logging in to the app.

**Expected Behavior:** The user's name/role should be displayed after logging in to the app. 
Last Name, First Name
Role

**Comment by MeghanStothers** [comment]
@HasanSifat Can you test this one to see if it is still happening? This looks like an old ticket. 
We'll want to test in all three environments

**Comment by HasanSifat** [comment]
@MeghanStothers User name and role are still not present when logged into all 3 of the environments. 

Currently, the header has Digital Journeys as the title and a "Sign Out" button on the left hand. 
![ss4.JPG](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/cd4f690e-b718-4a18-ac30-4d157fe9c1bc)

**Comment by alexandralloyd** [comment]
Still not present in all three environments.

**Comment by Abuchana** [comment]
@Stella-Archer can you add an estimate to this tickets?
