### ISSUE TITLE
Hide Back button and duplicate "Print PDF" button on task tab for editable form.

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#704]
The telework form can be edited by the manager in the task tab. Such forms contain the same details from the "application/submission" edit page.

Acceptance criteria
- [ ] Hide the backlink and edit the icon in front of the form name.
- [ ] Remove duplicate "Print As PDF" button.

Please find attached a screenshot for reference.
![image.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/52d07f30-e43c-474c-a4a0-042b79a8cc5b)

**Comment by bhumin-fw** [comment]
@HasanSifat It's ready to test on DEV and TEST environment.

**Comment by HasanSifat** [comment]
tested successfully in TEST. Ready to be transferred to PROD
