### ISSUE TITLE
[DUPLICATE]TELEWORK: 2 Print as pdf button in Review forms tab

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#705]
Background: 2 print as pdf buttons in review forms tab
 
Steps to Reproduce: 

- submit a new telework form to a manager

- sign in to DJ as manager and go to review forms 

- open new submission

 
Actual Behavior: the review forms tab is showing 2 print as pdf buttons for a submission- 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/3d4f2d94-de24-4175-95e8-75e8c8fe0029)
 
Expected Behaviour: there should just be 1 print as pdf button
 
Environment: PROD

**Comment by bhumin-fw** [comment]
@HasanSifat I have fixed it and deployed it on DEV and TEST. Log the below ticket. Let's keep only one ticket and move it to the review/QA tab.
https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/bcgov/digital-journeys/704

**Comment by HasanSifat** [comment]
oh sweet, thank you! did not notice that we already had a ticket related to this. I'll close this one
