### ISSUE TITLE
TOOL: Formsflow pdf naming 

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#706]
**User Story**
As a user (employee/manager) I want the downloaded pdf from the tool to be named in a way that it makes sense. Currently it downloads as form-exported-xxxxx.pdf

**Tasks**

- [ ] name the pdf same as the name of the draft 

**Acceptance Criteria**
When downloaded pdfs have the above formatted name

**Comment by bhumin-fw** [comment]
@HasanSifat I guess you missed the suggested "PDF name" format in the task.

**Comment by HasanSifat** [comment]
not sure what you are referring to @bhumin-fw

**Comment by bhumin-fw** [comment]
**"add a feature so that the pdf name is downloaded as"**

Above line missed "PDF name" suggestion.
- @HasanSifat

**Comment by HasanSifat** [comment]
@bhumin-fw can you send me a message in teams? Would be best to connect over a call on this

**Comment by bhumin-fw** [comment]
@HasanSifat I do not have access to the BC Gov Team.

Attaching a screenshot if that shows the correct point, of what I'm asking. If not could you please add the meeting in teams, I'll get invited in EY email and can jump on a meeting.
![image.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/f6c16faa-05a1-4358-9ce2-5da427d678a5)

**Comment by HasanSifat** [comment]
my apologies lol, i added the criteria with closed brackets. Updated the ticket now and should be visible

**Comment by iman-jamali-fw** [comment]
@Stella-Archer Please let me know if this format for the name of the pdf is what you're looking for:

- When the name field is populated in a form: `formName-Name`. For example: `Telework-iman_jamali`, ` Senior_Leadership_Review-hasan_sifat`.
- When the name filed is not populated: `formName-uniqueNumber`. For example: `Telework-1670304466059`

**Comment by Stella-Archer** [comment]
Thanks @iman-jamali-fw , Yes formName-Name. For example: Telework-iman_jamali, Senior_Leadership_Review-hasan_sifat. make sense 
but I'm wondering if a name field is not populated instead of a random number we could amend it with current date 'Telework-2022-12-08' as I think if a user was downloading/saving a blank form they'd at least have reference to when the downloaded that version, which would be more helpful than a random number

**Comment by iman-jamali-fw** [comment]
@Stella-Archer Thanks for reviewing the format. Sure, I'll replace the random number with the current DateTime.

**Comment by iman-jamali-fw** [comment]
@Stella-Archer Ready for test on TEST environment 😀

**Comment by Stella-Archer** [comment]
SWEET! - good to go to PROD
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/283dd4c4-5974-4f77-8289-0ca54bba8ccd)

![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/72a2b59f-3198-486a-b44b-ad2751cdf389)
