### ISSUE TITLE
TELEWORK/TOOL: Form not autosaving 

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#707]
Background: The form is not auto-saving. Only when the save as draft button is clicked a draft form is saved in draft forms tab
 
Steps to Reproduce: 

- go to a new telework form. Fill in a few details and wait for it to save

- no auto-save prompts are made 

- go to draft forms tab and there won't be a new entry for the new submission in progress

 
Actual Behavior: Form does not auto-save
 
Expected Behaviour: Form should auto save with all changes made to the content 
 
Environment: PROD

**Comment by HasanSifat** [comment]
tried testing again, it's auto-saving now. Updates to follow

**Comment by HasanSifat** [comment]
the form is not auto-saving as i am making changes to the form, it auto-saves as leave the form and go to a different page/tab. It needs to auto-save as changes are made

**Comment by iman-jamali-fw** [comment]
@HasanSifat The auto-save feature is enabled and saves the form every few seconds, the user just doesn't see the green box ("saved") but the form indeed auto-saves in the background.

**Comment by HasanSifat** [comment]
@bhumin-fw can we bring back the prompt that used to show at the top right? it's slightly confusing to know if it is auto-saving or not if there is not prompt

**Comment by iman-jamali-fw** [comment]
We can if that makes sense in terms of UX. Currently, the auto-save indicator is hidden per @fazil-ey suggestion. We can make that enable again if it makes sense or shows the green box save the message on every auto-save.

![Screen Shot 2022-11-09 at 12.29.11 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/0cc3e1a4-9f05-4d07-a4a8-4e9dcd0cc085)

**Comment by HasanSifat** [comment]
Not required to have the auto-save prompt on the top right!
