### ISSUE TITLE
TOOL: Make top menu bar texts bigger

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#708]
**User Story**
As a user in DJ, I want the top-menu bar text size to be consistently the same size as all other text in the platform 
**Tasks**

- [ ] Make top menu bar text bigger

**Acceptance Criteria**
When the top menu bar buttons are more clear to users.

![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/4f2632b6-eb6b-497b-b37c-a92a272a96a8)

**Comment by bhumin-fw** [comment]
@HasanSifat 
Menu font size change to Websites' default value. It is slightly bigger than the previous one. Changes are available on both DEV and TEST. (Hard refresh is required to see the change)

**Comment by HasanSifat** [comment]
@bhumin-fw after discussion with the program team, We want the font size to go up another 2-3 levels.

**Comment by bhumin-fw** [comment]
@HasanSifat for sure, Increased font size to 3 levels. Changes Deployed to DEV and TEST.

**Comment by fazil-ey** [comment]
@bhumin-fw  I see the changes in dev but not test, the text is still small in test
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/507e2e2f-b2be-4383-a4a6-ddb06ed7abf1)

Dev in comparison -
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/5cc2852d-dd3e-410f-9028-01260086be10)

**Comment by MissionT** [comment]
Test env has large menu font  (Forms, Draft Forms...) than the current Prod env.  The larger text size looks great compared to the prior prod, smaller text size. 
Test env large menu size all good   - Confirmed.
