### ISSUE TITLE
1.10 Form: Usability review of draft form 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#716]
As a user who will use this form to lodge a complaint, I would like to access a concise digital form in plain language that helps me easily understand the information and actions needed. 

REVIEW/edits needed before the form is built in FormsFLow

link on teams:
https://bcgov.sharepoint.com/:w:/r/teams/03991/Shared%20Documents/1.10%20Formal%20Complaints/Joint%20Triage%20Intake%20Form%20-%20Nov%202%20DRAFT.docx?d=w4a3dc50d331f472396ab9dc41b74ad09&csf=1&web=1

**Comment by fazil-ey** [comment]
Completed the review. For the most part the form seems to be clear and straightforward.
However, in the form itself with how the questions are worded, it wasnt clear if someone can fill this on behalf of someone else or if they observe something happened to a third party.

**Comment by fazil-ey** [comment]
Had a discussion with Don, and action items have been noted on the draft copy of the form. Tickets will be created to address them as needed
