### ISSUE TITLE
SL Review: Grant access to ADMs 

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#717]
- [ ] Get the final list of ADMs from @JodiLittle by week of March 20

- List to have idirs, first name- last name, emails 

- [ ] DJ program team to add names to SL ADM group in PROD

**Comment by fazil-ey** [comment]
- Can we automate adding names? Bulk Upload? Yes but it needs work, break it into another ticket 
- Does it have to be done for each environment separately? - we only need a few people to test in TEST and everyone needs to be added to PROD

**Comment by fazil-ey** [comment]
Other SL tasks before release 
- [ ] Make form published 

- [ ] Change link to MS teams site to form in PROD

**Comment by MeghanStothers** [comment]
See #964 for info about the bulk/automated uploads - #964 is closed. This ticket relates to adding the ADM names when we have the final list.

**Comment by Stella-Archer** [comment]
@bhumin-fw Jodi has sent the list for the SL KeyCloak group I've uploaded it to our teams channel > https://bcgov.sharepoint.com/:x:/r/teams/03991/Shared%20Documents/SL%20Review/KeyCloak%20Security%20Group/Copy%20of%20Execs%20-%20Min%20Position%20Name%20Email%20May%203%202023.xlsx?d=w44a373c44a894ebfa698aa499279a9a7&csf=1&web=1&e=vvE9Oc
Could you check and confirm everything is ok and ready to upload with the bulk upload feature? thx

**Comment by MeghanStothers** [comment]
@bhumin - to move to test

**Comment by Andrew-Vargas-bcgov** [comment]
Test passed. Great work Bhumin :)

**Comment by MeghanStothers** [comment]
Tested and can be closed with Jodi's okay

**Comment by Stella-Archer** [comment]
PO Approved & Closed
