### ISSUE TITLE
TOOL: Migrate from Silver to Gold

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#721]
As a forms building team, we want to keep servers updated a.

Simen will be carrying out the deletion of Silver Integration #2311migration to Gold SSO for our production servers which was completed on Nov. 8th.

**Comment by Abuchana** [comment]
From: Sharma, Abhinav CITZ:EX <Abhinav.Sharma@gov.bc.ca> 
Sent: November 15, 2022 1:56 PM
To: XT:Christian, Warren CITZ:IN <warren.christian@telus.com>
Cc: ji.zhao@telus.com; Stothers, Meghan PSA:EX <Meghan.Stothers@gov.bc.ca>; XT:Smaaberg, Simen HLTH:IN <Simen.Smaaberg@ca.ey.com>; Samji, Zorin CITZ:EX <Zorin.Samji@gov.bc.ca>
Subject: RE: Action required: Delete silver integration #2311 and move to Gold services #3961

Good afternoon Warren,

Just checking in if you have any updates for us on the deletion of Silver Integration #2311?

Regards,
Abhinav

From: Warren Christian <Warren.Christian@telus.com> 
Sent: November 1, 2022 9:08 AM
To: BC Gov SSO Team CITZ:EX <BCGov.SSO@gov.bc.ca>
Cc: Samji, Zorin CITZ:EX <Zorin.Samji@gov.bc.ca>
Subject: RE: Action required: Delete silver integration #2311 and move to Gold services #3961

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.

Hello,

We have scheduled the migration to Gold SSO for our production servers on the evening of Nov. 8th.

I expect that the form for deleting the Silver integration will be completed a day or two later, following testing and verification procedures.

Just let me know if you have any questions or concerns.

Regards,

Warren Christian
Senior Full Stack Developer / Analyst, TELUS Health & Payment Solutions
T 1 250 686 1359
telus.com  Facebook  Twitter  Instagram  YouTube  LinkedIn

This email, including any attachments, is for the sole use of the intended recipient and may contain confidential information. If you are not the intended recipient, please notify us immediately and destroy this email and any copies.

From: BC Gov SSO Team CITZ:EX <BCGov.SSO@gov.bc.ca> 
Sent: Friday, October 28, 2022 10:23 AM
To: Warren Christian <Warren.Christian@telus.com>
Cc: Samji, Zorin CITZ:EX <Zorin.Samji@gov.bc.ca>
Subject: Action required: Delete silver integration #2311 and move to Gold services #3961

ATTENTION: This email originated from outside of TELUS. Use caution when clicking links or opening attachments. | Ce courriel provient de l'extérieur de TELUS. Soyez prudent lorsque vous cliquez sur des liens ou ouvrez des pièces jointes.

Hi Pathfinder SSO friend,

We see you have a silver integration #2311 and also a gold integration #3961
We'd love to see you delete your silver integration #2311 in our CSS App (https://bcgov.github.io/sso-requests) and move to gold going forward.

Next action:
1.	Please let us know the concerns/challenges for deletion of Silver integration #2311 . 
For example:
a)	No resources to delete Silver integration
b)	Don`t know the need to delete Silver integration after applying Gold integration
c)	Need both integrations for migration period / Requirement of both integrations for your applications
d)	Others (please specify)

2.	Request you to complete this action by Nov 5, 2022 or we can meet via Teams meeting.

Let us know if you have any questions.

Thanks,
Pathfinder SSO Team

From: BC Gov SSO Team CITZ:EX 
Sent: October 12, 2022 4:00 PM
To: XT:Smaaberg, Simen HLTH:IN <Simen.Smaaberg@ca.ey.com>
Cc: Samji, Zorin CITZ:EX <Zorin.Samji@gov.bc.ca>
Subject: Gentle reminder: Pathfinder SSO ask to delete existing silver integration #2311 and move to Gold services #3961

Hi Pathfinder SSO friend,

We see you have a silver integration #2311 and also a gold integration #3961
We'd love to see you delete your silver integration #2311 in our CSS App (https://bcgov.github.io/sso-requests). and move to gold going forward.

Please let us know if you have any questions.

Thanks,
Pathfinder SSO Team

From: BC Gov SSO Team CITZ:EX 
Sent: September 28, 2022 3:54 PM
To: Samji, Zorin CITZ:EX <Zorin.Samji@gov.bc.ca>
Subject: IMPORTANT: Silver Standard Clients -- Pathfinder SSO Community Update

Dear Current Silver Standard Clients
A friendly reminder about our offering of Gold standard services. We would like you to migrate your Silver standard integrations on the Gold standard by end of October, 2022.
What does this mean to you?
If you have a silver integration with us on our Common Hosted Single Sign on (CSS) App, then we need your help to create a new gold integration. You can see the Service Type in your Dashboard   
 
How do you create a gold integration?
1. Log in to the CSS App: https://bcgov.github.io/sso-requests
2. Create a new integration.
3. Develop and test with your application that uses our integration.

How do you migrate from silver to gold?
1. Once you are satisfied with your gold service integration (created above), please delete your silver service integration.
2. Drop us a quick note to let us know you've migrated all your environments.

Thank you for your support in this (sometimes complex) journey together.

- Your friends from the Pathfinder SSO Team.

Have any questions? We would love to hear from you.
RocketChat #SSO Channel
Via Email
Visit our wiki page
