### ISSUE TITLE
SL Review: Don't save if there is no Employee Name in the form

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#722]
**User Story**
As a Senior Leader I do not want the form saved if there is no name on the form so that there are no empty drafts saved unnecessarily

**Acceptance Criteria**

- [x] On clicking "Save Changes", show an error saying "Employee Name is required". Only Employee Name field should be validated on save. No other fields need to be validated.
- [x] No auto-save should happen if there is no name

**Comment by bhumin-fw** [comment]
@fazil-ey @Stella-Archer 
It is ready to test on DEV and TEST environment(It might need a Hard refresh).

**Comment by Stella-Archer** [comment]
seems to be saving with out assigning name in both TEST and DEV even after clearing cache @fazil-ey @MissionT are you having the same experience? ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/df2037a8-1011-4385-8354-abb511fd3357)

**Comment by bhumin-fw** [comment]
@Stella-Archer 
It is deployed on DEV and TEST. You might need to hard refresh to test these changes.

**Comment by Stella-Archer** [comment]
Nice work @bhumin-fw I love the red "employee name required' warning when I try to force the save with the manual save button!
