### ISSUE TITLE
SL Review - Employee name sometimes does not autopopulate

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#724]
**Steps to Reproduce:**

The bug is not consistently reproducible 

See video https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/SL%20Review/Error%20with%20autopopulation.mov?csf=1&web=1&e=tLKGj7
 
**Actual Behavior:**
Employee information fields do not show up and autopopulate 
 
**Expected Behaviour:**
Employee information fields do not show up and autopopulate 
or if there is an error, there should a message saying "Error fetching employee information, please refresh the page and search again"
 
**Environment:**
Test

**Comment by bhumin-fw** [comment]
@fazil-ey 
We have moved the script to "action event". If the custom script got frozen and produced this issue then this will solve it. (Thanks to SImen's suggestion here)
for today and tomorrow, Could you please keep an eye on it and update us if the same issue occurs again or not?
(Hard refresh is required)

**Comment by fazil-ey** [comment]
Looks good for now, I also notice the performance is slightly better. Will keep trying and report

**Comment by fazil-ey** [comment]
I ran into this again on Nov 24 in a draft form that did not have name.

**Comment by Stella-Archer** [comment]
@fazil-ey do we need to move the back to 'in progress' to have the DEVs look at it again or are we going to monitor it for a bit more?

**Comment by fazil-ey** [comment]
I checked again today, and it happened again. It happened the first time i got into the form in test after a long time. However, to handle this we can perhaps change the error message "Enter employee name e.g. Doe Jane is required. If you see a name in the field, please refresh the page and try entering a name again"

![Screen Shot 2022-12-08 at 8.56.35 AM.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/c845dba6-eb91-4838-9194-4cddabbf2a67)

**Comment by fazil-ey** [comment]
@Stella-Archer This issue isnt consistently happening, but is still happening occasionally. 

I think we should handle it in the error message, asking people to search for a name again if they are getting a validation error even when the name field is populated.
