### ISSUE TITLE
1.10: Explore methods to access form for non-IDIR users

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#726]
**User Story**
As a user eligible to lodge a 1.10 complaint, i should be able to access the form in the cases mentioned below so that I can submit the form whenever i need to. 

1. As a BC Public Service employee part of GEU/PEA union who has IDIR access
1. As a BC Public Service employee part of GEU/PEA union who does NOT have IDIR access because I am on leave
1. As a LDB employee who does not have IDIR access

**Acceptance Criteria**
- [ ] All 3 types of users have a way to access the same form on digital journeys
- [ ] We can authenticate that they are employees of BC Public Service or LDB

**Additional Questions/Notes**
1. Do LDB employees have an intranet where the link to this form can be placed that is not accessible to the public?

**Comment by fazil-ey** [comment]
Old AC from #130 

All forms should accessible for non-IDIR users as well as authenticated ones

If user is not logged in: support for viewing and submitting forms only

Accessed via a single link from BC Gov site:

If not signed in with IDIR already -> show page (login / I don't have an IDIR)
Make clear that by not using IDIR you need to fill out the full form
Same workflows for authenticated or unauthenticated users

Unauthenticated users can only submit forms, no other functions on the system

Unauthenticated users have to fill out a ReCaptcha

Formsflow has a public form option

embedding form into a webpage is another option

**Comment by simensma-fresh** [comment]
Some options to discuss:


*Public Forms*
- System already supports it
    - Would need some styling tweaks
- Increased risk of spam
- Increased risk of abuse of system

*Basic BCeID*
- Anyone can register
- Simple/quick sign up process
- No need for in-person verification
- Support System already in place

*Personal BCeID*
- Anyone can register
- Use by services where identity needs to be verified.
- 2 step registration process (online + in-person)

*BC Services Card*
- Secure Sign on for BC Gov residents
- Bar is pretty high for sign-up
- Only available for BC residents with BC Services Card

*Internal User Management*
- Username / password login within app
- Easily supported by KeyCloak

- Pretty big effort
- Privacy / Security risks
- Need support system (e.g. assisting with password resets etc)

**Comment by Abuchana** [comment]
Don doesn't know who the technical contact would be at LDB but thinks Lindsey Oreskovic (604-252-6244) may be able to help.

**Comment by fazil-ey** [comment]
**Notes from Nov 24**

**Options -** 
Action item - Arrange a meeting with IDIM @Stella-Archer 

- BCeID 
   - Personal BCeID - any BC resident can sign up for, caveat go to service canada centre before if you dont have one
   - Basic BCeID - anyone can sign up, caveat we will depend on LDB or PSA team to look at form data and verify who that person is
  - Who runs this?  IDIM as well 
  - is this email verified? If they use bc gov email while registering, there might be ways to merge the accounts for both IDIR & BCeID logins. Relevant for Mat/pat when people submit with IDIR and then go on leave.
  - Also find what data can we get about the user from that. To prepoulate fields
   - can we link with IDIR automatically? 
  - Has it been abused? Security concerns?  Privacy concerns if emails are not verified or are personal emails? 
- idea - attach BCeID in peoplesoft? 
      
- BC Services Card login like health gateway
   - More "Secure" as the person is verified 
   - How many people would not have this at LDB or those who are on leave? 
   - amanda sandberg for more info IDIM OCIO would help in onboarding 
   - If you havent used it before, you have to setup. Verification can take a day? 
   - You have to be BC resident - Are most employees BC residents anyway? 
   - BCID, BC services card, Driver's license
   - If you dont have one, it can take some time to get that card 
   - Fringe Cases  - just call? 
   -Also find what data can we get about the user from that. To prepoulate fields
   - can we link with IDIR automatically? 

- Point at LDB's existing authentication 
  - would not be scalable across all forms 
   - Find a contact to understand what they do now - ask Don Smallwood @Abuchana 
   - Also find what data can we get about the user from that. To prepoulate fields

Rejected Options - 
- Rejected because too much work to implement this ourselves - Create username/passwords on KeyCloak, we can do that since we have our own instance 
    - Managing passwords, forgot password  etc

**Comment by fazil-ey** [comment]
IDIR, LDB authentication, BCeID (leave)
