### ISSUE TITLE
SL Review - Change "Submit New" to "Start New" in forms tab

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#727]
**User Story**
As a Senior Leader I do want the form tab to say "Start New" instead of "Submit New" so that it is clear that the tab is only for starting new forms.
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/ee6bc9f5-a384-43af-8e16-03e687d1bab1)

**Acceptance Criteria**
- [ ] "Submit New" button name is changed to "Start New"

**Comment by Stella-Archer** [comment]
Nice! this looks great @bhumin-fw ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/4450e543-ebd8-4ab9-b428-8ce12476a754)
