### ISSUE TITLE
1.10: Copy for emails and section on the form

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#728]
Copy is required for the following items
- [x] "Cover page" section of the form
    - [x] Brief description on who this form is for 
    - [x] Brief description of the process
    - [x] Link to more detailed info 
    - [x] Privacy disclaimer
    - [x] How to contact for help
- [x] Information on next steps before submission in the form 
    - [x] Brief description of what to expect & next steps after form submission
- [x] Confirmation message after form submission
    - [x] Brief description of what to expect & next steps after form submission
- [x] Confirmation email after form submission to complainant
    - [x] Brief description of what to expect & next steps after form submission
- [x] Confirmation email after form submission to recipient
- [x] Email to be sent to PSA/LDB secure mailbox

**Comment by morezooomm** [comment]
[Digital Journey Virtual Team - Assignment 728.docx](https://github.com/bcgov/digital-journeys/files/10070662/Digital.Journey.Virtual.Team.-.Assignment.728.docx)

**Comment by morezooomm** [comment]
I believe copy has been provided for each of the above elements.
