### ISSUE TITLE
1.10: Create form in Formsflow

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#729]
Create a new form in the dev environment based on the specifications in this [document](https://bcgov.sharepoint.com/:w:/r/teams/03991/_layouts/15/Doc.aspx?sourcedoc=%7BFF97CF7D-81C1-40BB-9956-2DA678FE8F80%7D&file=Joint%20Triage%20Intake%20Form%20-%20Nov%2014%20DRAFT.docx&action=edit&mobileredirect=true&wdPreviousSession=45124d70-24d8-4fbc-adb5-5570572ce197&wdOrigin=TEAMS-ELECTRON.teamsSdk.undefined)

Key points - 
- conditional logic based on the screening questions 
    - show form only if member of GEU or PEA
    - If LDB employee, must be GEU 
    - If a witness to incident, then show information on how to report
- Complainants should be able to add upto 50 respondents
- Word limit on main description of incident - 2500 words
- Word limit on other contextual questions - 250 words

Form Features - 
- Autosave & edit drafts
- View submitted forms
- No workflow/approval process
- Data retention - ?

**Comment by fazil-ey** [comment]
We may not need to have the option to choose if a person is an LDB employee if they login through the LDB credentials

**Comment by MissionT** [comment]
Conditional logic added and will need to be tested. If the user selects 'other', the text that appears may need to be edited. Do you want a link that takes the user to new page?

**Comment by Abuchana** [comment]
[https://app.zenhub.com/files/439477060/07d8b7ef-feaf-495b-855b-682613a0a429/download][https://app.zenhub.com/files/439477060/9722ba1f-bf7b-41ef-8b5e-9e44546156d1/download]

**Comment by fazil-ey** [comment]
1. 
There are several places where the text/content doesn’t reflect the latest (attached) version of the form.  I have highlighted these areas in yellow highlight on an (attached) pdf printout, which also contains other points of testing feedback.

2. The content displayed online when the complainant submits the form should be changed to: “The Public Service Agency (PSA) will notify your union within 10 days of your complaint. You may ask your union representative at any time for an update on the status of a review or investigation arising from your complaint”. The heading should also be changed to the latest form name.  [Note: content will need to change if an LDB employee]
·        The content on the email sent to the complainant should be changed to: “Attached is a copy of the complaint you just submitted to the Public Service Agency (PSA) regarding a bullying / misuse of authority complaint under article 1.10 of the collective agreement. You may ask your union representative at any time for an update on the status of a review or investigation arising from your complaint.”  [Note: content will need to change if an LDB employee]

**Comment by fazil-ey** [comment]
Feedback for 1.10 form - 

1. Change title of the form to "Bullying / Misuse of Authority Complaint Form (Article 1.10)"
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/05bb782f-2fbc-4e2d-b8ac-469c986ce34c)
