### ISSUE TITLE
TOOL:"Contact us" in the footer goes to GDX and should go to DJ mailbox 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#732]
**Tasks**

- [ ] Open Outlook with to to DJ email - "digitaljourneys@gov.bc.ca" (To be confirmed)

**Comment by Stella-Archer** [comment]
The current footer goes to a page with info on "Help with Government Services"![ContactUs.gif](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/76cbbcb7-7c8c-4213-807d-11f3b2d98b80)
@fazil-ey and @MissionT @MeghanStothers could we put our heads together on a confirmation style page that would give users information on contacting us
