### ISSUE TITLE
1.10: Decision on Data Retention

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#735]
Question for 1.10  - How long should draft & submitted forms be retained in the Digital Journeys platform?

**Comment by morezooomm** [comment]
Based on comments from Julianne Burslem, PSA's FOI and Records Analyst, the retention period for our complaint case files is 1 year, so I would expect that draft and submitted forms be retained for the same period.  

While one might argue the digital journey versions are transitory records once they are submitted, keeping them available to complainants for the year would likely be a good service, for those who want to access a copy after submission.

**Comment by fazil-ey** [comment]
Drafts - 60 days with instructions
After submission - only confirmation page & email. Cannot see submitted forms

**Comment by morezooomm** [comment]
This makes sense to me.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin
