### ISSUE TITLE
SL Review - Changes in form fields 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#736]
The following changes have been made to the SL review form in digital journeys. Corresponding changes need to be made in the ODS for reporting. 

- “Program development” has been added as an option in the Expertise and Skills section
- “Program development” has been added as an option in the Learning and Development section
- There is now an ‘Other’ option in the Readiness section: both an ‘Other’ radio button and an associated text box.
- The final text box on the form is called ‘Additional comments’ now. It was changed from ‘Summary Recommendations’.

**Comment by T854236** [comment]
@iman-jamali-fw can you confirm if there are new fields on the SLReview form?

thanks

**Comment by iman-jamali-fw** [comment]
Hi @T854236
Not yet, I'll update the ticket once those fields are added.

**Comment by iman-jamali-fw** [comment]
@T854236 
These three fields are added:`essk_programDevelopment` `ldsk_programDevelopment` `readiness_other`
And this one is renamed from `summaryRecommendations` to `additional_comments`

Please let me know when you made these changes to test out the submissions. Thank you

**Comment by T854236** [comment]
@iman-jamali-fw 

For the 3 new fields, are they all boolean values?

**Comment by iman-jamali-fw** [comment]
@T854236  Yes they're booleans.

**Comment by T854236** [comment]
@iman-jamali-fw 

changes are done.  Please test.

**Comment by iman-jamali-fw** [comment]
@T854236 
Posted one by application id `7004`

Updated one by application id `7005`

**Comment by T854236** [comment]
@iman-jamali-fw both were successful.

**Comment by iman-jamali-fw** [comment]
@T854236 Thank you

@Stella-Archer Changes confirmed. We're good to move this ticket forward.

**Comment by Stella-Archer** [comment]
yahoo - this is ready for PROD then?
