### ISSUE TITLE
TOOL: Accurate and current dataset of ministry names

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#738]
As a form-building team (program) area, we need to have access to a current and correct names of ministry names (especially with changes in government).

This list is required to update the live forms, such as Telework form, (or those in development as well as the Senior Leadership Review to be launched  in 2023 .

Acceptance criteria
1) find an established source (likely BP Steven Jones)
2) update the tool with new ministry names (TES dev work)
3) Connect with Pattrick about ODS/data fields and any changes required
4) Document the latest additions/new ministry names in program area fields/wiki etc. for reference

**Comment by fazil-ey** [comment]
Has implications for 1.10, we also need to keep a track of names as someone could raise an issue when the name was different.

**Comment by Abuchana** [comment]
[11:18 a.m.] Jones, Steven PSA:EX
It's on my list to connect with Michelle Guerrero re: re-org stuff

[11:18 a.m.] Jones, Steven PSA:EX
It's not usually too big of a deal to update the org hierarchy, but I have no details on when it should go into effect yet

Patrick can provide an update to the team once more is known

**Comment by fazil-ey** [comment]
We should hear back in Feb about this from Don Moffats team

**Comment by fazil-ey** [comment]
We do not own the data, we cannot do anything to update this data from our end. 

On DJ we will hear about it if users complain and tell us, we can relay the message to DIO team and BI group at Telus
