### ISSUE TITLE
Add Application statuses to support the tele-work form/tool

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#74]
**Description**: As a form manager I would like to be able to see the status of form submissions so that I know where in the process a form is.

Currently all form submissions have the status of "new". Camunda can trigger changes to the status based on progress through a workflow.

**Acceptance Criteria**:

**Tele-work Form:**
- Statuses:
   - Pending
   - Approved
   - Denied

**Maternity Form:**
- Statuses:
  - TBD

**Comment by warrenchristian1telus** [comment]
I believe the form status is now being updated in the manager view. This should include new, approved and rejected. I think this meets the basic requirements, but if we need to change the status wording, that can be done. If so, I recommend tat we use the same wording denied vs. rejected, etc. across all forms.

@Stella-Archer can you please verify if this is working as expected? If so, I think we can close it.

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/165b196b-8dc4-4143-9d85-f36b6f6cd39e)
