### ISSUE TITLE
Form Links do not open to new page (Global Function impacted by Update 5.0)

### ISSUE THREAD

**Issue by MissionT** [bcgov/digital-journeys#742]
Background: As a form's designer, I noticed when building a new form that the form links do not open to a new page.
 
Steps to Reproduce: In the dev env, the 1.10 Complaint form being built has 3 links located in the instructions panel. These links do not open to a new page. 
 
Actual Behavior: This is a global function that was applied to all forms to ensure that (_blank) or new page/tab was opened up after a link was selected.  The recent 5.0 updated may have affected the actual behavior.
 
Expected Behaviour: User should not leave the form, a new/second web page should open, i.e. to view the collective agreement.
 
Environment: Dev (not sure if this impacts all other environments since its global function)

![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/2cc81dde-9f04-4daf-b864-8da2ba5a1229)

**Comment by bhumin-fw** [comment]
@MissionT @Stella-Archer 
I have deployed this change on DEV. Could you please test it here? If it looks good then I'll move it to TEST today.

**Comment by Stella-Archer** [comment]
Nice this works perfectly in DEV @iman-jamali-fw good to move to TEST

**Comment by Stella-Archer** [comment]
This worked great

**Comment by MissionT** [comment]
We noticed when reviewing the Bulling Form 1.10 form that the GEU and PEA links do not open to a new web page. Can this fixed so that the user does not leave the Forms page when selecting a URL to view related data.
