### ISSUE TITLE
Add how-to guides for the new features in the TOOL

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#745]
A form designer should have a guide/how-to on the features that can be done through TOOL without needing the devs to do it through the platform (codebase).

Write how-to guides on the following features:
- Adding/Removing accepted email domains on the Telework form
- A guide on how to work with BPM workflows through the `processes` tab on the TOOL. Things like how to export or edit them on the TOOL. Also, explain that each environment has its own workflow and change in one should be also done on other environments. 
- A guide on how to add/customize floating buttons.
- A guide on how to change error messages.
- A guide on how a form designer can change a form's pdf naming generated on the TOOL.
- A guide on how to have a component hidden in a server-side-generated PDF by adding `hidden-in-print ` as a custom CSS class.

@MissionT to create & share the document on teams for the how-to guide.

**Comment by iman-jamali-fw** [comment]
@simensma-fresh @bhumin-fw Please feel free to add the features you think are worth having a how-to guide.

**Comment by MissionT** [comment]
New job aid template was created:
1) Update domain names - done.
2) Allow users to add fields automatically for multiple data entry   - done.
3) currently repurposing 2 other jobs to the new format.

**Comment by fazil-ey** [comment]
We need to add this on [github](https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md)
