### ISSUE TITLE
1.10: Confirmation Page 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#747]
**User Story**
As a Complainant I want to see a confirmation page after form submission so that I know that the form was submitted successfully and can be informed about the next steps. 

**Acceptance Criteria**

- [x] Complainant sees a confirmation page after successful submission of 1.10 form

**Comment by bhumin-fw** [comment]
@morezooomm @Stella-Archer @fazil-ey @MeghanStothers 
I have added a confirmation code for review.
Please take a look at the below image for reference. (Contains copy from the docx file attached to ticket 728). Please provide your suggestions and changes if any.
![Screenshot 2022-11-29 at 11.49.04 AM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/cf88aa17-7af4-4a4e-bd9b-f3ebf667219c)

**Comment by morezooomm** [comment]
The content I would put in the confirmation is as follows:

Thank you for submitting your bullying and harassment complaint form (Article 1.10). (This name would match the name on the current version of the complaint form – Don)

The employer will notify your union within 10 days of your complaint. You may ask for assistance from your union representative either before or after submitting your complaint and may ask your union representative at any time for an update on the status of a review or investigation arising from your complaint.  (This is a shorter version of what I originally submitted on ticket 728 – Don)

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment]
Thanks @morezooomm  
I have updated the details on the success page. Please take a look at below reference image from the local development copy.
![Screenshot 2022-11-29 at 9.12.41 PM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/7898d011-fd65-4911-918e-32f0f4ec0d87)

**Comment by Stella-Archer** [comment]
thanks confirmation page was functioning fine in  DEV

**Comment by MeghanStothers** [comment]
@fazil-ey Fazil and I talked about this one - we will created a new ticket #794 to adjust to the correct/final form name, as well as make the bullet points separate, etc. See ticket #794 and add details

**Comment by MeghanStothers** [comment]
First we will need to deploy to prod
