### ISSUE TITLE
1.10: Naming the Draft forms 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#748]
Working title for the draft forms - "Article 1.10 Complaint Intake Form for First Name Last Name"

**Update** - Name is updated to  "Bullying / Misuse of Authority Complaint Form (Article 1.10)"

**Comment by fazil-ey** [comment]
We will test the name in January when we do UX testing for the form.

**Comment by morezooomm** [comment]
The name on the form should be: “Bullying / Misuse of Authority Complaint Form (Article 1.10)”

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by fazil-ey** [comment]
@bhumin-fw  currently the draft name is "Bullying And Harassment Complaint Form Article 1 10"

are we able to name the drafts "Bullying / Misuse of Authority Complaint Form (Article 1.10)"

**Comment by morezooomm** [comment]
Yes, the form should be named “Bullying / Misuse of Authority Complaint Form (Article 1.10)” as harassment complaints are not covered on this form.  Thanks.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by fazil-ey** [comment]
Name is correct in test

**Comment by morezooomm** [comment]
Agreed.

I have received a couple of test complaints in the Registrar Intake Mailbox and the heading on the complaints was “Bullying / Misuse of Authority Complaint Form (Article 1.10) – PSA”.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin
