### ISSUE TITLE
1.10 - Explore CSV attachments for form in the email 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#749]
Explore if it is possible to have excel spreadsheet/csv to facilitate data entry for 1.10 form. 

Any format that can be opened in Excel and allows data to be copied will work. The goal is to reduce manual data entry for 1.10 team, as they would have to copy data from a PDF. 

What will the CSV look like with multiple respondents and other dynamic sections?

**Comment by MeghanStothers** [comment]
As per Don's note, I don't think this is a requirement any longer - see email on Dec 12

**Comment by MeghanStothers** [comment]
From	Subject	Received	Size	Categories	
Smallwood, Don PSA:EX	Registrar Intake Tracker Spreadsheet	12:48 PM	38 KB

**Comment by MeghanStothers** [comment]
Alison, 

Attached is a spreadsheet that I’ve drafted for our Intake Analyst to track incoming 1.10 complaints to the new registrar intake mailbox.  Once I developed this, it was clear that very few of the fields would be taken from the submission itself – only 3 fields on tab A and an additional field on tab B.  

As such, I don’t currently think building and sending us a csv file along with the pdf will offer much value add. Perhaps we should just park this csv file request for now and I can revisit it down the road, if required.  
Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9

**Comment by MeghanStothers** [comment]
[https://app.zenhub.com/files/439477060/02736a51-0e1a-4d91-91b3-9e8ce65d4130/download](https://app.zenhub.com/files/439477060/02736a51-0e1a-4d91-91b3-9e8ce65d4130/download)

**Comment by fazil-ey** [comment]
Closing this based on Meghans comment above - Don doesn't think this will add much value
