### ISSUE TITLE
Devs to build new form automation to allow components such as text fields to be added to forms bypassing the clunky adding and hiding of prebuilt fields

### ISSUE THREAD

**Issue by MissionT** [bcgov/digital-journeys#759]
Using the SL Review form as an example, the form designer must manually add fields, hide them, and the apply logic to show them based on another field value, example:  a checkbox was selected (=true), show other fields. 

A new form is being developed that could potentially have 50 groups of fields (5 text fields x 50 iterations = 250 fields), that need to be manually added. This is an arduous and clunky process. Could the developers create code to automatically create form components thereby saving the form developer a considerable amount of time of manually added each component to the form?

Context:  I would like to add 5 text fields, and 1 checkbox. I would like to apply this 52 times to the form. I would like the default format of each field to be hidden. The dependent field that would unhide them would be i.e. fieldname = true.
The behavior of the form objects: add type of field, how many; add another type of field, how many. How many instances of these fields to you want to create? i.e. 25. Default fields: all hidden, show when another field is selected or equal true. 

![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/5f2cd4eb-6236-4a60-9a4a-b4e53cf2aba9)

**Comment by Stella-Archer** [comment]
@simensma-fresh could you demo the component that does this action?

**Comment by simensma-fresh** [comment]
Discussed this with @MissionT  and decided to proceed with using the Data Grid component instead. @MissionT  will create a new ticket to improve the styling of the Data Grid component as it currently does not look great

**Comment by MissionT** [comment]
These components are available. Ticket can be closed.  Steps to add this automation by the form designer: Add a Data Grid, Add a field set, add text fields.
