### ISSUE TITLE
Create a formsflow Dashboard for management to view form submission stats

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#766]
Could we have a dashboard built within formsflow to allow management to use when reporting on forms flow stats.

Stats to be generated:
1) total forms in the Review and Process Forms tab
2) total forms in the Submitted Forms tab
3) total draft forms in the Drafts tab

![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/add87322-94c7-47c5-afb4-556ef553c64b)

**Comment by Stella-Archer** [comment]
Closing Rolling into #1165
