### ISSUE TITLE
TOOL: The user is not displayed with any error messages and can upload a form with the same title, name or path of an existing form.

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#77]
**Background:** The user is not displayed with any error messages and can upload a form with the same title or path of an existing form.

**Steps to Reproduce:**

1. Log in to the PSA-Digital-Journey portal on dev as an admin with valid credentials.
2. Download a copy of an existing form.
3. Edit the name and path, but do not edit the title; save the json file.
4. Click on "Upload Form".
5. Select the file.
6. **Actual Behavior:** The user is not displayed with any error messages and can upload multiple copies of a form with the same title. 

![DJsameTitle.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/4d400973-b6d7-478e-8152-6a04835ba71c)

**Expected Behavior:** Each form's title should be unique, and the user should be displayed with an error message "The form title/name must be unique".

7. Edit only the path, but do not edit the title and name; save the json file.
8. Click on "Upload Form".
9. Select the file.
10. **Actual Behavior:** The user is displayed with the "Forms Upload Confirmation" pop-up with continuous loading indicator. The same behavior happens if only name is edited. 

![DJunabletoUpload.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/1f4e00a3-7805-47b9-ae76-3b3fae8ddd23)

**Expected Behavior:** Each form's name should be unique, and the user should be displayed with an error message "The form name must be unique".

11. Edit the title and name, but not the path; save the json file.
12. Click on "Upload Form".
13. Select the file.
14. **Actual Behavior:** The user is able to upload the form with the same path as an existing form.

**Expected Behavior:** Each form's path should be unique, and the user should be displayed with an error message "The form path must be unique".

**Comment by Abuchana** [comment]
@iman-jamali-fw can you please add an estimate for this ticket please? Thanks!

**Comment by fazil-ey** [comment]
closing as this is only an issue for form designers/devs
