### ISSUE TITLE
1.10: Pre-fill fields for IDIR users 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#770]
**User Story** 
As a complainant with IDIR access I want to have my basic information prefilled, so that I can save time by not having to fill everything myself. 

Fields to be prefilled - 
- Legal first name
- Legal last name
- Your ministry
- Your position title
- Your work location
- Your immediate supervisor
- Your telephone number
- Your government email address:  

**Acceptance Criteria**
- [x] The fields mentioned above are prefilled for IDIR users when they log in
- [x] The fields should be editable 

**Notes**
https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md#how-to-auto-populate-form-fields-with-the-user-data
@MissionT

**Comment by MissionT** [comment]
Legal first name  - done
Legal last name - done
ministry -  populated - user must select  manually, (this is because the field is not connected to source of truth)
Your position title - done.
Your work location - done. Note: only the street pulls (no other info such as city, prov, postal code)

**Comment by Stella-Archer** [comment]
I can only see this form in DEV so leaving in TEST/QA to confirm its' ok in TEST as well, could you check for me on Monday @fazil-ey ask Iman about the access and let home know if you still can't see the 1.10 complaint in TEST either

**Comment by MissionT** [comment]
I asked the devs to provide access to Fazil on Monday. Hoping he will be granted access by this afternoon.

**Comment by MissionT** [comment]
The API property field officePhone has been added. My own phone doesn't populate.  I'll ask Iman if this does not work for UC#s.
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/9b3c0810-420e-4b46-8e23-85aa35f586cd)

**Comment by fazil-ey** [comment]
Tested, fields are pre-filled as expected
