### ISSUE TITLE
1.10: New login page for digital journeys

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#771]
**User Story**
As a user, i should be able to choose a login method appropriate for me so that i can access Digital Journeys and fill the form i need to 

**Acceptance Criteria**
- [x] Users are able to choose between IDIR, BCeID and LDB Authentication to login to DJ
- [x] Users have instructions to guide on on which login method to choose
- [x] The page follows the design guidelines specified [here](https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/identity-and-authentication-services/login-best-practices/login-launch-page) 

**Design** 
TBD

**Comment by MeghanStothers** [comment]
Meghan to reach out to Jordan to find out about her availability to send us a design - request to Iman to keep going with the design as possible

**Comment by fazil-ey** [comment]
@MeghanStothers & @Abuchana to add examples to help devs know what the page should look like

**Comment by fazil-ey** [comment]
@MeghanStothers & @Abuchana to add examples to help devs know what the page should look like

**Comment by MeghanStothers** [comment]
We met with the communication team for and they gave us an example of a common login page) like what you see in www.Timepayhome-ps.gov.bc.ca  (open with Firefox)
We will need to follow these guidelines as well as connect with the communications team to show them before launch (Meghan And Don will have regular communications meetings with that team)

For this work, we can look at examples form other product teams, such as the performance Development login page

**Comment by MeghanStothers** [comment]
https://www.performance.gov.bc.ca/login

**Comment by MeghanStothers** [comment]
This will be one page for access to all forms (including the login page to the Telework form)

**Comment by Stella-Archer** [comment]
The landing page or login page may just have to look like the Employee Self Service landing page for users that don’t have an IDIR- currently that looks like this:
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/78748739-ba6d-40ee-91fb-a7f999f33287)

**Comment by MeghanStothers** [comment]
@Stella-Archer The info sent from the BCeID team has the requirements - see the "LOGIN PAGE" info in the file "IDIM's Client Communication Package v.4" doc - please pull the requirements info from there.

**Comment by bhumin-fw** [comment]
@Stella-Archer @MeghanStothers 
I have started working on theme that we can apply in the exiting keycloack setup. I did review https://www.performance.gov.bc.ca/login but that seems way different that Stella's screenshot.

I have prepare one draft to see how it works.
**Exiting TEST environment login page**
![Screenshot 2023-01-30 at 7.42.51 PM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/ae14ee39-d6eb-444d-b1c2-b1c2ed00ca99)

**Draft: Login page using BC GOV details and theme**
In below image you can see 3 & 4 **sign in with** options. 
![Screenshot (30).png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/09aecef2-c6c8-42be-a417-5b0efbfdd770)

**Comment by bhumin-fw** [comment]
@Stella-Archer 
One more suggestion by changing template. 
**Please ignore "facebook" button, added to test fa icons.**

![UpdatedTheme.PNG](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/3a437aba-c7f4-4895-8d93-d9a2e286dbc4)

**Comment by MeghanStothers** [comment]
We will preview the login page with the OCIO team/BCeID/BCSC team in early February (Date) TBD as per their requirements to approve about any public-facing communications or mentions of the BC Services card.

**Comment by Stella-Archer** [comment]
This is looking really good @bhumin-fw the last comp is getting closest.
I did a mock up based on that with some changes
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/0e291a6b-993b-4e1d-8f3d-70bf44287205)

**Comment by Stella-Archer** [comment]
I;ve numbered the changes
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/62145c6e-9d9d-4f1c-b16a-c7c8b262f06d)

**Comment by Abuchana** [comment]
@Stella-Archer is it not Liquor Distribution Branch as displayed in the GAL?

**Comment by Stella-Archer** [comment]
1/ we're putting the focus on IDIR first as that makes up the huge majority of all forms so make the default " log in with **IDIR**"
2/ label "IDIR Username"
3/ label button 'Continue'
4/ on the left OT under a blue bar and #FFFFFF background the options can be stacked and labeled "Log in with"
5/ Button Colour #336699 "BC Services Card"
6/ BCeID Basic
7/ Liquor Control Branch ID
8/ in same style you did the pervious Dj help but underneath the alt authentication options:
**Need Help?**
"Contact the BC Services Card Help Desk if you need help with: 
Setting up the BC Services Card app 
Using the app to log in 

**BC Services Card Help Desk** 
Open Monday to Friday (except statutory holidays) from 7:30 am to 5 pm Pacific Standard Time, or 8:30 am to 6 pm Mountain Time. 

1-888-356-2741 (Canada and USA toll free) 

604-660-2355 (Within Lower Mainland or outside Canada and USA)

**Comment by bhumin-fw** [comment]
@Stella-Archer 
Please find my comments on your suggested points. I did make change on points 4-8. 
Points 1-2-3 cannot be done here as we are not capturing IDIR credentials on DJ login page.

> 1. Login with IDIR is external authentication process, **Log in to sfs7.gov.bc.ca** here it will login, When we click on IDIR it will redirect to "pathfinder SSO" and then show up IDIR login page.
> ![1.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/b9f5bf39-b9a7-4b9f-aeec-6f582224bfc8)
> 
> 2. On digital Journey login page we are not capturing username and password for IDIR. User must login into IDIR using "pathfinder SSO".
> 3. (As this page only provide login for admin and users)



4. The label is predefined with keycloak setup. But I can make requested change using CSS context.
5. change colour & title can be done.
6. Title can be change from the keycloak configuration. I can check it with Iman and see how we can re-configure it with updated name
7. Same as 6th point
8. Changes can be done

I have updated login page design. (text needs to update in configuration, not include IDIR change)
![CaptureChanges.PNG](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/bd074409-1dc3-4aa2-ae5f-d46e71253d1f)

**Comment by Stella-Archer** [comment]
Thank @Bhumin in that case we probably need to present all the options in a simple stack 1st as in structed here https://www2.gov.bc.ca/gov/content?id=54526FE255574495B6F6FB2708932E19
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/01db2406-7a0f-418e-bfb6-8366edac3b40)

**Comment by Stella-Archer** [comment]
so the main log in page would look like this 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/2c3d4fe8-8cdc-45d0-a374-b8643595d182)

**Comment by bhumin-fw** [comment]
@Stella-Archer You can check it on DEV (version with login form and social providers). In the backlog refinement I can show alternative option that do a trick using javascript and hide component and re-arrange visible component.

**Comment by bhumin-fw** [comment]
Change estimation from 5 to 8, It will help in velocity report. We did spent some additional time to handle deployment failures.

**Comment by bhumin-fw** [comment]
@Stella-Archer @MeghanStothers 
**Change are up and running on DEV and TEST server and ready to test.**

(Needs to discuss couple points with Dev Team, hence keeping it in "peer review")

**Comment by bhumin-fw** [comment]
latest login screen with "BC Sans" fonts.
![Screenshot 2023-02-13 at 10.12.23 PM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/096a5135-eeda-43a1-97b1-4a906dbfe103)

**Comment by Stella-Archer** [comment]
This is looking really good we just need to connect the LDB log in page (ticket #782) @iman-jamali-fw  do you have everything you need to hook that up?

**Comment by iman-jamali-fw** [comment]
@MeghanStothers @Stella-Archer 
Do you want to The new login page for PROD as part of the first deployment (tonight) or the second one in March? If you want it be deployed to PROD tonight, it only will have IDIR. Please let @bhumin-fw  and me know. Thank you

**Comment by iman-jamali-fw** [comment]
This is deployed to PROD. We can toggle the new theme whenever BCeID and BCSC added in the next deployment in March but the changes for the new theme in the Keycloak was added to PROD.

**Comment by Stella-Archer** [comment]
Looks good - we added a new bug tix as we can't logout but closing this part
