### ISSUE TITLE
GUID and IDIR missing on submissions to BI API services and ODS

### ISSUE THREAD

**Issue by T854236** [bcgov/digital-journeys#773]
We just noticed that as of Nov 9th 10:30 AM, GUID and IDIR are no longer passed with the submissions to ODS.  As of Dec. 5th 9:44 AM, there are 1205 records with missing IDIR and GUID.

Can the records be re-submitted?  Unfortunately, this impacts reporting and will require the information records to be updated or re-submitted.

To review if we can make those fields mandatory

**Comment by MeghanStothers** [comment]
Simen recommends See if we can reproduce in Test - assign to Bhumin or Iman - could be an issue related to the upgrade

**Comment by T854236** [comment]
@simensma-fresh 

I loaded a file with records with missing GUID.  Unfortunately, the email or application IDs are not sent to ODS.  File is loaded to SharePoint: https://bcgov.sharepoint.com/:x:/r/teams/03991/Shared%20Documents/Data%20Collection/[Telework_submissions_with_missing_GUID_Dec6_2022.csv](https://bcgov.sharepoint.com/:x:/r/teams/03991/Shared%20Documents/Data%20Collection/Telework_submissions_with_missing_GUID_Dec6_2022.csv?d=wfb49c6be39f74860bc267569d94e42fa&csf=1&web=1&e=Z8NPV2)?d=wfb49c6be39f74860bc267569d94e42fa&csf=1&web=1&e=Z8NPV2

**Comment by MeghanStothers** [comment]
@simensma-fresh I'm definitely open to that idea of keeping submissions in the system for 60 days - can you confirm it would mean that completed Telework Agreements (= those signed by supervisors) would still be available after they have been approved, so up to 120 days (60 days for manager to approve + 60 days retained?) 
@Stella-Archer I would like you to weigh in on this issue to to see about any impacts to other forms in development. For Telework, we would need to update the PIA.

**Comment by simensma-fresh** [comment]
@MeghanStothers That would be my suggestion for the Telework Agreement at least (60 days for manager to approve + 60 days retained)

**Comment by iman-jamali-fw** [comment]
@T854236 I sent two Telework submissions from our DEV and TEST environment to ODS. Can you please verify if `idir` and `guid` are properly sent?

**Comment by T854236** [comment]
@iman-jamali-fw 

Yes confirmed I see them with the GUID and IDIR information.  I noticed the schedule is missing.  Is that expected with your tests?

**Comment by T854236** [comment]
@iman-jamali-fw 

I don't see the 3rd one yet.  Do you need to approve it first before it is send to the API service?

**Comment by iman-jamali-fw** [comment]
@T854236  Just sent another. One thing I  learned is that we flatten the schedule before sent to ODS so the values will be the days of the week (e.g, `monday:false`, `firday: true`) and `schedule` itself will be removed before sent to ODS. Is that expected?

**Comment by T854236** [comment]
@iman-jamali-fw 

I see the 3rd test now and the schedule column is blank.  It used to have values before (e.g. {"monday":true,"tuesday":true,"wednesday":true,"thursday":true,"friday":true,"saturday":false,"sunday":false}).  Was there a decision to remove this field from ODS?

I can ask Sarah M. if she uses this field for reporting purposes.

**Comment by iman-jamali-fw** [comment]
I believe we decided to flatten the data sent to ODS when we were working on the SL Review form. The flatter function should have removed `schedule` :( 

Can we update these fields to something like `schedule-friday `, `schedule-monday`?

**Comment by iman-jamali-fw** [comment]
@T854236  Hmm, seems like a lot of effort to change that. Does the current structure with the schedule as flat values (e.g., `monday:true`) work for ODS and BI purposes?

**Comment by T854236** [comment]
@iman-jamali-fw 

I would recommend to revert the change with the schedule for now and open to discuss if changes are required.  We should bring in Steven's team so they are aware of the changes if that is what we want to do.

The column is a string value up to 4000 characters.  I believe it was an array and converted to string.  Sample below. 

{"monday":true,"tuesday":true,"wednesday":true,"thursday":true,"friday":true,"saturday":false,"sunday":false}

**Comment by simensma-fresh** [comment]
@T854236 Perfect thanks. I'll take a look and see what I can do

**Comment by MeghanStothers** [comment]
@Stella-Archer - Can you have a peek at this ticket?  Thanks For now, I have added you to the ticket and we could talk about it at scrum tomorrow.

**Comment by MeghanStothers** [comment]
Alison checked with Jodi who is ok with rolling back the function. Jodi said they will have the PSA ADMs in there in January sometime so we'll have to find a way to fix it early in Jan. Alison let
 Simen and Iman know and they 
 might have a fix for TWA that doesn't involve BI so SLR won't be affected. They will keep us posted....

**Comment by iman-jamali-fw** [comment]
@MeghanStothers @simensma-fresh  If it makes sense, I can move the missing `schedule` issue to a separate ticket. And have this ticket to only track `GUID` and `IDIR` which are currently deploying in PROD.

**Comment by iman-jamali-fw** [comment]
@T854236 
I sent a Telework submission with applicationId `28620` on Prod. Do you mind verifying if GUID and IDIR were received on your end?

**Comment by iman-jamali-fw** [comment]
@T854236 
Great! Thank you.
