### ISSUE TITLE
1.10: Changes in form after BCeID is implemented

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#777]
The following changes would be required in 1.10 form 

- [x] Employees using personal emails do not have any data pre filled except first name, last name & email
- [x] Employees using personal emails do not receive an attachment of the form on their email

**Comment by iman-jamali-fw** [comment]
@MeghanStothers @fazil-ey 

Sorry, I confused this ticket with #886. That ticket is required for our deployment next week, which I pulled into in progress today. I'll remove the dependency from this ticket and add it to #886.

@fazil-ey Feel free to move this back to the product backlog.

**Comment by MeghanStothers** [comment]
Thank you - @fazil-ey I have pulled this one into the backlog

**Comment by morezooomm** [comment]
Fazil,


In response to your questions:

  *   [X] Employees using BCeID do not have any data pre filled except first name, last name & email  Agreed.
  *   [X] Employees using BCeID do not receive an attachment of the form on their email  Ageed.
  *   [ ] Employees using BCeID receive a generic confirmation email as their identity cannot be confirmed. Copy TBD @morezooomm<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmorezooomm&data=05%7C01%7CDon.Smallwood%40gov.bc.ca%7Cf529830dac874c9d066b08db1052241e%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638121717192722208%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6f1qpQaCp%2Bqv4gF9qrpvmXB05g3fpNye9OYJGT%2FRAh4%3D&reserved=0>

I would suggest the same message we have used elsewhere when we are not sure of who the sender is: “You just submitted a complaint regarding bullying / misuse of authority under article 1.10 of the collective agreement. You may ask your union representative at any time for an update on the status of a review or investigation arising from your complaint. You may also access or download a copy of your complaint by visiting the Digital Journey portal<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdigital-journeys-test.apps.silver.devops.gov.bc.ca%2F&data=05%7C01%7Cdon.smallwood%40gov.bc.ca%7Ca79e2c18ef24462c81b008db110b2a67%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638122511864926767%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=2yiQcWi8Yhy%2FgQUnQVkEfaP2E6Dj1d9kcxD%2BLXIk%2FKM%3D&reserved=0>.”

  *   [ ] Ask for work email in addition to the BCeID email for verification purposes. But we send the email confirmation to the BCeID email. This would be an optional field.  Agreed.
Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

Government confidentiality and privilege requirements apply to this message and any attachments.  If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately, and delete this message and any attachments from both your inbox and deleted items folder.

**Comment by fazil-ey** [comment]
- [ ] Ask for work email in addition to the BCeID email for verification purposes. But we send the email confirmation to the BCeID email. This would be an optional field. @morezooomm to confirm if this is required 

Not needed as per the comment above
