### ISSUE TITLE
TOOL: Showing forms to its supported IDP users on the form list page

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#778]
Acceptance criteria

- [x] As a user logging in using IDIR, I only see forms that support IDIR.
- [x] As a user logging in using BCeID, I only see forms that support BCeID.
- [ ] As a user logging in using BCSC, I only see forms that support BCSC.

**Comment by fazil-ey** [comment]
@morezooomm to look at #783 to see how the PIA for 1.10 is affected by this

**Comment by morezooomm** [comment]
The Digital Journey team will create a separate PIA to cover the BCeID and BC Services Card.  I will continue to move forward the PIA for the 1.10 form, and will make reference in my PIA to the use of BCeID and BC Services Card, and that those are covered under a separate PIA.

**Comment by iman-jamali-fw** [comment]
@fazil-ey  I suggest changing this ticket to "each form in the list, only be displayed to the user, if user logged in with the form's supported IDP". For example, if Telework only supports IDIR users, the form only is displayed in the forms list, if a user is logged in with IDIR. For 1.10, only displayed to IDIR, BCeID, and BCSC users.

Background: As part of BCeID/BCSC integration each form now has a field that indicates which IDPs to support (e.g., IDIR, BCeID and etc) (see the doc [here](https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md#form-access)). Once the user opens that form, if their IDP is not supported AND that user is not a designer, will be prompted by a "no form access" message and redirected to the forms list page.

Fo

**Comment by morezooomm** [comment]
Fazil,

Your suggestion below sounds reasonable to me.  Cheers!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment]
@Stella-Archer It is ready to test on DEV and TEST environment.
@MissionT @Andrew-Vargas-bcgov I have changed the form access method. Now you can add supported IDP along with the form meta and do not need to add any hidden field. For more detail, please review the document [here](https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md#form-access).

**Comment by Andrew-Vargas-bcgov** [comment]
@iman-jamali-fw @bhumin-fw   All users only see forms that they have access to fill out, as per their IDP. They also see and have access to forms in which the IDP was left blank (as intended).
Older forms need to be saved all the way through with the correct IDP information filled out and also when making changes to the IDPs.
Great job :).

**Comment by MeghanStothers** [comment]
ready for deployment

**Comment by MeghanStothers** [comment]
tested and okay to close
