### ISSUE TITLE
Missing `schedule` object in the data sent to ODS

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#779]

**Comment by iman-jamali-fw** [comment]
@T854236 

I just sent a telework submission on our DEV environment. Can you please check the `schedule` data on your end?

**Comment by T854236** [comment]
@iman-jamali-fw 

I see 2 from this morning with missing values but the last one that you just sent has the schedule value.

GUID and IDIR information looks good too.

**Comment by iman-jamali-fw** [comment]
@T854236 

The last one was after the fix was deployed to DEV.

@simensma-fresh I think we're good to deploy the fix to PROD. In the meantime, I'll do another test on TEST once it's deployed.

**Comment by Stella-Archer** [comment]
YAY  - Push it to PROD please!

**Comment by T854236** [comment]
@iman-jamali-fw 

yes confirming the schedule information is there.

**Comment by iman-jamali-fw** [comment]
@T854236 

Can you please confirm if the schedule has been received by ODS on PROD? I just sent a submission after the fix is deployed to PROD

**Comment by T854236** [comment]
@iman-jamali-fw 

Hi yes confirmed received.
