### ISSUE TITLE
BCeID integration

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#781]
In order to allow full integration of BCeID for the 1.10 Complaint form, we need to make some changes in order to make sure the Telework Form is not impacted.

**Isolation of Users**
Users that log in with BCeID should be treated as separate users from IDIR users, even if they have the same email address. This has an impact where we need to update
- Keycloak to use a user guid as the "username" instead of email as currently set up (for BCeID users)
- Make sure Camunda uses a users username as the user identifier instead of email.

Without any changes, Keycloak will merge a BCeID user and an IDIR user due to the account merging setup we did to support pre-creation of Manager accounts for the Telework Form

**Prefill first name, last name, & email**
- The 1.10 Complaint form should have first name, last name & email prefilled from your auth token

**Acceptance Criteria**
- When I log in as a BCeID user with the same email address as an existing IDIR user, I cannot see previously submitted applications submitted by the IDIR user
- When I log in as a BCeID user with the same email address as an existing IDIR user, I cannot see tasks the IDIR user is assigned to
- When I log in as an IDIR user, I have access to the same forms/submissions/tasks as before
- When I log in as a BCeID user, I cannot navigate to or submit the Telework form.
- When I start to fill out the 1.10 complaint form after logging in with my BCeID, my first name, last name, and email is prefilled

**Technical Info**
- Attributes received from BCeID can be found here (BCeID Basic - Gold): https://github.com/bcgov/sso-keycloak/wiki/Identity-Provider-Attribute-Mapping 

*Proposed KeyCloak Changes*
 - Update IDP Username mapper in Keycloak to use the BCeID username as the users in-app username (bceid_guid@bceidbasic).
- Update IDP email mapping to allow for users with duplicate emails within KeyCloak.

*Camunda*
- Update Camunda to use the new username as a user identifier instead of email

*App*
- Modify endpoints in app to allow restricting what forms you can see based on the IDP you are logging in with - only allow submissions of Telework form if you're logging in with IDIR
- Modify /me endpoint to return your first name, last name and email if the IDIR attribute is not found (so we cannot look you up in the ODS)

**Comment by iman-jamali-fw** [comment]
Testing instruction:

**Form Access**
Each form has a new form access field that determines users by which Identity Providers (IDPs) (e.g., IDIR, BCeID, and BCSC) have been allowed to submit this form. This is done through a hidden form field called `formSupportedIdentityProviders` and its default values.

Telework allows IDIR users and the 1.10 form allows IDIR and BCeID users to access the form. A user with a `designer` group has access to all forms.

To test the form access, you can once access the form with the designer (who should have access to all forms) and once without it.

**Comment by iman-jamali-fw** [comment]
@MissionT 

You can create a test BCeID account for each environment through the following:
Test environment: https://www.test.bceid.ca/register/
Dev environment: https://www.development.bceid.ca/register/

**Comment by Andrew-Vargas-bcgov** [comment]
Passed all tests.

**Comment by MeghanStothers** [comment]
Andrew tested and can be closed
