### ISSUE TITLE
1.10: LDB authentication integration

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#782]
- Also prefill first name, last name & email in the form

**Comment by fazil-ey** [comment]
Check with @morezooomm to see where LDB people are with this. This works in DEV

**Comment by morezooomm** [comment]
I have not had any discussion with LDB on this issue, as it was my understanding that the Digital Journey team have been in direct contact with technical staff at LDB.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by MeghanStothers** [comment]
Iman will likely need help with LDB technical team - Will reach out to Don or team for contact name if needed

**Comment by iman-jamali-fw** [comment]
Sccot Petersen (technical person at LDB) confirmed that the integration on DEV is working. Please note that LDB's DEV integration is only accessible from within their network.

We're currently working to set it up for TEST which will be also accessible from outside the LDB network.

**Comment by MeghanStothers** [comment]
Iman to follow up with Scott

**Comment by MeghanStothers** [comment]
March 3 Friday

**Comment by MeghanStothers** [comment]
Iman asked Scott for test account to make sure LDB access is compatible

**Comment by MeghanStothers** [comment]
Iman sent LDB prod integration and asked for test account

**Comment by iman-jamali-fw** [comment]
Update from LDB:
They send the initial configuration for PROD. The final approval and configuration should be done early next week as they have a meeting planned for Monday.

They also got me a test account for TEST environment.

**Comment by iman-jamali-fw** [comment]
Did not find an expert on SAML (standard of LDB authentication) at EY.

Looking into the option of making the changes to the username and user Id from the LDB side. Waiting for their response.

**Comment by fazil-ey** [comment]
@Abuchana to follow up on this to find a technical resources to help us

**Comment by iman-jamali-fw** [comment]
@Stella-Archer @Andrew-Vargas-bcgov 

This is ready for testing on TEST. Please let me know to share the username/password of an LDB test account with you when testing. Thank you

**Comment by MeghanStothers** [comment]
@iman-jamali-fw Andrew is off today - do you need this tested before the 7 a.m. LDB work tomorrow? If so, I will see if @Stella-Archer  or @chriscaldwell-psa can test (or me too)

**Comment by MeghanStothers** [comment]
@iman-jamali-fw what tests would you like us to do? (Assuming we'd test in test environment?)

**Comment by Stella-Archer** [comment]
In test about to sign in with LDB do you have credentials I should use for this @iman-jamali-fw 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/672cc7f3-f083-4f1e-92ca-3f09510e4a01)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/b07551d8-dea0-4ab4-8ad7-b88ad6dd6974)

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 

Please click "Proceed to identity.test.bc...." and then use the credentials I sent you in Teams.

@MeghanStothers 

Testing not necessary need to be done after LDB PROD integration, no rush.

**Comment by Stella-Archer** [comment]
@Andrew-Vargas-bcgov and @ayushdamani this worked great for me but could you each check TEST https://digital-journeys-test.apps.silver.devops.gov.bc.ca/form  again and confirm:
1/ you can access identity.test.bcldb.com and get in with Iman's Credentials(Sending in an email)
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/bce1af41-a828-4811-9c6d-27c71b4cf056)
2/ You can only see mat/pat and 1.10 when you log in
3/ everything works on the form as expected

**Comment by ayushdamani** [comment]
@Stella-Archer 

I can confirm:
1) I am able to access identity.test.bcldb.com with Iman's Credentials.
2) I am able to see mat/pat and 1.10 when logged in.
3) The forms are working great - 1.10 auto-populates data as well.

**Comment by Andrew-Vargas-bcgov** [comment]
Looks good to me. 
1. Login works
2. I can see 1.10 and mat/pat. 
3. firstName, lastName, email all autopopulated.

**Comment by chriscaldwell-psa** [comment]
I tested the LDB login - I have the same results as Andrew. All good.
