### ISSUE TITLE
PIA for BCeID & BC Services Card (overall tool)

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#783]
We want to have a stand alone PIA for the BC Services Card and BCeID for the formsflow.ai platform as we anticipate multiple forms being set up with these methods of access. 

Individual forms that use these methods can then reference this PIA in their PIAs.

**Comment by morezooomm** [comment]
This should have no impact on the PIA I am processing for the 1.10 form itself.  While I will reference the BCeID and BC Services Card in my submission, they will be covered by a separate PIA that will allow the Digital Journey team to reuse the PIA approvals for other forms.

**Comment by MeghanStothers** [comment]
Met with Nas today and we looked at what's missing from the latest draft of the PIA that we'll need completed before we launch the 1.10 form (as well as the mat/pat form). 

We have a current draft which has reference  to the BC Services card (pulled from another project.)

@iman-jamali-fw The missing part of the PIA we'll need to complete before launch is the technical steps/back-end for BceID authentication.
Iman - do we have any documentation/information about what will happens in the back-end?   We will need to add bullets to the PIA or list of what happens in the forms flow system related to BCEID authorization/login.

**Comment by iman-jamali-fw** [comment]
@MeghanStothers
We have some general documentation from AOT of how Keycloak is setup and work for each component. For example [here](https://github.com/AOT-Technologies/forms-flow-ai/tree/v5.0.2/forms-flow-web#keycloak-setup) for the website and more generally [here](https://github.com/AOT-Technologies/forms-flow-ai/tree/v5.0.2/forms-flow-idm). We don't currently have one for BC Services Card.

Do we know what technical steps it requires for that document? If there is an example for another project available (with regards to BC Services card) we can use that as the starting point for our project.

**Comment by fazil-ey** [comment]
@matbusby-fw can you help with this documentation?

**Comment by morezooomm** [comment]
Yes, I am happy to help with any PSA content in the PIA the Digital Journey team is working on for BCeID and BC Service Card.

I have a meeting scheduled with Meghan and Stella for next Monday at 9:30. We will be discussing the BCeID Comms plan as well as MyHR content, so perhaps we can add the PIA for BCeID to the agenda as well?

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by NassNK** [comment]
Hi All, 

Just to clarify, here is the information pulled from the PIA about how the BC Services Card process functions within FormsFlow. You'll see on pages 2-4 the description broken into 6 phases with some diagrams (https://app.zenhub.com/files/439477060/314a1b97-c4be-4d2a-b0af-2c0e42dba78b/download)

What I need for the PIA is the same type of process information on how BCeID functions within FormsFlow. @iman-jamali-fw @morezooomm if either of you have some type of documentation that has information on the process for BCeID, I can probably pull together what is needed from anything that's been passed on from the BCeID team.

**Comment by NassNK** [comment]
thanks to @iman-jamali-fw who  provided steps and  links. The PIA has been updated with information regarding the BCeID process and has been sent back to Jennifer for approval/feedback.

**Comment by NassNK** [comment]
Jennifer has reviewed, it's good to go to be submitted and she has gone ahead and sent it off.

**Comment by NassNK** [comment]
PIA and PIA checklist was forwarded to PCT on Feb 07. Should expect a response back within two weeks or so, will follow up next week if needed.

**Comment by NassNK** [comment]
The recommendation is not to pull the User Name and Email address from BCSC, these data points should continue to be pulled through Peoplesoft. The fields that are approved to be linked from BCSC are the Primary Documented Surname, Primary Documented Given, Birth Date. @iman-jamali-fw do you see any issues with this?

**Comment by morezooomm** [comment]
I see no issues with this.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

Government confidentiality and privilege requirements apply to this message and any attachments.  If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately, and delete this message and any attachments from both your inbox and deleted items folder.
***@***.***

**Comment by iman-jamali-fw** [comment]
@NassNK 

We currently use the email from BCSC to auto-populate the forms (1.10 at this point). If we no longer can get the logged-in user's email from BCSC, and instead get it from ODS, it will involve some dev effort from our side.

A question for @T854236 
How we can get employee data such as email from ODS based on the available data that BCSC IDP provides when the user logs in including first name, last name, and `bcsc-user-guid`?

**Comment by T854236** [comment]
@iman-jamali-fw 

Is this the same GUID passed down to ODS?  If so, the employee demographic endpoint has that information and use that as part of filter.

**Comment by iman-jamali-fw** [comment]
@T854236 

This is BCSC-specific guid and is different from IDIR's guid.

**Comment by T854236** [comment]
@iman-jamali-fw

I am checking with the PeopleSoft team.  The field info is in the data warehouse but very limited.  A little over 200 employee records have the BCSC_GUID.

**Comment by NassNK** [comment]
@iman-jamali-fw and/or @T854236 if either of you can provide a couple of sentences explaining the reasoning for why the email address is necessary to come through BCSC instead of PS then we can take that back to the team. 

From their perspective, I believe the recommendation was made under the assumption that if the email address is readily accessible from PS it should come from there however if that recommendation creates complexity, we can bring that to their attention and ask for reconsideration.

**Comment by MeghanStothers** [comment]
@T854236 HI Patrick - can you give us an update on this ticket?

**Comment by T854236** [comment]
@MeghanStothers @iman-jamali-fw 

I just received confirmation from the PS team that it will only contain the BCSC GUID info if employees log into PS with this method.

**Comment by T854236** [comment]
@NassNK @iman-jamali-fw

Employees who log into PS will have the work emails populated. Do you have scenarios to support employees not in PS?

**Comment by NassNK** [comment]
@T854236 @iman-jamali-fw This can be disregarded, the BCSC team has approved the email and user name. They reviewed it internally and confirmed that it is inline with other PSA use cases of BCSC onboarding so both are approved.

**Comment by iman-jamali-fw** [comment]
@NassNK 
Great! Thank you

**Comment by MeghanStothers** [comment]
Signed by all parties and filed today
