### ISSUE TITLE
1.10: Identifying someone as Union & LDB employee

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#784]
The 1.10 form needs identify if an employee is a GEU & PEA employee and an LDB employee right in the beginning, so that we can show the right instructions & send the form to the right address. 

Conditional logic - 

- Ask which union they are a part of, if not GEU or PEA union, then show instructions about where they can file their complaint. 
- If PEA show PSA instructions & send form to PSA mailbox
- If GEU, ask for LDB, if yes show LDB instructions, otherwise show PSA instructions
- If LDB send form to LDB mailbox otherwise PSA mailbox

**Comment by MissionT** [comment]
Can someone check that the logic is flowing correctly?  
To recap, the form will do:
1. Provide the option for a user to identify as a member of BCGEU, if so, ask if they belong to LDB
2. Provide the option for a user to identify as a member of PEA, if so, remove LDB option
3. Provide the option for a user to identify as a member of other to screen out non-members. 
More information such as a possible link to seek out non-member info or other instructions may need to be explored:

See screenshot below:
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/f980883b-5056-4956-bcf1-4904c903dc67)

**Comment by fazil-ey** [comment]
Pending decision in Jan - we may not need LDB in the form

**Comment by MeghanStothers** [comment]
This is the same ticket at #817

**Comment by MissionT** [comment]
The  logic is now complete and can be tested. When the user selects 'other' the text box that appears will need Alert CSS  Styling added.

**Comment by MissionT** [comment]
@bhumin-fw  - Hi Bhumin,  could we connect this morning? I have a few questions.  Thx Chris

**Comment by bhumin-fw** [comment]
@MissionT 
I have attached the workflow (with form 1.10) and it is ready to test on DEV.

In standup, you mentioned about "save changes" and "print as PDF" floating buttons in the form. I can add that if you have query or issue adding those in the form. Please do let me know.

**Comment by MissionT** [comment]
Hi Bhumin,  I received another set up edit changes this from Don this morning. Those changes are now complete. I uploaded the Bullying form to the test env. I will need the floating buttons  like we have in the other forms.  Can you add those. You can make the changes in test or dev. If you make them in the dev env, let me know and I'll upload the form to test again.  Once that is complete, can we check to see that the data is set up to be submitted. Thanks Chris 
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/16f56090-1a6a-44c5-b0b2-17f630d2698f)

**Comment by bhumin-fw** [comment]
@MissionT 
Added both buttons in DEV and TEST, also workflow is attached and works fine.

**Comment by Abuchana** [comment]
@fazil-ey I don't recall us talking about this one, it looks like it can be closed too...?

**Comment by fazil-ey** [comment]
This is implemented & can be closed
