### ISSUE TITLE
Decision on Retaining forms on DJ 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#786]
DJ team to finalize the rules around how long we want to retain drafts and submitted forms in DJ

**Comment by MeghanStothers** [comment]
See if there is a use case for managing/retaining forms  for longer than 60 days - do we need server space? What are our options?

**Comment by fazil-ey** [comment]
Document the time we retain the form in project wiki @Stella-Archer

**Comment by fazil-ey** [comment]
@iman-jamali-fw 
- Is the time 60 days  for drafts after creation or last update
- is there any issue with resources/storage if we keep forms for this long (drafts & submitted)

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 
I've added my documentation for forms retention. Could you please review it and let me know if it meets your expectations? My intention is to add it to the forms documentation section of the repo, which can be found [here](https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md).

I have a couple of questions for you:

What is the retention policy for SL Review forms? We never discussed this, and I was wondering if you had any specific requirements in mind.

What is the retention policy for drafts? Drafts that are submitted are automatically deleted from the system immediately after submission. However, drafts that are still in the Draft tab of the TOOL remain there indefinitely, as we currently don't have a policy or functionality to remove them. If we want to delete these drafts after a certain number of days, we need to create a new ticket and discuss the policy further (for example, after how many days to delete them, whether days are counted from draft creation or draft update, etc.).

**Comment by iman-jamali-fw** [comment]
Two tickets were added to the unanswered questions in this ticket:
* SL Review Completion condition + retention: [#993](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/993)
* Unsubmitted draft retention: [#992](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/992)

**Comment by iman-jamali-fw** [comment]
Ready for review. The form retention table is added [here](https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md#form-retention)

**Comment by Stella-Archer** [comment]
@MeghanStothers could you check with Jodi on the SL retention times?
