### ISSUE TITLE
TOOL:  Add technical rule to reject null forms without GUID and IDIR value (TES Jan change window)

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#788]
As a program area technical team, I want to ensure that any forms without GUID or IDIR value are rejected

**Comment by MeghanStothers** [comment]
@Abuchana I've started the ticket and pulled it into this sprint, thinking we'll want to implement this rule soon (and before the 1.10 form is launched)

We'll need a dev estimate of effort

**Comment by iman-jamali-fw** [comment]
@T854236 

I sent three Telework applications on DEV:
7191 => no bcguid (has idir)
7192 => no bcguid no idir
7193 => no idir (has bcguid)

**Comment by T854236** [comment]
@iman-jamali-fw 

Thanks Iman.  That didn't work as expected.  Restrictions is now on the database level.  Can you try again?

Please let me know if the same can be applied for the schedule column or are there cases where it can be Null.

**Comment by T854236** [comment]
Disregard my question on schedule column, I see there is a scenario for it

**Comment by iman-jamali-fw** [comment]
@T854236 
Just sent one with applicationId 7205. I can see my request to ODS failed with 500 error.

**Comment by MeghanStothers** [comment]
Added Fazil to this ticket with so many folks away today/this week - let's keep an eye on this one

**Comment by T854236** [comment]
@iman-jamali-fw 

Perfect, thank you.  I see in the logs that it rejected it because of missing IDIR value.

**Comment by iman-jamali-fw** [comment]
@T854236 

I sent two more to have all the conditions (IDIR null, GUID null, and both NULL) and can see all three stopped with 500 errors. Which I believe is the expected result we want for this ticket :)

**Comment by T854236** [comment]
@iman-jamali-fw 

Yes, I see 9 tests total.  All expected to test the Null values.  We will add this change to our next BI change in January.

**Comment by MeghanStothers** [comment]
Will go to Telus change window in January - approved
