### ISSUE TITLE
Supervisor receives blank screen in approval process, another cannot attach document or edit comments field

### ISSUE THREAD

**Issue by MissionT** [bcgov/digital-journeys#789]
Background: On Nov 28th, employee Paul S. submitted his telework agreement to his supervisor Amanda Z. Amanda would get a blank screen after selecting the link in the confirmation email sent from the employee. I sent the emails to Iman. 

On Thursday Dec 8th, Sonya M, a director is unable to attach documents or comment in the Manager comments field. She is the direct supervisor to her employee Allan O. I will send this email to Iman this afternoon as well. 

 
Steps to Reproduce: 1)Investigate why a supervisor cannot access her employee's telework agreement to approve.
2) Investigate why another supervisor cannot upload a document or add comments before submitting the form for approval
 
Actual Behavior:  see comments above.
 
Expected Behaviour:1) Supervisor can get into the forms review portal 2) Supervisor can upload a document such as an ADM approval email and make comments in the Manager Comments field. 
 
Environment: prod env for telework form

**Comment by MissionT** [comment]
I am making a ticket for this since my last day  before holidays is on Monday Dec 12th.

**Comment by MeghanStothers** [comment]
@iman-jamali-fw  I forgot to mention this one at scrum today - I have pulled it into the backlog and would love an estimate whenever you can - thanks

**Comment by MeghanStothers** [comment]
Chris wil be here on Monday and then off on hols, so let's grab him for any more info. Cheers

**Comment by iman-jamali-fw** [comment]
@MeghanStothers I'll look into these issues and will update this ticket. Thanks for the headsup.

**Comment by iman-jamali-fw** [comment]
For the issue of `employee Paul S. submitted his telework agreement to his supervisor Amanda Z. Amanda`, the issue lies in the supervisor's Keycloak account that lacks IDIR and GUID. Looking for a fix.

**Comment by iman-jamali-fw** [comment]
For `Sonya M, a director is unable to attach documents or comment in the Manager comments field`, She is most likely trying to upload a document through the PDF she received in the email and NOT the TOOL. I learned that from the emails Chris forwarded and the screenshot of where she tries to upload.

**Comment by fazil-ey** [comment]
@MeghanStothers to action this

**Comment by MeghanStothers** [comment]
I have written a note to Sonja in the Digital Journeys mailbox with the instruction provided by Iman.

**Comment by MissionT** [comment]
This has been completed. Chris.
