### ISSUE TITLE
1.10: Content edits on confirmation page

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#794]
The following changes are needed in content needed for consistency & usability

- [x] Add bullets for the different points in the confirmation message. 
    -  The Public Service Agency (PSA) will notify your union within 10 days of your complaint.
    - You may ask for assistance from your union representative either before or after submitting your complaint 
    - You may also ask your union representative at any time for an update on the status of a review or investigation arising from your complaint
- [x] Change "employer" to "Public Service Agency (PSA)" for non-LDB
- [x] Change "employer" to "Liquor Distribution Board (LDB)" for LDB 

![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/15ba3148-f743-44e6-b06e-9e94af7bfd92)

**Comment by morezooomm** [comment]
The final form name on the top of the form (for both PSA and LDB) should be "Bullying / Misuse of Authority Complaint Form (Article 1.10)".  For the pdf naming, I expect we will have to replace the slash with a dash. 

I am not sure what the reference to adding bullets refers to.

**Comment by MeghanStothers** [comment]
TES Dev (Iman) said that we could replace the slash with a dash). PSA dev team (Stella, Chris, Fazil) to determine the places where this name shows up (form/tool/pdf, etc.) and test with users in January.

**Comment by morezooomm** [comment]
Hopefully, we can keep the slash on the form itself.  Other places, like file names, don’t allow a slash, so a dash will be fine wherever a slash is not allowed.  Cheers!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by fazil-ey** [comment]
@MissionT to action this

**Comment by MeghanStothers** [comment]
Get the logic done first, do testing and then test the language

**Comment by fazil-ey** [comment]
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/bcfe87b0-8337-4213-87e9-c0e8ad85dbb3)

name has been updated
contact is bulleted

**Comment by morezooomm** [comment]
Fazil,

I am unsure what your email below refers to.  I just tested the forms again and found:

  *   The confirmation message when you hit submit needs to be altered for both PSA and LDB versions
  *   The confirmation email to the sender is generic and looks good for both PSA and LDB employees
  *   The confirmation email to the recipient looks good for PSA but needs modification for LDB

This feedback was provided to Chris yesterday and I suspect he will address it when he is back on Monday.  Cheers!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by MissionT** [comment]
Don send us some changes on Thursday Jan 5th in a PDF. Can you please ensure that the confirmation emails will reference LDB should the user select they are part of  LDB?

![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/de470fcf-51b2-4d87-a2ef-360bf6c5e9d5)

**Comment by morezooomm** [comment]
Chris,

I know we are deferring many of the final changes to the form until after user testing is completed this week, but if the change you note below could be made sooner, it would avoid some confusion and user feedback.

It would also be great if we could change the name at the top of the form to “Bullying / Misuse of Authority Complaint (Article 1.10)” asap.  Thanks!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment]
@MissionT @morezooomm 
On test new changes has not been reflect. I have fix issue and now all latest changes are available on TEST too. Please see the attached screenshot for the same. 
Please hard refresh application if you are already logged in in TEST environment to test this changes.
![Screenshot 2023-01-10 at 7.58.09 PM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/b985f74e-e17d-499c-894a-dfcb3f9e9369)

**Comment by morezooomm** [comment]
Thanks Bhumin!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by morezooomm** [comment]
Just noting that on the final point above, Liquor Distribution Board should read Liquor Distribution Branch.  Don

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov to change the fullform for LDB

**Comment by Andrew-Vargas-bcgov** [comment]
Bhumin updated the the success e-mail to "Liquor Distribution Branch".
All form references to "Liquor Distribution Board" have been updated "Liquor Distribution Branch"

**Comment by morezooomm** [comment]
Perfect – thanks.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin
