### ISSUE TITLE
Tool: PDF Styling 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#795]
Ticket created to address PDF styling issues from #666. 

**Tasks**
- [ ] Logo & Form title are in an empty first page [https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/785cfcc4-b1a9-4c5b-946e-95a28a875f7e]

- [ ] remove  'before you begin', 'before teleworking' and other instruction sections. ![https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/d319b9ac-a168-44a0-b1f4-74afedfbcee4]

-----------

**PDF Attachments** 
NEW AOT PDF:
[https://app.zenhub.com/files/439477060/10406841-1bb6-45d5-967b-4b984ddf6eb4/download]
OLD Custom PDF:
[https://app.zenhub.com/files/439477060/7899227a-ac1a-463d-8a41-97f471ab0051/download]

**Comment by iman-jamali-fw** [comment]
@Stella-Archer  This is ready to be tested on TEST. 
Please note that in order to make a component hidden in the server-side pdf, use `hidden-in-print` as a custom CSS for a component like below: 
![Screen Shot 2022-12-20 at 2.00.51 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/e11c8d72-8fbb-4426-9a7b-d690431ebb45)

**Comment by Stella-Archer** [comment]
Sweet @iman-jamali-fw this worked great in DEV.
I will build a little job aid in the wiki for my team so they are all aware of the custom class.
I don't have designer status in TEST if you could change that for me in Keycloak I will confirm this works in TEST and close the ticket

**Comment by iman-jamali-fw** [comment]
@Stella-Archer Added the designer group to your user account on TEST 🙌🏼

**Comment by Stella-Archer** [comment]
Hurray! this worked perfect in TEST as well @iman-jamali-fw thanks for making the new 'hidden-in-print' class! I will move this to 'deploy to PROD'
