### ISSUE TITLE
SL Review: Change error message to address autopopulate error 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#796]
#724 did not address the auto populate issue. It still happens occasionally. To address the confusion cause by having a name in the field but still seeing the validation error for name. 

Change validation error message for employee name to - 

"Enter employee name e.g. Doe Jane is required. If you are seeing this error after the field has been filled, refresh the page and fill the name again. Don't forget to save changes if you don't want to lose your work "

**Comment by bhumin-fw** [comment]
I have updated the save changes condition with one more value.
Could you please confirm the below point?
When you face a similar issue, try to save using "save changes" button on the right-bottom. If it shows a success message in green on the top-right.

If the above case works fine, we can direct the user to click on save changes and go to the draft form, and continue. In this manner, they can retain filled data and the form gets reloaded.

**Comment by fazil-ey** [comment]
@fazil-ey to update the error message

**Comment by bhumin-fw** [comment]
@fazil-ey 
Is it working for you? like click on "save changes" and then start editing in draft form.
It must be work if we are planning to put this message. I'm not able to reproduce this by playing around with hidden fields and a search bar for employee names.

**Comment by fazil-ey** [comment]
@bhumin-fw 
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/0f00eba9-8654-496d-9def-a3cc29f9871a)

**Comment by bhumin-fw** [comment]
@fazil-ey Ohh that's bad. The script that we are using is not working.
The original step looks good to you ? the one with "clear name" and select it again?

If you got some time, could you share what you are doing to reproduce it?

**Comment by fazil-ey** [comment]
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/SL%20Review/Auto%20populat%20error%202%20dec%2019.mov?csf=1&web=1&e=WFGMuO

https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/SL%20Review/Autopopulate%20error%20dec%2019.mov?csf=1&web=1&e=NDoD3t

**Comment by fazil-ey** [comment]
the error message does not last under the name field. The pop up error message does not have the instructions
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Bullying%20-%20Misuse%20of%20Authority%20Complaint%20Form/Autopoulate%20error%20Dec%2021.mov?csf=1&web=1&e=MNM1CC

**Comment by bhumin-fw** [comment]
@fazil-ey 
I have matched both the error messages component and the popup.

**Comment by fazil-ey** [comment]
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/a8894963-de54-417a-aeb1-fa69046de8c7)

![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/2d5fca48-15a2-46a2-bbdf-8b20eba8cb6f)

Error message is clear and valid. Reentering name solves the error
