### ISSUE TITLE
Tool: Open "Contact us" mailto link in new tab

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#798]
Open "Contact us" mailto link in new tab. Currently opens in the same tab. It will just make going back to the forms page easier, especially if you have to refer back to that to write your issue.

**Comment by bhumin-fw** [comment]
@fazil-ey I have deployed it on DEV. It works well on mac os. It needs to check on windows os but on PCOD does not allow me to change the detail mail app to the browser like what you showed yesterday on call.
Could you please confirm on your end on DEV, to open "Contact Us" in the new tab?

**Comment by fazil-ey** [comment]
Tested in Mac OS, works well. @MeghanStothers are you able to test this in Windows?

**Comment by fazil-ey** [comment]
Tested on Windows by Meghan & works as expected
