### ISSUE TITLE
1.10: Exception Cases for Form Access 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#802]
This ticket is to start the conversation about cases for people who cannot access the DJ form.  e.g. people without access to a PC or phone, low computer literacy
- Do we need a paper/pdf form? 
- Privacy risks with paper forms
- Role of the union
- Level of digital acumen
- Maintain level of confidentiality when filling out
- Access to a computer
- Lack of work email address

**Comment by morezooomm** [comment]
The following are my thoughts, to start the conversation.  I invite feedback from everyone.

Challenges/Options
1)	Expect that 80% of LDB staff and 2-3% of PSA staff will not have an active IDIR
       o	Those without an IDIR can get to the form using BCeID or BC Services Card
      o	Option for union rep to help the complainant complete and submit the form
      o	Easy (but limiting) to provide a pdf or paper version of the complaint form
2)	Some employees do not have a personal computer and have no access to one
      o	Those without access can utilize a pc at BC Service Centre for access to form
                (BC Service Centre provides a reasonable level of privacy for complainants)
      o	Union rep could assist complainant with preparation and/or submission of form
      o	LDB/PSA could provide a pdf/paper version and process submission manually
      o	LDB could provide shared pc access for staff within their retail/warehouse sites
                (An LDB shared pcs in open space may not be viable, due to privacy concerns)
3)	Introducing a pdf/paper version of the form could introduce privacy risks
      o	Provide advice and warnings on the form to alert complainants to privacy risks
      o	Restrict where/how paper forms can be submitted by a complainant to PSA/LDB
      o	Follow advice from Jennifer and Igor on how to mitigate privacy/security risks
      o	We already experience similar risks in how we accept and process complaints
4)	Employees do not have a government email address to mail themselves the form
      o	Allow an employee to download the form directly from Digital Journey site
      o	Allow complainants to use their public email address, as they bear the risks
      o	Explore risk mitigation of using public domain emails with the PIA team
5)	Some complainants need help to complete form (i.e., digital literacy, ESL, poor vision)
      o	Union rep can assist complainant with preparation and/or submission of form
      o	Complainant should be able to email a draft form to their union rep for feedback
      o	Complainants can ask a trusted friend to help them complete/submit the form
      o	Complainant can get help from HR staff within their ministry/business unit
      o	PSA (i.e., AskMyHR) or LDB can provide accommodation, as they do now
6)	No mobile version of the form, so will need to use a pc to get access
      o	Not likely a good candidate for mobile use, due to amount of data entry required
      o	Perhaps we can revisit when/if Digital Journey adds mobile capability later

**Comment by fazil-ey** [comment]
@morezooomm do we have any updates on this? are they any tasks that need to be done for the decisions made here?

**Comment by morezooomm** [comment]
This ticket is to start the conversation about cases for people who cannot access the DJ form. e.g. people without access to a PC or phone, low computer literacy

  *   Do we need a paper/pdf form? – yes, we will allow for one
  *   Privacy risks with paper forms – n/a, follow same procedures as currently used
  *   Role of the union – has been drafted, will discuss with ADM on Feb 6
  *   Level of digital acumen – addressed through current help procedures
  *   Maintain level of confidentiality when filling out – alternative private access options identified
  *   Access to a computer – alternative access options identified
  *   Lack of work email address – addressed through BCSC, BCeID, paper version
I am comfortable that the above questions have been sufficiently addressed and we can close this ticket.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin
