### ISSUE TITLE
BC Services Card Initial Setup

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#803]
In order to be able to log into the app, some basic setup is needed of the BC Services Card integration in KeyCloak.

*Acceptance Criteria*
- I'm able to log into the app with a BCSC test account in the dev environment.
- First Name, Last Name, and Email is properly populated in the Auth token passed along to the app

*Technical Details*
- Create a new Identity Provider (keycloak-oidc) in Keycloak named `bcsc`

BCSC Openid config (test env):
https://idtest.gov.bc.ca/login/.well-known/openid-configuration

BCSC Openid config (prod env):
https://test.gov.bc.ca/login/.well-known/openid-configuration

**Comment by Abuchana** [comment]
BC Service Card technical contact: Ryan James

**Comment by iman-jamali-fw** [comment]
Works on DEV and TEST

**Comment by MeghanStothers** [comment]
Iman set up for dev and test - needs to make changes to test. Iman to connect with Simen

**Comment by iman-jamali-fw** [comment]
Ready to be tested on DEV and TEST. Please let me know to pass the test username and password for BCSC logging testing.

**Comment by MissionT** [comment]
@iman-jamali-fw  Hi Iman, Can you tell me where I would find the BcEID (or other) user name and passwords for testing (in the future)?  I would like to put login user name testing user names and passwords on our wiki. thanks Chris.

**Comment by iman-jamali-fw** [comment]
@MissionT 

Hi Chris. For BCeID you can easily register on [here](https://www.bceid.ca/register/basic/account_details.aspx?type=regular&eServiceType=basic)

For BCSC however, there are a few test accounts that are created by the BCSC team for our DEV and TEST environment. I will share them with you in the Team.

**Comment by fazil-ey** [comment]
@MissionT & @Andrew-Vargas-bcgov to test this today

**Comment by MissionT** [comment]
We tested both test and dev environments with the user name and passwords provided. All looks good:  
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/09a25328-7890-4a44-8dab-e350e56934c7)
