### ISSUE TITLE
BC Services Card Integration 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#804]
In order to allow full integration of BCSC for the 1.10 Complaint form, we need to make some changes in order to make sure the Telework Form is not impacted.

**Isolation of Users**
Users that log in with BCSC should be treated as separate users from IDIR users, even if they have the same email address.

**Prefill first name, last name, & email**
- The 1.10 Complaint form should have the first name, last name & email prefilled from your auth token

**Acceptance Criteria**
- When I log in as a BCSC user with the same email address as an existing IDIR user, I cannot see previously submitted applications submitted by the IDIR user
- When I log in as a BCSC user with the same email address as an existing IDIR user, I cannot see tasks the IDIR user is assigned to
- When I log in as an IDIR user, I have access to the same forms/submissions/tasks as before
- When I log in as a BCeID user, I cannot navigate to or submit the Telework form.
- When I start to fill out the 1.10 complaint form after logging in with my BCSC, my first name, last name, and email is prefilled

**Comment by MeghanStothers** [comment]
Sorting out the logic after BCeID work is completed

**Comment by iman-jamali-fw** [comment]
@Stella-Archer This is ready for testing on TEST.

**Form Access**
Each form has a new form access field that determines users by which Identity Providers (IDPs) (e.g., IDIR, BCeID, and BCSC) have been allowed to submit this form. This is done through a hidden form field called `formSupportedIdentityProviders` and its default values.

Telework allows IDIR users and the 1.10 form allows IDIR and BCeID users to access the form. A user with a `designer` group has access to all forms.

To test the form access, you can once access the form with the designer (who should have access to all forms) and once without it.

Documentation was added [here](https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md#form-access)


**Form submission**
Telework: Try to submit as an IDIR user. (you should see your data pre-populated)
1.10 form: Try to submit as an IDIR and **BCeID** and BCSC. (you should see your data pre-populated). Please note that BCSC only provides the first/last/email.

**Comment by Stella-Archer** [comment]
Sweet that worked great Iman thanks.
with BCeID I just see my personal gmail and basic info 
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/14cda1b9-c1f8-4671-85b8-e5ee8f03377c)

**Comment by Stella-Archer** [comment]
However when I first logged into test with my BCeID I could see telework & mat/pat ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/56737d73-7821-4460-9324-686a23615b10)

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 
We currently don't filter forms in the forms list page based on the IDPs. However, this is checked and enforced once the user opens a form. If you want this feature, we can implement that in a new ticket :)

**Comment by Stella-Archer** [comment]
Thanks @iman-jamali-fw  I think we can close this ticket then as ticket #778 addresses what user logging in through BCeID can see  https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/778
