### ISSUE TITLE
Question: Telework field character  limits

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#810]
Can you please advise about character limits in the following fields?

1) Comments on Telework Schedule 

2) Employee Comments

**Comment by MeghanStothers** [comment]
@Stella-Archer This answer is to reply to an email sent to the Digital Journeys mailbox requesting this indo - can you reply with the info Iman shares?

**Comment by iman-jamali-fw** [comment]
Max 255 characters for the `Employee Comments`

For the `Comments on Telework Schedule` currently there is no max limit on the TOOL but I guess there should be a similar 255 limit when it is sent to ODS. @T854236 can help find that limit. I suggest we set the same max character limit on TOOL to not lose data when sent to ODS. @T854236 that field is sent by `scheduleComments` API key.

**Comment by MeghanStothers** [comment]
Thanks - I have replied to the email in the DJ mailbox and we can talk about changing these limits if required.

Closing this ticket! :)
