### ISSUE TITLE
Automate/Update Deployment of three components

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#821]
Updating the continuous deployment of the following components:
- forms-flow-bpm

Automate the deployment of these components:
- forms-flow-forms
- forms-flow-files

AC:
- Images need to be built and pushed within the GitHub Actions

Note: Three components: forms-flow-web, forms-flow-webapi and forms-flow-documents have already been updated.

**Comment by iman-jamali-fw** [comment]
Updating the continuous deployment of the following components:
- forms-flow-bpm
- forms-flow-forms
- forms-flow-files

AC:
- Images need to be built and pushed within the Github Actions


Note: Three components: forms-flow-web, forms-flow-webapi and forms-flow-documents have already been updated.

**Comment by iman-jamali-fw** [comment]
@bhumin-fw 
If this is complete on DEV could you please move it to TEST column for testing the deployment on TEST?

**Comment by iman-jamali-fw** [comment]
The new Camunda deployment tested and worked great on DEV, TEST and PROD. 

I will test the other component and update this ticket.

**Comment by iman-jamali-fw** [comment]
form-flow-forms was successfully tested on DEV and TEST. Will test it on PROD after hours.

**Comment by MeghanStothers** [comment]
Tested on Dev and Prod. Approved to test on Prod after hours.

**Comment by iman-jamali-fw** [comment]
All tested on PROD and worked great. Ready to be closed.

**Comment by MeghanStothers** [comment]
approved
