### ISSUE TITLE
Automated Test Suite Integration

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#822]
Forms-flow-ai comes with a suite of tests that can be integrated into the pipeline. The tests and CI files for GitHub actions are already included in the project for the following components:
- forms-flow-web
- forms-flow-webapi
- forms-flow-bpm
- forms-flow-documents
- forms-flow-data-analysis-api

AC:
- Integrate CI files into the pipeline.
- Make sure all the tests are passing after the integration. Our customizations may have some tests to fail. In this case, those tests would need to be compatible with our changes.

**Comment by iman-jamali-fw** [comment]
Forms-flow-ai comes with a suite of tests that can be integrated into the pipeline. The tests and CI files for GitHub actions are already included in the project for the following components:
- forms-flow-web
- forms-flow-webapi
- forms-flow-bpm
- forms-flow-documents
- forms-flow-data-analysis-api

AC:
- integrate CI files into the pipeline.
- Make sure all the tests are passing after the integration. Our customizations may have some tests to fail. In this case, those tests would need to be compatible with our chagnes.

**Comment by iman-jamali-fw** [comment]
As the first step, Bhumin will connect with Simen to plan for test integration.

**Comment by Abuchana** [comment]
On hold: Will be completed once the upgrade is deployed.

**Comment by fazil-ey** [comment]
This work is complete. Additional work to be done before deployment in a new ticket
