### ISSUE TITLE
1:10: UX test plan for  early January

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#826]
As a user of this form, I would like to have a clear and accessible form (and process) that allows me to submit my compliant.

**Comment by fazil-ey** [comment]
[UX Plan ](https://bcgov.sharepoint.com/:w:/r/teams/03991/Shared%20Documents/Bullying%20-%20Misuse%20of%20Authority%20Complaint%20Form/UX%20Plan%201.10.docx?d=w4e8fbef4683a494abee43be7eb32c78d&csf=1&web=1&e=ymH2Zi)
