### ISSUE TITLE
1.10: Download PDFs missing components

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#827]
In the form "Bullying / Misuse of Authority Complaint Form (Article 1.10)" a few components are not displayed in the downloaded PDF.

Few cases that we have noted down so far,
- Custom component with dropdown values
- Condition-based hidden components.

**Comment by MeghanStothers** [comment]
Bhumin to attach screenshots and more notes to this ticket

**Comment by bhumin-fw** [comment]
**PDF that was sent in an email with missing details.**
[https://app.zenhub.com/files/439477060/23780ea7-550c-4c9e-9fa4-a86db315ec14/download](https://app.zenhub.com/files/439477060/23780ea7-550c-4c9e-9fa4-a86db315ec14/download)

**On the TEST environment submitted the form,** 
https://digital-journeys-test.apps.silver.devops.gov.bc.ca/form/6397a5f77c268bc37d8c1ef3/submission/63a5ae4e7c268bc37d8c4473

**In the email, the correct PDF was sent from the same workflow, at the end of the workflow for PSA-LDB mailbox is here with all components loaded**
[https://app.zenhub.com/files/439477060/62be7ce1-f57f-45af-a21a-d5f75ca375cd/download](https://app.zenhub.com/files/439477060/62be7ce1-f57f-45af-a21a-d5f75ca375cd/download)


@iman-jamali-fw It seems like a timeout for the first PDF that was sent in the email for the recipient and complainant.

**Comment by MeghanStothers** [comment]
to connect with Iman and share the details

**Comment by bhumin-fw** [comment]
@Stella-Archer 
This ticket resolve issue of component render on the form. We have noticed in the 1.10 form that dropdown and data grid ("Add another person" checkbox status and related components) not load properly sometime while we are on form submission, draft form or submitted form page.

This ticket resolve that component render issue, when you click on "Download PDF" button.

**Comment by MissionT** [comment]
This  form has been tested. The downloaded PDF had all the data and form components.  The criteria has been met. This ticket can be closed.

**Comment by MeghanStothers** [comment]
Good to close this one - as per Chris' report
