### ISSUE TITLE
Telework: Retain submitted forms for 60 days 

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#828]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
“As a product owner I want to retain all submitted forms for 60 days so I can mitigate/revover any data loss issues.” 

**Tasks**
TBD

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 
This is ready for testing on TEST. You can complete a Telework form and see if it is still in the submitted tab and not removed like before.

**Comment by iman-jamali-fw** [comment]
@T854236 

Can you verify that these three applications were successfully sent to ODS? Two of them have the new ministry name `Emergency Management and Climate Readiness`.
```
ApplicationId
33151
33152 (emergency ministry)
33153 (emergency ministry)
```

**Comment by T854236** [comment]
@iman-jamali-fw 

We do see it in PROD ODS.
