### ISSUE TITLE
Update workflow for 1.10 based on PSA, PEA or LDB employee

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#830]
conditional logic for access for form has been set up as per below.

If PEA - Show form with PSA instructions, send to PSA mailbox
If BCGEU
a. If not LDB - Show form with PSA instructions, send to PSA mailbox
b. If LDB - Show form with LDB instructions, send to LDB mailbox (LDB specific instructions to be defined)
If Other - Show Other instructions, don't show form

The above instructions have been updated to the form and based on them, need to set up a workflow to send emails with the form PDF, PDF name must be a draft name and needs to fetch the first name and the last name accordingly based on the condition.

If the new form has to have such names as firstName, firstName1, and FirstName2 then the Draft and submitted form names also need to update.

- [ ] Change workflow to prepare the name of the attachment like draft name and send email to PSA/LDB mailbox.
- [ ] Apply condition as per the new form on DraftName and SmittedForm name.

**Comment by MeghanStothers** [comment]
Stella asked Iman to look at the work started by Chris.
Bhumin to add details to the ticket, as well as guidance for Chris.

**Comment by bhumin-fw** [comment]
@MissionT 
I have added a new form "**Test - Bullying / Misuse of Authority Complaint Form (Article 1.10)**". It is the same form you recently updated for Article 1.10.

**Why ?**
- In the form, there are duplicate fields and the name are added dynamically with a sequence number appended to them. e.g. firstName, firstName1, firstName2 and firstName3.
Due to the above naming issue, every time we have to check conditions to identify the field key in the form data. It affects camunda flow, draft & submitted form name on the webpage.

**Updates**
- Keep the form with a name that has not attached the sequence number (in simple, I keep the first block of the form).
- Move the information block at the top and keep the same conditions that you applied earlier. (here condition only applies in the instructions)
- Now the main form. It will only display if you select union and ldb-related fields(if applicable)
For that, I have added an advanced condition in the form builder. Please find the code below.

`
show = false;
if (data.pleaseSelectTheUnionYouBelongTo === 'bcGeneralEmployeesUnionBcgeu') {
  if (data.areYouAnEmployeeOfTheLiquorDistributionBoardLdb !== undefined) {
    if (data.areYouAnEmployeeOfTheLiquorDistributionBoardLdb === 'yes' ||
      data.areYouAnEmployeeOfTheLiquorDistributionBoardLdb === 'no'
    ) {
      show = true;
    }
  }
} else if (data.pleaseSelectTheUnionYouBelongTo === 'professionalEmployeesUnionPea') {
  show = true;
}
`

**Note,**
If you don't have much idea here, please see the below comment on how it works.

> We need to assign **true** or **false** values to the **show** variable in this logic to hide and show the component. You can select other component values using **data** variable and that component's **API Name**.

cc: @Stella-Archer @iman-jamali-fw

**Comment by MissionT** [comment]
This all looks good - works great. This is ready for prod. Chris
