### ISSUE TITLE
Mat/Pat: Auto-populate basic info fields

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#831]
**User Story**
As an applicant i want my basic information to be auto-populated so that I do not have to update it myself

**Acceptance Criteria**
- [ ] The following fields should be auto-populated 
    - Name
    - Ministry 
    - Employee Class
    - Appointment Status - [Aux, K, J etc] _(Question: is there a label associated that can be used?)_
    - Full Time/Part Time - [Full time, Part Time]
    - Mailing address _(Question: if empty can we show home address ? Also PIA implications?)_
     
 - [ ] The fields should not be editable 
 

**Design**
Basic Info screen - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764536515093569&cot=14

**Comment by Andrew-Vargas-bcgov** [comment]
We are only missing Full Time/Part Time - [Full time, Part Time]. It is not available in our current API. Full time employees work 35 hours per week and have an FTE status of 1, while part time employees work less than 35 hours per week and have a FTE status of less than 1 (as per Connie) (e.g. 17.5 hours worked per week would be FTE status of .5).
@T854236 is it possible to add the FTE field from the ODS to the telework API so we can pull that information?

**Comment by T854236** [comment]
@Andrew-Vargas-bcgov 

There is a full_part_time field that can introduce.  Will let you know once available.

**Comment by Andrew-Vargas-bcgov** [comment]
@T854236 Looks good. Added it to our frontend to autopopulate on mat/pat.

**Comment by T854236** [comment]
@Andrew-Vargas-bcgov 

Great, let us know when we can deploy to PROD.

**Comment by ayushdamani** [comment]
![Screenshot (8).png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/d656c720-2947-494b-ae3b-7dbc50d30054)

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov  can you confirm that for Ayush Employee Class & Fulltime/partime is missing in the database or is not being populated?

**Comment by Andrew-Vargas-bcgov** [comment]
Yes, he will not see anything there, but it will populate in production
when we are ready. Employee class currently only available in production.
Full time part time will be added to all environments during our next
deployment.

**Comment by fazil-ey** [comment]
Based on the comment above that 

> Employee class currently only available in production.
> Full time part time will be added to all environments during our next
> deployment.

PO Approved in test, will have to be tested again in production
