### ISSUE TITLE
Mat/Pat : Only show tabs relevant to the applicant based on their choices

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#832]
Only show tabs that are relevant to the the applicant based on the conditional logic defined below

**Logic** 

- All applicants see Before you begin & Employee information screens
    - Eligible for benefits (#612) 
        - If yes, show "Are you a birthing parent" screen, 
        - If no show "Not eligible screen"
    - Are you a Birthing Parent
        - If yes, show maternity leave screens
        - If no,  show "are you applying for parental leave" screen. 
    -  Are you applying for parental leave
        - If "Yes", show parental leave screens
           - Is your partner a BC gov employee
               - If yes, show "verify partner information" screen
               - If no, show "parental leave information" scree
        - If "No" but  "Yes" for birthing parent,  see the confirm supervisor, review, certification & confirmation screens
        - If "No" but  "No" for birthing parent, show form validation error saying "You must take at least one of maternity or parental leave"
    - Maternity or parental leave allowance deferral
       - If deferring any one, show "Defererred allowance" screen
       - If deferring only one, show form validation error saying "You must defer top-up allowance for both parental and maternity leave. You cannot choose to defer top-up allowance for only one leave"

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov 

Tabs are disappearing in the partner info screen ![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/2a8a8cbb-15ff-47e5-8591-e7b250c1027c)

**Comment by fazil-ey** [comment]
The summary, certification tabs only show up after I type the email for supervisor. Not sure if that is intended? I think they should show up along whenever the summary tab shows up 

![Screen Shot 2023-02-23 at 9.30.09 AM.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/22bc8d5f-35d0-4c89-ba03-50af103a65b8)
![Screen Shot 2023-02-23 at 9.30.54 AM.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/f2d1d470-9870-4e0c-98fb-cf82827e093d)

**Comment by fazil-ey** [comment]
The not eligible workflow is not implement yet

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey fixed both issues in dev and moved to test.

**Comment by fazil-ey** [comment]
Retested and looks good!
