### ISSUE TITLE
BCeID Approvals with CITZ/IDIM team

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#834]
As a form owner and program area, we would like to ensure all approvals request by BCeID are in place before the soft launch of the form (March 17 TBD)

The approvals involves showing the BceID team the MVP for launch, which will include the login screen for users to see how and where users will be able to login to the 1.10 form using their BceID (and/or BC services card info)

**Comment by morezooomm** [comment]
Meghan,

I am happy to lead this work.

When we next meet, perhaps you can share what I need to provide, to whom, etc. to get the approval.  Cheers!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin


From: Meghan Stothers ***@***.***>
Sent: January 5, 2023 10:15 AM
To: bcgov/digital-journeys ***@***.***>
Cc: Smallwood, Don PSA:EX ***@***.***>; Assign ***@***.***>
Subject: [bcgov/digital-journeys] BCeID Approvals with CITZ/IDIM team (Issue #834)

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


As a form owner and program area, we would like to ensure all approvals request by BCeID are in place before the soft launch of the form (March 17 TBD)

The approvals involves showing the BceID team the MVP for launch, which will include the login screen for users to see how and where users will be able to login to the 1.10 form using their BceID (and/or BC services card info)

**Comment by MeghanStothers** [comment]
Met today to reviews docs sent by the BCeID team, as well as the requirements.[https://app.zenhub.com/files/439477060/8005b621-656a-4ddd-bb71-5833e0c8dfc5/download](https://app.zenhub.com/files/439477060/8005b621-656a-4ddd-bb71-5833e0c8dfc5/download)

**Comment by MeghanStothers** [comment]
BceID team noted we have met all comms requirements needed for launch: login page, service plans, communications approach. We will still need official sign off on technical work, security, privacy

**Comment by fazil-ey** [comment]
Official sign off received on technical work, security, privacy

**Comment by fazil-ey** [comment]
Official sign off received on technical work, security, privacy
