### ISSUE TITLE
Mat/Pat - showing latest peoplesoft data in draft forms 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#835]
**User Story**
As an applicant I should be able to see my latest data from peoplesoft whenever i open the form (for the first time or a saved draft) so that the latest data is submitted. Submitted forms should show the data submitted. 

Context - We do not want applicants to edit their data in the form itself as consistent data across the form and peoplesoft is important for smooth processing of the applications. 

**Acceptance Criteria**
- [ ] The form shows the latest information from peoplesoft, even after it is saved as draft.
- [ ] Once submitted, the form shows the data that was pulled at the time of submission. 
- [ ] In an active session, the form shows the latest data once the page is refreshed

**Comment by bhumin-fw** [comment]
Moving back this ticket in "Sprint Backlog"
We need to discuss that, draft will contain latest value received from peoplesoft for all the forms or not?

Estimation to apply this change for all form is 3-5 and for single form it's 5. It is on a higher side as for single form we have to add additional condition that work for that form and in future we can apply same change for few more forms. So in future it will be easy like estimating 1 story point for it.

**Comment by MeghanStothers** [comment]
Needs a tester for this ticket @Stella-Archer

**Comment by bhumin-fw** [comment]
@Stella-Archer 
_In this ticket it will continue fetch default data for the form submission page._
Here it will fetch latest data if you open / edit draft. and only replace latest default peoplesoft data if **fields are disabled**.
Please see attached reference UI. And also checkout steps to test it out.
![835-first.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/665cd8df-797f-475f-99c3-cf051ef1c670)
![835-latest.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/83060fc9-b500-464e-af22-43ca99d0d869)

Steps to test this change.
1. Open any form in which we are fetching peopesoft data for some fields. Try to select form in which we have more fields that pre-filled with default values.
2. Form will save in draft by default. You can save it manually.
3. Now click on edit draft and change values in all default fields. (can be done in step 1 too before saving it to draft).
e.g FirstName fetched "Bhumin", change it to "<some text>", and same for some more fields that are pre-filled.

4. Now got to form edit mode. Mark few fields as "disabled" (which are pre-filled by peopesoft data).
5. Go to Draft, select the same form and start edit. Now you will see all disabled fields updated with peopesoft data. and other stay with what value it had.

**Comment by bhumin-fw** [comment]
Changes are deployed to DEV environment.
For my user there is no record in peoplesoft, hence not able to test the same.

Same as above comment, We can test this ticket. Only one change, added one hidden param for additional condition. please see this [document](https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md#fetch-default-values-in-draft) for the same.

**Comment by fazil-ey** [comment]
I am not able to test this because I do not have any peoplesoft data. Relying on ayush's testing to PO approve
