### ISSUE TITLE
1.10: Bug when removing multiple respondents 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#837]
**Steps to reproduce**
1. Open 1.10 form, scroll to respondent section
2. Select "Add another person" checkbox
3. Click "remove section". 

**Expected behaviour**
Respondent should be removed when clicking "remove section". "Add another person" checkbox should be unchecked

**Actual behaviour**
section is not removed. "Add another person" checkbox has to be unchecked manually to remove the first "added" person. 

Remove section works for the subsequent added persons.

**Screen Recording**
https://images.zenhubusercontent.com/439477060/fb500623-1118-4b08-abcf-32412f2e2975/screen_recording_2023_01_05_at_10_30_04_pm.mov

**Comment by bhumin-fw** [comment]
Added other ticket [#841](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/841) for the same issue.
