### ISSUE TITLE
1.10: Changes for LDB section on the form

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#839]
1. Change the last point in instructions to 
"All personal information is collected in accordance with section 26(c) of the Freedom of Information and Protection of Privacy Act (FOIPPA) for the purposes identified above. Any questions or concerns regarding the collection of your information may be directed to by submitting a request to employee.relations@bcldb.com"

~2. Change "Your government email address" to "Your email address" in Written Complaint section
_(Question: Are there any constraints on the email?)_~

3. Make "Your Ministry" optional in Written Complaint Section

4. Change "Government email address:" to "Email address" in Recipient of written complaint section

5. Change  Public Service Agency (PSA) to Liquor Distribution Board (LDB) in the Next Steps section

**Feedback document attached for reference** 
[https://app.zenhub.com/files/439477060/2684f101-ea4d-4291-8473-ea010fc52d97/download](https://app.zenhub.com/files/439477060/2684f101-ea4d-4291-8473-ea010fc52d97/download)

**Comment by morezooomm** [comment]
On point 5, it should read Liquor Distribution Branch, not Liquor Distribution Board.

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov to change the fullform

**Comment by Andrew-Vargas-bcgov** [comment]
1. Updated [employee.relations@bcldb.com](mailto:employee.relations@bcldb.com) to be an e-mail link.
2. The e-mail field gets updated to display "Your preferred email" when the user selects that they are LDB.
3.  Field is optional.
4. Updated to "Recipient's email address"
5. Changed all instances of "Liquor Distribution Board" to "Liquor Distribution Branch".

**Comment by morezooomm** [comment]
Andrew,

This all looks good to me, with two exceptions:

  *   If I first select LDB, then check “not LDB” when opening the form, it leaves “Liquor Distribution Branch” as the default ministry/organization.  Once I checked “not-LDB”, it should clear that field?
·        When I identify as being from LDB, in the first bullet of “Before you submit” the text reads:
o    “When you submit your complaint, it will be automatically sent to you, the recipient and to the LDB Employee Relations Department, Public Service Agency (PSA), who will provide a copy to your union within 10 days”
o    It should read: “When you submit your complaint, it will be automatically sent to you, the recipient and to the LDB Employee Relations Department, Liquor Distribution Branch (LDB), who will provide a copy to your union within 10 days”  [changes highlighted]
Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin
