### ISSUE TITLE
Bullying 1.10 Form - Add another person 

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#841]
Background:  After a user selects the check box to  add another person (the person who bullied) to the form, the fields appear to enter the person's name, ministry etc.  If they decide to delete that section due an error, the fields will still show. Can we have the fields also be hidden?
 
Steps to Reproduce: User will add another person by selecting the check box (Add another person), the fields will appear, the user enters the information, the user then decides to delete that information.   *New request: the fields will be hidden after the user select the delete button labelled, Remove Section.
 
Actual Behavior: After a user adds another user under:  "Who are you making your complaint against?", and then deletes that group of fields via the Delete button (Remove Section), the fields still appear blank. 
 
Expected Behaviour: Have the fields hidden after the user deletes the field. They must then select the check box again to add another user. This is to avoid having empty fields remain on the form after a user decides not to include another person after all. 
 
Environment: Dev
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/ccb47b34-3d37-44f0-b4ed-977104fdda2f)

**Comment by morezooomm** [comment]
Chris, I agree with the comments attached to this ticket.

That said, I am not sure if you are asking me for something more on this one?

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment]
@MissionT @morezooomm 
I found one basic solution please comments below.

If we have more than one sections available it will looks same as it.
![show.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/94e8c552-7d38-4d66-9361-c14636f49e5e)

I have prepared small script that hide "Remove Section" if only one element is remain.
![hide.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/cb566cb0-59ff-4820-88fc-2119b2549b15)

To hide or clear all the value from the last section, user must "uncheck" the value of "Add another person". It will hide and clear value from all the fields.
Note: If you check the checkbox again then it will show with validation error message for all the required fields in section. please below image for your reference.
![hide-show-again.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/3195ca1a-9044-4f1c-8abe-02c588577959)

**Comment by morezooomm** [comment]
Bhumin,

Your proposed solution sounds good.

I will be conducting further tests this weekend and will include this scenario in my testing.  Cheers!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by morezooomm** [comment]
I think we can close this ticket for now.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment]
Thanks Don, Moving it to closed.

**Comment by MeghanStothers** [comment]
Reopening this ticket as this bug showed up in testing after March 3 deployment.

Note: we cannot process the form as it gets validation errors, which is a high priority barrier for someone completing/submitting the form.

@iman-jamali-fw and @bhumin-fw

**Comment by iman-jamali-fw** [comment]
@bhumin-fw Do you have time to look into this?

**Comment by bhumin-fw** [comment]
@iman-jamali-fw @MeghanStothers 

A validation error throws if the checkbox is selected.
The proposed solution will hide the "Remove Section" button in the case of the last section. But the user still needs to uncheck that checkbox if they don't want to add another person's detail.
![1.10_add_another_person.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/4dfa8da2-d25b-492d-aca2-841459fb7a82)

**Comment by Andrew-Vargas-bcgov** [comment]
@bhumin-fw Since the "Remove Section" button already has logic to determine if it is the last element in the data grid array, could we also fire off an event to uncheck the "addAnother" checkbox? This would hide that last element, and the default logic already clears the fields.

**Comment by morezooomm** [comment]
Sounds good to me and better than the option I identified.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

Government confidentiality and privilege requirements apply to this message and any attachments.  If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately, and delete this message and any attachments from both your inbox and deleted items folder.
***@***.***

**Comment by bhumin-fw** [comment]
Hi @morezooomm @chriscaldwell-psa  @Andrew-Vargas-bcgov @Stella-Archer 

**I have implemented below solution on DEV and TEST. It will replace "add another person" CHECKBOX with BUTTON.**

![replace-with-button.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/45d68e95-f688-41a7-a536-df7c7912dadf)

**Also if checkbox is required and we cannot hide/remove it, based on UI perspective (Non technical). Please see solution as per below.**

![keep-checkbox-add-remove-all.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/88f15a75-1b2c-49d2-8927-27dff8ae14a0)

**Comment by MeghanStothers** [comment]
PO approved
