### ISSUE TITLE
1.10: Default ministry name for LDB 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#844]
If complainant is an LDB employee, autofill ministry to "Liquor Distribution Board". Also, make the field non editable.

**Comment by bhumin-fw** [comment]
@fazil-ey 
Updated changes on both environment. Please let me know to whom I assign this ticket for testing.

**Comment by morezooomm** [comment]
LDB stands for Liquor Distribution Branch, not Liquor Distribution Board.  Don

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov to change

**Comment by Andrew-Vargas-bcgov** [comment]
- Updated the label to display "Liquor Distribution Board". It will now show this to the user for every instance across the form. 
- I left the value as "LiquorDistributionBoard" just in case there was any backend logic that interacted (although I don't think there is).
- I updated the calculated field logic that auto populates LDB in ministry/org field.
- Looks like @bhumin-fw already updated the success e-mail to "Liquor Distribution Board".

**Comment by morezooomm** [comment]
Sorry, there is no business unit called “Liquor Distribution Board”.

All references to LDB, on all tickets, should read “Liquor Distribution Branch”.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin
