### ISSUE TITLE
1.10: No email to be sent to LDB employees giving non gov email addresses

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#845]
For LDB employees, if email provided by complainant in "Your preferred email" is NOT a **gov.bc.ca or bcldb.com** email (e.g. a personal gmail or hotmail address) then 

1. no email should be sent to the complainant after submission
2. an additional note should be added in confirmation message that says that to access or download the pdf of the form they need to come to the DJ portal (@morezooomm to provide copy) 
    - Additional copy for confirmation message  -  "You may access or download a copy of your complaint by visiting the [Digital Journey portal](Add link to the DJ portal so that its easy for complainant to know where to go to access their submitted forms

Add this line to the existing copy - 
"You may access or download a copy of your complaint by visiting the [Digital Journeys portal](http://digital-journeys-apps.silver.devops.gov.bc.ca/form)"

Update 
- Add link to the DJ portal so that its easy for complainant to know where to go to access their submitted forms (For all complainants receiving the email)
   Add this line to the existing copy - 
   "You may access or download a copy of your complaint by visiting the [Digital Journeys portal](http://digital-journeys-apps.silver.devops.gov.bc.ca/form)"

**Comment by bhumin-fw** [comment]
@fazil-ey @morezooomm 
Right now we are sending 3 email.
1. Recipient
2. complaint (user itself)
3. Mailbox (PSA/LDB)

Ticket says we should not send an email to "complaint" if email domain is not gov.bc.ca or bcldb.com.

Do we need to check same condition for "Recipient" email as well?

**Comment by morezooomm** [comment]
Bhumin:

We should always send a confirmation email to the person submitting the complaint (the complainant).  In most cases, where they use a bc.gov.ca or bcldb.com email address, that email would include an attached pdf copy of the complaint.

In cases where the complainant is not using a gov.bc.ca or bcldb.com email address, we should still send them the confirmation, but not attach the pdf.  In these cases, the confirmation should state that the complainant has to download a copy of the complaint from the Digital Journey site and we should provide a link to the site.

In the case of recipients, the use of a gov.bc.ca or bcldb.com email address should be mandatory, and a pdf copy of the complaint should be attached.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment]
@morezooomm 
That make sense and clear my queries too.

We are sending below paragraph in the email in case of LDB.
"Attached is a copy of the complaint you just submitted to your employer regarding bullying / misuse of authority complaint under article 1.10 of the collective agreement. You may ask your Union representative at any time for an update on the status of a review or investigation arising from your complaint."

Now, We should change it. like below in case of LDB that does not have gov.bc.ca or bcldb.com email.
"
Attached is a copy of the complaint you just submitted to your employer regarding bullying / misuse of authority complaint under article 1.10 of the collective agreement. You may ask your Union representative at any time for an update on the status of a review or investigation arising from your complaint.
You may access or download a copy of your complaint by visiting the Digital Journey portal at [URL for DJ portal]
"

**Comment by morezooomm** [comment]
Bhumin,

I propose using the following, shorter version, which would cover either PSA or LDB.


Proposed PSA/LDB content if they provide a bc.gov.ca or bcldb.com email address (pdf copy of complaint attached):

"Attached is a copy of the complaint you just submitted regarding bullying / misuse of authority under article 1.10 of the collective agreement. You may ask your union representative at any time for an update on the status of a review or investigation arising from your complaint."

Proposed PSA/LDB content if they do NOT provide a bc.gov.ca or bcldb.com email address (no pdf attached):
"You just submitted a complaint regarding bullying / misuse of authority under article 1.10 of the collective agreement. You may ask your union representative at any time for an update on the status of a review or investigation arising from your complaint.  You may also access or download a copy of your complaint by visiting the Digital Journey portal at [URL for DJ portal].”


Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment]
@fazil-ey @morezooomm 
It's deployed on DEV and TEST. If LDB with gov.bc.ca and bcldb.com then they will receive PDF if not then they won't get attached PDF in the confirmation email.
Other 2 emails, recipient and PSA/LDB mailbox will receive PDF in all the cases.

Also I have updated content on mail based on above last comment.

**Comment by bhumin-fw** [comment]
@morezooomm 
"Bhumin,
Comments embedded below."

Not getting above message. Could you please share your comment again if any for this ticket?

**Comment by fazil-ey** [comment]
"It's deployed on DEV and TEST. If LDB with gov.bc.ca and bcldb.com then they will receive PDF if not then they won't get attached PDF in the confirmation email. This logic is correct and supported by tests I just ran. Good work.
Other 2 emails, recipient and PSA/LDB mailbox will receive PDF in all the cases. Correct – looks good.

Also I have updated content on mail based on above last comment." 

i think this is thew comment embedded - so things work okay.

**Comment by morezooomm** [comment]
Bhumin,

Sorry about that.  Content from my previous email of Jan 16 at 2:04 was:

It's deployed on DEV and TEST. If LDB with gov.bc.ca and bcldb.com then they will receive PDF if not then they won't get attached PDF in the confirmation email.  This logic is correct and supported by tests I just ran.  Good work.
Other 2 emails, recipient and PSA/LDB mailbox will receive PDF in all the cases.  Correct – looks good.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin
