### ISSUE TITLE
1.10: Edits to field labels/content in the form  

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#846]
1. Change field "Your Ministry" to "Your Ministry or organization"
2. For LDB change 
    - "Your email address" to "Your preferred email address"
    -  **Remove form validation that this email has to be a govt email address**
    - "Your telephone number" to "Your preferred telephone number"
3. For non-LDB change 
    - "Your email address" to "Your government email address"
    - "Your telephone number" to "Your government telephone number"

4. Remove the following text from "Details of your complaint"
"Describe what as said or done (words, tones, actions) in each incident. When and where did the incident(s) happen (e.g., dates, times, and locations)? Use approximate dates if exact dates are not known. 

Should your complaint result in an investigation, you will be contacted if  additional details such as documents, emails, or photographs to support your case are required." 

5. Change "Describe what happened." to 

"Describe what happened. Describe what as said or done (words, tones, actions) in each incident. When and where did the incident(s) happen (e.g., dates, times, and locations)? Use approximate dates if exact dates are not known. 

Should your complaint result in an investigation, you will be contacted if  additional details such as documents, emails, or photographs to support your case are required. 

**Update Jan 13** - also remove - "As a reminder, use this section to describe each incident regarding your complaint of bullying between peers or misuse of managerial authority as outlined in Article 1.10 of your BCGEU or PEA collective agreement. "

You can drag the field to expand if needed. Do not exceed 2,500 words"

6.  remove note "Note: Maximum of 2,500 words."

7. Add word limit, 250/2500 words, as a placeholder for the "Details of your complaint" fields

**Comment by MissionT** [comment]
All steps from 1 to 7 are completed. Andrew/Chris

**Comment by fazil-ey** [comment]
@MissionT 
Can we also remove "As a reminder, use this section to describe each incident regarding your complaint of bullying between peers or misuse of managerial authority as outlined in Article 1.10 of your BCGEU or PEA collective agreement. " from the details of your complaint section. 

I think i missed it in the ticket! my apologies!

**Comment by fazil-ey** [comment]
This is implemented & can be closed
