### ISSUE TITLE
Camunda incident review - Users with no IDIR or/and GUID

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#847]

**Comment by iman-jamali-fw** [comment]
A new check for data that is sent to ODS has recently been added that stops data from being sent to ODS if a user has no IDIR/GUID. This affected users whose IDIR/GUID were null and had in-progress submissions with null IDIR/GUID at the time the check were added.

These cases are [reported as incidents in Camunda Cockpit](https://digital-journeys-camunda.apps.silver.devops.gov.bc.ca/camunda/app/cockpit/default/#/process-definition/teleworkform:21:77e47a71-5fcd-11ed-899a-0a580a6190dc/runtime?searchQuery=%5B%5D&viewbox=%7B%22Definitions_0993co4%22:%7B%22x%22:-4918.737777777777,%22y%22:-4789.235555555555,%22width%22:11866.666666666666,%22height%22:2382.222222222222%7D%7D&detailsTab=pd-incidents-tab). Currently, around 14 incidents reported are needed to be resolved.

AC:
- Send the affected user data to ODS through Camunda.
- Make sure IDIR/GUID is added to their data.

**Comment by iman-jamali-fw** [comment]
@T854236 

We have a number of users with submissions in Camunda who had in-progress submissions when you added a check for null IDIR and GUID on the ODS side. As a result, these users failed to submit their data to ODS.

I manually added their IDIR and GUID and resubmit their data to ODS. Can you please check to see if their data is received on your end? Thank you


application_id:
28011
26351
26195
27037
27983
25988
26347
28238
27116
27918
26963
27024
27023
25952
26433
26435
26003
26665
27046
25943
26519
26181
28425
28281
26444
27844
26083
28341
25946
28375
26452
26284
25697
27710
26703
26440
28323
28121
28062
26013

**Comment by T854236** [comment]
@iman-jamali-fw 

Confirm I see all 40 entries.  There a total of 63 records received today so far.

**Comment by iman-jamali-fw** [comment]
@T854236 

Awesome! 🎉 Thank you
