### ISSUE TITLE
DGJ Vulnerability Assessment & Penetration Testing for BCSC/BCeID

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#849]
Address Critical & High vulnerabilities before Feb 17 

@iman-jamali-fw @warrenchristian1telus Kunal & Igor to address issues

**Comment by iman-jamali-fw** [comment]
During the BCSC/BCeID check-in meeting, their team said that a Penetration Test for all the DGJ components that are connected to BCSC/BCeID might be required.

For more info refer to their `Key Milestones and Deliverables Table for BCSC + BCeID` document in `security => Dynamic Vulnerability Assessment; & Penetration Test`

**Comment by fazil-ey** [comment]
@warrenchristian1telus can you take a look at this and tell if this is required?

**Comment by warrenchristian1telus** [comment]
Hi @fazil-ey - yes, penetration testing is a requirement for BCSC/BCeID. I'm still investigating the finer details and options, but we will definitely need to meet this requirement to implement (either of) these authentication methods.

**Comment by iman-jamali-fw** [comment]
@warrenchristian1telus 
Based on the last check-in with the BCeID+BCSC team, _Penetration Test_ is not needed but we need to have a _Dynamic Vulnerability Assessment_

**Comment by warrenchristian1telus** [comment]
Thanks @iman-jamali-fw. Can we confirm what the "Dynamic Vulnerability Assessment" entails? To me, this sounds like ACS dashboard, which is already in place. Assessing the vulnerabilities is one thing. Remediating them is another. I think we will need to determine what constitutes done / approved here. Do we need a review by someone? Do we need to eliminate any Critical / high vulnerabilities (that are classified as fixable)? Do we just need to get to a "Policy Status = Pass" on ACS?

**Comment by fazil-ey** [comment]
we may not need to do Penetration testing @warrenchristian1telus

**Comment by Abuchana** [comment]
Dynamic Vulnerability Assessment; & Penetration Test	PSA	Feb 3, 2023
	
COMPLETE - Results provided to IDIM. Critical and High vulnerabilities will need to be remediated prior to configuration in PRODUCTION environment.

Dec 20, Kit confirmed penetration test will be bypassed
Jan 3, David confirmed dynamic scan will be required
Jan 4, kit confirmed the Pen test to be bypassed (Using BC Dev Ops – OpenShift)
Jan 10, Kit still confirming if the Pent test will be bypassed; Kit explained to client what testing will be required
Jan 11, Kit sent email to Deb requesting to bypass Pen test; awaiting response
Jan 17, Kit confirmed response has not yet been received; kit provided additional info to Jamali on the DVA scan
Jan 24, Kit confirmed response has not yet been received
Jan 31, Kit received approval to bypass Pen test, with the recognition that the penetration test was done previously.
Feb 3, David confirmed the scan results are listed in the STRA and deliverable is complete

**Comment by iman-jamali-fw** [comment]
As of Feb 9, all the vulnerability updates from Snyk are deployed to DEV and TEST. Currently, there is no outstanding Snyk PR in the repo.

**Comment by MeghanStothers** [comment]
based on meeting - Iman updated components: Redash and dev and test. If everything work Iman will deploy to prod

**Comment by MeghanStothers** [comment]
Warren had the security dashboard down to two issues and sees many more overnight - will investigate

**Comment by iman-jamali-fw** [comment]
Redash was updated on PROD

**Comment by warrenchristian1telus** [comment]
After review with Igor, we've concluded that the undertaken efforts have been enough, and we should be clear to proceed. He will need to verify that with the powers that be, but I believe we're set as far as mitigating all the critical/high/medium vulnerabilities.
