### ISSUE TITLE
Telework Agreement  - Manager cannot edit  forms for 4 employees .

### ISSUE THREAD

**Issue by MissionT** [bcgov/digital-journeys#854]
Background: A manager contacted DJ with not being able to edit and approve 4 of her employees' telework agreements. 
She has cleared her cache, restarted her laptop, confirmed her email is correct and indicated that she is their direct supervisor and has been able to approve other agreements in the past. When watching her perform the steps in a screenshare, she was not able to select check boxes etc. 
 
Steps to Reproduce:  Not sure if this is keycloak issue or other issue? Steps to reproduce needs to be discussed first with devs.
 
Actual Behavior: Manager received 4 telework agreements from her staff, select the link in the body of the email, the forms portal opened, she selected the employees pending agreement, once the form was open, she was unable to select components such as check boxes.  The form seems to be frozen. 
 
Expected Behaviour: Typical behaviour is required
 
Environment: Prod. (below is screen shot of the manager unable to select the check box)

![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/fd7e7fed-7c18-418e-8552-b19135cec7c4)

**Comment by MissionT** [comment]
This is the email I received from the manager: 
Hello there, 

I am trying to approve telework agreements for 4 of my reports, but the form will not let me click into the fields I need to fill out. 

There are no flags indicating that I have missed any required boxes. I simply can’t click into any fields except Manager name or decision, and the form won’t let me submit either.

I previously approved telework agreements for these same people before, so I believe my permissions should be fine. 

Can you help?

Thanks,
Stephanie

**Comment by iman-jamali-fw** [comment]
@MissionT 

I checked her account and everything seems fine. Her Keycloak account has IDIR and GUID, has manager group and below four applications correctly assigned to her as their manager. Can you please ask her to try again with these links?

 

https://digital-journeys.apps.silver.devops.gov.bc.ca/task/4e2dc064-920b-11ed-aa76-0a580a61333d
https://digital-journeys.apps.silver.devops.gov.bc.ca/task/087feb82-920b-11ed-aa76-0a580a61333d
https://digital-journeys.apps.silver.devops.gov.bc.ca/task/2fc3e9d4-920a-11ed-aa76-0a580a61333d
https://digital-journeys.apps.silver.devops.gov.bc.ca/task/248668f2-920a-11ed-aa76-0a580a61333d

**Comment by fazil-ey** [comment]
@MissionT has been fixed, nothing in the inbox to indicate this is still an issue. Closed.
