### ISSUE TITLE
1.10: New Copy for Next Steps 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#855]
We want to address the following in the next steps 
- [x] Change section title "Next Steps" to "Before you submit"

- [ ] Change copy of Next Steps to (with bullets) For PSA 
" 
- When you submit your complaint, it will be automatically sent to you, the recipient and to the Director of Investigations & Intake, Public Service Agency (PSA), who will provide a copy to your union within 10 days. 
- You may ask your union representative at any time for an update on the status of a review or investigation arising from your complaint
- You may access a copy of your draft or submitted complaints on the Digital Journeys portal for 60 days

"
For LDB - 
" 
- When you submit your complaint, it will be automatically sent to you, the recipient and to the Liquor Distribution Board (LDB), who will provide a copy to your union within 10 days. 
- You may ask your union representative at any time for an update on the status of a review or investigation arising from your complaint
- You may access a copy of your draft or submitted complaints on the Digital Journeys portal for 60 days

"

**Comment by morezooomm** [comment]
Fazil,

We have already addressed points 1, 3 and 4 below in our discussions this week, and in the written feedback I will provide this weekend.

Regarding point 2, I would defer this for now.  We will be building material of this sort to put onto MyHR and/or in topic guides, but that material will not be ready until very near the launch date.

We can review at that time if a link from the form to this new material is still needed.  For example, the “micro-help” material I provided earlier today on what “alternative dispute resolution” and “investigation” mean may suffice.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin


From: fazil-ey ***@***.***>
Sent: January 13, 2023 8:51 AM
To: bcgov/digital-journeys ***@***.***>
Cc: Smallwood, Don PSA:EX ***@***.***>; Mention ***@***.***>
Subject: [bcgov/digital-journeys] 1.10: New Copy for Next Steps (Issue #855)

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


We want to address the following in the next steps

  *   Be more specific as to who the form is going to go to
  *   Add a link to the 1.10 process to ensure people understand what they can expect
  *   Change "Next Steps" to "Before you Submit"
  *   Ensure we say that the complainant will also receive an email

@morezooomm<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmorezooomm&data=05%7C01%7CDon.Smallwood%40gov.bc.ca%7C9fc78cbfc3a94dc0e46808daf5864c41%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638092254391123714%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WLthIKhp%2Fd8aEFoxVCwLd55uenUzIUn%2FFqFreG0%2BbpY%3D&reserved=0>

**Comment by MissionT** [comment]
Next steps panel completed.

**Comment by fazil-ey** [comment]
@morezooomm can you confirm what the copy for LDB should be for point # 1

"When you submit your complaint, it will be automatically sent to you, the recipient and to the Director of Investigations & Intake, Public Service Agency (PSA), who will provide a copy to your union within 10 days."

**Comment by morezooomm** [comment]
Fazil,

The version to send to LDB is:

"When you submit your complaint, it will be automatically sent to you, the recipient and to Employee Relations, Liquor Distribution Branch (LDB), who will provide a copy to your union within 10 days."
Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by morezooomm** [comment]
Fazil,

I have reviewed the bullets for #855 and offer the following feedback:

For the PSA version of copy in the “Before you submit” section, it all looks good, except:

·        In the third bullet, the Digital Journeys portal should be a URL, to take them to the portal?
For the LDB version of copy in the “Before you submit” section, it all looks good, except:

  *   In the first bullet, “LDB Employee Relations Department, Public Service Agency (PSA)” should read “Employee Relations Department, Liquor Distribution Branch (LDB)”.

·        In the third bullet, the Digital Journeys portal should be a URL, to take them to the portal?
Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by fazil-ey** [comment]
@MissionT has implemented this
