### ISSUE TITLE
1.10: Add Contact us button

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#856]
Add contact us button to the form that links to union contact information on Careers & myHR. The link should be based on the union selected in the form - BCGEU or PEA. 
Question: What will we link it to before a union is selected? Can we show the button only after selection?

This will help ensure queries about filling the form are directed to the union instead of AskMyHR

@morezooomm to provide links for the contact us button

**Comment by couvrez1111** [comment]
I can add the contact us button and conditionally render it based upon union selection, so that the button will take the user to the correct union information.
@morezooomm I believe we just need the link to pages you would like the button to point to (PEA and BCGEU).

**Comment by morezooomm** [comment]
Andrew,

I like the approach you describe below, but I will not have content to point to until just before startup in March.  I will first have to build that content for the MyHR website and a new topic guide.

I think we should defer putting the Contact Us button on the form until that time, in which case we could move this ticket to the parking lot for now?  Cheers!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by morezooomm** [comment]
Fazil,

Works for me.

We can revisit shortly before our launch, to see if we have relevant content by then.  Cheers!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by Stella-Archer** [comment]
duplicate issue to #907 closing this tix
