### ISSUE TITLE
1.10: Explain the terms "alternate dispute resolution" & "investigation" in the form

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#857]
**Task**

- Add tooltip next to the terms "alternate dispute resolution process" and "investigation" in the text "Are you open to participating in an alternate dispute resolution process, rather than an investigation?"

Copy for tooltips - 

Alternative dispute resolution – conducted through the Conflict Management Office in PSA, a neutral facilitator helps the parties reach a voluntary resolution of your complaint. This can often be completed within weeks of commencing the process.

Investigation – conducted under the Public Service Employment Act, an unbiased investigator will review concerns raised in your complaint and collect any relevant or missing information. This process may take several months to complete.

Tooltip - 
 ![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/9104e793-1d5f-4c59-bf0b-993efda55e57)

--------

In UX testing we found that people are not very familiar with what alternate dispute resolution & investigation means and therefore are not likely to make an informed decision. 

2 solutions have been proposed - 
- tooltip to explain what the terms mean
- link to resources/pages that explain what the terms mean

@morezooomm to decide the solution and provide copy/resources

**Comment by morezooomm** [comment]
My proposed content for these two terms would be:


  *   Alternative dispute resolution – conducted through the Conflict Management Office in PSA, a neutral facilitator helps the parties reach a voluntary resolution of your complaint.  This can often be completed within weeks of commencing the process.

·        Investigation – conducted under the Public Service Employment Act, an unbiased investigator will review concerns raised in your complaint and collect any relevant or missing information. This process may take several months to complete.
Not sure if that is too long for micro-help/tool tip, but if it works, we could put it there for now?

If we need a URL link, we will likely have to defer that for now on the form, as we first need to build content for MyHR and a topic guide.  Once that work is done (likely very close to launch date) we could leverage some of that content for the URL.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin


From: fazil-ey ***@***.***>
Sent: January 13, 2023 10:34 AM
To: bcgov/digital-journeys ***@***.***>
Cc: Smallwood, Don PSA:EX ***@***.***>; Mention ***@***.***>
Subject: [bcgov/digital-journeys] 1.10: Explain the terms "alternate dispute resolution" & "investigation" in the form (Issue #857)

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


In UX testing we found that people are not very familiar with what alternate dispute resolution & investigation means and therefore are not likely to make an informed decision.

2 solutions have been proposed -

  *   tooltip to explain what the terms mean
  *   link to resources/pages that explain what the terms mean

@morezooomm<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmorezooomm&data=05%7C01%7CDon.Smallwood%40gov.bc.ca%7Ca82556e9ee604f98942e08daf594add3%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638092316157334810%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GrGT%2BDTlKWHuoqoLkbhPZduBCV%2FEKqft9opDrxuqD5k%3D&reserved=0> to decide the solution and provide copy/resources

**Comment by morezooomm** [comment]
I just noticed an error below, as it should read “Public Service Act”, not “Public Service Employment Act”.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin


From: Smallwood, Don PSA:EX
Sent: January 13, 2023 11:03 AM
To: 'bcgov/digital-journeys' ***@***.***>; bcgov/digital-journeys ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [bcgov/digital-journeys] 1.10: Explain the terms "alternate dispute resolution" & "investigation" in the form (Issue #857)

My proposed content for these two terms would be:


  *   Alternative dispute resolution – conducted through the Conflict Management Office in PSA, a neutral facilitator helps the parties reach a voluntary resolution of your complaint.  This can often be completed within weeks of commencing the process.

·        Investigation – conducted under the Public Service Employment Act, an unbiased investigator will review concerns raised in your complaint and collect any relevant or missing information. This process may take several months to complete.
Not sure if that is too long for micro-help/tool tip, but if it works, we could put it there for now?

If we need a URL link, we will likely have to defer that for now on the form, as we first need to build content for MyHR and a topic guide.  Once that work is done (likely very close to launch date) we could leverage some of that content for the URL.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin


From: fazil-ey ***@***.******@***.***>>
Sent: January 13, 2023 10:34 AM
To: bcgov/digital-journeys ***@***.******@***.***>>
Cc: Smallwood, Don PSA:EX ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [bcgov/digital-journeys] 1.10: Explain the terms "alternate dispute resolution" & "investigation" in the form (Issue #857)

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


In UX testing we found that people are not very familiar with what alternate dispute resolution & investigation means and therefore are not likely to make an informed decision.

2 solutions have been proposed -

  *   tooltip to explain what the terms mean
  *   link to resources/pages that explain what the terms mean

@morezooomm<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmorezooomm&data=05%7C01%7CDon.Smallwood%40gov.bc.ca%7Ca82556e9ee604f98942e08daf594add3%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638092316157334810%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GrGT%2BDTlKWHuoqoLkbhPZduBCV%2FEKqft9opDrxuqD5k%3D&reserved=0> to decide the solution and provide copy/resources

**Comment by MissionT** [comment]
To add tooltips next to the terms would require CSS styling by the developers. We will need to discuss if this is a MPV and if the cost warrants a ticket. ![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/006f53ff-d17a-49fa-813e-e9093278d1c2)

**Comment by morezooomm** [comment]
This is not an MVP, but it would be nice to add before we go live on March 17.

Perhaps we should move this one to the icebox for now and revisit once we are closer to launch date?  We plan to revisit other tickets around the same time that could leverage built for MyHR or the topic guide by then.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by MissionT** [comment]
We cannot add a tool tip above each term. Please see the next best option: 
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/79d71edf-9129-41a7-a7a4-851442ab80c7)

**Comment by morezooomm** [comment]
I can’t sign into GitHub to respond directly, so offer my comments here.

Rather than show the additional details on the form, I would park this one in the icebox and revisit in early March.  By then, we should have content on MyHR that we could link to via URL.

My concern is that we have several other places on the form that could use further explanation and if we start adding then directly to the form, it could get rather messy.  Cheers!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by fazil-ey** [comment]
@MissionT please remove the definitions from the form. I also notice that the question itself is missing on the form 

![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/c872c28e-989e-4238-aee0-b90369556e4f)

**Comment by morezooomm** [comment]
Agreed we can remove these two definitions from the form and put this ticket in the icebox.  In March, I will review if we have definitions content on MyHR that we can link to instead.  Don

**Comment by MissionT** [comment]
The question has been put back in and the definitions removed.
