### ISSUE TITLE
PIA for mat/pat/parental leave form

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#859]
Work with form owner to ensure the latest PIA is complete and approved in time for November, 2023 launch. 

Digital Journeys team will support with info and inputs related to:
- technical steps/flow of information
- details/decision around retention period

**Comment by Abuchana** [comment]
@NassNK are you actively working on this PIA too? We haven't really been talking about it...

**Comment by NassNK** [comment]
@Abuchana it is with m yes, but I haven't had a chance to do much on it yet. Next week  I will be able to begin working on it.

**Comment by Abuchana** [comment]
@NassNK can you update this ticket with the progress make so far? Thanks!

**Comment by NassNK** [comment]
The PIA is almost ready to go back  for review. @MeghanStothers @Stella-Archer  Two questions that need clarification: 

On the PIA we've indicated the following: The PSA Business Intelligence team creates and hosts dashboards on a secure government website to which specific individuals are provided access on an as-needed basis in accordance with the PSA’s Information Access Framework. - **Is there any PI/employee specific data going to be on these dashboards? And can we provide examples of users who will have access?**

**Comment by Stella-Archer** [comment]
we’re maybe okay to simply remove this step in the PIA, as I am not aware if business-area reporting is a requirement for Connie (which is outside the scope of the DJ team/work).

I will confirm with Stella and Fazil (who have been connected in this work) if this requirement has been mentioned or recorded.

I believe “Step 12” in the PIA was related to the Telework Agreement, in which execs had reporting needs/requirements. In turn, the BI team (Ian Busby/Steven Jones) built a dashboard with some stats.
@NassNK connect with Connie to confirm

**Comment by Abuchana** [comment]
Nass: Mat/Pat PIA has been updated and reviewed. There are some minor notes for Connie to provide context on then it will be ready for final review and then signatures.

**Comment by MeghanStothers** [comment]
Moving this ticket into in progress as we review the September launch timeline and all key pieces needed to launch.

**Comment by MeghanStothers** [comment]
Decision needed from form owner (in consult with DJ team) about how long we keep draft mat/parental leave forms forms  in the formsflow platform. @fazil-ey Can you check with Connie and your next session about ideal (or approximate) timeline. This information ill need to be reflected in the PIA, and possibly in email/confirmation messages to employees/applicants, as well as in any communications materials.

**Comment by MeghanStothers** [comment]
@Abuchana As part of the presentation to PSA exec, we've flagged the PIA as a deliverable/requirements for launch.  We've flagged this for Connie who said she'll reach out to Jennifer to review the latest draft. DJ Journeys team can help with any information needed, such as flow of info through to the CRM.

**Comment by fazil-ey** [comment]
PIA is complete and needs a final review from the DJ team & Igor and be signed off

**Comment by fazil-ey** [comment]
PIA needs a few tweaks, Connie to confirm if it can be signed off

**Comment by MeghanStothers** [comment]
I sent the draft to Privacy on November 11 
 
Reply from Privacy: "Will update the PIA and send over to CPO for final sign-off. We can always do a PIA update in the future if the process workflow changes impacting how PI is collected, used, disclosed or stored 👍"

Cheers, (& congrats on the project completion! ⭐)"

**Comment by MeghanStothers** [comment]
Once I get the final PIA (signed off by CPO), will file in in our Team channel.

**Comment by MeghanStothers** [comment]
@NassNK Thanks for your efforts to get this PIA drafted and approved - we'll wait for the final sign-off and file in our teams records.
