### ISSUE TITLE
TELEWORK: Link to form from the BC Gov website

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#86]
As a BC Gov employee I would like to be able to access the tele-work form from the BC Government website so that I don't have to go to a different place to submit the form.

**A/C**

- Form is linked to from the BC Gov site
- Instructions for how to link to forms is documented/communicated to the PSA

**Comment by MeghanStothers** [comment]
Right now some on our team can access the form from Careers & MyHR, but other cannot from other ministries. We want to make sure there are no barriers (such as Key Cloak) for those employees with active IDIRs to access the forms tool and its forms.

**Comment by Stella-Archer** [comment]
I can confirm I worked with GDX/Ify(GDX Jira tix SDE-14182) to remove the QA lockdown and tested with new employees not yet in our system this was successful
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/5b9aa521-392f-43fc-a18b-69500ed4f954)
