### ISSUE TITLE
Tool: Issues with Email PDFs

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#862]
PDF generation is inconsistent. This bug was found in 1.10 

When form was submitted, the pdf sent to the sender was complete, but the version sent to the recipient was not.  The version saved on the DJ portal was fine, as was the version sent to the PSA Registrar Intake Mailbox; only the recipient version was incomplete.

Incomplete version sent to recipient - [https://app.zenhub.com/files/439477060/4124ac0e-5247-4374-a864-fcc0604e12bc/download]

Complete version - (https://app.zenhub.com/files/439477060/4124ac0e-5247-4374-a864-fcc0604e12bc/download)

**Comment by bhumin-fw** [comment]
@Stella-Archer 
It deployed to DEV and TEST.

For your note: 
If you select LDB and provide email other than gov.bc.ca or bcldb.com then it will send email without PDF to the **complainant**.
**Recipient** and **LDB inbox** both receive email with attached PDF.

**Comment by morezooomm** [comment]
Thanks Bhumin, that is what should happen.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by MeghanStothers** [comment]
Reported at scrum: issue has been resolved in test and dev 

Can be moved to prod. 

Related to a team that sent a complaint to Chris/DJ mailbox for Telework

**Comment by bhumin-fw** [comment]
Changes deployed to Production.
