### ISSUE TITLE
Create Maternity form

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#87]
As a BC Gov employee and PSA form Designer I would like the Maternity form to be created so that I can submit maternity applications.

**A/C**

- Create maternity form on the test site (this can be exported to prod later)

**Comment by qudsia-khan-fw** [comment]
@simensma-fresh 
Here are the screenshots as discussed:
![tooltipSelectBoxes.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/a6bb3f42-89bb-4651-91b9-8fa0840be5a1)

![textFieldCheckbox.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/d0d84af9-5ad2-4c47-b1f6-6d2cba6827cb)

**Comment by simensma-fresh** [comment]
@qudsia-khan-fw I left some initial feedback in this document: https://docs.google.com/document/d/1qU3tLwO3Q5ElkvGwCvIcyiptiE-oS79nE8Yfg-oflGg/edit?usp=sharing including answers to 1. / 2. above
