### ISSUE TITLE
Mat/Pat - Create form & add content (v1) 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#871]
Create the wizard form and add content for v1 - https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764543687588226&cot=14

Note - 
Any content changes will be consolidated and added to v2

**Comment by MissionT** [comment]
Form build was finished on Jan 31st. Andrew is adding logic to the form.  We will clean up the formatting, spacing to follow.

**Comment by MissionT** [comment]
Status of of Feb 9th - Wizard tabs are all built, logic is being added. User testing is in progress as additional logic is added.

**Comment by Abuchana** [comment]
@MissionT can you add an estimate to this ticket?

**Comment by fazil-ey** [comment]
Hey @MissionT, We want to show the Saturday alert all the time so that people select a Saturday on the first go. 

![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/d2a348ae-589b-4644-a5e1-79064b4a17f5)

**Comment by MissionT** [comment]
@fazil-ey re Saturday alert -note made. Thx
