### ISSUE TITLE
Mat/Pat - Form validation for Maternity leave screens + additional logic

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#875]
[Birthing Parent Selection](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764543687588205&cot=14) 
- "Are you a birthing parent?" is mandatory 

[Maternity leave info](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428155&cot=14) and [Leave length info](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428154&cot=14)
- no field validation or logic

[Start Date](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545587861208&cot=14)
- mandatory
- must be a valid date (submitter logic)
     - if before form approval max 9 months in the future from current date, cannot be a past date
     - if approved:
           - if before leave start, max 9 months in the future from current date or at max 1 month in the past
         ~- if after leave start, max 1 month in the past from current date. Cannot be a future date~
    

[Number of weeks](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428156&cot=14)
- mandatory
- must be a number
- must not be more than 17 weeks 
- after start date and number of weeks is input, show the info box with start & end dates calculated

[Allowance selection](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428158&cot=14)
- mandatory

Split allowance info popup to #1304

**Comment by fazil-ey** [comment]
Keep an eye out for timezones @Andrew-Vargas-bcgov 
Also refer to the original mat/pat form & logic - maybe things can be reused

**Comment by Andrew-Vargas-bcgov** [comment]
need infopop screenshot to add.

> After leave starts, can be a date at max 1 month in the past from current date
> if editing a submitted form, date can be in the past
Finished researching this. These can be implemented after summary screen created.

**Comment by fazil-ey** [comment]
On the leave length screen, the dates are calculated even before the value is input. Also, the initial design was to have it as part of an info box. Also info box should appear after the start date is input. 


![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/63116767-aa47-4bd3-bf87-ed289939ad66)

**Comment by ayushdamani** [comment]
Tested and verified!
The start and end dates appear before the user inputs maternity leave value, like Fazil mentioned. Once the maternity leave field has an input, the 'End date' gets updated.

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov  @chriscaldwell-psa 

 Issues found

1. For consistency lets change the error message for mat leave start date to "You must select a date in the future"

**Comment by Andrew-Vargas-bcgov** [comment]
updated validation messages.
Changed allowance selection to mandatory.
added fields for chris to display dates in info boxes.

**Comment by Andrew-Vargas-bcgov** [comment]
1 - 4 complete
5. working with Iman on this one. The feature for adding tooltips does not seem to work for number fields. 
6. complete

**Comment by MeghanStothers** [comment]
Iman to look into this one

**Comment by fazil-ey** [comment]
FYI the error message is incorrect. It should use the name of the question "Are you a birthing parent?" instead of the content below. 

![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/f69099ff-73ff-4ec2-8688-bf368ab94fe9)

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey This validates in the review section now, so you can skip over it initially and only verify at the end. Whatever is checked on this page or the review page is written to both fields. Is this okay?

**Comment by ayushdamani** [comment]
Tested:

- Birthing section - mandatory ✅

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakE4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dfd8d277896744cd28622921f97f430c19351fef/image.png)

- Maternity leave info and Leave length info - contains no logic ✅

- Start date - acceptance criteria met ✅

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBams4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5ad02b52d3ae8e171761fc8e668d71abc9148cb2/image.png)

- Number of weeks - validated, info box appears with calculations ✅

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanM4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--09e1b9d2f54271487b80db85e91a05a2b34ec7bb/image.png)

[Private Zenhub Image]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanc4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0bb75670e908692bbacb36a2e96a99fbc6153279/image.png)

- Allowance estimation - info box for calculating salary and EI estimation does not appear right ❔

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa284IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b447884d0e9915c9fbed4ba40439515113e48a03/image.png)

- Allowance section - mandatory ✅

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazA4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8b011435c579eb87c1d327f26b2781d21041df9c/image.png)

**Comment by fazil-ey** [comment]
Tested and works as expected. Except Allowance calculator info pop which is split into #1304
