### ISSUE TITLE
Mat/Pat - Form validation & additional logic for Parental leave

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#876]
[Are you taking parental leave?](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428159&cot=14)
- Mandatory field
- If "Yes, both my partner and I will be taking parental leave"
   - Ask "Does your partner work for BC Public Service?"
   - Mandatory field, if the question is asked 
   -(the above passed QA)

[Parental Leave Info ](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545705819519&cot=14)
-  No logic/validation

[Parental Leave - Leave Type](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428162&cot=14)

- "What parental leave are you taking?"
     - Mandatory field
     
- "How many weeks of leave do you want to take?"
    - Mandatory field, valid whole number
    - length of leave should not exceed the max length allowed based on the following logic 

```
If applicant is not taking maternity leave, or a 15 week mat leave or less than 15 week mat leave then options should be - 
         - Standard, up to 37 weeks
         - Extended, up to 63 weeks
If applicant is taking a 17 week maternity leave then options should be - 
         - Standard, up to 35 weeks
         - Extended, up to 61 weeks
If applicant is taking 16 week mat leave then options should be - 
          - Standard, up to 36 weeks 
         - Extended, up to 62 weeks
```

- If Yes to "Does your partner work for BC Public Service?" then show [alert](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545707190334&cot=14) telling that their choice must be the same as their partner

**If only parental leave** then use this screen [Parental leave start date with birth date](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764548086882697&cot=14) **else use** [Parental leave start date](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545707100507&cot=14)

- Content should change depending on type of leave selection (note that the content is split across 2 questions if we are asking for child's date of birth)

    - If Standard leave then 

>You can start your parental leave only after your child is born or placed for the purpose of adoption. If your child is born later than the start date provided in this form, you must ask you supervisor to amend the start date.
>
>You must start your standard leave within 52 weeks of the birth of your child or the placement of your child for the purpose of adoption.
> 
> If your leave extends beyond 52 weeks, you will not be paid EI & allowance for the part of your leave after 52 weeks.

   - If extended leave then

>You can start your parental leave only after your child is born or placed for the purpose of adoption. If your child is born later than the start date provided in this form, you must ask you supervisor to amend the start date.
>
>You must start your extended leave within 78 weeks of the birth of your child or the placement of your child for the purpose of adoption.
> 
> If your leave extends beyond 78 weeks, you will not be paid EI & allowance for the part of your leave after 78 weeks.

- "When do you want to start your leave?"
    - Mandatory field, must be a valid date
    - If taking maternity leave, start date should be after the end date of maternity leave. We need to do the following 2 tasks 
       -  Show [maternity leave alert](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545707100523&cot=14) instead of [Saturday alert](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764547008323659&cot=14).  
       - Add form validation if date selected is not after mat leave ends 
_"You must select a date after your maternity leave ends on `*mat leave end date*` "_ 
    - If taking only parental leave
        - Show [Saturday alert](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764547008323659&cot=14) only 
        - Date must not be more than 52 weeks from the child's birth date if standard leave, and 78 weeks from the child's birth date if taking extended leave. 
        - Show "When do you want to start your leave?" section after "When was your baby born or placed after adoption?" is filled as the validation is not dependent on birth date being filled

(in the screen when taking only parental leave) 
- "When was your baby born or placed after adoption?"
    - Must be a valid date, must be a current date or past
    - Mandatory

**Comment by Andrew-Vargas-bcgov** [comment]
@chriscaldwell-psa Can you test this in dev?

**Comment by ayushdamani** [comment]
Logic not working - will connect with Andrew once he is back.

**Comment by Andrew-Vargas-bcgov** [comment]
made the fields mandatory and chris and ayush tested the parental leave length logic.

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov @chriscaldwell-psa  

Issues found - 

- "Does your partner work of BC Public Service" should show only if "Yes, both my partner and I will be taking parental leave" is selected

- "Does your partner work of BC Public Service" is mandatory if it is shown, however currently we can go to the next page without answering that question. Nor does it show an error message on submission

- "What parental leave are you taking is a mandatory field, however again, you can go to the next page without answering  it, nor does it show in the submission errors

[https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-04-26%20at%201.32.14%20AM.mov?csf=1&web=1&e=tnRhMv]

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov 
Issues found -

- "How many weeks of leave do you want to take?" has a default value 37. It should be empty by default 
- Odd spacing here @chriscaldwell-psa, too much spacing between "how many weeks.." and "you can take" </br>
 <img src="https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/5d30d37b-6a9f-46df-a0f3-5a2eb971a9cc" width="40%" length="40%"/>
- This alert box should not be on this page </br>
 <img src="https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/46a4b44e-d8cb-4445-85a1-a2468e1cd3e8" width="40%" length="40%"/>

**Comment by Andrew-Vargas-bcgov** [comment]
1. complete.
2. complete
3. complete
4. complete
5. complete
6. Seems like hidden components take up space in wizard forms. We will need to investigate. 
7. complete
8. complete
9. complete
10. complete
11. complete
12. complete
13. complete
14. complete
15. complete

@ayushdamani @chriscaldwell-psa can you test these changes?

**Comment by chriscaldwell-psa** [comment]
@Andrew-Vargas-bcgov I will test this today. Thanks! C.

**Comment by chriscaldwell-psa** [comment]
@Andrew-Vargas-bcgov I tested the logic and it looks good except, I'm not sure if the logic for the following works correctly" Applicant taking a 16 week mat leave - Standard up to 36 weeks) . Currently the text reads 37 and not 36 and I think it needs to be updated. We can discuss when you have time. Thx

**Comment by fazil-ey** [comment]
Issues - 
1. Incorrect error message "Birthing, non-birthing and adoptive parents can take parental leave to care for their child is required" instead of "Are you taking a parental leave is required"
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/8dd5d251-9dd1-43c0-b7f2-dda81277cdfe)

2. Incorrect error message "Standard, extended leave is required" instead of "What parental leave are you taking?"
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/7fc909b5-5cec-4bb6-b209-42f2cbb4b2f6)

3. Incorrect Error Message "You can take up to 37 weeks of standard leave (or 35 weeks if taking the full 17 week maternity leave) is required" instead of "What parental leave are you taking? is required"
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/7f8a5e78-29dc-4e34-b86b-9670c3d1cea4)

4. Content does not match for Parental Leave - Start Date page (without birth date)
 ![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/1901f8f8-9a2c-44b4-8ea6-f71d80a07812)

5.

UX Improvement 
1. Add some context to the error - "Number of weeks cannot exceed 36 as total length of maternity + parental leave cannot exceed 52 weeks"
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/5269744b-1c00-4b4a-b22b-6bb0a41db6a4)

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov "How many weeks of leave do you want to take" still has incorrect error message 
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/a5997797-0dd3-4a1f-a12e-1792904218bb)

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey just to reconfirm, parental only leave can be a date in the future now, correct?

**Comment by Andrew-Vargas-bcgov** [comment]
ready to test

**Comment by fazil-ey** [comment]
Tested, created on bug ticket for a small bug with the text when extended leave is selected #1276

For parental leave child's birth date - There is no need for a limit on how far back a date can be because it will be validated by when they start their leave. So we should remove the "cannot be a date 2 months in the past"  validation and error message.  

 "When was your baby born or placed after adoption?"
