### ISSUE TITLE
Mat/Pat : Form validation for common screens + additional logic

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#877]
[Employee Info ](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764546379072516&cot=14)
- Radio button is mandatory. However validate only on form submission, not on moving to next screen

[Alternate Contact Info](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428152&cot=14)
- Fields are not mandatory
- Should NOT be pre-populated

[Deferred allowance](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428167&cot=14)
- In the info box, show the dates between which the employee can choose to claim their allowance based on dates provided in the form 
```
    - employees can claim any date AFTER the maternity and/or parental leave ends
    - employees must claim before the return-to-work repayment period 
       - if union code is NOT `CRN` then 
            - if total leave duration (mat + pat)  is less than 6 months then end date + 6 months
            - if total leave duration (mat + pat) is greater than 6 months then end date + leave duration
       - if union code is `CRN` then 
          - end date + 6 months
```

- if union code is CRN i.e Crown Counsel content should be -

> You have chosen to defer your top-up allowance. To claim allowance after your leave, you must return to work for a period of 6 months`
> `You can choose any date from the day you return to work up to the day your return-to-work repayment period ends (i.e. 6 months). However you must complete the return-to-work repayment period to receive the full allowance amount.

- Form validation - date must be between the dates calculated above i.e after leave ends and before return-to-work repayment period

[Confirm Supervisor](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428164&cot=14)
- supervisor name 
    - mandatory
    - must be pre populated
   ~- must not be prefilled~
     - editable
    - valid string
- supervisor email
    - mandatory
    - must be pre populated
    ~- must not be prefilled~
    - editable
    - must be a valid email 
    -  Updated Mar 1: only the following domain should be allowed (all valid gov email addresses allowed for mat/pat) 
`
"gov.bc.ca", 
 "bcest.bc.ca", 
"bchumanrights.ca", 
"crtbc.ca", 
"destinationbc.ca", 
"eaat.ca", 
"elections.bc.ca", 
"iiobc.ca", 
"lrb.bc.ca", 
"wao-bc.org", 
"eao-bc.org", 
"wcat.bc.ca", 
"royalbcmuseum.bc.ca", 
"rcybc.ca", 
"wao-bc.org", `

[Declaration](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764543687588221&cot=14)
- All checkboxes are mandatory
- date must be prefilled by current date
- date should not be editable

**Comment by fazil-ey** [comment]
Connect with @T854236 to check if we have the union codes available

**Comment by Andrew-Vargas-bcgov** [comment]
@chriscaldwell-psa can you test the deferred allowance dates and add the alert box dates.

**Comment by chriscaldwell-psa** [comment]
Tested this ticket and entered dates that should trigger and error message and it did. Logic works good. I will ask if Ayush can test this Wed due to the many options that can be selected on the Mat/Pat Form.

**Comment by ayushdamani** [comment]
Tested this with Chris -  we need to make sure that we are testing this right.
We are going to setup an appointment with Andrew this week, and go from there.

**Comment by Andrew-Vargas-bcgov** [comment]
testing is complete. sending to po for approval. I will also insert a more readable validation message after grooming.

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov  @chriscaldwell-psa  @ayushdamani 
Issues - 
- Confirm your information radio button is [not being validated on submission](https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-05-01%20at%206.40.31%20AM.mov?csf=1&web=1&e=cHpD74) 

1. Alternate Contact Info 
2. Fields are not mandatory, however they are being shown as mandatory when next is pressed. 
<image src="https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/27784732-9641-459d-9816-dbc5ecbf2334" width="30%" length="30%" />


3. Can we add "optional" under the text fields for alternate contact information </br>
<image src="https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/d5b095c2-bf99-4f66-9e52-2a5224049a75" width="10%" length="10%" />

**Comment by MeghanStothers** [comment]
@chriscaldwell-psa to look at this one and update as required

**Comment by chriscaldwell-psa** [comment]
Did testing on Thursday June 8th, I have bit left to do re the logic and will finish this on Tuesday when I return to work.  I am off on Monday (in the USA).

**Comment by chriscaldwell-psa** [comment]
This ticket was tested and reviewed with Andrew. All good.

**Comment by ayushdamani** [comment]
Tested and verified updated ✅ 
- Calculation for the dates has been corrected.
- Space between "submit" and "previous" button has been fixed as well.
- Wordings for the error message has been updated.

**Comment by fazil-ey** [comment]
1. Not following the logic described in the ticket - Radio button is mandatory. However validate only on form submission, not on moving to next screen
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/489d920e-7a81-4e59-a925-df65918e17fa)

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey This validates in the review section now, so you can skip over it initially and only verify at the end. Whatever is checked on this page or the review page is written to both fields. Is this okay?

**Comment by ayushdamani** [comment]
Tested:

Employee info mandatory on form submission ✅
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzA4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4be4ede5d371cef345e49db9dc811bba251c223d/image.png)

Alternate contact info - not mandatory, not pre-populated ✅
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzg4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--463cf71c8e3a88d9be0a5cde918f53bd5a392b47/image.png)

Deferred allowance - calculations ✅

Supervisor information - editable, not pre-populated ❔
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaG84IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3bb612900284cfe33a86c12a6e30a8222378ed20/image.png)


Declaration - requires at least 6 items to be selected, the date's section is prefilled with today's date and is non-editable ✅
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVU4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--06d1a338ba05664ab2a27832e58ec9027ebe6e2c/image.png)

**Comment by Andrew-Vargas-bcgov** [comment]
auto populated supervisor name and email. Going to test supervisor editing before moving to test.

**Comment by Andrew-Vargas-bcgov** [comment]
@chriscaldwell-psa I have moved this to test for you :). Let me know if you have any questions and we can jump on a call together.

**Comment by chriscaldwell-psa** [comment]
The supervisor field is auto-populating. Over Fazil.

**Comment by fazil-ey** [comment]
Deferred allowance page has some pending work that will be done in #1085.

All other pages pass AC
