### ISSUE TITLE
1.10 - Clear "Your Ministry or organization field" when switching between LDB & non LDB forms

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#878]
When yes for LDB is selected - ![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/0bae7b4f-5041-46a1-b68f-40c0926fe8e4)

When no for LDB is selected![image.png] (the ministry field should be cleared)(https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/3f9e856c-53ae-48c6-8283-b4a96c1408a6)

**Comment by Andrew-Vargas-bcgov** [comment]
This was completed on another ticket and is on dev. Need to move all of our changes to test.

**Comment by Andrew-Vargas-bcgov** [comment]
- [ ] Clear ministry on change to bcgeu, pea, or switching between ldb & non-ldb.

- [ ] remove clear when hidden for auto-populated fields (ie: first and last name clearing when switching from bcgeu to pea and then back to bcgeu). 
@MissionT can you test this to make sure i didn't miss anything and then move the changes to test?

**Comment by MissionT** [comment]
Tested the 2 criteria and all tests pass. No Issues. Logic works very well.  Chris

**Comment by MissionT** [comment]
Dev environment: all criteria pass except the government email does not autopopulate
Test environment: cannot get into the Test env - the Bullying form does not load . Waiting for Iman to fix the load form issue

**Comment by MeghanStothers** [comment]
Andrew said this has been tested and can be closed
