### ISSUE TITLE
Mat/Pat : Review Selections and Edit

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#880]
**User Story**
As an applicant I want to review and make edits in the form easily before submission so that I do not have to navigate through all the screens unnecessarily 

**Design** 
[Review Selections](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428165&cot=14)

**Acceptance Criteria**
- [ ] Should include all fields the following fields
   - Employee information and confirmation, Alternate contact information (if available), 
  - if taking maternity leave - start date, end date, number of weeks,  leave allowance selection, 
  - if taking parental leave - Partners info and confirmation (if with partner in BC gov), parental leave type, number of week,  childs birth date (if taking alone), start date, end date, leave allowance type, leave allowance dates, deferral date (if deferring), supervisor information)
- [ ] All sections except "Employee Information" should have the option to edit
- [ ] Users can edit & save changes on the same page
- [ ] Form validation logic applied on the original screens should be applied for each field in this screen as well

**Comment by Andrew-Vargas-bcgov** [comment]
I have disabled employee information and partner information in the review field. If we want to have people be able to search for partners in the review page, I will have to rework some logic.
All other sections are editable and reflect changes from the form or review change.
Logic has been added to the review page.
Do you want me to hide alternate contact info if it is blank, or keep it available for inputs since it is optional?
In the review page, "Are you applying for leave allowance?" modifies both maternity and parental top up allowance options (if they exist) when changed.

Ready to test. Please try this in initial submission, editing a submitted form, and the manager review page. The code had to be added to a lot of places, so let me know if I missed one.

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov 

2 fields had discrepancy between what was entered in the form and what was in the review page - alternate contact email and number of weeks for parental leave

https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-08-25%20at%2012.08.37%20PM.mov?csf=1&web=1&e=GJgjVK

https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-08-25%20at%2012.13.17%20PM.mov?csf=1&web=1&e=ggJbTS

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov 
UI - 
- lets remove the warning, i think it does not help much since we have the confirmation radio button
- make the supervisor info section which has a blue header, consistent with  all other sections [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbW8rIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ea6e88da61732caf9b4673e0519bf812ed15eebe/Screen%20Shot%202023-08-25%20at%2012.26.02%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWsrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0f786d28b8b7dd2c4e2275a9261ed20c7c54a13a/Screen%20Shot%202023-08-25%20at%2012.26.06%20PM.png)

**Comment by Andrew-Vargas-bcgov** [comment]
finally replicated the "length of leave" issue. The value is sometimes being set before the user is finished typing and then does not retrigger. Need to implement a debounce method.

**Comment by Andrew-Vargas-bcgov** [comment]
fixed value bug on dev. On to the other changes.

**Comment by Andrew-Vargas-bcgov** [comment]
completed 1, 2, 4, 5, 6.
Will add requirements from number 3 and update the buttons on partner info/review page to write to both.

**Comment by Andrew-Vargas-bcgov** [comment]
added requirement 3. When testing, don't jump directly from partner info to review. You should pick any other page before swapping between them. This is a refresh issue that will not exist in the real world as we will not allow people to jump multiple pages.

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov  FYI noticed another error. In review page for deferred allowance date it is showing an error. however, it is not showing an error in the actual deferred allowance page 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3VDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--393424cf32dcd48f4ce5150ca53d4e2008fdcd70/image.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3FDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--37546344831a0019e895a38d3eea0310c76f1371/image.png)

**Comment by Andrew-Vargas-bcgov** [comment]
all changes ready to move to test after the demo this morning.

**Comment by fazil-ey** [comment]
Hey @Andrew-Vargas-bcgov I see a discrepancy for the partner info confirmation
video - 
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-09-14%20at%204.21.33%20PM.mov?csf=1&web=1&e=ceBkkg

**Comment by Andrew-Vargas-bcgov** [comment]
1. oops, great catch. I had the updated code in the review but not the main. Will move this fix over to test and then tag you.
2. Can we have a quick chat about this one? won't take too much time to change.

**Comment by Andrew-Vargas-bcgov** [comment]
Good to go @fazil-ey

**Comment by fazil-ey** [comment]
No discrepancies noticed, also checked in review and process tab. closing ticket
