### ISSUE TITLE
Optimtize storage allocation 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#881]

**Comment by warrenchristian1telus** [comment]
Hi @fazil-ey can you be more specific as to what needs to be optimized? Is space running out somewhere?

**Comment by iman-jamali-fw** [comment]
@warrenchristian1telus 

Checking the persistent storage on PROD shows that Patroni DBs are filling up quickly, currently ~ 840 MB / 1GB. We're planning to increase the retention period of Telework submissions by 60 days.

I suggest optimizing the storage and giving patroni's dbs more capacity. Specially mongo dbs (mongo-data-hamongo) seems to have a lot of free storage to spare.


https://console.apps.silver.devops.gov.bc.ca/k8s/ns/d89793-prod/persistentvolumeclaims

**Comment by warrenchristian1telus** [comment]
Sure @iman-jamali-fw - capacity has been increased to 5 GB for postgresql-patroni-0, 1 and 2. On dev, test and prod.
