### ISSUE TITLE
TOOL: Form page loading issue

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#883]
After BCeID integration, loading a form page randomly fails. The workaround is to load the form by navigating from the form list page.

Once in a form, reloading that form sometimes fails and the form won't be displayed.

AC:
- All forms should be able to be opened directly. For example, a user should be able to open a direct link to the Telework form.
- Once on a form page, the form should be able to be reloaded with no issue.

**Comment by MeghanStothers** [comment]
Iman noted this only happens when someone directly tries to access the form through an email link, rather than going to the dashboard

**Comment by iman-jamali-fw** [comment]
Deployed to PROD

**Comment by MissionT** [comment]
I tested this as well and works fine. This ticket can be closed.
