### ISSUE TITLE
Migrating IDIR usernames after BCeID/BCSC integration

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#886]
After BCeID/BCSC integration, IDIR users will be recognized as new users and no longer have access to their submitted submissions and drafts.

ACs:
- [x] Migrate all the IDIR users' submissions and drafts on the TOOL to the new usernames after BCeID/BCSC integration.
- [x] Migrate all the IDIR users'  Camunda submissions to the new usernames after BCeID/BCSC integration.
- [x] Write and store the migration script in the repo.

Migration progress in different environments (check when is done):
- [x] DEV
- [x] TEST
- [x] PROD

**Comment by MeghanStothers** [comment]
Will do this after the BCeID and BCSC integration.

**Comment by MeghanStothers** [comment]
Iman will need to do this ticket right after the first deployment related to BCeID/BSC

**Comment by MeghanStothers** [comment]
After PR Imam will run migration for Test and then send to teamfor testing

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 

This is ready to be tested on the TEST environment. For testing simply log in to TEST and verify you have all your previous drafts, applications, and tasks. All the previous submissions prior to the BCSC+BCeID integration for the IDIR user should be restored.

**Comment by MeghanStothers** [comment]
Only thing left to do is deploy to prod

**Comment by Stella-Archer** [comment]
woohoo everything is there good to go!

**Comment by iman-jamali-fw** [comment]
Great! 
Moving it to Deploy to PROD

**Comment by iman-jamali-fw** [comment]
Deployed to PROD.
