### ISSUE TITLE
Automatically merge new BCeID user

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#888]

**Comment by iman-jamali-fw** [comment]
Currently, once a new BCeID user logs in for the first time, user is prompted by an update user account form.

AC:
A new user should sign in for the first time and their account automatically without be prompted

![Screenshot 2023-02-02 at 11.03.41 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/f92be695-4b76-48fa-8bb8-143725a27685)

**Comment by iman-jamali-fw** [comment]
Currently, once a new BCeID user logs in for the first time, user is prompted by an update user account form.

AC:
A new user should sign in for the first time and their account automatically without be prompted

![Screenshot 2023-02-02 at 11.03.41 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/f92be695-4b76-48fa-8bb8-143725a27685)

**Comment by iman-jamali-fw** [comment]
@Stella-Archer This is ready for testing on TEST.

**Testing instruction**
Please log in with your BCeID as a new user. If already logged in with your BCeID on Test, please first remove your user account in Keycloak (I can help you with that), and then log in.

Once logged in, two things should be working fine:
1. You should no longer see the "Update Account Information" dialog form.
2. Once go to a BCeID-supported form like 1.10, should be able to see your first name, last name and email.

**Comment by Andrew-Vargas-bcgov** [comment]
Passed all tests!

**Comment by MeghanStothers** [comment]
close this ticket
