### ISSUE TITLE
Form tools: Radio button selection disappears

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#892]
When user click on "Download PDF", radio button style disappears. It keep the value and render form accordingly and send the same on form submission too. But it disturb user's experience.

**Acceptance Criteria**
- Radio button should stay selected if selected before click on "download PDF".

Reference Image
![downloadPDF.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/cf0b22dc-068c-4f00-94a4-bb7e27e670a2)

**Comment by bhumin-fw** [comment]
@Andrew-Vargas-bcgov This bug is fixed and deployed on DEV and TEST. 
When you click on download PDF it will disappear but Once PDF downloaded it will re-appear.

**Comment by Andrew-Vargas-bcgov** [comment]
Looks good @bhumin-fw . Appearing as intended.

**Comment by MissionT** [comment]
Hi Bhumin, I tested two different download PDFs; the LDB radio buttons do not appear and print in the PDF. They should appear, and this needs to be fixed.  The 3 radio buttons do appear re: BCGUE, PEA, Other. Chris

**Comment by bhumin-fw** [comment]
@MissionT 
Could you please share more detail here?
I want to know browser, page on which issue noticed and screen resolutions(if possible).

**Comment by MeghanStothers** [comment]
Chris to test

**Comment by MissionT** [comment]
The LDB radio buttons are now appearing! Thank you. This ticket can be closed.

**Comment by MeghanStothers** [comment]
ready to deploy

**Comment by MeghanStothers** [comment]
okay to close
