### ISSUE TITLE
Mat/Pat : Supervisor Approval

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#895]
**User Story**
As a supervisor I should be able to approve or return forms submitted by employees under me so that their leave forms can be sent for further processing. 

**Note** - need to confirm the status so that we are consistent across DJ. To be discussed when this ticket is picked up. 

**Acceptance Criteria**

- [x] Supervisor is able to see all forms submitted by applicants who specified them as their supervisor in the form
     - Status of the form on submission (or resubmission) is "NEW" 
- [x] Supervisor is able to see the following in the task name 
      - Name of the form with applicants name "Maternity, Parental Leave and Allowance form for *applicants name*"
      - Status of the application i.e "NEW" or "APPROVED" or "DENIED" 
- [x] Supervisor is only able to view the review page and certification page of the form. All other tabs should be hidden (except those needed technically)
- [x] Supervisor is able to approve the form. 
     - Status of the form on approval is "APPROVED" 
- [x] Supervisor is able to send back the form for resubmission if any changes are required
     - Status of the form on sending back is "DENIED"

**Comment by MeghanStothers** [comment]
Re-work the tickets with consistent naming conventions to see if we need new ones

**Comment by iman-jamali-fw** [comment]
@fazil-ey 

These are the status we currently have in different forms.
- Telework: `New`, `Approved`, `Denied`
- SL: `Submitted - Validation`, `Submitted - Final`
- Cold/flu: `Submitted`
- Other status in the system (used at some point): `Resubmit`/`Resubmitted`, `Submitted`, `validated`

**Comment by iman-jamali-fw** [comment]
progress report:
-  [x] The new status for the Mat/Pat form was added which no longer relies on workflow and its version, which can be changed anytime by the form designer
- [x] Updated to correctly assign edit access to statuses used in multiple forms.
- [ ] Pending: Display the applicant's name and submission status under the "Review and Process Forms" tab.

Expect to have this ticket ready for PR today

**Comment by iman-jamali-fw** [comment]
@fazil-ey 
Let me know if `status` looks good on the task item. It'll be like: Maternity and parental leave form for {applicants name} **- {status}**

example below for the status of NEW:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHpTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--431c1c6e1e2ffe7a207ed22d1bb73c5913963f8c/Screenshot%202023-09-25%20at%208.58.46%20AM.png)

**Comment by iman-jamali-fw** [comment]
@Stella-Archer @ayushdamani 
This is ready to be tested on TEST.

Testing instructions:
1. Submit a new Mat/Pat form
2. As an employee you should be able to see your submission under `Submitted Forms` with the status of `NEW` and it should allow for your edit.
3. As a manager, assigned for the submission in 1, you should be able to see the submission, assigned to you, under `Review and Process Forms`. Make sure the status of that submission is listed in the task list (on the left). Check the comment above for more details.
4. As a manager, open the submission and you should be able to approve/deny the submission.
5. Check the submission status properly changed when you approve/deny for both manager and employee. 
6. As an employee, try to resubmit your submission, this should change the approved/denied status to `NEW`.
7. Please verify the ACs in the ticket when doing the steps above. 

Let me know if need more details, good luck testing 🎉😀

**Comment by ayushdamani** [comment]
Tested this in the test environment
I was able to follow Iman's instructions and everything worked out great.

Only one question - The acceptance criteria mentions, the supervisor should only be able to see the Review tab, and the rest of the tabs should be hidden. But as a supervisor, I am still able to see all the tabs. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1BaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50e03cfaab78bcf7f262a76247f9c120700a0f00/image.png)

**Comment by iman-jamali-fw** [comment]
@ayushdamani 
I thought by review tab, meant the `Review and Process Forms` tab (at the app level). Maybe @fazil-ey  can clarify.

**Comment by iman-jamali-fw** [comment]
@fazil-ey 
Please also look at this part of the Mat/Pat workflow that sends emails based on application status. This would need to get updated based on the new status [NEW, APPROVED, DENIED]. There are other conditions in the workflow that only trigger (send email or create/update CRM ticket) if the status is `Validated`, with the new status, my guess was it should updated to 'APPROVED', but leave it to you to review and let us how to update. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDdoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6533d34d4214d0472f5bc2a8fd86f0c69479bf22/Screenshot%202023-09-27%20at%207.03.55%20AM.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalBoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e0c9b31bb996986d055a633761b0f697ea1e6d4e/Screenshot%202023-09-27%20at%207.08.43%20AM.png)

**Comment by fazil-ey** [comment]
@iman-jamali-fw  yes, the current emails should only be sent if the form is validated. 

We might need a new email just to the applicant for "DENIED" i can create a new ticket for that.

**Comment by iman-jamali-fw** [comment]
@ayushdamani 
This is ready for your testing on TEST. All the Mat/Pat form tabs are hidden except for review and certify when the manager reviews the submission.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEQ4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f5e68c60ff7d32c10a59fbd3166a53a5b8efdacc/Screenshot%202023-10-03%20at%207.51.18%20AM.png)

**Comment by iman-jamali-fw** [comment]
FYI, the actual efforts for this ticket were closer to 5 than 3.

**Comment by fazil-ey** [comment]
Unable to test because of this error on approval. The date is the same as the original form. Also, documented the same error in #1334, not sure which one it is more related to. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDBBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c12afea25ba197b1696fa9af8a56bc205a7c1a47/image.png)

**Comment by MeghanStothers** [comment]
Bhumin to update this ticket with next steps

**Comment by iman-jamali-fw** [comment]
@fazil-ey @ayushdamani 
Keeping a few necessary tabs (like mat, pat, allowance) open on supervisor review for now as hiding all tabs has technical complications. @bhumin-fw  and I are working on a long-term solution to hide all unnecessary tabs, but for now, keeping a few essential tabs open is more feasible for MVP.

Ready to be test on TEST.

**Comment by ayushdamani** [comment]
Hi Fazil,
Can you please guide me, how to recreate the issue that you faced?

**Comment by ayushdamani** [comment]
I referred back to #1334, and identified how to recreate the issue:
- The start date error has been resolved as I was able to validate the submission. Thank you so much for the update, Iman!
- Like Iman mentioned, a couple more tabs are visible to the supervisor.

**Comment by fazil-ey** [comment]
unable to approve - tried multiple times. Submitted a form with a gap and tried to approve as a supervisor. 

https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-10-18%20at%203.47.49%20PM.mov?csf=1&web=1&e=q87hPg

**Comment by ayushdamani** [comment]
I will request the team at check-in to test this, since I am not being able approve submissions again in TEST and DEV.

**Comment by ayushdamani** [comment]
I was able to submit the form ✅
Checked the review and process tab ✅

**Comment by fazil-ey** [comment]
works well! submissions going through and status updated as expected
