### ISSUE TITLE
Mat/Pat: Edit submitted forms (applicants)

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#906]
Edits should happen in the submitted form tab. When edit is selected the submitted form should open on the review page and edits should be allowed in the same page or they can go the the specific tab for the field and edit there as well.

AC
**1. Before Supervisor Approval and Leave Start Date**
- Applicants should be able to change anything in the form. 
~-If mat leave start date is changed, ensure~
    ~-parental leave start date should be after the mat leave ends~ 
    ~- deferral date should be after both leave end~

**2.After Supervisor Approval and Before Leave Start Date**
- Applicants should be able to change anything in the form 
- Form should go for supervisor approval again (to the supervisor specified in the form, regardless of previous submission)
~- If mat leave start date is changed, ensure parental leave start date should be after the mat leave ends and deferral date should be after both leave end.~ 
     ~- All existing validation on the start dates should also apply when dates are edited~

**3.After Supervisor Approval and After Leave Start Date and taking Only Parental Leave**
- Applicants should be able to change ONLY parental leave start date to a date in the future from current date and no other field
- Should go for supervisor approval

**Comment by iman-jamali-fw** [comment]
@fazil-ey  @Andrew-Vargas-bcgov 

This is ready for testing on the TEST environment.
https://digital-journeys-test.apps.silver.devops.gov.bc.ca/form/642da678c960c54ed1c7015f

Please let me know if needed me to explain the workflow for the testing.

**Comment by fazil-ey** [comment]
@iman-jamali-fw Thanks! Yes, so we tested this on April 5 and the manager group was not assigned automatically. Will retest today

**Comment by fazil-ey** [comment]
No response on resubmit, and status does not change in submitted forms, but form is updated for supervisor

**Comment by iman-jamali-fw** [comment]
I found the issue of the first issue, which should be fixed today:
> No response on resubmit, and status does not change in submitted forms, but form is updated for supervisor

I will work on the second requirement below:
> After validation, applicant sees validate submission button and then if applicant refreshes they see resubmit button

**Comment by iman-jamali-fw** [comment]
I found the issue of the first issue, which should be fixed today:
> No response on resubmit, and status does not change in submitted forms, but form is updated for supervisor

I will work on the second requirement below:
> After validation, applicant sees validate submission button and then if applicant refreshes they see resubmit button

**Comment by iman-jamali-fw** [comment]
@fazil-ey 

I have a few questions for you.


When you say "After leave Date", do you mean the maternity start date?
![maternity-start-date-field.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/cae6a89f-43e2-4532-8624-b66f87e33b10)




When you say "Only Parental Leave", do you mean when parents select they're not eligible for maternity leave but taking parental leave?
![maternity-leave-eligiblity.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/0f6d00b8-923e-4002-8a6f-d43faf8c66be)

![taking-parental-leave.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/4acf735c-d370-4b3b-89b5-b814862e0daa)


When you say "Employee can only change the parental leave start date and everything else disabled" do you mean only the Parental leave start date field in the "Parental Leave Start Date" page or the whole page should be enabled for edit?
![parental-leave-start-page.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/6c4a3d8b-0016-47f5-87fc-6714e25e7bf0)

**Comment by fazil-ey** [comment]
@Iman 

1.  After leave Date - is mat leave start date if taking ,mat leave or parental leave start date if taking only parental leave

1. Only Parental Leave - yes that what it means, when a parent is taking only parental leave and not maternity leave 

1. Parental Leave Start Date - Only the parental leave start date field, nothing else on the page or the form

**Comment by fazil-ey** [comment]
@iman-jamali-fw  @Andrew-Vargas-bcgov This is in progress however just FYI there are some issues while resubmitting 
- The button says validate submission instead of just Submit
- there is no confirmation page, however the edit is successful. When we go to the form again we see the edited value 

https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-05-04%20at%209.54.44%20AM.mov?csf=1&web=1&e=8Rgqpc

**Comment by Andrew-Vargas-bcgov** [comment]
added two hidden fields 
lastSubmittedLeaveStartDate: to track last submitted leave start date
leaveStarted: to tell if that date has passed.
I'll add the logic to disable the mentioned fields after the leave start date has passed.

**Comment by Andrew-Vargas-bcgov** [comment]
added logic for submitted forms to redirect to review page initially.
added logic to disable fields after leave start date.

**Comment by Andrew-Vargas-bcgov** [comment]
Just needs #880 to be done for this to be complete. 
@chriscaldwell-psa could you test and make sure the redirects are working well for you?

**Comment by chriscaldwell-psa** [comment]
@Andrew-Vargas-bcgov  I submitted a MAT/PAT form where it was successfully redirected to the Review and Process Form page . Please note that the review page  did not show the summary information only the tab labelled 'Before you begin' (page). Let me know if I need to test more of this ticket. Thx.

**Comment by Andrew-Vargas-bcgov** [comment]
tested with Ayush. Parental leave only, mat leave only, and both redirect to the correct review tab page.

**Comment by fazil-ey** [comment]
AC#2 seems to be failing. Even though it is before leave start date, i am unable to edit and change the form as an applicant. It seems to be combined with AC#3

Recording - 
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-06-12%20at%204.39.16%20PM.mov?csf=1&web=1&e=G3eQnG

**Comment by iman-jamali-fw** [comment]
@fazil-ey (cc @Andrew-Vargas-bcgov )
I notice that the status logic for changing the status of a submission to "Validated" has changed. Initially, each time the manager validates a submission, the status changed to "Validated".

Now, status only changes to "Validated" when manger validates a submission for the first time.

**Comment by fazil-ey** [comment]
We have a [ticket](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/895) where we have defined what the status should be. The applicants should know if the form being submitted is waiting for approval or has been approved. 

I am not sure what is happening behind the scenes with the status right now, but we havent picked up the ticket with the approval states

**Comment by iman-jamali-fw** [comment]
Progress:
- Fixing manager validation status. Each time the manager validates the submission, the form status changes to "Validated". This was necessary to have CRM service work on manager validation.
- The manager's group/role is added when the employee sets the manager's email on the initial submission. This was broken at some point. Fixed and working again.

**Comment by MeghanStothers** [comment]
Almost ready to test - closer look at AC 3 and then the ticket with to PSA dev

**Comment by iman-jamali-fw** [comment]
@fazil-ey 

Ready to be tested on TEST.

**Comment by iman-jamali-fw** [comment]
@fazil-ey 
Please pause testing this ticket, some of the logic was overwritten on the TEST, I'll work to bring them back tonight. I will keep you posted here.

**Comment by iman-jamali-fw** [comment]
Changes recovered and saved to DEV and TEST.
@fazil-ey 
Ready for testing on TEST when you're ready

**Comment by fazil-ey** [comment]
Works as expected, except that AC #3 was for people taking only parental leave, not both maternity and parental. Will split that into another ticket, as we might reconsider our initial decisions for editing a form after leave starts. #1313
