### ISSUE TITLE
1.10 : Contact Us Button

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#907]
Add a contact us button next to save and download pdf buttons in the 1.10 form so that applicants can easily know who they can contact to get help as they fill the forms

The contact us button should open a popup with the following content 

> •	For help completing the form for BCGEU members, contact your GEU at 1-800-663-1674
•	For help completing the form for PEA members, contact your PEA at 1-800-779-7736
•	For technical help in using the form, contact digitaljourneys@gov.bc.ca
•	For PSA accommodation assistance in completing the form, contact AskMyHR 
•	For LDB accommodation assistance in completing the form, contact employee.relations@bcldb.com 
•	For suggestions on how to improve the form, contact PSA.RegistrarIntake@gov.bc.ca

Example for reference on how the popup should look like  ![Screen Shot 2023-02-09 at 1.35.13 AM.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/4ac8934b-a547-4b27-b393-5e2282759f8c)

**Comment by MeghanStothers** [comment]
Component created - Iman looking into options for tool tip to trigger the pop up

**Comment by MeghanStothers** [comment]
Ready to test

**Comment by iman-jamali-fw** [comment]
@Stella-Archer  @Andrew-Vargas-bcgov 

This is ready to be tested on TEST. Documentation was also added [here](https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md#form-access)

**Comment by Andrew-Vargas-bcgov** [comment]
Tested and works perfectly in DEV. Great work @iman-jamali-fw 
In DEV I added mailto links for the emails and a link to myhr which I think we had left out of the ticket.

**Comment by iman-jamali-fw** [comment]
Perfect! Thanks @Andrew-Vargas-bcgov 

Could you please add that link to TEST as well? 

Forms on TEST are the most important ones, during the deployment to PROD, we basically copy the form on TEST and paste it onto PROD.

To optimize your testing efforts, you can only test the features on TEST.

**Comment by Andrew-Vargas-bcgov** [comment]
Thanks @iman-jamali-fw I have made the changes in TEST as well.

**Comment by MeghanStothers** [comment]
Andrew tested and looks okay. Can close this ticket
