### ISSUE TITLE
1.10: Popup for alternate dispute resolution info 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#908]
Create a popup with the following content to provide additional context to people in 1.10 form. 
The popup should be similar to the release note popup on digital journeys portal

This popup should be an (i) tooltip next to this question - "Are you open to participating in an alternate dispute resolution process, rather than an investigation?" 

> Alternative dispute resolution – conducted through the Conflict Management Office in PSA, a facilitator can help resolve interpersonal workplace conflict. Participation is voluntary and based on an informal, interest-based approach.
> 
> Investigation – conducted under the Public Service Employment Act, an investigator will interview parties relative to a complaint, collect and assess evidence, and determine findings of fact needed to resolve the complaint.
> 
> Review – any actions outside of an investigation in which the appropriate manager takes steps, with the support of PSA staff as appropriate, to resolve the issues and incidents outlined in the complaint.
> 

Refer - #673
Example for how the pop up should look like 
![Screen Shot 2023-02-09 at 1.35.13 AM.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/a345db0a-78d0-4dc1-9cf1-69f1470c9e7f)

**Comment by iman-jamali-fw** [comment]
@fazil-ey 
When do you want this popup to show up? Is that displayed when a new form is opened or it triggers by a button within the form?

**Comment by MeghanStothers** [comment]
Waiting for Fazil/Stella to see if this is what is wanted

**Comment by fazil-ey** [comment]
@iman-jamali-fw this looks good. Just want to ensure that for 1.10 we either want an (i) like we use for tooltips or a link to trigger the popup

**Comment by MeghanStothers** [comment]
ready to test

**Comment by iman-jamali-fw** [comment]
@Stella-Archer  @Andrew-Vargas-bcgov 

This is ready to be tested on TEST. Documentation was also added [here](https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md#form-access)

**Comment by Andrew-Vargas-bcgov** [comment]
@iman-jamali-fw Tested and works :).

**Comment by MeghanStothers** [comment]
approved and ready to move to deployment

**Comment by Stella-Archer** [comment]
A new term "recipient'  has been added to the definitions:

Recipient – the person who will receive the complaint, normally the supervisor or excluded manager of the person submitting the complaint. They are not a subject of the complaint but they will be involved in helping to resolve the complaint.

**Comment by Stella-Archer** [comment]
put a '?' symbol in the recipient information box eithe title of first line where recipient appears
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/547a7b8e-7a46-41b3-b10d-cb87cbcd9e3a)

**Comment by Stella-Archer** [comment]
@Andrew-Vargas-bcgov  Add Recipient definition to the main definition box as well
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/db4a9521-4b71-42b6-94e2-3dcf7d30b2fc)

**Comment by Andrew-Vargas-bcgov** [comment]
done. Added to recipient name and the alternate dispute resolution process as requested :).
