### ISSUE TITLE
Mat/Pat - Update form content (v2)

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#910]
Update form screens based on the v2 design 

https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428173&cot=14

**Comment by fazil-ey** [comment]
@MissionT I added a disclaimer that Legal wants to put in the [before you begin ](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428270&cot=14)screen. 

Its the last bullet point. 

Also a sticky note

**Comment by fazil-ey** [comment]
@chriscaldwell-psa 

Eligibility screen has some issues 

![Screen Shot 2023-04-24 at 2.11.48 PM.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/2460ac54-aebe-4484-8901-1f6605cc8333)

**Comment by chriscaldwell-psa** [comment]
Will work on this today - April 25th. Chris

**Comment by chriscaldwell-psa** [comment]
Status update: Fazil, Ayush, Andrew and myself looked at the outstanding  logic tickets this morning and Andrew said he would update this logic with ticket ensuring the show/hide logic works.  The updates will be done today and tomorrow and will be ready to test by Thursday April 27 at the latest.

**Comment by fazil-ey** [comment]
@chriscaldwell-psa 

The label "Date/Time" should be "Start Date" on the not eligible page

<image src="https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/4b4752b0-5e33-4e81-b43d-c1bc4750f469" width="50%" length="50%"/>

**Comment by chriscaldwell-psa** [comment]
Confirming that the labels are named correctly and sections match: 
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/51902c98-f94b-45a3-8da9-95554877e440)
