### ISSUE TITLE
Mat/Pat - Maternity leave allowance calculator

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#911]
**User Story**
As an applicant i should be able to estimate my weekly maternity leave allowance in the form so that I have a clear idea of what i can expect during my leave and make informed decisions about my leave. 

**Input fields**

1.Your basic pay (bi-weekly, gross) - mandatory, number with 2 decimals
2.EI Estimate - mandatory, number with 2 decimals
2.Additional Earnings - optional, number with 2 decimals

**Logic**
```
weekly basic pay = bi-weekly basic pay/ 2
85% of your weekly basic pay 
minus
EI Estimate 
minus
Additional earnings received
equals
Weekly gross maternity leave allowance amount

```
**Acceptance Criteria**

- [ ] Applicants can estimate their allowance using the above input fields, following the constraints specified above
- [ ] Estimated allowance is calculated correctly using the logic specified above

**Design**
[Mat leave allowance calculator ](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428157&cot=14)

**Comment by Andrew-Vargas-bcgov** [comment]
complete. Over to @MissionT for testing.

**Comment by MissionT** [comment]
I tested the calculator on page: Maternity Leave - Top-Up Allowance Information - the calculations are correct: 
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/89031524-ae7a-4f74-9e36-a485243f62d6)
