### ISSUE TITLE
Mat/Pat - Parental leave allowance calculator

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#912]
**User Story**
As an applicant i should be able to estimate my weekly parental leave allowance in the form so that I have a clear idea of what i can expect during my leave and make informed decisions about my leave. 

**Input fields**

1.Your basic pay (bi-weekly, gross) - mandatory, number with 2 decimals
1.Leave Type - mandatory
2.EI Estimate - mandatory, number with 2 decimals
2.Additional Earnings - optional, number with 2 decimals

**Logic**
```
If Standard -
weekly basic pay = bi-weekly basic pay/ 2

75% of your weekly basic pay 
minus
EI Estimate 
minus
Additional earnings received
equals
Weekly gross maternity leave allowance amount

If Extended 
Weekly Extended Allowance = (Weekly Standard Allowance * 35)/61

```
**Acceptance Criteria**

- [x] Applicants can estimate their allowance using the above input fields, following the constraints specified above
- [x] Estimated allowance is calculated correctly using the logic specified above

**Design**
[Mat leave allowance calculator ](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428157&cot=14)

**Comment by Andrew-Vargas-bcgov** [comment]
created new screen for parental top up calc. added adjusted calc feature.
@chriscaldwell-psa can you test this in dev when you get a chance?

**Comment by MeghanStothers** [comment]
@Andrew-Vargas-bcgov I love this work - whenever you're ready, I'd like to demo this at an upcoming sprint review. Give me a holler when you're ready to share initial prototype

**Comment by ayushdamani** [comment]
Tested and verified.
- Tested with both 'Standard' and 'Extended' field values for 'Type of leave'.
- The estimated allowance amount matches the logic.

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov 
Issues found during testing 
- Additional earnings is an optional field, however currently if there is no value in additional field, the estimate is not calculated 

https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-04-25%20at%209.50.09%20AM.mov?csf=1&web=1&e=f7gL3u

- There should be a button to calculate, similar to the design
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/ecb6636d-2d65-41d3-8f7d-3f0f17a27827)

**Comment by Andrew-Vargas-bcgov** [comment]
todo:
write additional field optional.
button to calculate instead of auto calc.

**Comment by Andrew-Vargas-bcgov** [comment]
Reworked logic to only calculate when clicking "Estimate".
Basic Pay, Ei Estimates, and parental leave type are now required for calculations and have unique validation errors.
Additional Earnings are optional

@ayushdamani can you test the new mat/pat allowance calculators.
@fazil-ey Let me know if this looks correct now.

**Comment by chriscaldwell-psa** [comment]
Tested the Parental Calculator: Values: 1,800 EI: 250, Other: 100 - Estimate was 325.00, the math is correct 
Logic: 1,800 /  2 = 900  = 900 * 75% = 675 - 250 = 425 - 100 = 325.00 (Correct)

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov 
The allowance estimate is calculated correctly. 

Can we clear the estimated value field if the form is edited for another calculation? The stale value in the "Estimated top-up allowance" field may cause confusion

**Comment by Andrew-Vargas-bcgov** [comment]
@fazil-ey should work how you want now. Let me know if you want me to do anything else for this.
