### ISSUE TITLE
Mat/Pat: How to link Mat/Pat IDIR user to BCeID/BCSC

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#913]
Explore how do we link Mat/Pat form with the IDIR user. This may have implications for deployment of BCSC and BCeID, therefore should be done before BCeID & BCSC deployment on March 3

**Comment by iman-jamali-fw** [comment]
@T854236 

Context: In Mat/Pat form, a user may start the submission with their IDIR, and then after the leave starts, log in with their basic BCeID or BCSC and should have access to their submitted Mat/Pat form that was originally initiated with IDIR.

**A question is. What are the possible ways, from the ODS side, to link a basic BCeID/BCSC user with their IDIR?**

A BCeID user would have BCeID username, email, and GUID
A BCSC user would have BCSC email and GUID.

**Comment by iman-jamali-fw** [comment]
@T854236 

Did you have a chance to look at the last comment? :)

**Comment by T854236** [comment]
@iman-jamali-fw 

Sorry, I missed this one.  There are emails in the employee demographic endpoint.  Emails associated to employees are office email addresses.

Are the email addresses associated to BCeID and BCSC associated to office email addresses?

**Comment by iman-jamali-fw** [comment]
@T854236 

I don't think so. They can choose any email when signing up. BCeID doesn't even verify the signup email. Is there a way to link IDIR based on BCeID or BCSC GUID?

**Comment by iman-jamali-fw** [comment]
@fazil-ey 

Here are my findings for this explore ticket, with a small Chatgp touch to improve my English  :)

To link an IDIR user to BCeID and BCSC, all accounts should be registered using the same email associated with the IDIR account. Fortunately, it's possible for users to edit their email address in both BCeID and BCSC if they already have an existing account. To ensure a seamless linking process, we recommend asking Mat/Pat users to either create a new BCeID or BCSC account using their IDIR email, or if they already have an account with a different email, to change the email associated with their account to match their IDIR email address. This will allow for a smooth integration between the different systems and simplify user management.

**Comment by T854236** [comment]
@iman-jamali-fw

BI source of truth for emails are with payroll information.  It would not hold all personal email addresses unless it was shared within the payroll system.  I agree, if they can sign in using the work email address, that should work.

**Comment by fazil-ey** [comment]
@iman-jamali-fw Ultimately the goal is to make it as seamless as possible to link the account. Most people would have to create a new account with the gov email or update the email. 

If have the same email is the requirement, then we need to do some thinking on how the workflow would be for users to link (maybe its not in the form & in the login page?) , and if it needs to mandatory. We can work it out with the team next sprint!
