### ISSUE TITLE
Plan for deployment of BCeID/BCSC integrations

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#914]
BCeID/BCSC integrations have implications for the current IDIR and Telework users, requiring attention and efforts to deploy and monitor the potential issues. I suggest we deploy all the changes to PROD except for the BCeID/BCSC actual integration in Keycloak in one step and deploy the rest along with the 1.10 form two weeks after. This would give the team the to ensure the stability of the platform and capture potential issues with IDIR users before a new form (1.10) with its users land on the system.

**Deployment on Feb 17-18**
Changes for deployment:
- Changes to IDIR username
- Restoring current IDIR users' submissions/drafts after the change of username. **This would require downtime of the system of up to one day.**
- Form access
- New workflow that supports the new IDIR username
- Synk vulnerabilities updates
- New login page

**Deployment in the first week of March**
- Integration of BCeID/BCSC in PROD keycloak
- 1.10 Form deployment to PROD

**Comment by MeghanStothers** [comment]
Iman gave an update: implications on deployment and he suggest two deployments 1) to make sure IDIR users end of next week 2) first week of March bring into Key Cloak - enable users to login and have the 1.10 form deployed
