### ISSUE TITLE
BCeID & BCSC Deployment(1/2) on Feb 17-18

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#915]
**Changes for deployment:**

Changes to IDIR username
Restoring current IDIR users' submissions/drafts after the change of username. This would require downtime of the system of up to one day.
Form access
New workflow that supports the new IDIR username
Synk vulnerabilities updates
New login page

**Comment by iman-jamali-fw** [comment]
I'll be doing the deployment on Friday 17th evening and will let the team know when deployment to PROD is done.

The PROD will likely be down for 4 hours. Please let me know if Friday 5-8 pm works @MeghanStothers .

**Comment by MeghanStothers** [comment]
Success! You did it - thanks for the after-hours work and Stella for testing and oversight.

**Comment by Stella-Archer** [comment]
Hi @T854236  Could you check to see if our TESTs from Friday nights PROD deploy sent data to the ODS? Application numbers:

**Comment by T854236** [comment]
@Stella-Archer 

We only see Application ID# 34107 in PROD.  Is that expected?

**Comment by iman-jamali-fw** [comment]
@T854236 
These applicationIds were sent to ODS, could you please verify that? Thank you

34106
34107
34103
34100
33149
34115
34099
34113

**Comment by T854236** [comment]
@iman-jamali-fw @Stella-Archer 

Hi Iman, I confirm the ones you listed is already in the data warehouse or in ODS.

**Comment by Stella-Archer** [comment]
Yes sorry Patrick they have not gone through manager approval so won't be in ODS yet

**Comment by MeghanStothers** [comment]
241 records gone - 88 completed reported by Iman

**Comment by MeghanStothers** [comment]
no issues to report - Iman noted we can close. Data in the ODS. Safe to close
