### ISSUE TITLE
SL: Review: Make Sure the form is compatible

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#916]
Some dev research/review required to ensure that SL Review form will be compatible with other form/related updates functionality

**Comment by fazil-ey** [comment]
Tested by @bhumin-fw and no issues found

**Comment by fazil-ey** [comment]
Stella & Eddie to test on Prod

**Comment by MeghanStothers** [comment]
Stella does not see this ticket in prod - decision to do this testing after those other SL tickets are done: Decision about retention and how the workflow ends. Needs answers from Jodi when we are ready.

**Comment by Stella-Archer** [comment]
Hello @Andrew-Vargas-bcgov could you add the client team to a security group so they can access & QA the test version of SL Review form: https://digital-journeys-test.apps.silver.devops.gov.bc.ca/form/63471cbc842f42ecdafecc4b
Martha Wood 
Roberta Turton
Eduardo Ramirez
Anita Bawa
Jodi Little

**Comment by Andrew-Vargas-bcgov** [comment]
Form seems to be functioning properly.
