### ISSUE TITLE
Keycloak statefulsets spin up pod issue

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#923]
In ticket [#771](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/771) we needs to change statefulsets and restart keycloak pods to add new theme for login page.

During restart we noticed that it spin up only one pod and other pod keeps restarting, It failed with postgres driver error.
![Screenshot 2023-02-13 at 10.01.48 PM.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/ce05b3ce-847b-4757-9801-e7252894ddd2)

Note: It can be resolve by taking a look at log in detail but all other error start after on line "Stopped Driver service with driver-name = postgresql".

And just to verify that it's not an error with the new change that we want to merge. 
We have checked out Prod statefulsets for keycloak and found the same issue occurred since the last update of openshift on 3rd Feb 2023. 
![kc-prod.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/7ef3ad13-22a7-4bae-8968-318dae66412b)

**Comment by iman-jamali-fw** [comment]
Fixed on TEST.
Will try to fix the PROD during the deployment to PROD, this evening.

**Comment by iman-jamali-fw** [comment]
Fixed on PROD.

The workaround was to set Keycloak replicas to 0, wait for the pods to be terminated, and set replicas to 2 again.
