### ISSUE TITLE
110 Form: Launch Plan March 10

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#924]
As a program area team, we want to ensure we have connected all the requirements from the workstreams: technical, communications, security, privacy.
**Technical**
- [x] functional 
- [x] tested 
- [x] ready for launch

**testing***
- test with LDB before March 17

**Communications**
- [x] Careers & MyHR content
- [x] Log in Page
- [x]  service desk Comms for service BC (Document C)
- [x]  Digital Journeys mail box standard text for BCCS/BCeID (Document D)
- [x]  Review DS comm plan

**Security**
- [x] STRA
- [x] SOAR

 **Privacy**
- [x] PIA

**Comment by Stella-Archer** [comment]
**Technical**
-[ ] functional 
-[ ] tested 
-[ ] ready for launch

**Communications**
-[ ] Careers & MyHR content
-[ ] Log in Page
-[ ]  service desk Comms for service BC (Document C)
-[ ]  Digital Journeys mail box standard text for BCCS/BCeID (Document D)
-[ ]  Review DS comm plan


**Security**
-[ ] STRA
-[ ] SOAR

 **Privacy**
-[ ] PIA

**Comment by MeghanStothers** [comment]
Alison confirmed with form owner that LDB team will be ready to launch for March 17. We will need to build in testing access with LDB" into our launch plan. Perhaps the after March 10 and before March 17.

**Comment by MeghanStothers** [comment]
We will lock down changes to content, new functionality on March 3 to have enough time to deploy, test, etc.

**Comment by MeghanStothers** [comment]
At Feb 28
**Technical**
- [ TBD ] functional - part 2 deployment for March 3
- [ ] tested TBD
- [ ] ready for launch

TO DO: Send LDB Lindsey/Don S/Stephanie (Writer) prod link after Friday

**testing***
- test with LDB before March 17
TO DO: End to end test with all authentication methods and user groups (PEA, LDB, regular employees
Date: March 3 start
Involved: Andrew, Chris, Fazil Ayush, writer
Meeting booked for Friday March 3 10 .am. to 12
Bug testing reported/tickets etc.

**Communications**
- [X ]IN PROGRESS  Careers & MyHR content (Meghan/Stephanie has this in progress and will be ready for Thursday)
- [ X] Log in Page (Complete)
- [X ] DONE service desk Comms for service BC (Document C)
- [X ]  DONE Digital Journeys mail box standard text for BCCS/BCeID (Document D)
- [ X]  DONE Review DS comm plan (approved by BCID services team

**Security**
- [DONE ] STRA - Security vulnerabilities complete and approved 
- [] SOAR - Ask Igor
 
 ****Privacy**
- [ ] PIA** BceID - Question for Nass

**Comment by MeghanStothers** [comment]
	Add/link the permanent URL for the 1.10 form on PROD: 
https://digital-journeys.apps.silver.devops.gov.bc.ca/form/6402aeb21268f904ebba2c5d

Added to Careers & MyHR content

**Comment by MeghanStothers** [comment]
PIA signed with all signatures and sent to files

**Comment by MeghanStothers** [comment]
@Stella-Archer we will need to clear the environment before launch. I have created two tickets for regular ongoing maintenance, although this task will need to be done before March 17 launch. Let's connect about best timing for this

**Comment by MeghanStothers** [comment]
@Iman let's decide a time to make these pieces live on Friday morning.
