### ISSUE TITLE
PROD issue - Possible issue with the new SSL Certificates

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#928]
There is an issue for PROD users when logging in to the website or Camunda.

Error get when logging in to Camunda:
![Screenshot 2023-02-15 at 8.58.52 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/c54f3f77-1a4d-4600-8f91-c78a0f21255e)

Error get when logging in to Website:![Screenshot 2023-02-15 at 8.59.00 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/4d3952c2-f8b5-428a-9205-470bb06760f9)

**Comment by warrenchristian1telus** [comment]
The SSL certs have been rolled-back, and system access has been restored. We will work to reimplement tonight.
