### ISSUE TITLE
Mat/Pat - Confirmation on form submission

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#929]
**User Story**
As an applicant I want to see a confirmation page on form submission so that I can be confident that my form was submitted successfully and I am informed of the next steps

**Design**
Eligible - [Confirmation](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428166&cot=14) 
[Not eligible](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545585428175&cot=14)

**Acceptance Criteria**

- [x] On form submission, applicants must see a confirmation page with the content specified in the design  for both eligible & not eligible

**Comment by fazil-ey** [comment]
The confirmation page is not in the right place in the tabs
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/3f9cfd13-db9d-4b69-b622-4117e68d0187)

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov - use the same one copy for employee resubmits. 

I will create another ticket for supervisor confirmation.

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov - use the same one copy for employee resubmits. 

I will create another ticket for supervisor confirmation.

**Comment by Andrew-Vargas-bcgov** [comment]
Updated formatting of these pages to look more in line with the miro board prototype and flipped conditions to prevent unreachable ineligible condition.
Will send PR in the morning

**Comment by ayushdamani** [comment]
Confirmation page is looking great; matches content on Miro board.
