### ISSUE TITLE
Mat/Pat - Form Validation and additional logic for parental leave allowance  

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#932]
[Parental Leave allowance](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764543687588215&cot=14) 
  - Mandatory field
  - If taking mat leave AND the option selected is not the same as the option in mat leave then 
          - show form validation error saying `Your selection must be the same for both parental and maternity leave`
 - _(Update May 5)_ If "I do not want to claim allowance is selected" then none of the following allowance screens should be shown
     - Parental leave - top up allowance type, Parental leave - top up allowance dates, Deferred allowance dates

[Parental leave allowance info](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764545710539313&cot=14)
- covered in #912 
- Add [info popup](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/c06d5689-0e2e-4ac8-b7a2-e07dff157cc1) that has instructions for calculating basic pay _(updated April 12)_ 

> **Instructions to calculate gross basic pay**
>
> In your paystub, **ADD** all of the line items present in your pay stub from the following list. It is okay if you do not have all of the line items listed below in your pay stub, just add the ones that are present. 
>
> 1. Regular Hours Paid Earnings 
> 2. Salary Protection 
> 3. Classification Adjustment
> 4. Temporary Market Adjustment (AMA Market Adjustment)
> 

- Add info popup that shows screenshot of EI estimation screen to help people find where the estimate is [Maternity & Parental leave EI Estimate Popup](https://bcgov.sharepoint.com/:w:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/MatPat%20EI%20Estimate.docx?d=wdbc274396c5c43c9abbb204dd8ebca1c&csf=1&web=1&e=pu1etp)
~- Add tooltip for additional earnings `to be decided`~ _Not needed, updated Apr 12_

[Parental Leave Allowance Selection](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764546117417168&cot=14)
   - "Which top-up allowance option will you choose?"
      - Mandatory field
  - If an applicant is taking extended leave and their leave length is not the full leave i.e 61 (if taking mat leave) or 63 (if not taking mat leave) then show alert warning (yellow box) saying 
      - `Some employees choose standard allowance with extended leave to maximize their earnings during their leave. Learn more in the information box below`

[Parental Leave Allowance Date Selection](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764546117417169&cot=14)
   - "When do you want to receive your top-up allowance?"
      - Mandatory fields
      - Must be valid dates
      - Start and end dates must be within the start and end dates of the parental leave
      - After dates are input, the info box should show the type of leave, number of weeks and start & end dates selected. 
      - Form validation for number of weeks 
          - If taking standard leave, number of weeks should not exceed 35 weeks
          - If taking extended leave, number of weeks should not exceed 61 weeks 
          - Change validation error message according to the leave type `You cannot claim more than 35 weeks of allowance`

**Comment by Andrew-Vargas-bcgov** [comment]
just need popup copy and image to complete.

**Comment by chriscaldwell-psa** [comment]
I will need to connect with Andrew when he returns to discuss more info about this ticket. The logic does not seem to work when we confirm if both the Maternal and Parental leave options are not the same.  Ayush indicated that this test was not a pass either.  Chris

**Comment by Andrew-Vargas-bcgov** [comment]
Chris caught that the error is only for deferring allowance and now for consistency across all choices. @fazil-ey do you want a different error message for picking yes receive top up allowance in one leave and picking no top up allowance in the other leave?

**Comment by fazil-ey** [comment]
Sorry for the late response @Andrew-Vargas-bcgov  It should be consistent for all options!

**Comment by MeghanStothers** [comment]
Iman to connect with Bhumin to continue work - there might be some technical complexity.

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 
This is ready for testing on TEST. The popup issue should be working on the Mat/Pat form.

**Comment by ayushdamani** [comment]
Tested in TEST environment ✅
Parental leave allowance:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGlOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ccc07c94b5fb30f94ca626f2d608c5615567eabb/Screenshot%202023-09-12%20041548.png)

Parental leave allowance info:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWlOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb100836991a22b2ce1fc4fd9b152cafd1b5550d/image.png)


Parental Leave Allowance Selection:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWVOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e8287cd09c2a5b42e0e262df68c35a6856e1f124/Screenshot%202023-09-12%20042430.png)

Parental Leave Allowance Date Selection:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckNOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a279ac2ccb2a452f5ab9a30cae7bf8d3ec9ef0e2/Screenshot%202023-09-12%20042850.png)

**Comment by fazil-ey** [comment]
This was not implemented, splitting into another ticket #1315

> If an applicant is taking extended leave and their leave length is not the full leave i.e 61 (if taking mat leave) or 63 (if not taking mat leave) then show alert warning (yellow box) saying
> Some employees choose standard allowance with extended leave to maximize their earnings during their leave. Learn more in the information box below


Allowance popup functionally implemented, but content for EI is not implemented Splitting into #1316

> Add info popup that shows screenshot of EI estimation screen to help people find where the estimate is Maternity & Parental leave EI Estimate Popup

We want to add start and end dates of the leave to the allowance dates page as per the [v3 designs](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764553143184516&cot=14). so splitting to another ticket
