### ISSUE TITLE
Cold/Flu - Requirements & Process Map

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#933]

**Comment by MeghanStothers** [comment]
Waiting for the business requirements and process maps. Estimated date to begin this work is Wednesday March 22 after 1.10 form launch.  See Stella's Miro board for latest program area planning/timelines.

**Comment by MeghanStothers** [comment]
Meeting set up for Mach 6 with the form owner to go over timelines, requirements (process maps and requirements) expect March 22.
