### ISSUE TITLE
1.10 : Content updates in the form 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#935]
@MeghanStothers  to attach the list of changes

**Comment by MeghanStothers** [comment]
[https://app.zenhub.com/files/439477060/4a8cc07b-e1e4-4714-893a-066273c638cb/download](https://app.zenhub.com/files/439477060/4a8cc07b-e1e4-4714-893a-066273c638cb/download)

**Comment by MeghanStothers** [comment]
Attached are the final/approved content changes as discussed with form owner and DJ team. Changes to be completed the week of Feb 27 with final content in place by March 3 [https://app.zenhub.com/files/439477060/dfd69726-6543-4bb0-9aa6-5b2b98d9e4b8/download](https://app.zenhub.com/files/439477060/dfd69726-6543-4bb0-9aa6-5b2b98d9e4b8/download).

**Comment by MeghanStothers** [comment]
[https://app.zenhub.com/files/439477060/8edb64b5-23c9-4666-9181-ffbab9f086a0/download](https://app.zenhub.com/files/439477060/8edb64b5-23c9-4666-9181-ffbab9f086a0/download)

**Comment by MissionT** [comment]
I will use the above link to apply the changes to the form on Monday Feb 27th ( to allow room for any possible changes between now and then). I have this task booked in my calendar. Thanks Chris

**Comment by MissionT** [comment]
Final edits to the Bullying Form 1.10 as per the edits provided via the link above are now complete. I am waiting for an updated URL for one of the links that I asked Don S for. Andrew is looking into updating the confirmation emails for both LDB and PSA (in the Camunda BMP Model).

**Comment by MeghanStothers** [comment]
Keep open until all changes are locked down.

**Comment by Stella-Archer** [comment]
Suggested additional comment for instructions: ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/4b4ed006-b43b-4860-bb18-9b208b35f85c)

**Comment by MeghanStothers** [comment]
Waiting for Don's approval on final line to go into the information and instructions section (see screenshot above) for placement: 

This information gathered in this form is will remain private and strictly confidential

**Comment by chriscaldwell-psa** [comment]
Both the dev and test envs have been updated with a 3rd bullet: "Information gathered in this form will remain private and strictly confidential" - under the Information and Instructions section.  This ticket can be closed.

**Comment by MeghanStothers** [comment]
approved
