### ISSUE TITLE
TOOL: Can't log out of PROD, missing parameters

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#939]
Background: when I try to log out of the PROD environment I get and error
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/d7c2541c-de80-48ed-92f9-860e8493de61)
 
Steps to Reproduce:
log into PROD hit the 'sign out' button
above message appears
 
Actual Behavior:
 parameters missing message appears
Expected Behaviour:
normal log out
 
Environment:
PROD

**Comment by Stella-Archer** [comment]
@matbusby-fw and @iman-jamali-fw could you check out this bug and give us an estimate?

**Comment by fazil-ey** [comment]
Explore to see if its to do with identity provider or key cloak. likelihood of occurence is low since it only happens when switching between identify providers.

We also have a workaround - clear cache or use incognito window

**Comment by fazil-ey** [comment]
We will tackle this if we get complaints about this. Closing for now.
