### ISSUE TITLE
"Make this form public?"

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#940]
Hide the "Make this form public" checkbox, so a forms designer cannot inadvertently check this.

**Comment by bhumin-fw** [comment]
@ayushdamani @Stella-Archer 
"Make this form public?" field hide. Changes are up on DEV and TEST environment.

**Comment by MeghanStothers** [comment]
ready for deployment

**Comment by MeghanStothers** [comment]
Andrew tested and this works. Okay to close
