### ISSUE TITLE
Mat/Pat: Update Tab Names

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#947]
For **v2** the tab names should be - 

1. Before you begin
2. Employee information
3. Alternate contact information
4. Maternity leave
5. Maternity leave - General information
5.1. Maternity leave - Start date
6. Maternity leave - Length of leave information
7. Maternity leave - Length of leave
8. Maternity leave - Top-up allowance information
9. Maternity leave - Top-up allowance
10. Parental leave
11. Parental leave - Partner's information
12. Parental leave - General Information
13. Parental leave - Leave type and length of leave 
13.1 Parental leave - Start date 
14. Parental leave - Top-up allowance information
15. Parental leave - Top-up allowance
16. Parental leave - Top-up allowance type
17. Parental leave - Top-up allowance dates
16. Deferred allowance dates
17. Supervisor information
18. Review 
19. Certify and Submit

**Comment by chriscaldwell-psa** [comment]
Completed.

**Comment by fazil-ey** [comment]
Length of leave tab name is not consistent with the ticket
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/9e4e3c81-7e54-45b1-b8e9-2a69b41aba36)

**Comment by chriscaldwell-psa** [comment]
I have updated the the following tab (Maternity leave- Length of leave) to: ![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/1113cca6-7b80-460e-9ae6-87345019559b)

**Comment by ayushdamani** [comment]
Tested and verified working in Test ✔️
-  Maternity leave - Length of leave is now Maternity leave - Length of leave information

![Screenshot 2023-05-16 084748.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/ead41c2a-c530-490c-87e7-a31339f1763d)

**Comment by fazil-ey** [comment]
In test environment - the following tab names don't match 
- Maternity leave - Length of leave information - (Maternity leave - Length of leave)
- Maternity leave - Length of leave - (Maternity leave - Duration)
- Maternity leave - Top-up allowance information - (Maternity leave - Top-up allowance) 
- Maternity leave - Top-up allowance - (Maternity leave - Allowance) 

![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/3b9eaa92-a39a-4784-b70e-6850120fb9a5)

**Comment by fazil-ey** [comment]
Looks good!
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/ad86b635-8a39-4c11-a1b0-50bb44c9917d)

![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/57494d7f-74ba-45c7-a9bf-129b698f93dc)
