### ISSUE TITLE
Upgrade to the latest version of forms-flow-ai

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#951]
As of March 2, forms-flow-ai is two versions ahead of DGJ.

The latest release info can be found [here](https://github.com/AOT-Technologies/forms-flow-ai/releases).

A new version (5.1.1) was released on May 18, 2023.

Some of the new features are:
- Most of the dependencies (packages and libraries used under the hood) will be updated. This will check many security vulnerability boxes and will bring better performance among other things.
- Added form versioning
  - Allow forms to be versioned. This will allow us to track and manage form versions. Also, a form designer can decide if the updated form (the last version of the form) should be effective for all the in-progress submissions or only new ones.
- Draft discard
  - We already have this feature, but opt-in for the form-flow-ai implementation would allow easier future updates and better maintenance. 
- PDF templating
- Added form embedding
  - This will allow embedded DGJ in another website. Can be useful if a client wants to include a DGJ (which has their form) in their own website

**Comment by iman-jamali-fw** [comment]
The next release in June appears to be an excellent choice for scheduling an upgrade, particularly since it includes the release of the micro front-end.

**Comment by iman-jamali-fw** [comment]
@bhumin-fw @Andrew-Vargas-bcgov 
upgrade app is ready for testing - feel free to pull the upgrade branch and have it running on your local.

**Comment by fazil-ey** [comment]
upgrade is complete, testing this in #1249

**Comment by fazil-ey** [comment]
upgrade is complete, testing this in #1249
