### ISSUE TITLE
Mat/Pat - Ensure there is no gap between maternity & parental leave dates 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#952]
**User Story**
When a supervisor or applicant edits a leave start date, then it should be ensured that there is no unintended gap between maternity and parental leaves. 

**Acceptance Criteria**
- [ ] if there is a gap between the maternity leave end date and the parental leave start date then there should be a popup warning before submission in the review page for both supervisor and applicant
 
> We noticed there is a gap of [_X_] days between the end of your maternity leave [_date_] and the start of your parental leave [_date_]. Please review the dates to ensure they are correct. If incorrect, please edit the dates before submission. 
>
> Maternity Leave starts on [_date_] and ends on [_date_]
> Parental leave starts on [_date_] and ends on [_date_]
> Parental leave allowance starts on [_date_] and ends on [_date_]
> 

**Popup example** - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDE1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6d8439812f99cadff11147f12b4255864c47f699/Screen%20Shot%202023-09-07%20at%2012.01.01%20AM.png)

**Comment by MeghanStothers** [comment]
A simple "warning" solution before submissions to address the majority of the problem around leave dates - avoid processing errors

**Comment by iman-jamali-fw** [comment]
@fazil-ey 
Based on our conversion, can you confirm if this is what we want for this ticket? Please add if I'm missing anything.

If there is a gap, we want a warning pop-up when the employee or supervisor clicks submit (initial submit/resubmit/validate). It's nice to take the user to the review tab.

**Comment by iman-jamali-fw** [comment]
@ayushdamani @fazil-ey 
Mat/Pat gap is ready for your test on TEST.

Test instruction:
If there is a gap between mat and pat leave a popup will be displayed to let the user know. When the user clicks to submit the form for the first time. The user clicks OK, and the second time, the submission goes through.

Consider testing different cases such as when it's a mat-only form/pat-only form/mat+pat with or without allowance etc. Good luck with the testing :)

**Comment by ayushdamani** [comment]
Thank you for adding the test instructions, Iman!

Tested in the test environment with different cases like Iman recommended. The pop up is displayed when a gap exists between the mat and pat dates.

Sorry I am unable to post screenshot due to an error.

**Comment by fazil-ey** [comment]
Works as expected
