### ISSUE TITLE
1.10 Completed Form Retention

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#958]
1.10 Form submissions currently do not remove from the DGJ platform after completion. This ticket can specify and implements this retention period. 

AC:
Find out the retention period.
Add the retention to the 1.10 complete form submissions to be removed from DGJ.

@MeghanStothers  @morezooomm 
Could you please let me know how many days 1.10 submissions should be kept in DGJ before getting removed? The telework form has 60 days.

**Comment by MeghanStothers** [comment]
@iman-jamali-fw 60 days is the maximum unless there are business reasons why this period should be extended.

**Comment by morezooomm** [comment]
I am good with 60 days.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

Government confidentiality and privilege requirements apply to this message and any attachments.  If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately, and delete this message and any attachments from both your inbox and deleted items folder.
***@***.***

**Comment by MeghanStothers** [comment]
Excellent - thank you.

**Comment by iman-jamali-fw** [comment]
@Andrew-Vargas-bcgov @Stella-Archer 

This is ready for testing on TEST along with changes to the workflow that Andrew sent me.

For easier testing, retention time is set to 50 seconds (instead of 60 days). The submitted form under the `Submitted Forms` tab, should be removed 50 seconds after emails are sent.

**Comment by Andrew-Vargas-bcgov** [comment]
Tested and working as intended.
