### ISSUE TITLE
1.10 mailbox for PROD and Non-PROD

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#959]
LDB and PSA mailboxes for completed 1.10 submissions are the same in PROD and non-PROD environments.

@morezooomm 
Do you want to have a separate mailbox address for submissions sent in PROD and non-PROD environments?

**Comment by morezooomm** [comment]
The mailboxes for PSA and LDB are the same, regardless of the environment.  Cheers!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

Government confidentiality and privilege requirements apply to this message and any attachments.  If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately, and delete this message and any attachments from both your inbox and deleted items folder.
***@***.***



From: iman-jamali-fw ***@***.***>
Sent: Monday, March 6, 2023 11:11 AM
To: bcgov/digital-journeys ***@***.***>
Cc: Smallwood, Don PSA:EX ***@***.***>; Mention ***@***.***>
Subject: [bcgov/digital-journeys] 1.10 mailbox for PROD and Non-PROD (Issue #959)

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


LDB and PSA mailboxes for completed 1.10 submissions are the same in PROD and non-PROD environments.

@morezooomm<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmorezooomm&data=05%7C01%7CDon.Smallwood%40gov.bc.ca%7C968282959d4d46c9b58108db1e768c91%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638137266726611168%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oyxpmpHndZeKaeDNr6D5tyRP6OAUaKOoZUnhLoy23%2F0%3D&reserved=0>
Do you want to have a separate mailbox address for submissions sent in PROD and non-PROD environments?

**Comment by iman-jamali-fw** [comment]
Thank you @morezooomm 

This ticket can be closed as no further action is required.
