### ISSUE TITLE
TOOL: UI fixes

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#96]
**Actual Behavior:** 

1. Navigation tab bar options are not displayed properly.
![DJtabOptionsNotShowing.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/06ed375e-e5c4-46a1-ba08-42b2e29b9df8)

 ![DJtabOptions2.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/6d6a9cdd-73ab-4669-a2cc-8bc6a201d28f)

2. The cell alignment is not aligned properly.
![DJcellAlignmentOff.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/33f2cd05-0444-4736-b048-5cd3f96706bd)

3. Applications tab display errors:
![DJapplicationsTabUI.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/cd4ec424-084e-48f2-b46c-6888be922da2)

4. Admin tab:
![DJadminTabUI.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/c93b7a0d-5f31-49e6-9c46-4562607efc15)

5. Clicking on Task options make them invisible to the user:
![tasks.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/5a96ea66-7a8b-490b-b164-112c9f7f9cf7)

6. Form button text is not properly aligned
![formButtons.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/b8b0b35c-9524-462b-a579-3cba87bc6b98)

7. Inconsistent padding/spacing, e.g. Status column "New"
![application history.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/5ebd3efd-5b59-440c-b5b2-c21c8e273a93)

**Comment by HasanSifat** [comment]
Current considerations-
1. Only Forms and Tasks tabs will be visible to form reviewers
1.1- Forms tab to show forms accessible to a certain user
1.2- Tasks tab will only show tasks to be carried out by a user with a status message in the left pane to show "Pending/Approved/Denied"
1.3- Forms tab should have the option to make a new submission and view previous submissions besides each form available to a certain user

2. Current test and dev environment have all historical submissions available to any/all users coming into the environment. The tasks tab has submissions that have no relation to a new user coming in. Forms tab gives access to all available forms in that particular environment. 

3. The Prod environment has a bug where new users coming into the task tab in the environment as reviewers get an "Unauthorized" error and has no info filled out from the submission of the employee. The manager's section is also not visible. Ticket#292 has been created to address this issue

**Comment by MeghanStothers** [comment]
Stall to QA

**Comment by alexandralloyd** [comment]
1. Still present in all three environments.

2. Still present in all three environments.

3. Still present in all three environments.

4. Fixed in all three environments.

5.  Still present in all three environments.

6. Still present in all three environments.

7. Inconsistent padding/spacing for Application ID column in all three environments.

**Comment by Abuchana** [comment]
#6 is the only issues left outstanding and only affects the forms designers and can live with it
