### ISSUE TITLE
Prod IDIR login stalling/failing

### ISSUE THREAD

**Issue by Andrew-Vargas-bcgov** [bcgov/digital-journeys#961]
When logging in with IDIR using Edge, on PROD, the authentication hangs on https://logon7.gov.bc.ca/clp-cgi-preLogon.cgi 
or fails with a 400 - bad request.
![image.png](https://images.zenhubusercontent.com/63bf02395e70d816edf8df36/0c001194-1182-460b-a89b-2b5bf4e29d01)

Client users see the /forms page, but the forms list is empty despite having access to 1.10 and telework forms. If the user navigates to a different tab and back, the forms will show back up.

**Comment by Andrew-Vargas-bcgov** [comment]
Might be related to IDIR login issues happening today: https://chat.developer.gov.bc.ca/channel/sso?msg=7zjFqoutZLmmMdBom

**Comment by fazil-ey** [comment]
This occurs only when someone is inactive on the login page for more than 10 mins. They can refresh the page and login again. This issue is not a blocker, but good to keep it on our radar

**Comment by iman-jamali-fw** [comment]
We looked into the login timeout issue and discovered it happens after 3 minutes. But, we can't change that because it's set and enforced by the BC gov OIDC for IDIR, BCeID, and LDB.

Basically, if you're on the login page of IDIR, BCeID, or LDB for more than 3 minutes, you might see this error.

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 
If we want to make a change to that expiry time (3 minutes) or the error message we should contact the BC GOV OICD team. Please let us what you think.
