### ISSUE TITLE
Mat/Pat : Handle cases when mailing address is empty

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#963]
Mailing address is needed for send hardcopy of pay advices during leave as people lose access to the pay systems

**AC**
- [x] Use mailing address not home address in employee information
- [x] If mailing address is empty in employee info then we can use home address & inform via a validation message under the field 
"Your mailing address was unavailable in our database, therefore your home address has been used. See instructions below to update mailing address"

**Comment by Andrew-Vargas-bcgov** [comment]
Need to add Mailing Address to our API. We currently only have access to Home Address. I have left Home Address as the autopopulate until we add the additional field, and then I can easily set up the logic with hidden fields.

**Comment by Stella-Archer** [comment]
@bhumin-fw will update this

**Comment by Stella-Archer** [comment]
need user who doesn't have office address - then need home address - ask Patrick for reference

**Comment by bhumin-fw** [comment]
In response you will get **officeAddress** and **address**. Default we are displaying **address** as **Mailing address**.

**"address": "119-3501 Dunlin Street, Victoria, V9C 0P7",**
"address1": "119-3501 Dunlin Street",
"address2": " ",
"postal": "V9C 0P7",
"city": "Victoria",
**"officeAddress": "810 Blanshard St, Victoria, BC, V8W 3E1",**
"officeAddress1": "810 Blanshard St",
"officeAddress2": " ",
"officeCity": "Victoria",
"officeCountry": "CAN",
"officePostal": "V8W 3E1",
"officeStateprovince": "BC"

**Comment by jerry-ey** [comment]
Thanks Andrew for detail, put this here as more reference.
---

> office address is physical location of their in-person work place. 810 blanchard for me is my in-person worksite
> mailing address is where we should send mail to when they are on leave.
> home address is their current home address.
> Home and mailing address can be different, so we need to get the mailing from peoplesoft.

**Comment by Andrew-Vargas-bcgov** [comment]
@T854236 will be adding mailing address.
Then we can check the value and show home address + alert instructions if we do not have one.

**Comment by Andrew-Vargas-bcgov** [comment]
Added alert box, hidden mailingAddress field, and conditions to display mailing/home address depending on availability.
left to do: map mailingAddress field in employee_data model to allow auto-populate once it is added by Patrick.

**Comment by T854236** [comment]
@Andrew-Vargas-bcgov 

Hi Andrew, mailing address information added to employee demo endpoints.

**Comment by ayushdamani** [comment]
Tested with Andrew in TEST 
The validation message can be now seen ✅

**Comment by fazil-ey** [comment]
Tested validation message. Closing it as Andre and Ayush have tested it

**Comment by Andrew-Vargas-bcgov** [comment]
@mikeshi-bcgov 
Will you please move over these new fields to the telework production?
mail_address1	
mail_address2	
mail_city	
mail_country	
mail_postal	
mail_stateprovince

**Comment by mikeshi-bcgov** [comment]
@Andrew-Vargas-bcgov sorry, Justin will deploy changes tomorrow March 12th with CRQ1928913

**Comment by mikeshi-bcgov** [comment]
@Andrew-Vargas-bcgov 
Confirm these have been deployed to production already.

**Comment by Andrew-Vargas-bcgov** [comment]
@mikeshi-bcgov Thanks! These are now available in production.
