### ISSUE TITLE
SL Review: Automate adding Names to Keycloak and assign group

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#964]
To import ADM into our system, it requires to have their account in Keycloak. After creating an account in Keycloak, we can grant access to the required group(in our case, it's "SL-REVIEW-ADM").

Prepare an API that will accept multiple users as input. Now create an account and grant access to them for the "sl-review-adm" group.
Note: 
The API can be triggered by
1. Local script with the help of a Designer token.
2. Using Postman(or same API collections) with help of Designer token.
3. (Future enhancement) Attach API with the UI and allow specific users to upload bulk user s data and assign them to a specific group.

- [ ] Prepare an API to import users.
- [ ] API is restricted to FORM DESIGNER only (It is accessible using Form Designer token only).

**Comment by Stella-Archer** [comment]
Adding the list of SL leaders names is managed in ticket #717
