### ISSUE TITLE
[1.10 ]: Contact information corrections

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#966]
**User Story**

As a complainant I want to contact the correct groups so I can get resolve questions and issues. however neither the PSA nor LDB provide accommodation assistance 

**Tasks**
* [x] remove PSA contact info for accommodation assistance
* [ ] Remove LDB accommodation contact info
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/8ef04f42-4275-4fc3-a6fe-6ef27a653494)

**Acceptance Criteria**
referenced contact information no longer is available when users click the 'contact us' button

**Comment by Andrew-Vargas-bcgov** [comment]
Complete.
