### ISSUE TITLE
1:10 Confirmation email message to form recipient

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#968]
As a person/supervisor who has been notified about someone who has filed a 1.10 form to report bullying harassment, I would like to have a clear understanding of my role, as well as the next steps I should take 

A/C:
Replace the current message:
You have been named as the recipient by the person submitting the attached bullying / misuse of authority complaint under article 1.10 of the collective agreement. Please contact your Employee Relations Specialist (ERS) at the Public Service Agency (PSA) for advice on how you should proceed.

With this one:
The person submitting the attached complaint on bullying between peers / misuse of managerial/supervisory authority (under article 1.10 of the collective agreement) believes you can help resolve the complaint, but **the complaint is not against you.** 

Here’s what you need to do next:
•	You must keep all matters regarding the attached complaint **strictly confidential** and must not share it with others. 
•	Before taking any steps, please **contact your Employee Relations Specialist (ERS)** at the Public Service Agency (PSA) for advice on how you should proceed. PSA has already received a copy of the complaint at the same time it was sent to you.
•	If you do not know who your ERS is, **contact PSA.RegistrarIntake@gov.bc.ca**and an ERS will be promptly assigned to help you with next steps.

email address is PSA.RegistrarIntake@gov.bc.ca

LDB version:

The person submitting the attached complaint on bullying between peers / misuse of managerial/supervisory authority (under article 1.10 of the collective agreement) believes you can help resolve the complaint, but **the complaint is not against you.** 

Here’s what you need to do next:
•	You must keep all matters regarding the attached complaint **strictly confidential** and must not share it with others.
•	Before taking any steps, please **contact your LDB Employee Relations Department at the Liquor Distribution Branch** (LDB) at employee.relations@bcldb.com for advice on how you should proceed. LDB has already received a copy of the complaint at the same time it was sent to you.

**Comment by Andrew-Vargas-bcgov** [comment]
@MeghanStothers  Do you want this message for both the PSA and LDB versions? Can you provide an LDB version if there are different requirements?

**Comment by Andrew-Vargas-bcgov** [comment]
@MeghanStothers @morezooomm Updated the bpmn model in test to add new recipient email copy.
PSA:![image.png](https://images.zenhubusercontent.com/63bf02395e70d816edf8df36/78dba221-5f5c-4e15-b9d7-881b7161aaf0)

LDB:![image.png](https://images.zenhubusercontent.com/63bf02395e70d816edf8df36/fca0dcdc-dbf0-4760-a01b-3623b8027536)

**Comment by MeghanStothers** [comment]
@Andrew-Vargas-bcgov I have an updated LDB version to be added as below: 
The person submitting the attached complaint on bullying between peers / misuse of managerial/supervisory authority (under article 1.10 of the collective agreement) believes you can help resolve the complaint, but the complaint is not against you. 
Here’s what you need to do next:
•	You must keep all matters regarding the attached complaint strictly confidential and must not share this information with others.
•	The LDB Employee Relations Team has already received a copy of the complaint at the same time it was sent to you.
•	A representative from the Employee Relations team will contact you to discuss and advise you on how to proceed. 
•	Before taking any steps, please wait for LDB Employee Relations to contact you. To inquire on the status of the complaint or to follow up, please contact LDB Employee Relations at employee.relations@bcldb.com.

**Comment by Andrew-Vargas-bcgov** [comment]
@MeghanStothers Here is the updated LDB email: ![image.png](https://images.zenhubusercontent.com/63bf02395e70d816edf8df36/9f159b13-e5c1-4c5c-bdaf-194712de4a45)

**Comment by MeghanStothers** [comment]
Looks good - ready to test

**Comment by MeghanStothers** [comment]
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/5dfc7336-5a36-42b5-a15e-0c21bb6f8a62)

**Comment by MeghanStothers** [comment]
Still need to test the LDB confirmation message

**Comment by morezooomm** [comment]
I just ran a test and the LDB content on the email to the recipient looks good.  Thanks.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

Government confidentiality and privilege requirements apply to this message and any attachments.  If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately, and delete this message and any attachments from both your inbox and deleted items folder.
***@***.***

**Comment by MeghanStothers** [comment]
okay to launch
