### ISSUE TITLE
1.10: form content fixes

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#969]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
?As a <user role> I want <this action> so I can get <this value>.? 

**Tasks**
add an 'n' after 'know' should be **known**
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/2dd6d387-a897-47d6-99a2-c28759ba77fc)

**delete space between 'complaint' and the period in the recipient contact info section**
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/4a9afbf5-06af-409d-92d1-efe71d6afdf8)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/ea707547-c777-4269-af2f-681a10a81f34)

**Comment by chriscaldwell-psa** [comment]
Typo has been fixed in test env. Will upload test to dev once other ongoing edits are made. Chris 

[Ticket969SmallSpellingError.jpg](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/4f86e21f-6a3e-44f1-8e62-290ed93b4668)

**Comment by chriscaldwell-psa** [comment]
Gap between text has been removed. 
![969GapFixed.jpg](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/ac6cf0bc-0730-44b2-8ab2-95e5cb320f98)

**Comment by Stella-Archer** [comment]
**UPDATE!!!**
@chriscaldwell-psa  could you fix this befor we deploy this afternoon?
Please update the privacy bullet:
Current wording:  Information gathered in this form will remain private and strictly confidential

NEW wording: **Information gathered in this form is private and strictly confidential and will only be shared with those directly involved in resolving your complaint**

**Comment by chriscaldwell-psa** [comment]
@Stella-Archer Both the dev and test envs have been updated with the latest bullet changes.

**Comment by Stella-Archer** [comment]
thanks @chriscaldwell-psa this looks great - moving to 'to deploy'
