### ISSUE TITLE
[1.10]: Remove Pronoun field

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#971]
**User Story**
As a complainant I do not want to feel I must need to reveal my gender to make a complaint .

**Tasks**
* [ } remove the pronoun field in the 1.10 complaint form
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/4a9501c3-3048-4d74-9828-d1bc88997562)

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.

**Comment by chriscaldwell-psa** [comment]
Pronoun component removed  as per the following standards: 
![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/057ff5d1-c581-4ef3-ab9d-0d32a072ddc9)
Below are the changes: ![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/157a4f84-5366-4a49-83b7-dfacdb3e2907)
