### ISSUE TITLE
TOOL: EY regular clean-up of old form submissions 

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#974]
As a dev team, we want to clean up old submissions, drafts and unused data in database.

**Tasks**
() establish a regular maintenance cycle 

**Acceptance Criteria**
() follow established cycle and remove outdated submissions

**Comment by iman-jamali-fw** [comment]
All the unused forms, workflows, applications, submissions, and drafts are deleted from TEST and DEV environments, and clean up documentation was added [here](https://github.com/bcgov/digital-journeys/blob/main/docs/cleanup-environment.md)

**Comment by Abuchana** [comment]
@iman-jamali-fw and @Stella-Archer, how does this ticket differ from #973? If it doesn't, can you delete the lesser of the 2?

**Comment by iman-jamali-fw** [comment]
From the dev perspective it has been done as part of the SL and cold/flu launch and steps to clean up for the future are documented [here](https://github.com/bcgov/digital-journeys/blob/main/docs/cleanup-environment.md)

Unless you want to set up a recurring cleanup, this ticket (technically) can be closed.
