### ISSUE TITLE
Manager unable to approve a telework form or complete one (March 13th) 

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#976]
Background: We have received 2 emails from managers. One manager cannot approve a form, another  manager cannot fill one out. 
 
Steps to Reproduce: Look up supervisors inside the system. 
 
Actual Behavior:  cannot approve a form, another manager cannot fill one out. 
 
Expected Behaviour: as per usual steps for a telework form process
 
Environment: prod

**Comment by chriscaldwell-psa** [comment]
[https://app.zenhub.com/files/439477060/212cf62f-7c54-42ec-a605-452f0b6b846c/download]

**Comment by iman-jamali-fw** [comment]
This issue was caused by the new SSL certs integration. @kkapoor-fresh foxed the issue.
