### ISSUE TITLE
Improvement to Submission Success Message

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#980]
Currently, the message only checks for Form.io success submission before displaying the success message. However, it doesn't consider successful triggers of Camunda workflow.

To improve our system's accuracy and prevent potential issues, I suggest that we modify the success message to only display if the Camunda workflow is successfully triggered. This change will allow us to catch issues earlier and ensure that all necessary steps are taken to process the request.

**Comment by MeghanStothers** [comment]
Extra comments from Fazil/Iman/Warren at grooming: Users could expect to see 3-4 or more (20) seconds to show that this workflow process is underway.  

Could we look at different ways to handle this one?

Chris noticed when testing Telework and has advised users o submit a new form as an interim solution.

**Comment by fazil-ey** [comment]
If the workflow is not triggered we delete the form itself and send back the error. So this is resolved now and is no longer an issue. 

So even if the workflow is not triggered we will still see an error. Closing.
