### ISSUE TITLE
Incorrect link: In Instruction and information section

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#981]
As a form filler, I would like be directed to a a specific page on Careers & MyHR to get more information (from the highlighted link below) 
 
![image.png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/aee88f44-df58-4687-8336-bb085b0c0a15)

**Comment by MeghanStothers** [comment]
@chriscaldwell-psa can you please change this link from this one:https://www2.gov.bc.ca/gov/content/careers-myhr 

to this one:

**Comment by chriscaldwell-psa** [comment]
Done - like dinner. All good. :)
