### ISSUE TITLE
1.10 : Post Launch Content update

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#985]
Current content in “**Before you submit**” bullet reads: “You may ask your union representative at any time for an update on the status of a review or investigation arising from your complaint” 

It should read: “**Starting 10 days after your submission, you may ask your union representative for an update on the status of a review or investigation arising from your complaint**”  

Note this new wording should filter through the confirmation messages and emails as well, and it applies to both PSA and LDB versions of the form/confirmation message/emails

**Comment by chriscaldwell-psa** [comment]
The 3rd bullet in has been updated with new text as per above in the prod env.  I also made that changes to 3 confirmation emails in the Camunda BMP. I would like permission by one of the devs to upload the bmp model to deploy in prod. I'm not comfortable deploying to prod without  informing the dev team.  @iman-jamali-fw

**Comment by iman-jamali-fw** [comment]
@chriscaldwell-psa 

If you haven't already, I'd suggest making the changes to the form and workflow in TEST and if everything worked as expected, do it in PROD. Should be OK

**Comment by chriscaldwell-psa** [comment]
will do

**Comment by MeghanStothers** [comment]
Sent email to Don requesting he looks at this in test and, once approved, we'll move it to prod.

**Comment by chriscaldwell-psa** [comment]
I'll reach out to Andrew to see where this pop-up message is in the Camunda BMP model. I will work on this with him. Thanks for catching this!! Chris.

**Comment by Andrew-Vargas-bcgov** [comment]
@Stella-Archer ready on test.

**Comment by Stella-Archer** [comment]
Looks great! thx

**Comment by Stella-Archer** [comment]
LIVE in PROD
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/841e2df0-82f5-45e1-a763-4476babb5f3a)
Looks great PO Approved & Closed
