### ISSUE TITLE
Cold/Flu: Instructions, Orientation Information

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#989]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
“As a cold and flu clinic worksite register I want start the registration process with orientation information choices so I can easily select my worksite for registration.” 

**Tasks**
* [x] Add Title: **2023 Influenza Worksite Registration**
* [x] Add orientation instructions: 
Registration for the 2023 Flu Clinic Program is now open. Please update your worksite information.
If you have any questions or need assistance, please contact us at cold.flu@gov.bc.ca or call 236-478-2046.
Thank you from the BC Public Service Agency
If you cannot find your worksite or are having difficulties registering your worksite, contact the Workplace Health & Safety Branch:
Phone: 250-952-0446 Email: cold.flu@gov.bc.ca
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/1d5bb9b3-fe97-4118-828c-4a4c66ef9048)

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.

**Comment by chriscaldwell-psa** [comment]
The tasks are now completed.

**Comment by Stella-Archer** [comment]
I've updated the contact phone number at heathers recommendation to 236-478-2046
there was a discussion about the repetition of contact info but i love it in the blue alert box @chriscaldwell-psa

**Comment by ca-liu** [comment]
Hi @chriscaldwell-psa,

Thanks again for getting this started! Nass and I made some changes to the mockup (attached)[https://app.zenhub.com/files/439477060/cfe4963d-a25c-4abb-a830-3029c97646db/download].

High level summary of changes
- Screen 1: Added Ministry Dropdown
- Screen 2/4: Redesigned address selection / display
Updated contacts (phone number) fields
Added secondary contact radio buttons

- Screen 3: Added email icon for contact in Registered Clinics for Worksite

Happy to provide a walkthrough of our mockup if needed.

**Comment by ca-liu** [comment]
Hey @chriscaldwell-psa, 
Quick note, for the form title and introduction, could we please ensure that the year is dynamically displayed? I.e. if I am viewing the form next year, it should say "2024 Influenza Worksite Registration"

- Title: **{year} Influenza Worksite Registration**
- Introduction: 

> Registration for the {year} Flu Clinic Program is now open. Please update your worksite information.
> If you have any questions or need assistance, please contact us at cold.flu@gov.bc.ca or call 236-478-2046.
> Thank you from the BC Public Service Agency
> If you cannot find your worksite or are having difficulties registering your worksite, contact the Workplace Health & Safety Branch:
> Phone: 250-952-0446 Email: cold.flu@gov.bc.ca

const today = new Date();
const yyyy = today.getFullYear();

Thank you!

**Comment by iman-jamali-fw** [comment]
> Hey @chriscaldwell-psa, Quick note, for the form title and introduction, could we please ensure that the year is dynamically displayed? I.e. if I am viewing the form next year, it should say "2024 Influenza Worksite Registration"
> 
> * Title: **{year} Influenza Worksite Registration**
> * Introduction:
> 
> > Registration for the {year} Flu Clinic Program is now open. Please update your worksite information.
> > If you have any questions or need assistance, please contact us at [cold.flu@gov.bc.ca](mailto:cold.flu@gov.bc.ca) or call 236-478-2046.
> > Thank you from the BC Public Service Agency
> > If you cannot find your worksite or are having difficulties registering your worksite, contact the Workplace Health & Safety Branch:
> > Phone: 250-952-0446 Email: [cold.flu@gov.bc.ca](mailto:cold.flu@gov.bc.ca)
> 
> const today = new Date(); const yyyy = today.getFullYear();
> 
> Thank you!

A hidden field called `year` was added to the form that can be used throughout the form.

**Comment by chriscaldwell-psa** [comment]
@iman-jamali-fw  re dynamic year required with form name. Thanks for the note. I will look into this. Chris

**Comment by chriscaldwell-psa** [comment]
Done. PO approved. Chris
