### ISSUE TITLE
Tools: Display name on draft and submission list

### ISSUE THREAD

**Issue by bhumin-fw** [bcgov/digital-journeys#997]
We have set up the display name for three forms manually in the code. For every new Form, we have to prepare one ticket that adds a display name on the draft and submission list.

- [ ] Add a Form hidden field, which carries the display name. It will allow the form designer to add this hidden field at the time of form design and can be changed without any developer's help.

Please find the below image for reference,
![draft-submission-list.png](https://images.zenhubusercontent.com/62e98579ff9c075848ccdb67/330592c4-c965-4443-a45d-582fa5bf1417)

**Comment by fazil-ey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Digital-Journeys-61c10fe84c8bcb001491c5f5/issues/bcgov/digital-journeys/997?planning-poker) with Zenhub @iman-jamali-fw @bhumin-fw @matbusby-fw @Andrew-Vargas-bcgov

**Comment by fazil-ey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Digital-Journeys-61c10fe84c8bcb001491c5f5/issues/bcgov/digital-journeys/997?planning-poker) with Zenhub @Stella-Archer
